rust-lang/crates.io

app/controllers/crate/index.js

Allows users to see a box with the number of downloads for each crate version on a given day instead of examining each data point independently. This helps when multiple versions have 0 downloads on a given day and their chart lines overlap.

Allows users to see download numbers on overlapping lines

---

app/controllers/crates.js
app/mixins/pagination.js
app/routes/crates.js
app/templates/application.hbs
app/templates/crates.hbs

* 'Browse All Crates' links to all crates instead of all
crates that start with the letter A.
* Changing the 'Sort by' param returns the user to the first page.
* Crates pagination only shows the surrounding 9 pages instead
of all possible pages.
Closes #44.

Sort by downloads without letter restriction

---

app/controllers/crate/index.js
app/templates/crate/index.hbs

A bug is causing `versions` to be fetched once for each version causing
excessive queries to slow down or freeze the page.
* Turn versions.length into a computed property to prevent extra
requests
This only happens when you visit from the search. I found this by looking for "hyper" and clicking the first link and experiencing unresponsiveness. I'm not totally sure, but I think this might be a result of having both a `versions` attribute that is null from the search and having a `versions` attribute in `links`.
This could probably be avoided altogether by passing `version_ids` instead of the objects or links in addition to coalescing the requests. If you decide to go that way and need some help on the Ember side I'm more than happy to help implement that.

Use computed property for versions length

---

app/index.html
public/opensearch.xml

So we can search for crates easily from the address bar in Chrome/Firefox/etc.

Add OpenSearch description

---

.travis.yml
README.md
package.json

Makes `npm install` "just work" and doesn't require bower to be installed globally.
npm is clever enough to prepend `PATH` with `./node_modules/.bin` for the postinstall script, which ensures that the right version of bower is used.

Automatically install bower dependencies

---

app/styles/app.scss
app/templates/application.hbs

This should have no effect on the behavior or appearance of the search box, except that it enables features like right-click -> "Add a keyword for this search" in Firefox and other browsers.

Wrap the search field in a <form> element

---

src/krate.rs
src/lib.rs

The route /crates/foo.svg will redirect to shields.io, of an svg showing
the latest version of the crate on crates.io.
Example: [![0.3.7](https://img.shields.io/badge/crates.io-0.3.7-green.svg)](https://crates.io/crates/hyper)
This could be shown in the UI somehow, but for now, exposing a route is quite cheap, and shields.io encourages use like this. A use case is including the badge in the README on github, so visitors can see what is the latest version published, even if master is a little ahead.

add a "badge" route for crates

---

app/templates/application.hbs

I try to tab-select the search box every time I visit crates.io, but other elements such as the 'Fork me' ribbon have priority by default.  This is a simple change that makes things a little bit nicer.
Perhaps as well some other links should have an index assigned to them, but I am not sure which ones to assign or in what order they should be assigned.  Maybe just 'Browse All' and 'Log In', left-to-right, would be enough?

Set the tab index of the search input to 1.

---

app/styles/app.scss

Before | After
------------ | -------------

Fix user links CSS

---

app/routes/crate.js

When visiting a crate that doesn't exist the application uses
`transitionTo` to change the route to the index route. This allows the
user to navigate back to the same missing crate route which breaks the
browsers back button.
* Replace `transitionTo` with `replaceWith` to avoid adding history
entry.
https://github.com/rust-lang/crates.io/issues/141

Use `replaceWith` to transition from missing crate

---

app/controllers/crate/index.js

Crates such as [regex](https://crates.io/crates/regex) have their version numbers wrapping in the graph which shouldn't be happening. Make the graph smaller so it stops happening.
Note: I couldn't test this because no test crates have version numbers high enough to trigger wrap-around. I'm not sure if I'm able to upload to it or if an admin has to do it. Either way, I'd upload a crate with a version number like `42.12.88` (admittedly, a crate with 6 digits might be unlikely...not sure) so the graph can be sized accordingly.
Then I'd change the size so it doesn't wrap.

Make graph version numbers not wrap

---

app/controllers/crate/index.js

Should be good for at least a 100,000 downloads and 5 digit versions without resorting to wrapping. It's shifted because staying centered tends to keep it too far to the right (the diagram stays centered while the legend gets closer to the edge).
Regex crate:

Second try making the graph legend fit without wrap

---

src/krate.rs

Since `ts_rank_cd()` doesn't provide unique ordering using it with `LIMIT ... OFFSET` will lead to inconsistent results, as is apparent from #162. Add ordering by name to break the ties.

In a crate search query, order the results by name in addition to rank

---

app/routes/github-authorize.js
app/routes/github-login.js
app/routes/login.js
src/keyword.rs
src/krate.rs
src/lib.rs
src/user/mod.rs
src/version.rs

This PR adds documentation comments to several route handlers on the front- and backend code.

Add routing documentations

---

.env
app/controllers/crate/docs.js
app/router.js
app/routes/crate/docs.js
app/templates/crate/docs.hbs

Implementation of rust-lang/crates.io#197.

Well-known routes

---

src/app.rs
src/bin/delete-crate.rs
src/bin/delete-version.rs
src/bin/migrate.rs
src/bin/populate.rs
src/bin/server.rs
src/user/middleware.rs
src/user/mod.rs

This PR adds documentation comments to the `user` module.

Documentation

---

app/routes/index.js
app/serializers/crate.js

Resolves the remaining issue in #214

Fix remaining Ember Data problem

---

app/routes/crate/index.js

This might resolve #220 but since I can't reliably reproduce it I'm not sure. In any case it fixes the currently broken download graphs for crate version routes like https://crates.io/crates/libc/0.2.2. 
Sorry about that!

routes/crate: Fix meta.extra_downloads handling

---

src/bin/migrate.rs
src/bin/populate.rs
src/bin/update-downloads.rs
src/keyword.rs
src/krate.rs
src/version.rs

There's a lot of places in the code where there's duplicated hard coded default values for certain tables, or manual updating of things which the database can handle for us (like counter caches and `updated_at`). This updates as many of these cases as I could find to rely on the database when possible. 
We shouldn't require the person adding new code to know that they have to manually increment a counter on another table, or manually set `updated_at` to the right value when they change a row. (As an example of this point, I found that `versions.updated_at` was never actually changed after insert, and several places that it seems we would want `crates.updated_at` to be set, but weren't).
The trigger to update the counter cache on `keywords` will end up performing more queries than what we …

Rely on the database for data things

---

app/styles/app.scss

fix highlight bar going outside rounded corner

---

app/styles/home.scss

The "Getting Started" button was a bit lower compared to "Install Cargo" in Safari.
Tested in OS X 10.11.2 and Safari 9.0.2. Doesn't break in Chrome 47 nor 43.

Fixed unaligned Getting Started button in Safari.

---

app/app.js
app/router.js
app/routes/crate/index.js
app/routes/crate/version.js
package.json

Closes #252, #258, and #261.
Appears to work in all scenarios, hoping somebody else can confirm.

Adding ember-route-alias to handle index routes.

---

src/bin/migrate.rs
src/bin/update-downloads.rs
src/krate.rs
src/tests/all.rs
src/tests/krate.rs
src/tests/team.rs

This column was present both in the table and in the Rust model, but
was only ever used to update the search index on update. The actual
source of keyword info is the crates_keywords table, and it's actually
reasonably easy for this column to get out of sync.
Instead of relying on things calling the `update_crate` function every
time the keywords column is modified, we can instead populate the column
with a subselect which grabs the keywords associated. This also means we
need an additional trigger to touch the crate whenever the
crates_keywords table is modified.

Remove mostly unused keywords column from crates table

---

src/krate.rs
src/tests/krate.rs
src/user/mod.rs

The data is sent properly in this endpoint, but they aren't actually
associated with the crate as the ids aren't present. This appears to be
the only endpoint where these are sideloaded.
I've added a test for this, but haven't visually verified the fix (as I
don't have everything set up to run the backend locally), so this should
be tested on staging before deployment.
Fixes #271

Properly sideload keywords in crates#show

---

app/styles/app.scss
app/templates/application.hbs

(This is just a quick change; haven't tested locally if it looks like it is supposed to.)
I think that the links to the cargo docs are much too hard to find at the bottom of the page. (Especially since you can't find it by searching for "doc".) Neither is the "Getting started" button on the index page a good entry point, since it is only present on that page.
This is kind of what #139 suggests, but without the full drop-down.

Add Cargo guide link to the top nav bar.

---

bower.json
package.json

We recently upgraded ember-data, but not ember itself.
This also removes an unneeded package; it was there for pre-2.0
reasons, but we've upgraded past 2.0.
@wycats , this introduces warnings:
```
DEPRECATION: Support for the `ember-legacy-controllers` addon will end soon, please remove it from your application. [deprecation id: ember-legacy-controllers] See http://emberjs.com/deprecations/v1.x/#toc_objectcontroller for more details.
```
One for views as well. As far as I can tell, none of our code (nor our dependencies' code) uses the deprecated stuff; is this an unconditional warning?

Update ember and remove an outdated dep

---

app/templates/application.hbs

Right now, the textfield tells the keyboard (e.g. on mobile Safari) to provide autocompletion/ autocorrect. Most keyboards/phones don't know words/ terms like "https" or "zlib" which causes an autocorrect for these words. 
This commit disables the autocompletion/autocorrect for the mobile search textfield.

disable autocorrect for the mobile search field

---

app/styles/app.scss
app/templates/components/link-to-dep.hbs
app/templates/crate/version.hbs

Same idea & style as the yanked marker (but not red).
Fixes #233

Show which dependencies are optional on the crate page

---

app/templates/application.hbs

Most people come to the site to search for a package, so why not save them a click or pressing tab once? ;)
On browsers that don't support the autofocus attribute it should just be ignored.

add autofocus attribute to search field

---

app/controllers/crate/version.js
app/templates/crate/version.hbs

Fixes #99.
I would have liked to include a number for how many total dependents there are, but couldn't figure out how to get the actual number. Taking `reverse_dependencies.length` is limited by pagination so tops out at 10.

Add a link to reverse dependencies for crates.

---

app/templates/crate/version.hbs
app/templates/crate/versions.hbs

Fixes #148.
Both paragraphs need to be wrapped in another `div` under `crate-info` since the stylesheet for `crate-info` makes a column-based layout which is not desirable for this case.

Add a backlink to newest for yanked crate versions

---

app/templates/application.hbs

This is what most people are looking for.  Many might not have heard
of the term "manifest".
See also https://github.com/rust-lang/cargo/pull/2587 for the same in the cargo docs.

Doc dropdown menu: name "Cargo.toml" explicitly

---

app/templates/application.hbs

This PR synchronizes the Docs drop down from doc.crates.io to crates.io:
* Added the missing "Specifying Dependencies" link 
* "Using crates.io" has been renamed to "Publishing on crates.io"
(This list should be converted to a shared template in future, I think.)

Add "Specifying Dependencies" in Docs drop down

---

app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs

The titles help blind users and the rel attributes help search engines (in
theory at least).
These also allow users of extensions like vimperator to navigate forwards and
backwards using hotkeys (`[[` and `]]`).

Annotate next/prev page links.

---

Cargo.lock

When running `cargo test` on OSX, I was getting assertion failures in openssl similar to [this issue](https://github.com/sfackler/rust-openssl/issues/303), and I tried all manner of setting openssl-related env vars, `cargo clean`ing, turning around three times and throwing salt over my shoulder, etc, recommended in that issue and others, but the only thing that solved the problem was upgrading the openssl crate. I have no idea which change in openssl solved my issue, but it's gone now!

Upgrade openssl and its dependencies

---

.env.sample
README.md

Hi! I hit a few bumps along my path to getting everything set up and the rust tests passing, so I made these changes to make it a little easier for the next person ❤️ 
- Instead of recommending exporting a bunch of env vars, point out the
convenient `.env.sample` file that can be customized into your own,
personalized `.env` file.
- Reorganize `.env.sample` to have the vars you'd most likely need to
change first.
- Move most of the documentation about the vars into `.env.sample` for
easy reference while editing it.
- Document the need to have the s3 bucket set to `alexcrichton-test`
when running `cargo test` in order to get them to pass.
I think it'd be nice to not have to set the s3 bucket to `alexcrichton-test` to get the tests to pass, but I see a bunch of different solutions possible …

Improve example .env documentation

---

app/initializers/session.js

This shows up in the browser console. Fixed as suggested at:
http://emberjs.com/deprecations/v2.x/#toc_initializer-arity
pssst hi @steveklabnik, this is relevant to #375 :)

Fix a deprecation warning about `initialize` arguments

---

src/bin/migrate.rs
src/krate.rs
src/tests/all.rs

user_id has been replaced with a join to the crate_owners table since
multiple owners was implemented, but the user_id column on the crates
table still had a non-null foreign key constraint on it.
Discovered during the course of working on ✨secret things✨ ; let me know if there's a use for this that I'm not seeing!

Remove obsolete user_id column on crates table

---

Cargo.toml

The new version includes additional license recognized as valid by the SPDX spec.

Update license-expr dependency.

---

app/controllers/search.js
app/routes/search.js
app/templates/search.hbs
src/krate.rs
tests/acceptance/search-test.js

I have updated the crates API endpoint to be slightly more robust to be able to accept both search terms and sorting parameters. I have also updated the front-end for the search results to mimic the "sort by" functionality found on other pages. 
In my opinion I believe this also addresses issue #281

Implemented 'sort by relevance/downloads' for search results

---

src/krate.rs
src/tests/krate.rs

Fixes ordering error in SQL query in crates API. Closes #396.

Fix sort order in crates api

---

.env.sample
src/bin/fill-in-user-id.rs
src/bin/server.rs
src/config.rs
src/krate.rs
src/tests/all.rs

So I've been thinking about/working on making it easier to run a crates.io mirror. The mirror in particular that I'm working on would basically just mirror the crates.io API:
- A cargo user would change their registry index URL in their `.cargo/config` to point to [an alternate index](https://gitlab.com/integer32llc/crates.io-index)
- That index would be a clone of the official index with one extra commit changing the config.json to point to [an alternate crates.io instance](https://cratesio-mirror.herokuapp.com/)
- The crates.io instance would have its `S3_BUCKET` set to `crates-io` and its `S3_REGION` set to `us-west-1`, so it would NOT be mirroring the actual crate files
The problem I hit was that in order to get a redirect from `/crates/:crate_id/:version/download` to S3, the crate …

Remove restriction that a crate must be in the database to get a download URL

---

.env.sample

removing quotes from env sample file

---

app/templates/crates.hbs
app/templates/dashboard.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/index.hbs

Adds titles to pages from #101

adding titles to pages

---

app/index.html
app/routes/index.js
app/templates/head.hbs
package.json

refs #425 
first pass at adding meta descriptions
This PR adds the ember-cli-meta-tags module. It also adds a head template. This is needed when using multiple modules using ember-cli-head which we now are.
There is an entry for the index route to have a meta description tag at `app/routes/index.js`.
This can be added to any route by adding an object:
```
headTags: [{
type: 'meta',
attrs: {
name: 'description',
content: 'cargo is the package manager and crate host for rust'
}
}],
```
this produces:
`<meta id="ember823" content="cargo is the package manager and crate host for rust" name="description" class="ember-view">`
Feedback and thoughts on other page descriptions most appreciated.

adding ember-cli-meta-tags npm package to provide meta descriptions

---

app/components/download-graph.js

Closes #305
Google graphs does not treat 0-values in a stacked area-graph very well.  The default behavior for something like the crates.io download graph is to draw many lines right over the top of eachother, meaning that a recently released version will have its lines drawn over the top of the the other versions.
This can be fixed by passing google graphs a dataset with nulls instead of zeros for areas where the line shouldn't be drawn.
This is an implementation of an algorithm that detects sequences of zeros and removes all the zeroes in the middle of the sequence, replacing them with null.
For example
```
[1, 2, 0, 0, 0, 0, 5, 10, 0, 0, 0, 3, 0, 0]
```
will become (spaces indicate null)
```
[1, 2, 0,  ,  , 0, 5, 10, 0,  , 0, 3, 0, 0]
```
Leaving the boundary 0s makes the graph look …

Massage the data going into download graph

---

app/routes/keyword.js
app/templates/keyword/error.hbs

This is to address issue #436
Follows the same format as the crate not found page for consistency, taken from PR #421 
Example:

Handle keyword not found by flashing message

---

README.md
app.json

I am able to install crates from a heroku instance created using this app.json, at https://cratesio-mirror.herokuapp.com/ !
I have an index mirror at https://gitlab.com/integer32llc/crates.io-index that I'm updating every 10 min. I tested out installing a crate through this index and my mirror server, updating that crate on crates.io, verifying that a `cargo update` does not see the update, waiting until my index fetches the changes, then getting the update with a `cargo update` run after that.
It's still probably not doing what people would expect when they hear "mirror", so I tried to add clear caveats about what this does and does not do right now.
Again, this is a baby step in a series of baby steps I hope to help with, but I think it's a step worth taking! 👣

Add a deploy to heroku button and instructions on running a mirror!

---

app.json

I left a trailing comma in the app.json so the deploy to heroku button doesn't actually work right now i'm sorry i'm sorry this should fix it :(

Remove a trailing comma I left in the json

---

app/styles/home.scss
app/templates/components/crate-list.hbs

fixes #451 
(I could no longer see that crate so I just made up a very long version number)

breaking long words in the crates list

---

README.md

I thought the readme might be better organized to clarify the difference between frontend and backend.
Alongside various stylistic changes, I've done my best to group frontend and backend related comments together.

Readme update for clarity

---

Cargo.lock
Cargo.toml
src/bin/delete-crate.rs
src/bin/delete-version.rs
src/bin/fill-in-user-id.rs
src/bin/migrate.rs
src/bin/populate.rs
src/bin/transfer-crates.rs
src/bin/update-downloads.rs
src/db.rs
src/keyword.rs
src/krate.rs
src/migrate/Cargo.toml
src/migrate/lib.rs
src/user/mod.rs
src/util/mod.rs
src/version.rs

This PR brought to you by `cargo-outdated`.
This upgrades many of our dependencies to the latest versions. Almost all of them are sevmer-compatible, and therefore, have no code changes. One notable difference is `URL`, which I've upgraded from pre-1.0 to post 1.0, which did take some small tweaks.
Here's `cargo oudated` after:
```text
$ cargo outdated
Checking for SemVer compatible updates...Done
Checking for the latest updates...Done
The following dependencies have newer versions available:
Name                         Project Ver  SemVer Compat  Latest Ver
civet->semver                   0.2.3          --          0.5.0
conduit->semver                 0.2.3          --          0.5.0
conduit-cookie->cookie          0.2.5          --          0.3.0
conduit-json-parser->semver     0.2.3 …
```

Upgrade many dependencies

---

app/styles/home.scss

It is currently impossible to view the Just Updated and New Crates list on mobile as they are set to hide at <= 750px and <= 550px respectively. Instead of completely hiding them, I made them wrap at the same breakpoints used right now, so at <= 750px, there are 2 lists per row, and at <= 550px there is only 1 per row now.
Screenshots (after applying the changes in this PR):
At around 750px:
At around 550px:
I would really appreciate if someone can test this out to double check I didn't mess anything else.

Wrap instead of hiding crate list sections on mobile.

---

src/dist.rs
src/util/mod.rs

Fixes #163.
@alexcrichton this is currently untested, but I'd be happy to add a test if you have some guidance.

Assume html if no Accept header is presented

---

script/init-local-index.sh

This change rewrites the message at the end of the script to be more consistent with the README file. The README says to run the script but not to modify the config file until after running. The ending message states these instructions, uses the replace-with key, and provides a URL to the README for convenience. Fixes #471.

Update index creation message

---

app/templates/components/crate-downloads-list.hbs
app/templates/components/crate-list.hbs
app/templates/components/crate-row.hbs
app/templates/crate/reverse-dependencies.hbs

Fixes #331. Thanks to @locks, who knew exactly what the problem was!!!!
On crate list pages, we had *some* data about each crate, but not
keywords. The way the links were constructed, ember saw the partial data
that matched and would use that on the crate page instead of reloading
the whole crate from the crate show api JSON, which *does* have keywords
available. Using the id with the links instead of the whole model forces
the request for all the data to happen.

Use crate.id with links to force ember to load all the crate data

---

app/templates/application.hbs
app/templates/catch-all.hbs

If you search for nothing (click the field and hit enter), it responds with zero results.
Might as well disable it from doing so.

Make search field require input before searching

---

app/styles/crate.scss
app/templates/components/crate-row.hbs

Instead of the plain-text version number.
This has the advantage of quickly showing pre-1.0 (orange) vs. post-1.0
(blue) when scanning down a list of crates.
Since people might want to copy the version number of a crate from the
crate list page, I've changed the alt text of the image to just be the
version number that used to appear here, so that you can highlight the
image and copy the version number.
Screenshot:

Display the version badge on crate list pages

---

.travis.yml

Since we've upgraded the version of postgres crates.io is using in prod, it should use the same version in tests.
This also means the [dist needs to be trusty](https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version).

Update postgres version used on travis to 9.5

---

Cargo.lock
Cargo.toml
app/components/badge-appveyor.js
app/components/badge-travis-ci.js
app/controllers/crate/version.js
app/mirage/fixtures/search.js
app/models/crate.js
app/styles/crate.scss
app/templates/components/badge-appveyor.hbs
app/templates/components/badge-travis-ci.hbs
app/templates/components/crate-row.hbs
app/templates/crate/version.hbs
src/badge.rs
src/bin/migrate.rs
src/krate.rs
src/lib.rs
src/tests/all.rs
src/tests/badge.rs
src/tests/http-data/krate_good_badges
src/tests/http-data/krate_ignored_badges
src/tests/krate.rs
src/upload.rs
src/user/mod.rs
tests/acceptance/search-test.js

This goes with corresponding PR rust-lang/cargo#3546. It probably makes the most sense for this one to go in first.
If a maintainer is testing their project on Travis and Appveyor and so chooses, they can specify attributes for badges for the crate's current build status in its Cargo.toml. 
The badges will then get displayed in alphabetical order on both pages that list crates:
and an individual crate's page:
If any badges other than appveyor or travis are specified, crates.io will ignore them and send back a warning for cargo to display. If the "repository" attribute for either badge is missing, crates.io will ignore that badge and warn about it. If any attributes other than the ones crates.io knows about for each badge is specified, those will get ignored and not warned about.

Add support for showing Travis and Appveyor current build status badges

---

app/controllers/categories.js

We only have 37 top-level categories now, so this will show all
top-level categories on one page for the foreseeable future and make for
a better browsing experience.
Fixes #505.

On /categories, change the # per page to be 100

---

src/categories.toml

We had some inconsistent casing of category names (`Foo Bar` vs `Foo bar`) and people were confused about the difference of `external-ffi-bindings` and `api-bindings`.

Category description tweaks

---

src/krate.rs

I think this is vestigial from 1852499; it doesn't seem to have any effect that I can tell....
r? @alexcrichton

Remove a line that doesn't seem to be doing anything

---

app/templates/categories.hbs
app/templates/category/index.hbs

Fixes #509 whereby category descriptions over 200 characters would be truncated.
Since these descriptions are curated, not truncating them should be fine and won't abuse the UI.

Remove truncate-text helper on Categories page (Fix #509)

---

src/categories.toml

I think a new category for this is justified, because of the large number of crates that belong in there.
Example crates:
For "engine": sdl, skia, ggez, kiss3d, piston-graphics and some of its plugins, the 2 or 3 ray tracing crates, etc. and the numerous bindings to existing libraries in other languages
For "graphics-api": gl, glutin, glfw, glium, gfx and all its plugins, glitter, the 4 or 5 vulkan bindings, the 4 metal bindings, directx, libovr, openvr, etc.
For "data-formats": the 4 crates that parse wavefront, the 4 bindings for assimp, gltf, collada, spine, text-related crates like freetype, etc.
For the base "rendering" category, everything that doesn't fit elsewhere: scene management (gfx_scene), maybe maths crates that have quaternions, frustrums and stuff (eg. cgmath).
I don't …

Add rendering category and subcategories

---

src/categories.toml

Searching (in the browser) for testing in https://crates.io/categories/ does not find anything. Adding testing in the description of "Development tools" helps find the "Development tools/Testing" subcategory.

Add testing in description of Development tools

---

README.md

I just found another useful way to run the frontend without the backend-- don't specify any arguments to `yarn run start`, and it'll use the mirage fixtures!
Figured that could be useful for others to know :)
Also found one remaining use of the `npm` command where it should be `yarn`.

Update the readme: remove an `npm`, add info about running frontend with fixtures

---

app/styles/home.scss
app/templates/components/category-list.hbs
app/templates/components/keyword-list.hbs
app/templates/index.hbs
src/category.rs
src/keyword.rs
src/krate.rs

Fixes #490. 
Below the lists of new, most downloaded, and just updated 10 crates will be the 10 most popular keywords and the 10 most popular categories, plus links to /keywords and /categories. It looks like this:

Show most popular keywords and categories on the home page

---

app/router.js
config/environment.js
package.json

Fixes #529 
Uses https://github.com/dollarshaveclub/ember-router-scroll.
Followed the usage steps given.

Fix #529 - Scroll position is reset when going back in history

---

src/categories.toml

Seems like an odd thing to miss, given how well Rust performs in this area!

Add an "Embedded" category

---

app/components/badge-gitlab.js
app/mirage/fixtures/search.js
app/templates/components/badge-gitlab.hbs
src/badge.rs
src/tests/badge.rs
tests/acceptance/search-test.js

Resolves #537.
I tested this code by modifying `app/mirage/fixtures/search.js` with data from my `gattii` crate, which has Gitlab CI configured. None of the existing projects in this file have gitlab CI, so should I add my `gattii` crate information to this file? If so, is there an easy way to grab this info (maybe a REST call to the real crates.io)?
I know there are badge tests in `src/tests/badge.rs`, but it's all one big complicated test. Should I try to integrate a gitlab badge into that existing test or create a new one? I'm not really certain what to do here that would be best so some guidance here would be helpful.

Add Gitlab CI badge support.

---

README.md

Add more documentation about crates.io's database needs

---

src/categories.toml

There are two major tools that I think deserve this category on their own, `syn` and `quote`. I'm also working on a small helper for parsing attributes inside procedural macros, which doesn't fit into any of the existing categories directly.
@dtolnay have you looked into categories for `syn` and `quote` yet? Would you apply this category (or something similar) if it existed?
I'm not 100% sold on the name, if anyone can suggest a better one I'd be happy to change it.

Add development-tools.procedural-macro-helpers category

---

src/categories.toml

Allows browsing of crates that are `#![no_std]` compatible.

Add a "No standard library" category

---

README.md

Following on #550, these changes separate out the initial backend configuration from the separate paths for hosting crates.io locally and running the backend tests. There's an extra commit in here to remove trailing whitespace as git likes to do that whenever you edit a text file, so I figured I'd include it.

Revise backend documentation

---

app/components/badge-gitlab.js
src/badge.rs
src/tests/badge.rs

Failure introduced in 4ce099b.
Closes #546

Fix intermittent badge::update_crate.

---

app/adapters/dependency.js
mirage/config.js
mirage/fixtures/crate.js
mirage/fixtures/crate_authors.js
mirage/fixtures/crate_dependencies.js
mirage/fixtures/crate_downloads.js
mirage/fixtures/crate_owners.js
mirage/fixtures/crate_reverse_dependencies.js
mirage/fixtures/crate_versions.js
mirage/fixtures/keyword.js
mirage/fixtures/summary.js
tests/.jshintrc
tests/acceptance/crate-test.js
tests/helpers/matches-text.js
tests/helpers/start-app.js

Apparently some behavior around `baseURL`/`rootURL` changed with the ember upgrade, and the reverse dependencies adapter constructs a custom URL that started being relative when it should be absolute. 
I also added a bunch more acceptance tests, which meant a bunch more mirage fixtures, to help us feel more confident about ember upgrades not breaking things in the future :)
I merged and deployed the ember upgrade (PR #501) last night, then I reverted the deploy but not the code today when I saw #553. So no git gymnastics needed, just a merge and then a deploy :)

Fix reverse dependencies page that didn't work after ember upgrade

---

app/models/dependency.js
app/styles/crate.scss
app/templates/crate/reverse-dependencies.hbs
src/dependency.rs
src/krate.rs
src/version.rs

Fixes #495 
I swapped the redundant arrow link on the right for the download count, I don't think anybody used it (?).

Show and sort by downloads on reverse dependency page

---

app/templates/components/badge-appveyor.hbs

Appveyor badges seem to sporadically not load (for me). Previously, it looked like this:
But now, thanks to explicit width and height, it looks at least 42% less shitty:
I took the 106px width from a "build passing" badge. Let's hope the other variants are of that size, too :)
(Might also be a good idea to do that for the other badges.)

Add explicit size to appveyor badge

---

app/components/download-graph.js

The non-stacked scattered chart as a basis reflects the download numbers
correctly. The stacked area chart before was a bit midleading. Both
approaches are a bit "noisy", so I added a 7-day moving average line for
each version number. This gives a higher-level overview and also makes it
easy to see when new versions overtake older ones in usage.
The colors were chosen to be colorblindness-friendly as well as having
a hot-cold metaphor.
Example, the futures crate, before and after:

Add 7-day moving averages to download graph. Plus UI tweaks.

---

app/templates/application.hbs

Update the site to include the email address help@crates.io as described here: rust-lang/crates.io#522 :slightly_smiling_face:

Add contact email address in the footer

---

src/krate.rs
src/tests/category.rs
src/tests/krate.rs

Only show crate once, even if search is like several category #524

---

package.json
yarn.lock

Sigh, I thought I figured out how to include lodash on https://github.com/rust-lang/crates.io/pull/552, and that worked locally, but when i deployed to production, on a crate page only the name of the crate would load before i'd get an error that lodash couldn't be found.
This change is what's recommended by [ember-lodash](https://www.npmjs.com/package/ember-lodash) and I have this PR up on staging right now and [crate pages are loading fine](https://staging-crates-io.herokuapp.com/crates/crossbeam).
r? @alexcrichton

Add ember-lodash to properly include lodash

---

app/styles/app.scss
app/styles/crate.scss

- Add some margin to header nav/menu and mobile search field to keep them away from the edges.
- Set flex-wrap: wrap on name/version heading to wrap rather than overflow (and potentially break layout) when the screen is too narrow. This approach is not the best-looking, but a lot better than doing nothing.
- Add some margin to crate-links sections (Fixes #235 ).
Before:
After:
Before:
After:
For the `#crate-links.section` margin it also applies to the right-most element(s), which is not quite optimal. An alternative solution without this minor issue is shown below, but this unfortunately makes the gray divider line too long, so I've stuck with the simple solution.
```diff
--- a/app/styles/crate.scss
+++ b/app/styles/crate.scss
@@ -313,11 +313,14 @@
padding-bottom: 20px;
border-bottom: 5px …
```

Tweak layout for elements on crate page to fix some small issues with narrow screens

---

src/s3/lib.rs

As noted in https://github.com/rust-lang/crates.io/issues/493#issuecomment-282514820,
the recorded `http-data` in `src/tests` expects "http://alexcrichton-test.s3.amazonaws.com".
But, as the `S3_REGION` env var is loaded as `Some("")`,
it matches wrong leading to wrong host "http://alexcrichton-test-.s3.amazonaws.com".
This fixes it by handling match when region is empty.

fix: incorrect host when running tests

---

src/version.rs

Sort optional dependencies last

---

src/app.rs
src/bin/delete-crate.rs
src/db.rs
src/tests/badge.rs
src/tests/category.rs
src/tests/keyword.rs
src/tests/krate.rs
src/tests/version.rs

There are a bunch of tests which are explicitly casting `&MockRequest`
into a `&Request` trait object, because the extension methods provided
are only on the trait object, not anything which implements the trait.
By changing from `Request + 'a` to `T: Request + ?Sized` (which is more
ideomatic anyway), we can just call the method directly on `MockRequest`
in tests.
The deletion of the `#[macro_use]` line was to get the tests to compile locally. It's an unused annotation which emits a warning on my machine.

Implement request extensions on `T: Request` not `Request`

---

app/styles/app.scss
app/templates/application.hbs

Sometimes when I run crates.io locally, and I'm signed in, I get this
error in the js console:
```
Error: Assertion Failed: Attempted to register a view with an id already
in use: current-user-links
```
Id isn't required for rl-dropdowns, so I changed current-user-links to
be a class instead.
r? @alexcrichton

Change an HTML id used twice into a class

---

src/version.rs

Rebased and deld the pr by accident.  so I resubmitted it.

Fix #467 - Author ordering

---

app/routes/crate/version.js
src/bin/migrate.rs
src/krate.rs
src/tests/all.rs
src/tests/http-data/krate_publish_after_yank_max_version
src/tests/http-data/krate_yank_max_version
src/tests/krate.rs
src/user/mod.rs

Updating columns like this tends to be pretty brittle unless it's done
via a trigger. We can't update this one from a trigger, since PG doesn't
know about semver's comparison rules. Either way, we don't really need
to cache this unless it turns out to be a performance bottleneck. We can
instead calculate the value on the fly.
This does introduce some N+1 queries, and those may end up being a
hotspot. We can definitely get rid of them, but it's a pain in the ass
to do manually and Diesel has support for it built in, so I'd rather
just fix them as we move those endpoints over.

Remove the `max_version` column from Crates

---

Cargo.toml
src/bin/delete-crate.rs
src/category.rs

`EXPLAIN ANALYZE` output (tested assuming `ORDER BY crates_cnt DESC LIMIT 10 OFFSET 0`)
Before:
```
(cost=7129.79..7129.82 rows=10 width=127) (actual time=1.184..1.187 rows=10 loops=1)
```
After:
```
(cost=5.88..5.88 rows=1 width=131) (actual time=0.170..0.171 rows=10 loops=1)
```
About half of the performance comes from removing the `COALESCE`. Since
the subselect is including the `crates_cnt` from the toplevel category
(which is why it doesn't have to add `c.crates_cnt`), so it can never
return null.
The second big win is changing from a subselect to a join. PG is usually
quite good at figuring out when these cases are equivalent, but I
suspect that the use of an aggregate function in the subselect means
that it will actually have to subselect in a loop.
Finally, we avoid using `LIKE`, …

Simplify and optimize `Categories::toplevel`

---

migrations/20170308140537_create_to_semver_no_prerelease/down.sql
migrations/20170308140537_create_to_semver_no_prerelease/up.sql
src/krate.rs
src/tests/krate.rs

So in #592, I accidentally changed the meaning of the
`reverse_dependencies` query from "select 10 crates where the max
version of that crate depends on this one" to "select 10 crates where
that crate had a version with the same number as this one's max version,
which depended on this crate" which is nonsense and wrong.
There's actually no way that we can truly replicate the old behavior
without breaking pagination or loading all the versions of every crate
which has ever depended on another into memory and doing the limiting
locally... which would defeat the purpose of pagination.
The only real alternative here is to revert #592 and go back to updating
the `max_version` column. I still think this approach is the right one,
even with the added complexity to this column, as updating …

Fix `reverse_dependencies`

---

src/bin/fill-in-user-id.rs
src/krate.rs
src/version.rs

This replaces several `mut vecs` with `.collect::<Vec<_>>()`. I get it is a small thing, but it was bugging me. :-)

Remove mut vec

---

src/bin/update-downloads.rs

A not-insignificant portion of our production logs is the update-downloads worker printing the date:
```
Mar 07 11:47:38 crates-io app/worker.1: Mon, 06 Mar 2017 19:47:37 GMT 
Mar 07 11:47:38 crates-io app/worker.1: Tue, 07 Mar 2017 00:00:00 GMT 
Mar 07 11:47:38 crates-io app/worker.1: Mon, 06 Mar 2017 19:47:37 GMT 
Mar 07 11:47:38 crates-io app/worker.1: Tue, 07 Mar 2017 00:00:00 GMT 
Mar 07 11:47:38 crates-io app/worker.1: Mon, 06 Mar 2017 19:47:37 GMT 
```
I think this is printing like... 1000 times every 30 seconds or so. 
In addition to removing log noise, this should hopefully help our papertrail quota stretch a bit farther.

Remove logging of dates from update-downloads

---

migrations/20170308191449_crate_owners_does_not_need_id/down.sql
migrations/20170308191449_crate_owners_does_not_need_id/up.sql
src/schema.rs

`crate_owners` has a primary key column called `id`. This column is
never referenced in the code, and is not the real primary key. All
places that we need to uniquely identify a row in this table, we do so
with a combination of `crate_id`, `owner_id`, and `owner_kind`. Let's
just make this the actual primary key.
Additionally, we don't need a separate index on just `crate_id`, PG can
use the primary key index. We can, however, benefit from a duplicate
index that is scoped to `NOT deleted`, as this lets the query in
`Crate#owners` go from
```
Nested Loop  (cost=0.30..16.41 rows=1 width=200)
->  Index Scan using crate_owners_pkey on crate_owners  (cost=0.15..8.23 rows=1 width=4)
Index Cond: ((crate_id = 1) AND (owner_kind = 0))
Filter: (NOT deleted)
->  Index Scan using users_pkey on users …
```

Remove pointless column and index from `crate_owners`

---

migrations/20170309122510_generate_api_token_with_sql/down.sql
migrations/20170309122510_generate_api_token_with_sql/up.sql
src/bin/update-downloads.rs
src/tests/all.rs
src/tests/user.rs
src/user/mod.rs

There's a ton of code which is setting this field in misleading ways,
and it seems really odd to pass it to `find_or_insert` when it's
completely ignored in the update case. We can just use a database
default for this, and simplify everything a bit.

Use the database to generate API tokens

---

src/bin/delete-version.rs
src/bin/transfer-crates.rs
src/git.rs
src/krate.rs
src/tests/all.rs
src/tests/krate.rs
src/version.rs

On the majority of endpoints involving versions, we're parsing the
version (using `.unwrap` even, which could take down the server) only to
immediately convert it back into a string. This causes needless
allocations, and a larger surface for errors to appear.
We really only care about semver when ensuring a version is valid, and
when determining the max version for a crate. Everywhere else, we can
just use a String.

Don't parse `Version#num` for reads

---

src/bin/delete-version.rs
src/bin/transfer-crates.rs
src/git.rs
src/krate.rs
src/tests/all.rs
src/tests/krate.rs
src/version.rs

Reverts rust-lang/crates.io#610
Fixes #614. I don't think the change is worth keeping given the number of places we're having to add parsing where we do care, I'd rather make these bugs difficult to introduce.

Revert "Don't parse `Version#num` for reads"

---

migrations/20170311180634_remove_semver_index/down.sql
migrations/20170311180634_remove_semver_index/up.sql

It's not actually being used in the reverse dependencies query and
heroku postgres doesn't like it.
I'm seeing these errors in the heroku postgres logs:
```
Mar 10 19:34:13 crates-io app/postgres.8131: [WHITE] [4-1] ERROR:  type "semver_triple" does not exist at character 139 
Mar 10 19:34:13 crates-io app/postgres.8131: [WHITE] [4-2] QUERY:   
Mar 10 19:34:13 crates-io app/postgres.8131: [WHITE] [4-3] 	  SELECT ( 
Mar 10 19:34:13 crates-io app/postgres.8131: [WHITE] [4-4] 	    split_part($1, '.', 1)::int4, 
Mar 10 19:34:13 crates-io app/postgres.8131: [WHITE] [4-5] 	    split_part($1, '.', 2)::int4, 
Mar 10 19:34:13 crates-io app/postgres.8131: [WHITE] [4-6] 	    split_part(split_part($1, '+', 1), '.', 3)::int4 
Mar 10 19:34:13 crates-io app/postgres.8131: [WHITE] [4-7] …
```

Remove the versions_to_semver_no_prerelease_idx index

---

Cargo.lock
Cargo.toml
migrations/20170307211844_versions_yanked_is_not_nullalbe/down.sql
migrations/20170307211844_versions_yanked_is_not_nullalbe/up.sql
src/app.rs
src/badge.rs
src/category.rs
src/keyword.rs
src/krate.rs
src/lib.rs
src/owner.rs
src/schema.rs
src/tests/all.rs
src/tests/category.rs
src/tests/keyword.rs
src/tests/krate.rs
src/tests/user.rs
src/version.rs

I decided to tackle this one next since we have an N+1 queries bug on
the max versions, it's a relatively high traffic endpoint, and the code
benefitted the most from Diesel.
There was probably more code added to support migrating the tests over
than to support the actual `index` function, but all those pieces will
start to get used as more endpoints are ported over. There were a few
tests that were hitting the followings and owners endpoints which I have
temporarily changed to hit the database directly instead.
Porting those endpoints would mean porting over more tests, which might
mean porting over more endpoints, etc. We didn't lose any coverage
overall, but we should still go back to hitting the endpoints directly
in tests when we can.

Port `crates#index` to use Diesel

---

src/tests/krate.rs
src/version.rs

This is draft of fix for issues/557. Inspired by @carols10cents comment I tried to use the same pagination code as is used for the other endpoints.

use pagination for version downloads

---

.env.sample
.travis.yml
README.md
src/app.rs
src/bin/fill-in-user-id.rs
src/bin/server.rs
src/config.rs
src/http.rs
src/krate.rs
src/lib.rs
src/s3/lib.rs
src/tests/all.rs
src/uploaders.rs
src/util/io_util.rs
src/util/mod.rs

This should make working on crates.io LOTS easier, I hope :)
In order to test out stuff with a development instance of crates.io running locally, it's nice to be able to publish to your local instance and see what happens. But currently, crates.io tries to upload crate files to S3 even if you don't have any values in the S3 config vars. I've gotten around this by having a commit that comments out the S3 publishing parts and running that code when I want to publish, but that's pretty annoying.
Instead, with this PR, if you're running locally (the env var HEROKU is not set) and you have not set the S3_BUCKET env var, then when you publish a crate to your crates.io with `cargo publish --host file:///path/to/crates.io/tmp/index-co`, it'll put the `.crate` tarball in `dist/local_uploads`. Then …

Local upload instead of S3 to enable publishing in development

---

Cargo.lock
Cargo.toml
src/badge.rs
src/lib.rs

All of the logic we're using to validate the attributes can be entirely
represented with serde.

Use serde to deserialize badges from the database

---

src/krate.rs
src/tests/krate.rs

Also make the test catch this bug by having slug != category.
Sorry I didn't catch this when reviewing #609, but at least I caught it before I deployed it to production!!!!
Ultimately this is my fault for writing tests that had the same value for the category display name and slug, which isn't what the real data is like, so the tests passed for #609 :(

Fix category query to look up on slug

---

migrations/20170312165531_index_dependencies/down.sql
migrations/20170312165531_index_dependencies/up.sql
src/krate.rs
src/krate_reverse_dependencies.sql

Right now on production the reverse_dependencies endpoint takes around a
second to load. This commit decreases that to ~70ms on my machine.
I've moved the query to its own file to give syntax highlighting and add
comments. The query barely differs from the original though. I've made
two main changes.
The first is using a window function to get the total count instead of a
second query. The second is the addition of `where crate_id =
any(subselect)` when gathering the versions.
Ultimately this query is an intersection between all the max versions,
and the versions which depend on this crate. Prior to this commit, the
query essentially did exactly that. The problem is that even if an index
is used, collecting all the max crates takes ~300ms. This speeds that up
considerably by first scoping …

Optimize the reverse dependencies endpoint

---

app/controllers/dashboard.js
app/models/version.js
app/templates/dashboard.hbs
src/krate.rs
src/tests/all.rs
src/tests/krate.rs
src/tests/user.rs
src/user/mod.rs

Get it? Because this ports the follow endpoints. To Diesel. ...Anyone?
This ports 4 endpoints over to Diesel. The 3 endpoints which manipulate
the `follows` table, as well as the `/me/updates` endpoint since it
is only hit by the tests for the follows endpoints.
I ended up changing the updates endpoint quite a bit. I wanted to
eliminate the N+1 queries on the max version, and was wondering why we
needed the max version at all here. I went to go look at it in the UI,
and it turns out that the dashboard page which displayed it is actually
broken as well. After fixing it, I noticed that it doesn't need the
crates at all, just the name (which we tell Ember is the id).
I couldn't actually find a good way in Ember to reference the ID of an
association without loading the whole thing. If anybody …

Follow the Diesel

---

Cargo.lock
Cargo.toml

Since we're not using `infer_schema`, we don't need to provide a backend
to `diesel_codegen`. This drops the transitive dependency on
`diesel_infer_schema`.

Remove needless feature from `diesel_codegen`

---

src/bin/fill-in-user-id.rs
src/categories.rs
src/db.rs
src/git.rs
src/http.rs
src/krate.rs
src/owner.rs
src/uploaders.rs
src/user/mod.rs
src/util/errors.rs
src/util/mod.rs
src/version.rs

These functions have no reason to take their arguments by value, since
they're just calling `.to_string` on it anyway. Additionally, everywhere
that was passing `format!` can pass `format_args!` instead and skip the
intermediate string

Make the bounds on `human` and `internal` a bit more explicit

---

src/db.rs
src/krate.rs
src/lib.rs
src/tests/krate.rs
src/user/mod.rs

Consider code like the following:
```rust
let conn = req.db_conn()?;
let body = req.body();
```
Since the `body` function requires `&mut self`, this code will fail
since the lifetime of the connection is tied to the lifetime of the
request. These are of course disjoint, but the compiler can't know that.
Really there's no reason to stick the request in `extensions` like we
are. I think the reason the postgres code did it that way was to allow
mocking the connection out in tests, but we just set the pool size to 1.
Additionally, some endpoints (like `crates#summary` are embarassingly
parallelizable, so we should expose the capability for multiple database
connections in a single request.

Don't tie the lifetime of the db connection to the request

---

app/models/dependency.js
migrations/20170315133901_make_dependencies_schema_match_use/down.sql
migrations/20170315133901_make_dependencies_schema_match_use/up.sql
src/dependency.rs
src/schema.rs

Dependencies kind is assigned a default value when deserialized from the
database, and all newly inserted values are given a non-null value.
Let's just give it a default at the database level and mark it not-null.
Additionally, we were storing it as a comma-delmited string but there
was really no reason to do so. It was converted back to a string before
being sent to the front-end, but we converted to/from an array in
between so there was no gain from storing it as a string. Additionally,
the front-end never used it as a comma delimited string (actually, it
doesn't use `dependencies.features` at all unless there's some crazy
metaprogramming that doesn't show up when grepping for "features" and
"featureList")
I honestly can't find any reason in the history that they were stored
this way. I …

Update the dependencies schema to match use

---

src/tests/krate.rs
src/util/errors.rs

Any method in Diesel's API which returns a single record (specifically
`.get_result` and `.first`) treats 0 records as an error case by
default (calling `.optional` on the `Result` turns it into a
Result<Option<T>>`). However, right now if a
`diesel::result::Error::NotFound` is returned, the server will return a
500. We don't test every possible place a 404 can be returned, so this
is never apparent in tests.
The implementation is a bit of a kludge, but I'm not sure that there's a
better way to do this without either requiring nightly for
specialization or significantly reworking the error handling of the
application (I do think that we should eventually do the latter)

Ensure Diesel NotFound results in a 404

---

.travis.yml
Cargo.lock
Cargo.toml
src/app.rs
src/bin/fill-in-user-id.rs
src/categories.rs
src/category.rs
src/db.rs
src/dependency.rs
src/dist.rs
src/download.rs
src/git.rs
src/http.rs
src/keyword.rs
src/krate.rs
src/lib.rs
src/owner.rs
src/upload.rs
src/uploaders.rs
src/user/middleware.rs
src/user/mod.rs
src/util/errors.rs
src/util/hasher.rs
src/util/head.rs
src/util/io_util.rs
src/util/request_proxy.rs
src/version.rs

Adds the ability to run clippy against the project (disabled by default since it requires nightly), and makes all the required changes to make it pass. The failures were mostly to make the code idiomatic, though there were a batch that was due to requiring unnecessary allocations. I plan on enabling some additional lints to make this more pedantic in future PRs, this is just the default set of lints.

Add clippy, make it pass

---

src/badge.rs
src/bin/transfer-crates.rs
src/category.rs
src/dependency.rs
src/keyword.rs
src/krate.rs
src/owner.rs
src/tests/all.rs
src/tests/badge.rs
src/tests/krate.rs
src/tests/record.rs
src/tests/team.rs
src/tests/version.rs
src/upload.rs
src/user/mod.rs
src/version.rs

I regret that this PR had to be so large, but there was a cluster of endpoints that all had to be ported together or we'd lose test coverage. I have kept separate commits that are roughly the size of what I would normally submit as a PR, so I suggest reviewing this that way.

Port `/crates/new` and supporting endpoints to use Diesel

---

Cargo.lock
Cargo.toml
migrations/20170318181441_downloads_need_no_id/down.sql
migrations/20170318181441_downloads_need_no_id/up.sql
migrations/20170322130523_version_downloads_needs_no_id/down.sql
migrations/20170322130523_version_downloads_needs_no_id/up.sql
src/bin/update-downloads.rs
src/download.rs
src/lib.rs
src/schema.rs
src/version.rs

We expect there to only be one entry per crate per date, so let's
enforce that by making it the primary key. Additionally `date` is always
used as a date, so let's make it a date. Finally, there was some dead
code around this table that's been removed

Update `crate_downloads` schema to match use, kill dead code

---

src/dependency.rs
src/krate.rs
src/tests/krate.rs

So that we aren't writing the crate name as its dependencies' names in the git index.
r? @sgrif, there might be better ways to do some of the stuff involving `NewDependency` that interacts with diesel, but idk because the dependencies table doesn't care about the dependencies' names :(

Fixes the code that caused the index corruption today

---

src/krate.rs
src/tests/krate.rs
src/version.rs

Fixes #664.
Also added a test for /crates/:crate_id/versions; that was functioning
correctly before this commit though since it's still calling
krate::versions.
Also added some notes-- I'm not sure why /crates/:crate_id/versions
exists (and I am seeing ember request it) if the version information is
included in the crate show json. I also don't know where or how the
/api/v1/versions endpoint is used, with the `ids=[]` params... I wanted
a reminder to investigate that some other time.
r? @sgrif

Versions should be sorted in semver order in crate show json

---

app/controllers/application.js
app/styles/app.scss
app/templates/application.hbs
tests/acceptance/search-test.js

Hey there, first PR to this project, I hope I did not make too much mistakes.
Most of the code was adapted from rust-doc (wondering if and how I should credit them) to using with Ember, though it doesn't really feel Ember *-ish* it would seem that adding custom events to an entire application isn't. I found some addons that achieved this but I wasn't sure it was worth to add a dependency for one keyboard shortcut.
This functionality required adding an ID to the search bar in order to be able to grab its focus as its name is not unique in the document (the mobile search bar shares the same name 'q').
I also made an acceptance test for this feature.
Fixes #643

Search field keyboard shortcut

---

app/styles/crate.scss
app/templates/crate/version.hbs

As per issue #608 , I've copied the quick-links from crate listings into the header on a crate's detail page.
This required some tweaking to the crate.scss, in order to reuse the quicklink styling, as well as introducing an extra div to keep the layout under control.
I'm certain there are more elegant solutions, feel free to provide tips/tricks/criticism!
I've intentionally made tiny commits, to make it easier to follow my reasoning (for both myself and for others). If you'd prefer everything squashed into a single commit, I'll gladly make one.

quick-links in crate header

---

app/styles/crate.scss

After my insertion of quick-links in Crate headers in #668, the follow-crate button became mis-aligned, which I failed to notice because I wasn't logged in.
Thanks @kureuil for reporting [here](https://github.com/rust-lang/crates.io/issues/608#issuecomment-292310505)
This fixes the alignment by copying the relevant css flex attributes into the new div style that I introduced.

Fix alignment of crate-follow button

---

app/routes/crate/version.js

Currently, when you log in on a page, it would seem only the `session.currentUser` object gets updated. This automatically updates the menu and that's fine for most of the pages. However, on crate/version, `session.currentUser` is used in the template but its value is not watched in the route, which means that the template knows that a user logged in but the route doesn't.
This PR forces the route to reload when the `session.isLoggedIn` value is changed, allowing the route to correctly update the follow button.
Fixes #644

Fix the infinite spinner on the follow button

---

app/styles/_helpers.scss
app/styles/crate.scss

(I have not tried building locally with changes made, just translated working CSS code into @include statements etc, fingers crossed!)
e.g. on this page: https://crates.io/crates/reffers
at the top now "reffers" and "0.4.2" should be baseline-aligned while keeping the image centered.

fix vertical alignment of crate name and version

---

app/styles/app.scss

I just added a base font size, because it seems there is none right now and it results in a weird display on different browser for the inline code. Here is a screenshot of firefox (same with chrome):
You can see the `rustc` and `cargo new` are really smaller and there is no reason(?). I think a base font size for the site may be better. Here is a screenshot with base font-size:
It seems more readable. Sorry if this PR is useless (I'm not sure it's my first PR here and I'm not a CSS master)

Added a base font size

---

README.md

Installation via npm has been deprecated, see 'Install via npm' section
of https://yarnpkg.com/en/docs/install#alternatives-tab for more
details.

Update install step for yarn

---

.env.sample
Cargo.lock
Cargo.toml

Upgrade to dotenv 0.10.0 since that version considers `key=` lines to be valid with a blank value. With 0.9.0, I've seen errors because of the `export S3_REGION=      # not needed if the S3 bucket is in US standard` line, and the errors look like they're saying that the GIT_REPO_URL var isn't set instead, and it's terrible, and this fixes it.
And actually, blank values for the S3 variables still cause the code to use the S3 uploader when I added the whole local uploader thing so that you don't have to deal with all that in development. Silly me though just straight up removed all those vars in *my* `.env`, and I should have commented them out in `.env.sample` as well to make setup for others easier out of the box.
Also just added a commit to put a sample postgres URL nearer to the …

Improve environment variable setup for development

---

README.md
docs/CONTRIBUTING.md
docs/MIRROR.md
script/init-local-index.sh

At a recent OSS event that I helped out with, [we discovered](https://github.com/rust-lang/crates.io/issues/667) that the setup instructions were missing some things and were organized in a confusing way.
I wanted some room to elaborate, so I moved the dev setup instructions and the mirror setup instructions into their own files.
I also removed the instructions that the init-local-index.sh script printed out, since the instructions for setting up cargo there are confusing (ex: you should not put the `.cargo/config` in your crates.io checkout and then try to build crates.io, which isn't clear) and out of date.
Fixes #667.

Organize docs

---

Cargo.lock
Cargo.toml
src/migrate/Cargo.toml
src/s3/Cargo.toml

These changes should make the cargo-registry crate publishable on crates.io, which I want to do to make the docs about crates.io's code available on docs.rs to help people working on crates.io.
This will also involve publishing the crates in src/s3 and src/migrate.

Make crates.io publishable on crates.io

---

migrations/20170430202433_reserve_windows_crate_names/down.sql
migrations/20170430202433_reserve_windows_crate_names/up.sql

These names will break cargo on windows machines if uploaded to
the registry.

Reserve windows crate names.

---

src/bin/delete-crate.rs

When deleting the `nul` crate, I couldn't use the delete crate script for a number of reasons, one being that there were categories and when I added categories I forgot to add deleting them to this script :(

Delete crate script should delete categories and badges too

---

migrations/20170502181306_drop_schema_migrations/down.sql
migrations/20170502181306_drop_schema_migrations/up.sql

We haven't been using this since we switched to diesel;
`__diesel_schema_migrations` manages this now. We left this around just
in case we needed to roll back the switch to diesel in production, but
we're good and switched now.
The existence checks are so that these migrations won't error if people
are starting from a database that either does or does not have a
schema_migrations table.

Drop the old schema_migrations table

---

Cargo.toml
src/s3/Cargo.toml

I forgot to add descriptions [earlier](https://github.com/rust-lang/crates.io/pull/691) :( Not adding a description to the migration crate because [I think we should delete it instead](https://github.com/rust-lang/crates.io/pull/707).

Add descriptions to crates so that they're publishable

---

app/routes/crate/version.js

When a crate does not specify a documentation link, we query docs.rs to know
if the documentation for the requested version was successfully built. If
if is, we set the crate's documentation link to the corresponding docs.rs
page, if not nothing changes.
Fixes #419.

Add docs.rs integration

---

app/styles/crate.scss

Before:
After:
Looks slightly better, IMHO, and Shep said y'all're are open to suggestions.

Remove extraneous left padding from exact match class

---

Cargo.lock
Cargo.toml
src/util/hasher.rs

In order to be able to build successfully without the lockfile, which
happens when verifying with `cargo package` since [package never includes
`Cargo.lock`](https://github.com/rust-lang/cargo/issues/2263).
If we don't constrain these crates' versions, they update to
incompatible versions of, most problematically, serde_json.
openssl has also deprecated the `finish` method and changed some types
in a minor version bump. I don't feel like figuring it out right now so I'm locking it down too :P

Lock down some crate versions; update others semver compatibly

---

src/krate.rs
src/tests/krate.rs
src/upload.rs

Limit crate names to 64 characters

---

docs/CONTRIBUTING.md

Found by @baileyn [over here](https://github.com/rust-lang/crates.io/pull/687#issuecomment-298758541) ❤️ 
Why can't they all have the same names???

Fix pkgconfig name for Fedora instructions

---

src/categories.toml

Gives utilities for build scripts there own category. 
For example a utility which helps you pack resources into your binary can fall into this category.
- is the name ok?
- maybe restrict it to build script utilities only?

Add category for built utils

---

src/badge.rs
src/keyword.rs
src/krate.rs
src/lib.rs
src/tests/all.rs
src/tests/badge.rs
src/tests/keyword.rs

Switch most of badges and keywords to use diesel

---

src/app.rs

Staging was using 20/20, prod was using 122/120, due to the upgrade in r2d2 with this change? https://github.com/sfackler/r2d2/commit/df5eb7422f2b41d5c55d8d93f86c17c073e2d727
This change makes staging use 10/20 on boot and 16/20 after the first request, seems better.

Adjust db connections

---

app.json
src/app.rs

@sgrif I'm trying to test out #730 on staging and I'm overwhelming the db limit of 20 connections there again :( This'll let me set prod and staging differently. I did unify the settings for rust-postgres and diesel though, with the thought that hopefully we'll be getting rid of the rust-postgres connections soon anyway.

Enable setting database pool limits from environment variables

---

Cargo.lock
Cargo.toml
src/badge.rs
src/tests/krate.rs

There was one test failure due to a change in how serde handles null
values going into `HashMap<String, String>`, but other than that this
appears to be a simple migration.

Update to serde 1.0, diesel 0.13

---

app/components/badge-codecov.js
app/components/badge-coveralls.js
app/components/badge-is-it-maintained-issue-resolution.js
app/components/badge-is-it-maintained-open-issues.js
app/templates/components/badge-codecov.hbs
app/templates/components/badge-coveralls.hbs
app/templates/components/badge-is-it-maintained-issue-resolution.hbs
app/templates/components/badge-is-it-maintained-open-issues.hbs
mirage/fixtures/search.js
src/badge.rs
src/tests/badge.rs
tests/acceptance/search-test.js

Adding the badges to address #705 and #706
The badges added are:
Is it maintained: Resolution time
Is it maintained: Percentage of open issues
Codecov: Code coverage
Coveralls: Code coverage

Added badges for Is it maintained, codecov and coveralls

---

src/krate.rs

I appear to have fucked up in #746. The API was sending the detailed
stats for the oldest 5 versions instead of the newest 5 versions,
causing the whole graph to just show "other". This fixes that error.
(as an aside, I kinda prefer just having the whole picture as one stat
like that)

Fix crate/downloads

---

Cargo.toml
build.rs
src/tests/all.rs

While we're running these in the integration tests, they weren't run
before unit tests. Rather than duplicating the logic for this everywhere
that we have a test that interacts with the database, we can just do
this at compile time.
As best I can tell, Cargo doesn't give you any environment variable to
know that you're building for tests and not just a debug build, so I've
set this up to only try to migrate if the env var is present, and not
error in its absense.
Fixes #762.

Migrate test database at build time instead of runtime

---

.travis.yml

This should hopefully fix https://github.com/rust-lang/crates.io/issues/776.
As noted by @carols10cents, `--force` is needed to get the latest version of diesel_cli because [we added cargo caching](https://github.com/rust-lang/crates.io/commit/209dab0f40bbcaa7826188dd3d3ff85b72005ecd#diff-354f30a63fb0907d4ad57269548329e3).

Force Travis to get the latest versions of diesel_cli and rustfmt

---

package.json

This PR cleans up the `package.json` file a little according to the Ember CLI best practices

Cleanup package.json file

---

src/krate.rs
src/tests/krate.rs

The query assumed that if the name was equal to the query string, that
the full text search would always match that crate. This is not true in
the case where the query string is a stop word (words like a, the, just,
which), which are excluded from full text search.
Explicitly adding an or condition to include a crate whose name matches
is always returned solves the issue. We purposely continue to exclude
crates which would only match because their readme contains a stopword,
as this behavior is important for things like stemming to do their job.
Fixes #321.

Ensure exact match crates are always returned by search

---

mirage/fixtures/team.js
src/owner.rs
tests/acceptance/team-page-test.js

The team's GitHub link on the team's crates page was broken when trying to access `/org/org_name/team/team_name`. This could be because not all teams are publicly viewable, so the link was changed to instead go to the organization's GitHub page.

fixing link to github team page via crates team page

---

app/initializers/set-global-promise.js
package.json
tests/.eslintrc.js
tests/acceptance/categories-test.js
tests/acceptance/crate-test.js
tests/acceptance/front-page-test.js
tests/acceptance/search-test.js
tests/acceptance/team-page-test.js
tests/acceptance/user-page-test.js
tests/helpers/has-text.js
tests/helpers/matches-text.js
yarn.lock

as suggested by e.g. https://emberway.io/maintainable-user-interface-testing-with-ember-40f1b58040b6

Use async/await for tests

---

.travis.yml
docs/CONTRIBUTING.md
testem.js

PhantomJS is unmaintained and officially deprecated

Use headless Chrome for CI testing

---

app/controllers/application.js

This is handled by [ember-router-scroll](https://github.com/dollarshaveclub/ember-router-scroll) already
Closes https://github.com/rust-lang/crates.io/pull/824

controllers/application: Remove obsolete scrollTo(0, 0) call

---

app/controllers/crate/version.js

`DS.PromiseArray` is private in Ember Data, but its both dependencies are not so we create our own `PromiseArray` now.

controllers/crate/version: Replace private DS.PromiseArray usage

---

tests/acceptance/crate-test.js

These tests were apparently introduced by https://github.com/rust-lang/crates.io/pull/790 while we were refactoring towards async/await.
/cc @natboehm

tests/acceptance/crate: Use async/await

---

app/adapters/team.js
app/adapters/user.js
app/routes/team.js
app/routes/user.js

`find()` expects to get a record with the same ID that was passed in, but in this case we're passing in a string (login) and receiving a numeric ID causing warnings like:
> WARNING: You requested a record of type 'user' with id 'blabaere' but the adapter returned a payload with primary data having an id of '1'. Use 'store.findRecord()' when the requested id is the same as the one returned by the adapter. In other cases use 'store.queryRecord()' instead
/cc @sivakumar-kailasam

Use queryRecord() instead of find()

---

src/dependency.rs
src/krate.rs
src/tests/krate.rs

Resolves https://github.com/rust-lang/crates.io/issues/306
@carols10cents could you check if this is indeed working as intended? I didn't have any crates in my local env to check and only used the unit tests for verification. Is there some sort of sandbox env that we could deploy this too?
This PR only includes the backend changes for now until we have verified that those work as intended.

WIP: Fix reverse dependencies query

---

app/controllers/dashboard.js
app/controllers/me/index.js
app/routes/application.js
app/routes/crate/version.js
app/routes/github-authorize.js
app/routes/github-login.js
app/routes/index.js
app/routes/keyword.js
app/routes/logout.js
package.json

This prepares the codebase to move to FastBoot. I've tested this with local, staging & live proxy to avoid any issues.
@Turbo87 I'll raise a separate PR when we're ready to get rid of all the destructured imports in favor of modules 😄

Remove ic-ajax in favor of ember-ajax

---

mirage/factories/category.js
mirage/factories/crate.js
mirage/factories/version.js
tests/acceptance/categories-test.js
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/search-test.js
tests/acceptance/team-page-test.js
tests/acceptance/user-page-test.js

Instead of using fixtures it is recommended to use factories to setup acceptance tests. This PR introduces a first set of factories and uses them in a few of the existing tests to simplify them. This PR is not yet converting everything to factories, but can be merged at any point.
@samselikoff would be awesome if you could give this a quick review :)

Start using ember-cli-mirage factories

---

app/routes/search.js

It trims white spaces from search term to provide a more accurate results (Ember takes params as it is, including white spaces)
E.g. right now two similar queries would yield different results due to white space:
"conduit" - gives exact match
"conduit "- gives no exact match
It is a minor thing, but occasionally you can copy-pate name with white spaces and etc...
So might be a bit annoying that it changes your result.
I'm not sure that white space is a legal character for crate's name.

Trim white spaces from search term

---

src/keyword.rs
src/krate.rs
src/lib.rs
src/pagination.rs
src/user/mod.rs

This pattern gets duplicated quite a bit (and it should be duplicated
even more since we still have places where we're doing more than one
query to paginate). Additionally, using the `sql` function will cause a
query to be removed from the prepared statement cache (since Diesel
doesn't know if the string was generated dynamically or not).
This moves it out into a trait, and represents a paginated query in a
bit more of an abstract form from the SQL point of view. This will
slightly change the SQL in the places that it's being used, so that it
looks more like what we have in `src/krate_reverse_dependencies.sql`,
applying the limit/offset as late as possible. This will not affect the
query plan unless they are using `distinct`, or if `limit`/`offset` are
called prior to `paginate`. Even if …

Refactor paginating queries to a trait

---

app/templates/me/index.hbs

Based on the instructions on the [crates.io publishing page](http://doc.crates.io/crates-io.html), these instructions should now refer to the `~/.cargo/credentials` file.

Update publisher token file name.

---

src/category.rs
src/tests/all.rs
src/tests/category.rs

I don't think `tests::categories::update_crate` is testing enough shit. Damn that's a long test. I changed `cnt` to a macro rather than a function so I could see the line that was failing when one of the 100 invocations of it was wrong (otherwise it just gives the body of the function as the line)

Port categories/index and categories/show over to Diesel

---

src/category.rs
src/tests/all.rs
src/tests/category.rs
src/tests/krate.rs

All tests are green on stable and beta, however I think I'm hitting a bug in nightly as I get a segfault on the test krate::index_queries with nightly `rustc 1.20.0-nightly (445077963 2017-06-20)`.
```
$ RUST_TEST_THREADS=1 RUST_BACKTRACE=1 rustup run beta cargo test krate::index_queries --verbose
[...]
running 1 test
test krate::index_queries ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 98 filtered out
$ RUST_TEST_THREADS=1 RUST_BACKTRACE=1 rustup run nightly cargo test krate::index_queries --verbose
[...]
running 1 test
test krate::index_queries ... error: process didn't exit successfully: `/home/jtgeibel/repos/github.com/rust-lang/crates.io/target/debug/deps/all-12d198baf6ed1586 krate::index_queries` (signal: 4, SIGILL: illegal instruction)
```

Switch several category routes over to diesel

---

src/badge.rs

GitLab variant is still renamed manually.

Use serde rename_all = "kebab-case"

---

src/version.rs

This was changed when switching from rustc serialize to serde; ember
expects the key in the JSON to be "crate" but Rust needs the field in
the struct to be named "krate". The tests didn't catch this because we
aren't testing the serialized JSON string at all; a round trip through
JSON totally worked :-/
This breaks the reverse dependencies page-- the name of the dependent crate doesn't show up.
I checked everywhere that has `krate:`; it looks like all the other places have serde renaming appropriately.
Found this while testing on staging before deploying to prod-- @sgrif you around to review?

Rename krate in json to crate

---

docs/CONTRIBUTING.md

The package including postgres' header files was in Ubuntu's list of package but not in Fedora's one.

Installation guide for PostgresQL on Fedora was missing a package

---

migrations/20170711193021_rerename_gitlab/down.sql
migrations/20170711193021_rerename_gitlab/up.sql
src/badge.rs

Sooo I have already deployed #865 to production, but not the revert. This means the migration got run, which means we need to undo it, so I've added it back here with the up/down swapped. It shouldn't affect anyone who hasn't run the reverted migration.
I also cherry-picked the commit from #865 that removes `badge_type`-- that method is indeed still not being used since we switched to serde, so that commit is fine. In fact, not having this is causing small problems because #807 was made between #865 and the revert, and it adds a new badge, so if I merge in #807 that variant isn't in `badge_type`.

Fixup some fallout from the revert of #865

---

app/components/badge-circle-ci.js
app/templates/components/badge-circle-ci.hbs
src/badge.rs
src/tests/badge.rs

Closes #800 
ember-cli seems unhappy with Node 8 that Arch Linux has, so I haven't run frontend tests unfortunately :(
Badge docs: https://circleci.com/docs/1.0/status-badges/

Support CircleCI badges

---

Cargo.lock
src/tests/user.rs
src/user/mod.rs

0.13.1 was a bugfix release that changed `sum` and `avg` to properly reflect their return type. Previously, this endpoint would error if the query was being performed on an empty table.
Fixes #866

Update to Diesel 0.13.1.

---

app/templates/dashboard.hbs

Use the format-num helper to properly comma-seperate the "Total Downloads" count
on the Dashboard page.
Fixes #855

Format dashboard total downloads count

---

src/krate.rs
src/util/errors.rs

Trivial casts were allowed in two places but the code compiles and
passes tests without this attribute.

Disallow trivial casts

---

migrations/20170706165855_dont_touch_timestamps_unless_row_changed/down.sql
migrations/20170706165855_dont_touch_timestamps_unless_row_changed/up.sql
src/bin/delete-crate.rs
src/bin/delete-version.rs
src/bin/populate.rs
src/bin/transfer-crates.rs
src/bin/update-downloads.rs
src/bin/update-licenses.rs
src/categories.rs
src/db.rs
src/schema.rs

I thought we were done, but we're not... I forgot the binaries. Sorry.
:(
This one was pretty straightforward. There's a bit of refactoring in
here as well, and I moved some of the integrity checks that this code
was doing to the database. It's worth noting that the new body of
`set_updated_at` is identical to `diesel_set_updated_at`, but I can't
actually call that function from the other since it's `RETURNS trigger`.
Not sure if it's worth resolving, since the function is unlikely to
change.

Port `bin/update-crates` over to Diesel

---

src/bin/transfer-crates.rs

Redo of #798, learned not to use master for PR's :)

transfer_crates script: switch to GitHub IDs

---

src/badge.rs
src/tests/badge.rs

I added new Badges @carols10cents please review the enums. Thanks!!
And also I had this error =/
https://gist.github.com/marti1125/d2ddda017b9e1c8a4224cf48cc2a42b1

add new badges #704

---

src/krate.rs

See [comment](https://github.com/rust-lang/crates.io/pull/801#issuecomment-313859341).

Better error reporting on invalid upload request

---

migrations/20170708133715_ensure_crate_id_foreign_keys_cascade/down.sql
migrations/20170708133715_ensure_crate_id_foreign_keys_cascade/up.sql
migrations/20170708135123_ensure_version_id_foreign_keys_cascade/down.sql
migrations/20170708135123_ensure_version_id_foreign_keys_cascade/up.sql
src/bin/delete-crate.rs
src/tests/all.rs
src/tests/load_foreign_key_constraints.sql
src/tests/schema_details.rs

I moved nearly all of the behavior from this binary into the database.  We could instead just do exactly what this binary was doing before, but it's a lot of behavior that has 0 tests. I wanted to figure out how best to actually test this as well, since any test which actually attempted to delete the crate would have to insert rows in all of these tables to be useable, meaning it would have to know about every foreign key that exists. That test would be brittle, and likely to get out of date.
By moving this into the database, we can also test that any new columns which point to the crates table have a foreign key, and won't break in the future.
Additionally, I've tested the updated binary locally against an old dump of the database.
If we're concerned about someone "accidentally" deleting …

Port `bin/delete-crate` over to Diesel

---

src/badge.rs
src/category.rs
src/dependency.rs
src/krate.rs
src/token.rs
src/uploaders.rs
src/user/mod.rs
src/version.rs

There are several functions where a QueryResult can be returned instead of the wider range of errors supported by CargoResult.  Basically I just did a single pass through the code and for every function with a `use diesel` I changed the return type and did a `cargo check`.
I'm wondering if there is general support for moving all diesel queries and associated structs into source files under a `model` module.  This is my first pass through the code to start to identify functions that would be candidates for such a module.  On master there are 11 other functions already returning QueryResult.  Then the remaining functions using diesel could be reviewed to factor out the query logic.
/cc @carols10cents @sgrif

Use QueryResult in place of CargoResult where possible and remove some unused code

---

app/routes/crate.js

Ensure model exists before accessing get

---

.travis.yml

Travis is timing out (because of no output for 10 min) trying to install rustfmt (with syntex_syntax) when we're using rustc 1.20.0-nightly (734c83642 2017-07-03) for clippy... but we don't need rustfmt installed when we're running clippy, soooooo let's not

Only install rustfmt when we need it

---

src/dist.rs

We have several routes (notably the download route) which assume they
will be receiving the request regardless of if a JSON accept header was
specified or not. Ultimately if someone is typing `/api/...` into their
browser, they're probably debugging or doing something else for which
they don't want Ember rendering a 404 page.

Never serve HTML for paths starting with `/api`

---

bors.toml

We're gonna try out [bors-ng](https://bors.tech/)! I've got an instance running at https://bors-voyager.herokuapp.com/ but the repo needs this file :)

Add bors-ng configuration file

---

app/adapters/version.js
app/controllers/crate/version.js
app/models/version.js
app/templates/crate/version.hbs

The download button has not been available since pre rust-1.0.  The button was originally commented out in #15 and #18.

Remove unused code for download button

---

docs/CONTRIBUTING.md

Along the lines of #899, we should start mandating doc comments on all new types and functions, and encourage doc comments on modified types. 
Is there a way to check for this in TravisCI as well?

Doc comments on new pull requests

---

docs/ARCHITECTURE.md
docs/BACKEND.md
docs/FRONTEND.md
package.json
src/app.rs
src/bin/server.rs
src/lib.rs

I started this a while ago, but an email from @vignesh-sankaran prompted me to get what I have out there rather than bitrotting on my machine.
I'd love a review of what I have so far, @vignesh-sankaran! What do you think of the outline of the architecture document? What kinds of things would make that document a more useful high-level overview? 
The doc comments should hopefully make the docs at https://docs.rs/cargo-registry/ better, I don't think the little bit I've added here warrants a version bump and publish yet, though.

Start to add lots of documentation

---

migrations/20170728002039_fix_keywords/down.sql
migrations/20170728002039_fix_keywords/up.sql
src/keyword.rs

Background for anyone unfamiliar with crates.io's database schema:
- We've got crates
- We've got keywords
- Crates can have many keywords and keywords can have many crates
- There's a join table `crates_keywords` that contains records associating crate.ids and keyword.ids
This migration fixes invalid data that currently exists in the database. Between
commits d5c563560 and 4c2bd4225, it was possible for keywords to be
created without lowercasing them first. Then, due to this code:
```
pub fn find_or_create_all(conn: &PgConnection, names: &[&str]) ->
QueryResult<Vec<Keyword>> {
// ...elided...
keywords::table
.filter(::lower(keywords::keyword).eq(any(&lowercase_names)))
.load(conn)
}
```
which selected any keywords that matched the given keywords *regardless*
of case and associated these …

Fix keywords that weren't lowercased before inserting

---

.buildpacks
app.json
config/nginx.conf.erb

**Deployment Warning:** This pull request uses a configuration syntax added in nginx-1.7.5 and requires switching to a new buildpack.  ~~If this pull request is merged the buildpack configuration on *staging* and *production* will need to be changed on Heroku.~~  (This is no longer a concern with the updated PR as this is specified in `.buildpacks`.)  It is unclear if there are any existing mirror deployments on Heroku or otherwise depending on our `nginx.conf.erb` template.
This pull request enables HSTS headers for all responses.  My tests show an upgrade from an F to a D on the Mozilla Observatory.  (Out of 100 points, this scores 35 instead of 15.)  Please also see the discussion in #597 which is what prompted my review.
This pull request also fixes the buildpack URLs defined in …

Enable HSTS headers on all responses

---

src/categories.toml

Background: https://github.com/rust-lang/cargo/issues/4368
* <https://en.wikipedia.org/wiki/Internationalization_and_localization>
* <http://www.i18n.ca/publications/GILT.pdf>
* <http://philip.pristine.net/glit/en/>
Almost all libraries that implement Unicode-related functionalities (<https://crates.io/search?q=unicode>), like:
* `unicode-normalization`
* `unicode-bidi`
* `unicode-segmentation`
* `unicode-width`
* `unicode-script`
* `unic`, which covers/will-be-covering all of the above.
* `cldr`
* `accept-language`
* `language-tags`
* `locate-locale`
* `locale`
* `precis`
* `idna`
* https://github.com/servo/rust-icu
There are fewer crates in this category, but still enough to start the category:
* `gettext-rs`
* `litelocale`
* `crowbook-localize`
* `locale`
* `l20n`

[categories] Add internationalization and localization

---

app/styles/app.scss
app/templates/components/category-list.hbs
app/templates/components/crate-list.hbs
app/templates/components/keyword-list.hbs
app/templates/crate/version.hbs
app/templates/crate/versions.hbs
public/assets/right-arrow.svg
src/http.rs
src/lib.rs

These headers are all pretty straightforward except CSP. For CSP I
defined the sources based on what was loaded from visiting the main page
and all crates. Images should be safe, so I've allowed them from all
sources.
This should be checked on staging before deploying.
Fixes #586.

Add security headers

---

build.rs

Helps avoid unnecessarily compiling the main library!

Add dependencies for top-level build script

---

src/user/middleware.rs

I'm a bit worried about the fact that there were not tests which needed
to be updated. It seems like we never actually test the authentication
directly, we always just stub the user into the request.

Use diesel from inside the users middleware

---

src/tests/all.rs

Fixes up #937, which was caused by me not having the `TEST_DATABASE_URL` set i.e. it was `TEST_DATABASE_URL=`. Thanks to Arnavion on the #rust channel for pointing out I could use unwrap_or() to cover both the `None` and `""` cases at once :).

Better error messages for empty string ENV variables

---

docs/CONTRIBUTING.md

Resolves #809 by recommending `nvm` to install `node` and `npm` on Linux

Add steps to avoid sudo for npm and node on Linux

---

config/nginx.conf.erb

Such as the /me route, which can be requested by the browser for its
frontend HTML or its backend JSON, but the browser should not cache
either and return it for the other one.
Fixes #888.
I was able to reproduce the problem with reloading locally when, instead of using `ember serve`, I ran `npm run build -- --environment production` and then served the files in `dist` using nginx. This change fixed the problem! 
@sgrif @jtgeibel do yinz see any reason NOT to set this header for literally any non-asset route?

Add Vary header to prevent caching routes with different content types

---

migrations/20170801133919_touch_crates_when_versions_modified/down.sql
migrations/20170801133919_touch_crates_when_versions_modified/up.sql
src/schema.rs
src/tests/all.rs
src/tests/http-data/krate_uploading_new_version_touches_crate
src/tests/krate.rs

Prior to this commit, if uploading a new version of a crate didn't
otherwise change the metadata (description, etc), the crate's updated_at
record wouldn't be changed.
The migration specifically checks if `updated_at` changed on the
versions to make sure the touch doesn't happen if `downloads` was
bumped. I wanted to avoid duplicating that here, so instead this will
only happen if the row is new, or as a result of the trigger bumping
updated_at on the version.
I have specifically not included a query to correct existing data, as
it's an irreversable operation. We should manually run a query like
`UPDATE crates SET updated_at = MAX(crates.updated_at,
SELECT(MAX(versions.updated_at) FROM versions WHERE versions.crate_id =
crates.id))` if we want to correct existing data.
Fixes #908.
Close …

Touch a crate whenever its versions are changed

---

src/git.rs
src/krate.rs
src/lib.rs
src/upload.rs
src/version.rs

As part of the effort to better document crates.io, I added more documentation comments to the `krate::index` and `krate::new` functions as well as to some associated functions. Also added some comments in some functions and to document. Thanks for providing the background on these functions @carols10cents :).
I'd like to doc comment the git::yank function as well before this gets merged.

Add more documentation

---

app/styles/crate.scss

The current `overflow-x: scroll` shows a scrollbar all the time, even
for code blocks that don't need them. Switch to `overflow-x: auto`, to
only show the scrollbar when needed.

crate.scss: When rendering code in README, don't show scrollbar unless necessary

---

src/badge.rs
src/tests/badge.rs

Feel status is a better name for the `Maintenance` struct key than value. I also renamed the `MaintenanceValue` enum to `MaintenanceStatus`.

Rename maintenance struct key from value to status

---

build.rs

When the timestamp on the migrations/ directory changes the build script will be run so that any pending migrations are run.
I've tested this on Linux, but management of timestamps on directories may be platform specific.

Ensure the build script is run when migrations are added

---

app/styles/app.scss
app/templates/components/crate-row.hbs

On http://crates.io/categories/no-std, we list "All time downloads" and "Recent downloads" without explaining how recent the recent downloads are. This diff just adds an `<abbr>` element with a title to explain:
The default `<abbr>` styles on my browser made this illegible (Brave on OS X) so I replaced the default abbr style with a border-bottom, but it could potentially be changed to use a newer CSS property (text-decoration-position).

Adds a title to elaborate on how we count recent downloads.

---

src/bin/render-readmes.rs

It appears that the lint on nightly is more aggressive and it correctly
identifies that the entries binding itself is not mutated even though
the type is (and needs to be) &mut.
This will ensure that our builds don't break when nightly becomes
the new beta.

Make `entries` binding immutable for &mut type

---

app/styles/crate.scss

A little screenshot with the new style:
As you can see, the `code` elements inside the texts are now easier to spot and I find it more attractive when reading.

Improve code display

---

.gitignore
docs/ARCHITECTURE.md
docs/CONTRIBUTING.md
src/config.rs
src/dist.rs
src/krate.rs
src/lib.rs
src/local_upload.rs
src/uploaders.rs

Fix #934, serve locally uploaded crates from a different location since `dist/` gets recreated each time the front end restarts.

Serve locally uploaded crates from a different folder

---

app/routes/logout.js
docs/ARCHITECTURE.md
src/lib.rs

Other sites are allowed to make `GET` requests so switching to `DELETE`
to match the destructive nature of the route.
If the user navigates to `GET /logout` we now fall back to the default
behavior which is to serve up the ember app.  Ember then sends a
`DELETE` request.  Fortunately we already enforce sameorigin for
iframes via the `X-FRAME-OPTIONS` header.
Fixes: #986

Switch to `DELETE` for /logout route to prevent CSRF

---

src/bin/render-readmes.rs

To pick up the readmes that have been rendered before the change to
record the time a readme is rendered went out.

Need to rerender readmes that haven't been recorded

---

app/adapters/api-token.js
app/controllers/dashboard.js
app/routes/application.js
app/routes/index.js
mirage/config.js
src/lib.rs
src/tests/krate.rs
src/tests/token.rs
src/tests/user.rs

For consistency, to avoid the clash with the frontend /me route that
caused problems with staying logged in, to make it clear that these
routes are part of the public HTTP API provided by crates.io, and to
let us evolve these routes in the future.
This would make me feel comfortable about adding a cargo command that uses the info from the backend me route (see #1012).
We could do this more conservatively by leaving the old routes here and only adding the new routes... but we haven't made any guarantees about the stability of these routes, so...
See discussion: https://github.com/rust-lang/crates.io/pull/910#issuecomment-318250109
@jtgeibel wdyt?

Move backend routes under api/v1

---

src/krate.rs
src/tests/krate.rs

If there is at least one other owner remaining, then an owner can remove themselves from a crate.

Issue #680 : Crate owners can now remove themselves as owner 

---

build.rs
src/badge.rs
src/bin/delete-crate.rs
src/bin/delete-version.rs
src/bin/populate.rs
src/bin/transfer-crates.rs
src/bin/update-downloads.rs
src/categories.rs
src/category.rs
src/db.rs
src/dependency.rs
src/download.rs
src/keyword.rs
src/krate.rs
src/owner.rs
src/tests/all.rs
src/tests/categories.rs
src/token.rs
src/user/mod.rs
src/version.rs

As of diesel 0.16.0 `diesel::pg::PgConnection` is now also exported
from `diesel::prelude`.

Remove explicit use of PgConnection as this is now in the prelude

---

Cargo.lock
Cargo.toml
src/render.rs

Fixes #998.
Needed an upgrade to ammonia.

Add rel=nofollow to README links to prevent being used as spam

---

app/components/badge-maintenance.js
app/templates/components/badge-maintenance.hbs
mirage/fixtures/crates.js
tests/acceptance/search-test.js

Start front end work for #704 by creating a maintenance badge component. I'm not quite sure what the alias() function does in ember.js, think it takes out the attributes from the badges for a crate?
I'm going to work on all the frontend changes here, since the tests failed when I attempted to add the fixture without the badge component.
NOTE: If #996 is approved, I'll have to change this PR to work with it.

Maintenence badge front end

---

app/styles/crate.scss

Give tables in readmes a bit of padding and a border

---

src/krate.rs
src/tests/krate.rs

Additionally, we've updated the join for this data on krate::index to
use the new public API Diesel added for this in the most recent version,
and made sure that any other endpoints which *don't* include this data
are returning NULL instead of 0
/cc @natboehm

Add query to display recent_downloads on krates::show

---

src/krate.rs
src/tests/team.rs
src/tests/user.rs

I noticed that the cargo-canoe crate was still listed under my crates on /dashboard, even though alex changed all the ownership records except one to `deleted=true`. Turns out we didn't have that condition on here!
The new tests with the ownership records changed to deleted failed before these changes and pass after.

Don't list crates that teams/users used to own

---

app/router.js
app/templates/application.hbs
app/templates/policies.hbs

Moving the "Crates.io Package Policies" page from
<http://doc.crates.io/policies.html>, which is hosted in `cargo` repo,
here, as this is a website-related content and not related to the
build-system.
First step for <https://github.com/rust-lang/crates.io/issues/1030>
Next step will be to redirect the old URL to this new page.

Add /policies page

---

app/templates/application.hbs

As Cargo documentation is being moved to <doc.rust-lang.org>, and to
emphasis the difference between `crates.io` and `cargo`, we better not
title the website as *CARGO* anymore.
This is a quick fix for this, until we redirect `docs.crates.io`
completely and fix the menus and links here.
See <https://github.com/rust-lang/crates.io/issues/1031>

[header] Replace CARGO with crates.io

---

Cargo.toml

Fixes #911
- Adds a [package.metadata.docs.rs] to Cargo.toml
- Sets the rustdoc-args key to [ "--no-defaults --passes collapse-docs --passes unindent-comments" ]

Display doc comments for private types

---

app/routes/install.js
app/templates/install.hbs

The content of the `install` page here is duplicate of `cargo`'s
*Installation* page/section. Since it's not *registry*-specific feature,
we better just redirect to the original source.
The content of the page is already merged into <http://doc.crates.io/>
and is live.
See <https://github.com/rust-lang/crates.io/issues/1029>

Redirect /install to doc.crates.io

---

Cargo.toml

Fixes: #911
Tested with [this crate](https://docs.rs/docsrs-test/0.0.4/docsrs_test/).

Fix docs.rs metadata for docs of private types

---

app/styles/app.scss

After shipping the update to header title/subtitle and testing it with
logged-in user, the subtitle was broken into two lines, breaking the
layout. Making the subtitle a bit smaller fixes the problem.
See <https://github.com/rust-lang/crates.io/issues/1031>

[styles] Make header subtitle fit in one line

---

app/styles/app.scss
app/styles/crate.scss

Fixes https://github.com/rust-lang/crates.io/issues/970
**Summary**
This is my first PR to this repo, but I saw the Issue above and thought I'd try and tackle it since it's fairly minimal, but is a nice change to help with readability. This is a suggestion to widen the width of the main div to 960px so that the `.crate-info .docs` div can be increased a bit without having to decrease the size of the `.crate-info .authorship` div.
**Reasoning**
I mainly chose 960px since it's a fairly widely accepted standard for content of this type. This allows the documentation to be 640px, which increases the line-length of the `pre` elements to 65 to help minimize horizontal scrolling.
**Before/After**
**Other Changes**
I also changed the responsive screen width option to match the 960px width. The …

Make the page wider to give more room for README on desktop

---

app/helpers/format-email.js
package-lock.json
package.json

Prototype extensions are unfortunately not supported by fastboot so we will need to disable them to prepare for server-side rendering.
(see https://github.com/ember-fastboot/ember-cli-fastboot#prototype-extensions)

Disable prototype extensions

---

app/components/email-input.js
app/models/user.js
app/styles/me.scss
app/templates/components/email-input.hbs
src/tests/user.rs
src/user/mod.rs

Just cleaning up a few small things before deploying email verification :)

Email polish

---

app/routes/category.js
app/routes/crate.js
app/routes/keyword.js
app/routes/team.js
app/routes/user.js

Turns out when we were checking for crate/category/etc not being found, we were using `any` from the ember prototype extensions. This PR changes those spots to use `some` instead, and cleans up a few other inconsistencies I noticed.
I tried to write tests for "not found" pages, but that's proving to be a bit more.... interesting... so I decided to open this up to fix production first.
r? @Turbo87

Fixes errors on "not found" pages

---

app/components/badge-appveyor.js
app/templates/components/badge-appveyor.hbs
src/badge.rs
src/tests/badge.rs

this is part of fixing issue #693

Fix Wrong AppVeyor badge

---

src/render.rs

Syntax highlighting seems to be working as intended now.  I tested by publishing a create locally with a `README.md` including a couple of code samples, see below for a screenshot. Thanks for the help, and please let me know if you have any questions.
Closes #1008

Re-enable syntax highlighting.

---

src/tests/user.rs
src/user/mod.rs

This commit has various cleanup of functions involving `NewToken` and
`NewEmail` in the users module. In particular, the following changes
were made:
- Use the database as the source of truth when possible
- Run non-atomic operations in a transaction
- Avoid extra allocations
- Clean up some oddly structured code

Cleanup of the `users` module

---

Cargo.lock
Cargo.toml
src/tests/token.rs
src/token.rs

- Inlined functions which were only used once
- In the case of `find_for_user`, I think that the order should be
close to where it is relevant.
- In the case of `delete`, the only test that was calling it was
literally testing "a deleted row is deleted", which is not needed.
There are tests for the `revoke` endpoint
- The direct usage of Diesel is not meaningfully more verbose than
these functions were
- Removed `EncodableApiToken`, moved the `#[derive(Deserialize)]` struct
to tests

Various minor cleanup of the `token` module

---

migrations/00000000000000_diesel_initial_setup/down.sql
migrations/00000000000000_diesel_initial_setup/up.sql

This used to be done implicitly by Diesel, but it now generates a
migration for this explicitly (since 0.15.0 I believe)

Include the generated Diesel setup migration

---

docs/CONTRIBUTING.md

Introduced in https://github.com/rust-lang/cargo/pull/4209

Update contribution guidelines to use --index

---

Cargo.lock
Cargo.toml
src/bin/render-readmes.rs
src/category.rs
src/crate_owner_invitation.rs
src/keyword.rs
src/krate/mod.rs
src/lib.rs
src/tests/all.rs
src/tests/krate.rs
src/token.rs
src/user/mod.rs
src/version/mod.rs

This replaces all remaining usage of the deprecated `time` crate with
the `chrono` crate instead.

Remove the `time` crate

---

app/templates/index.hbs

Modified the `<h1>` header inside `app/templates/index.hbs` from "The Rust community’s crate **host**" to "The Rust community’s crate **registry**".

Resolves #1031 - Branding updates for crates.io

---

migrations/2017-09-26-200549_users_lowercase_index/down.sql
migrations/2017-09-26-200549_users_lowercase_index/up.sql
migrations/2017-10-06-234455_fix_local_dbs_unique_gh_login/down.sql
migrations/2017-10-06-234455_fix_local_dbs_unique_gh_login/up.sql
migrations/2017-10-09-135625_add_lower_gh_login_index/down.sql
migrations/2017-10-09-135625_add_lower_gh_login_index/up.sql
src/tests/user.rs
src/user/mod.rs

So I can't deploy to production right now because of the unique index added to users.gh_login.
The values on production for gh_login aren't unique, and here's why:
- Someone can sign up for github with username whatever.
- They can sign in to crates.io. We now get their gh_id, say, 3 (which *is* unique) and their gh_login, whatever. Their user account gets crates.io id 10.
- They rename or delete their github account, which leaves the username 'whatever' available again. (If they renamed their github account, their gh_id stays stable and we'd migrate their account to their new username next time they log in)
- Someone else signs up for github with username wHaTeVeR.
- They can sign in to crates.io. We now get their gh_id, 9000, and their gh_login, wHaTeVeR. Their user account gets …

Gh login cant be unique

---

src/krate/mod.rs
src/tests/krate.rs

- Adds "most_recently_downloaded" property to JSON response returned from `api/v1/summary`
- Adds tests for `api/v1/summary` endpoint

Fixes #962 Backend: add "most_recently_downloaded" to 'summary' endpoint

---

app/components/download-graph.js

The purpose of this PR is to change the download chart such that it shows how the absolute number of downloads compares from version to version. Instead of having lots of different lines that might be hard to compare to each other, we show the 7-day average as an area. Additionally, the areas are stacked, so you can see the total and compare between versions.
Here's an example of how it might look (that's the libc crate):
This PR intends to close #393, although I realize it doesn't do exactly what was proposed. I think this is a simple fix that improves the readability of the graph, but I'm prepared to change it to more closely mimic the proposal in #393 if need be.

Show download graph as a stacked area chart

---

app/components/badge-appveyor.js
app/templates/components/badge-appveyor.hbs
src/badge.rs
src/tests/badge.rs

This fixes an issue with appveyor badges where if your repository name included an underscore, the link generated would not work because appveyor urls use dashes.
You can now specify an optional `project_name` for the appveyor badge in your `Cargo.toml`
```
[badges]
appveyor = { repository = "example/test_crate", service = "github", project_name = "example/test-crate" }
```
If the optional `project_name` attribute is present, we will use that for the link URL, otherwise we default to the required `repository` attribute and replace the underscores with dashes.
The reason to provide the `project_name` option is that if you change the repository name appveyor doesn't track the change.
Let me know if I missed anything!  I did create a test crate and set it up with appveyor to confirm.
Closes …

Fix appveyor badge display and link.

---

app/models/crate.js

models/crate: Remove obsolete JSHint directives

---

package.json
tests/acceptance/categories-test.js
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/keyword-test.js
tests/acceptance/search-test.js
tests/acceptance/team-page-test.js
tests/acceptance/user-page-test.js
tests/helpers/has-text.js
tests/helpers/matches-text.js
tests/helpers/start-app.js

see https://github.com/simplabs/qunit-dom
/cc @carols10cents @sivakumar-kailasam

Use High Level DOM Assertions from "qunit-dom"

---

src/krate/downloads.rs
src/krate/follow.rs
src/krate/metadata.rs
src/krate/mod.rs
src/krate/owners.rs
src/krate/publish.rs
src/krate/search.rs
src/lib.rs
src/version/deprecated.rs
src/version/downloads.rs
src/version/metadata.rs
src/version/mod.rs
src/version/yank.rs

This series of commits splits the api endpoints in the `krate` and `version` modules into submodules as an initial step of the refactoring discussed in #912.
Shared by cargo and the frontend, used for searching crates.
Used by `cargo publish`.  This endpoint updates the index, uploads to S3, and caches crate metadata in the database.
Endpoints in these files provide read-only access to data that could largely be recreated by replaying all crate uploads.  The only exception I've seen to this so far is that some responses include download counts.
Provide crate and version level download stats (updated in `version::cargo::download`).
All endpoints for the used by cargo and the frontend for maintaining the list of crate owners.
Read/write access to a user populated list of followed crates. …

Split krate and version functionality into submodules

---

src/lib.rs
src/site_metadata.rs

This PR adds an api endpoint `/deployed_sha`, which returns a JSON response containing that sha `{ "sha": "abc" }` or if it's unavailable returns `{ "sha": "unknown" }`.
Closes #879

Add endpoint to display deployed git sha.

---

app/components/crate-row.js
app/templates/application.hbs
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/components/crate-list.hbs
app/templates/components/crate-row.hbs
app/templates/crate/version.hbs
app/templates/crates.hbs
app/templates/index.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs
package.json
tests/acceptance/categories-test.js
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/keyword-test.js
tests/acceptance/search-test.js
tests/acceptance/team-page-test.js
tests/acceptance/user-page-test.js

see https://github.com/simplabs/ember-test-selectors

Use "ember-test-selectors" for UI tests

---

app/templates/crate/version.hbs
package-lock.json
package.json
tests/.eslintrc.js
tests/acceptance/categories-test.js
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/keyword-test.js
tests/acceptance/search-test.js
tests/acceptance/team-page-test.js
tests/acceptance/user-page-test.js

Use "ember-native-dom-helpers" for simulated user actions

---

app/controllers/dashboard.js
app/routes/dashboard.js

This is a bit of a quick patch to address the problem, we should dig some more into why it's happening.
Fixes #1099
[edit] I only checked `config/environment.js` for something disabling prototype extensions, and forgot to check `package.json`, which lists [ember-disable-prototype-extensions](https://github.com/rust-lang/crates.io/blob/master/package.json#L49).

Fix "pushObjects is not a function" error

---

Cargo.lock
Cargo.toml
app/controllers/crate/version.js
app/initializers/hashchange.js
src/render.rs

Fixes #1037. Use latest comrak, and use the header IDs extension to generate GitHub-compatible anchors.
/cc @kejadlen @treiff

Update comrak to 0.2.3, use ext_header_ids

---

src/config.rs

Working my way through the codebase I came across this markdown issue.

Minor documentation fix

---

.travis.yml
Cargo.lock
Cargo.toml
src/badge.rs
src/keyword.rs
src/krate/metadata.rs
src/krate/mod.rs
src/krate/publish.rs
src/krate/search.rs
src/lib.rs
src/render.rs
src/tests/all.rs
src/tests/user.rs
src/uploaders.rs
src/user/mod.rs
src/util/errors.rs
src/version/deprecated.rs

Bump clippy and rustfmt to versions compatible with the latest nightly compiler.

Bump clippy and rustfmt

---

app/templates/components/api-token-row.hbs

Tokens now go in ~/.cargo/credentials, not ~/.cargo/config

Fix path in api-token-row.hbs

---

src/config.rs
src/tests/all.rs
src/uploaders.rs

This should hopefully allow us to configure a CDN on Heroku (namely CloudFront)
to distribute crates/readmes through.

Add support for a CDN in front of crates/readmes

---

Cargo.lock
Cargo.toml
docs/CONTRIBUTING.md
src/s3/Cargo.toml
src/s3/lib.rs

This series of commits bumps many dependencies, with the exception of diesel (as I couldn't figure out how to update the reverse dependencies query).  In particular, this switches from `time` to `chrono` in the `cargo_registry_s3` crate.
I've also updated the contributing instructions for Ubuntu and Fedora to explicitly install `pkg-config`.

Bump version of most dependencies

---

src/render.rs

And this is okay, because the major sites (BitBucket, GitHub, GitLab) all either directly support visiting the `.git`-suffixed URL of any repo, or redirect from it to the non-suffixed version. These all work fine as-is.
What they don't universally work for is letting you append any path onto that. (Which is to say, from my testing BitBucket doesn't mind, but GitHub and GitLab both 404.)  So we trim the suffix when manipulating relative paths.
See https://github.com/kbknapp/clap-rs/issues/1106 for where this came up with `clap`.

repository URLs sometimes end in .git in real-world usage

---

.travis.yml
Cargo.lock
Cargo.toml
docs/CONTRIBUTING.md
src/bin/delete-crate.rs
src/bin/delete-version.rs
src/bin/populate.rs
src/bin/render-readmes.rs
src/bin/server.rs
src/bin/transfer-crates.rs
src/bin/update-downloads.rs
src/krate/mod.rs
src/lib.rs
src/tests/all.rs
src/tests/categories.rs
src/tests/category.rs
src/tests/keyword.rs
src/tests/krate.rs
src/tests/owners.rs
src/tests/record.rs
src/tests/team.rs
src/tests/token.rs
src/tests/user.rs
src/tests/version.rs
src/version/mod.rs

This switches our CI to install `clippy` and use the `cargo clippy` command.  Additionally, the tests are now run on CI in the same build as `rustfmt`.  If `cargo fmt` fails, travis will still run `cargo clippy` and report any errors there.
In this configuration, `clippy` is no longer included in the `Cargo.toml` file.

Switch to `cargo clippy` which also lints the binaries and tests

---

app/controllers/index.js
app/routes/index.js
app/styles/home.scss
app/templates/index.hbs
package.json

This PR improves the perceived frontpage performance experience by loading the summary data in the background while already displaying the "data" that is available.
We can probably use the same pattern for some other routes too to get rid of the "Loading..." screen.
/cc @carols10cents @tchak

Load summary data in the background

---

.travis.yml

Pinning Node to v8.1.3 does not seem useful 🤔

CI: Use latest Node 8 release

---

app/controllers/application.js
app/controllers/search.js
app/routes/search.js
app/styles/crate.scss
app/templates/application.hbs
app/templates/search.hbs
package.json

Similar to https://github.com/rust-lang/crates.io/pull/1186 this PR changes the "Search" page to load and reload data in the background

Load search results in the background

---

app/controllers/application.js
app/controllers/search.js
app/templates/application.hbs

Similar to e.g. https://yarnpkg.com/ this PR changes the code to start the search while typing instead of having to click the <kbd>Enter</kbd> button. It also debounces the search task (250ms) to limit the amount of requests that are hitting the server.

Start search while typing

---

Cargo.lock
Cargo.toml
build.rs
src/app.rs
src/category.rs
src/db.rs
src/dependency.rs
src/krate/krate_reverse_dependencies.sql
src/krate/mod.rs
src/lib.rs
src/tests/all.rs
src/tests/load_foreign_key_constraints.sql
src/tests/schema_details.rs
src/version/downloads.rs
src/with_count.rs

Most of the code changes are for us to switch to `sql_query` where
appropriate. `sql` deprecated its API for bind parameters, as it's meant
to be used with fragments of SQL as part of the query builder, not full
queries. `sql_query` does not require the SQL type to be specified, and
it gets the values by name instead of by index. Unfortunately, none of
the places we are using raw SQL were places that
`#[derive(QueryableByName)]` would work, so I had to manually implement
all of them
This also updates to r2d2 0.8, because I couldn't remember the command
to make cargo force r2d2-diesel to resolve to r2d2 0.7

Update to use Diesel 0.99.0

---

app/controllers/application.js
app/controllers/search.js
app/templates/application.hbs

While I still like the feature it self, the implementation currently has some issues (see #1209) that I wasn't aware of initially and are not quite as easy to fix. Since I'll be on vacation for the next weeks I won't have time to work on a proper solution for now, so IMHO the best solution is to revert the problematic behavior until this can be fixed correctly.
Resolves #1209
/cc @durka @Boscop

Revert "Merge #1194"

---

Cargo.toml
README.md
src/s3/Cargo.toml

Explicitly state our license in the README, use `OR` in Cargo.toml

---

app/controllers/me/crates.js
app/templates/me/crates.hbs

This fixes #1231, and renames "Downloads" to "All-Time Downloads" to be consistent with the sort dropdowns on other listings.

Add UI for sorting my crates by recent downloads

---

app/components/user-avatar.js
app/styles/app.scss
app/styles/crate.scss
app/styles/home.scss
app/styles/me.scss
app/templates/application.hbs
app/templates/components/crate-list.hbs
app/templates/components/link-to-dep.hbs
app/templates/crate/owners.hbs
app/templates/crate/version.hbs
app/templates/crates.hbs
app/templates/index.hbs
config/environment.js
package-lock.json
package.json
tests/acceptance/categories-test.js
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/keyword-test.js
tests/acceptance/search-test.js
tests/acceptance/team-page-test.js
tests/acceptance/user-page-test.js
tests/axe-config.js

Most commits have a message explaining why I think the change is necessary. Let me know if anything is unclear or if I should follow up with other changes.
Shoutout to @chriskrycho for his talk [Becoming a Contributor](https://www.youtube.com/watch?v=Abu2BNixXak) which encouraged me to do this!

Accessibility fixes (and tests)

---

Cargo.lock
Cargo.toml
src/app.rs
src/category.rs
src/db.rs
src/dependency.rs
src/krate/downloads.rs
src/krate/metadata.rs
src/krate/mod.rs
src/krate/search.rs
src/lib.rs
src/pagination.rs
src/schema.rs
src/tests/schema_details.rs
src/upload.rs
src/user/mod.rs
src/with_count.rs

This is the minimum changes required to fix any deprecation warnings.
There's a lot of additional stuff we could do that I wanted to keep
separate. After updating to Diesel 1.1, we can remove virtually anywhere
that we're doing an explicit `&*`. Additionally, there are probably a
lot of places that we should be using custom types but aren't. We can
remove a lot of code once
https://github.com/steveklabnik/semver/pull/169 is merged/released as well.

Update to Diesel 1.1

---

app/components/badge-appveyor.js

They apparently replace both '.' and '_' in URLs. Fixes #1220.

Replace '.' with '-' in Appveyor links

---

app/styles/crate.scss
app/templates/crate/version.hbs

`/crates/<some-crate>` pages
> Before
> After

[UI UPDATE]: Slight alignment tweak for the stats numbers on the

---

app/styles/crate.scss

Slight widening to the `main` section of a given crates page based on issue #1148, overflow now prevented

[UI UPDATE]: Based on issue #1148, widen main to prevent icon overflow

---

src/category.rs
src/crate_owner_invitation.rs
src/keyword.rs
src/krate/mod.rs
src/token.rs
src/version/mod.rs

99c459bb fixed the serialization to be RFC3339 compliant with the
timezone being represented as `+00:00`. This simply adds tests for the
structs where we use `#[serde(with = "::util::rfc3339")]` to ensure
the JSON representation of those dates stay the same.
Fixes #1164

Tests to ensure datetime JSON serialization stays the same

---

.travis.yml
src/bin/render-readmes.rs
src/crate_owner_invitation.rs
src/dependency.rs
src/krate/metadata.rs
src/krate/mod.rs
src/krate/publish.rs
src/tests/all.rs
src/tests/krate.rs
src/tests/schema_details.rs
src/token.rs
src/version/mod.rs
src/views/mod.rs
src/with_count.rs

Bump rustfmt and clippy and apply fixups.

Bump rustfmt and clippy on CI

---

app/styles/home.scss

Center stats on homepage for smaller/mobile screen

---

src/controllers/krate/publish.rs
src/git.rs
src/tests/all.rs
src/tests/krate.rs
src/views/krate_publish.rs

This is a companion to https://github.com/rust-lang/cargo/pull/4978
It is adding the links attribute to the index git. I am working on windows so cannot test locally, I.E. this may involve some sparing with the CI to get this green. Advice and help are welcome!

Try to add links to the index

---

src/boot/categories.toml

I did not add this under `web-programming` because there is nothing inherently "Web-y" about wasm: it can be used as a general arch-independent binary format, as parity exemplifies.
Examples crates that would use this category (some of which are not actually published on crates.io yet, but the point stands):
* `parity-wasm`
* `wasmi`
* `wee_alloc`
* `wasm-bindgen`
* `wasm-gc`
* `wasm-nm`
* `wasm-snip`
* `svelte`
* `binaryen`
* `wabt`

Add WebAssembly category

---

package-lock.json
package.json
testem.js
tests/test-helper.js

These changes:
1. Install a frontend dependency called [ember-exam](https://github.com/trentmwillis/ember-exam)
2. Alter the command to run frontend tests in order to use ember-exam parallelism feature. It will split randomly the frontend tests into four partitions and run them all in parallel. 
A simple further step to improve performance would be to detect how many core are available on the running machine and split by exactly this number - so it can be fully used.

Running ember tests in parallel

---

app/controllers/crate/version.js
app/initializers/session.js
app/mixins/authenticated-route.js
app/routes/application.js
app/routes/confirm.js
app/routes/crate/version.js
app/routes/dashboard.js
app/routes/login.js
app/routes/logout.js
app/routes/me/crates.js
app/routes/me/index.js
mirage/config.js
tests/acceptance/crate-test.js

This PR cleans up the `session` service. It is generally recommended to inject services only into those modules that actually need them. Injecting them unconditionally in an initializer makes them much harder to mock at the same time and causes unnecessary injections.
Partly extracted from https://github.com/rust-lang/crates.io/pull/1279, thanks @CvX!

Cleanup `session` service code

---

Cargo.lock
src/tests/record.rs

Replaced an API that was deprecated in hyper, then updated dependencies.

Update to new hyper API and run `cargo update`

---

.rustfmt.toml
.travis.yml
config/manifest.js
config/targets.js

Use the `rustfmt-preview` component on the `stable` channel when checking formatting on CI.   When developing, proper formatting is now just a `cargo +stable fmt` away!

Use the new rustfmt-preview component when on CI

---

tests/acceptance/categories-test.js
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/keyword-test.js
tests/acceptance/search-test.js
tests/acceptance/team-page-test.js
tests/acceptance/user-page-test.js
tests/helpers/setup-mirage.js

A crucial fix for visual testing.
Connects to #1293.

Set a constant faker seed for deterministic tests.

---

package-lock.json
package.json

one less dependency using the deprecated ember-cli-babel v5.x 🎉

Update `ember-cli-clipboard` to v0.9.0

---

.eslintrc.js
package-lock.json
package.json

Updates to eslint config and lint error fixes to follow in separate PRs.

Replace eslint-plugin-ember-suave with eslint-plugin-ember.

---

.eslintrc.js
mirage/factories/category.js

“Use import { dasherize } from '@ember/string'; instead of using Ember.String.dasherize”
cc: @Turbo87

ESLint: fix “ember/new-module-imports” error.

---

src/controllers/krate/metadata.rs
src/models/krate.rs

Related to #1304.
Because we only want to show the top 10 for /api/v1/summary, move the
LIMIT within the query for the top downloads rather than joining on
everything and then limiting.
This should help alleviate at least some of the slowdowns we were seeing today with the /api/v1/summary call; there are other queries that are taking up some load that will need other mitigation strategies though :(
Here's an explain analyze from the old query on a production dump from today:
```
explain analyze SELECT "crates"."id", "crates"."name", "crates"."updated_at", "crates"."created_at", "crates"."downloads", "crates"."description", "crates"."homepage", "crates"."documentation", "crates"."readme", "crates"."readme_file", "crates"."license", "crates"."repository", "crates"."max_upload_size" FROM ( …
```

Switch most recently downloaded summary query to be faster

---

src/middleware/security_headers.rs

This removes `https://www.google-analytics.com` from `script-src` in our CSP headers now that GA was removed in #1306.

Remove Google Analytics domains from our Content Security Policy headers

---

app/adapters/application.js
app/components/email-input.js
app/controllers/dashboard.js
app/controllers/index.js
app/controllers/me/index.js
app/routes/confirm.js
app/routes/crate/version.js
app/routes/github-authorize.js
app/routes/github-login.js
app/routes/logout.js
app/services/session.js
package-lock.json
package.json

This will path the way to eventually remove jQuery :)

Replace `ember-ajax` with `ember-fetch`

---

.travis.yml

Diesel 1.0.0 was released with overly broad constraints on internal
dependencies. `diesel_cli` relies on internal implementation details of
`diesel` (and other internal crates) which are not bound to semver.
Unfortunately, we didn't anticipate the problems that came from having a
"semver compatible" bound on these dependencies when relying on semver
excempt APIs.
This was fixed in Diesel 1.0.1. We could probably just switch to 1.2.0,
but this is the more conservative change.
Fixes our build

Don't use Diesel CLI 1.0.0

---

src/models/krate.rs
src/tests/krate.rs
src/views/krate_publish.rs

Diesel 1.2 had planned on renaming our `large-tables` and `huge-tables`
features to `32-column-tables` and `64-column-tables` respectively,
while also introducing the `128-column-tables` feature. This change was
made several months ago in Diesel. Cargo will happily accept those
as feature names, and resolve them properly from other crates.
However while publishing Diesel 1.2, I ran into a snag mid-release when
I realized that Cargo is incorrectly assuming that a feature name must
be the same as a crate name. I suspect this is an artifact of the fact
that feature names often are crate names (and perhaps in the past that
was the only form of feature?).
However, now they are an entirely separate thing, and we should allow
the same set of feature names that Cargo does. (As an aside, do we …

Allow feature names to begin with numbers

---

src/views/krate_publish.rs

There was a use of `valid_feature_name` that didn't get changed to `valid_feature`. I've added a regression test that exercises more of the stack to ensure this doesn't happen again in the future.
Fixes #1334

Correct uploading features with `/`s

---

package-lock.json
package.json

This is no longer needed as all dependencies use Babel 6+ now :)

Remove obsolete `ember-cli-shims` dependency

---

src/app.rs
src/db.rs

We're consistently seeing the endpoint for crate downloads H12. The logs
are showing that we are *eventually* finishing without error, it's just
taking >30s, so Heroku is killing the connection.
Unfortunately, this means that we don't have visibility into *why* it's
timing out. It's either waiting for a long time for a DB connection,
updating the `version_downloads` table (my guess), or talking to S3. If
it's database related, this will turn those requests into actual errors.
This setting will increase our error rates, as we're seeing the 99th
percentile push up to 5s at some points, and we do have requests that
take 15s to complete (but are completing). Eventually I think we should
be able to consider 10s response times unacceptable, but for now I'm
only going to leave this at 10s for …

Allow database timeouts to be configured

---

src/bin/update-downloads.rs

Prior to this commit, `bin/update-downloads` will hold a lock on every
row it updates for the entire batch of 1000. Each row gets locked when
it is `updated`, but the lock isn't released until the whole transaction
is comitted. This means that the first row in the batch is locked for
the whole transaction, but the last row in the batch isn't locked longer
than it should be.
Processing 1000 rows is routinely taking more than 30 seconds to
complete. Whenever it does, this causes requests to time out. Even when
it doesn't, this locking behavior is the reason that our 99th percentile
response time is getting to be so bad.
The endpoint affected by this is `/crates/{name}/{version}/download`. In
other words, this bug is causing `cargo install` to fail. Even when it
doesn't, this bug is causing …

Don't lock more than 1 row at a time in `update-downloads`

---

migrations/2018-04-13-170549_properly_index_version_downloads/down.sql
migrations/2018-04-13-170549_properly_index_version_downloads/up.sql

The query used to grab the next batch of unprocessed version downloads
is now taking on average 9 seconds to run. It can take as much as 30
seconds. I suspect this is because the size of the `processed` index, or
some other measurement PG is using changed so it decided that index
wasn't the right one to use.
That index wasn't very helpful anyway (it was just the `processed`
column). We can do better by indexing the id with the where clause.
`EXPLAIN ANALYZE` results:
Before:
```
QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=0.09..16204.73 rows=1000 width=21) (actual time=39279.902..39298.408 rows=1000 loops=1)
->  Index Scan using …
```

Better index version downloads for the update script

---

src/middleware/debug.rs
src/middleware/mod.rs

There are enough different IPs requesting large number of crate details
endpoints at the same time that I think we have a page making more API
calls than it should be. I'd also like the see the UA header for a
crawler hitting us a lot. This enables me to do both.

Add the ability to log request headers in production.

---

src/middleware/blacklist_ips.rs
src/middleware/mod.rs

It turns out `req.remote_addr()` is just always returning localhost with
a port. The actual IP we want is in the `X-Forwarded-For` header, which
appears to always be the a comma separated list of IPs with spaces, one
of which is the one we want.
This makes the "is this IP in there" much wonkier (why can't I call
`Vec<String>::contains(&str)`?), but this should get us what we want.
Heroku will always provide an `X-Forwarded-For` header.

Fix IP blacklisting

---

src/middleware/ensure_well_formed_500.rs
src/middleware/mod.rs

rust-civet basically vomits if you ever return it an error. The
resulting response would cause nginx to flip out, and then for Heroku to
give us an H13 or otherwise respond with a 502 error.
This ensures that we always return an `Ok` response, no matter what.

Ensure we return a well formed 500 on errors

---

app/components/crate-badge.js
app/templates/components/crate-badge.hbs
app/templates/components/crate-row.hbs
app/templates/crate/version.hbs

Every single time someone loads a crates.io badge from shields.io, they
make a separate API call to our servers for each one, with no caching.
This means that right now when you go to the search page, you're going
to make 11 API calls when you should be making 1. The result is that shields.io
accounts for an unreasonably large amount of traffic to our systems.
We have all the information we need for this badge when we load the page,
so let's just do that and use their "badge with these words" API instead.
I've just removed it from the version show page since we already display
that info elsewhere on the page, and it's especially confusing when the
numbers don't match.

Don't use shields.io's crate badges

---

app/components/crate-badge.js
app/templates/components/crate-badge.hbs

Dashes are used to separate sections, and need to be escaped. I had
thought that `crate.max_version` never included prereleases, but I was
wrong.

Fix badges for crates with prerelease versions

---

migrations/2018-04-13-203856_trigger_search_reindex_less/down.sql
migrations/2018-04-13-203856_trigger_search_reindex_less/up.sql

I'm seeing a lot of this in the logs:
> Words longer than 2047 characters are ignored.
>  PL/pgSQL function trigger_crates_name_search() line 8 at assignment
It looks like the update-downloads script is causing this trigger to run
when it increments the download count. This restricts the trigger so it
only runs when the `updated_at` column is changed (which does not happen
when only the downloads column is touched)

Don't re-index crates search all the time

---

src/github.rs

We already have custom logic for handling 403 responses from github.  This handles a 401 status in the same way.
Fixes #1327

Return a friendly error if github API responds with status code 401

---

app/controllers/crate/version.js
app/templates/crate/version.hbs

This endpoint is one of our slowest, we don't need to hit it every time
someone visits this page.

Don't query `reverse_dependencies` on crates/show

---

.gitignore
.nycrc
config/coverage.js
mirage/config.js
package-lock.json
package.json

Run `npm run test-coverage` to get the code coverage report.
This PR uses a pre-release version of ember-cli-code-coverage (current master, git ref 77b5b92) which includes the latest fixes. We'll update to a new release as soon as it's available.
cc: @Turbo87

Add ember-cli-code-coverage.

---

app/routes/install.js
app/templates/application.hbs
app/templates/index.hbs
app/templates/install.hbs
app/templates/search.hbs
src/controllers/krate/publish.rs
src/models/dependency.rs

This updates the links to point directly to the new documentation on rlo, rather than going through the redirect at doc.crates.io.
I know there was a previous discussion of adding `includeSubDomains` to our `Strict-Transport-Security` header but this was blocked by the old documentation (served via github pages I believe).  I'm assuming that is no longer blocked as the redirect works for me over `https://`.  However, this PR does not change the STS header at this time.

Update the documentation links to point directly to the new domain

---

src/middleware/log_request.rs

Conduit doesn't provide any methods that give us the path and query
string if present, so we have to do some additional junk to make that
happen ourselves.

Include query string in logs

---

migrations/2018-04-24-145128_create_recent_crate_downloads/down.sql
migrations/2018-04-24-145128_create_recent_crate_downloads/up.sql
src/bin/update-downloads.rs
src/controllers/krate/metadata.rs
src/controllers/krate/search.rs
src/schema.rs
src/tests/all.rs

Every aspect of crates.io is extremely fast except one. Calculating
recent downloads is a moderately expensive operation that we are doing
too often. It's not "slow" per-se. The query takes 500ms to complete on
average, which is not unreasonable.
However, this query does put a good bit of load on the DB server. The
root cause of #1304 was an irresponsible bot hitting /crates (which
includes recent downloads) enough that it caused our DB server's CPU
load to reach 100%. We're on a very low tier database server right now,
so we could fix this by just upgrading to the next tier if we wanted to.
However, as the number of crates grows, this problem will just get
worse.
Recent downloads appear in 3 places. Summary, search, and crate details.
Summary and search are the two endpoints that …

Make recent downloads fast

---

app/controllers/search.js
app/templates/search.hbs

To sort by relevence, the backend expects the sort string to either be
not present, or set to the value "relevance". Right now the backend is
either sending the string `null` or an empty string. Neither of these do
what we want.
Fixes #1370

Fix relevance sorting on search

---

src/render.rs

Images in READMEs don't render ([example](https://crates.io/crates/imgref)), because relative image URLs are converted to a URL to an HTML page about the image, rather than to the image data.
This fixes image embedding by changing `/blob/` to `/raw/` part of the URL for image URLs. The images are detected by file extension in the URL, because I haven't found a way to distinguish when URLs are generated for `<img>` markup and other URLs.

Use /raw/ rather than /blob/ URLs for images

---

src/bin/update-downloads.rs

The existing 2 hour offset causes tests failures between 0:00 and 2:00
UTC.  During this time period, the generated row is given a date of
"yesterday" and the new processing logic marks the row as processed.

Update test in the update-downloads binary to work at all hours

---

app/styles/crate.scss

Before: ![before](https://user-images.githubusercontent.com/6342851/39496654-108b97ec-4da8-11e8-94ee-6d44ac6d7c12.png)
After: ![after](https://user-images.githubusercontent.com/6342851/39496659-139bd24e-4da8-11e8-9e93-4a099f3716ae.png)

Add missed wrap to fix view on small screens

---

migrations/2018-04-27-194025_remove_unused_indexes/down.sql
migrations/2018-04-27-194025_remove_unused_indexes/up.sql

The gh_id index has never been read at all. reserved_crate_names is too
small of a table for indexes to be useful. I've manually verified that
every query hitting version_downloads either doesn't use these indexes,
or has the same performance when not using them.

Remove some unused indexes

---

src/controllers/krate/search.rs
src/models/badge.rs
src/models/mod.rs

I've been noticing response times spiking towards 300ms when a
particular crawler hits us. Specifically one that sets `per_page=100`.
The number of queries executed to load badges is the only thing that
would dramatically change in timing based on the number of rows. This
will load the badges in 1 query per request instead of 1 query per crate
per request.

Remove the N+1 queries from crates search

---

app/templates/application.hbs

The [Guide link in the footer](https://doc.rust-lang.org/cargo/guide.html) is currently not found.

Fix Guide link in footer

---

.travis.yml

The Diesel buildpack uses the version defined in `.diesel_version` when
running migrations.  This change ensures that we are also using the
same version on CI any time the version in that file is bumped.

Pull diesel_cli version from .diesel_version when installing on CI

---

src/bin/render-readmes.rs
src/bin/server.rs
src/controllers/krate/publish.rs
src/email.rs
src/middleware/app.rs
src/middleware/security_headers.rs
src/models/owner.rs
src/models/user.rs
src/render.rs
src/router.rs
src/tests/all.rs
src/tests/krate.rs
src/tests/user.rs
src/uploaders.rs
src/util/errors.rs
src/util/mod.rs

Running `cargo +stable fmt` because CI is failing on master now that
1.26.1 has been released.

Update formatting for rustfmt-preview as of 1.26.1

---

src/middleware/mod.rs

According to #1358 Firefox incorrectly sends a Accept: text/html header when requesting
the opensearch.xml.
This fixes the bug, but I am not sure if it is the most ideal.
edit by JTG: Fixes #1358

opensearch.xml not served if Accept header is text/html

---

package-lock.json
package.json

This PR updates `ember-cli` to the latest release. It does not yet update Ember itself, which will follow in a separate PR.

Update `ember-cli` to v3.1.4

---

package-lock.json
package.json

This update gets rid of a broccoli deprecation warning.
see https://github.com/ember-cli/ember-fetch/blob/master/CHANGELOG.md

Update `ember-fetch` to v5.0.0

---

package-lock.json
package.json

This PR updates `ember-source` to v3.1.2. Since all previous deprecation warnings had been addressed already, this should work without any changes, but will allow us to take advantage of newer features soon. :)

Update Ember to v3.1.2

---

package-lock.json

Fixes several `npm audit` warnings

Update `lodash` subdependency to v4.17.10

---

package-lock.json

Fixes several `npm audit` warnings

Update `debug` subdependency to v2.6.9

---

package-lock.json

Fixes several `npm audit` warnings

Update Babel subdependencies

---

src/controllers/krate/metadata.rs
src/models/krate.rs
src/render.rs
src/tests/krate.rs
src/tests/owners.rs
src/util/io_util.rs

This is the diff that results from `cargo +beta fmt`.  It will not pass
CI today, but should be mergable via bors after the release tomorrow.

Prepare for new rustfmt in 1.27 release

---

src/views/mod.rs

Fix for #1001. I guessed on the formatting of the comment. I can easily change it if needed.

#1001 Add a comment to fields used by shields.io

---

src/uploaders.rs

It was discovered recently that tarballs with hard links aren't properly handled
in the `tar` crate and can in malicious situations cause any file on the
filesystem to get overwritten during the extraction process. This commit is a
patch for crates.io to simply reject all tarballs which have hard links inside
of them. This is a big hammer of a solution and is step 1 of a fix for this bug.
I've verified that all existing tarballs on crates.io do not contain hard links
and Cargo itself doesn't produce tarballs with hard links inside them. That
means that no legitimate tarball should be rejected as a result of this patch.
After this has been deployed I'll be updating the `tar` crate as well as Cargo
itself, in addition to posting an announcement.

Forbid tarballs with hard links being uploaded

---

Cargo.lock
Cargo.toml

And then update `Cargo.lock` with:
```console
$ cargo build
```
This bumps us from the SPDX License List 2.4 to 3.1.  Some 2.4 identifiers have since been deprecated by SPDX, but none of them have been removed, so it should be safe to deploy this before bumping Cargo and its docs (which mention 2.4 since rust-lang/cargo#4898).
Fixes #1278.

Cargo.toml: Bump license-exprs to 1.4.0

---

src/controllers/krate/downloads.rs
src/controllers/krate/metadata.rs
src/controllers/krate/search.rs
src/controllers/version/mod.rs
src/models/krate.rs
src/models/mod.rs
src/tests/all.rs
src/tests/krate.rs

Since this seems likely to creep up again, I've added a canonical
`versions` method to both `Crate` and `Vec<Crate>` which filters out
yanked versions, and a separate `all_versions` which includes yanked
versions. I've gone through all uses of `Version::belonging_to` to make
sure that these methods are used instead.
I'm tempted to remove the association entirely to force this function to
be used instead, but if I did that we'd lose the ability to use
`grouped_by`, which is a lot of code to replace.
In one case, this required adding an additional temporary, since the
trait appears to be confusing the borrow checker (I'm not sure why the
temporary is required now, but wasn't before -- the same lifetime is
appearing on a type in the same positions. I suspect it's a borrow
checker bug that …

Don't consider yanked versions for `max_version` on Search

---

app/templates/application.hbs

Previously the category slug list wasn't linked from anywhere on
crates.io.

Add list of category slugs to docs menu

---

app/controllers/category/index.js
app/controllers/crates.js
app/controllers/keyword/index.js
app/controllers/me/crates.js
app/controllers/search.js
app/controllers/team.js
app/controllers/user.js
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/me/crates.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs
src/controllers/krate/search.rs
src/tests/krate.rs
tests/acceptance/search-test.js

Allow sorting by which crates were most recently updated as mentioned in #1210. The option is called 'recent-updates' in order to match the naming convention of 'recent-downloads'

Recently updated sort

---

Cargo.lock
Cargo.toml
src/email.rs
src/lib.rs

Upgrade to the latest `lettre` crate and address API changes.

Update lettre from 0.6.2 to 0.8.2

---

app/models/category-slug.js
app/styles/crate.scss
app/templates/category-slugs.hbs
mirage/config.js
package-lock.json
package.json
src/controllers/category.rs
src/models/category.rs
src/tests/all.rs
src/tests/category.rs
src/tests/krate.rs
tests/acceptance/categories-test.js

The manifest documentation https://doc.rust-lang.org/cargo/reference/manifest.html
suggests https://crates.io/category_slugs as a list of all categories, but this
is a fairly terse list of nouns presently. The description is useful for making
an informed decision about which categories apply.

frontend: show descriptions in category list

---

src/bin/update-downloads.rs
src/lib.rs
src/tests/all.rs

Because we deny warnings, this new lint will cause our CI to fail once
it hits beta.  Allowing `unknown_lints` is necessary because
stable-1.28 isn't aware of this lint.
This patch can be reverted as part of upgrading to Diesel 1.4 once that
is released.  See the [upstream PR] for more information.
[upstream PR]: https://github.com/diesel-rs/diesel/pull/1787

Allow a new macro hygiene lint until we get Diesel 1.4

---

.travis.yml
src/controllers/category.rs
src/controllers/keyword.rs
src/controllers/krate/metadata.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/session.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/email.rs
src/git.rs
src/middleware/blacklist_ips.rs
src/middleware/ember_index_rewrite.rs
src/models/dependency.rs
src/models/keyword.rs
src/models/krate.rs
src/tests/all.rs
src/tests/krate.rs
src/tests/user.rs

This will fail on stable until the 1.28 release on Thursday.  At that point, bors should be able to merge this.
The command run on CI is now `cargo fmt -- --check`.

Apply formatting changes from rustfmt-preview on 1.28

---

src/bin/render-readmes.rs
src/controllers/helpers/pagination.rs
src/middleware/log_request.rs
src/models/krate.rs
src/tests/all.rs
src/tests/record.rs
src/util/errors.rs
src/util/request_proxy.rs
src/views/krate_publish.rs

This diff was created with the following commands:
RUSTFLAGS="-W elided_lifetimes_in_paths" cargo +nightly fix
cargo +stable fmt

Add wildcard lifetimes where they were previously elided

---

Cargo.lock
Cargo.toml
docs/BACKEND.md
src/bin/server.rs

This is a work in progress implementation switching from `civet` to `hyper` as the base http server.
This is based on `conduit-hyper` which I've updated to `hyper 0.11`.  That source code is [here](https://github.com/jtgeibel/conduit-hyper/blob/master/src/lib.rs).  A huge shout-out to @sfackler and @drbawb as this is forked from their repos.  I'm curios if either of you are still using this code and if you have any feedback.  I plan to eventually publish this crate on crates.io, so please let me know if you would like to be added/removed as an author or if you have any objections.
There are several things I wish to investigate further, including:
* I'm not yet sure if hyper handles panics.  I see no results searching for `catch_unwind`, so I'm assuming panics need to be handled in this …

Replace `civet` with `hyper` as http server

---

Cargo.lock
Cargo.toml
docs/BACKEND.md
src/bin/server.rs

This reverts commit ba6c689c2ebec7bcb8a9298de0750638af36c9ec, reversing changes made to 9b4a92cf16f712dbc4f3074fb40641b0f2b64c88.
This reverts the changes introduced in PR #1378.  The deploy has already been rolled back and this will get master back into a clean state so that deploys can be made if other issues arise before this bug can be resolved.  The code reverted by this PR was causing `cargo publish` to fail with a 404 error.
The issue appears to be triggered because `cargo publish` includes an additional `/` at the beginning of its route.  It is possible that civet removes this automatically before it gets to conduit's routing logic, and that hyper leaves the extra `/` intact, causing the routing logic to fail to find the correct handler.

Revert "Merge #1378"

---

src/bin/populate.rs
src/bin/render-readmes.rs
src/bin/update-downloads.rs
src/boot/categories.rs
src/controllers/crate_owner_invitation.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/email.rs
src/git.rs
src/github.rs
src/models/badge.rs
src/models/category.rs
src/models/dependency.rs
src/models/keyword.rs
src/models/krate.rs
src/models/user.rs
src/render.rs
src/router.rs
src/tests/all.rs
src/tests/krate.rs
src/tests/owners.rs
src/tests/record.rs
src/uploaders.rs

This diff was created from the latest nightly and passes checks on beta
(which will soon be stable).  As I understand it, Rust 1.29 will
include the rustfmt release candidate and we can expect stable
formatting from this point forward!
Bors should be able to merge this cleanly after the release tomorrow.  It will fail on CI for now.

`cargo +nightly fmt` to prepare for the next stable release

---

package-lock.json
package.json

Addresses https://github.com/rust-lang/crates.io/issues/1473. New
version of ember-keyboard fixes the issue around keycode vs. key,
allowing hotkey search for non-qwerty keyboards.

Update version of ember-keyboard

---

.travis.yml

* Only install node on the stable branch
* Move rustfmt-preview installation to the before_install step
* Clear target directory on nightly (downloaded crates and the index will still be cached)

Tweak a few things on CI

---

src/tests/all.rs
src/tests/category.rs
src/tests/keyword.rs
src/tests/krate.rs
src/tests/owners.rs
src/tests/team.rs
src/tests/token.rs
src/tests/user.rs
src/tests/version.rs

The `Arc<App>` is passed around a lot in the tests, but it isn't needed in many cases.

Quit cloning Arc<App> unnecessarily in tests

---

src/controllers/user/me.rs
src/db.rs
src/tests/all.rs
src/tests/badge.rs
src/tests/category.rs
src/tests/keyword.rs
src/tests/krate.rs
src/tests/owners.rs
src/tests/token.rs
src/tests/user.rs
src/tests/util.rs
src/tests/version.rs
src/views/mod.rs

This builds on the test infrastructure improvements made by @carols10cents.  In particular, it adds a `Response<T>` type that wraps the `conduit::Response` and a callback.  Tests can use the `good()` method which asserts that the response status is good and returns the deserialized `T`.  It is the equivalent of `::json(&mut ok_resp!(...))`. The `bad()` method is equivalent to `bad_resp!`.
The callback is called if the test calls `good()` on the response.  This allows helper methods to return a `Response<T>` with attached assertions that are run if the test expects the response to deserialize correctly, but are not run if the test expects an error response.

Build on the new test infrastructure and convert more tests

---

src/util/errors.rs

If you don't have the concrete error type you expect, or aren't sure
what you even have, figuring out the answer is incredibly frustrating
without this impl. We do not ever use the debug implementation outside
of tests.

Make `CargoError` implement debug

---

migrations/2018-10-17-203221_index_crates_name/down.sql
migrations/2018-10-17-203221_index_crates_name/up.sql

Our most time consuming query is coming from crawlers on /crates ordered
by name. It turns out this query was not using any indexes, as the only
index we have on `crates.name` is `canon_crate_name(name)`. An
alternative would be to order by `canon_crate_name(name)` instead, but
that shouldn't actually be able to change the order. This is a low write
table, so the extra index isn't a major cost. Adding an index instead of changing
the query means the effects of this change will be easier to see.
The weird index name is because we already have an index called `index_crates_name`.

Add a missing index on crates

---

Cargo.lock
Cargo.toml
src/tests/http-data/krate_new_krate_git_upload_appends
src/tests/krate.rs

Our git tests aren't actually testing very much at the moment. We can
replace the entire body of `commit_and_push` with `Ok(())`, and the
test suite would pass. Right now all our tests do is check that we
manipulated files in a given directory, which is more of an
implementation detail than anything else.
Aside from not actually testing what we want, these tests also break
with the setup I want to use for async index updates. Once the index
updates are off the web server, there's no reason we need to keep a
local checkout of the index. We can afford to just do a full clone every
time, which simplifies our code. Once we do that though, our tests can't
observe the directory the commit was made in.
Pushing to a remote repository doesn't actually update the files you
changed on disk. Instead, …

Fix our git tests to actually test that we pushed

---

Cargo.lock
Cargo.toml
src/models/dependency.rs
src/models/version.rs
src/old_semver/Cargo.toml
src/old_semver/src/lib.rs
src/util/request_proxy.rs

The amount of manual serialization/deserialization of semver stuff is
really starting to get in the way of refactoring. Semver supports both
Serde and Diesel on master (only serde in the released version, hence
the git dependency).
Conduit still expects an older version though. That project is
unmaintained and I've been having trouble getting added as an owner to
publish a new version (Alex is in Europe right now, not worth bothering
him) so we've got a little hacky workaround in the meantime.

Bump semver

---

src/tests/category.rs
src/tests/krate.rs
src/tests/owners.rs
src/tests/user.rs
src/tests/util.rs

This converts another batch of tests.  The first 3 commits are straightforward conversions.  The 4th commit includes 2 tests where I pulled some logic into closures.  It makes the tests much easier to follow, but the diff isn't as straightforward.  The final commit includes a few minor cleanups.

Convert more tests

---

src/app.rs
src/tests/all.rs
src/tests/category.rs
src/tests/keyword.rs
src/tests/krate.rs
src/tests/owners.rs
src/tests/token.rs
src/tests/user.rs
src/tests/util.rs
src/tests/version.rs
src/uploaders.rs

The unused `Uploader::NoOp` option is now `Uploader::Panic` which
panics on any usage.  The panic message directs users to initialize the
app with `TestApp::with_proxy()`.
While this adds more panics to the main lib, the application
configuration isn't dynamic and it should be obvious that
`Uploader::Panic` is not to be used to configure a production
application.

Add `TestApp::init()` for tests that don't need HTTP recording

---

src/middleware/mod.rs
src/tests/server.rs

And clarify who should be pinging whom (readers of the code should ping
the crates.io team)
CI is currently broken; this should fix it.
r? @sgrif

Temporarily disable the test requiring a user agent too

---

src/tests/krate.rs

This test wasn't technically wrong, it was just very confusing. The
`assert_dl_count` function was testing the length of the array returned
by the downloads endpoint. When we test that case insensitivity works,
this makes it look like there's a bug, since we'd intuitively expect
`assert_dl_count` expect 2 downloads. But it wasn't testing the number
of downloads, it was testing the number of records we returned (one
record per version per day that there were downloads). So the JSON we
returned was correct:
[
{
"version_id": 1,
"date": "2018-10-30",
"downloads": 2,
}
]
But the test didn't really reflect what we expected. This changes it to
actually test the sum of the "downloads" field, which is intuitively
what you'd expect this to be testing.

Fix the `krate::downloads` test

---

src/models/dependency.rs
src/models/krate.rs
src/tests/krate.rs

On the client side cargo checks dependency names against the index and
requires an exact match.  For instance, a user cannot depend on
`diesel-migrations` or `Diesel_migrations` as cargo generates an error
directing them to use the correct name `diesel_migrations`.
This check for an exact name match is now repeated on the server when a
crate is published.  This ensures that bugs in cargo or third-party
tooling cannot result in a dependency name that cargo is unable to
locate in the index.

Ensure only exact name matches are added to the index

---

src/tests/all.rs
src/tests/builders.rs
src/views/krate_publish.rs
src/views/mod.rs

This PR renames the structs in `views/krate_publish` to have the prefix `Encodable`, as per a `TODO` that was present.

Rename structs in `krate_publish` with prefix `Encodable`

---

src/controllers/krate/publish.rs
src/models/badge.rs
src/models/category.rs
src/models/user.rs
src/tests/all.rs
src/tests/badge.rs
src/tests/http-data/krate_new_krate_with_unverified_email_warns
src/tests/http-data/krate_new_krate_with_verified_email_doesnt_warn
src/tests/http-data/krate_new_krate_without_any_email_warns
src/tests/krate.rs
src/views/mod.rs

This is the start of the implementation of https://github.com/rust-lang/crates-io-cargo-teams/issues/8. 
We can start warning now; if folks are using nightly, cargo will show it. Next release, beta will show it, and then the release after that, stable will show it. We have until the release after THAT to implement the hard error. I think. If I've counted correctly.

Email verification warning

---

.travis.yml
script/cargo-clean-on-new-rustc-version.sh

Recently I've been monitoring where our CI time is spent.  Currently,
the build and test stages take about 14 minutes without a cache and
1.7 to 3.6 minutes when a cache is present.  The variation in the
latter comes from the `cargo install diesel_cli` step which is
partially rebuilt any time a new compatible version of a dependency
is published.
For each channel, we cache about 1GB of build artifacts.  This results
in a total of 4 minutes that are spent in caching related activities.
However, extracting the cache on Travis appears to be O(n^3) because
once a new version of rustc is released the size of the `target/`
directory doubles but cache extraction take 8 times as long and total
cache related time nearly quadruples to 13.5 minutes.  This effectively
wipes out any gains of caching …

Run `cargo clean` on CI when the version of rustc changes

---

app/templates/policies.hbs

I found the wall of text about the crawler policy less than readable, so I added some paragraph breaks and `<code>` tags in an attempt to make it slightly more readable. This doesn't change any of the text of the policy.

Make crawler policy more readable

---

src/models/dependency.rs
src/tests/builders.rs
src/tests/http-data/krate_new_crate_allow_empty_alternative_registry_dependency
src/tests/krate.rs
src/views/krate_publish.rs

See also #1579 and rust-lang/crates-io-cargo-teams#21.

Reject publishing of crates that depend on an alternative registry

---

app/styles/crate.scss
app/templates/crate/version.hbs

The crate heading text (with name and version) are being aligned by baseline using flex, however the icon doesn't line up because it doesn't have baseline information.
Manually pushing the icon down so aligns "correctly" with the crate name.
Before 🤢 🤮
After 🌹 🦄

Align crate icon with crate name in heading

---

Cargo.lock
Cargo.toml

Doesn't seem to cause compile issues.

Revert to release version of ring

---

Cargo.lock
Cargo.toml

This is required for us to continue to make any changes to Cargo.toml,
since all versions of ring except the most recent have been yanked. We
only depend on ring through cookie. Moving from cookie 0.9 to 0.11
doesn't appear to require any code changes in either our code or
conduit-cookie.
We can't use `[patch]` here, since it will not force Cargo to resolve to a
yanked version of a crate (it'll still just try to resolve
conduit-cookie 0.8.4 off the index which inevitably depends on ring 0.11
so it'll fail and go back to the last version which used openssl)

Update to the latest version of cookie

---

src/middleware/log_connection_pool_status.rs
src/middleware/mod.rs

On rare occasions we've had outages occur as a result of the connection
pool refusing to return any connections. Shortly before this occurs, we
start to see significant spikes in response times (likely because the
pool has begun serving only a 1 or 2 connections and there's a large
amount of contention).
Right now we have limited capability to debug this. The only
explanations that I can come up with are a bug in r2d2, or something is
happening causing our worker threads to be killed in a way that does not
run destructors, or something is causing threads to hang indefinitely.
If one of those three options above is true, we should see `connections - idle_connections`
trend towards zero over time, and diverge away from
`in_flight_requests` over time (they aren't expected to be exactly …

Log the state of the connection pool once per minute

---

Cargo.lock
Cargo.toml
src/app.rs
src/controllers/crate_owner_invitation.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/db.rs
src/middleware/current_user.rs
src/tests/all.rs
src/tests/util.rs

This is required to move forward on #1588, I have spun it off into a standalone PR for ease of review, since it's isolated and a change that makes sense on its own. This requires #1609 and includes those commits
Right now the way our test suite works is that we set the database
connection pool size to 1, and tell that single connection to start a
test transaction. This works, but has the caveat that only a single
reference to the connection can be live at any given time.
This becomes a problem when we add background jobs into the mix, which
will always want to grab two connections from the pool (and we still
need them to be the same connection). The code that we end up running
looks something like:
```
// In request
let conn = pool.get();
insert_background_job(&conn)?;
// In middleware …
```

Explicitly share a single connection in tests

---

src/controllers/version/deprecated.rs
src/controllers/version/metadata.rs
src/router.rs

Discovered that /crates/:crate_id/:version is used in the show_version
test RequestHelper function, so it probably shouldn't be marked as
deprecated even though the frontend isn't using it.
Takes care of the FIXME comment.

Split the two uses of version::deprecated::show into separate fns

---

src/tests/all.rs
src/tests/git.rs
src/tests/team.rs

`ATOMIC_USIZE_INIT` is deprecated starting in 1.34.  The new warning is
causing nightly to fail on CI.  For consistency, `Once::new()` is used
in place of `ONCE_INIT`.

Use `AtomicUsize::new(0)` in place of deprecated `ATOMIC_USIZE_INIT`

---

src/bin/update-downloads.rs
src/controllers/mod.rs
src/controllers/user/session.rs
src/models/category.rs
src/render.rs
src/s3/lib.rs
src/tests/badge.rs
src/tests/category.rs
src/tests/keyword.rs
src/tests/krate.rs
src/tests/owners.rs
src/tests/team.rs
src/tests/user.rs
src/uploaders.rs
src/util/request_proxy.rs

The warnings were ultimately from `clippy::needless_borrow` and
`clippy::redundant_clone`.

Temporarily deny clippy::nursery and fix warnings

---

Procfile

This reverts a portion of #1611.  Heroku does not make a checkout of
the source code available at runtime, so at the point in time we run
migrations `src/schema.rs` will not exist, and will thus always fail
this check.
The `--locked-schema` check is still run on CI, so this still gives us
confidence that our schema and `src/schema.rs` do not diverge.

Remove `--locked-schema` when running migrations on Heroku

---

Cargo.lock

I ran into this issue while trying to debug the login issue.  We have a
few dependencies that pull in an older version of `log`, which means
that, for instance, `RUST_LOG=oauth2=debug` doesn't work.  `log:0.3.9`
provides a semver compatibile wrapper around `log:0.4` which allows
logging to work for all our dependencies which support it.

`cargo update -p log:0.3.8`

---

app/components/badge-azure-devops.js
app/templates/components/badge-azure-devops.hbs
mirage/fixtures/crates.js
src/models/badge.rs
src/tests/badge.rs

I added a project of mine that is already using `Azure Devops` into `fixtures/crates.js`. Let me know if that's an inconvenience and I'll remove it. I just put it there to easily see that everything was working as expected.
I also added some tests by following the existing code example.
See also rust-lang/cargo#6264

Add support for Azure DevOps badge

---

src/controllers/user/me.rs
src/controllers/user/session.rs
src/email.rs
src/models/user.rs
src/tests/user.rs

Invalid emails from GitHub

---

.buildpacks
app/templates/policies.hbs
config/nginx.conf.erb
src/middleware/block_ips.rs
src/middleware/log_request.rs

This adds a restriction to the number of crates that can be published
from a single IP address in a single time period. This is done per IP
instead of per-user, since that's what we can do with nginx alone. We
may want to do additional rate limiting per token to force spammers to
register additional accounts, and not just change their IP.
This will use what's called the "leaky bucket" strategy for rate
limiting. Basically every user has a bucket of tokens they use to
publish crates. They start with 10 tokens available. Every time they hit
this endpoint, they use one of the tokens. We give them a new token each
minute.
What this means is that you can upload 1 crate per minute, but we allow
you to upload up to 10 in a short period of time before we start
enforcing the rate limit.
When …

Rate limit the crate publish endpoint

---

Cargo.lock
Cargo.toml
docs/BACKEND.md
src/bin/server.rs
src/old_semver/Cargo.toml
src/old_semver/src/lib.rs
src/util/request_proxy.rs

`conduit-hyper` now handles normalizing paths, such that `//api/v1`
becomes `/api/v1` and doesn't break our router.

Switch to `conduit-hyper` in place of `civet`

---

Cargo.lock
Cargo.toml
docs/BACKEND.md
src/bin/server.rs
src/old_semver/Cargo.toml
src/old_semver/src/lib.rs
src/util/request_proxy.rs

This reverts commit 69368a6efe228f3a7cc91a3b8783ff03ec9e9d92, reversing
changes made to 6fa8ad32cc3470b3d320d4620ba305c8d220ff2d.
When deploying this change, we saw response times nearly triple, and our
CPU usage went through the roof. Additionally, this did not appear to
fix the memory issues we were hoping to address by removing civet.
/cc @jtgeibel

Revert "Auto merge of #1618 - jtgeibel:conduit-hyper-round2, r=sgrif"

---

src/controllers/krate/publish.rs
src/tests/krate.rs

Because that's at least on 2019-02-28 (the date we announced) in all timezones,
and should definitely be after the release scheduled for that day.
As per the plan at https://github.com/rust-lang/crates-io-cargo-teams/issues/8
Needs to be merged and deployed anytime before 2019-03-01 00:00 UTC to be on time with our announced date.

Require a verified email after 2019-03-01 00:00 UTC

---

docker-compose.yml
frontend.Dockerfile

Fixes to frontend to make `docker-compose up` work again on a fresh clone.
Two fixes need to happen:
1. `npm install` needs to run when building the docker container, so that all of the dependencies exist.
2. A slight change to the `docker-compose.yml` file to properly link up the frontend to the backend.
---
*[Edit]: this previously consisted of only a single commit that looked at the frontend.Dockerfile file. As I continued trying to get an environment up, I noticed another fix that needed to be made and decided it was similar-enough in scope that it should be added to his pull request. The original description follows.*
**Add `npm install` to frontend Docker**
The frontend Docker image appears to be following a pretty standard Node
convention of adding the package.json, running `npm …

Fix frontend docker configuration in docker-compose

---

src/middleware/log_request.rs

We originally logged this in order to help us separate malicious
traffic. Ultimately we've never ended up using this at all. As we're
reviewing our privacy policies, this seems like a good time to stop
logging things we don't care about that expose additional information
about our users.

Stop logging the referer header

---

docker_entrypoint.sh

When using `docker-compose up` to bring up everything for development,
we mount the source directory as read-only so that changes can only
happen on the host machine and not because of something that the code
running in docker does.
This read-only mount was causing problems because `patch`, called by
`diesel migration run`, would try to write to the filesystem and fail.
When bringing up a docker environment for the first time from a fresh
clone, we expect that the schema.rs file is already pristine, and that
we just need to run migrations. For that reason, use `diesel migration
run`'s `--locked-schema` option to just run migrations.
This change makes it so that a new contributor can clone the repo, run
`docker-compose up`, and have an almost complete environment to poke at
and start …

docker: use --locked-schema for diesel migrations

---

Cargo.lock
Cargo.toml
docs/BACKEND.md
src/bin/server.rs
src/old_semver/Cargo.toml
src/old_semver/src/lib.rs
src/util/request_proxy.rs

If the `USE_HYPER` environment variable is set then `hyper` is used as
the backend server.  If the variable is not set, the default remains a
`civet` based server.
This has a trivial impact on build times and binary sizes, as `hyper`
is already pulled in (as a `Client`) on production via `reqwest`.
This will also aid in profiling performance differences, as backend
instances can be run in parallel in two terminals:
```
$ PORT=8888 cargo run --release --bin server
$ PORT=8889 USE_HYPER=1 cargo run --release --bin server
```

Add `hyper` support as a boot-time option

---

app/components/download-graph.js

When formatting download numbers in the download graph, use a consistent numbering format for both raw numbers and the rolling 7-day average.
There are cases where the user's local can make inconsistent formatting. Specifically, we use `Number.prototype.toFixed` to format the rolling 7-day average, which always results in a number format that uses a decimal point (e.g. "1234.56"). However, the raw download numbers end up using the locale, which in some places can end up formatting the number with a decimal as the thousands separator ("1.234").
To fix this, use google.visualization.NumberFormat for *both* values, so that they are always consistent.
Fixes #1628 
Note that I couldn't fully test this, because even after changing my browser's language to `de`, I would still see English number …

Use a consistent format for numbers in dl graph

---

Cargo.toml

This builds jemalloc with profiling enabled, and preserves debug symbols
in the release binary (note: `debug = true` does not disable
optimizations). This commit by itself doesn't actually perform any
profiling, but it allows it to be controlled by an environment variable.
At this point I cannot get any useful information about the memory issue
we're seeing in production locally. We also can't reproduce it in a
staging environment. There's *something* about our production traffic
patterns that we're missing, so the next step is to start looking at
dumps of production memory usage.
My intention is to start enabling sampling based profiling in
production, and copy some of the dumps off the server to examine
locally.

Allow profiling jemalloc

---

Cargo.lock

`hyper` and its dependencies are updated.  The overlap with other
production functionality is fairly minimal and comes from compatible
bumps to fairly foundational crates.  Below is a summary of the notable
overlap:
* `bitflags` - diesel, openssl
* `byteorder` - base64, diesel, libflate
* `hyper` - reqwest
* `lazy_staic` - openssl, ring, schannel, semver-parser
* `libc` - many crates, of course
* `time` - chrono, conduit_conditional_get, conduit_static, cookie, tar
The full output of the update command is below:
```
Updating arrayvec v0.4.7 -> v0.4.10
Updating bitflags v1.0.1 -> v1.0.4
Updating byteorder v1.1.0 -> v1.3.1
Updating bytes v0.4.8 -> v0.4.12
Updating cfg-if v0.1.2 -> v0.1.7
Updating crossbeam-deque v0.6.1 -> v0.7.1
Updating crossbeam-epoch v0.5.2 -> v0.7.1
Adding …
```

`cargo update -p hyper --aggressive`

---

script/ci/cargo-clean-on-new-rustc-version.sh

When we bump a low-level dependency, such as `libc`, a large number of
crates are rebuilt and this can grow our cache to the point where
caching hits a timeout (and is not persisted).
By changing the value of `manual_stamp` in the script, the cache can be
cleared without waiting for the next compiler release.

Add a manual trigger to clean the cache on CI

---

script/ci/cargo-clean-on-new-rustc-version.sh

Cache creation is currently failing on stable and beta channels.

Force a clean build on CI

---

Procfile
src/bin/update-downloads.rs

We're paying for a dyno that spends 90% of its time sleeping. A
repeating task like this is better handled by a cron-like tool (heroku
scheduler in our case), especially for something non-critical like
updating download counts.

Remove the worker dyno

---

Cargo.toml

It looks like hyper may have fixed our memory issue after all. I'd still
like to spend some time looking at heap dumps because I still think our
memory usage is higher than reasonable, but it's low priority and not
something I'm going to do this week, and leaving debug info on makes our
binaries *huge*

Turn off debug symbols

---

Cargo.lock
Cargo.toml
src/render.rs

The latest version of `comrak` requires an explicit opt-in to produce
unsanitized output (the previous default).  We already sanitize the
output with `ammonia` and `comrak`'s sanitized output is too
restrictive, causing 5 tests to fail.
Refs: #1265

Update to the latest `comrak` and `ammonia` for processing markdown

---

src/bin/server.rs

50 is probably way too high. @jtgeibel and I are interested in seeing
how this is affecting our memory usage, it'd be great to configure this
without a redeploy.

Make the number of threads on the server configurable

---

.buildpacks
.travis.yml
Cargo.lock
Cargo.toml
backend.Dockerfile
docs/CONTRIBUTING.md

The `git2` crate has dropped its dependnecy on `cmake` and we can as
well.

Bump `git2` and remove dependency on `cmake`

---

README.md

[![What's Deployed](https://img.shields.io/badge/whatsdeployed-prod-green.svg)](https://whatsdeployed.io/s-9IG)
Right now, this only includes prod, and it basically only provides the difference between production and master. Staging, oddly enough, is *behind* prod right now, so it doesn't actually work. If @ag_dubs updated staging to master, it would be possible to do a compare between all three (which is where whatsdeployed really shines). Compare https://staging-crates-io.herokuapp.com/api/v1/site_metadata with https://crates.io/api/v1/site_metadata

Add a whatsdeployed.io badge to README

---

src/app.rs
src/bin/background-worker.rs
src/bin/monitor.rs
src/bin/on_call/mod.rs
src/bin/server.rs
src/config.rs
src/controllers/site_metadata.rs
src/controllers/user/session.rs
src/db.rs
src/email.rs
src/lib.rs
src/models/category.rs
src/models/keyword.rs
src/tests/all.rs
src/tests/categories.rs
src/tests/record.rs
src/tests/util.rs

While doing memory profiling, I noticed that `dotenv` was being
initialized each time the `env` helper function was called.  With my
`.env` file in development it was (temporarily) allocating 9.7MB on
each call to the `env` helper.
The `dotenv::var` helper uses `std::sync::Once` and avoids this
duplicate work.  I don't expect this to improve allocation patterns on
production much/any, as without a `.env` file, only 1.9kB is
(temporarily) allocated.
Some binaries will initialize sooner and will pick up some variables that
would not previously work from `.env`.

Remove duplicate initialization of `dotenv`

---

src/app.rs
src/db.rs
src/git.rs
src/middleware/current_user.rs
src/middleware/run_pending_background_jobs.rs
src/models/user.rs
src/tests/all.rs
src/tests/read_only_mode.rs
src/util/errors.rs

This is in preparation for our next database upgrade. Last time we
needed to do this, we took the whole site down. This means that for 30
minutes, `cargo build` just didn't work. This is no longer something we
consider acceptable. While we could just take everything down *except*
`cargo build`, we can do better.
The upgrade process is basically:
- Set up a new replica of the primary database
- Wait until the replica is "caught up" (< 200 commits behind)
- Take down the site
- Upgrade the replica in place
- Verify the upgrade was successful
- Swap over to the replica
- Bring the site back up
There's no reason that we actually need to bring the site down though,
we just need to stop writing to the primary during the upgrade process.
This does that by setting the default transaction mode to …

Allow the database to be set in read only mode

---

src/controllers/version/downloads.rs
src/tests/krate.rs
src/tests/read_only_mode.rs

This ensures that the download endpoint still works even if counting the
download fails. The main case that we expect failure to occur is when
the application is in read only mode. However, even if an unexpected
failure occurs, we still want `cargo build` to succeed. Counting
downloads is always considered optional -- it's much more important that
people's builds succeed than having accurate download stats.
Note that we still require a database connection from the pool. In
theory, we could allow getting the version ID to fail as well, and just
blindly redirect to S3 no matter what, and rely on a 404 happening
there. However, this could result in successful builds in the event that
the index is out of sync with our DB, since we don't routinely clean up
the S3 bucket. Our current test …

Allow download counts to fail to be updated

---

src/controllers/krate/search.rs

Our database spends more of its time processing /api/v1/crates with no
parameters other than pagination. This query is the main one hit by
crawlers, and it is taking over 100ms to run, so it's at the top of our
list (for posterity's sake, #2 is copying `crate_downloads` during
backups, #3 and #4 are the updates run from bin/update-downloads, and #5
is the query run from the download endpoint)
The query is having to perform the full join between crates and
recent_downloads, and then count the results of that. Since we have no
search parameters of any kind, this count is equivalent to just counting
the crates table, which we can do much more quickly. We still need to do
the count over the whole thing if there's any where clause, but we can
optimize the case where there's no search.
This …

Optimize our most time consuming query

---

src/app.rs
src/bin/render-readmes.rs
src/bin/server.rs
src/config.rs
src/controllers/krate/metadata.rs
src/controllers/version/downloads.rs
src/github.rs
src/tests/all.rs
src/tests/util.rs
src/uploaders.rs

A `reqwest::Client` represents a pool of connections and should be
reused.  For the `server` and `render-readme` binaries, a single pool
is now used for all requests.
This should reduce allocation activity in production for routes that
make an outgoing HTTP connection.  Each initialization costs 30,255
allocations and 2.0 MB of allocated data.  This work is also done on a
new thread which will map it to a random jemalloc arena.  The
initialization is now done once when the server is booted and any
remaining per-request allocations will occur on a smaller thread pool.
This also cleans up how proxying is implemented when running tests.
Previously, the configuration was stored in the S3 `Uploader` but this
resulted in test failures when calling functions (i.e. `crate_location`
and …

Initialize a single `reqwest::Client` for the server process

---

app/routes/github-authorize.js
app/routes/login.js

The code was serializing an entire response object, which didn't
actually contain the errors that came back from the API, so we'd never
show anything other than "Failed to log in". With this change we now
show the error returned by the API if it returned any. Notably, if a
user tries to create a new account while we're in read only mode, they
will now see an error saying that.

Display errors during login

---

src/controllers/user/session.rs

Currently whenever a user signs in we attempt to update their profile
(display name, avatar, email, etc). If we're in read only mode, we can't
do that. However, preventing them from signing in entirely seems
unfortunate.
If we get a read-only error, we will now try to look for an existing
user, returning that user if found (or any errors that occurred loading
it), and continue to return `ReadOnlyMode` if we couldn't find an
existing user.
A user will have to sign out and back in again after maintenance has
completed if they want to update their information. Ideally we'd display
a warning informing them of this fact, but we don't currently have code
in place to support that, and with < 3 hours remaining until maintenance
time, there's not enough time to write it.
I'd also love to add some …

Allow existing users to sign in while READ_ONLY_MODE=1

---

app/routes/crate/version.js

Added check for yanked status when computing currentVersion

---

Cargo.lock

`cargo update -p flate2:1.0.1 --aggressive`
This updates the `flate2` we use in production.  We also pull in
`flate2:0.2.20` via `conduit-git-http-backend` which is a middleware
that is only enabled in development.
This addresses four instances of "Conditional jump or move depends on
uninitialised value(s)" raised when running
`valgrind --trace-children=yes cargo test`

Update flate2 to fix a few issues in valgrind

---

.travis.yml

Been testing against 11 locally for a while, but figured we should get a
travis run on this

Change Travis to PG 11

---

src/boot/categories.toml

As described in #1475, there are many crates related to cryptocurrencies, which don't have a better category than cryptography.

Add Cryptocurrencies category

---

src/bin/monitor.rs

We've noticed some common patterns in recent spam attacks. While our
response time on these has been ok, we can look for some of these common
patterns and page whoever is on-call earlier than we'd otherwise notice.
The exact patterns we look for is considered sensitive information, and
thus not in the repo and should not be discussed publicly.
Note that I've opted to look for crates that are likely spam, rather
than volume. Volume is more likely to have false positives, and is
better handled by more aggressive rate limiting.
This assumes that we consider a spam attack to be something we always
want to page for. Since we have better coverage of someone watching
discord most hours, we could alternatively have this post in a private
channel, and let whoever is awake determine if it's worth …

Add monitoring for common spam patterns

---

src/db.rs
src/middleware/current_user.rs
src/tests/owners.rs

`unused_imports` now triggers for redundant imports.
`diesel::Connection` is part of `diesel::prelude`, `mem::drop` is part
of `std::prelude`, and `InvitationResponse` was explicitly imported at
the top of the file

Fix new lint on nightly

---

README.md

We no longer use irc.mozilla.org.

Our chat is now on Discord

---

.travis.yml
config/environment.js
config/manifest.js
config/targets.js
ember-cli-build.js
testem.js

This pull request fixes all warnings from lint:js and enforces that by running the task on Travis CI.

 Make "npm run lint:js" happy

---

src/background_jobs.rs
src/controllers/krate/metadata.rs
src/controllers/krate/publish.rs
src/email.rs
src/middleware/log_connection_pool_status.rs
src/models/category.rs
src/models/dependency.rs
src/models/krate.rs
src/models/version.rs
src/render.rs
src/tests/record.rs
src/util/errors.rs

The lint is more sensitive starting in 1.34 (currently in beta).  This
addresses the new warnings so that CI isn't affected after the release
next week.
There is one case that recommends using `failure::error::Error::compat`
however we do not currently include `failure` in our TOML file.  Rather
than add it just for this case, I've allowed the lint for this
expression.

Fix new instances caught by `clippy::redundant_closure`

---

package-lock.json
package.json

... to resolve the duplicate `ember-cli-head` subdependency
This was caught by `ember-cli-dependency-lint` which I will add in a separate PR.

Update `ember-cli-meta-tags` to v5.3.0

---

package-lock.json
package.json

The main reason for this is that it deduplicates the `ember-cli-head` subdependency.

Update `ember-page-title` to v4.0.5

---

.travis.yml

Ignore auto instead of staging.tmp on Travis CI

---

Procfile

When we deploy today, the current process is as follows:
- Build new code
- If build fails, release is aborted, failed build does not affect
cache
- Shut down all dynos
- At this point requests are being held by the router until the new
dyno starts up. The 30 second timeout still applies, so we have to
boot and process the queued requests in under 30 seconds or they
will get a 503
- Wait for shutdown to complete
- Run database migrations
- If this fails, our app crashes, all requests will return 500 until
we manually intervene
- Boot app
- If this fails, our app crashes, all requests will return 500 until
we manually intervene
- Requests are processed
With this change, the flow will now be:
- Build new code
- Run database migrations
- If this fails, the release will not be deployed. The …

Use the release phase to run migrations

---

src/middleware.rs
src/middleware/require_user_agent.rs
src/tests/server.rs
src/tests/util.rs

We deployed this back in October, and quickly realized that old versions
of Cargo (Rust 1.15 and earlier) didn't set a User-Agent header.
Notably, the version of Cargo used for bootstrapping the compiler back
then was this old, so we accidentally broke the build for rustc.
We still see build traffic for these old versions, and we likely will
never be willing to break `cargo build` for old versions of Cargo.
However, as we discussed back in early November, we're fine with doing
this for all other endpoints.
This change will break versions of Cargo prior to Rust 1.16 for all
operations that talk to crates.io, except for `cargo build`. We no
longer receive any traffic for publish, yank, unyank, or owners from
these old versions. (`cargo search` hits an endpoint that is also hit by
bots, so I …

Require a User-Agent header, take 2

---

src/background_jobs.rs
src/bin/background-worker.rs
src/bin/delete-crate.rs
src/bin/delete-version.rs
src/bin/monitor.rs
src/bin/populate.rs
src/bin/render-readmes.rs
src/bin/server.rs
src/bin/test-pagerduty.rs
src/bin/transfer-crates.rs
src/bin/update-downloads.rs
src/db.rs
src/lib.rs
src/s3/lib.rs
src/tests/all.rs
src/tests/category.rs
src/tests/krate.rs

This series first addresses a warning now produced on nightly.  Then `clippy::all` and `rust_2018_idioms` are explicitly denied for all lib, bin, and test artifacts.
By denying `clippy::all`, the RLS will automatically show clippy warnings in an IDE.  This only affects the RLS and `cargo clippy --all-targets` should still used in a command line workflow.

Clippy cleanups

---

app/routes/github-authorize.js

The Github login is currently broken. The bug was introduced by upgrading ember-fetch in #1733.
This fix imports `serializeQueryParams` from its new location, which fixes the Github login for me. To verify, I followed the instructions in `docs/CONTRIBUTING.md`.
Clearly test coverage is insufficient. I'm happy to add tests as desired, but would like to get feedback what kind of test you suggest first.

Fix import for serializeQueryParams from ember-fetch.

---

ember-cli-build.js

In the production build all the SVGs are copied into dist/assets without fingerprints. All other assets have fingerprints. Since all files in dist/assets are served with far-future cache headers there would be cache issues if the files were ever updated. This is not major issue as these files are not used in normal operations.
Closes #1575

Fingerprinting SVGs

---

app/components/download-graph.js

The acceptance tests are failing for me when running them locally. Some tests error out with an error like this
```
not ok 122 Chrome 74.0 - [undefined ms] - Global error: Uncaught TypeError: window.google.visualization.arrayToDataTable is not a function at http://localhost:7357/assets/cargo.js, line 682
While executing test: Acceptance | crate page: /crates/:crate is accessible
---
browser log: |
testContext: [object Object]
ERROR: Uncaught TypeError: window.google.visualization.arrayToDataTable is not a function at http://localhost:7357/assets/cargo.js, line 682
...
```
while other tests time out (with a ridiculously long timeout of like three minutes per test). I get similar errors in the JavaScript console when loading the live version of crates.io in Chrome 74, though the page …

Only draw chart on crates page once Google Charts has been loaded.

---

app/serializers/version-download.js

Fix the following assertion error that occurs when running the frontend in debug mode, which cause graphs to not display at all.
> Assertion Failed: You must include an 'id' for version-download in an object passed to 'push'
This has been happening since 3c92ca2b46a6fd166b4ae556b3d925907c85250c landed.
The fix involves telling Ember how to create a unique ID for a version-download object, using the composite key.
I haven't been able to confirm, but I believe this is the reason that graphs in production are only ever counting/displaying a single version. When using this change locally in debug mode against the live website, the downloads graphs are rendering correctly.
Fixes #1704.

Fix assertion error in Ember for version downloads

---

migrations/2019-05-14-165316_index_crate_name_for_like/down.sql
migrations/2019-05-14-165316_index_crate_name_for_like/up.sql

A major performance regression was introduced by #1560, as it didn't
introduce the appropriate index and the query is now falling back to a
sequential scan. This has caused the query to increase from 12ms on
average to 756ms on average. This introduces the appropriate index,
bringing performance back to its previous levels.
Original Query
---
```
QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=180.26..180.26 rows=1 width=881) (actual time=0.509..0.509 rows=0 loops=1)
->  WindowAgg  (cost=180.26..180.26 rows=1 width=881) (actual time=0.508..0.508 rows=0 loops=1)
->  Sort  (cost=180.26..180.26 rows=1 width=873) (actual …
```

Fix performance regression on crate search

---

src/controllers/krate/search.rs

Even after #1746, we're still seeing a performance issue with search in
production. Now it's limited to searches that are a single letter, or
short 2 letter words like 'do'. It's caused by any search that would
cause PG to warn that the query contains only stopwords. It appears the
code path taken when `plainto_tsquery` returns an empty query is
substantially slower than it would be otherwise, even if the query
contains stopwords.
The reason this has started causing problems now is that #1560 caused
the query to change from performing a nested loop join to a hash join.
Due to what appears to be a bug in PG, `plainto_tsquery` is getting
called once per row when a hash join is performed. When the query is
passed as the only argument, the function is declared as `STABLE`,
meaning that within …

Further address performance regression in search

---

Cargo.lock
Cargo.toml
src/bin/server.rs

The server process now intercepts SIGINT and SIGTERM to initiate a
graceful shutdown of the server.
This is useful when tracking memory leaks locally, as both `hyper` and
`civet` are given a chance to return memory and shutdown cleanly.
However, this will not improve things in production as we also run an
instance of `nginx`, which will close all connections after receiving a
SIGTERM from Heroku.  From my preliminary investigation, it appears we
may need to customize the buildpack to change this behavior.
Additionally, the server will now briefly sleep before notifying Heroku
that it is ready to receive connections.  Also, when using `hyper` the
`Runtime` is configured to use 4 background threads.  This overrides
the default, which is one thread per CPU and provides consistency
between …

Add support for graceful shutdown of the server

---

src/controllers/krate/search.rs
src/models/krate.rs
src/tests/krate.rs

Since #1560 we've had various performance problems with search. While
we've addressed most of the biggest issues, we still have poor
performance when the search term is 2 characters or longer (between
100-200ms at the time of writing this commit, though there is a PR being
merged which can regress this another 30%).
This level of performance isn't the end of the world, but the majority
of our 1 or 2 character searches come from a handful of crawlers which
hit us very frequently, and I'd prefer not to spend this much time on
queries for crawlers. (There's quite a few of these, they all do things
like search for 's', then 'se', then 'ser', etc over and over again --
User Agent only identifies the HTTP lib they used, which varies).
The performance issues come from two places. The first …

Use a stricter form of search for extremely short queries

---

Cargo.lock
Cargo.toml
src/email.rs

This will fix our CI on the beta branch, which is currently failing due
to a known breaking inference change.  See rust-lang/rust#60958 for
more info.
I have reviewed the [upstream changes] relative to our current version
and see no issues with the changes there (although we could
alternatively backport just the needed fix).
[upstream changes]: https://github.com/lettre/lettre/compare/v0.9.0...0ead3cd

Update to latest master for lettre and lettre_email

---

Cargo.lock
script/ci/cargo-clean-on-new-rustc-version.sh

I have several local branches updating dependencies and addressing any
breaking changes (towards closing out #1265).  I'd like to avoid
lockfile merge conflicts between those branches so I'm bumping all
semver compatible versions in this PR.
I'd like to let this bake in production for at least a few days before
opening PRs bumping major versions in `Cargo.toml`.
If this approach is too aggressive, or needs to be reverted, I can open
the other PRs more serially and look into breaking this upgrade into
smaller pieces.

Run `cargo update`

---

src/controllers/version/downloads.rs
src/tests/krate.rs
src/tests/util.rs

Fixes #1687.
Crates are uploaded to S3 under the name they were first published as, but the download endpoint always uses the name as written in the request. If these names differ in their use of dashes vs. underscores, the download endpoint returns an invalid link.
To avoid adding another database request for every single crate download, this fix changes the database request that updates the download count to also return the original crate name. We will need to confirm that the performance impact of this change is negligible.

Return correct download link for requests for non-standard crate names.

---

src/render.rs

When browsing the code, I noticed that the HTML sanitzation code looked a bit messy, so I attempted to clean it up. This patch should not change the functionality in any way, but the new code may be easier to read and understand – not sure whether that's enough for you to spend time reviewing this.
I also wonder whether there is an explicit list of allowed tags in the code. The [defaults in the `ammonia` crate](https://docs.rs/ammonia/2.1.1/src/ammonia/lib.rs.html#260-269) look quite reasonable to me (we'd only need to add `input` for check boxes).

Clean up README rendering code.

---

app/routes/team.js
app/routes/user.js
src/controllers/krate/search.rs
src/tests/krate.rs

Add a URL parameter to the `/api/v1/crates` endpoint that specifies whether or not the endpoint should return crates that have been fully yanked - i.e., where every version has been yanked.
If not specified, this defaults to `true` because we have typically always returned all matching crates, whether or not their versions have been yanked.
This makes it possible to display only non-yanked crates at various places in the UI without changing Rust code.
Use this from the user and team pages to exclude yanked crates from them.
Closes #958

Exclude yanked crates on user/team pages

---

build.rs

Edits to `.env` may alter the value of the `TEST_DATABASE_URL` environment variable, so we should
rerun the build script if `.env` was changed. The build script is already configured to be rerun
when the value of `TEST_DATABASE_URL` changes, but the current setup does not capture changes
performed via `.env`, since the environment file is only loaded at runtime of the build script.
This change also removes the redundant `cargo:rerun-if-changed=build.rs`; the build script is always
rerun if it is changed.

Rerun the build script if `.env` has been changed.

---

src/tests/all.rs
src/tests/category.rs
src/tests/owners.rs
src/tests/user.rs
src/tests/util.rs

This converts the remaining tests to the newer test API, so that we can continue to move forward with improvements without some of the tests lagging behind. 
I do think there's more to be done to make the tests easier to read, write, and debug, and I am introducing some duplication and abstractions I'm not happy with. Next pass though.

Finish updating tests

---

src/render.rs

Clippy on the beta channel complained about this, so builds for new PRs won't pass unless we fix this.

Fix clippy error on beta.

---

Cargo.lock
Cargo.toml
src/controllers.rs
src/controllers/krate/search.rs
src/tests/all.rs
src/tests/krate.rs

As discussed in the May 30th team meeting
(https://discordapp.com/channels/442252698964721669/448525639469891595/583749739166695444),
this is the first step in deprecating/removing numbered pagination for
the "all crates" endpoint. The remaining steps are:
- Open issues/PRs on bots which have set a user agent that lets us
identify them, have them start following this link
- Change our frontend to show "next/prev page" links on the all crates
page
- Stop returning the "total" meta item when the next/prev page links
will be cursor based
- Switch the links over to cursor based pagination when applicable
- Error when given pagination parameters that would cause very high
offsets
Since the problem we're addressing only occurs when the offset is
greater than ~18k, the only place that we …

Include `next_page` and `prev_page` metadata on search

---

src/controllers/krate/owners.rs
src/tests/owners.rs
src/tests/team.rs
src/tests/user.rs
src/tests/util.rs

Fixes #1583.
The API endpoints to add and remove owners for a crate has multiple issues.
* The database interactions are not wrapped in a transaction, making them prone to race conditions.
* The lack of a transaction can also result in partially applied operations, e.g. when adding or
removing multiple owners at once.
* The check whether the last owner was removed only triggers if the _original_ list of owners had a
length of exactly one. This is wrong in at least two cases:
* Teams do not have permission to manage ownership, so they should not be counted.
* If multiple users are removed at once, we can end up with no owners even when there originally
was more than one user.
This change fixes all mentioned problems, and adds tests for all bullet points except for the first
one (which …

Fix checks and consistency in the API endpoints to manage ownership.

---

app/components/badge-cirrus-ci.js
app/templates/components/badge-cirrus-ci.hbs
src/models/badge.rs
src/tests/badge.rs

Upstream API: https://cirrus-ci.org/guide/writing-tasks/#embedded-badges
Modeled after https://github.com/rust-lang/crates.io/pull/807.

Support Cirrus CI badges

---

Cargo.lock
Cargo.toml

Also see #1754 where this workaround was originally added.  The changes
were released upstream in version `0.9.2`.

Switch back to released versions of `lettre` and `lettre_email`

---

src/controllers/krate/follow.rs
src/controllers/token.rs

These endpoints are obtaining two separate connections for each
request.  If there is a backlog of requests, then these endpoints will
wait in line multiple times for a database connection.
Any request with an auth token or cookie will also obtain and drop a
connection in the `CurrentUser` middleware.  We could consider caching
and reusing this database connection as well.

Remove duplicate calls to `db_conn` in a single endpoint

---

Cargo.lock
script/ci/cargo-clean-on-new-rustc-version.sh

Begin bisecting the segfault caused by a bulk `cargo update` by only
bumping a few dependencies.
`cargo update -p flate2:0.2.20 -p flate2:1.0.7 -p libflate -p tar --aggressive`

Update `tar`, `flate2`, and `libflate`

---

triagebot.toml

This adds [triagebot](https://github.com/rust-lang/triagebot) (@rustbot) to the repo, allowing people outside the team to relabel issues (with `@rustbot modify labels: foo bar`) and to claim issues for themselves (with `@rustbot claim`).
Currently non team members can add or remove any labels, but we can whitelist only a few of them if y'all want.
r? @sgrif

Add triagebot to the repository

---

src/middleware/ember_index_rewrite.rs
src/middleware/head.rs
src/router.rs
src/util/request_proxy.rs

The RequestProxy value is constructed 3 places, overwriting 1 of 2
values.  The fields are made private and 2 new constructors give each
use case a name.

Encapsulate the RequestProxy use cases

---

app/index.html
app/templates/application.hbs
config/manifest.js
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/search-test.js

To be clear that crates.io is a Rust package registry&mdash;in fact the _default_ crate host for Rust---this commit changes the `name`, `short_name`, and `description` fields in the manifest to reflect the nature of the project.  crates.io isn't really "Cargo", so it seems logical to me to not mention much about it, at least in the metadata for the site.
I also more explicitly mention that `crates.io` is the "default" package registry to be a bit more neutral; it's the baked-in default in Cargo, but there are others out there. I got the branding "Rust Package Registry" from the tagline in the visible top bar on the landing page.
Also, update the various acceptance tests that I found floating around.
Should resolve #1777, I think.

Adjust branding to reflect what crates.io actually does

---

src/bin/enqueue-job.rs
src/lib.rs
src/tasks.rs
src/tasks/update_downloads.rs

This replaces the `update-downloads` binary with a background job, and a
binary that is used to queue up a given job, which we will run from
Heroku scheduler. This accomplishes 2 things:
- It makes it easier to write tasks that need to run periodically (e.g.
cleaning up stale rate limit buckets), since we don't need to create a
new standalone binary.
- `update_downloads` and any future recurring tasks will automatically
get monitoring if they fail, since we are already monitoring for
background jobs not being successfully run.
Right now the intent is to have `enqueue-job update_downloads` get run
periodically by Heroku scheudler (and a similar scheduled task for any
future tasks that are added). Once swirl gains the ability to schedule
jobs to be run at arbitrary points in the future, we …

Move `update-downloads` to a background job

---

migrations/2019-08-07-153647_ensure_existing_crates_not_reserved/down.sql
migrations/2019-08-07-153647_ensure_existing_crates_not_reserved/up.sql

We've made this mistake twice now. If a record gets added to this table
and a crate already exists with that name, we will fail to update
download statistics as we can no longer update that row in `crates`. The
expected invariant is that the crates table never overlaps with
`reserved_crate_names`, we should enforce that remains true.

Don't allow crate names in use to be added to `reserved_crate_names`

---

docker-compose.yml

There's a typo in docker-compose.yml

Fix environment variable's name

---

src/bin/background-worker.rs

An incident was caused by #1798. There is a description below if you're
interested, but this PR does not fix the problem. However, the band-aid
to get things running again fix is to increase the timeout for the job
runner. When responding to an incident, waiting for a full rebuild to
change this is not acceptable. This replaces the hard-coded value with
an environment variable so we can quickly change this on the fly in the
future.
Description of the actual problem that this does not fix
--
The problem was that the `update_downloads` job takes longer than the
timeout we had set for jobs to begin running. So swirl would start the
`update_downloads` job, try to spawn another worker, and then would time
out hearing from that worker whether it got a job or not. So we would
crash the process, …

Configure the background job timeout via an environment variable

---

src/background_jobs.rs
src/bin/background-worker.rs

A brief incident was caused by #1798. A band-aid fix is in place, and
#1803 (included in this branch) makes it possible to apply similar
band-aids in the future without requiring a rebuild of the code. This
commit attempts to better address the root problem though.
The short version (which is expanded on below, but not required to
understand this commit or why it's needed) is that `update_downloads`
takes longer than our job timeout to run. When we moved that task to a
background job, we did not increase the number of concurrent jobs, nor
did we increase the timeout. This meant that swirl timed out trying to
start new jobs, and our behavior in that case was to crash the process.
This would mean that `update_downloads` never completes, and remains at
the front of the queue. This PR …

Make the job runner a bit more resilient to slow jobs or other errors

---

Cargo.lock
Cargo.toml

Docopt is only used directly in the `render_readme` binary, though this
does transitively update some crates that are used in production.
Refs #1265, #1805

Bump docopt 0.8 -> 1.1.0

---

src/config.rs
src/middleware.rs
src/middleware/block_traffic.rs
src/tests/all.rs
src/tests/server.rs
src/tests/util.rs

This generalizes the `block_ips` module to allow checking against any
header instead of just the `X-Real-Ip` header. This does not enable more
complex matching such as regexes, but it does let us apply the simple
string matching we have today to any header.
Additionally, which headers we check against is now configured by an
environment variable, which is a comma separated list in the form
`Header=VALUE_ENV_VAR`. So to keep the behavior we had today, one would
set `BLOCKED_TRAFFIC="X-Real-Ip=BLOCKED_IPS"`.
This means that when we see traffic patterns that we need to block which
can be handled by the existing logic, we can now begin applying it to
patterns we didn't previosuly anticipate without requiring a redeploy

Allow blocking arbitrary traffic without redeploying

---

src/bin/render-readmes.rs
src/s3/lib.rs
src/uploaders.rs

Currently the interface in the `s3` crate accepts the contents of an upload as a byte slice, which
so far isn't much of a problem, since crate uploads are generally below 10MB. When uploading public
database dumps to S3 (#1800), however, we don't want to keep the whole dump in memory at once.
This change basically changes the type of the uploaded content from `&[u8]` to a generic type
implementing `std::io::Read + Send + 'static`, which are the trait bounds `reqwest` requires for the
request body.
The PUT request to S3 needs to include a Content-Length header. Since a `std::io::Read` does not
have a length, we need to add another parameter for the content length, and pass it on to `reqwest`.

Allow streaming uploads to S3.

---

app/controllers/crate/version.js
app/templates/crate/version.hbs
tests/unit/controllers/crate/version-test.js

Fixes #1660.
Without this change, the page for a yanked version looks like this:
With this change applied, crate owners see this page instead:

Show right-hand column for yanked versions to crate owners.

---

.eslintrc.js
Procfile
app/index.html
app/styles/app.scss
config/environment.js
config/nginx.conf.erb
fastboot.js
fastboot/initializers/ajax.js
foreman-procfile
package-lock.json
package.json
src/bin/server.rs
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/search-test.js
tests/helpers/dom.js

Actually, without completely removing jQuery, FastBoot seems working.

Enable FastBoot

---

src/controllers.rs
src/controllers/category.rs
src/controllers/helpers.rs
src/controllers/helpers/pagination.rs
src/controllers/keyword.rs
src/controllers/krate/metadata.rs
src/controllers/krate/search.rs
src/controllers/user/me.rs
src/models/helpers/with_count.rs
src/models/krate.rs
src/tests/krate.rs

This continues the changes made in #1763. Since that PR was merged, one
of the non-code steps has been taken care of -- All users hitting any
endpoint with `?page=20` (which is an arbitrary search pattern that
seemed high enough to give any crawlers going through pagination) have
been contacted about the change, with a PR opened against any that
included a repo. (Intersting aside, there are *zero* records of this for
any endpoint other than search, which perhaps implies we can get rid of
a few of these endpoints, but that's a separate discussion).
This PR does not change any functionality, but moves some code around
to better encapsulate things for upcoming changes. Specifically:
- Change our frontend to show "next/prev page" links on the all crates
page
- Stop returning the "total" meta …

Refactor pagination to prepare for cursor-based pagination.

---

package-lock.json
package.json

broccoli-asset-rev 2.5.0 didn't work with FastBoot and we should upgrade
dependencies anyway.

Upgrade broccoli-asset-rev

---

package-lock.json
package.json

`npm install --save-dev nyc@14.1.1` to resolve some of the
vulnerabilities `npm audit` reports.

Upgrade nyc from 11.6.0 to 14.1.1

---

.eslintrc.js
app/mixins/rl-dropdown-component.js

During #1832, I've realized that the indentation on `app/mixins/rl-dropdown-component.js` is off.

Fix ESLint issues

---

app/routes/crate/version.js
ember-cli-build.js
package-lock.json
package.json

Our backend was behaving properly in this regard, but the front end was
considering any version that had build metadata to be unstable. There's
no reason for us to have this detection be hand-rolled, we can use a
proper semver library to determine whether something is a prerelease or
not.
I've manually confirmed this has the expected behavior for the crate
`openssl-src`, which was reported with incorrect behavior.

Don't consider versions with build metadata to be unstable

---

app/templates/application.hbs

This PR tweaks two things in the footer:
* A link to the [security policy](https://www.rust-lang.org/policies/security) was added: we had a person asking where to report a security issue on Discord, so hopefully this extra link should point people to the right disclosure guide.
* Removed a redirect when someone presses "Install": the old page it linked to ([`/install`](https://crates.io/install)) instantly redirected the viewer to [the cargo guide](https://doc.rust-lang.org/cargo/getting-started/installation.html), so I changed the link to point directly to it.
r? @sgrif

Tweak links in the footer

---

src/controllers/krate/search.rs

This changes the behavior of `/api/v1/crates` if no sort option is
provided. This does not change the behavior of the website when accessed
through a browser, as the Ember frontend always specifies a sort field.
The query run by search when sorting by recent downloads currently
accounts for nearly 40% of our total DB load. It takes ~60ms on average,
which means it's extremely high load. Our logs for traffic to this
endpoint with an explicit `sort=recent-downloads` don't match up with
this. We can fix this by making the query faster, but this has drawbacks
that were determined not to be worth it (see #1755). So if we can't
decrease execution time, the only other option is to decrease execution
count.
A significant number of crawlers hit us without specifying any sorting,
which should mean …

Change the default sorting on search to something less expensive

---

migrations/2019-09-15-194259_add_badges_crate_id_foreign_key/down.sql
migrations/2019-09-15-194259_add_badges_crate_id_foreign_key/up.sql
src/schema.patch
src/schema.rs
src/tests/load_foreign_key_constraints.sql

Since we may already have entries in the `badges` table referring to crates that don't exist, we
need to delete these entries before creating the foreign key constraint. This is a destructive
operation in the sense that it cannot be reverted, but it should only delete rows that should have
been deleted together with the crates they belong to.
We have a test to verify that all columns called `crate_id` are actually foreign keys referring to
`crates.id`. However, the query for the relevant columns contains the filter `contype = 'f'`,
effectively limiting the result to columns that already have foreign key constraints. This change
fixes the query to also allow `contype IS NULL`.
In addition, I modified the query to only verify tables in the schema `public`. This is useful for
an integration …

Add missing foreign key constraint for columns badges.crate_id.

---

migrations/2019-09-19-191534_remove-index-already-removed-in-prod/down.sql
migrations/2019-09-19-191534_remove-index-already-removed-in-prod/up.sql

This index doesn't exist in production currently, but it still exists in a db created from this codebase because we never made a migration to remove it.
Should be a no-op on prod so can be merged and deployed at any time.

Migration to remove an index already removed from prod by hand

---

script/ci/cargo-clean-on-new-rustc-version.sh
script/ci/prune-cache.sh

Build times have regressed and we are spending a lot of time doing caching stuff (and downloading/uploading 8GB of compressed data).  By manually wiping out the cache, stable and beta build times should align more closely with nightly (which is cleaned on every new nightly release).  This PR also fixes the list of pruned binaries:
* Remove update-downloads
* Add enqueue-job
* Sort alphabetically for easier comparison against `ls src/bin`

Travis cache fixes

---

Cargo.lock

cc @kemitchell, https://github.com/rust-lang-nursery/license-exprs/pull/30

Update license-exprs crate to support SPDX 3.6

---

app/styles/crate.scss

1. Fixed table from overflowing when the width is too large.
2. Removed a pointless CSS property. See https://developer.mozilla.org/en-US/docs/Web/CSS/float
`inline-block` is ignored due to the `float`.
If `float` has a value other than `none`, the box is floated and `display` is treated as `block`.
Fixes: #1638

Updated crate.scss

---

migrations/2019-09-18-233204_fix_int_type_in_to_semver_no_prerelease/down.sql
migrations/2019-09-18-233204_fix_int_type_in_to_semver_no_prerelease/up.sql
src/tests/krate.rs

Fixes #1839.
So the reverse dependencies API request for crc32fast started failing because the susu crate depends on crc32fast and has [published versions](https://crates.io/crates/susu/versions) like 0.1.20190509190436.
In the logs for the request that were responding with 500, I saw a message that said `value "20190409163015" is out of range for type integer` 😰 
So I went digging, and after isolating which query was the problem and then which part of the query was the problem, I figured out it was [this call to `to_semver_no_prerelease`](https://github.com/rust-lang/crates.io/blob/12c64bc716a4a7d1fd25f2a658f80cbdcbdcbf08/src/models/krate_reverse_dependencies.sql#L15).
That function was defined in [this migration](https://github.com/rust-lang/crates.io/blob/a27c704faa2982ddd75a3dc564da85c …

Support u64 version parts in SQL function semver_no_prerelease

---

app/routes/crate/version.js

Previously, if it had searched everything and found nothing. However, this also means it cannot find `maxVersion`, which was what it was set to before.
Thus, this commit's solution is to provide another fallback when there are no stable and non-yanked versions available. It will simply find anything that is not yet yanked even if it is unstable.
If even this fails, then we truly have nothing to offer thereby offering an empty page.
The code could be improved imo, but I am not especially well-versed in JavaScript.

Fixed versions suggestion

---

app/templates/crate/version.hbs

I completely removed the indication of which version the stats are being
displayed for because the graph labels already indicate the version being graphed.
Fixes #1275.

Removes "Showing stats for" dropdown

---

src/render.rs

Allow `rowspan` and `colspan` attributes of forms in READMEs.
Fixes #1863

Allow rowspan and colspan in markdown table rendering

---

app/components/email-input.js
app/components/pending-owner-invite-row.js
app/controllers/crate/owners.js
app/routes/confirm.js
tests/acceptance/crate-test.js

Caught request error objects do not have a payload property, this should start properly showing error details instead of the generic fallback message.
Fixes #1547

Fix error response payload parsing

---

Cargo.lock
Cargo.toml
src/render.rs

Closes https://github.com/rust-lang/crates.io/issues/1872.
I have followed the instructions on the issue. Basically removing that list of allowed elements and relying on ammonia to do the job and also upgrading ammonia to 3.0.

Ammonia 3.0 upgrade

---

migrations/2019-09-19-185655_add_experimental_indexes/down.sql
migrations/2019-09-19-185655_add_experimental_indexes/up.sql

@sgrif added these to the production database by hand for testing
purposes a while back; they seem to be performing well so they should
get added to the codebase to keep the schema in sync.
r? @sgrif, feel free to wait to merge this until you've checked the bloat you mentioned wanting to check; I'm happy to update this PR if needed. Just wanted to have something around as a reminder.

Add indexes in migrations that have already been running in production

---

src/bin/render-readmes.rs
src/render.rs

This just started failing builds since the new beta was cut. I'm going to merge this once CI passes.

Fix new clippy lint about unnecessary parens

---

Cargo.lock

This commit bumps a few additional packages that could be related to
the segfaults seen in production.  See #1805 for more info.
`cargo update -p backtrace -p rustc-demangle`
```
Updating backtrace v0.3.3 -> v0.3.38
Updating backtrace-sys v0.1.16 -> v0.1.31
Removing dbghelp-sys v0.2.0
Updating rustc-demangle v0.1.5 -> v0.1.16
```

Bump `backtrace` and `rustc-demangle`

---

src/render.rs

Fixes #1851 where SVGs from GitHub aren't rendered in READMEs if they use relative links.
First PR, so if I did something wrong point it out!

Fix GitHub relative SVGs not rendering properly

---

src/background_jobs.rs
src/bin/background-worker.rs
src/config.rs
src/git.rs
src/tests/all.rs
src/tests/util.rs

At the moment crates.io relies on Personal Access Tokens to be able to push changes to the index, but this is not great from a security point of view as it's not possible to scope a token to a single repository.
That means if an attacker managed to compromise the server hosting crates.io they'd be able to compromise other, unrelated parts of the Rust project infrastructure.
This PR changes crates.io to optionally support using deploy keys instead of tokens to push new commits to GitHub. Deploy keys are scoped to a single repository and can be either read-only or read-write (in our case we need write access).
The key must be stored in the `GIT_SSH_KEY` environment variable, base64-encoded. It has to be encoded as that way it's easier to copy-paste it, and the [setup-deploy-keys tool in …

Use deploy keys for git operations

---

app/styles/crate.scss
app/templates/components/crate-row.hbs
tests/acceptance/search-test.js

Adds the crate's last updated at time to search results on the right:
And with hover state to display exact date and time:
Happy to move it to a different location if preferrable, reasonable alternatives could be at the end of the quick links? or under the crate title?
Fixes #1597

Show crate last updated at on search results

---

app/styles/app.scss
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/search-test.js
tests/helpers/dom.js

This PR contains Fastboot-related fixes (from #1832) except for actually enabling Fastboot.
After merging this change, I'm going to submit a PR that updates package.json to include Fastboot in the dependencies.
Then I will submit a PR that enables Fastboot, based on USE_FASTBOOT env variable.

Preparation for Fastboot (1/3)

---

package-lock.json
package.json

Fastboot-related dependencies are added by the following "npm install"
commands:
* npm i --save fastboot-app-server
* npm i --save-dev ember-cli-fastboot
But Fastboot itself is disabled by having FASTBOOT_DISABLED=true.

Add Fastboot dependencies without enabling them

---

src/boot/categories.toml

This change adds the additional mathematics category, as well as removing "math" from the list of  fields covered by the "science"
category.
I think having a separate category makes a lot of sense, as mathematics related items can be related to e.g. simulations or games, which might be worth extracting it out from "science".
I would however like some input on the description. As a non-mathematician I'm not too aware of the range of mathematics crates that are available.
#1791

Add mathematics category

---

src/models/krate.rs

This switches to a manual check of the string prefix, because
`Url::parse` may sanitize URLs as they are parsed, making it
difficult to ensure both slashes are present.
Fixes: #169

Check that URLs begin with `http://` or `https://`

---

app/components/crate-row.js
app/components/crate-toml-copy.js
app/controllers/crate/version.js
app/styles/crate.scss
app/templates/components/crate-row.hbs
app/templates/components/crate-toml-copy.hbs
app/templates/crate/version.hbs

To copy the most recent version of a crate to the clipboard, users would have to go to the crate's individual page. However, it would probably be convenient to have the same control on the search results page. To accomplish this, a new component was created to encapsulate the copy control and its notifications (success/failure). This new component was added to the search result page; the crate page was reworked to use it as well.
For this first run at the UI, I added the same copy button to the left of the name/link for the result. I'm open to any other ideas too!
Here are some screenshots to illustrate the changes:
Fixes #1587

Add Cargo.toml copy button to crate rows

---

app/routes/index.js
app/routes/search.js
tests/acceptance/search-test.js

Not sure what the correct product choice is here, but this clears the search input when navigating back to index route if that is in fact the behavior that is preferred.
Fixes #1230 
(for some context both npm and rubygems.org do NOT clear the index if you search and then navigate back via browser, but both clear if you navigate forward to the index route via top left icon clicks)

Clear search input on index route

---

Cargo.lock

To get [this fix]. Emails with domains that start with a number were
incorrectly being marked as invalid.
[this fix]: https://gitlab.com/fast_chemail/fast_chemail-rs/commit/d5a621273e70b875eec36804d49c3e929244f14b

Update fast_chemail to 0.9.6

---

.travis.yml
script/ci/cargo-clean-on-new-rustc-version.sh
script/ci/prune-cache.sh

These changes started based on a discussion over on [internals](https://internals.rust-lang.org/t/evaluating-github-actions/11292/8?u=jtgeibel).  Basically, on every single build we end up touching some files and invaliding the caches.  This forces Travis to compress and upload a new cache on every single build.
This PR includes several changes on CI:
* Incremental compilation is disabled.  It appears that incremental files can change even if nothing in the codebase changes.
* Drop the `target/.rustc_info.json` file before caching, as it can change on each build.
* Running `cargo install` for the diesel CLI acts similar to a `cargo update` causing changes to the index and some caches maintained under `$HOME/.cargo`.  `cargo install` is now only run if the diesel binary is not on the path. …

Improve build caching on CI

---

src/bin/render-readmes.rs
src/s3/lib.rs
src/tasks/dump_db.rs
src/tests/record.rs
src/uploaders.rs

Adds cache control header with value `public,max-age=31536000,immutable` to all future crate and README uploads.
Fixes #1826

Upload all content to s3 as public and immutable

---

src/controllers/krate/publish.rs
src/middleware/log_request.rs

This pull request implements the first step in determining a maximum metadata size for uploads as described in issue 1896 [https://github.com/rust-lang/crates.io/issues/1896](url). There was no test added for this change as log output is not automatically tested.

conditionally add request metadata length to log output (no test)

---

src/email.rs
src/models/krate.rs

If the recipient of a crate ownership invitation has a verified email address, they will be sent an email indicating that a specified user has invited them to become an owner of a named crate. Only sends the email on the first instance of an invitation.
Completes the first part of #1360.

Send email on crate owner invitation

---

src/bin/transfer-crates.rs
src/controllers/krate/metadata.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/session.rs
src/controllers/version/deprecated.rs
src/middleware/current_user.rs
src/models.rs
src/models/krate.rs
src/models/owner.rs
src/models/user.rs
src/models/version.rs

Related: #1888 
This commit(s) prepares the migration to dropping `email` column from the `User` table.
Here, I introduce a new intermediate type called `UserNoEmailType`.
Copied from my latest commit:
Every queries out of `User`'stable should now be converted into an intermediate type called `UserNoEmailType`.
This is done by selecting only the appropriate columns which is defined in `user::ALL_COLUMNS` (notice that it excludes `email`) 
This could be renamed, I guess.
Conversion from this type to `User` is simply a copy except that `email` returned will always be `None`.
I think its possible to remove `email` from User directly because its not actually the mirror of `User`'s table.
The mirror struct is actually `NewUser`.

Preparation to drop `email` in User in Rust codes

---

Cargo.lock
Cargo.toml
script/ci/cargo-clean-on-new-rustc-version.sh

Overall, this drops 16 old versions of dependencies.  The `num-*` crates are on the list at #1805, but overall I think this is low risk to deploy together.
* `cargo update -p num -p num-iter -p num-traits --aggressive`
* `cargo update -p chrono`
* `cargo update -p migrations_macros -p derive_deref`
* Update to latest `dotenv`

Update chrono, dotenv, num-*, migrations_macros, and derive_deref

---

src/bin/render-readmes.rs
src/s3/lib.rs
src/tasks/dump_db.rs
src/uploaders.rs

Related issue:  #1915 
`extra_headers` parameter is no longer wrapped in `Option<T>`

Added cache control to readme files

---

src/bin/transfer-crates.rs
src/controllers/krate/metadata.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/session.rs
src/controllers/version/deprecated.rs
src/middleware/current_user.rs
src/models.rs
src/models/krate.rs
src/models/owner.rs
src/models/user.rs
src/models/version.rs

When reviewing #1911, I missed a spot. I reverted the PR merge on master, so this PR reverts the revert and adds the fix.
I tried to write a test that would have caught this, but I utterly failed at making a real-enough app/request that would have `.user()` but would let me set the `session()` :(
Also a lot of this code is temporary and will be undone once I've rebased #1891, but this needs to be deployed separately from #1891 to ensure there aren't any uses of the email column.
r? @jtgeibel

Missed a conversion from UserNoEmailType to User

---

app/routes/github-authorize.js
app/routes/github-login.js
app/routes/logout.js
src/controllers/user/session.rs
src/router.rs
src/tests/user.rs

This PR moves 3 remaining backend routes so that all backend routes are now scoped under `/api/`.  Upon further examination, I've determined that the initial OAuth callback is handled by the `/authorize/github` frontend route, which has not moved.  Therefore, this PR does not need to be synchronized with any changes to the GitHub OAuth settings!

Move 3 backend routes to `/api/private/session`

---

app/routes/crate/docs.js
app/routes/crate/repo.js
app/routes/install.js
app/services/redirector.js

Will add nginx.conf change after #1907. Early feedback is welcome!

Make /install work under FastBoot

---

app/components/api-token-row.js
app/templates/components/api-token-row.hbs
tests/integration/components/api-token-row-test.js

@locks I think this fixes the revoke button -- what I saw was `TypeError: input is null` on page load, when there isn't any input because a row hasn't been inserted yet.
This reverts the reverts and adds a null check.
r? @locks

Redo api row

---

app/components/api-token-row.js
app/components/owned-crate-row.js
app/controllers/me/index.js
app/models/owned-crate.js
app/routes/me/index.js
app/services/session.js
app/styles/me.scss
app/templates/components/owned-crate-row.hbs
app/templates/me/index.hbs

This commit adds the front-end capabilities to coincide with the API endpoint that was built on the server. There's also a small bug fixed in the api-token-row; it was throwing an error every time the "/me" route was loaded.
This PR addresses the second item in #1895.
I like how the UI ended up, but it may very well be creators bias :smile:. If this doesn't work, then I'll be happy to iterate!

front-end: Add email notification preferences

---

app/components/badge-bitbucket-pipelines.js
app/templates/components/badge-bitbucket-pipelines.hbs
src/models/badge.rs
src/tests/badge.rs

- based on #1782
- [link in screenshot](https://bitbucket.org/delan/nonymous/addon/pipelines/home#!/results/branch/branch%2Fname%2Fwith%2Fslashes/page/1)

add support for Bitbucket Pipelines badges (Shields.io)

---

.travis.yml
src/bin/background-worker.rs
src/bin/delete-crate.rs
src/bin/delete-version.rs
src/bin/monitor.rs
src/bin/populate.rs
src/bin/render-readmes.rs
src/bin/server.rs
src/bin/test-pagerduty.rs
src/bin/transfer-crates.rs
src/email.rs
src/lib.rs
src/models/version.rs
src/s3/lib.rs
src/tests/all.rs
src/tests/krate.rs

By denying warnings explicitly on CI, we don't need to deny warnings in each library or binary.  `#![warn(clippy::all)]` is used to automatically enable clippy in RLS enabled IDEs and `rust_2018_idioms` is now applied consistently.  Finally, clippy allow attributes that are no longer needed have been removed.

Add `-D warnings` to `RUSTFLAGS` on CI

---

app/styles/me.scss
public/assets/check-mark.svg

The content security policy of the production website was set up to not allow data URL's. Moving the logo to a static SVG policy fixes this.
Fixes #1938

Move check mark SVG to static file

---

src/models/team.rs
src/tests/http-data/team_add_owners_as_team_owner
src/tests/http-data/team_add_team_as_non_member
src/tests/http-data/team_add_team_mixed_case
src/tests/http-data/team_crates_by_team_id_not_including_deleted_owners
src/tests/http-data/team_nonexistent_team
src/tests/http-data/team_publish_not_owned
src/tests/http-data/team_publish_owned
src/tests/http-data/team_remove_team_as_named_owner
src/tests/http-data/team_remove_team_as_team_owner

I was having trouble adding the `github:awslabs:tough` team to [one of our new crates](https://crates.io/crates/tough) because the awslabs org has over 100 teams.
This allows users to use the 101st-created team on their GitHub organization for staggeringly large organizations by querying the team directly.
Test data was updated by hand per guidance in #crates-io, based on similar queries I made manually, but I would greatly appreciate if someone with access to actually make these API calls tested things work. :)

Query GitHub teams directly by name

---

bors.toml
docs/ARCHITECTURE.md

We've been using rust-lang's bors since
[2019-01](https://github.com/rust-lang/rust-central-station/pull/124)
and just never removed the references to bors-ng, oops

Remove bors-ng config; we now use rust-lang's main bors

---

src/controllers/user/me.rs
src/controllers/user/other.rs
src/tests/owners.rs
src/tests/user.rs

I found some places I missed checking for where we should be using the new `CrateOwner::by_owner_kind` helper method added in https://github.com/rust-lang/crates.io/pull/1901/commits/6d94155b4f80272adedc0c0fe3dbec77cf82f7e1 that adds the filter for `deleted` being false.
I've also added one test that currently passes and two tests that failed before this fix to hopefully cover everywhere that selects crate owners; the other places already have tests.

Use `CrateOwner::by_owner_kind` everywhere to exclude deleted ownerships

---

src/boot/categories.toml

Rename "Game engines" to "Game Development"

---

Cargo.lock
Cargo.toml
src/bin/server.rs

Background threads are now enabled for all artifacts by enabling the
`background_threads` feature.
Reviewing `jemalloc-sys` shows the underlying `jemalloc` version remains
unchanged at 5.1, so this is not expected to affect runtime behavior in
production.
Refs: #1265

Upgrade `jemallocator`

---

docs/CONTRIBUTING.md

`http://mailgun-documentation.readthedocs.io/en/latest/quickstart.html` is the broken link now, so `https://documentation.mailgun.com/en/latest/quickstart.html` looks good.

Fix the broken link in `CONTRIBUTING.md`

---

config/dependency-lint.js

We already run `npm run lint:deps` as part of CI, there is no need to also generate tests for this and slow down the build doing so.

dependency-lint: Disable `generateTests` option

---

config/nginx.conf.erb
script/ember.sh
script/start-web.sh

This adds a new mode to the `USE_FASTBOOT` environment variable.  The logic is now:
* When deployed on Heroku (staging or production - via `script/start-web.sh`):
* If `USE_FASTBOOT=staging-experimental` then non-backend requests are sent to FastBoot.
* If `USE_FASTBOOT` is set and non-zero length, FastBoot is enabled only for allowed paths.
* Otherwise (`USE_FASTBOOT` is not set, or is zero length), FastBoot is disabled.
* When doing local development (via `script/ember.sh`):
* If `USE_FASTBOOT` is set, all (initial) frontend requests are served via FastBoot.  This is equivalent to `staging-experimental` above.
* If `USE_FASTBOOT` is not set, FastBoot is disabled.
Because our development environment doesn't go through nginx, it isn't possible to support the "FastBoot is enabled only for …

Add a `USE_FASTBOOT=staging-experimental` mode

---

app/routes/crate/version.js
ember-cli-build.js
package-lock.json
package.json

... instead of using the complicated `app.import()` API

Use `ember-auto-import` to import npm modules

---

mirage/factories/category.js
mirage/factories/crate.js
mirage/factories/version.js
package-lock.json
package.json
tests/helpers/setup-mirage.js

`ember-cli-mirage` v1.0.0 removed its `faker` dependency in favor of importing via `ember-auto-import`. This PR adds an explicit dependency on `faker`, and migrates all the existing import to import from the `'faker'` module directly.

Migrate `faker` imports

---

Cargo.toml

It's not supported on macOS :(
When I try to `cargo run --bin server` on macOS Catalina 10.15.1, I get:
```
$ cargo run --bin server
Finished dev [unoptimized + debuginfo] target(s) in 0.51s
Running `target/debug/server`
<jemalloc>: option background_thread currently supports pthread only
memory allocation of 40 bytes failedAbort trap: 6
```
Leave [the upgrade](https://github.com/rust-lang/crates.io/pull/1953) but turn off the `background_threads` feature for now. [Someday we might be able to enable features per-target](https://github.com/rust-lang/cargo/issues/1197), but that day is not today.
r? @jtgeibel

Disable the background_threads jemallocator feature

---

src/controllers.rs
src/controllers/crate_owner_invitation.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/team.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/session.rs
src/controllers/version/deprecated.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/middleware/log_request.rs
src/tests/user.rs
src/util/errors.rs
src/util/errors/http.rs

This is a continuation of #1920.  This series captures several changes:
* The controller prelude is split to provide helpers for either cargo or frontend endpoints.  Eventually this will be unnecessary, but I see it as a temporary guard rail to encourage the correct usage.
* Several user and session frontend endpoints are updated to return a response with the correct HTTP status.  Tests were updated as necessary.
* A `util::errors::http` module is added for concrete error types associated with HTTP status codes.  There are more types to be moved here, but for review purposes that can be done in another PR.
* Once `cargo_err` was refactored to use `http::Ok`, all of the description and fallback logic in the `AppError` trait and `ConcreteAppError` type was no longer necessary.
Here is what …

Error response refactoring step 2

---

.travis.yml

Because branches that become PRs are built twice :(

Limit the branches that travis builds on

---

package-lock.json
package.json

to unblock the `ember-cli-htmlbars` updates

Update `ember-cli-babel` to v7.13.2

---

src/controllers/krate/metadata.rs
src/controllers/user/me.rs
src/controllers/version/deprecated.rs
src/controllers/version/metadata.rs
src/models/action.rs
src/models/version.rs
src/tests/krate.rs
src/views.rs

Add Verions Owner Actions to the API

---

package-lock.json
package.json
tests/integration/components/api-token-row-test.js

Since https://github.com/ember-cli/ember-cli-htmlbars/pull/286, the `ember-cli-htmlbars-inline-precompile` dependency is obsolete and replaced by `ember-cli-htmlbars` itself :)

Remove obsolete `ember-cli-htmlbars-inline-precompile` dependency

---

mirage/fixtures/crates.js

ember-cli-mirage v0.4.13 "fixed" the order in which fixtures are sent to the client (see https://github.com/miragejs/ember-cli-mirage/issues/1461). This PR adjusts our fixture order so that the tests will still pass after the upgrade, which should unblock https://github.com/rust-lang/crates.io/pull/1976.

mirage/fixtures/crates: Adjust fixture order

---

src/tasks/dump_db/dump-import.sql.hbs

- This allows `updated_at` field values to be loaded during import.
Before this change, `updated_at` was set to when the import ran,
overwriting the values being loaded.
- Also, the import completes in about one fifth the time
(on my slow MacBook Air).

Disable database triggers during import

---

app/templates/components/badge-gitlab.hbs

Fixes: https://github.com/rust-lang/crates.io/issues/1997

build.svg -> pipeline.svg to correctly display GitLab pipeline badge

---

app/templates/catch-all.hbs

DEPRECATION: Passing actions to components as strings (like `{{input
enter="search"}}`) is deprecated. Please use closure actions instead (`{{input
enter=(action "search")}}`). ('cargo/templates/catch-all.hbs' @ L6:C2)
[deprecation id: ember-component.send-action] See
https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more
details.

DEPRECATION: Passing actions to components as strings is deprecated.

---

app/routes/github-authorize.js

Accessing `queryParams` on the `transition` object was never officially public API in Ember.js, and has been deprecated in Ember.js v3.6 (see https://deprecations.emberjs.com/v3.x#toc_transition-state). Since it was only considered "intimate" API its removal was done in v3.9 instead of v4.0. Since we skipped both of these versions we unfortunately never saw the corresponding deprecation warning... 😞 
But even if we did upgrade to v3.8 LTS in between, we probably still would have missed it, because the `github-authorize` route is only called in a popup window where the usual DevTools console is not attached, and we unfortunately don't have any test for the login flow (yet!).
Closes https://github.com/rust-lang/crates.io/pull/2027, Resolves https://github.com/rust-lang/crates.io/issues/2028 …

routes/github-authorize: Fix `queryParams` code

---

app/templates/index.hbs

This fixes a paper-cut where after clicking on the button, clicking the
back button causes the user to immediately redirect again.
Additionally, on Firefox 71, it was not possible to long-click on the
back button to return to crates.io (as the only entry in the list was
the redirect.  On Chromium 79 I had no such issue.

Link directly to cargo install page

---

app/styles/app.scss

This is a different attempt to fix the percy problems; the percy yaml config doesn't work with the ember-percy version we're currently on.

Use the percy media query method to hide the downloads graph from percy

---

.editorconfig

We've switched to "2 spaces" (the default in Ember.js apps) quite a while ago, but apparently missed to adjust the editorconfig file. This PR adjusts the file to teach my editor to indent properly... 😅 
r? @locks

editorconfig: Adjust indent size for Ember-related files

---

app/serializers/api-token.js
app/serializers/application.js
app/serializers/crate-owner-invite.js
app/serializers/crate.js
app/serializers/dependency.js
app/serializers/version-download.js

This resolves a few deprecation warnings from Ember Data about using the implicit default serializer which will be removed in the next major version release
r? @locks

Extract `application` serializer

---

.template-lintrc.js

with a few rules disabled for now until we can comply with them...
The `no-curly-component-invocation` rule should in theory be able to run without issues but it currently seems to have a small bug that is causing false positives for us (see https://github.com/ember-template-lint/ember-template-lint/issues/1026)
r? @locks

template-lint: Use `octane` preset

---

app/adapters/application.js

`ember-data` will use it `fetch()` automatically now (see https://github.com/emberjs/data/pull/6082)
Resolves https://github.com/rust-lang/crates.io/issues/1995
r? @locks

Remove obsolete `FetchAdapter` mixin

---

.template-lintrc.js
app/templates/components/api-token-row.hbs
app/templates/components/email-input.hbs
app/templates/components/pending-owner-invite-row.hbs
app/templates/crate/owners.hbs
app/templates/crate/version.hbs
app/templates/dashboard.hbs
app/templates/me/index.hbs

see https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-button-type.md
r? @locks @NullVoxPopuli

template-lint: Enable `require-button-type` rule

---

app/mixins/rl-dropdown-component.js

because using `this.$()` on components is deprecated
r? @locks

rl-dropdown-component: Replace `component.$()` call with `$(component.element)`

---

.eslintrc.js
app/components/badge-maintenance.js
app/controllers/crate/version.js
app/mixins/authenticated-route.js
app/mixins/pagination.js
app/mixins/rl-dropdown-component.js
app/routes/crate/version.js
tests/unit/mixins/pagination-test.js

... and instead only disable specific cases using `eslint-disable-next-line` comments
Resolves https://github.com/rust-lang/crates.io/issues/2042
r? @jtgeibel

ESLint: Enable disabled rules

---

.template-lintrc.js
fastboot.js
mirage/fixtures/categories.js
mirage/fixtures/crates.js
mirage/fixtures/dependencies.js
mirage/fixtures/keywords.js
mirage/fixtures/teams.js
mirage/fixtures/users.js
mirage/fixtures/version-downloads.js
mirage/fixtures/versions.js

I was experimenting with the eslint setup, and it appears that some lint overrides are no longer needed.
This PR removes all results for `git grep "eslint-disable "` and removes some overrides in `.template-lintrc.js`.  There are 10 remaining needed `eslint-disable-next-line` usages.
r? @Turbo87

Remove some unnecessary eslint overrides

---

config/manifest.js

On current staging, but not production, navigating directly to a path
such as `/crates/crate-name` results in a request sent to
`/crates/cargo-835dd6a18132048a52ac569f2615b59d.png` (a 404 response
status).
It appears that the `src` field is now treated as a relative path.
Using an absolute URL works for me locally.
r? @Turbo87

Fix an icon link that was generating bad URLs

---

app/adapters/application.js

The backend was complaining about only accepting requests with a `User-Agent` header, so let's give it such a header 😉 
r? @locks

adapters/application: Pass `User-Agent` header to backend in fastboot mode

---

.env.sample

file:// URLs do not support relative paths. This change uses $PWD to make an absolute path based on where the user is running Crates on their local machine.
This fixes issue #2030

Use absolute path for GIT_REPO_URL file:// URL

---

.github/workflows/ci.yml
.travis.yml

On top of the production configuration, this commit adds two options:
* `abort:true` - most jemalloc warnings become fatal ([opt.abort])
* `junk:true` - both allocated and deallocated memory will be
initialized to 0xa5. ([opt.junk])
Combined with the existing `abort_conf:true`, this should be equivalent
to enabling the `debug` feature of `jemallocator`.  We cannot enable
this feature in `Cargo.toml` because that would affect performance in
production.
[opt.abort]: http://jemalloc.net/jemalloc.3.html#opt.abort
[opt.junk]: http://jemalloc.net/jemalloc.3.html#opt.junk

Enable debug MALLOC_CONF options on CI

---

.github/workflows/ci.yml

Based on the documented cache [restrictions], pull reqeusts are failing
to access the cache.  One solution is to alway build on master, because
all builds should be able to access caches created by the default
branch.
r? @jtgeibel
[restrictions]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

CI: Enable GH Actions on master branch

---

.github/workflows/ci.yml
.travis.yml

Our caching situation on GH Actions could use some work.  For now, I've added documentation with some initial thoughts.
This also adds `RUST_BACKTRACE=1` to help us debug random test failures on GH Actions: `panicked at 'Could not run jobs: NoMessageReceived'`.

CI: Add docs to GH Actions workflow and add `RUST_BACKTRACE=1`

---

src/tests/util.rs

The intermittent errors on GH Actions appear to be coming from two
places ([1], [2]) related to running background jobs.  It's possible
we're hitting the 1 second [timeout] and that the background job is not
completing in time.
Refs: #2059
[1]: https://github.com/rust-lang/crates.io/blob/e74de84f3d69dd623a83dfc0d8b43191e064104d/src/tests/util.rs#L76
[2]: https://github.com/rust-lang/crates.io/blob/e74de84f3d69dd623a83dfc0d8b43191e064104d/src/tests/util.rs#L190
[timeout]: https://github.com/rust-lang/crates.io/blob/e74de84f3d69dd623a83dfc0d8b43191e064104d/src/tests/util.rs#L236

Increase background job timeout for tests

---

config/nginx.conf.erb

In production we're currently returning a 502 Bad Gateway for
`/policies`.  I intend to merge this and deploy to production shortly.
This bug was introduced in #1907.  The bad check always evaluated to
true.  An explicit check for an empty string is added as well.  I've
tested this locally with `erb` and different values and the generated
configuration is now working correctly.
r? @jtgeibel

Fix fastboot check in nginx erb template

---

app/templates/application.hbs
config/optional-features.json
package-lock.json
package.json

This is one of the requirements to enable the "Octane" mode of Ember.js. It moves the implicit application template wrapper element into the `application` template and thus makes it optional for those applications that don't need it. Since we set a max width on this element we do currently still need it though.
r? @locks

Disable `application-template-wrapper` feature

---

app/index.html

I'm not sure when it got broken, but all of the crates.io brower tabs I have open currently say `crates.io: Rust Package Registry` when they previously said things like `mio - crates.io: Rust Package Registry` or `Search Results for 'mio' - crates.io: Rust Package Registry`. This patch fixes this.
There is a bunch of code that sets the page title dynamically,
but it is all being overridden by a title tag in the main
app/index.html template (the DOM is only allowed to have
a single title tag in it, so subsequent title tags are
ignored by all browsers).
There is probably a better way to do this (using fastboot
to fill in the correct title on the backend would be ideal)
but this patch should be enough to restore the dynamic
titles for browsers with javascript enabled.

restore crate prefixes to browser-tab titles

---

app/routes/login.js
app/templates/application.hbs
app/templates/components/flash-message.hbs
package-lock.json
package.json
tests/acceptance/login-test.js

This PR adds two basic application tests for the login button and the `login` route. Please note that this does not test the `github-login` and `github-authorize` routes yet, which we will do in a follow-up PR.
r? @locks 

tests: Add basic "successful/failed login" test cases

---

app/components/crate-readme.js
app/modifiers/highlight-syntax.js
app/templates/components/crate-readme.hbs
app/templates/crate/version.hbs
package-lock.json
package.json
tests/modifiers/highlight-syntax-test.js

This PR implements a new `highlight-syntax` modifier based on https://github.com/ember-modifier/ember-modifier and the existing `ember-prism` addon. That modifier is then used to apply the Prism.js syntax highlighting to all code blocks in the README, making the `CrateReadme` component obsolete.
r? @locks

Simplify README rendering using a new `highlight-syntax` modifier

---

src/middleware/log_request.rs

In production I observed serveral log lines with only " SLOW REQUEST".
Occasionally another thread will obtain the lock on stdout between our
calls to `print!()`.
This implementation consolidates the entire log line into a single
`println!()` and avoids an allocation unless an error is being logged.
r? @smarnach

Consolidate logging into a single `println!()`

---

src/controllers/krate/search.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/middleware/block_traffic.rs
src/models/badge.rs
src/models/keyword.rs
src/models/team.rs
src/s3/Cargo.toml
src/s3/error.rs
src/s3/lib.rs
src/uploaders.rs
src/util.rs

This commit reduces the usage of unwrap within the request/response
lifecycle, and documents a few remaining cases.  Usage of unwrap in
tests, binaries, or server boot code is generally okay and was not
reviewed.
Remaining work:
* Some usage of unwrap in `git.rs` and `src/tasks/` background jobs.
This code is not directly in the request/response lifecycle, but
should be reviewed.
* Current usage in middleware seems okay, but could be documented.
In most cases, such as with the handler in `AroundMiddleware`, the
conduit API ensures a handler is set.

Remove some usage of `unwrap()`

---

package-lock.json

It looks like dependabot is able to make a minimal incision and update
caniuse-lite without messing around with the rest of the package lock.
I suspect that dependabot will eventually get around to updating
caniuse-lite if we wait long enough, but I was curious to see how hard
it is to run manually, so I had a go. Turns out it's really easy, but
takes quite a long time.
Steps to reproduce:
* clone https://github.com/dependabot/dependabot-core
* docker pull dependabot/dependabot-core
* bin/docker-dev-shell
* bin/dry-run.rb --dep caniuse-lite npm_and_yarn rust-lang/crates.io
* paste the printed patch into a file (e.g. patchfile.txt)
* patch package-lock.json patchfile.txt
* npm ci && npm start
Fixes #1914

manually run dependabot for caniuse-lite

---

src/uploaders.rs

The headers intended for crates and readme uploads were swapped.
r? @smarnach

Fix cache control headers set for S3 uploads

---

app/templates/components/api-token-row.hbs

The lint references https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action.  There is no usage of `sendAction` in the component, so I believe no further changes are needed there.
r? Turbo87

Fix a deprecation warning during `ember build`

---

src/bin/background-worker.rs
src/bin/enqueue-job.rs
src/tasks/dump_db.rs
src/tasks/update_downloads.rs

Add more logging to background jobs

---

Cargo.lock

Bumping a few more dependencies from #1805.
* `utf-8` from 0.7.1 to 0.7.5
* `maplit` 1.0.0 to 1.0.2
* `filetime` from 0.1.14 to 0.1.15

Bump a few more backend dependencies

---

app/components/crate-toml-copy.js

I'm not sure what that call was originally supposed to do, but without it this seems to work quite fine and makes the "Copied!" notification appear again.
r? @locks

Fix `event.clearSelection is not a function` error

---

app/components/pagination.hbs
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crate/reverse-dependencies.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

Our pagination code was pretty much the same everywhere, so we might as well extract it into a shared component to simplify the styling and have a consistent implementation everywhere that is a11y-compliant.
r? @locks

Extract shared `Pagination` component

---

app/index.html
app/styles/app.scss

After having FastBoot, JavaScript would not be "required" but still
necessary for full functionality of crates.io.

Tweak <noscript> text and placement

---

app/controllers/application.js

Fixes #2106, I think.
I don't think we actually need this parameter set to null here?
Alternatively, the backend could be changed to treat "presence but empty" differently than "presence with value", which currently we do not :(

Remove default null setting of the all_keywords parameter

---

src/controllers/helpers/pagination.rs
src/tests/krate.rs
src/tests/user.rs

Errors in parsing the pagination query string parameters can be safely returned to the client and do not need to propagate up to the logging middleware.
The following have been observed in production logs:
* error="cannot parse integer from empty string" for `/api/v1/crates?page=&per_page=50&sort=downloads` (empty `page=`)
* error="invalid digit found in string" for `/api/v1/crates?page=1&per_page=100%22%EF%BC%8Cexception"` (very invalid `per_page`)
Additionally, 2 existing pagination errors are converted to use `bad_request()` in place of `cargo_err()`.  It is not necessary to send a status=200 response to support old versions of cargo for pagination errors.
Fixes:  #1928
r? @smarnach

Convert pagination ISE into a Bad Request response

---

tests/acceptance/search-test.js

These were made for testing, while the previous helpers worked, but had a different purpose. The advantage of the new helpers is that they are based on `@ember/test-helpers` and are calling `settled()` at the end to wait for any effects from the user interaction to settle.
r? @locks

tests/search: Use `ember-keyboard` test helpers

---

mirage/config.js
mirage/route-handlers/docs-rs.js

https://github.com/rust-lang/crates.io/blob/5cc7fb4d17c7400ce4a8db6218d6c773326b8de5/app/routes/crate/version.js#L31 is requesting data from docs.rs that we currently don't catch in our mock server. This MR adds a basic request handler for it that returns an empty response.
r? @locks

mirage: Add basic route handler for `builds.json` API from docs.rs

---

mirage/factories/crate.js

The `withVersion` trait does not seem to be used anywhere in the code (anymore?).
r? @locks

mirage/crate: Remove unused `withVersion` trait

---

mirage/factories/keyword.js
tests/acceptance/keyword-test.js

This will make it easier to create mock `keyword` resources in the future :)
r? @locks

mirage: Add `keyword` factory

---

mirage/factories/team.js
mirage/factories/user.js

This is roughly similar to #2128, but for the `team` and `user` resources.
r? @locks

mirage: Add `team` and `user` factories

---

mirage/route-handlers/crates.js

Our `GET /api/v1/crates/:id` mirage request handler was not handling unknown crates the same way as the production API server. This PR fixes the inconsistency by returning a 404 error if the client requests a crate that does not exist on the mock server.
r? @locks

mirage/crates: Return 404 if specified crate can't be found

---

src/models/krate.rs

This lint was recently added to nightly and is a reasonable change.
I plan to r+ soon, so:
r? @ghost

Fix a new lint - clippy::iter-nth-zero

---

mirage/factories/category.js
mirage/factories/crate.js
mirage/factories/version.js
package-lock.json
package.json
tests/acceptance/crate-test.js
tests/helpers/setup-mirage.js

This generally is easier to work with in my experience. If we want random values we can still generate them on a case-by-case basis, but by default we will have somewhat stable test fixtures now.
This should unblock #2120 :)
r? @locks

mirage/factories: Use predictable values instead of random fake values

---

mirage/route-handlers/crates.js

We had a lot of mirage request handlers that we failing with Error 500 when requesting unknown crates. This PR adds null checks that result in correct Error 404 responses.
r? @locks

Fix error handling for mirage request handlers

---

mirage/factories/dependency.js
mirage/factories/version-download.js

mirage: Add factories for `dependency` and `version-download` resources

---

tests/mirage/categories-test.js
tests/mirage/crates-test.js
tests/mirage/keywords-test.js
tests/mirage/summary-test.js
tests/mirage/teams-test.js
tests/mirage/users-test.js

For the frontend test suite we use a mock API server based on https://www.ember-cli-mirage.com/. Since we want to make sure that our mock server returns consistent results that match what the production server would return, we should also write tests for the mock server.
This PR implements a first few tests for our current mirage setup. The results of those tests are not entirely perfect yet so we will likely have to refactor some of the mirage code, which should become quite a bit safer with these new tests.
r? @locks

Add tests for the mirage mock server implemenation

---

src/controllers.rs
src/controllers/crate_owner_invitation.rs
src/controllers/krate/follow.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/util.rs
src/controllers/version.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/middleware.rs
src/middleware/current_user.rs
src/tests/all.rs
src/tests/authentication.rs
src/tests/util.rs

Many endpoints do not require user authentication, and by moving the
logic out of the middleware layer these endpoints now avoid obtaining a
database connection from the pool and 1 or 2 queries.
Due to lifetime issues a small middlware component remains.  Further
details are described in the middleware's documentation.

Defer user authentication until requested by endpoint

---

src/app.rs
src/config.rs
src/controllers/krate/downloads.rs
src/controllers/krate/metadata.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/version.rs
src/controllers/version/downloads.rs
src/db.rs
src/middleware/log_connection_pool_status.rs
src/models/krate.rs
src/tests/all.rs
src/tests/util.rs

Now that we have a read-only replica of the database, we can offload some read-only queries to it.  This commit series updates the `Config` and `App` structs to support a primary database and and optional read-only replica.
If the `READ_ONLY_REPLICA_URL` environment variable is set, a database pool of read-only connections will be initialized.  If the variable is not set, converted endpoints will fall back to the primary database pool (and are given read/write connections).
Tests do not configure a read-only replica and each test still operates within a single transaction.  Potential over-use of the read-only pool (in an endpoint that needs write access) can be detected in staging, by configuring `READ_ONLY_REPLICA_URL` to the same value as `DATABASE_URL`.
Current set of Endpoints:
* …

Use the read-only replica for some queries in production

---

config/nginx.conf.erb

This PR disables nginx access logs.  This should allow us to drop the `measure#nginx.service` filter in Papertrail.  I've tested this in my staging area and the nginx entries are no longer produced.

Disable nginx access logs on Heroku

---

.github/workflows/ci.yml

Based on a solution suggested by @pietroalbini.
I plan to push a few more things to this branch to test things and will probably drop the cache of rustc.  So for now, 
r? @ghost

CI: Include rustc version in key for `target/` cache

---

app/components/crate-list-newest.hbs
app/templates/crate/version.hbs
tests/acceptance/crate-test.js
tests/acceptance/front-page-test.js

I made three changes to improve the experience.
The homepage links go to the overview instead of a specific version
I added the version next to the stats, so you can tell what they are for.
I added a link back to the overview page next to the stats.
On the overview page it looks like this "Stats Overview"
On a specific version it looks like this "Stats Overview for 0.2.4 (see all)"
Resolves issue #2143
Remaking to run job again

Resolves issue 2143

---

.eslintrc.js
package-lock.json
package.json

This is needed to convert the `app/router.js` file to an ES6 class (see https://github.com/rust-lang/crates.io/pull/2149#issuecomment-578534173), and now the default in Ember.js apps (see https://github.com/ember-cli/ember-new-output/blob/v3.15.2/.eslintrc.js).
r? @locks

ESLint: Use `babel-eslint` parser to allow decorators and field initialization

---

src/tasks/update_downloads.rs

If we defer the update to `version_downloads.counted` until immediately
before the commit, it should eliminate the contention between counting
new downloads and propagating previous downloads.
Refs: #2153
See also: https://github.com/rust-lang/crates.io/issues/2153#issuecomment-577504032

Update `version_downloads.counted` last to minimize lock contention

---

app/initializers/set-global-promise.js

This is no longer needed in modern Ember.js projects
r? @locks

Remove obsolete `Promise` global override

---

docs/CONTRIBUTING.md

I had a little difficulty getting my Postgres database setup (I'm using Ubuntu on Windows Subsystem for Linux). With some creative googling I figured it out, but thought I would update the instructions to make it easier for the next person :)
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>

updates postgresql setup instructions

---

src/tasks.rs
src/tasks/update_downloads.rs

If multiple instances of this job are run concurrently then it is
possible to overcount downloads, at least temporarily.  The job first
selects all matching `version_downloads` and later uses those values to
calculate how many downloads to add to `versions` and `crates`.  If a
second job is run, it would select some rows from `version_downloads`
that were already queued for processing by the first task.
If an overcount were to occur, the next time the job is run it should
calculate a negative adjustment and correct the situation.  There's no
point in doing extra work and if we eventually need concurrency we
should built that out intentionally.  Therefore, this commit wraps the
entire job in a transaction and obtains an transaction level advisory
lock from the database.
If the lock has …

Ensure the update_downloads job doesn't run concurrently

---

src/bin/render-readmes.rs
src/controllers/krate/publish.rs
src/controllers/user/session.rs
src/models/dependency.rs
src/render.rs

Option::as_deref was introduced in rustc 1.40.0.  There is a new clippy lint on nightly that recommended the changes in the first commit.  The second commit converts 2 other equivalent syntax forms.  The old forms were:
* `as_ref().map(String::as_str)`
* `as_ref().map(|s| &**s)`
* `as_ref().map(|s| &s[..])`

Use Option::as_deref to convert Option<String> to Option<&str>

---

Cargo.lock
Cargo.toml
src/git.rs

replaces `tempdir` which is deprecated with `tempfile`

Replace `tempdir` with `tempfile`

---

src/router.rs

`serde_json` tweaks the visibility of `ErrorCode` and `syntax()` so they are not available with further version(1.0.45). I don't update deps at this point but this tweak should be useful for further work.

Remove use of private items

---

src/tasks.rs
src/tasks/update_downloads.rs

It appears that the additional wrapper transaction added around the
update_downloads task causes delays and timeouts to download requests
whenever the background job is run.  Reverting so that master can be
deployed.
r? @ghost

Revert changes to update_downloads task in #2157

---

src/boot/categories.toml

Right now the closest thing in the list to computer vision is `science::robotics`. Computer vision algorithms are not always used for robotics. This slug also allows computer vision crates to be found easier instead of being lost among the other robotics crates.

Add computer-vision slug

---

README.md

~~Prevents unexpected failures from being displayed.~~
Since we don't gate on GH Actions currently, so display the Travis badge until we resolve everything in #2059.

Revert status badge to travis

---

app/components/crate-row.hbs

Make crate stats look more consistent

---

app/styles/app.scss
app/styles/categories.scss
app/templates/categories.hbs

This PR aims to close #544, and just adds a div and some styles for it.
<details><summary>📸 Before</summary><img width="1036" alt="image" src="https://user-images.githubusercontent.com/1566689/74396257-0aa34100-4dd7-11ea-9f77-c27cca629da6.png"></details>
<details><summary>📸 After</summary><img width="1040" alt="image" src="https://user-images.githubusercontent.com/1566689/74396288-260e4c00-4dd7-11ea-9c48-04bf3f9c814b.png"></details>
Wording and stylesheet placement is absolutely negotiable!

frontend: Document category proposal system and categorization process

---

app/controllers/crate/version.js
app/mixins/rl-dropdown-component.js
app/routes/crate/version.js
package-lock.json
package.json

`no-observers` now complains imports. We can also disable at file level, it's an option.
Closes #2198
r? @locks

Bump eslint-plugin-ember from 7.7.2 to 7.8.1

---

src/git.rs

We're losing jobs to publish crates. It's not clear why. The requests
are returning 200, which implies they are being queued correctly. There
is no log to indicate that these jobs failed, so right now I believe
that this job is erroneously returning `Ok` when it failed. Given GitHub
is having a partial outage, that seems to reinforce this theory.
From looking at the code, this looks like the only way we could have
returned `Ok` when the publish failed. I believe we got some sort of
error response (or lack of one) from GitHub that caused this callback
not to be run.

Don't return `Ok` if update handler isn't run

---

Cargo.lock

Introduce new lockfile format, as suggested in #2195.
r? @jtgeibel

Introduce new lockfile format

---

package-lock.json
package.json

I've bisected the issue with the broken "New Token" button to this merge.  What is very strange is that the original commit 28a03bfd that implemented the change does not appear to have this issue.  Therefore it seems the issue is some sort of conflict between multiple pull requests somewhere in https://github.com/rust-lang/crates.io/compare/c970817d...663259cb.
I'm deploying to staging now and will deploy to production as soon as I test the change there.
cc @locks
r? @ghost

Revert #2201 to fix broken new token button

---

Cargo.lock

Update `tempfile` and `uuid` to remove `rand` v0.5

---

Cargo.lock

This series does an aggressive update for `conduit-hyper` and then `reqwest`.  This portion of the dependency tree has been updated recently and we aren't using `conduit-hyper` in production yet, so this should be fairly low risk even though it bumps a lot of crates.
The commit messages show the detailed output of each command.
cc #1805
r? @JohnTitor

Aggressively update conduit-hyper and reqwest

---

app/helpers/format-num.js

There is no need to implement this ourselves, and using the native browser APIs for this will make it easier in the future to localize the application.

helpers/format-num: Simplify implementation using `Intl.NumberFormat`

---

src/bin/server.rs

When using `conduit-hyper` to serve requests, if the max thread count is
reached then new requests are rejected immediately rather than blocking.
The fallback value for `SERVER_THREADS` is increased to ease local
testing when setting `USE_HYPER=1`.
cc #2204

Increase the default thread count to 5 in development

---

Cargo.lock

```
Updating arrayref v0.3.5 -> v0.3.6
Updating backtrace v0.3.38 -> v0.3.44
Updating backtrace-sys v0.1.31 -> v0.1.32
Updating byteorder v1.3.2 -> v1.3.4
Updating curl v0.4.12 -> v0.4.25
Updating curl-sys v0.4.16 -> v0.4.26
Updating failure v0.1.5 -> v0.1.6
Updating failure_derive v0.1.5 -> v0.1.6
Updating safemem v0.3.0 -> v0.3.3
Updating socket2 v0.3.8 -> v0.3.11
Updating synstructure v0.10.2 -> v0.12.3
Updating typenum v1.10.0 -> v1.11.2
```
r? @JohnTitor

Aggressive update of oath2

---

app/controllers/category/index.js
app/controllers/crates.js
app/controllers/keyword/index.js
app/controllers/me/crates.js
app/controllers/search.js
app/controllers/team.js
app/controllers/user.js
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/me/crates.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs
src/controllers/krate/search.rs
src/tests/krate.rs
tests/acceptance/search-test.js

This change adds the option to sort crates by "Newly Added" on the following pages:
- `/crates`
- `/search`
- `/users/:user_id`
- `/teams/:team_id`
- `/keywords/:keyword_id`
- `/categories/:category_id`
- `/me/crates`
Sorting is performed using the `crates.created_at` column.
I've put "Newly Added" as the last option in the dropdown:
Let me know if you would like a different label or for the order to be different.
I couldn't find any existing frontend tests of changing sort order. I'd be happy to add some as part of this PR if they would be valuable.
Closes #1919.

Enable sorting crates by most recently added

---

tests/models/crate-test.js

these tests help in isolating the issue that is causing the CI failure in https://github.com/rust-lang/crates.io/pull/2224
r? @locks

models/crate: Add tests for `inviteOwner()` / `removeOwner()`
