rust-lang/crates.io

app/templates/install.hbs

Change install instructions

---

app/controllers/search.js
app/routes/search.js

I'm an Ember novice, so please let me know if there's a better way to do this!

Give the search results page a title

---

app/controllers/crate/index.js

Reverts rust-lang/crates.io#181

Revert "Make graph version numbers not wrap"

---

app/controllers/crate/index.js
app/controllers/crate/reverse-dependencies.js
app/controllers/crates.js
app/controllers/keyword/index.js
app/controllers/keywords.js
app/controllers/me/crates.js
app/controllers/me/following.js
app/controllers/search.js
app/routes/crate/index.js
app/routes/keyword/index.js
app/routes/keywords.js
app/routes/me/crates.js
app/routes/me/following.js
app/routes/search.js

After this PR is merged we should be alright to upgrade to Ember 2.x without any major issues.

Resolved remaining Ember 1.13 deprecations

---

.jshintrc
app/mirage/config.js
app/mirage/fixtures/search.js
app/mirage/fixtures/summary.js
app/mirage/scenarios/default.js
bower.json
package.json
tests/.jshintrc
tests/acceptance/front-page-test.js
tests/acceptance/search-test.js
tests/helpers/has-text.js
tests/helpers/start-app.js

This PR adds two basic acceptance tests for the index page and the search functionality. The implementation is probably not perfect yet but I wanted to get it out there before going on vacation next week. I'll continue improving it after I get back in January.

Ember: Acceptance Tests

---

app/styles/app.scss
app/templates/application.hbs

Fix menu dropdown and add searchbar to mobile layout

---

bower.json

issue with ember, ember is pending a release. This is the short-term fix.

[fixes #246]

---

app/routes/crate/index.js

Fix trailing slash redirect breaking browser back button

---

src/tests/krate.rs
src/version.rs

This shouldn't be deployed until December 11th, but I'm opening it now so we don't forget.

Forbid wildcard dependency constraints

---

src/tests/user.rs

This PR should fix the TravisCI build again.

Remove unused import

---

app/components/download-graph.js
app/controllers/crate/version.js
app/routes/crate/version.js
app/styles/crate.scss
app/templates/components/download-graph.hbs
app/templates/crate/version.hbs
config/environment.js

this resolves the `// TODO: move this to a component` comment

Ember: Extract download graph component

---

README.md

I still get an error with these changes:
```
$ npm run start:local
> cargo@0.0.0 start:local /Volumes/Aldith/Developpeur/crates.io
> ember server --proxy http://127.0.0.1:8888
Cannot find module 'jshint'
Error: Cannot find module 'jshint'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:289:25)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at Object.<anonymous> (/Volumes/Aldith/Developpeur/crates.io/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/index.js:6:16)
at Module._compile (module.js:425:26)
at Object.Module._extensions..js (module.js:432:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:313:12)
at Module.require (module.js:366:17)
at require (module.js:385:17)
npm ERR! Darwin 14.5.0 …
```

Update installation and first run instructions

---

bower.json
package.json

I skipped 2.2.0 because everything was going so smoothly.
All tests pass, I clicked around locally and it seemed to be working fine.

Upgrade ember

---

app/styles/app.scss
app/templates/application.hbs

Ok, next try. See screenshot...

Add Cargo documentation dropdown to the top nav bar (better spacing this time)

---

src/bin/migrate.rs
src/keyword.rs
src/tests/keyword.rs

Ignore case for crate search

---

.jscsrc
app/router.js
package.json

So, mostly what was blocking this update was new defaults in our linter tool. I turned them all back to false, and fixed some indentation.
@alexcrichton @wycats do you have opinions about these particular settings?

Greenkeeper ember suave 3.0.1

---

.env.sample

fixing typo in postgres db location comment

---

README.md

Per conversation on Twitter:
- https://twitter.com/rustlang/status/768248262235226112
- https://twitter.com/rustlang/status/768248406343032832
I set things up and recorded the gaps between the Readme and my experience.
_According to the traditions of my people, every pull request should come with a cute animal picture:_

Update README based on experience with OS X setup

---

app/templates/crate/version.hbs

adding badges to crate page

---

package.json

adding dashes to yarn run commands to pass extra args

---

app/styles/crate.scss
app/templates/components/crate-row.hbs

adding docs, homepage, and repo links to crate-row/search

---

.travis.yml
tests/acceptance/search-test.js

Fix the frontend search test looking for the version

---

app/templates/application.hbs

https://github.com/rust-lang/cargo/issues/3387

Add links to new documentation sections

---

app/templates/category/index.hbs

Show the category description on the category page

---

src/categories.toml

Make development category less Rust-specific

---

src/categories.toml

For crates such as https://github.com/mehcode/config-rs

Add "Configuration" category

---

app/router.js
app/routes/crate/repo.js

fixes #520 by adding a /repo url redirect similar to /docs redirect

adding auto redirect to repo when hitting crates /repo url

---

app/templates/crate/version.hbs

Add text stating that the crate has no dependent crates #379

---

.buildpacks

The patch we needed has been merged

Go back to the main rust buildpack

---

Cargo.lock
Cargo.toml
src/tests/all.rs
src/tests/version.rs
src/util/request_proxy.rs

Ran cargo outdated and found a bunch of stuff to upgrade. Only a few little things in the code and tests needed to change.

Upgrade all the things

---

app/templates/application.hbs

See https://github.com/rust-lang/cargo/pull/3865

Sync doc sections

---

src/dependency.rs
src/tests/http-data/krate_new_krate_non_canon_crate_name_dependencies
src/tests/krate.rs
src/version.rs

Fixes #651. I can't figure out how to call the sql function `canon_crate_name` on each value in the `any` by using diesel's DSL, soooo.... going back to one query per dep.
r? @sgrif ?

Fix publishing with deps

---

src/krate.rs

The current code is racy and can result in rows with duplicate
(version_id, date)s. This is a problem because of the unique index added
in c46c384: before that, the race condition just causes duplicate rows.
Now, this will cause download requests to fail. Let's not do that :)
r? @sgrif ?

Upsert into version_downloads to avoid creating duplicates

---

src/krate.rs

Started fixing up the backend to allow the ability to track if the search-crate was a `perfect match`.

Working on issue 493

---

src/owner.rs

The GitHub team ID is unique and stable, so we look up teams based on
that, but the `github:org:team` login value, the team name, and the team
avatar might have changed so we should update that.
Fixes rust-lang/crates.io#446.
Fixes rust-lang/cargo#4019.
Fixes rust-lang/crates.io#625.
r? @sgrif because diesel?

Upsert based on GitHub team ID in case of org/team renames

---

.travis.yml

This changed recently, see
https://github.com/travis-ci/travis-ci/issues/4681#issuecomment-304919767

Explicitly specify the default build in the matrix

---

src/user/mod.rs

Github link in /users route works now

---

app/controllers/search.js
app/templates/search.hbs

Resolves #738. I'm happy to make any changes necessary so feel free to suggest wording, styling and code.

Link to getting started guide when search result is empty

---

Cargo.lock
Cargo.toml
src/download.rs
src/krate.rs
src/schema.rs
src/tests/krate.rs
src/version.rs

As I was going through the code for the /downloads endpoints, I did a
bit of additional refactoring to make the intent more clear. I've also
changed these endpoints to properly return a 404 error code rather than
a 200 with a message.

Port crate/download and supporting endpoints to Diesel

---

mirage/fixtures/crate_teams.js
mirage/fixtures/team.js
mirage/fixtures/user.js

Should've rebased #785 before merging... Sorry!

Convert remaining JSCS directives to ESLint

---

.travis.yml

see https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/.travis.yml#L12-L13

CI: Use recommended yarn installation method

---

app/adapters/application.js
app/controllers/dashboard.js
app/controllers/me/index.js
app/routes/application.js
app/routes/crate/version.js
app/routes/github-authorize.js
app/routes/github-login.js
app/routes/index.js
package.json
yarn.lock

This reverts commit dbc1c9a08b3d9f79fab8e4bef27692aeb38f5a42. The changes were causing login to fail; I've filed #820 to track fixing whatever the problem is :-/

Revert "Replace ic-ajax & other ajax calls with ember-fetch"

---

app/templates/application.hbs

related to conversation with @withoutboats and @carols10cents

feat(footer): add link to policies

---

app/serializers/dependency.js
app/templates/crate/reverse-dependencies.hbs
mirage/config.js
src/dependency.rs
src/krate.rs
src/tests/krate.rs

This PR is a rebase of https://github.com/rust-lang/crates.io/pull/810, but this time including the necessary changes to the frontend. I've tested this locally using the staging API and everything seems to work as intended now.
Resolves #306

Fix reverse dependencies query

---

src/categories.rs
src/category.rs
src/config.rs
src/dependency.rs
src/download.rs
src/git.rs
src/keyword.rs
src/krate.rs
src/lib.rs
src/owner.rs
src/s3/lib.rs
src/upload.rs
src/uploaders.rs
src/user/mod.rs
src/version.rs

I was trying to track down a problem and kept being sad by missing Debug derivations. No longer!

Derive debug on all the things!

---

src/tests/version.rs
src/version.rs

Since `authors` was only used in one place for this query, I didn't
think it was worth keeping an instance method or even a Diesel
association around.

Port version/authors over to Diesel

---

mirage/factories/crate.js
mirage/factories/version.js
mirage/fixtures/crates.js
mirage/fixtures/versions.js
mirage/serializers/application.js
mirage/serializers/crate.js
mirage/serializers/version.js

mirage: Move "links" into serializer

---

.gitignore
package.json
yarn.lock

see https://github.com/ember-cli/ember-cli/releases/tag/v2.14.0

Update "ember-cli" to v2.14.0

---

Cargo.lock

update Diesel 0.15.0 to 0.15.1

---

src/user/mod.rs

This was a fairly trivial route to port. I'm a bit worried that it has 0
text coverage though.

Port `/authorize` over to Diesel

---

src/krate.rs
src/tests/krate.rs

Initial implementation of documentation blacklist

---

.travis.yml

i'm going to merge this myself with bors-ng to test, eees wafer thin

Don't build the bors-ng staging.tmp branch on travis

---

src/categories.toml

Slug for simulation frameworks or executables.

Added simulation slug

---

src/bin/delete-version.rs

The changes here were broadly similar to those in `delete-crate`. The
child row deletions are no longer needed here, as they cascade in the
database. (Arguably neither of these binaries are really needed anymore
since it can just be done in the database)

Port `bin/delete-version` to use Diesel

---

src/bin/populate.rs

This was a pretty straightforward piece to port. Once tuple inserts are available (Diesel 1.0 likely) this would probably benefit from getting rid of the struct that's only ever used once. I switched to using Chrono here, as the `time` crate doesn't have a type that maps only to a date, so it has no type that Diesel supports for insert here.

Port `bin/populate` over to use Diesel

---

src/bin/transfer-crates.rs

I noticed a bug in this script as part of porting it over. It was
previously updating the `crate_owners` table without filtering on
`owner_kind`, which would be very bad if there were a team with the same
ID. I've fixed that bug as part of this port.

Port `bin/transfer-crates` over to Diesel

---

src/user/mod.rs

This is weird and not a great example and we should have a comment here
explaining why :)

Add a comment explaining why gh_id needs a `> 0` condition here

---

app/routes/login.js

Instead, set it to undefined.
Fixes #954.

Don't delete window.github_response, not allowed in strict mode

---

app/styles/crate.scss

CSS: Restrict readme image width

---

app/templates/crate/version.hbs

Fixes #967.
This is still untested as I will need to setup my environment, but I am opening this to get early feedback.
(Hello from rustconf)

Fallback to description if the crate has no readme

---

docs/CONTRIBUTING.md
docs/PR-REVIEW.md

@vignesh-sankaran Want to take a look at this and let me know what you think? Is this helpful? Anything missing?

Add a document describing how to do a pull request review

---

Cargo.lock
Cargo.toml
src/render.rs

You should probably rebuild all the READMEs after this.

Upgrade to ammonia 0.7.0

---

migrations/2017-09-26-200549_users_lowercase_index/down.sql
migrations/2017-09-26-200549_users_lowercase_index/up.sql
src/tests/krate.rs
src/tests/user.rs
src/user/mod.rs

Make users::show() case insensitive

---

src/krate/mod.rs
src/tests/krate.rs

The changes to the test crate descriptions are because the test enforces sort order.
Closes #1065

Made the search feature -/_ insensitive.

---

package-lock.json

From 4edd14eb59facc14e6167381bf96bace4240022d

Add qunit-dom to package-lock.json too

---

docker-compose.yml
docs/CONTRIBUTING.md
frontend.Dockerfile

neunenak found some yarn stuff still hanging around!! oops!!

Remove some vestigial yarn mentions

---

app/routes/dashboard.js
app/routes/keyword/index.js
app/routes/team.js
app/routes/user.js
app/serializers/crate.js

... to make sure we're not missing any arguments.

Use `...arguments` for `this._super()` calls

---

app/mixins/authenticated-route.js
app/routes/application.js
app/services/session.js

Test coverage for this stuff is not great, but I tested it manually. (I have the whole stack running locally now \o/)

Don’t use global events for login action

---

package-lock.json
package.json

/cc @locks @sivakumar-kailasam

Update `ember-cli-sass` to v7.1.7

---

package-lock.json
package.json

Extracted from https://github.com/rust-lang/crates.io/pull/1279
/cc @CvX

Update qunit-dom to v0.5.0

---

app/controllers/dashboard.js
app/routes/dashboard.js
app/routes/team.js
app/routes/user.js

* Remove fetchingFeed property - it was only being set, but not read anymore
* Remove `data` and `crates` properties - those two controllers (team, user) have been using only their models for some time now

Remove a bit of unused frontend code

---

.travis.yml
package-lock.json
package.json
tests/acceptance/categories-test.js
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/keyword-test.js
tests/acceptance/search-test.js
tests/acceptance/team-page-test.js
tests/acceptance/user-page-test.js

Use percy.io for visual testing

---

ember-cli-build.js
package-lock.json
package.json
tests/helpers/setup-mirage.js

Fixes remaining issues in Percy. Continuation of #1292 and #1295. Third time's the charm? 🙃
Closes #1293 (addresses issues raised by @jtgeibel - thank you! 😃)
cc: @Turbo87

Freeze the time in frontend tests.

---

app/templates/application.hbs
package-lock.json
package.json

This version has better fastboot compatibility 🚀

Update `ember-page-title` to v4.0.3

---

.template-lintrc.js
app/templates/application.hbs
app/templates/components/api-token-row.hbs
app/templates/components/badge-appveyor.hbs
app/templates/components/badge-circle-ci.hbs
app/templates/components/badge-codecov.hbs
app/templates/components/badge-coveralls.hbs
app/templates/components/badge-gitlab.hbs
app/templates/components/badge-is-it-maintained-issue-resolution.hbs
app/templates/components/badge-is-it-maintained-open-issues.hbs
app/templates/components/badge-maintenance.hbs
app/templates/components/badge-travis-ci.hbs
app/templates/components/crate-row.hbs
app/templates/crate/version.hbs
app/templates/dashboard.hbs
app/templates/team.hbs
app/templates/user.hbs
package-lock.json
package.json

This PR adds a dev dependency on https://github.com/ember-template-lint/ember-cli-template-lint to make sure templates are pretty 😉

Add `ember-cli-template-lint` dependency

---

package-lock.json
package.json

see https://github.com/patience-tema-baron/ember-keyboard/releases/tag/v3.0.0
/cc @tchak

Update `ember-keyboard` to v3.0.2

---

.eslintrc.js
app/components/email-input.js
app/controllers/index.js
app/controllers/search.js

“Use brace expansion”
cc: @Turbo87

ESLint: fix “ember/use-brace-expansion” error.

---

.eslintrc.js
package.json
tests/.eslintrc.js

Update ESLint configuration to match ember-cli blueprint

---

.eslintrc.js
app/controllers/me/index.js
app/models/crate.js
app/routes/dashboard.js
app/routes/index.js
tests/acceptance/crate-test.js

“Only string, number, symbol, boolean, null, undefined, and function are allowed as default properties”
cc: @Turbo87

ESLint: fix “ember/avoid-leaking-state-in-ember-objects” error.

---

config/environment.js
package-lock.json
package.json

see https://github.com/ember-cli/ember-cli-app-version#heroku

 app-version: Use `SOURCE_VERSION` env var if available

---

config/environment.js
config/manifest.js
config/targets.js
ember-cli-build.js
testem.js

Continuation of #1320 (see: https://github.com/rust-lang/crates.io/pull/1320#discussion_r179233216)
cc: @Turbo87

Remove extraneous eslint-env comments.

---

.eslintrc.js
app/components/rl-dropdown.js
app/styles/app.scss

“Don't use .on() in components”
cc: @Turbo87

ESLint: fix "ember/no-on-calls-in-components" error.

---

package-lock.json
package.json

I've tested this using the test suite and manually, and it seems to work fine
/cc @tchak

Update `ember-data` to v2.18.2

---

app/controllers/application.js
tests/acceptance/search-test.js

Focus on search on Shift+S

---

app/index.html

Resolves #1341
/cc @sgrif @pravic

Add missing `<title>` tag

---

src/middleware/blacklist_ips.rs
src/middleware/debug.rs
src/middleware/mod.rs

We're seeing some suspicious traffic that we think is the causing enough
load to be the source of our overall performance problems.

Add the ability to blacklist IPs

---

src/router.rs

There are 3 main types of errors encountered at the router level:
* Specific HTTP error responses such as `NotFound` and `Unauthorized`
* Human errors, returned as a json response with status 200
* Unexpected errors from libraries and `internal()`
These tests help document the current error handling behavior at the router level of the stack.

Test error handling logic in the router

---

src/controllers/krate/search.rs

I was going through our log filters to see if they were all still
needed. We were specifically filtering out `text-search query doesn't
contain lexemes: ""`. This happens whenever someone runs `cargo search`
with no parameters, resulting in a request like `?q=&page=1`.
Rather than filtering this out of our logs, let's avoid doing full text
search at all. This will reduce load on our DB server. This does change
the behavior from returning nothing to returning the first 10 crates,
but that's probably what the user wanted anyway.

Don't do full text search on empty strings

---

package-lock.json
package.json

This apparently resolves some npm slowness when installing deps of the project.

Update `ember-cli-code-coverage` to v1.0.0-beta.4

---

.travis.yml
package-lock.json

because it's quite a bit faster :)

CI: Use Node 10

---

package-lock.json
package.json

Resolves a few `npm audit` warnings among other things :)

Update `ember-cli-mirage` to v0.4.7

---

package-lock.json

Fixes more `npm audit` warnings :)

 Update more subdependencies

---

src/tests/all.rs
src/tests/krate.rs

Follow-up with a test for #1448

Add a test that hard links are rejected

---

src/boot/categories.toml

Some crate examples are listed on this site: http://robotics.rs/

Add robotics category

---

Cargo.lock
Cargo.toml
src/tests/all.rs
src/tests/krate.rs
src/tests/owners.rs
src/tests/team.rs
src/tests/version.rs

Opening this to see what people think of this; eventually want to get rid of all the new_req* functions.
This is what I was talking about @jtgeibel

Test code refactoring experiment

---

app/styles/crate.scss

Show follow/unfollow button on mobile

---

src/bin/update-downloads.rs
src/controllers/krate/publish.rs
src/models/version.rs
src/tests/all.rs
src/tests/builders.rs
src/tests/krate.rs
src/tests/schema_details.rs
src/tests/user.rs
src/tests/version.rs

These commits contain minor test cleanups and convert some additional tests to the new infrastructure.

Convert more tests

---

config/nginx.conf.erb

Connects to #1643.
I'm going to merge and deploy this once it passes CI to unblock @behnam from publishing.

Increase publish rate limit from 10 to 30

---

package-lock.json
package.json

see https://github.com/simplabs/qunit-dom/blob/master/CHANGELOG.md

Update `qunit-dom` to v0.8.4

---

.travis.yml

Run Frontend's tests and Backend's tests in parallel.

Run Frontend's tests separately

---

.travis.yml
package-lock.json
package.json

see https://github.com/salsify/ember-cli-dependency-lint#motivation for more information

Use `ember-cli-dependency-lint` to warn about duplicate addons

---

app/components/download-graph.js
app/components/google-jsapi.js

We may need to remove jQuery before enabling Fastboot.

Remove jQuery from Download Graph

---

package-lock.json
package.json

see https://github.com/ember-cli/ember-fetch/blob/v6.5.1/CHANGELOG.md

Update `ember-fetch` to v6.5.1

---

package-lock.json
package.json

see https://github.com/ember-cli/ember-cli/blob/v3.9.0/CHANGELOG.md

Update `ember-cli` to v3.9.0

---

migrations/2019-06-14-195059_remove_unused_indexes/down.sql
migrations/2019-06-14-195059_remove_unused_indexes/up.sql

Neither of these indexes have ever been scanned.

Remove unused indexes

---

app/templates/application.hbs

Closes https://github.com/rust-lang/crates.io/issues/1819.
[edit: I had more changes associated with this PR but decided to send them separately]

Add owner invites link to mobile menu

---

app/templates/application.hbs

Add a link to the Rust privacy notice to the footer

---

app/templates/crate/version.hbs
package-lock.json
package.json

Fixes https://github.com/rust-lang/crates.io/issues/554.

Display loading message while dependencies are loading

---

package-lock.json
package.json

Update ember-prism dependency.

---

package-lock.json
package.json

see https://github.com/machty/ember-concurrency/blob/master/CHANGELOG.md

Update `ember-concurrency` to v1.1.3

---

app/adapters/api-token.js
app/adapters/application.js
app/adapters/crate-owner-invite.js
app/models/api-token.js
app/models/category-slug.js
app/models/category.js
app/models/crate-owner-invite.js
app/models/crate.js
app/models/dependency.js
app/models/keyword.js
app/models/owned-crate.js
app/models/team.js
app/models/user.js
app/models/version-download.js
app/models/version.js
app/serializers/application.js

This was migrated using https://github.com/ember-codemods/ember-data-codemod/
r? @locks

Migrate `ember-data` imports to new module import paths

---

app/index.html

see https://zonkyio.github.io/ember-web-app/docs/getting-started/installation
r? @locks

Add missing `ember-web-app` tags

---

app/templates/search.hbs
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/search-test.js

This fixes frontend test problems *uncovered* by Percy, but hopefully no longer *impacted* by Percy problems 🤞 
r? @jtgeibel

Fix frontend test issues

---

app/services/redirector.js
package-lock.json
package.json
tests/services/redirector-test.js

Not much to say here, this new tests checks if the `redirectTo()` method works as it's supposed to.

services/redirector: Add basic test for `redirectTo()` method

---

app/components/link-to-dep.js
app/templates/components/category-list.hbs
app/templates/components/crate-downloads-list.hbs
app/templates/components/crate-list-name-only.hbs
app/templates/components/crate-list-newest.hbs
app/templates/components/keyword-list.hbs
app/templates/components/link-to-dep.hbs
config/optional-features.json

see https://emberjs.github.io/rfcs/0278-template-only-components.html
r? @locks

Enable `template-only-glimmer-components` feature flag

---

app/components/flash-message.js
app/controllers/application.js
app/templates/application.hbs
app/templates/catch-all.hbs

Simplify and reuse `FlashMessage` component

---

app/components/pagination.module.scss

Fixes a small issue I introduced in #2111 😱 
r? @locks

Pagination: Fix `.active` link styling

---

package-lock.json
package.json

see https://github.com/simplabs/qunit-console-grouper/
r? @locks

Add `qunit-console-grouper` dev dependency

---

testem.js

similar to https://github.com/simplabs/ember-test-selectors/pull/463 :)
r? @locks

testem: Increase start timeout for GitHub Actions CI

---

tests/mirage/crates-test.js

tests/mirage/crates: Fix test suite title

---

app/router.js

... to make the transition to https://github.com/rust-lang/crates.io/pull/2149 a little easier :) 
r? @locks

router: Convert to ES6 class

---

package-lock.json

This should (at least partly) unblock https://github.com/rust-lang/crates.io/pull/2254
r? @locks

Update transitive `ember-in-element-polyfill` dependency to v0.2.2

---

package.json

see https://github.com/keithamus/sort-package-json/
r? @locks

package.json: Sort contents according to the npm documentation order

---

app/components/category-list.hbs
app/components/crate-list-name-only.hbs
app/components/crate-list-newest.hbs
app/components/keyword-list.hbs
app/styles/crate.scss
app/templates/crates.hbs
app/templates/search.hbs

Remove unused/redundant CSS classes

---

app/index.html
app/styles/app.scss
app/styles/application.module.scss
app/styles/application.scss
app/templates/application.hbs

This PR converts a few of the elements in `application.hbs` and `index.html` to use CSS modules

Convert application-wide CSS to CSS modules

---

app/templates/crates.hbs

whoops... 🤦‍♂ 
this got lost in 958fa74
r? @locks

crates: Fix missing `letter` condition

---

app/components/follow-button.hbs
app/components/follow-button.js
app/controllers/crate/version.js
app/helpers/or.js
app/routes/crate/version.js
app/templates/crate/version.hbs
tests/acceptance/crate-following-test.js

best reviewed commit-by-commit 😉 
r? @locks

Extract `FollowButton` component

---

app/components/follow-button.js
package-lock.json
package.json

more information at https://api.emberjs.com/ember/release/modules/@glimmer%2Fcomponent
Glimmer components are essentially the new default in Ember application, and they feature improved performance and a better overall developer experience.
r? @locks

FollowButton: Convert to Glimmer component

---

app/components/owned-crate-row.hbs
app/templates/application.hbs
app/templates/crate/owners.hbs

Convert `@id` arguments to `id` attributes

---

tests/acceptance/dashboard-test.js

Add basic tests for the dashboard page

---

app/styles/app.scss
app/styles/application.module.scss

Move `abbr` styling into CSS module

---

app/templates/keywords.hbs

keywords: Remove unused `vers` CSS class assignment

---

app/components/crate-badge.hbs
app/components/crate-row.hbs
app/components/crate-row.module.scss
app/styles/crate.scss
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

Use CSS module for `CrateRow` component

---

app/components/results-count.hbs
app/components/results-count.module.scss
app/styles/crate.scss
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crate/reverse-dependencies.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

Extract `ResultsCount` component

---

app/styles/crate.scss
app/styles/crate/version.module.scss
app/templates/crate/version.hbs

version: Move `quick-links` CSS class into CSS module

---

app/styles/me.scss
app/styles/me/index.module.scss
app/templates/me/index.hbs

me: Move `me-profile` CSS classes into CSS module

---

app/styles/crate.scss
app/styles/crates.module.scss
app/styles/search.module.scss
app/templates/crates.hbs
app/templates/search.hbs

Move more CSS code from `crate.scss` to CSS modules

---

app/components/pending-owner-invite-row.hbs
app/templates/accept-invite.hbs
app/templates/me/pending-invites.hbs
tests/acceptance/invites-test.js
tests/acceptance/token-invites-test.js

Add acceptance tests for `/me/pending-invites` and `/accept-invite/:token` routes 

---

app/components/owned-crate-row.hbs
app/routes/me/index.js
app/services/session.js
app/templates/application.hbs
tests/bugs/2329-test.js

Fix missing owned crates after authentication

---

app/components/badge-appveyor.hbs
app/components/badge-azure-devops.hbs
app/components/badge-bitbucket-pipelines.hbs
app/components/badge-circle-ci.hbs
app/components/badge-cirrus-ci.hbs
app/components/badge-codecov.hbs
app/components/badge-coveralls.hbs
app/components/badge-gitlab.hbs
app/components/badge-is-it-maintained-issue-resolution.hbs
app/components/badge-is-it-maintained-open-issues.hbs
app/components/badge-maintenance.hbs
app/components/badge-travis-ci.hbs

We don't have any `.badge` CSS class style declarations 🤷‍♂ 
r? @locks

Remove unused `badge` CSS class assignments

---

app/components/pending-owner-invite-row.hbs
app/components/pending-owner-invite-row.module.scss
app/styles/me.scss
app/styles/me/pending-invites.module.scss
app/templates/me/pending-invites.hbs
tests/acceptance/invites-test.js

Convert `my-invites` styling to CSS modules

---

app/components/category-list.hbs
app/components/crate-list-name-only.hbs
app/components/crate-list-newest.hbs
app/components/front-page-list.hbs
app/components/front-page-list.module.scss
app/components/front-page-list/item.hbs
app/components/front-page-list/item.module.scss
app/components/keyword-list.hbs
app/styles/app.scss
app/styles/index.module.scss

This makes it easier to apply unified styling to all of these lists on the frontpage  :)
r? @locks

Extract `FrontPageList` component

---

app/components/api-token-row.hbs
app/components/api-token-row.module.scss
app/components/email-input.hbs
app/components/email-input.module.scss
app/components/follow-button.hbs
app/components/follow-button.module.scss
app/components/pending-owner-invite-row.hbs
app/components/pending-owner-invite-row.module.scss
app/styles/app.scss
app/styles/crate/owners.module.scss
app/styles/index.module.scss
app/styles/me/index.module.scss
app/styles/shared/buttons.module.scss
app/templates/index.hbs
app/templates/me/index.hbs

Extract shared `button` CSS module

---

app/components/crate-row.module.scss
app/components/pending-owner-invite-row.module.scss
app/components/results-count.module.scss
app/styles/app.scss
app/styles/crate/version.module.scss
app/styles/crate/versions.module.scss
app/styles/dashboard.module.scss
app/styles/shared/typography.module.scss
app/templates/crate/version.hbs
app/templates/crate/versions.hbs

Extract shared `typography` CSS module

---

app/components/api-token-row.hbs
app/components/api-token-row.module.scss

ApiTokenRow: Replace all regular `class` assignments with CSS module

---

app/components/email-input.hbs
app/components/email-input.module.scss
app/components/owned-crate-row.hbs
app/styles/me.scss
app/styles/me/index.module.scss
app/templates/me/index.hbs

EmailInput: Use CSS module

---

app/styles/categories.module.scss
app/templates/categories.hbs

categories: Use CSS module classes

---

app/styles/app.scss
app/styles/application.module.scss
app/templates/application.hbs

application: Convert `subtitle` to CSS module class

---

app/components/dropdown.hbs
app/components/dropdown.module.scss
app/styles/app.scss
app/styles/crate.scss
app/templates/application.hbs
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

Dropdown: Use CSS module for container styling

---

app/styles/app.scss
app/styles/application.module.scss

Move global element styling into `application` CSS module

---

app/components/dropdown/content.hbs
app/components/dropdown/content.js
app/components/dropdown/content.module.scss
app/styles/app.scss
app/styles/application.module.scss
app/templates/application.hbs
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

Dropdown::Content: Use CSS module

---

app/styles/category-slugs.module.scss

category-slugs: Simplify `list` styles

---

app/styles/app.scss
app/styles/crate/versions.module.scss
app/templates/crate/versions.hbs
tests/acceptance/crate-test.js

crate.versions: Convert remaining styles to CSS module classes

---

app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

Remove unused `sort` CSS class assignments

---

app/templates/application.hbs
app/templates/catch-all.hbs

Remove unused `search` CSS class assignments

---

app/components/dropdown.hbs
app/components/dropdown/menu-item.hbs
app/components/dropdown/menu-item.module.scss
app/components/dropdown/menu.hbs
app/components/dropdown/menu.module.scss
app/styles/app.scss
app/templates/application.hbs
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

The main goal of this new subcomponent is to abstract away some of the styling into corresponding CSS modules.
r? @locks

Dropdown: Extract `Menu` subcomponent

---

app/styles/crate/version.module.scss
app/templates/crate/version.hbs

crate.version: Remove/Replace remaining `class` assignments

---

app/styles/shared/buttons.module.scss

... to eventually get rid of SASS 🙏 
r? @locks

styles/buttons: Replace mixins

---

app/styles/index.module.scss
app/templates/index.hbs

index: Extract `stats-label` CSS module class

---

app/styles/application.module.scss

to eventually be compatible with regular CSS... 😉 
r? @locks

styles: Convert // comments to /*...*/ comments

---

app/styles/category/index.module.scss
app/styles/crate.scss
app/styles/crates.module.scss
app/styles/keyword/index.module.scss
app/styles/keywords.module.scss
app/styles/me/crates.module.scss
app/styles/me/following.module.scss
app/styles/search.module.scss
app/styles/team.module.scss
app/styles/user.module.scss
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

Extract `list` and `row` CSS module classes

---

app/templates/application.hbs
app/templates/category/index.hbs
app/templates/crate/version.hbs
app/templates/index.hbs
tests/acceptance/crate-test.js

There are no styles assigned to these IDs and they seems unlikely to be used in bookmarks
r? @locks

Remove more unused `id` assignments

---

app/components/sort-dropdown.hbs
app/components/sort-dropdown.module.scss
app/components/sort-dropdown/option.hbs
app/styles/categories.module.scss
app/styles/category/index.module.scss
app/styles/crate.scss
app/styles/crates.module.scss
app/styles/keyword/index.module.scss
app/styles/keywords.module.scss
app/styles/me/crates.module.scss
app/styles/me/following.module.scss
app/styles/search.module.scss
app/styles/team.module.scss
app/styles/user.module.scss
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

 Extract `SortDropdown` component 

---

app/styles/dashboard.module.scss
app/templates/dashboard.hbs

Otherwise `composes` doesn't actually work correctly... 😱 
r? @locks

dashboard: Convert `date` and `version` to top-level classes

---

app/templates/team.hbs
app/templates/user.hbs

These elements didn't cause any visual difference, so we might as well remove them...
r? @locks

team|user: Remove unnecessary wrapper elements

---

app/routes/github-authorize.js
tests/routes/github-authorize-test.js

see commit messages for details 😉 
r? @locks

Test and simplify `github-authorize` route

---

.eslintrc.js
app/controllers/dashboard.js
app/templates/dashboard.hbs

and enable ESLint rule that prevents it in the future :)
r? @locks

dashboard: Remove redundant `visibleStats` property

---

app/components/owned-crate-row.js
app/controllers/category/index.js
app/controllers/crates.js
app/controllers/keyword/index.js
app/controllers/me/crates.js
app/controllers/search.js
app/controllers/team.js
app/controllers/user.js
app/routes/accept-invite.js

With the newer Ember.js versions this is no longer necessary in the majority of cases 🎉 
r? @locks

Remove unnecessary `this.get()` calls

---

app/routes/team.js
app/routes/user.js
app/services/session.js

async/await is significantly easier to reason about in JavaScript than Promise chains.
r? @locks

Convert promise chains to async/await

---

app/app.js

see https://github.com/emberjs/ember.js/issues/15140
r? @locks

Disable global, non-passive `touchstart` and `touchmove` event listeners

---

app/adapters/crate.js
mirage/route-handlers/crates.js
tests/acceptance/crate-test.js
tests/models/crate-test.js

Resolves https://github.com/rust-lang/crates.io/issues/2084
r? @locks 

Fix owner invite error handling behavior

---

.editorconfig

Current config makes my editor confused.

Set YAML indent size to 2

---

config/nginx.conf.erb

Replaces https://github.com/rust-lang/crates.io/pull/2105.

Add 'unsafe-inline' for style-src CSP

---

tests/acceptance/crate-test.js

This test checks what happens when a version details page of an unknown version is visited.
r? @locks

tests/crate: Add "unknown version" test

---

app/controllers/crate/version.js
app/routes/crate/version.js
app/templates/crate/version.hbs

... and prevent the code from overwriting model attributes on the `crate`
r? @locks

crate.version: Move docs.rs request into a controller task

---

app/controllers/crate/version.js
app/routes/crate/version.js
tests/unit/controllers/crate/version-test.js

Best reviewed commit-by-commit 😅 
r? @locks

crate.version: Simplify `model()` hook

---

app/helpers/eq.js
app/helpers/or.js
package-lock.json
package.json

see https://github.com/jmurphyau/ember-truth-helpers
r? @locks

Replace custom `eq` and `or` helpers with ember-truth-helpers

---

app/controllers/crate/version.js
app/models/version.js
app/routes/crate/version.js
app/templates/crate/version.hbs

Simplify dependency loading by using an ember-concurrency task

---

app/controllers/crate/version.js

crate.version: Remove unused `isDownloading` property

---

app/components/crate-row.hbs
app/components/crate-row.js

Convert `CrateRow` to template-only component

---

package.json

see https://github.com/ember-cli/ember-new-output/blob/v3.16.1/package.json#L14
r? @locks

package.json: Adjust `build` script to build production assets

---

app/models/api-token.js
app/models/category-slug.js
app/models/category.js
app/models/crate-owner-invite.js
app/models/crate.js
app/models/dependency.js
app/models/keyword.js
app/models/owned-crate.js
app/models/team.js
app/models/user.js
app/models/version-download.js
app/models/version.js

Convert all models to ES6 classes

---

Cargo.lock
Cargo.toml

I don't expect any breakage.
cc #1265
r? @jtgeibel

Update `toml` to 0.5

---

app/controllers/dashboard.js
app/routes/dashboard.js
app/styles/dashboard.module.css
app/templates/dashboard.hbs

Best reviewed commit-by-commit :)
r? @locks

dashboard: Cleanup data loading code

---

app/styles/application.module.css

This seems to be a best practice 🤷‍♂️ 
r? @locks

styles: Use `:root` to define global CSS variables

---

app/styles/dashboard.module.css
app/templates/dashboard.hbs

dashboard: Convert `img` element to inline SVG icon

---

app/routes/category.js
app/routes/keyword.js

Use async/await for `model()` hooks instead of Promise chains

---

app/styles/application.module.css
app/templates/application.hbs

Shrink page header height

---

app/components/footer.module.css
app/controllers/application.js
app/helpers/add-html-class.js
app/index.html
app/services/design.js
app/styles/application.module.css
app/templates/application.hbs

This will add a "Toggle Design" button to the development mode that toggles the color scheme and fonts to a new design proposal. This will allow us to incrementally improve the design and eventually switch over.
r? @pichfl

Add theme switcher in development mode

---

src/middleware.rs
src/middleware/ember_html.rs

Simplify logic and improve documentation for the ember middleware layer.
r? @JohnTitor

Improve code and docs for serving Ember.js HTML

---

app/controllers/index.js
app/routes/index.js

This didn't quite work as intended... 😅 
r? @pichfl

index: Fix broken summary request caching logic

---

Cargo.lock
Cargo.toml

Bump to comrak 0.7

---

.github/workflows/ci.yml

Correct actions syntax

---

package-lock.json

Update locked dependencies to fix `npm audit` warnings

---

.github/workflows/ci.yml

maybe that'll fix the broken CI jobs... 🤷‍♂️ 
r? @Turbo87

CI: Use `postgres` service

---

app/templates/application.hbs
app/templates/crate/version.hbs
app/templates/search.hbs

Replace `{{title}}` with `{{page-title}}`

---

app/services/progress.js

The `progress` property can be replaced by a local variable, and the `count` property by a derived task state property :)
r? @locks

services/progress: Remove two unnecessary properties

---

app/routes/search.js
app/services/header.js

services/header: Convert `searchValue` to tracked property

---

app/components/dropdown.js

This PR converts the `Dropdown` component into a more efficient Glimmer component
r? @locks

Dropdown: Convert to Glimmer component

---

app/components/header.js

This PR converts the `Header` component into a more efficient Glimmer component
r? @locks

Header: Convert to Glimmer component

---

app/components/user-avatar.hbs
app/components/user-avatar.js

This PR converts the `UserAvatar` component into a more efficient Glimmer component
r? @locks

UserAvatar: Convert to Glimmer component

---

app/components/download-graph.hbs
app/components/download-graph.js
package.json

This PR converts the `DownloadGraph` component into a more efficient Glimmer component
r? @locks

DownloadGraph: Convert to Glimmer component

---

Cargo.lock
Cargo.toml

Switch back to upstream release of derive_deref

---

Cargo.lock

This introduces 3 new dependencies and removes 8 dependencies.
r? @jtgeibel

Update dependencies with `cargo update`

---

.dependabot/config.yml

since we're using renovatebot now instead

Remove dependabot config file

---

src/config.rs

Address new clippy suggestion

---

package-lock.json
package.json

This PR is a combination of #2754 and #2698 to make our dependency linter happy :)
r? @locks

Update ember-keyboard and ember-modifier

---

app/templates/crate/version.hbs

Move owners section above authors

---

app/components/api-token-row.hbs
app/components/follow-button.hbs
app/components/page-header.hbs

Add missing `alt` attributes for the loading spinners

---

app/routes/me/index.js

There is no need for doing this in the `willTransition` action
r? @locks

me/index: Move `controller.setProperties()` call into `setupController()`

---

.buildpacks

Upstream changes:
* https://github.com/emk/heroku-buildpack-rust/compare/578d630...cfa0f06
* https://github.com/heroku/heroku-buildpack-nginx/compare/fbc49cd...53b03b0
r? @JohnTitor

Bump rust and nginx buildpacks

---

ember-cli-build.js
src/render.rs

Add TOML syntax highlighting and fix YAML syntax highlighting

---

app/app.js

app.js: Convert to ES6 class

---

app/adapters/api-token.js
app/adapters/crate-owner-invite.js

adapters: Use `application` adapter as base class for all other adapters

---

package-lock.json
package.json

see https://github.com/kaliber5/ember-cli-bundle-analyzer
r? @locks

Add `ember-cli-bundle-analyzer` addon

---

.github/workflows/ci.yml
.travis.yml

not sure how we missed this 😅 
r? @locks

CI: Run test suite including coverage reporting

---

config/coverage.js

This seems more useful than looking at just the console output and raw JSON files :D
r? @locks

coverage: Add `html` reporter

---

app/components/pending-owner-invite-row.hbs
app/components/pending-owner-invite-row.js
app/components/pending-owner-invite-row.module.css
tests/acceptance/invites-test.js

PendingOwnerInviteRow: Replace custom error display with regular notification

---

app/components/api-token-row.hbs
app/components/api-token-row.js
app/templates/me/index.hbs

ApiTokenRow: Use `@token` argument

---

.eslintrc.js
app/controllers/application.js
app/controllers/catch-all.js
app/controllers/categories.js
app/controllers/category/index.js
app/controllers/crate/owners.js
app/controllers/crate/reverse-dependencies.js
app/controllers/crate/version.js
app/controllers/crate/versions.js
app/controllers/crates.js
app/controllers/dashboard.js
app/controllers/index.js
app/controllers/install.js
app/controllers/keyword/index.js
app/controllers/keywords.js
app/controllers/me/crates.js
app/controllers/me/following.js
app/controllers/me/index.js
app/controllers/search.js
app/controllers/team.js
app/controllers/user.js

Convert controllers to ES6 classes

---

app/components/api-token-row.hbs
app/components/api-token-row.js

ApiTokenRow: Convert to Glimmer component

---

app/components/crate-row.module.css
app/styles/crate/version.module.css
app/styles/shared/buttons.module.css

CopyButton: Improve and simplify the styling code

---

README.md

We don't actually use this anymore at the moment
r? @locks

README: Remove Browserstack section

---

app/components/pending-owner-invite-row.hbs
app/components/pending-owner-invite-row.js

 PendingOwnerInviteRow: Convert to Glimmer component

---

tests/bugs/2329-test.js

tests/bugs/2329: Use mirage setup for fixtures

---

src/controllers/user/me.rs

controllers/user/me: Fix typo in `update_user()` API docs

---

app/components/header.hbs
app/components/header.js
mirage/config.js
mirage/route-handlers/session.js
tests/acceptance/logout-test.js
tests/mirage/session-test.js

This addresses https://github.com/rust-lang/crates.io/pull/2866#commitcomment-42957327 and adds a regression test for the logout behavior.
r? @jtgeibel

Fix broken logout button

---

app/controllers/catch-all.js
app/templates/catch-all.hbs
tests/acceptance/404-test.js

This resolves https://github.com/rust-lang/crates.io/issues/2874 and adds a basic regression test for it.
It should also resolve https://sentry.io/organizations/rust-lang/issues/1935718226/
r? @jtgeibel

Fix search field on 404 page

---

app/services/fetcher.js

This removes the last remaining `.then(...)` usage in the app 🎉 
r? @pichfl

services/fetcher: Convert `ajax()` to async method

---

app/components/email-input.js
app/models/user.js
tests/acceptance/email-change-test.js
tests/models/user-test.js

Implement email confirmation API calls using ember-api-actions

---

.template-lintrc.js
app/components/dropdown.hbs
app/components/header.hbs
app/components/header.js
app/components/pending-owner-invite-row.hbs
app/controllers/me/index.js
app/templates/crates.hbs
app/templates/me/index.hbs

see https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-action.md
r? @locks

Replace `action` helper usage

---

app/adapters/api-token.js
app/adapters/application.js
app/adapters/category-slug.js
app/adapters/crate-owner-invite.js
app/adapters/dependency.js
app/adapters/team.js
app/adapters/user.js

... and adjusts `headers` to be a getter.
r? @locks

Convert adapters to native JS classes

---

app/adapters/application.js
app/components/api-token-row.js
app/components/email-input.js
app/controllers/me/index.js
app/helpers/format-num.js
app/initializers/hashchange.js
app/routes/accept-invite.js
app/routes/category.js
app/routes/crate.js
app/routes/keyword.js
app/routes/team.js
app/routes/user.js
app/services/session.js
app/utils/local-storage.js

Simplify catch bindings

---

ember-cli-build.js

ember-fetch: Enable `preferNative` option

---

.github/workflows/ci.yml
ember-cli-build.js
package.json
yarn.lock

see https://github.com/embroider-build/embroider/
r? @locks

Add Embroider build job

---

mirage/scenarios/default.js

Resolves https://github.com/rust-lang/crates.io/issues/671
r? @locks

mirage/scenarios/default: Use authenticated session by default

---

.github/workflows/ci.yml
app/components/api-token-row.hbs
app/components/api-token-row.js
app/components/email-input.hbs
app/components/email-input.js
app/components/header.hbs
app/components/header.js
app/controllers/catch-all.js
app/controllers/crate/owners.js
app/controllers/me/index.js
app/templates/catch-all.hbs
app/templates/crate/owners.hbs
app/templates/me/index.hbs
ember-cli-build.js
package.json
yarn.lock

see https://github.com/buschtoens/ember-event-helpers#prevent-default
r? @locks

Use `prevent-default` helper from `ember-event-helpers`

---

.eslintrc.js
app/components/api-token-row.js
app/components/email-input.js
app/components/follow-button.js
app/controllers/crate/owners.js
app/controllers/crate/version.js
app/initializers/hashchange.js
app/services/google-charts.js
config/environment.js
mirage/route-handlers/crates.js
mirage/route-handlers/summary.js
package.json
tests/helpers/dom.js
yarn.lock

see https://github.com/sindresorhus/eslint-plugin-unicorn
r? @locks

ESLint: Add `eslint-plugin-unicorn`

---

package.json
yarn.lock

see https://github.com/ember-cli/ember-cli-terser/pull/230 😉 
r? @locks

Replace `ember-cli-uglify` with `ember-cli-terser`

---

app/components/page-header.hbs
app/controllers/search.js
app/routes/search.js
app/styles/search.module.css
app/templates/search.hbs
mirage/route-handlers/crates.js
tests/acceptance/search-test.js

When an error occurs we display an error message with a "Try Again" button now.
r? @locks

Implement error handling for the search page

---

app/controllers/index.js
app/routes/index.js
app/styles/index.module.css
app/styles/shared/buttons.module.css
app/templates/index.hbs
mirage/route-handlers/summary.js
tests/acceptance/front-page-test.js

When an error occurs we display an error message with a "Try Again" button now.
r? @locks

Implement error handling for the index page

---

src/bin/server.rs
src/s3/lib.rs

Address recent clippy lints

---

.eslintrc.js
app/controllers/crate/version.js
app/routes/crate/version.js
package.json
yarn.lock

see https://github.com/simplabs/eslint-plugin-ember-concurrency :)
r? @locks

ESLint: Add `eslint-plugin-ember-concurrency`

---

Cargo.lock
Cargo.toml
src/s3/Cargo.toml

Update `hmac` and `env_logger`

---

src/controllers/version/downloads.rs

The implementation is a bit more complicated than hoped, because
lifetimes.
r? @Turbo87

Add a log message if a download is not counted

---

Cargo.toml
build.rs
src/bin/server.rs

This should hopefully address https://github.com/rust-lang/crates.io/pull/2991#pullrequestreview-521146500
r? @jtgeibel

Use `HEROKU_SLUG_COMMIT` if available

---

.github/workflows/ci.yml

This was missed in #1867 which only changed the frontend.
r? @Turbo87

CI: Upgrade to ubuntu-18.04

---

src/controllers/user/me.rs
src/middleware/normalize_path.rs
src/middleware/require_user_agent.rs
src/s3/lib.rs
src/tests/all.rs

Apply clippy suggestions for comparison_to_empty

---

Cargo.lock
Cargo.toml
src/models/dependency.rs
src/tests/all.rs
src/tests/builders/dependency.rs

This reverts commit cdf69158ebf5ece20aa9aceca83aefe8991562d4, reversing
changes made to 6e7b63a7f5877dac1161c473e104d3b9166ef7fd.
I'll r+ once CI is green
r? @ghost

Revert "Auto merge of #2990 - jtgeibel:update/semver, r=pietroalbini"

---

app/components/follow-button.hbs
app/components/follow-button.js
tests/acceptance/crate-following-test.js

FollowButton: Add error notifications when network requests fail

---

src/models/krate.rs
src/tests/krate.rs

... as described in the TODO comment

Move `Crate::valid_feature()` unit test to the `model/krate.rs` file

---

src/controllers/helpers/pagination.rs
src/controllers/keyword.rs
src/controllers/krate/search.rs

Resolve unnecessary_wraps clippy warning in pagination logic

---

app/routes/application.js

see code comment 😉 
r? @pichfl

routes/application: Explicitly ignore `ember-concurrency/no-perform-without-catch` warning

---

app/services/progress.js

The code comment should hopefully explain the changes well enough :)
r? @locks

services/progress: Add `catch()` blocks to the `perform()` calls

---

app/components/download-graph.js
package.json

Sort versions in download graph using semverSort

---

app/components/ember-tooltip.js
app/components/version-list/row.hbs
app/components/version-list/row.module.css
package.json
public/assets/checkbox-empty.svg
yarn.lock

VersionList::Row: Show feature names in tooltip

---

app/components/front-page-list/item.module.css

This improves the contrast on these links, but also the focus styles are much more visible now :)

FrontPageList::Item: Improve styling

---

app/models/version.js
package.json
yarn.lock

see https://github.com/pzuraq/tracked-toolbox#cached

models/version: Use `@cached` decorator to expensive properties

---

app/components/version-list/row.hbs
app/components/version-list/row.js
app/components/version-list/row.module.css

VersionList::Row: Improve focus styling

---

app/styles/dashboard.module.css

Fix dashboard 'Load More' margin

---

docs/CONTRIBUTING.md

as discussed during the last team meeting
r? @jtgeibel

CONTRIBUTING: Add "team meeting" section

---

Cargo.lock
Cargo.toml
src/admin/populate.rs

Bump to latest rand

---

app/components/nav-tabs/tab.module.css
app/components/version-list/row.module.css

Improve keyboard focus styling

---

src/middleware/log_request.rs
src/models/token.rs
src/tests/builders/version.rs
src/tests/record.rs
src/util/token.rs

Address new clippy findings

---

app/components/crate-sidebar.module.css
app/styles/shared/typography.module.css

These classes appear to not be used anywhere anymore.

Remove unused `yanked` CSS classes

---

config/nginx.conf.erb

Update CloudFront IP addresses

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css
app/styles/crate/version.module.css
app/templates/crate/version.hbs

Improve README styling

---

app/components/dependency-list/row.module.css
app/components/front-page-list/item.module.css
app/components/front-page-list/item/placeholder.module.css
app/components/version-list/row.module.css

We use 5px everywhere else, so we should try to stay consistent. Visually it looks almost the same. :)

Unify `border-radius` values

---

.gitignore

See: https://github.com/rust-lang/crates.io/pull/3430#issuecomment-802899330

gitignore: Remove .vscode directory

---

Cargo.lock
Cargo.toml
docs/BACKEND.md
src/bin/server.rs

as discussed in our weekly team meeting today :)
Resolves https://github.com/rust-lang/crates.io/issues/2204

Remove `civet` server option

---

app/components/crate-sidebar.hbs
app/models/version.js
app/routes/crate/version.js

see https://github.com/rust-lang/rfcs/pull/3052 😉 

Remove "Authors" section from crate details page

---

src/tasks/dump_db.rs

Before:
```console
$ tar tf db-dump.tar.gz
2021-03-06-140039/
2021-03-06-140039/README.md
2021-03-06-140039/schema.sql
2021-03-06-140039/import.sql
2021-03-06-140039/export.sql
2021-03-06-140039/metadata.json
2021-03-06-140039/data
2021-03-06-140039/data/teams.csv
2021-03-06-140039/data/reserved_crate_names.csv
2021-03-06-140039/data/version_downloads.csv
2021-03-06-140039/data/keywords.csv
2021-03-06-140039/data/crates.csv
2021-03-06-140039/data/dependencies.csv
2021-03-06-140039/data/version_authors.csv
2021-03-06-140039/data/users.csv
2021-03-06-140039/data/crates_keywords.csv
2021-03-06-140039/data/versions.csv
2021-03-06-140039/data/categories.csv
2021-03-06-140039/data/metadata.csv
2021-03-06-140039/data/badges.csv
2021-03-06-140039/data/crate_owners.csv …
```

Topologically sort db-dump.tar.gz

---

src/controllers/crate_owner_invitation.rs
src/models/crate_owner_invitation.rs
src/tests/owners.rs
src/views.rs

This will allow us to display avatars on the frontend for the `inviter` part of the invitations.

GET /me/crate_owner_invitations: Add `users` list

---

mirage/route-handlers/crates.js
tests/mirage/crates-test.js

see https://github.com/jtgeibel/crates.io/issues/3426 :)

mirage/crates: Add support for `/api/v1/crates?ids[]=...`

---

src/controllers/crate_owner_invitation.rs
src/github.rs
src/middleware/log_request.rs
src/models/version.rs

Address some new clippy suggestions

---

app/components/rendered-html.module.css

Resolves https://github.com/rust-lang/crates.io/issues/3476

RenderedHtml: Use `--font-monospace` for code samples

---

app/components/crate-sidebar.js
tests/components/crate-sidebar/playground-button-test.js

Resolves https://github.com/integer32llc/rust-playground/issues/699
/cc @shepmaster @miDeb

Add `edition=2018` to the Rust Playground link

---

src/render.rs

As per request, fixes #3500
(not tested locally)

Add `webp` to possible media urls

---

src/models/token.rs
src/util/token.rs

This commit implements the FromSql and ToSql traits for SecureToken, allowing it to be used as a model field and in queries. This commit also hides the inner SHA256 value to prevent the rest of the application from accidentally leaking it.
The motivation of this commit is to enforce even more good practices around tokens through the type system.

Allow using SecureToken in Diesel queries

---

Cargo.lock
Cargo.toml

Fixes #3501 by upgrading comrak to an rc version. See the issue for more detalis.

Upgrade `comrak` dependency

---

.github/workflows/ci.yml

We can merge this after bumping to the heroku-20 stack on production.
r? @ghost

Bump to ubuntu-20.04 on CI

---

src/middleware.rs
src/middleware/balance_capacity.rs
src/middleware/block_traffic.rs
src/middleware/normalize_path.rs
src/middleware/require_user_agent.rs

Include add_custom_metadata in middleware prelude

---

app/components/crate-downloads-list.hbs
app/components/crate-downloads-list.module.css

Adjust download list icon alignment

---

ember-cli-build.js

see https://webpack.js.org/configuration/devtool/
This should fix the sourcemaps on Sentry

auto-import: Fix source maps

---

.template-lintrc.js
app/components/footer.module.css
app/components/header.hbs
app/components/header.module.css

Reverts rust-lang/crates.io#3681
Closes #3687 

Revert "Use full page width for `Header` and `Footer` components"

---

app/templates/data-access.hbs

close https://github.com/rust-lang/crates.io/issues/3618

Link to the dump changelog in the data access page

---

src/admin/render_readmes.rs

Fix crates-admin render-readmes for local installations

---

docs/CONTRIBUTING.md

Might be helpful for new contributors!
[rendered](https://github.com/hi-rustin/crates.io/blob/rustin-patch-docs/docs/CONTRIBUTING.md#using-mailgun-to-send-emails)

Better docs for send email in development

---

app/templates/me/index.hbs

close https://github.com/rust-lang/crates.io/issues/3743
Look like:

Add note to "Account Settings" page about how to change Name/Github Account

---

Cargo.lock
Cargo.toml
src/bin/server.rs

see https://github.com/getsentry/sentry-rust/blob/master/CHANGELOG.md and https://github.com/getsentry/sentry-rust/tree/master/sentry-tracing

Update Sentry and enable `tracing` integration

---

renovate.json

Update renovatebot config

---

Cargo.lock
Cargo.toml
src/db.rs

see https://docs.rs/thiserror/

db: Use `thiserror` crate to derive `Error` for `PoolError`

---

.eslintrc.js
package.json
yarn.lock

see https://github.com/simplabs/eslint-plugin-qunit-dom

ESLint: Use `qunit-dom` plugin

---

.github/renovate.json

I think I can help with some of the bump pull requests.

github: add me to reviewers

---

src/admin/render_readmes.rs
src/uploaders.rs

This should be slightly more efficient 😄

Use `HeaderValue::from_static()` instead of `::from(&str)`

---

Cargo.lock
Cargo.toml

see https://github.com/tikv/rust-prometheus/pull/216

prometheus: Disable `protobuf` feature

---

app/components/search-form.hbs

SearchForm: Adjust `autocomplete` and spellchecker attributes

---

app/components/follow-button.js
app/controllers/index.js
app/controllers/search.js
app/models/version.js
app/services/chartjs.js
app/services/playground.js
tests/components/download-graph-test.js

This is similar to https://github.com/rust-lang/crates.io/pull/4069, but converts all the remaining tasks that had concurrency modifiers attached to them.

Use ember-concurrency v2 decorator syntax

---

app/components/header.module.css
app/components/search-form.module.css
app/styles/application.module.css

Header: Add drop shadows to main elements

---

app/components/owners-list.hbs
app/components/owners-list.module.css
tests/components/owners-list-test.js

OwnersList: Fall back to `login` if `name` is not filled

---

.github/workflows/ci.yml
ember-cli-build.js

... and enable two additional Embroider options
see https://github.com/embroider-build/embroider#options

CI: Run tests for Embroider job again

---

docs/CONTRIBUTING.md

docs: Update team meeting time

---

package.json
yarn.lock

This should hopefully fix most of the Ember.js 4 compatibility issues :)

Update `ember-cli-fastboot` to v3.2.0-beta.5

---

app/components/crate-sidebar.js

Looks like a little copy-paste mistake 😅

CrateSidebar: Fix class name

---

.github/workflows/ci.yml
frontend.Dockerfile
package.json

see https://github.com/nodejs/node/releases/tag/v16.13.1

Update Node.js to v16.13.1

---

.github/renovate.json5

The previous approach wasn't working particularly well... 🙈

renovate: Adjust `node` package handling config

---

tests/acceptance/dev-mode-test.js

This can be used during development of pages that are only available if authenticated.

Add "Development Mode" application test

---

app/routes/application.js
mirage/config.js
mirage/route-handlers/metadata.js
tests/acceptance/read-only-mode-test.js

Resolves https://github.com/rust-lang/crates.io/issues/3989

Show info notification if crates.io is in read-only mode

---

.github/renovate.json5

see https://docs.renovatebot.com/dependency-pinning/

renovate: Pin dependency versions

---

app/components/settings/api-tokens.hbs
app/components/settings/api-tokens.js
app/components/settings/api-tokens.module.css
app/styles/shared/buttons.module.css
tests/acceptance/api-token-test.js

Closes https://github.com/rust-lang/crates.io/pull/3915

Improve "API Tokens" settings page

---

package.json
tests/components/download-graph-test.js
tests/helpers/fake-timers.js
tests/helpers/setup-mirage.js
tests/mirage/me/tokens/create-test.js
tests/models/version-test.js
yarn.lock

`timekeeper` is not really maintained anymore. `@sinonjs/fake-timers` is well maintained and has a few additional nice features.

Replace `timekeeper` with `@sinonjs/fake-timers`

---

.github/renovate.json5
.github/workflows/ci.yml
package.json

Use Volta to pin Node.js and yarn versions

---

app/routes/crate/version-dependencies.js
tests/acceptance/crate-dependencies-test.js

crate.version-dependencies: Show error page if data loading fails

---

app/routes/category.js
tests/routes/category-test.js

also similar to https://github.com/rust-lang/crates.io/pull/4476

category: Show error page if data loading fails

---

src/admin/render_readmes.rs

[`upload_readme`](https://github.com/arlosi/crates.io/blob/fd690b09b8724e1301f5aeb307f1456f8d6c14b4/src/uploaders.rs#L153) has the same functionality as the removed code here.
r? @Turbo87

Refactor `render-readmes` task to use `upload_readme` function

---

fastboot.js
mirage/route-handlers/categories.js
mirage/route-handlers/keywords.js
mirage/route-handlers/teams.js
mirage/route-handlers/users.js
package.json
yarn.lock

Also tweak code to fix warnings.
Closes #4933
Signed-off-by: Yuki Okushi <jtitor@2k36.org>

Update eslint-plugin-unicorn to v43

---

app/styles/shared/buttons.module.css

Superseeds https://github.com/rust-lang/crates.io/pull/4954

Use cursor pointer for all buttons

---

src/tests/record.rs

* Add `RECORD=force` to regenerate existing files
* Add `RECORD=passthrough` to preserve the old behavior. There may not be a use-case for this, alternatively we could drop this entirely.
When not in the legacy passthrough mode, a status 200 response with no headers and an empty body is generated.
Extracted from https://github.com/rust-lang/crates.io/pull/5022

Add an option to easily regenerate http-data files

---

app/templates/policies.hbs

Replace Mozilla with Rust Foundation in Package Policies

---

package.json
pnpm-lock.yaml

Looks like #5100 wasn't enough, but hopefully this PR should fix it... 😅

pnpm: Fix more peer dependency issues

---

src/boot/categories.toml

Changed typo in `[aerospace.categories.space-protocols]` in `src/boot/categories.toml`

Fixed typo

---

src/admin/git_import.rs

This should make the error reporting from #5120 more useful :)

admin::git_import: Improve error reporting

---

.github/workflows/ci.yml

Maybe this will fix our CI issues... 🤔

CI: Run `percy exec` with `pnpm` instead of `pnpx`

---

app/components/dependency-list/row.js
app/components/email-input.js
app/components/follow-button.js
app/components/pending-owner-invite-row.js
app/components/rev-dep-row.js
app/components/settings/api-tokens.js
app/controllers/crate/settings.js
app/controllers/crate/version.js
app/controllers/dashboard.js
app/controllers/index.js
app/controllers/search.js
app/models/version.js
app/routes/application.js
app/services/chartjs.js
app/services/playground.js
app/services/progress.js
app/services/session.js
tests/components/download-graph-test.js

see https://github.com/machty/ember-concurrency/blob/HEAD/CHANGELOG.md#%E2%80%8B230

ember-concurrency: Migrate to new task syntax API

---

.gitignore
frontend.Dockerfile

This roughly follows the example on https://pnpm.io/cli/fetch
Resolves https://github.com/rust-lang/crates.io/issues/5130

Docker: Fix pnpm usage

---

src/tests/category.rs
src/tests/snapshots/all__category__category_slugs_returns_all_slugs_in_alphabetical_order.snap
src/tests/snapshots/all__category__index-2.snap
src/tests/snapshots/all__category__index.snap
src/tests/snapshots/all__category__show.snap

see https://github.com/rust-lang/crates.io/pull/5133 :)

Use snapshot testing for `category` API tests

---

app/components/header.module.css
app/styles/application.module.css

Adjust header foreground colors

---

app/components/rendered-html.module.css

RenderedHtml: Fix inline code styling in lists

---

src/tests/record.rs

In particular, it is no longer necessary to manually bind the
listener, as hyper now provides a `Server::local_addr()`.

Simplify setup of test recorder

---

src/bin/server.rs

The initial setup is now done in a single `rt.block_on()` making the
code easier to read.
The `rt.spawn()` before printing `Listening at ...` has been dropped,
as the only way I could get that `async` block to run before the main
thread was by sleeping for 1ms. I tried using `tokio::task::yield_now()`
and `std::task::yield_now()` but the output from the main thread always
came first. In any case, the server binds to the listen address before
indicating it is ready, so this `spawn` is unnecessary.

Simplify spawning the http server in production

---

Cargo.lock
Cargo.toml
src/lib.rs
src/tests/all.rs

The former is unfortunately unmaintained :-/
see https://github.com/svartalf/rust-claim/issues/9#issuecomment-1232437287

Migrate from `claim` to `claims`

---

app/components/page-header.module.css
app/styles/category/index.module.css

PageHeader: Adjust `padding` to other content on the pages

---

app/components/crate-header.hbs
app/components/crate-header.module.css
app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css
app/components/crate-sidebar/link.hbs
app/components/crate-sidebar/link.module.css
app/components/follow-button.hbs
app/styles/crate/version-dependencies.module.css
app/templates/crate/version-dependencies.hbs

CrateHeader: Fix narrow screen layout

---

package.json
pnpm-lock.yaml

fix: bump to ember-data 4.6.4 to fix randomUUID polyfill bug

---

app/components/settings/api-tokens.hbs

Fixes #5207
Feel free to nitpick! :-)

Add clarification on why you can't view existing API keys

---

app/components/crate-row.module.css
app/components/crate-sidebar.module.css
app/components/dependency-list/row.module.css
app/components/footer.module.css
app/components/front-page-list/item.module.css
app/components/nav-tabs/tab.module.css
app/components/owned-crate-row.module.css
app/components/rev-dep-row.module.css
app/components/search-form.module.css
app/components/side-menu/item.module.css
app/components/version-list/row.module.css
app/styles/application.module.css

This should help us to bring a little more consistency into our design.
Roughly adapted from https://shoelace.style/tokens/transition :)

styles: Extract `transition` design tokens

---

app/components/header.module.css
app/styles/crate/version.module.css

These two classes don't seem to be used anywhere anymore...

Remove unused CSS classes

---

.github/renovate.json5

Similar to how we already keep some other CI env vars up-to-date :)

renovate: Keep pnpm version up-to-date

---

mirage/fixtures/crates.js

see https://github.com/rust-lang/crates.io/pull/5071 :)

mirage: Remove `badges` from fixtures

---

src/worker/cloudfront.rs

The infra team has seen random HTTP 503 errors for CloudFront invalidation requests. This change adds additional logging (headers and body) from the HTTP 503 responses to these requests.

Add additional HTTP logging for cloudfront invalidation failures

---

src/worker/cloudfront.rs

The existing logging wasn't as helpful as necessary, so this PR adjusts the debug logging a little to provide more information.

cloudfront: Improve logging

---

src/views.rs

As discussed at https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/link.20to.20scam/near/311155912

extend doc url blocks to arbitrary subdomains

---

src/worker/cloudfront.rs
src/worker/daily_db_maintenance.rs
src/worker/dump_db.rs
src/worker/git.rs
src/worker/update_downloads.rs

... and improve the existing logging calls in a few other cases :)

worker: Use `tracing` macros instead of `println!()`

---

src/tests/server_binary.rs

Returning an `Err` causes the following unhelpful output:
```
thread 'server_binary::startup_without_database' panicked at 'assertion failed: `(left == right)`
left: `1`,
right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/test/src/lib.rs:184:5
```

tests/server_binary: Use `unwrap()` to fail test instead of returning error

---

src/tests/owners.rs

It looked like we didn't have any such tests yet, so I added a few for this specific endpoint.

tests/owners: Add basic authentication tests for `PUT /crates/:name/owners`

---

src/tests/http-data/routes_crates_versions_yank_unyank_auth_cookie_user
src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user
src/tests/http-data/routes_crates_versions_yank_unyank_auth_unauthenticated
src/tests/routes/crates/versions/yank_unyank.rs

... to prepare to the token scopes implementation

tests/yank_unyank: Add authentication tests

---

src/tests/util/response.rs

By reordering the header checks, we can use `.into_body()` instead.

tests/util/response: Remove unnecessary `mem::swap()`

---

.github/renovate.json5

The label names have slightly changed... 😅

renovate: Update PR labels

---

src/util/tracing.rs

We don't want `http` logging to clutter the error reporting. These errors are not deduplicated properly, because they contain the request ID and other unique things in the error message.

util/tracing: Use custom `event_filter()`

---

src/headers.rs

X_REAL_IP: Fix copy paste bug in header name

---

src/middleware/log_request.rs

In the world of `axum` request handlers are not (really) allowed to return errors, so we need to rethink how `conduit` handler errors can be passed to the `axum` middleware. Since we already support custom metadata we can convert an `Err` result into a custom metadata field in the existing `conduit` middleware.

middleware/log_request: Add `error` field to `axum` logging

---

src/middleware/log_request.rs

This PR drops the logging part of the `conduit` middleware and uses the `axum` middleware for it instead, which is now on par with the `conduit` implementation.

middleware/log_request: Switch to axum-based logging

---

src/lib.rs
src/middleware.rs
src/middleware/debug.rs

This PR brings us one step closer to converting all of our code from `conduit` to `axum` :)

middleware/debug: Convert to `axum` middleware

---

src/lib.rs
src/middleware.rs

This moves our `axum` middleware stack building code into the `middleware` module, right next to similar code for the `conduit` middlewares.

middleware: Extract `apply_axum_middleware()` function

---

src/middleware.rs
src/middleware/require_user_agent.rs

Yet another PR that migrates a middleware to `axum`. This time the target is the middleware that rejects requests without a user agent header.

middleware/require_user_agent: Migrate to `axum`

---

src/admin/upload_index.rs
src/config.rs
src/controllers/helpers/pagination.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/token.rs
src/controllers/user/session.rs
src/controllers/version.rs
src/github.rs
src/lib.rs
src/metrics/log_encoder.rs
src/middleware/block_traffic.rs
src/middleware/ember_html.rs
src/middleware/log_request.rs
src/middleware/normalize_path.rs
src/models/krate.rs
src/models/owner.rs
src/models/team.rs
src/tests/all.rs
src/tests/builders/krate.rs
src/tests/builders/version.rs
src/tests/krate/publish.rs
src/tests/record.rs
src/tests/routes/crates/new.rs
src/tests/server_binary.rs
src/tests/util/response.rs
src/uploaders.rs
src/util/token.rs
src/worker/dump_db.rs
src/worker/git.rs

Address clippy suggestions in 1.67 beta.

`cargo +beta clippy --fix`

---

src/middleware/update_metrics.rs

This is similar to the `RequestCounter` of the `balance_capacity` middleware and ensures that the gauge is decreased again even if a different exit path out of the method is used somehow (i.e. `panic!()`).

middleware/update_metrics: Implement `GaugeGuard` struct

---

.buildpacks

I've tested this on staging and it works as expected.

Bump to latest nginx buildpack

---

src/middleware.rs
src/middleware/sentry.rs

This roughly corresponds to https://github.com/rust-lang/crates.io/blob/master/src/router.rs#L186-L188

Add `sentry::set_transaction` middleware

---

src/controllers/site_metadata.rs
src/lib.rs
src/router.rs

This PR migrates a first very basic route from `conduit` to `axum` 🎉

GET /api/v1/site_metadata: Migrate to `axum`

---

src/config.rs
src/controllers/util.rs
src/tests/util/test_app.rs

The `AllowedOrigins` struct abstracts the list of allowed `Origin` header values and slightly simplifies using it.

config: Extract `AllowedOrigins` struct

---

src/app.rs
src/db.rs

These methods are not relying on the request itself at all and only need access to the `App` instance. This PR moves the implementation of these methods into the `impl App` block and wires the old implementations to use the new methods. This allows us to only pass the `App` around when needing database access, instead of the full request object.

db: Move database access methods into `impl App`

---

src/util/errors.rs

This avoids the downcasting and is a little more explicit about what things are getting convert in what ways. It also avoids "duplicate implementation" errors in future PRs.

util::errors: Replace catch-all `From` implementation with explicit implementations

---

src/controllers/github/secret_scanning.rs

Most of the functions in this module don't need access to the full request object, so this PR narrows the function arguments down a bit. This will make it easier for us to port these modules to `axum`.

controllers/github: Narrow function arguments

---

.github/renovate.json5
.github/workflows/ci.yml
.github/workflows/coverage.yml

see https://github.com/Turbo87/renovate-config/blob/master/githubActions/regexManagers.json

renovate: Simplify regex managers config

---

conduit-axum/src/fallback.rs

This is only needed when the request has passed through the conduit router and it makes the function less reusable.

conduit-axum: Move `RoutePattern` insertion out of `conduit_into_axum()`

---

src/controllers/helpers/pagination.rs

If we only need the headers, we should only pass in the headers.

helpers/pagination: Simplify `is_useragent_or_ip_blocked()` signature

---

src/controllers.rs
src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/github/secret_scanning.rs
src/controllers/helpers.rs
src/controllers/keyword.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/team.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/session.rs
src/controllers/version/deprecated.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/util.rs

This prepares us for using `axum::Json`, which also takes ownership of the data.

req.json(): Take ownership of the JSON data

---

src/util/errors.rs
src/util/errors/json.rs

This means we need one less conversion step in the `IntoResponse` implementation, and it also means we can now use anything else that implements `IntoResponse` to build error responses. 🎉

AppError: Return `axum::Response` from `response()` fn

---

src/controllers/keyword.rs
src/router.rs

controllers/keyword: Convert `index()` to native `axum` request handler

---

conduit-axum/examples/server.rs
conduit-axum/src/tests.rs

conduit-axum: Migrate to async request handler functions

---

src/router.rs

The `C` wrapper will soon be a thing of the past, so this PR migrates the `router` module tests to using `.response()` instead.

router: Simplify error status code tests

---

src/controllers/version/downloads.rs

This may have been necessary while `&mut req` was needed for the `req.add_custom_metadata()` call, but since that is no longer the case, we can simplify the code here.

GET /crates/:crate_id/:version/download: Remove `log_metadata` variable

---

src/auth.rs
src/controllers/krate/owners.rs
src/controllers/token.rs
src/controllers/user/me.rs

Clean up `AuthenticatedUser` accessor methods

---

app/components/crate-sidebar.js
tests/components/crate-sidebar/playground-button-test.js

Sadly, we have to update it manually 😿
Signed-off-by: Yuki Okushi <jtitor@2k36.org>

Update playground link's edition to 2021

---

src/controllers/github/secret_scanning.rs
src/middleware/log_request.rs
src/middleware/session.rs

The `parking_lot` implementations appear to be more more efficient and allow us to not have to worry about `PoisonError` anymore :)

Use `parking_lot::Mutex` and `RwLock`

---

cargo-registry-index/lib.rs

As it turns out, in older `cargo` versions the order of the dependencies does matter to some degree. When the same dependency exists twice but with different `kind` fields, then things might break depending on the order. This commit changes the dependency sort order to first sort by `name` and then by `kind`, instead of `name, req`. This should restore the old sort order for most crates that had this scenario.
Related: 
- https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/index.20normalization/near/321109898
- https://github.com/serde-rs/serde/commit/1a3a49ce7cdd4761539297b17d78a7a90afa2031

index/Dependency: Change `Ord` order

---

src/controllers/token.rs
src/tests/routes/me/tokens/create.rs

This API endpoint can only be accessed via cookie (as in: via the web frontend), so it is not quite useable yet on its own. It is laying the foundation for implementing the corresponding frontend code though.

Add `crate_scopes` and `endpoint_scopes` fields to the `PUT /me/tokens` API endpoint

---

package.json
pnpm-lock.yaml

see https://github.com/emberjs/rfcs/issues/882

Remove deprecated `ember-export-application-global` dependency

---

src/email.rs

see https://github.com/lettre/lettre/issues/856

email: Add `Content-Type` header

---

src/controllers/version/downloads.rs

Fix typo in downloads.rs

---

app/components/download-graph.js

When falling back, a bug in date-fns[^0] results in the 23 hour day being skipped when building the `dates` array in `toChartData` if the current time is between 00:00 and 01:00 UTC. This results in that day's data essentially going missing, resulting in the subtly broken charts noted in #5477.
This commit adds a workaround adapted from a comment on date-fns/date-fns#571[^1] by @bertho-zero, which correctly adjusts the new date based on the time zone offsets, and means that `dates` is built as expected.
Fixes #5477.
Note that November 6 is missing: there's only one "down" day that weekend:
Now note that there are two days:
I tested this by hacking the crate download backend endpoint to shift the current data to be between 2022-09-03 and 2022-12-01, no matter what the current date is, and …

Fix download charts after a DST transition

---

Cargo.toml

see https://github.com/hyperium/hyper/commit/0ced15d3cc10ace477ebda13ead8e6857b51867e#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R116 :)

hyper: Enable `backports` and `deprecated` features

---

src/background_jobs.rs

This will eventually allow us to generate the `as_type_str()`, `to_value()` and `from_value()` implementations automatically from the enum definition.

background_jobs: Rename variants to match their `job_type` column values

---

src/worker/update_downloads.rs

... for consistency with the other logging in that fn :)

worker::update_downloads: Replace `println!()` call with `info!()`

---

src/sentry/mod.rs

sentry: Adjust `trace_sampler` implementation

---

src/worker/git.rs

see https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?h=v2.36.1#n181 😄

worker::git: Use imperative style commit messages

---

src/controllers/version/downloads.rs

This adds instrumentation for our version ID cache, which is used in the version download API endpoint.

version/downloads: Add `tracing` instrumentation

---

.github/workflows/ci.yml
deny.toml

see https://github.com/EmbarkStudios/cargo-deny

Integrate `cargo-deny`

---

app/components/settings-page.module.css
app/components/settings/api-tokens.module.css
app/styles/breakpoints.css
ember-cli-build.js
package.json
pnpm-lock.yaml

This is causing more [issues](https://github.com/rust-lang/crates.io/pull/5473) than it solves, and if we're only using it in two places we might as well not use it at all...

Remove unnecessary `postcss-custom-media` plugin

---

src/models/action.rs
src/models/category.rs
src/models/crate_owner_invitation.rs
src/models/dependency.rs
src/models/email.rs
src/models/follow.rs
src/models/keyword.rs
src/models/krate.rs
src/models/owner.rs
src/models/team.rs
src/models/user.rs
src/models/version.rs
src/publish_rate_limit.rs

see https://docs.rs/diesel/latest/diesel/query_dsl/trait.RunQueryDsl.html#method.load
tl;dr this should improve a few compiler error messages originating from `diesel` code.

diesel: Use `check_for_backend()` macro

---

src/models/action.rs
src/models/category.rs
src/models/dependency.rs
src/models/download.rs
src/models/follow.rs
src/models/keyword.rs
src/models/krate.rs
src/models/owner.rs

Uses a couple more lines of code, but seems easier on the eyes to me... :D

diesel: Merge `#[diesel(...)]` annotations where possible

---

app/styles/application.module.css

This increases the contrast of our header and footer a bit :)

styles: Use slightly darker background color

---

app/styles/settings/tokens/new.module.css
public/assets/dropdown.svg

The data URL is having issues on production due to our content security policy... 😫

settings/tokens/new: Use regular SVG file instead of data URL

---

src/tests/routes/crates/versions/download.rs
src/uploaders.rs

This PR implements step 3 of the proposed solution in https://github.com/rust-lang/crates.io/issues/4891#issuecomment-1580879109

Escape `+` to `%2B` in response URLs

---

src/worker/cloudfront.rs

cloudfront: Use `SecretString` for `secret_key` field

---

src/admin/delete_version.rs

This is similar to https://github.com/rust-lang/crates.io/pull/6724, but for the `delete_version` admin command.

admin/delete_version: Add ability to delete multiple versions with one command

---

src/admin/delete_crate.rs

This should make it easier for us to delete multiple crates from a list of e.g. spam crates.

admin/delete_crate: Add ability to delete multiple crates with one command

---

src/admin/delete_crate.rs

This PR is similar to #6727, but for the `delete-crate` admin tool this time.
I've manually verified that this is working as intended on our staging environment.

admin/delete_crate: Delete files from S3 too

---

src/controllers/util.rs
src/util/rfc3339.rs
src/worker/fastly.rs

We should probably add a check for this to our CI setup... 😅

Fix `cargo doc` warnings

---

crates_io_markdown/lib.rs
src/controllers/krate/metadata.rs
src/controllers/user/me.rs
src/controllers/version/deprecated.rs
src/models/token.rs
src/tests/server_binary.rs

These lints are new on nightly, and suggested fixes are reasonable.

Address clippy suggestions

---

src/admin/delete_version.rs

admin/delete_version: Simplify `object_store::Path` code

---

src/storage.rs

This PR extracts a few useful helper functions in the `storage` module. This should hopefully help to reduce the scope of https://github.com/rust-lang/crates.io/pull/6702 a tiny bit... 😅

storage: Extract helper functions

---

src/worker/dump_db.rs

... because I wanted to know what takes the most time :)

worker/dump_db: Add debug logging

---

src/worker/git.rs

This is a situation that technically should not happen, but has managed to happen a couple of times in the past. This change will ensure that at least the crate index is not messed up and that the crates.io team gets a notification about the problem on Sentry.
This will also avoid https://github.com/rust-lang/crates.io/issues/6793 from happening once https://github.com/rust-lang/crates.io/pull/6787 is merged.

Handle crates without versions gracefully

---

src/storage.rs
src/worker/dump_db.rs

Related:
- https://github.com/rust-lang/crates.io/pull/6702
- https://github.com/rust-lang/crates.io/pull/6783

worker/dump_db: Use `Storage` system to upload database dump tarball

---

src/worker/fastly.rs

This should reduce the risk of us accidentally leaking our Fastly API token to our debug logs.

Fastly: Mark API token as secret/sensitive information

---

crates_io_tarball/src/lib.rs

see https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/.60cargo.2Etoml.60.20on.20case.20insensitive.20filesystems/near/376986823
We have about 50 crate files published from case-insensitive file systems (most likely Windows) that are containing a lowercase `cargo.toml` instead of the regular `Cargo.toml` file.
We don't want to support this case in the future and `cargo` is planning to normalize the filename on publish, but a) the current implementation of cargo produces such artifacts in some cases and b) we have existing crate files that work with cargo on such filesystems. Thus we support this case on the server for now until the cargo normalization has been shipped. Afterwards we will not accept such crate files anymore, but we might still need to keep this code around …

tarball: Allow lowercase `cargo.toml` files for now

---

src/background_jobs.rs

This PR implements the equivalent of:
```sql
INSERT INTO background_jobs (job_type, data, priority) (
SELECT 'sync_to_git_index', '{"krate":"serde"}'::jsonb, -50
WHERE NOT EXISTS (
SELECT id FROM background_jobs WHERE job_type = 'sync_to_git_index' AND data = '{"krate":"serde"}'::jsonb FOR UPDATE SKIP LOCKED
)
) UNION ALL (
SELECT 'sync_to_sparse_index', '{"krate":"serde"}'::jsonb, -50
WHERE NOT EXISTS (
SELECT id FROM background_jobs WHERE job_type = 'sync_to_sparse_index' AND data = '{"krate":"serde"}'::jsonb FOR UPDATE SKIP LOCKED
)
);
```
This should ensure we don't enqueue a bunch of duplicate jobs if someone decides to yank/unyank a lot of versions of the same crate in a short amount of time.

Job::enqueue_sync_to_index: Only insert new jobs if no similar unlocked jobs exist

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

see https://doc.rust-lang.org/cargo/reference/config.html#termcolor

CI: Use `CARGO_TERM_COLOR: always` to enable colorful cargo output

---

src/tests/krate/publish.rs

https://github.com/rust-lang/crates.io/blob/281a57333234f516b4595b0b5e86030b8d52bc80/crates_io_tarball/src/manifest.rs#L31-L44 wasn't particularly well tested before, so this PR adds a dedicated test to ensure we don't lose this validation

tests/krate/publish: Add invalid `rust-version` test

---

.github/workflows/smoke-test.yml

I guess the diff speaks for itself :D

CI/smoke-test: Simplify `cargo` CLI flags

---

README.md

We are using the main branch right now.

Updated outdated default branch name

---

src/controllers/krate/publish.rs

This lets us get rid of the unnecessary `map_err()` operation since the `?` operator calls `into()` automatically :)

controllers/krate/publish: Replace `tarball_to_app_error()` fn with `From` implementation

---

src/controllers/krate/publish.rs
src/tests/krate/publish/basics.rs
src/tests/krate/publish/snapshots/all__krate__publish__tarball__empty.snap
src/tests/krate/publish/snapshots/all__krate__publish__tarball__json_bytes_truncated.snap
src/tests/krate/publish/snapshots/all__krate__publish__tarball__json_len_truncated.snap
src/tests/krate/publish/snapshots/all__krate__publish__tarball__tarball_bytes_truncated.snap
src/tests/krate/publish/snapshots/all__krate__publish__tarball__tarball_len_truncated.snap
src/tests/krate/publish/tarball.rs

controllers/krate/publish: Fix copy paste mistakes in error messages

---

src/tests/util.rs

This extra abstraction layer is barely worth it for the two lines of duplication that it saves...

tests/util: Inline `modify_owners()` fn

---

src/tests/krate/yanking.rs

See https://github.com/rust-lang/crates.io/actions/runs/6191130738/job/16808782508

Fix flaky yank ratelimit test

---

src/controllers/krate/publish.rs

We have gathered enough data about what common metadata lengths are since 2019, so this is no longer needed anymore.
see also:
- https://github.com/rust-lang/crates.io/issues/1896#issuecomment-1731401231

controllers/krate/publish: Remove `metadata_length` field from request logs

---

src/views/krate_publish.rs

Having the `impl` blocks so far away from the structs was very confusing. This change ensures that it is harder to miss them...

views/krate_publish: Reorder file contents

---

src/tests/krate/publish/dependencies.rs

The `DependencyBuilder` accepts invalid version strings in `version_req()` so there is no need for us to manually perform a string replacement on the JSON metadata blob. This change has the added benefit of also using the broken version string in the generated `Cargo.toml` file.

tests/krate/publish/dependencies: Simplify "broken version string" test

---

src/controllers/krate/publish.rs

This seems safer than relying on the database to do the right thing and the code looks a bit less confusing... 😅

publish: Always set `kind` column value

---

frontend.Dockerfile
package.json

Hopefully this works better than the v18.18.0 update in https://github.com/rust-lang/crates.io/pull/7142...

Update Node.js to v20.8.0

---

src/app.rs
src/router.rs

Added a comment to the storage and updated the index comment.

chore: add some comments

---

.github/renovate.json5

see https://docs.renovatebot.com/upgrade-best-practices/

renovate: Use `config:best-practices` preset

---

src/util/bytes_request.rs

This will allow the code to also work with e.g. https://docs.rs/tower-http/latest/tower_http/timeout/struct.TimeoutBody.html

util/bytes_request: Accept generic `Body` types

---

Cargo.toml
src/middleware.rs
src/middleware/app.rs

less custom code to maintain... very nice!

tower-http: Use `AddExtensionLayer` instead of custom middleware function

---

docs/CONTRIBUTING.md

Fix wrong frontend command in docs

---

src/config/server.rs

If this environment variable is set to `n` it will disable the use of the nginx wrapper process on our Heroku servers. The servers are currently not using this environment variable and thus should keep using nginx for now:
- `dotenvy::var("USE_NGINX")` will return `Err(Error::EnvVar(VarError::NotPresent))`
- `unwrap_or_default()` will turn this `Err` into `""`
- `"" != "n"` results in `true`
- -> `let use_nginx_wrapper = true`

Add `USE_NGINX` env var feature flag

---

app/routes/dashboard.js

I follow the steps from https://github.com/rust-lang/crates.io/blob/4b7002d797a9d44b339147c9276823c38f928491/app/routes/crate/version.js#L57
I tested it locally, it works well.
And I also tested reporting errors to the sentry.

Handle load more task error in dashboard

---

src/bin/server.rs

Code lines are expensive... let's save one 😂 
Arguably, the match statement is also a bit easier to read?

bin/server: Replace `if let` with simpler `match` statement

---

src/tests/util/fresh_schema.rs

This can be used in combination with `.with_span_events(FmtSpan::CLOSE)` to gain an understanding of how long the individual steps of creating and dropping a fresh database schema take when running our test suite.

tests/util/fresh_schema: Extract instrumented functions

---

src/bin/background-worker.rs

We have the tools… let's use them! 😄

background-worker: Simplify `job_start_timeout` assignment

---

src/background_jobs.rs

As a nice side-effect, this also simplifies the return types of the closure functions, since they no longer need to return `Result` types.

background_jobs: Reduce `to_value()` calls in `enqueue_sync_to_index()` fn

---

src/background_jobs.rs

... and slightly simplify its implementation.

background_jobs: Convert `fresh_connection()` fn to method

---

src/worker/dump_db/readme_for_tarball.md

I think @szabgab is right that we should have this included in the tarball.

dump_db: improve README based on #7030

---

src/worker/swirl/runner.rs

This allows us to reuse the logic elsewhere and have a bit less indentation in this part of the file :D

worker/swirl/runner: Extract `with_sentry_transaction()` fn

---

src/worker/swirl/runner.rs

We don't need to clone these since the job registry itself is inside an `Arc` already, so we can use the less expensive `Box` instead.

worker/swirl/runner: Use `Box` instead of `Arc` for task fns

---

src/worker/swirl/runner.rs

This gives us a better split between the code that is running on the main thread, and what is running on a worker thread. The purpose of the `Runner` is to orchestrate the pool of workers, while the `Worker` is responsible for running jobs.

worker/swirl/runner: Extract `Worker` struct

---

src/downloads_counter.rs

downloads_counter: Improve doc comment

---

src/worker/environment.rs
src/worker/jobs/daily_db_maintenance.rs
src/worker/jobs/dump_db.rs
src/worker/jobs/git.rs
src/worker/jobs/readmes.rs
src/worker/jobs/update_downloads.rs
src/worker/swirl/background_job.rs
src/worker/swirl/errors.rs
src/worker/swirl/mod.rs
src/worker/swirl/runner.rs

`anyhow::Error` is basically similar to `Box<dyn Error>` but a lot more ergonomic to use :)

worker/swirl: Use `anyhow::Error` instead of `Box<dyn Error>`

---

Cargo.lock
crates_io_smoke_test/Cargo.toml
crates_io_smoke_test/src/api.rs
crates_io_smoke_test/src/cargo.rs
crates_io_smoke_test/src/main.rs

This should allow us to eventually turn off the `blocking` feature of `reqwest` :)

Port `crates_io_smoke_test` package to async/await

---

crates_io_index/testing.rs
src/tests/util/test_app.rs

The latter part is required to eventually make the `TestApp` struct `Send + Sync`

Simplify `UpstreamIndex` and make it `Send + Sync`

---

src/tests/all.rs
src/tests/krate/following.rs

tests/krate/following: Simplify test code

---

src/controllers/version/downloads.rs

Simplify `controllers/version/downloads` module

---

src/controllers/user/session.rs
src/tests/routes/session/authorize.rs

controllers/user/session: Simplify `authorize()` endpoint fn

---

src/tests/util/response.rs

This also breaks these long call chains and makes the code a bit easier on the eyes :)

tests/util/response: Replace `unwrap/expect()` calls with assertions

---

src/tests/util.rs
src/tests/util/test_app.rs

Instead of creating a new runtime for every single request we can create it once and then reuse it :)

tests/util: Move `Runtime` creation into `TestAppBuilder::empty()` fn

---

app/components/footer.hbs
app/templates/data-access.hbs
app/templates/policies.hbs

see https://github.com/rust-lang/rfcs/pull/3463

Integrate "crates.io Policy Update" RFC

---

src/admin/enqueue_job.rs
src/bin/monitor.rs

This should prevent accidental bugs from typos and similar situations :)

Use `JOB_NAME` constant instead of string literals

---

Cargo.toml
crates_io_env_vars/Cargo.toml
crates_io_index/Cargo.toml
crates_io_markdown/Cargo.toml
crates_io_smoke_test/Cargo.toml
crates_io_smoke_test/src/cargo.rs
crates_io_smoke_test/src/main.rs
crates_io_tarball/Cargo.toml
crates_io_test_db/Cargo.toml
src/bin/background-worker.rs
src/bin/crates-admin.rs
src/bin/monitor.rs
src/bin/server.rs
src/lib.rs

see https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html#lint-configuration-through-cargo

Move lint rule configuration into `Cargo.toml` file

---

crates_io_tarball/src/lib.rs

tarball: Extract variables to simplify the code

---

src/worker/swirl/runner.rs

This ensures that we consistently log the job id and type when performing any work related to a specific background worker job.

worker/swirl/runner: Improve tracing information

---

src/worker/swirl/runner.rs

The main worker function is still running inside of a transaction, but the obsolete inner transaction and the transaction depth tracking are removed by this PR since they are no longer needed. The need for this came from us using a single database connection with a running transaction per test, but our test suite has transitioned to using fresh databases instead, making the transaction depth tracking obsolete.

worker/swirl/runner: Remove obsolete transaction code

---

Cargo.lock
Cargo.toml
src/cloudfront.rs
src/worker/jobs/dump_db.rs
src/worker/jobs/git.rs

cloudfront: Make async and use built-in retry behavior of the AWS SDK

---

crates_io_index/repo.rs
src/worker/jobs/git.rs

This should automate the first part of https://ops-guide.crates.io/ops/index-squash.html#manual-work

worker/jobs/git: Push squash snapshot branches to `GIT_ARCHIVE_REPO_URL` too

---

src/util/bytes_request.rs

There is no need to start a full `hyper` server when we can use `oneshot()` on the `Router` instead :)

util/bytes_request: Simplify test code

---

src/middleware.rs

Having `RequestBodyTimeoutLayer` (which changes the `Body` type of the `Request`) in the middle of the `ServiceBuilder` has already been hard to deal with in the past, and does not seem to work anymore with axum 0.7. This change moves these three layers out of the `ServiceBuilder` and applies them to the `Router` directly instead, which fixes the compilation errors.

middleware: Move compression and timeout layers out of the `ServiceBuilder`

---

src/middleware.rs

This should allow us to add more middlewares without significantly affecting compile performance (see #7708).

middleware: Split `ServiceBuilder` stacks

---

Cargo.toml

Addresses https://github.com/rust-lang/crates.io/pull/7715#discussion_r1425878876 😅

Clippy: Enable `dbg!()` warnings

---

src/models/owner.rs

models/owner: Simplify `Owner` fns

---

src/models/owner.rs
src/models/team.rs
src/models/user.rs

This reduces some of the verbose code in the `models/owner` module a bit.

Extract `find_by_login()` fns

---

src/controllers/metrics.rs

Simplify `metrics` controller

---

src/controllers/github/secret_scanning.rs

Getting a new connection for every loop iteration seems a bit wasteful...

controllers/github/secret_scanning: Only obtain database connection once per request

---

src/controllers/version/downloads.rs

The `NonCanonicalDownload` struct was useful when we had a custom error message, but as this is no longer the case we don't need this anymore.

controllers/version/downloads: Use regular 404 error instead of custom `NonCanonicalDownload` struct

---

app/components/user-avatar.hbs

Ref-: https://github.com/rust-lang/crates.io/pull/7789
Adding the decoding attribute to images with async for better image rendering. This is a default option in the popular Next.js framework (Reference: https://nextjs.org/docs/app/api-reference/components/image#other-props).
Adding <link rel="preload" as="script" href="..." /> for faster loading of JavaScript needed for the website (Reference: https://web.dev/articles/preload-critical-assets#preloading_javascript_files).
Closes #7789

Enhance Image Rendering: Introduce Async Decoding Attribute

---

src/controllers/helpers/pagination.rs
src/tests/pagination.rs

Related:
- https://github.com/rust-lang/crates.io/issues/7815

controllers/helpers/pagination: Add data access page link to high page offset error message

---

Cargo.lock
Cargo.toml
crates_io_github/Cargo.toml
crates_io_smoke_test/Cargo.toml
crates_io_tarball/Cargo.toml
crates_io_worker/Cargo.toml

This reverts commit 6880379617ceb5d86fbb5ea6a2403de92ee2de02.
Related:
- https://github.com/dtolnay/thiserror/issues/270

Revert "Update Rust crate thiserror to v1.0.52 (#7808)"

---

crates_io_env_vars/src/lib.rs
src/config/server.rs

This PR removes a bit of repetition from the `config/server` module by extracting two list parsing functions into the `crates_io_env_vars` package. These make it easier to read comma-separated lists from environment variables.

env_vars: Extract `list()` and `list_parsed()` fns

---

src/tests/all.rs
src/tests/routes/crates/read.rs
src/tests/routes/crates/snapshots/all__routes__crates__read__show.snap
src/tests/routes/crates/snapshots/all__routes__crates__read__show_minimal.snap

This PR converts the existing tests to snapshot testing, adds a missing test case and remove a bit of unnecessary setup code.

tests/routes/crates/read: Improve tests

---

src/tests/owners.rs

... because these branches of the endpoints are currently untested 🙈

tests/owners: Add "unknown crate" test

---

src/email.rs

This is no longer needed with https://github.com/lettre/lettre/pull/925 :)

email: Remove obsolete custom `Debug` impl

---

src/controllers/krate/publish.rs
src/models/version.rs
src/tests/krate/publish/auth.rs
src/tests/krate/publish/basics.rs
src/tests/krate/publish/build_metadata.rs
src/tests/krate/publish/categories.rs
src/tests/krate/publish/dependencies.rs
src/tests/krate/publish/emails.rs
src/tests/krate/publish/features.rs
src/tests/krate/publish/inheritance.rs
src/tests/krate/publish/keywords.rs
src/tests/krate/publish/manifest.rs
src/tests/krate/publish/max_size.rs
src/tests/krate/publish/similar_names.rs
src/tests/krate/publish/tarball.rs
src/tests/krate/publish/validation.rs
src/tests/team.rs

publish: Return "400 Bad Request" and "403 Forbidden" errors

---

src/worker/jobs/downloads.rs

see https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/download.20counting.20via.20CDN.20logs/near/419219223

worker/jobs/downloads: Ignore log files from the index domain

---

src/controllers/helpers/pagination.rs
src/controllers/krate/search.rs
src/tests/routes/crates/list.rs

Search queries with a space in them were broken by #7941, so reverting.

Revert "Merge pull request #7941 from eth3lbert/count-subq"

---

app/components/crate-sidebar.js
tests/components/crate-sidebar/toml-snippet-test.js

Remove build metadata within the toml snippet

---

Cargo.lock
crates_io_cdn_logs/Cargo.toml
crates_io_cdn_logs/examples/count_downloads.rs
crates_io_cdn_logs/src/download_map.rs
src/worker/jobs/downloads/process_log.rs

Simplify and extend `DownloadMap` API

---

src/worker/jobs/downloads/process_log.rs

We can use `Arc<dyn ObjectStore>` instead and avoid the unnecessary `Box` redirection.

worker/jobs/downloads/process_log: Avoid unnecessary `Arc<Box<dyn ObjectStore>>`

---

src/worker/jobs/downloads/process_log.rs

worker/jobs/downloads/process_log: Split code into more reusable/testable functions

---

src/worker/jobs/downloads/process_log.rs

Postgres has a limit of 65,535 parameters per query, so we have to insert the downloads in batches. Since we fill four columns per `NewDownload` we can only insert 16,383 rows at a time. To be safe we use a maximum batch size of 10,000.

worker/jobs/downloads/process_log: Insert downloads in batches

---

migrations/2024-02-12-120203_remove_unused_index/down.sql
migrations/2024-02-12-120203_remove_unused_index/up.sql

Resolves https://github.com/rust-lang/crates.io/issues/2055
/cc @eth3lbert @paolobarbolini

database: Remove unused `index_follows_user_id` index

---

crates_io_smoke_test/src/api.rs
crates_io_smoke_test/src/main.rs

see https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/Routing.20download.20traffic.20away.20from.20crates.2Eio :)

smoke-test: Check crate file downloads directly from the CDN too

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css

Resolves https://github.com/rust-lang/crates.io/issues/3952

components/crate-sidebar: Allow text selection in install snippets

---

src/app.rs

Specifically the match statement in the `db_read_prefer_primary()` fn is significantly simplified by this small refactoring. The semantics of the code shouldn't have changed though.

app: Use let-else to simplify match statements

---

src/controllers/krate/downloads.rs
src/controllers/krate/versions.rs

This PR eliminates the need to use the entire `Crate` entity when only the `crate_id` is required.

Refactor query to use crate_id only instead of Crate entity

---

src/worker/jobs/typosquat.rs

I don't care that the e-mails have been ugly for Walter and I, but I will care when these are going to Zulip Real Soon Now™.

typosquat: change the template very slightly for e-mails

---

src/controllers/summary.rs

This is roughly similar to #8244 and switches the `/api/v1/summary` endpoint over to using the `crate_downloads` database table instead of the `crates.downloads` column.

controllers/summary: Read downloads from `crate_downloads` table

---

src/controllers/krate/metadata.rs

This is roughly similar to #8244 and switches the `/api/v1/crates/:crate_id` endpoint over to using the `crate_downloads` database table instead of the `crates.downloads` column.

controllers/krate/metadata: Read downloads from `crate_downloads` table

---

src/controllers/helpers/pagination.rs

Best reviewed in "Hide Whitespace Changes" mode... 😅

controllers/helpers/pagination: Return errors early to reduce indentation levels

---

crates/crates_io_cdn_logs/src/paths.rs

see https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/download.20counting.20via.20CDN.20logs/near/426721121
Before we switched the download traffic from the API to the CDNs the log files were recording URLs like `https://static.crates.io/crates/foo/foo-1.2.3.crate`, but with the redirected traffic the URLs now are looking like https://static.crates.io/crates/foo/1.2.3/download`. This PR makes our parser compatible with both URL patterns.

cdn_logs/paths: Add support for `/:crate/:version/download` URLs

---

src/controllers/token.rs

This PR simplifies the `expired_at` filtering slightly by leveraging `assume_not_null`, eliminating the need to construct raw sql ourselves.

Simplify `expired_at` filtering using `assume_not_null`

---

src/metrics/instance.rs

These are using the same metrics for now as the existing r2d2 pools, but with different labels. In the future we might be able to expose more metrics from within `deadpool`.

metrics/instance: Add async connection pools

---

src/middleware/log_request.rs

The majority of download requests are no longer going through the crates.io API, so we can treat the remaining ones like all the other requests.

middleware/log_requests: Remove special casing for download requests

---

src/tests/krate/publish/max_size.rs

The `data` variables were previously initialized on the stack, which occasionally can lead to "stack overflow" issues. Using `vec![]` ensures that the bodies are initialized on the heap, where we don't run into stack size limits.
This should hopefully unblock https://github.com/rust-lang/crates.io/pull/8498

tests/krate/publish/max_size: Reduce stack size

---

app/templates/policies.hbs

Fixes https://github.com/rust-lang/crates.io/issues/8509

policies: Fix indent of sublist items

---

app/components/search-form.hbs

Same as https://github.com/rust-lang/rust/pull/123355

Support typing '/' to search

---

src/models/team.rs
src/tests/routes/crates/owners/add.rs
src/tests/team.rs

Improve GitHub team error message according to https://github.com/rust-lang/cargo/pull/12511

Improve GitHub team error message, and link to docs.

---

src/worker/jobs/downloads/update_metadata.rs
src/worker/jobs/downloads/update_metadata.sql

This makes the query a bit easier to work with and enables syntax highlighting etc. :)

worker/jobs/downloads: Extract long query into SQL file

---

src/worker/jobs/expiry_notification.rs

In the current form our logging system only shows "Checking if tokens are about to expire" without any additional information. This PR adds the number of token notifications that we are about to send out, and the number of successfully sent notifications. It also adds a bunch of optional debug logging that is disabled by default.

worker/jobs/expiry_notification: Add more logging statements

---

src/worker/jobs/expiry_notification.rs

Ideally, we wouldn't have users without associated email addresses, but for some reason we currently appear to have such cases. Instead of treating this as a hard error for the token expiry notification we can log it with `INFO` level and mark the token as processed even if no notification has been sent out.
The current logs for this case are a bit more noisy than intended:

worker/jobs/expiry_notification: Reduce log level for missing email addresses

---

app/styles/category-slugs.module.css

looks like I forgot that route in #8559 😅

styles/category-slugs: Fix dark-mode styling

---

src/worker/jobs/dump_db.rs

This seems a bit easier to deal with than manually comparing with the enumeration index :)

workers/jobs/dump_db: Use `insta` for tarball testing

---

.github/workflows/ci.yml
playwright.config.ts

This is a follow-up PR to #8521 and add e2e test into our CI.

CI: Add e2e test

---

.github/renovate.json5

Improve renovatebot config

---

app/sentry.js

Sentry: Fix staging URL in `allowUrls`

---

src/middleware/real_ip.rs
src/real_ip.rs

This should allow us to verify that the Heroku Router 2.0 update actually fixes [their X-Forwarded-For bug](https://github.com/heroku/roadmap/issues/238).

real_ip: Add debug logging

---

src/models/version.rs

This moves the `impl` blocks closer to their corresponding structs, making the file a little easier to comprehend.

models/version: Reorder impl blocks and structs

---

src/middleware/log_request.rs

The Datadog ingestion pipeline is already set up to handle these kinds of logs correctly (tested on staging).

Use tracing fields for `http` logs

---

src/middleware/log_request.rs

> http.matched_path=/api/v1/crates/:crate_id/:version
This will allow us to derive more metrics from the logs, grouped by the API endpoint.

Add `http.matched_path` field to HTTP request logs

---

app/models/api-token.js
app/models/version.js

Without the braces only the first type was considered...

Fix `@type` annotations

---

src/worker/jobs/rss/sync_updates_feed.rs

static.crates.io is primarily served via Fastly, so we should obviously invalidate that cache too 😅

rss: Invalidate Fastly cache too

---

src/controllers/krate/owners.rs
src/models/krate.rs
src/tests/routes/crates/owners/add.rs

Before this PR, it was possible to cause the "add crate co-owner" API request to repeatedly send spam emails to invitees.
A request can be constructed where the first N-1 invites can be processed successfully, but the Nth purposely fails (i.e. due to the username not existing, or already being an owner of the crate). 
Because the invite API request processing happens serially within one database transaction, the database modifications made by the API handler (including the successfully generated & emailed invites) are all rolled back together. Because the state is rolled back, there's nothing stopping a malicious user from sending the request again, causing the same to reoccur, and sending more emails.
This PR pulls sending emails out of the model (which seems like it probably shouldn't …

fix: send co-owner invite emails after txn commit 

---

src/models/user.rs

The `impl` block for this `struct` was hiding behind the `NewUser` struct and impl block, which is an unexpected location for something directly related to the `User` struct.

models/user: Move `impl` block closer to the `struct`

---

src/controllers/github/secret_scanning.rs
src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token-2.snap

see https://github.com/rust-lang/crates.io/pull/9324#discussion_r1729956543

github/secret_scanning: Fix email formatting

---

src/controllers/user/me.rs

If there is only a single database query in the transaction then we don't really need it. Especially if we're also explicitly ignoring any email sending errors.

user/me: Remove unnecessary `transaction()` call

---

Cargo.lock
Cargo.toml

Related:
- https://github.com/rust-lang/crates.io/pull/9256
- https://github.com/rust-lang/crates.io/pull/9482
- https://github.com/rust-lang/crates.io/pull/9485

Update `tower` and `axum` dependencies

---

src/models/feature.rs

see https://github.com/rust-lang/crates.io/pull/9551#discussion_r1787687860

models/feature: Add iteration limit warning

---

src/admin/delete_crate.rs

similar to https://github.com/rust-lang/crates.io/pull/9598

admin/delete_crate: Reduce `spawn_blocking()` usage

---

crates/crates_io_worker/src/background_job.rs

We're not actually using this, so let's call YAGNI and remove it :)

worker: Inline `enqueue_with_priority()` fns

---

crates/crates_io_index/features.rs

index/features: Simplify `split_features()` fn

---

src/worker/jobs/downloads/queue/job.rs

We can use `diesel-async` instead :)

worker/jobs/downloads/queue: Remove `spawn_blocking()` usage

---

src/worker/jobs/archive_version_downloads.rs

We can use `diesel-async` instead :)

worker/jobs/archive_version_downloads: Reduce `spawn_blocking()` usage

---

src/controllers/krate/search.rs

This refactoring moves some parts into type aliases, which will be helpful when we need more data properties like `default_version`.

controllers/krate/search: Add some type aliases

---

mirage/route-handlers/crates.js
tests/mirage/crates/versions/patch-test.js
tests/mirage/crates/versions/yank/unyank-test.js

Another PR partially extracted from https://github.com/rust-lang/crates.io/pull/9765 :)
Related:
- https://github.com/rust-lang/crates.io/pull/9423
- https://github.com/rust-lang/crates.io/pull/9765

mirage: Implement `PATCH /crates/:name/:version` route handler

---

src/db.rs

see https://github.com/weiznich/diesel_async/pull/189

Migrate to `AsyncPgConnection::try_from_client_and_connection()`

---

src/bin/crates-admin/default_versions.rs
src/bin/crates-admin/migrate.rs
src/bin/crates-admin/render_readmes.rs
src/bin/crates-admin/verify_token.rs
src/boot/categories.rs

This should allow us to get rid of the `db::oneoff_connection()` fns :)

admin: Migrate to async database connections

---

src/bin/crates-admin/render_readmes.rs

`div_ceil()` does pretty much the exact same thing 😅

admin/render_readmes: Simplify `total_pages` calculation

---

src/bin/crates-admin/verify_token.rs

admin/verify-token: Remove obsolete `spawn_blocking()` call

---

src/tests/routes/crates/owners/remove.rs

This PR ensures that owner removal with uppercased logins works as expected.
Related:
- https://github.com/rust-lang/crates.io/issues/4281

tests/routes/crates/owners/remove: Add uppercase test cases

---

Cargo.toml

see https://insta.rs/docs/quickstart/#optional-faster-runs

insta: Compile with `opt-level = 3`

---

src/bin/crates-admin/delete_crate.rs

as suggested by @weiznich. thank you! :)

admin/delete_crate: Replace raw SQL with diesel subquery builder

---

src/controllers/crate_owner_invitation.rs

controllers/crate_owner_invitations: Remove `spawn_blocking()` call

---

src/controllers/version/downloads.rs

controllers/version/downloads: Remove `spawn_blocking()` call

---

src/worker/jobs/downloads/update_metadata.rs

Another one down, 23 more to go 🎉

worker/jobs/downloads/update_metadata: Remove `spawn_blocking()` call

---

src/controllers/krate/search.rs

This finally fixed the `FIXME` comment that's been around roughly forever :D

controllers/krate/search: Use `.contains()` fn

---

src/controllers/summary.rs

... plus a couple of other smaller refactorings 😅 
This should make the `summary` endpoint slightly more comprehensible :)

controllers/summary: Convert `Record` to named struct

---

app/models/version.js

Related:
- https://github.com/rust-lang/crates.io/issues/10091
- https://github.com/LukeMathWalker/cargo-manifest/pull/60
- https://github.com/rust-lang/crates.io/pull/10093

Infer MSRV for Rust Edition 2024

---

mirage/route-handlers/crates.js
tests/mirage/crates/delete-test.js

see https://github.com/rust-lang/crates.io/pull/9904

mirage: Implement `DELETE /api/v1/crates/:name` endpoint

---

src/bin/crates-admin/render_readmes.rs
src/rate_limiter.rs
src/util/errors.rs
src/util/errors/json.rs
src/worker/jobs/archive_version_downloads.rs
src/worker/jobs/dump_db.rs
src/worker/jobs/index/squash.rs

see https://docs.rs/chrono/0.4.39/chrono/format/strftime/index.html

chrono: Use strftime shortcut specifiers

---

src/controllers/krate/versions.rs
src/tests/routes/crates/versions/list.rs
src/tests/routes/crates/versions/snapshots/crates_io__tests__routes__crates__versions__list__versions.snap

Per https://github.com/rust-lang/crates.io/pull/9624#issuecomment-2544487253

controllers/krate/versions: Add `release_tracks` meta for non-paginated versions

---

src/controllers/krate/search.rs

We can figure out the `auth_user_id` value at the point where we turn the `ListQueryParams` instance into `FilterParams`. This then allows us to get rid of the `OnceLock`, and remove the extra arguments from the `make_query()` fn.

controllers/krate/search: Simplify `auth_user_id` code

---

app/components/email-input.module.css

Obviously, the most pressing issue we face.

components/email-input: fix the dark theme border by using gray-border

---

src/controllers/version/metadata.rs
src/controllers/version/update.rs
src/models/action.rs

I just rewrote this using pipelining, but I haven't done any benchmarking (though I expect the performance improvement to be marginal).

controllers/version: Pipelining database queries

---

src/controllers/krate/metadata.rs

Looks like I missed this one :P
Related:
- #10306

controllers/krate/metadata: Pipelining database queries

---

src/router.rs

router: update dev-mode /git/index path to Axum 0.8 format

---

app/components/header.hbs
app/components/search-form.hbs

fix: only autofocus search form on hero header

---

src/controllers/krate/delete.rs
src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_new_crate-2.snap
src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_old_crate-2.snap
src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_really_old_crate-2.snap

Tiny thing, kind of bugged me when I received the mail.

capitalize first sentence of crate delete mail

---

src/tests/snapshots/crates_io__tests__read_only_mode__cannot_hit_endpoint_which_writes_db_in_read_only_mode.snap
src/util/errors.rs

I guess the title says it all... :D

Include status page URL in read-only mode error message

---

src/controllers/user/update.rs
src/models/email.rs
src/models/user.rs
src/tests/util/test_app.rs

models/email: Improve `NewEmail` struct

---

.github/workflows/ci.yml

... or at least attempt it 😅 
Related:
- https://github.com/rust-lang/crates.io/pull/9051

CI: Fix caching

---

package.json

see https://github.com/pnpm/pnpm/releases/tag/v10.0.0

pnpm: Allow msw to run postinstall script

---

.buildpacks

see https://github.com/Turbo87/heroku-buildpack-crates-io/commit/9f7dc067dcda506ea94ca2d77f863588c5558241

Update Heroku buildpack

---

crates/crates_io_diesel_helpers/src/pg_enum.rs

I was missing this a couple of days ago. I didn't actually end up needing it, but I guess it doesn't hurt to have it, if we need it in the future.

pg_enum: Add support for additional attributes

---

app/components/version-list/row.hbs
app/components/version-list/row.js
app/components/version-list/row.module.css

as discussed in the team meeting:
Related:
- https://github.com/rust-lang/crates.io/pull/10540

VersionList::Row: Limit the length of the features list

---

.editorconfig

Simplify `.editorconfig` file

---

crates/crates_io_cdn_logs/benches/count_downloads.rs

This should unblock https://github.com/rust-lang/crates.io/pull/11197 :)

benches: Use `black_box()` from `std::hint`

---

src/worker/jobs/index_version_downloads_archive/index.html.j2
src/worker/jobs/index_version_downloads_archive/snapshots/crates_io__worker__jobs__index_version_downloads_archive__tests__generate_html.snap
src/worker/jobs/index_version_downloads_archive/snapshots/crates_io__worker__jobs__index_version_downloads_archive__tests__generate_html_empty.snap
src/worker/jobs/index_version_downloads_archive/snapshots/crates_io__worker__jobs__index_version_downloads_archive__tests__template_context.snap

I have no idea why I didn't do this to start with.

index_version_downloads_archive: add table headings

---

.buildpacks

see https://github.com/Turbo87/heroku-buildpack-crates-io/commit/4a92ba7ad3df252cfeb4612431010558a74b7ab6

Heroku: Update buildpack

---

src/controllers/github/secret_scanning.rs

This condition seems a bit redundant... 😅

email: Simplify `token_exposed` context
