rust-lang/crates.io

src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/tasks/dump_db/gen_scripts.rs

It's a minor cleanup, uses `Vec::with_capacity()` as possible to prevent reallocation.

Use `Vec::with_capacity()` as possible

---

Cargo.lock
Cargo.toml

Update `parking_lot` to 0.10 (and `r2d2` to 0.8.8 from 0.8.6). This leaves only one version of `parking_lot` in the dependencies and removes some packages.
r? @jtgeibel

Update `parking_lot` to 0.10

---

src/controllers.rs
src/controllers/krate/publish.rs
src/middleware.rs
src/middleware/log_request.rs

This PR includes the crate name and version in the log entries of the publish API, to fix #2228 and to aid debugging issues in production. This is done in three steps.
First, the log entry generation code was refactored to easily allow adding new fields to it. Now, instead of hardcoding the list of fields in a `format!` macro, there is a builder with methods to add individual fields.
~~Then, a way to attach custom log fields to a response was added. This is implemented by setting HTTP headers in the response starting with `X-CratesIo-Log-Metadata-`, and by changing the middleware responsible for request logging to strip those headers and add their content to the log line instead.~~
Then, a way to attach custom log fields to a response was added. This is implemented as a "request …

Include crate name and version in the publish API's log entries

---

src/git.rs

Per #2226; is this sufficient to resolve that issue?
This PR simply adds a log message (`println!`) right before carrying out the final `commit_and_push` operation, which could otherwise fail silently if the Git host is experiencing an outage.

Add a log message to add_crate background job

---

src/controllers.rs
src/controllers/krate/publish.rs
src/middleware/log_request.rs
src/router.rs
src/util/errors.rs

This builds on the logging infrastructure recently added by @pietroalbini.  Whenever a user facing error is chained around an internal error, the router now captures that message and adds it to the log metadata.
In particular, this should allow us to identify errors sent to cargo via `cargo_err` which are sent via a status 200 response and left no indication in the logs that an error has occurred.

Log inner chained errors

---

Cargo.lock

Mainly this updates wasm related packages and removes some packages.
r? @jtgeibel

Run `cargo update -p web-sys --aggressive`

---

app/components/api-token-row.hbs
app/routes/login.js
app/services/session.js
app/templates/me/index.hbs
tests/acceptance/api-token-test.js
tests/helpers/visit-ignoring-abort.js

This adds a few basic application test for the API token list on the `/me` route. This should help in preventing regressions like mentioned in #2211.
r? @jtgeibel

Add tests for the API token list

---

Cargo.lock
Cargo.toml

Update handlebars to 3.0.1 ([changelog](https://github.com/sunng87/handlebars-rust/blob/master/CHANGELOG.md)).
cc #1265
Output:
```text
Updating handlebars v2.0.1 -> v3.0.1
Removing hashbrown v0.5.0
Updating quick-error v1.2.2 -> v1.2.3
Removing same-file v1.0.5
Removing walkdir v2.2.9
```
r? @jtgeibel

Update handlebars to 3.0.1

---

Cargo.lock

Update quote and failure versions since quote v1.0.2 has been yanked and failure v0.1.6 has compilation issue.
```text
Updating failure v0.1.6 -> v0.1.7
Updating failure_derive v0.1.6 -> v0.1.7
Updating quote v1.0.2 -> v1.0.3
```
r? @jtgeibel

Update quote and failure versions

---

src/controllers.rs
src/controllers/krate/owners.rs
src/models/keyword.rs
src/models/token.rs
src/views.rs

Resolves `clippy::single_component_path_imports`
r? @JohnTitor

Address clippy lint for unnecessary imports

---

app/styles/app.scss

This makes the frontend use a better-looking, more consistent font stack.
*Note: The font used depends on the OS (as before). Screenshots below were taken on Fedora 31 with Microsoft fonts installed.*

Use a modern font stack inspired by Bootstrap 4

---

src/background_jobs.rs
src/bin/background-worker.rs

When we fail to *start* (not run) new jobs, which could happen because
all our worker threads are saturated by a job that is taking too long,
we will rebuild the runner up to 5 times in an attempt to recover before
killing the process. Importantly, if this occurred because of a slow
job, this should give those slow jobs a chance to finish without
blocking the rest of the queue.
However, we were sharing a database pool even when we rebuilt the
runner. This means that if the slow jobs held a database connection,
our retries will just fail immedaitely, and we kill the process (along
with any hopes of the slow job catching up). This creates a new
connection pool whenever we restart the runner.
r? @jtgeibel

Create a new DB pool when rebuilding the worker

---

src/models/krate.rs

Found on: https://crates.io/crates/valico
No longer hosts any kind of rust documentation.

Add rustless.org to documentation blocklist

---

src/controllers/util.rs
src/middleware/block_traffic.rs
src/middleware/require_user_agent.rs

Add some error chaining to log more on auth failure

---

app/controllers/crate/owners.js
app/models/team.js
app/templates/crate/owners.hbs
mirage/route-handlers/crates.js
tests/acceptance/crate-test.js

This change updates the crate owners page (`/crates/<crate-name>/owners`) to display teams which are set to be crate owner. It also adds a "Remove" button for each team which allows removing teams from owning the crate in the same way that user type owners can be removed.
I have displayed the team as `<organisation>/<team>` rather than `github:<organisation>:<team>` because I think it looks cleaner (eg `rust-lang/core` vs `github:rust-lang:core`). Happy to change it if people disagree.
I haven't touched adding teams via the owners page in this PR. From what I can tell, it is currently possible although the message that is returned is misleading. I think that should be tackled in a separate PR.
Addresses #1617.

Display teams on the crate owners page

---

Cargo.lock

This is a tiny change, updates `futf` to 0.1.4 to remove `debug_unreachable` and `unreachable`.
Output:
```
Removing debug_unreachable v0.1.1
Updating futf v0.1.3 -> v0.1.4
Removing unreachable v0.1.1
```

Update `futf` to 0.1.4

---

tests/acceptance/api-token-test.js

This PR improves upon #2251 by adding a Percy snapshot to the API tokens test. This will ensure that the styling of the `/me` route will not get broken in the future.

tests/api-token: Add Percy snapshot

---

app/components/link-to-dep.hbs
app/components/link-to-dep.js
app/components/link-to-dep.module.scss
app/styles/app.scss
app/templates/crate/version.hbs

as the title says, this PR converts the `<LinkToDep>` component to be template-only and use CSS modules

LinkToDep: Convert to template-only component and CSS modules

---

app/styles/application.module.scss

This reverts commit a5dcbce630d610121724ae667bf6718fab1be439.
Turns out this doesn't behave quite the same if the content demands more space than available 🙈 
r? @locks

Revert "application: Simplify max width assignment"

---

app/components/dropdown/content.js
app/components/dropdown/trigger.js
app/styles/crate.scss
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

Some of our dropdowns were using `<a>` tags to open the dropdown, but that is semantically invalid HTML because `<a>` tags should only be used when **linking** to another page. Instead the dropdowns are now using `button` elements for their triggers.
r? @locks

Simplify dropdown styling and fix dropdown trigger semantics

---

Cargo.lock

It combines some tiny updates to remove some packages.
log:
```
Updating crates.io index
Removing antidote v1.0.0
Updating atty v0.2.10 -> v0.2.14
Removing c2-chacha v0.2.3
Updating rand_chacha v0.2.1 -> v0.2.2
Removing redox_termios v0.1.1
Updating scheduled-thread-pool v0.2.0 -> v0.2.3
Removing termion v1.5.1
```
r? @jtgeibel 
I'll leave the decision whether we include this to next deploying or not to you.

Update dependencies to remove some packages

---

.github/workflows/ci.yml

Travis allows us to ignore errors building on nightly.  Because failed
Actions are shown so prominently in the UI (and sends an email to the
author), lets drop this build until we can run such non-essential
builds in Actions.
r? @JohnTitor

CI: Don't run nightly for GH Actions    

---

app/styles/app.scss
app/styles/home.scss

I couldn't find these styles being used anywhere in our templates or elsewhere in the app.
r? @locks

Remove more unused CSS declarations

---

app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

There does not seems to be any code that relies on these IDs being set, so I think it should be save to remove them.
r? @locks

Remove unused `id=crates` assignments

---

mirage/fixtures/crates.js

`huonw/external_mixin` no longer exists on GitLab and leads to a broken badge image

mirage/fixtures: Remove broken GitLab badge

---

app/templates/search.hbs

There is no CSS associated with these IDs and it seems unlikely that anyone wants/needs to link directly to these anchors.
r? @locks

search: Remove unnecessary `#no-results` wrapper elements

---

app/styles/me.scss

There are no `.row` or `.align-center` elements in `#me-profile` (anymore?).
r? @locks

styles/me: Remove unused style declarations

---

app/components/email-input.hbs
app/templates/crate/owners.hbs

There is no `.small-text` style definition for these cases so we might as well remove those unused assignments.
r? @locks

Remove unused `.small-text` CSS class assignments

---

Cargo.lock
Cargo.toml
src/background_jobs.rs
src/bin/background-worker.rs
src/controllers/krate/publish.rs
src/controllers/version/yank.rs
src/db.rs
src/git.rs
src/render.rs
src/tasks/update_downloads.rs
src/tests/util.rs
src/util/errors.rs

This is to make master deployable.  The original PR caused issues with running background jobs.
This reverts commit b63607eab318d5ce1531835a39b7f48b4c99519d, reversing changes made to dc18552facdda23742d4c5b9e16a88a6e8c122b8.
r? @ghost
cc @sgrif #2269

Revert #2269

---

app/styles/app.scss
ember-cli-build.js

This moves the code into the `vendor.css` file
r? @locks

Import `normalize.css` via `app.import()`

---

app/styles/app.scss

Looks like we managed to remove/replace all of the usages of this CSS class :)
r? @locks

styles/app: Remove unused `small` CSS class

---

app/styles/categories.module.scss
app/styles/category/index.module.scss
app/styles/crate.scss
app/styles/crate/reverse-dependencies.module.scss
app/styles/crates.module.scss
app/styles/keyword/index.module.scss
app/styles/keywords.module.scss
app/styles/me/crates.module.scss
app/styles/me/following.module.scss
app/styles/search.module.scss
app/styles/team.module.scss
app/styles/user.module.scss
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crate/reverse-dependencies.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

... which replaces the `id="results"` assignments. While they all look similar there are sometimes slight differences. If it's considered worth it, we can try to deduplicate these styles at a later point.
r? @locks

Extract `results-meta` CSS module classes

---

app/components/api-token-row.module.scss
app/components/crate-row.module.scss
app/components/crate-toml-copy.module.scss
app/components/dropdown/menu-item.module.scss
app/components/dropdown/menu.module.scss
app/components/front-page-list/item.module.scss
app/components/owned-crate-row.module.scss
app/components/page-header.module.scss
app/components/pagination.module.scss
app/components/results-count.module.scss
app/components/sort-dropdown.module.scss
app/styles/app.scss
app/styles/application.module.scss
app/styles/categories.module.scss
app/styles/category/index.module.scss
app/styles/crate/owners.module.scss
app/styles/crate/reverse-dependencies.module.scss
app/styles/crate/version.module.scss
app/styles/crates.module.scss
app/styles/dashboard.module.scss
app/styles/index.module.scss
app/styles/keyword/index.module.scss
app/styles/keywords.module.scss
app/styles/me/crates.module.scss
app/styles/me/following.module.scss
app/styles/me/index.module.scss
app/styles/shared/typography.module.scss
app/styles/team.module.scss
app/styles/user.module.scss

This will allow us to get rid of the `app.scss` file and finally disable the `intermediateOutputPath` option of ember-css-modules.

Replace SASS variables with CSS variables

---

app/styles/app.scss
ember-cli-build.js

This is no longer needed, now that the `app.scss` file is essentially empty  🎉 
This brings us another step closer to being able to use https://github.com/embroider-build/embroider/
r? @locks

css-modules: Remove `intermediateOutputPath` override

---

app/components/email-input.js
app/components/follow-button.js
app/controllers/dashboard.js
app/controllers/me/index.js
app/routes/accept-invite.js
app/routes/confirm.js
app/routes/crate/version.js
app/routes/github-login.js
app/routes/logout.js
app/services/fetcher.js
app/services/session.js
app/utils/ajax.js

This utility is being removed from `ember-fetch` in v8, so we should import it into our own code to continue to use it.
Unblocks #2364 
r? @locks

Import `ajax()` utility from `ember-fetch`

---

app/components/api-token-row.hbs
app/components/api-token-row.js
app/components/email-input.hbs
app/components/email-input.js
app/components/pending-owner-invite-row.hbs
app/components/pending-owner-invite-row.js

async actions are dangerous because they reference component instances that might have already been destroyed when the async behavior finishes. ember-concurrency tasks resolve this issue by cancelling themselves if the parent object is destroyed.
r? @locks

Convert async actions on components to tasks

---

app/controllers/crate/version.js
app/routes/crate/version.js

This converts the README loading code into an ember-concurrency task in the controller, and removes the observer on the `readme` property by calling the code in the task directly.
r? @locks

Simplify README loading code

---

app/components/badge-maintenance.hbs
app/components/badge-maintenance.js

* Change the alt-text to be a little more descriptive
and screen-reader friendly
* Link to the Cargo documentation from the badge which describes what the maintenance intentions are
This addresses #2134. Have a read through of my summary for the motivations on the ticket to get a little context of what this is trying to achieve.

Improve the maintenance badge user experience

---

app/routes/confirm.js
app/templates/confirm.hbs
tests/acceptance/email-confirmation-test.js

There is no need for an API call here. We can use the `pushPayload()` method of the store instead to update the user record as if the API had sent us the payload.
r? @locks

routes/confirm: Simplify `email_verified` update

---

Cargo.lock

This aims to update `rand` and `proc-macro2` dependencies, to remove old versions in the future. Note that this adds some new deps.
Commits between v3.0.0 and v3.1.0: https://github.com/rust-ammonia/ammonia/compare/v3.0.0...v3.1.0
```
Updating crates.io index
Updating ammonia v3.0.0 -> v3.1.0
Updating html5ever v0.24.1 -> v0.25.1
Updating markup5ever v0.9.0 -> v0.10.0
Adding markup5ever_rcdom v0.1.0
Updating phf v0.7.24 -> v0.8.0
Updating phf_codegen v0.7.24 -> v0.8.0
Updating phf_generator v0.7.24 -> v0.8.0
Updating phf_shared v0.7.24 -> v0.8.0
Adding rand_pcg v0.2.1
Updating siphasher v0.2.2 -> v0.3.2
Updating string_cache v0.7.3 -> v0.8.0
Updating string_cache_codegen v0.4.2 -> v0.5.1
Removing string_cache_shared v0.3.0
Adding xml5ever v0.16.1
```
r? @jtgeibel

Update ammonia to v3.1.0

---

src/middleware.rs
src/middleware/log_request.rs

By converting to a regular `Middleware` (instead of `AroundMiddleware`),
the logging can now sit near the top of the middleware stack.
Previously logging occurred at the top of the around stack, which sits
under the layers added via `add()`.
This change ensures that middleware sitting below the request logger
in the stack are able to add logging metadata in a call to `after()`.
r? @JohnTitor

Move request logging near the top of the middleware stack

---

mirage/config.js
mirage/factories/api-token.js
mirage/factories/crate-ownership.js
mirage/factories/mirage-session.js
mirage/factories/user.js
mirage/fixtures/crate-ownerships.js
mirage/models/api-token.js
mirage/models/crate-ownership.js
mirage/models/crate.js
mirage/models/mirage-session.js
mirage/route-handlers/crates.js
mirage/route-handlers/me.js
mirage/serializers/api-token.js
mirage/serializers/team.js
mirage/serializers/user.js
mirage/utils/session.js
tests/acceptance/api-token-test.js
tests/acceptance/crate-following-test.js
tests/acceptance/dashboard-test.js
tests/acceptance/email-confirmation-test.js
tests/acceptance/invites-test.js
tests/helpers/setup-mirage.js
tests/mirage/crates-test.js
tests/mirage/me-test.js
tests/mirage/teams-test.js
tests/mirage/users-test.js

This PR improves our "fake backend" setup which uses https://www.ember-cli-mirage.com/
Due to the number of changes this PR is likely best reviewed commit-by-commit.
The main change is that this PR will make it easier to simulate the logged-in state of the application by providing a relatively simple `this.authenticateAs(user)` helper method on the test contexts.
r? @locks

Improve Mirage setup

---

config/nginx.conf.erb

Serve more folders containing files with hashed filenames directly from
nginx with a max expiration date.  Additionally, some unhashed static
files are allowed to be cached for up to 1 day.
These changes serve as a workaround for an authentication issue.
Currently `conduit-cookie` includes a `Set-Cookie` header in every
backend response.  During the authentication steps, the popup window
requests static assets such as `favicon.ico` and `cargo-{hash}.png`.
If these assets are served by the backend, they will echo whatever
cookie was sent in the request.  Therefore, there is a race between the
request to `/api/private/session/authorize?...` and requests for these
static assets.  If a request for one of these assets is sent before
authorization is complete and the response arrives after …

Serve more static files from nginx

---

src/models/owner.rs
src/tests/owners.rs

Pushing commit by commit to demonstrate test failures and fixes

Fixing issues with owner invites and renamed accounts

---

Cargo.lock
Cargo.toml
src/s3/Cargo.toml

These upstream packages have been updated to prune old dependencies and
include no functional changes at this time.  This PR removes 14
dependencies.
The updated version of `civet` is based on the 0.9 release we have been
pinned to.  The 0.12 release abandons the attempts to update to the
underlying library which resulted in build failures on macOS for the
0.10 and 0.11 releases.

Bump to alpha releases of conduit-* crates

---

mirage/models/user.js
mirage/route-handlers/crates.js
mirage/route-handlers/me.js
mirage/serializers/user.js
tests/acceptance/crate-test.js
tests/acceptance/dashboard-test.js
tests/mirage/crates-test.js
tests/mirage/me-test.js

Using this relationship we can finally implement several of the e-c-mirage route handlers related to users following crates.
Note that Percy.io will most likely complain about this PR due to the change of the dashboard test fixture data.
r? @locks

mirage: Add `followedCrates` relationship to the `user` model

---

app/routes/crate/version.js

This was only used when we were loading the `following` status in the model hook, but we no longer do that, so this observer is not useful anymore.
r? @locks

crate.version: Remove obsolete `refreshAfterLogin` observer

---

app/routes/crate.js

If an error was thrown without an `errors` property the error handler would crash, and if the error had such a property but without the "Not Found" detail the error would still not be shown because it wasn't rethrown.
r? @locks

crate: Fix error handling in `model()` hook

---

app/controllers/crate/version.js
app/models/version.js
app/routes/crate/version.js
app/templates/crate/version.hbs

The `readme_path` property is on the `version` resource, but we currently cache the README file content per crate. This PR cleans up the README loading code to cache the README per version instead, which means that we now show the correct README file corresponding to the selected version.
r? @locks

Improve README loading code

---

mirage/fixtures/crates.js

This fixes several warnings in the test suite :)
Resolves https://github.com/rust-lang/crates.io/issues/2156
r? @locks

mirage/fixtures: Add missing `updated_at` values

---

config/optional-features.json

We don't have any observers in the app anymore, so this should be safe to do. This is the final missing piece before we can toggle the Ember Octane flag.
r? @locks

ember: Enable optional `default-async-observers` feature

---

app/controllers/crate/version.js
app/models/version.js
app/routes/crate/version.js
app/templates/crate/version.hbs

This gets rid of the last remaining Array/PromiseProxy in the app and simplifies the data loading code a little more.
r? @locks

crate.version: Replace `displayedAuthors` property with `version` model task

---

src/middleware/ember_index_rewrite.rs
src/util/errors.rs
src/util/errors/concrete.rs

To avoid the need to set up a local nginx configuration during
development, this commit adds a simple proxy for frontend requests when
`USE_FASTBOOT=staging-experimental` is set.
When enabled, developers should browse to http://localhost:8888/
(instead of port 4200 when using `npm run start:local`).

Add backend proxy to aid local fastboot testing

---

.editorconfig

We seem to be using four spaces in CSS files at the moment 🤷‍♂️ 
r? @locks

editorconfig: Adjust `indent_size` for CSS files

---

Cargo.lock

This is also a step toward removing old proc-macro dependencies.
r? @jtgeibel 
log:
```
Updating crates.io index
Updating diesel v1.4.2 -> v1.4.4
Updating diesel_derives v1.4.0 -> v1.4.1
Updating diesel_full_text_search v1.0.0 -> v1.0.1
```

Update diesel related packages

---

app/mixins/authenticated-route.js
app/routes/application.js
app/routes/confirm.js
app/routes/login.js
app/services/session.js
tests/acceptance/login-test.js

This PR aims to simplify the state management in the `session` service. Instead of the various properties that were manually set I'm using a `loadUserTask` with a return value and a bit of derived task state.
The async nature of the authentication process is preserved by the `application` route triggering the new task, but not waiting for the result. The authenticated route mixin relies on the `application` route having triggered the task and waits for that specific task instance to resolve before continuing.
r? @locks

services/session: Replace manual state management with `loadUserTask`

---

app/routes/-authenticated-route.js
app/routes/dashboard.js
app/routes/me/crates.js
app/routes/me/following.js
app/routes/me/index.js
app/routes/me/pending-invites.js

This will make it easier to eventually use ES6 classes instead, and gets rid of one more mixin.
r? @locks

Convert `AuthenticatedRoute` mixin to regular base class

---

app/controllers/crate/owners.js
app/templates/crate/owners.hbs

crate.owners: Replace async actions with ember-concurrency tasks

---

app/styles/application.module.css
app/templates/application.hbs

This PR slightly adjusts the styling of the "main" section of the page. Instead of having it in a box we extend it horizontally to the full width of the page. 
r? @locks

Adjust styling of the "main" section

---

script/ci/prune-cache.sh

This ensures that `rm` does not fail when files don't exist and will hopefully fix the broken GitHub Actions job.
r? @jtgeibel

ci/prune-cache: Use `rm -f` to delete unnecessary files

---

Cargo.lock

This bumps a few dependencies (in particular `ctor`) to fix linking with `lld`.  Before this fix, tests would fail because the background jobs were not being registered correctly.
I'm seeing very promising results with `lld` locally.  Here are my times for a clean incremental build (after `touch src/lib.rs`) when running `time cargo test --no-run`:
```
real    0m54.108s
user    4m57.944s
sys     0m50.454s
```
```
real    0m20.015s
user    0m59.601s
sys     0m14.471s
```
Our production and CI are on an Ubuntu 16.04 stack, so I'm not sure what it would take to make this configuration the default.
r? @JohnTitor

Fix tests when linking with lld

---

Cargo.lock
Cargo.toml

This reduces the use of url 1.x (last thing is oauth2) and requires one additional dependency (jobserver).
```
Updating git2 v0.8.0 -> v0.13.5
Adding jobserver v0.1.21
Updating libgit2-sys v0.7.11 -> v0.12.5+1.0.0
```
cc #1265
r? @jtgeibel

Update `git2` to 0.13

---

.env.sample
app.json
docker-compose.yml
script/init-local-index.sh
src/app.rs
src/config.rs
src/middleware/ember_index_rewrite.rs
src/router.rs
src/tests/all.rs
src/tests/git.rs

The "index checkout" directory is used to initialize the bare index repo
but is not kept in sync after that. It seems unnecessary to require all
environments to define the `GIT_REPO_CHECKOUT` variable, so it is
dropped as well.
During local development, the `tmp/index-bare` repo is automatically
served at `/git/index` by the HTTP backend.
r? @JohnTitor

Fix serving `/git/index` during local development

---

app/routes/index.js

This will cause the app to only once perform the `GET /summary` call and then keep showing the same data until the whole app is refreshed. This should get rid of the annoying loading screen when navigating from the frontpage to a crate and then back again.
r? @locks

index: Reuse `GET /summary` result

---

.template-lintrc.js
app/templates/dashboard.hbs

This PR enables two more recommended ember-template-lint rules 🎉

template-lint: Enable `no-curly-component-invocation` and `require-valid-alt-text` rules

---

app/routes/category.js
app/routes/keyword.js
app/templates/error.hbs
tests/routes/category-test.js
tests/routes/keyword-test.js

When a non-404 error was returned from the backend the routes would continue with business-as-usual instead of showing the generic error page. Rethrowing the error fixes that behavior.
r? @locks

category|keyword: Rethrow unhandled errors

---

app/controllers/application.js
app/controllers/search.js
app/routes/index.js
app/routes/search.js
app/services/header.js
app/services/search.js
app/templates/application.hbs

This PR simplifies the code that handles the values of the two search boxes in the header. It mainly gets rid of a query param `alias()`, an unnecessary `oneWay()` property and two `controllerFor()` lookups. It also removes the `search` service and adds a new `header` service instead.
r? @locks

Simplify search field handling code

---

Cargo.lock
Cargo.toml
src/background_jobs.rs
src/bin/background-worker.rs
src/controllers/krate/publish.rs
src/controllers/version/yank.rs
src/db.rs
src/git.rs
src/render.rs
src/tasks/update_downloads.rs
src/tests/util.rs
src/util/errors.rs

This is a second attempt at #2269, which had to be reverted shortly
after being deployed, as it caused jobs to fail to run in production.
This commit only differs from that PR in the revision of swirl used.
The cause of the issue was the change in the signature of
`update_downloads`, which does not need anything from the job
environment, and so it only takes a connection. This changed the
environment type for that job from `background_jobs::Environment` to
`()`, so our runner no longer knew how to run that job.
The smallest fix in crates.io would have been to add an unused
environment argument to `update_downloads`. However, having some jobs
not require a shared environment felt common enough that I fixed this in
swirl instead. https://github.com/sgrif/swirl/pull/23 changed the
behavior …

Update Swirl, take two

---

src/bin/monitor.rs

This changes our pageable event for the background queue from "a job is
more than $MAX_JOB_TIME minutes old" to "a job is not currently being
run and is more than $MAX_JOB_TIME minutes old", meaning we will no
longer page for a single job taking longer than $MAX_JOB_TIME minutes to
run.
I've been getting paged a lot lately because `update_downloads` has
taken longer than our threshold to complete, meaning "a job has been in
the queue for too long". While I'd love to know if any other job is
stuck in an infinite loop, this has never triggered for a bug like that.
Any other job having that bug will clog the entire queue pretty quickly.
If a job is making progress, I don't need to be paged. For
`update_downloads`, really there's nothing I can do about it unless
there are two instances …

Don't page for long running jobs

---

Cargo.lock
Cargo.toml

This updates `pest` and `pest_generator` (v2.1.0 -> v2.1.3) and applies a patched `derive_deref` to fully drop old versions of `syn`, `quote`, and `proc_macro2` from our dependency tree!
Once sgrif/derive_deref#6 is merged and released we can switch back to the official release.
r? @JohnTitor

Update pest and derive_deref to drop old macro crates

---

app/styles/application.module.css
app/styles/crate/version.module.css

- Changed the margin to padding on the inline axis, preventing text from butting up against the edge of the display.
- Enable flex-wrap on authorship info. This prevents an overflow on the inline axis. This combined with moving `flex: 1` prevents the inner text from wrapping, improving readability.
Fixes rust-lang/crates.io#2486, along with other improvements.

Improve CSS for smaller displays

---

src/controllers/krate/metadata.rs
src/tests/krate.rs

This will allow us to show something like "3,442 downloads in the past 90 days" in the "Recent Downloads" list on the frontpage.
r? @jtgeibel

summary: Fill `recent_downloads` fields

---

src/app.rs
src/bin/server.rs
src/middleware.rs
src/middleware/balance_capacity.rs
src/tests/all.rs

In recent months we've had several incidents where bot traffic has sent hundreds of expensive requests per minute, starving database resources and resulting in timeouts on download requests. While cargo will retry download requests, builds are sometimes still affected.  For instance, here is an example from our own CI: https://github.com/rust-lang/crates.io/runs/631489355.
This new middleware layer will reject some requests as the database pool reaches capacity. At 20% load, the `in_flight_requests` count is added to the log output. At 70% load, all safe requests (`GET`, `HEAD`, `OPTIONS`, `TRACE`) are rejected immediately. This will reject many legitimate frontend requests as well, but should catch all bot traffic (which is unlikely to send `PUT`, `POST`, or `DELETE` requests). This …

Add middleware to prioritize download traffic

---

config/environment.js

Overriding the default `locationType` is deprecated now
r? @locks

ember-router-scroll: Fix deprecation warning

---

src/middleware/balance_capacity.rs

This adds a single environment variable that can be quickly set or
removed to toggle capacity enforcement. If this variable is set to any
value (including the empty string) then no requests will be rejected due
to load.
This will allow us to evolve the heuristics used in this middleware to
find the right balance before turning on enforcement.
This also increases the default logging percentage to a higher default.

Add a report-only mode to the `BalanceCapacity` middleware

---

docs/ARCHITECTURE.md
docs/CONTRIBUTING.md
script/init-local-index.sh

Follow-up of #2469
r? @jtgeibel

Remove mentions about `index-co`

---

app/routes/login.js
app/services/design.js
app/services/session.js
app/utils/local-storage.js

We should fail gracefully if the browser has `localStorage` blocked. This wrapper will make sure to handle this case in a predictable way.
Resolves #2502 
r? @pichfl 
/cc @danielzgtg

Extract `localStorage` wrappers with try/catch

---

Cargo.lock
Cargo.toml

Bump to rand 0.7

---

src/models/krate.rs
src/tests/krate.rs
src/views/krate_publish.rs

Up front: I am familiar with the several discussions linked by https://github.com/rust-lang/crates-io-cargo-teams/issues/41#issuecomment-494168728, and the conversation beginning at https://github.com/rust-lang/crates.io/pull/1331#issuecomment-379608097. This PR is not motivated by attempting to match whatever behavior Cargo currently has. Instead, it's a small thing I think we can decide now whether to allow. But it's necessary to say no corresponding Cargo change is required to accommodate this crates.io change.
This PR updates feature validation during publish to accept e.g. "c++20" and "dependency/c++20". We continue to not accept "c++20/feature" as the prefix before the slash would normally refer to a crate name of a dependency and a '+' would not be allowed in those.
I am interested …

Permit '+' in feature name, as in "c++20"

---

config/nginx.conf.erb

Seems 2ae350daad12fa046bd2bc0269efb9fb58abaaf4 added the use of google fonts but our CSP config doesn't allow that.
Fixes #2518
r? @jtgeibel or @Turbo87

Allow some google-related domains to fix CSP errors

---

config/nginx.conf.erb

This removes an unnecessary `:` from `font-src` that was causing the directive to fail.
r? @ghost
cc #2519

Fix font-src in CSP

---

Cargo.lock
Cargo.toml
src/bin/server.rs

The latest upstream changes should allow us to try enabling hyper in
production. All tasks tracked in #2204 should now be completed.
r? @JohnTitor

Bump to the latest conduit-hyper

---

Cargo.lock
Cargo.toml

I think we can now use `semver` dependency without specifying the repo.
PR for rustc-version that uses `semver` 0.9: https://github.com/Kimundi/rustc-version-rs/pull/29
r? @jtgeibel

Update `semver` to 0.10

---

src/bin/server.rs

The number of core_threads counts against the max_threads setting. For
parity with the thread count enforced by `civet`, the core thread count
is added to `SERVER_THREADS` when setting the max thread count.
r? @JohnTitor

Account for core_threads when setting up background threads

---

Cargo.lock
Cargo.toml

This upstream release now percent decodes the path component but not the
query string. This behavior aligns with the `civet` server. The known
difference is that `conduit-hyper` does a lossy utf8 conversion while
`civet` panics on invalid utf8 and closes the connection immediately.
This seems like a good compromise of matching the existing behavior as
closely as possible without copying the panic. I looked into fixing the
panic in `civet`, however the `to_str_slice` function returns an
`Option<&str>` and there is nowhere to store a newly allocated `String`
so changing the behavior there is not practical.
r? @JohnTitor 
cc #2204
https://github.com/jtgeibel/conduit-hyper/compare/v0.3.0-alpha.3...v0.3.0-alpha.4

Bump to latest release of conduit-hyper

---

Cargo.lock

proc-macro-hack 0.5.16 has a fix for rust-lang/rust#72545 and fixes our nightly build as well.
This also updates some low-level dependencies, some of them were updated recently and didn't cause failures.
r? @jtgeibel

Update transitive dependencies to fix nightly compilation

---

Cargo.lock
Cargo.toml
src/s3/Cargo.toml

The first 5 commits mirror recent version bumps done in #2488, #2467, and #2535. Since these were recently bumped they should be low risk.
Additionally, the following dependencies are bumped: `ring`, `base64`, `curl`, `curl-sys`, and some `diesel` dependencies (`migrations_internals`, `migrations_macros`, `pq-sys`, `scheduled-thread-pool`).
r? @JohnTitor

Update more backend dependencies

---

src/models/krate.rs

A recent change allowed crates.io crate names to include `+` in their name (requires a patched version of cargo which skips the cargo validation check). See the original issue reported by @ThePuzzlemaker below (#2550):
> I was looking at code and found out that by patching Cargo's code to allow `+` in package names, you can upload a package to the crates.io registry with `+` in the name.
> 
> This issue stems from commit [5f842f7](https://github.com/rust-lang/crates.io/commit/5f842f73c6a9f32719508db4b1c534959b02f6e8), where `+` is allowed in feature names.
> 
> The function `Crate::valid_name` in [`src/models/krate.rs`](https://github.com/rust-lang/crates.io/blob/master/src/models/krate.rs) uses `Crate::valid_ident`, which uses `Crate::valid_feature_name`. Due to …

Fix issue where crates.io allowed the plus sign in crate names

---

app/index.html
app/styles/application.module.css
config/nginx.conf.erb

This brings us closer to a unified style with the other Rust web assets.
Currently deployed at https://staging-crates-io.herokuapp.com/
r? @locks

Use "Fira Sans" font from Mozilla CDN as default font

---

Cargo.lock

3e674dd1374a1f1d3038535a819615fef3702ff2 is the only _unsafe_ thing, this introduces new dependencies.
https://github.com/sunng87/handlebars-rust/compare/v3.0.1...v3.1.0
Also, this updates some dependencies that were recently updated via f88d028c40d09aea9152de0b61204e2cd4131f72.
r? @jtgeibel

Update more*2 backend dependencies

---

config/nginx.conf.erb

I'm not sure when this broke, but the download chart isn't working on production right now and it appears to be due to CSP rules. I'm pushing this to staging now to ensure it works and will merge if so.
r? @ghost

Add gstatic.com to style-src CSP

---

.env.sample
src/config.rs
src/controllers/krate/publish.rs
src/email.rs
src/github.rs
src/middleware/block_traffic.rs
src/tests/all.rs

This PR allows setting the `DOMAIN_NAME` environment variable, which configures the domain name used in absolute URLs returned by the application, for example in emails or Cargo responses.
The scenario that prompted this change is when an user creates an account on the staging instance: before this PR the link they'd get in the verification email was invalid, as the production application doesn't know staging's email verification codes.
If the variable is omitted the domain will default to "crates.io".
r? @jtgeibel

Allow configuring the application's domain name

---

app/templates/categories.hbs
app/templates/category-slugs.hbs
app/templates/category/error.hbs
app/templates/category/index.hbs
app/templates/crate/error.hbs
app/templates/crate/owners.hbs
app/templates/crates.hbs
app/templates/dashboard.hbs
app/templates/keyword/error.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/index.hbs
app/templates/me/pending-invites.hbs

turns out searching for `{{title` doesn't catch the usages that have a space between the curlies and the helper name 😅 
r? @locks

Replace `{{ title }}` with `{{page-title}}`

---

app/components/crate-toml-copy.hbs
app/components/crate-toml-copy.js
app/helpers/is-clipboard-supported.js
package-lock.json
package.json

This PR performs a number of refactorings on the `CrateTomlCopy` component. The main changes are converting it to a Glimmer component and replacing the `ember-cli-clipboard` dependency with https://github.com/sindresorhus/copy-text-to-clipboard to save payload size and simplify the code. It also uses an ember-concurrency task now to prevent race conditions when clicking the button multiple times.
r? @locks

Simplify `CrateTomlCopy` component

---

src/bin/enqueue-job.rs
src/bin/monitor.rs

This ensures that if an `update_downloads` job is already running, a
duplicate job will not be enqueued. Currently, when multiple jobs are
running in parallel, they end up doing duplicate work resulting in
temporary overcounts that must be corrected in the next run. The
concurrent tasks also slow down the overall process and can result in
runaway performance problems as further jobs are spawned.
This commit also updates the monitoring to specifically check if the
update downloads job runs for too long (120 minutes by default). The
main check for stalled jobs will not trigger for `update_downloads` as
the row is locked for the duration of the job (and `skip_locked` is used
in that query).

Only enqueue 1 update_downloads job at a time

---

src/render.rs

Use default branch alias instead of "master"

---

Cargo.lock
Cargo.toml
src/app.rs
src/controllers/user/session.rs
src/github.rs
src/models/team.rs

Release notes: https://github.com/ramosbugs/oauth2-rs/releases
This pulls two versions of `http` crate, it should be resolved once https://github.com/ramosbugs/oauth2-rs/pull/103 is shipped. Otherwise, we can drop some (duplicate) dependencies. Also updates `url` crate to v2.
r? @jtgeibel

Update `oauth2` crate to v3

---

Cargo.lock
Cargo.toml

This makes one dependency duplication but it'll be resolved once we drop rand 0.6.
log:
```
Adding cloudabi v0.1.0
Adding instant v0.1.5
Updating lock_api v0.3.4 -> v0.4.0
Updating parking_lot v0.10.2 -> v0.11.0
Updating parking_lot_core v0.7.2 -> v0.8.0
Updating r2d2 v0.8.8 -> v0.8.9
Updating scheduled-thread-pool v0.2.4 -> v0.2.5
```
r? @jtgeibel

Update `parking_lot` to 0.11

---

Cargo.lock
Cargo.toml
src/middleware.rs

This bumps to the latest release of `cookie` and addresses a deprecation. Upstream `conduit-cookie` has similar changes: https://github.com/conduit-rust/conduit-cookie/compare/v0.9.0-alpha.3...v0.9.0-alpha.4
r? @JohnTitor

Bump to the latest version of cookie crate

---

Cargo.lock
Cargo.toml
src/middleware.rs
src/middleware/ember_html.rs
src/middleware/normalize_path.rs
src/router.rs
src/util/request_proxy.rs

The first commit bumps conduit dependencies to add path rewriting support. Here are the full upstream diffs for the releases:
* https://github.com/conduit-rust/conduit/compare/v0.9.0-alpha.2...v0.9.0-alpha.3
* https://github.com/conduit-rust/conduit-test/compare/v0.9.0-alpha.2...v0.9.0-alpha.3
* https://github.com/conduit-rust/conduit-router/compare/v0.9.0-alpha.2...v0.9.0-alpha.3
* https://github.com/conduit-rust/conduit-middleware/compare/v0.9.0-alpha.2...v0.9.0-alpha.3
* https://github.com/conduit-rust/rust-civet/compare/v0.9.0-alpha.3...v0.9.0-alpha.4
* https://github.com/jtgeibel/conduit-hyper/compare/v0.9.0-alpha.4...v0.9.0-alpha.5
The second commit implements path normalization. This should no longer be needed by cargo since …

Normalize request paths

---

src/middleware/log_request.rs
src/middleware/normalize_path.rs

In the original implementation the logging middleware would log the
final rewritten path. The NormalizePath middleware had custom logic
to log the original path, but the other 2 uses of path_mut() were not
handled consistently. The logging middleware now ensures that the
original request path is always logged.
r? @JohnTitor

Fix logging of original request path

---

src/bin/server.rs

This is changed so that running `cargo run --bin server` locally uses
the same web server that we are running in production. The `civet`
server can be selected by setting the `WEB_USE_CIVET` environment
variable to any value (including an empty string).
r? @JohnTitor 
cc #2204

Switch to hyper as the default web server

---

Cargo.lock
src/render.rs

I've split out the bump to `comrak` in a 2nd commit because of a source level breaking change upstream (in case we need to revert it, or we decide to drop it from this PR for now).
r? @JohnTitor

Run cargo update

---

app/controllers/me/index.js
app/templates/me/index.hbs

me.index: Hide "Email Notifications" until the feature is fully developed

---

Cargo.lock
Cargo.toml

0.7.1 is yanked as it contained a breaking change that we addressed here a while ago.
See: https://github.com/kivikakk/comrak/blob/master/changelog.txt
r? @jtgeibel

Update comrak to 0.8 since 0.7.1 is yanked

---

src/models/team.rs

Use matches macro which is stabilized in 1.42.0. And rename it from `whitelist` to `is_allowed_char` since it's ambiguous to return true when an unexpected character comes in, even though it's "whitelist".
r? @jtgeibel just in case but feel free to r=anyone as it's a quite simple change.

Use `matches!` macro and rename sanitize function

---

docs/CONTRIBUTING.md

This is necessary for uploaded crates to properly display their READMEs.

Document running the background worker.

---

src/controllers.rs
src/controllers/crate_owner_invitation.rs
src/controllers/krate/follow.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/util.rs
src/controllers/version/yank.rs

In https://github.com/rust-lang/rfcs/pull/2947#discussion_r456525127,
@pietroalbini says, with regards to restricting the default
authorization of API tokens:
> this would break everyone using the token to authenticate to endpoints
> not used by Cargo. Even though we're not providing stability guarantees
> for them I'd be wary of blindly breaking them. At least I'd like some
> stats on which endpoints are accessed with the cookie and which are used
> with tokens.
This change attempts to provide those stats via the logs. All
authenticated requests receive a `uid` field in the log output. If the
request was authenticated via an API token, the log output additionally
contains a `tokenid` field.
Because the method I used, log_request::add_custom_metadata, requires a
mutable request, I had to …

Log user id and token id when applicable.

---

src/render.rs

The Rust-specific code block annotations like `no_run` are used in doc testing through `doc-comment` or similar crates, and other services seem to ignore characters after a comma.
This removes characters from the annotations after a comma.
Since this is additional work, this may affect performance a bit, but from the benchmarks, it looks fine.
Also this allows `language-toml` class as it's supposed to be used widely.
Small input:
```
test bench_orig    ... bench:       1,363 ns/iter (+/- 29)
test bench_tweaked ... bench:       1,498 ns/iter (+/- 28)
```
Large input (about 2k COL):
```
test bench_orig    ... bench:     634,254 ns/iter (+/- 10,553)
test bench_tweaked ... bench:     636,279 ns/iter (+/- 13,216)
```
Fixes #1150
r? @jtgeibel

Shrink code block annotation after a comma

---

.buildpacks

It appears that the buildpack we were grabbing from S3 is very stale.
That version pins `heroku/nodejs-v98` which is also old (the current
version is v174).
This is causing deploys to fail and has already been [reported]
upstream. This commit pins to a custom built version based on
jtgeibel/heroku-buildpack-emberjs@34f4175.
I'm trying a staging deploy of this now, and will merge once that succeeds.
r? @ghost
[reported]: https://github.com/heroku/heroku-buildpack-emberjs/issues/61

Bump to the latest emberjs buildpack

---

.env.sample
src/config.rs
src/controllers/util.rs
src/tests/all.rs

This adapts the scheme added in #2627. When operating behind
CloudFront, the Host received by nginx is the Heroku instance and does
not match the user facing crates.io origin. Therefore it is necessary to
obtain a list of allowed origins at boot time.
If this header is not set, the server will panic and will not boot.
r? @JohnTitor 
cc @jsha

Obtain allowed origin list from the environment

---

Cargo.lock
Cargo.toml
src/email.rs

Update lettre to 0.10.0-alpha.1

---

src/boot/categories.toml

This is a tiny nitpick that I noticed while opening #2662: Apple stylizes their operating system without the space, so I figured consistency with their style makes sense.

categories: "mac OS" -> "macOS"

---

src/boot/categories.toml

First of all, thank you to the crates.io team! The service and work you provide is invaluable.
I'm opening this PR to propose a new category slug: `os::linux-apis`. My rationale:
Linux has a large API surface that isn't shared with other
members of the Unix/Unix-like family, so having a separate
category for it allows crate authors to better distinguish
when writing bindings for Linux-specific interfaces.
This is consistent with the availability of `os::macos-apis`,
as macOS is another member of the Unix/Unix-like family with
its own large and discrete API surface.

categories: Add os::linux-apis

---

app/styles/index.module.css

Hello,
This PR aims to fix the alignment issue on the two main button, on mobile and narrow widths.
This issue was due to [a media query](https://github.com/rust-lang/crates.io/blob/master/app/styles/index.module.css#L17) and [a `vertical-align`](https://github.com/rust-lang/crates.io/blob/master/app/styles/shared/buttons.module.css#L43) rule conflict between `570px` and `447px`, highlighted by the second link margin-top.
Note that the `yellow-button` class is extended 9 times in the app, that's why I've preferred a `vertical-align` "reset" on the `hero-button` definition.
Didn't found a better way. Let me know if you think about something else.
BEFORE: 
AFTER:
Fixes #2654

Fix button alignment on mobile / narrow widths

---

src/app.rs

While working locally with the crates.io backend I got stuck for some time. Requests to `/api/v1/crates/new` would hang for 30 seconds and then a 500 error would be returned. The error was from r2d2, which timed out while trying to acquire a database connection from the pool. I finally figured out the default max pool size had been set to 1. Strangely this seems to have been this way for 3 years now, so I don't know if I'm doing something wrong here, but this fixed the issue for me.

Set the default r2d2::Pool::max_size to 3

---

package-lock.json

I think this is the first time I've run `npm install` locally since the switch to Renovate, but I'm not certain where this drift came from.
r? @Turbo87

Save lockfile state after running `npm install`

---

public/_redirects

This should hopefully solve our API access issue for the preview apps.
more details are available at https://docs.netlify.com/routing/redirects/rewrites-proxies/

Netlify: Add `_redirects` file

---

src/bin/server.rs
src/middleware/balance_capacity.rs

The parent of this PR is what is currently deployed so we should be able to merge this and deploy `843a975` (not the merge commit) without deploying untested changes on master.

Log `in_flight_total` when the request count exceeds a threshold

---

app/components/user-avatar.hbs
app/components/user-avatar.js

Fixes #2721
I edited the `UserAvatar` component, so the improvement will be available everywhere where users' avatars would be shown.

Add title with the owner's name in the owner icons

---

script/ember.sh

It shouldn't be necessary to globally install `ember-cli` just so that our wrapper script can run properly. Instead we can refer to the locally installed `node_modules/.bin/ember` executable.
Closes https://github.com/rust-lang/crates.io/pull/2752
r? @locks

script/ember: Use locally installed ember-cli executable

---

app/app.js
app/resolver.js

... to match the current ember-cli blueprint :)
r? @locks

Inline `app/resolver.js` file

---

testem.js

This matches the current default configuration in ember-cli.
r? @locks

Update `testem` configuration

---

app/services/progress.js

Waiting for the progressbar to finish animating was slowing down the tests unnecessarily, so instead of waiting for it to finish animating we won't show it anymore at all.
r? @locks

services/progress: Remove progress bar when running tests

---

fastboot/initializers/ajax.js

This does not appear to be necessary anymore 🤔
r? @locks

Remove obsolete fastboot initializer override

---

package.json

We have templates in the `app/components/` folder now too and those were not linted :-/
r? @locks

Run ember-template-lint on *all* templates

---

README.md

I just tried to follow instructions to join discord channel and noticed that there is no #crates-io channel, but rather #crates-io-team.

Fix discord channel name in README.md

---

config/nginx.conf.erb
src/middleware/balance_capacity.rs
src/middleware/require_user_agent.rs

This should double our burst capacity during large influxes of download
traffic and reduce the occurance of H13 errors due to hitting the worker
connection limit.
With more queued connections we could potentially bump into limits on
the number of open file handles. It looks like Heroku dynos have a
ulimit on open files of:
* 10,000 for Standard-1X dynos
* 1,048,576 for Performance-M dynos
Based on these numbers, we have a margin of 1,808 file handles for
database connections, serving static files, etc. even on a Standard-1X
dyno.

Double nginx worker connections

---

app/models/api-token.js
app/models/category-slug.js
app/models/category.js
app/models/crate-owner-invite.js
app/models/crate.js
app/models/dependency.js
app/models/keyword.js
app/models/owned-crate.js
app/models/team.js
app/models/user.js
app/models/version-download.js
app/models/version.js

These are only needed when API fields should be transformed from one type to another (e.g. from ISO8601 string to `Date`), but for the regular cases they don't need to be used.
r? @locks

models: Remove unnecessary transforms

---

app/templates/crate/version.hbs

There is no `crate_id` on `this.crate`, so this was never quite working as intended. well... actually it was working as intended but not because of the `@query`... 😆 
r? @locks

crate.version: Remove unnecessary `@query` from "Dependent crates" link

---

.eslintrc.js
app/components/pagination.hbs
app/controllers/categories.js
app/controllers/category/index.js
app/controllers/crate/reverse-dependencies.js
app/controllers/crates.js
app/controllers/keyword/index.js
app/controllers/keywords.js
app/controllers/me/crates.js
app/controllers/me/following.js
app/controllers/search.js
app/controllers/team.js
app/controllers/user.js
app/mixins/pagination.js
app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/crate/reverse-dependencies.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/keywords.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs
app/utils/pagination.js

... and then finally enable the `no-mixin` ESLint rule
r? @locks

Replace `pagination` mixin with computed property macro

---

app/templates/crate/version.hbs
tests/acceptance/crate-test.js

Temporarily remove the yank button from the crate page until we find better placement for the button. The buttons added to the all versions page in #2623 remain.
I would like to merge this as a temporary fix to unblock deploying to production. I've opened #2794 to track adding this back.
r? @locks
cc @thiagoarrais

Temporarily remove yank button from crate header

---

.buildpacks

Since #2657 we build the frontend twice during a deploy. It seems that
the nodejs buildpack (pulled in by the emberjs buildpack) is running
our build script so lets just depend on that directly because it is
actively supported by Heroku.
r? @JohnTitor

Use nodejs buildpack directly (instead of via the emberjs buildpack)

---

app/components/api-token-row.js
app/components/email-input.js
app/components/owned-crate-row.js
app/components/pending-owner-invite-row.js

This PR ports the remaining files using `Component.extend({...})` to use `class ... extends Component { ... }` instead.
r? @locks

Convert remaining components to ES6 classes

---

.eslintrc.js
.template-lintrc.js
fastboot.js

Instead we'll use the `overrides` feature of ESLint
r? @locks

Remove unnecessary `eslint-env` declarations

---

tests/helpers/setup-mirage.js

This ensures that internal timers in the Ember runloop keep ticking correctly instead of being frozen too.
r? @locks

tests/helpers: Use time travel instead of time freezing

---

.github/workflows/ci.yml
.travis.yml

We'll want to synchronize this bump with a bump to the `heroku-18` stack in production. See the tracking issue for details.
closes: #1868

Bump CI stack from xenial to bionic

---

app/routes/team.js
app/routes/user.js

These error handlers should just rethrow the original error if no `errors` propery exists.
r? @locks

Fix error handling for errors without an `errors` property

---

app/components/api-token-row.hbs
app/components/api-token-row.js
app/components/api-token-row.module.css
tests/acceptance/api-token-test.js

This changes API token creation or revocation errors to use the regular notification system instead of displaying in a custom way.
r? @locks

ApiTokenRow: Replace custom error display with notification

---

app/routes/github-authorize.js
app/routes/login.js
tests/acceptance/login-test.js
tests/bugs/2329-test.js
tests/routes/github-authorize-test.js

I got nerd-sniped by the following comment in the codebase:
> For the life of me I cannot figure out how to do this other than polling
This PR simplifies the implementation and now uses the recommended way to communicate between parent and child window: `window.postMessage()`
see https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage for more information
r? @jtgeibel

Refactor login code to use `postMessage()` instead of polling loop

---

app/components/api-token-row.hbs
app/components/api-token-row.js

Instead of having `@token.isNew` checks everywhere we now only have a single top-level check, which then allows us to use a proper `<form>` element for the token name input field. Eventually this should probably be extracted to a dedicated component.
r? @locks

ApiTokenRow: Simplify template and wrap with `<form>` element

---

tests/unit/helpers/format-num-test.js

- added more tests for format-num
- currently format-num test does not cover larger values and decimal values. 
- Some countries, such as India use this format `12,34,567`. However, we want to use the format like `1,234,567`. 
- That's why I added a larger value test.

test: add more tests for format-num

---

app/helpers/format-num.js
tests/unit/helpers/format-num-test.js

see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_identification_and_negotiation 😉 
r? @locks

helpers/format-num: Format numbers in the user's preferred locale

---

app/routes/confirm.js
app/templates/confirm.hbs
tests/acceptance/email-confirmation-test.js

The `confirm` route previously only contained a single sentence and the layout looked a little broken. This PR changes the route to redirect back to the frontpage and show a success notification using our regular notification system.
r? @locks

Use notification service for the email notification success message

---

README.md

We use the bors bot to merge our code so the chance that this badge will ever not be green is veeery small and it doesn't give a lot of value to the readers so we should probably just get rid of it ;)
r? @jtgeibel

README: Remove TravisCI badge

---

app/app.js
app/sentry.js
config/environment.js
config/nginx.conf.erb
package-lock.json
package.json

Up until now we've essentially been running blind. This PR adds error tracking via sentry.io to our frontend code.

Add Sentry error tracking for the frontend

---

ember-cli-build.js

This is needed to take advantage of proper stacktraces in Sentry
r? @jtgeibel

Enable JS sourcemap output

---

app/sentry.js

According to https://github.com/emberjs/ember.js/issues/18416 it looks like changing query params that have `refreshModel: true` causes an internal `TransitionAborted` error. This error is being ignored by Ember itself (see https://github.com/emberjs/ember.js/blob/v3.21.3/packages/@ember/-internals/runtime/lib/ext/rsvp.js#L40-L42), but Sentry also hooks into `RSVP.on('error')` and unfortunately reports these false positives (see https://github.com/emberjs/ember.js/issues/12505)
This PR actively ignores `TransitionAborted` errors in the `beforeSend()` hook of Sentry.
r? @jtgeibel

sentry: Ignore `TransitionAborted` errors

---

app/utils/ajax.js

This should make Sentry issues like https://sentry.io/organizations/rust-lang/issues/1935012204/ a little more useful
r? @jtgeibel

utils/ajax: Throw an `Error` instance instead of a random object

---

app/services/google-charts.js

Up until now the function would have rejected with an `Event` instance, which shows up in a non-useful way on Sentry. https://developer.mozilla.org/de/docs/Web/API/HTMLScriptElement suggests to use `event.target.src` instead to convert the event to an `Error` instance.
r? @jtgeibel

services/google-charts: Ensure that `loadScript()` rejects with an `Error` instance

---

Cargo.toml

Having the dependencies arbitrarily grouped makes it hard to know where to put new dependencies. This PR sorts them alphabetically, which should resolve the problem.
r? @jtgeibel

Cargo.toml: Sort dependencies alphabetically

---

app/components/download-graph.hbs
app/components/download-graph.js
app/routes/application.js
app/services/google-charts.js

According to Sentry we have quite a few users that have trouble loading the Google Charts code. This PR improves the error handling in two ways:
1. The preloading code in the `application` route is simply ignoring any errors, since it's irrelevant for the preloading and the errors would trigger again when loaded through the `DownloadGraph` component
2. The `DownloadGraph` component is adjusted to show an error message if the loading of the Google Charts API failed, and it will no longer rethrow `ExternalScriptError` errors, which means they won't show up on Sentry anymore.
This should fix https://sentry.io/organizations/rust-lang/issues/1935278146/
r? @jtgeibel

Improve Google Charts error handling

---

app/services/google-charts.js
config/nginx.conf.erb

The old URL is a permanent redirect to the new URL, maching what is
shown in the [docs].
r? @Turbo87 
[docs]: https://developers.google.com/chart/interactive/docs/quick_start

Load charts directly, without a redirect

---

app/helpers/format-num.js

This should resolve https://sentry.io/organizations/rust-lang/issues/1936687439/
r? @jtgeibel

helpers/format-num: Fall back to `en` locale if `navigator.language` causes an error

---

app/components/email-input.hbs
app/components/email-input.js
app/templates/me/index.hbs
mirage/factories/user.js
mirage/route-handlers/users.js
tests/acceptance/email-change-test.js
tests/mirage/users-test.js

This PR also includes a small bugfix that resets the `email` property of the user back to its original value in case the request fails.
r? @locks

Add "Email Change" acceptance tests

---

app/utils/ajax.js

This should fix https://sentry.io/organizations/rust-lang/issues/1941994215/
r? @jtgeibel

utils/ajax: Allow `init` argument of `HttpError` to be `undefined`

---

app/routes/crate/version.js

`latestStableVersion` is already guaranteed to be `null` because of the previous condition. I assume the original intention here was to check for `latestUnyankedVersion` instead.
It looks like this bug was already present in the original implementation in https://github.com/rust-lang/crates.io/pull/1857
r? @jtgeibel

crate.version: Fix `latestUnyankedVersion` bug

---

ember-cli-build.js
vendor/qunit.css

This makes the testing container have the same background color as the regular app, which makes interactive testing a little more pleasant because the top menu is actually visible on the screen 😅 
r? @pichfl

QUnit: Override testing container background color

---

app/components/email-input.hbs
app/components/email-input.js
app/templates/me/index.hbs
tests/acceptance/email-change-test.js

The primary user-facing change in this PR is replacing the custom error display with usage of our regular `notifications` service. Other than that the input should work and look essentially the same as before, but is now based on a Glimmer component.
This PR converts our last remaining Ember component to Glimmer! 🎉 
r? @locks

Simplify and modernize the `EmailInput` component

---

src/boot/categories.toml

Added category for FreeBSD APIs: `os::freebsd-apis`

Add os::freebsd-apis category

---

.github/workflows/ci.yml
.travis.yml

GitHub now warns about the use of `set-env` and `add-path`: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This replaces them with new commands and just run `npx percy` directly instead of using percy's action since they haven't updated it (https://github.com/percy/exec-action/pull/18).
Also, I noticed the current config uploads snapshots even if it comes from a forked repo during debugging. 45866ff prevents it.
r? @jtgeibel

Remove use of deprecated `set-env` and `add-path`

---

.eslintrc.js
app/controllers/crate/owners.js
app/controllers/crate/version.js
app/controllers/crate/versions.js
app/controllers/dashboard.js
app/controllers/index.js
app/controllers/me/index.js
app/controllers/search.js
app/models/team.js
app/models/version.js
app/routes/me/crates.js

These should not be necessary anymore AFAICT
Resolves https://github.com/rust-lang/crates.io/issues/1795
r? @locks

Remove unnecessary `this.get()` calls

---

ember-cli-build.js

This should be included as the very first part of our CSS code so that the following code can override it if necessary
r? @locks

styles: Prepend `normalize.css` code

---

app/controllers/crate/owners.js
app/templates/crate/owners.hbs
tests/acceptance/crate-test.js

Instead of displaying the operation result somewhere in the page, this changes the code to use our regular notification system.
r? @locks

crate.owners: Use `notifications` service in tasks

---

app/app.js

The `@sentry/browser` packages rely on `window.location`, which is not available in Node.js
r? @locks

Sentry: Disable when using `FastBoot`

---

app/styles/application.module.css

This causes our footer to always appear at the bottom of the page, irregardless of how long the content is:
r? @locks

styles/application: Set minimum height for the `body` element

---

Cargo.lock
Cargo.toml
src/bin/backfill-org-ids.rs

~~_This builds upon https://github.com/rust-lang/crates.io/pull/2725. I've created multiple PRs for us to focus review on specific issues. Feel free to close the [previous one](https://github.com/rust-lang/crates.io/pull/2725) if you folks prefer to review this as one big PR instead._~~
I've added a small program for backfilling the current database with the organization IDs for the existing teams.
It goes over all the teams in the database that don't have an org id (assuming that #2725 has been online for some time) and tries to query the [`/teams/:team_id`][team_legacy_ep] endpoint. Failing that, it parses the org name from the `login` field and queries [`/orgs/:org_name`][org_ep]. For the first part, I took advantage of the fact that I described in …

Backfill GitHub organization IDs for teams

---

tests/acceptance/categories-test.js
tests/acceptance/crate-test.js
tests/acceptance/crates-test.js
tests/acceptance/front-page-test.js
tests/acceptance/keyword-test.js
tests/acceptance/owners-test.js
tests/acceptance/search-test.js
tests/acceptance/team-page-test.js
tests/acceptance/user-page-test.js

This PR is best reviewed commit by commit 😉 
tl;dr it cleans up our frontend test code a little bit by splitting a file, fixing problematic `visit()` calls and merging redundant/duplicate tests into single tests.
r? @locks

Frontend tests cleanup

---

.env.sample
Cargo.lock
Cargo.toml
src/bin/server.rs
src/middleware/log_request.rs

This PR implements initial Sentry integration for our backend API via https://github.com/getsentry/sentry-rust.
It will automatically report panics to Sentry, as well as internal server errors (unfortunately without stacktrace for now) and slow requests, similar to our current `println!()` logging.

Report errors and slow requests on the backend to Sentry

---

app/services/session.js

This will make it easier to associate backend errors with frontend errors on Sentry.

services/session: Add user ids to Sentry context

---

app/routes/crate/version.js

It looks like fixing the bug in #2894 exposed this bug. When there are
only pre-release versions of a crate, the version number needs to be
extracted so that the version object can be located again a few lines
later. This could probably be refactored, but for now this removes the
spurious error notification shown in the UI.
r? @Turbo87

Fix version logic when there are only pre-releases

---

app/controllers/crate/version.js
app/models/version-download.js

This gets rid of a few instances of unnecessary `Date` parsing. In most cases we can just use the ISO8601 string directly, without having to convert to `Date` and back to a string all the time.
r? @locks

Cleanup crate version downloads processing code

---

package.json
yarn.lock

We don't use SASS anymore...
Closes #2981
r? @locks

Remove obsolete `sass` dependency

---

config/targets.js

It looks like https://github.com/browserslist/browserslist currently does not support something like `last 2 Firefox ESR versions`, because `ESR` is essentially treated as an alias for a specific version.
Instead, this PR proposes to add the `last 1 years` specifier which covers all of the browsers listed below:
```
❯ browserslist "last 1 years"
and_chr 85
and_ff 79
and_qq 10.4
android 81
chrome 86
chrome 85
chrome 84
chrome 83
chrome 81
chrome 80
chrome 79
edge 86
edge 85
edge 84
edge 83
edge 81
edge 80
edge 79
firefox 82
firefox 81
firefox 80
firefox 79
firefox 78
firefox 77
firefox 76
firefox 75
firefox 74
firefox 73
firefox 72
firefox 71
ios_saf 14
ios_saf 13.4-13.7
ios_saf 13.3
op_mob 59
opera 71
opera 70
opera 69
opera 68
opera 67
opera 66
opera 65
safari 14
safari 13.1
samsung 12.0 …
```

config/targets: Support all browser versions released within the past year

---

Cargo.lock
Cargo.toml
src/config.rs
src/email.rs
src/lib.rs
src/models/krate.rs
src/models/token.rs
src/tests/all.rs
src/tests/builders/publish.rs
src/tests/category.rs
src/tests/krate.rs
src/tests/record.rs
src/tests/token.rs
src/tests/user.rs
src/tests/util.rs
src/tests/version.rs
src/views.rs
src/views/krate_publish.rs

This PR introduces https://github.com/svartalf/rust-claim/ for our tests to replace our custom `t!()` macro and simplify/improve a few other `assert!()` usages.
`t!()` is certainly shorter than `assert_ok!()`, but I think the latter expresses the intent way better than the former. With `t!()` is was always thinking that this might have something to do with translations... 😅 
r? @jtgeibel

Use `claim` to simplify assertions

---

Cargo.toml
build.rs
src/bin/server.rs
src/middleware/log_request.rs

This PR introduces multiple improvements to our backend Sentry integration:
* The `X-Forwarded-For` header is stripped before sending an event, as that contains PII.
* Slow requests are not sent to Sentry anymore, as those alerts are not really actionable.
* The current git commit is included in every event sent to Sentry, to be able to identify releases.
r? @Turbo87

Improve backend integration with Sentry

---

Cargo.lock
Cargo.toml
src/bin/delete-crate.rs
src/bin/delete-version.rs
src/bin/populate.rs
src/bin/render-readmes.rs
src/bin/test-pagerduty.rs
src/bin/transfer-crates.rs
src/bin/verify-token.rs

This should make it easier to convert these binaries to clap subcommands in a follow-up PR. It also simplifies our argument parsing code and generates help messages and proper errors if the passed arguments don't match our expectations.
r? @jtgeibel

Use `clap` for CLI argument parsing

---

app/components/crate-row.hbs
app/components/front-page-list/item.hbs
app/templates/index.hbs
package.json
yarn.lock

Using `LinkTo` can be "bad" for performance when used in loops since it still uses `Ember.Component` underneath. This PR switches two components to use https://github.com/buschtoens/ember-link instead, which should slightly improve the rendering times. It also significantly simplifies the API of the `FrontPageList::Item` component.

Use `ember-link` for links in lists

---

app/routes/crate/reverse-dependencies.js
app/templates/crate/reverse-dependencies.hbs
tests/acceptance/reverse-dependencies-test.js

Instead of showing an empty error page, this PR adjusts the code to show an error message popup through our regular `notifications` service system:
Related to https://github.com/rust-lang/crates.io/issues/187
r? @locks

crate.reverse-dependencies: Show error notification if data loading fails

---

Cargo.lock
Cargo.toml
src/bin/delete-crate.rs
src/bin/delete-version.rs
src/bin/dialoguer/mod.rs
src/bin/transfer-crates.rs

This simplifies our command line confirmation code in the admin tools by using https://docs.rs/dialoguer.
r? @jtgeibel

Use `dialoguer` crate for command line confirmations

---

Cargo.lock
Cargo.toml

see https://github.com/getsentry/sentry-rust/blob/0.21.0/CHANGELOG.md#0210

Update `sentry` to v0.21.0

---

Cargo.lock
src/bin/server.rs

r? @Turbo87 
```
Updating addr2line v0.13.0 -> v0.14.0
Updating aes v0.4.0 -> v0.6.0
Updating aes-gcm v0.6.0 -> v0.8.0
Updating aes-soft v0.4.0 -> v0.6.3
Updating aesni v0.7.0 -> v0.10.0
Updating aho-corasick v0.7.14 -> v0.7.15
Updating anyhow v1.0.33 -> v1.0.34
Removing arc-swap v0.4.7
Removing arrayvec v0.5.1
Updating async-compression v0.3.5 -> v0.3.6
Updating backtrace v0.3.53 -> v0.3.54
Updating base-x v0.2.6 -> v0.2.8
Adding bitvec v0.19.4
Removing block-cipher v0.7.1
Updating cc v1.0.61 -> v1.0.62
Adding cipher v0.2.5
Updating conduit-router v0.9.0-alpha.3 -> v0.9.0-alpha.4
Updating const_fn v0.4.2 -> v0.4.3
Updating cookie v0.14.2 -> v0.14.3
Updating core-foundation v0.7.0 -> v0.9.1
Updating core-foundation-sys v0.7.0 -> v0.8.2
Updating crc32fast v1.2.0 -> v1.2.1
Removing …
```

`cargo update`

---

Cargo.lock
Cargo.toml
src/models/dependency.rs
src/tests/all.rs
src/tests/builders/dependency.rs

The new release of semver treats `>= 0` the same as the `*` wildcard.
It makes sense that these are equivalent, but this did break 3 tests
and will technically reject syntax in `Cargo.toml` that was previously
accepted.
r? @ghost

Update to the latest semver

---

.template-lintrc.js

see https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/config/a11y.js
r? @locks

template-lint: Enable `a11y` preset

---

app/controllers/search.js

We are currently using the `drop` modifier for the data task, which means that subsequent requests are ignored while the first request is in flight.
Changing the modifier to `restartable` will take the data task drop all but the latest request. This should help with showing the correct search results when paginating and using the browser's back button.
Partially addresses https://github.com/rust-lang/crates.io/issues/3041.

Keep only latest search API request

---

src/boot/categories.toml

I've added the `accessibility` category to cover crates that implement features for the convenience of disabled people.
I wanted to start a project that translates given colour codes to colours colorblind people can distinguish more easily, but I haven't found a category to fit it. What else belongs in this category could be crates that interoperate with peoples screenreaders, new screenreader implementations or other assistive technology.

Added Accessibility category

---

app/templates/categories.hbs
app/templates/category/index.hbs
app/templates/keywords.hbs
mirage/serializers/category.js
mirage/serializers/keyword.js
tests/acceptance/categories-test.js

Passing the formatted number into the `pluralize` helper doesn't work quite as expected, and in these cases we already know the pluralization, so using the `pluralize` helper is somewhat pointless anyway.
Resolves https://github.com/rust-lang/crates.io/issues/3042
r? @jtgeibel

Fix broken pluralizations

---

src/tests/util.rs

We have enough tests that explicitly assert the crate name already. Removing this code path allows us to slightly simplify the test code a little more.
r? @jtgeibel

tests/util: Remove crate name check from `enqueue_publish()`

---

Cargo.lock
Cargo.toml

https://github.com/est31/cargo-udeps indicated that this dependency might be unused, and indeed I couldn't find any references to it anywhere in our code.
r? @jtgeibel

Remove unused `parse_link_header` dependency

---

src/tests/util.rs

This struct does not appear to be used anywhere (anymore).
r? @JohnTitor

tests/util: Remove unused `BackgroundJob` struct

---

src/controllers/user/other.rs
src/models/owner.rs
src/tests/owners.rs
src/tests/user.rs
src/tests/util.rs

Make owner invites case-insensitive

---

.eslintrc.js
app/adapters/category-slug.js
app/components/follow-button.js
app/controllers/crate/version.js
app/controllers/search.js
app/models/dependency.js
app/models/version-download.js
mirage/models/api-token.js
mirage/models/crate-ownership.js
mirage/models/crate.js
mirage/models/dependency.js
mirage/models/mirage-session.js
mirage/models/user.js
mirage/models/version-download.js
mirage/models/version.js
mirage/route-handlers/categories.js
mirage/route-handlers/keywords.js
tests/acceptance/404-test.js
tests/acceptance/api-token-test.js
tests/acceptance/crate-following-test.js
tests/acceptance/crate-test.js
tests/acceptance/front-page-test.js
tests/acceptance/invites-test.js
tests/acceptance/login-test.js
tests/acceptance/logout-test.js
tests/acceptance/search-test.js
tests/bugs/2329-test.js
tests/helpers/visit-ignoring-abort.js

With https://github.com/Tibfib/eslint-plugin-import-helpers and prettier, this rule makes it even easier to import things and have the tooling take care of formatting things in a readable way.
r? @locks

ESLint: Enable `sort-imports` rule

---

app/components/footer.hbs
app/components/footer.module.css
app/styles/application.module.css
app/templates/application.hbs

This moves the "Fork me on GitHub" link from a prominent corner ribbon to a footer link, and rewords it to "Fork crates.io on GitHub", removing the ambiguous "me". This is meant to address the confusion between accessing the source of a crate, and accessing the source of crates.io itself.
Without this change the source link for crates.io is much more prominent than the source link for the crate itself. Personally I've been bitten by this many times: I click on the ribbon intending to see the source for a crate. See #596 for some prior discussion. 
To prevent the footer from becoming too crowded and wrapping, I removed the "Install" link, with the idea that "Getting Started" is sufficient. If you click "Getting Started" you quickly land on "Install" instructions.
The corner ribbon is gone. …

Migrate "Fork me" from ribbon to footer

---

app/components/header.module.css

The current focus outline is using a rectangle, while the input is rounded, which looks very ugly. This commit uses a `box-shadow` instead of the regular `outline` to solve this issue.
Before:
After:
r? @locks

Header: Use custom focus styling

---

src/util/errors.rs

If you look at target/doc/cargo_registry/util/index.html, you will see this heading after *errors*:
> This module implements several error types and traits. The suggested usage in returned results is as follows: 
The first line is taken as a heading, so should remain separate, so that it's readable as a summary.

separate doc heading from body

---

src/controllers/krate/publish.rs
src/models/dependency.rs
src/tests/krate/publish.rs
src/tests/util.rs

Using the `json!()` macro makes it quite straight forward to assert against the exact response payload expectation and is ultimately less verbose than checking against `json.errors[0].detail` like we currently do.
r? @jtgeibel

tests/krate/publish: Use `assert_eq!()` to check response payload content

---

yarn.lock

The latest fastboot release removes some extraneous files that were
inflating our slug size. This is the minimal command I found that
bumped the version:
`yarn upgrade fastboot fastboot-app-server`
r? @Turbo87

Upgrade dependency to reduce slug size

---

src/tests/krate/publish.rs

The test was receiving "too large when decompressed" because of a broken header checksum, which was mistakenly converted into this error message, because we assume that every `entries()` error is coming from our `LimitErrorReader`.  This commit moves the checksum calculation to the right place, which causes the test to now test the correct condition in our `verify_tarball()` function.

tests/krate/publish: Fix `new_krate_tarball_with_hard_links()`

---

src/admin/test_pagerduty.rs
src/tests/krate/publish.rs

Use `std`'s items instead of `failure`'s

---

Cargo.lock
Cargo.toml

Changes between 0.8.2 and 0.9.0: https://github.com/kivikakk/comrak/compare/0.8.2...0.9.0
This shouldn't affect our codebase.

Update `comrak` to 0.9

---

src/models/version.rs

While this can be tested through API tests it's much more convenient to have a unit tests for this functionality.
This PR is in preparation for fixing https://github.com/rust-lang/crates.io/issues/2710, by introducing a `max_stable_version` property on the `crate` resource.
r? @jtgeibel

models/version: Add tests for `Version::top()` function

---

src/tests/account_lock.rs
src/tests/all.rs
src/tests/krate/dependencies.rs
src/tests/krate/publish.rs
src/tests/krate/search.rs
src/tests/krate/yanking.rs
src/tests/owners.rs
src/tests/team.rs
src/tests/token.rs
src/tests/user.rs
src/tests/util.rs
src/util/errors.rs
src/util/errors/json.rs

This PR continues #3066 and converts the remaining tests to use the same pattern of using `assert_eq!()` and the `json!()` macro to assert on the exact structure and content of the error responses.
r? @jtgeibel

tests: Use `assert_eq!()` to check error response payload content

---

src/controllers/category.rs
src/controllers/helpers/pagination.rs
src/controllers/keyword.rs
src/controllers/krate/metadata.rs
src/controllers/krate/search.rs
src/controllers/user/me.rs
src/models/krate.rs

For now just add log metadata so this is easily searchable. Eventually
we can suppress the metadata if the user is logged in, or even require
an authenticated user for very large offsets.
r? @Turbo87

Log when a bot is suspected due to large page offset

---

app/controllers/crate/owners.js
app/models/crate.js
mirage/route-handlers/crates.js
tests/acceptance/owners-test.js
tests/models/crate-test.js

On the frontend we were not considering that the backend always returns 200 HTTP status codes, even for errors. This PR fixes our frontend code to only consider `{ ok: true }` responses as successful requests and shows an error message otherwise.
This PR also adds two tests to the frontend test suite to avoid regressions on this.
Resolves #2976 

Fix owner removal error handling

---

app/routes/crate/version.js
app/templates/crate/version.hbs
app/utils/ajax.js
tests/routes/crate/version/docs-link-test.js
tests/utils/ajax-test.js

The primary goal of this PR is to correctly handle errors when requesting the `builds.json` files from docs.rs.
We first add tests for our `ajax()` utility function, then refactor it to always reject with `AjaxError` instances. We then use this specific error class on the error handler to only send errors to Sentry that are **not** `AjaxError`.
Since the result from docs.rs is not mission-critical we can simply ignore a missing response and treat it as if the result was `[]`. This part was already implemented in the `documentationLink` computed property.
This should hopefully reduce the number of issues like https://sentry.io/organizations/rust-lang/issues/1946426065/ and will fix another `ember-concurrency/no-perform-without-catch` ESLint issue.
r? @locks

Handle docs.rs request errors

---

.env.sample
docker-compose.yml
docs/CONTRIBUTING.md
frontend.Dockerfile
src/bin/server.rs

Fixes dockerized environment to run crates.io locally.

dev: update docker node version, server address, and docker-compose

---

Cargo.toml
docker_entrypoint.sh
docs/CONTRIBUTING.md

This allows us to use just `cargo run` instead of `cargo run --bin server`

Cargo.toml: Specify `server` as `default-run` field

---

app/app.js
app/index.html
config/nginx.conf.erb

This should resolve https://github.com/rust-lang/crates.io/issues/2984, by adding a short error message when something fails to load before the Ember app has booted up:
This does use an inline script though, so we might have to adjust the CSP for this 😞 
r? @jtgeibel

Show error message when JS code fails to load

---

src/tests/all.rs
src/tests/record.rs
src/tests/util.rs

This allows us to use e.g. `debug!()` in test utilities and run `cargo test` with `RUST_LOG=debug`.
This PR also adds `debug!()` calls to our HTTP proxy replay code, to make it easier to see what requests have been intercepted by the proxy.

tests: Initialize env_logger in `TestApp::init()`

---

src/controllers/category.rs
src/controllers/krate/metadata.rs
src/models/badge.rs
src/models/category.rs
src/models/krate.rs
src/views.rs

Our JSON `views` and the database `models` are currently tightly coupled through the `encodable()` methods on almost all models. 
Instead of having the database models depend on the JSON views it would be better to reverse this relationship, so that the database models can live on their own, and only the JSON views are depending on the database models. This would eventually allow us to extract the database models and schema into a dedicated crate, which would then allow us to cut down the dependency tree of some second-level binaries like `monitor` and `background-worker`
This PR starts the process of moving away from `encodable()` by implementing the `From` trait for two of our JSON views. This allows us to call `.into()` on the models to automatically convert it to the JSON view form. …

Convert `encodable()` methods to `From` implementations

---

Cargo.lock
Cargo.toml
src/bin/server.rs
src/lib.rs
src/tests/all.rs
src/tests/util.rs

This brings us closer to being able to use structured logging and properly instrumenting some of functions. The change is mostly a drop-in replacement as described by https://docs.rs/tracing/0.1.22/tracing/#for-log-users.
The only difference is the slightly changed log output format:
```
[2020-12-23T21:51:50Z INFO  cargo_registry::app] test23
Dec 23 22:53:48.847  INFO cargo_registry::app: test23
```
This could be massaged by using a custom `FormatEvent` implementation though, if we really need this to be formatted in a specific way. Otherwise there is also a JSON-based output format which might be beneficial in production for real structured logging.

Replace `log` and `env_logger` with `tracing` crates

---

src/controllers/keyword.rs
src/controllers/krate/downloads.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/team.rs
src/controllers/token.rs
src/controllers/user/other.rs
src/controllers/version/downloads.rs
src/models/download.rs
src/models/keyword.rs
src/models/owner.rs
src/models/team.rs
src/models/token.rs
src/models/user.rs
src/models/version.rs
src/views.rs

This PR continues #3124 by replacing more of our `encodable()` methods with `From` trait implementations to ultimately decouple our database models from the JSON views.

Replace more `encodable()` methods with `From` implementations

---

src/models/dependency.rs

Without these declarations it is quite hard to use these model structs outside of their files, and since the structs themselves are `pub` it makes sense for their fields to also be public.

models: Add missing `pub` declarations

---

app/routes/application.js
ember-cli-build.js
package.json
yarn.lock

It turns out a few Chinese browsers don't ship with an `Intl` API, and that causes several issues on Sentry.
This PR adds optional polyfills for the `Intl` APIs that are loaded if necessary before the app boots.

Load `Intl` polyfills, if needed

---

app/utils/ajax.js
tests/utils/ajax-test.js

This PR improves the `ajax()` function in two ways:
- it adds the nested `cause` to the `message` in debug mode (production is handled by Sentry automatically)
- it adds a `json()` method for easy access to the error response payload if one exists
The second part will be used in an upcoming feature, and the first part turned out useful during the development of that feature.
r? @pichfl

Improve `ajax()` utility function

---

config/environment.js

Having the notifications on the screen for only 3 sec by default is far too fast for most cases. Having it on the screen for too long is far better than the opposite. :)
r? @pichfl

notifications: Increase `clearDuration` to 10 sec

---

src/github.rs

https://crates.io/login is no longer valid (found in https://github.com/rust-lang/cargo/pull/9000#discussion_r547384911) and it's just enough to recommend re-authentication now, I think.

Remove outdated information about GitHub permission error

---

src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/keyword.rs
src/controllers/krate/follow.rs
src/controllers/krate/owners.rs
src/controllers/team.rs
src/controllers/version.rs
src/controllers/version/deprecated.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs

Convert more endpoints to the read-only follower database

---

Cargo.lock
Cargo.toml
src/middleware/log_request.rs

The request start time is now captured by a `conduit` based server. This
ensures that the logged elapsed time is accurate, even if the request
queues waiting for a background thread to run on.
Relevent upstream changes:
* https://github.com/conduit-rust/conduit/compare/v0.9.0-alpha.3...v0.9.0-alpha.5
* https://github.com/conduit-rust/rust-civet/compare/v0.12.0-alpha.4...v0.12.0-alpha.5
* https://github.com/jtgeibel/conduit-hyper/compare/v0.3.0-alpha.5...v0.3.0-alpha.5.1
Unrelated upstream changes (minor API cleanup):
* https://github.com/conduit-rust/conduit-test/compare/v0.9.0-alpha.3...v0.9.0-alpha.4
* https://github.com/conduit-rust/conduit-middleware/compare/v0.9.0-alpha.3...v0.9.0-alpha.4
r? @Turbo87
cc @pietroalbini

Use new conduit API when computing elapsed time

---

app/services/progress.js

The `updateTask` uses the `.drop()` modifier, which means it cancels automatically if there is already a running instance. This cancellation causes a `TaskCancelation` error rejection on the `perform()` call, and we should ignore that kind of error instead of reporting it to Sentry.
Resolves #3157 
r? @pichfl

services/progress: Add missing `didCancel()` check

---

app/helpers/format-num.js
app/routes/application.js
app/services/intl.js
package.json
tests/acceptance/categories-test.js
tests/unit/helpers/format-num-test.js
yarn.lock

This PR should hopefully fix #3158.
I've not been able to reproduce the issue locally, but it looks like it's related to `Intl.NumberFormat` and the polyfill that #3145 introduced. Since we only need this code for number formatting, and we usually want to format in the user's browser locale we can instead use `.toLocaleString()`.
I've extracted an `intl` service for this, which makes it easier to test the `format-num` helper, and brings the implementation closer to the ember-intl addon.
r? @pichfl

Replace `Intl.NumberFormat` usage

---

src/models/krate.rs
src/models/version.rs
src/tests/krate/search.rs
src/views.rs

This PR resolves the API part of https://github.com/rust-lang/crates.io/issues/654 by adding a `max_stable_version` field for the `krate` resource. Since naming is hard, it is called `highest_stable` internally on the `TopVersions` struct. Contrary to `newest_version` and `max_version` this field will be `null` (not `"0.0.0"`) if all available versions have been yanked.
r? @jtgeibel

EncodableCrate: Add `max_stable_version` field

---

src/controllers/krate/metadata.rs
src/controllers/version/metadata.rs
src/models/dependency.rs
src/views.rs

This PR continues #3124 by implementing `from_dep()` and `from_reverse_dep()` methods for the `EncodableDependency` struct and removing the `encodable()` methods on `Dependency` and `ReverseDependency`. We can't use the `From` trait in these cases because the `crate_name` has to be explicitly provided. What we could do instead is implement `From<(Dependency, String)>`, but that doesn't feel right to me.

models::Dependency: Replace `encodable()` method

---

app/components/download-graph.hbs
app/components/download-graph.js
app/components/download-graph.module.css

Without this the graph looks very pressed together on mobile devices
r? @pichfl

DownloadGraph: Set `maintainAspectRatio: false` and use `min-height` instead

---

src/controllers/crate_owner_invitation.rs
src/models/crate_owner_invitation.rs
src/views.rs

This PR is similar to #3134 and brings us one step closer to removing the `models -> views` dependency by inverting the relationship for the `CrateOwnerInvitation` model and `EncodableCrateOwnerInvitation` view.

CrateOwnerInvitation: Replace `encodable()` method

---

src/controllers/user/me.rs
src/models/user.rs
src/views.rs

This PR is similar to #3168 and brings us one step closer to removing the `models -> views` dependency by inverting the relationship for the `User` model and `EncodablePrivateUser` view.

User: Replace `encodable_private()` method

---

app/models/crate.js
app/routes/crate/version.js
mirage/serializers/crate.js
tests/acceptance/crate-test.js
tests/routes/crate/version/model-test.js

This PR adds a `defaultVersion` property on the `crate` model and uses it in the `crate.version` (and `crate.index`) route to determine which version to display by default. This lets us get rid of the `semver` dependency in that route and puts the backend in charge of telling us what to display by default. This will allow us to address https://github.com/rust-lang/crates.io/issues/654 in the near future, since the new `defaultVersion` property can be used in the search results too.
This is probably best reviewed commit-by-commit :)
r? @pichfl

Simplify `crate.version` route implementation

---

tests/acceptance/front-page-test.js

When running the testsuite locally, this test was failing due to my browser using the German locale for formatting instead. This PR forces the `intl` service in the test to explicitly use the `en` locale for formatting instead.
r? @pichfl

tests/front-page: Override locale to make download count test pass

---

Cargo.lock
Cargo.toml
src/bin/server.rs
src/s3/Cargo.toml
src/tests/record.rs

To avoid pulling in 2 versions of `tokio` at once:
r? @ghost

Bump to `tokio 1.0` and `hyper 0.14`

---

src/controllers/krate/metadata.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/user/me.rs
src/controllers/version/deprecated.rs
src/controllers/version/metadata.rs
src/models/krate.rs
src/models/version.rs
src/views.rs

This PR is similar to #3168 and brings us one step closer to removing the `models -> views` dependency by inverting the relationship for the `Version` model and `EncodableVersion` view.

Version|Crate: Replace `encodable()` methods

---

app/components/crate-row.hbs
tests/components/crate-row-test.js

This PR resolves https://github.com/rust-lang/crates.io/issues/654 by using the new `defaultVersion` property of the `crate` model in the `CrateRow` component which is used by the search page.
Closes #2751
r? @pichfl

CrateRow: Use `defaultVersion` for crate version display

---

src/tests/account_lock.rs
src/tests/krate/dependencies.rs
src/tests/krate/downloads.rs
src/tests/krate/publish.rs
src/tests/krate/search.rs
src/tests/krate/yanking.rs
src/tests/owners.rs
src/tests/read_only_mode.rs
src/tests/server.rs
src/tests/team.rs
src/tests/token.rs
src/tests/user.rs
src/tests/util.rs

`Response::status()` seems easier to use to me and doesn't hide the actual assertion. It also allows us to access things like `StatusCode::is_success()` directly.
r? @jtgeibel

tests/util: Replace `Response::assert_status()` with `Response::status()`

---

Cargo.lock
Cargo.toml
src/controllers/user/session.rs

The older `oauth2` release was the last thing that needed it but with our update to tokio 1.0 we also updated `oauth2`, so we can remove the `failure` dependency now. 🎉 

Remove obsolete `failure` dependency

---

src/views.rs

As of 2021-01-21 the domain is serving advertising on every page. The domain likely expired and then got picked up by squatters.

Block the ironframework.io documentation domain

---

src/controllers/krate/publish.rs
src/models/dependency.rs
src/tests/krate/publish.rs

This PR slightly cleans up the `dependency` model module, primarily by moving the `add_dependencies()` function into the corresponding controller. The function is using view-specific classes, which should be avoided in the `models` modules.

Clean up `dependency` model module

---

.github/workflows/ci.yml

While it is good for us to check whether we are compatible with https://github.com/embroider-build/embroider/ or not, we shouldn't make CI fail if something breaks our embroider compatibility. This problem is currently blocking a few dependency updates that will ultimately improve embroider compatibility, but breaks it in the transition period.
This PR configures our GitHub Actions CI to allow the embroider job to fail, to unblock these dependency updates.
r? @pichfl

CI: Allow embroider build to fail

---

src/db.rs

`connect_now()` appears to share a lot of code with the `connection_url()` function, so it should be safe to use one inside of the other

db: Simplify `connect_now()` implementation

---

docker-compose.yml

Pasting the detailed list of my changes on top of @Turbo87's branch:
* change GIT_REPO_URL to an absolute path to the repo, otherwise the background worker fails with 
`thread 'main' panicked at 'Failed to clone index: Error { code: -1, klass: 2, message: "failed to resolve path \'file://./tmp/index-bare\': No such file or directory" }', src/bin/background-worker.rs:38:46`
* add a new volume for the `local_uploads` directory, otherwise
backend won't be able to read readmes rendered by the background worker.
I'm not aware of any other directories that should be shared between these two services.
* remove the `depends_on` condition for the worker - this syntax is not
supported anymore according to the official docs
https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on
If …

Start background-worker from docker-compose.yml

---

app/initializers/hashchange.js

Catch exceptions thrown when an anchor in a readme is invalid

---

app/router.js

This route does not seem to be used anywhere and it has neither controller, nor template, nor route file.
r? @pichfl

router: Remove unused/empty `crate.download` route

---

src/tests/all.rs
src/tests/util.rs

The `req()` function does not seem to be used anywhere else, so it's probably easiest to keep it in the same module as where it is used.

tests: Move `req()` function to `util` module

---

app/controllers/crate/version.js
app/models/version.js
app/routes/crate/version.js
app/templates/crate/version.hbs

If we want to reuse this in other places then this code should live on the model, not a specific controller.
r? @pichfl

Move docs.rs link code from controller to `version` model

---

app/components/rendered-html.hbs
app/components/rendered-html.module.css
app/styles/crate/version.module.css
app/templates/crate/version.hbs

This PR extracts a new `RenderedHtml` component, which is used to render the README content on the crate details pages. To make the component easier to handle and align on the page, the styling was slightly adjusted so that the component does not have any outer margin by default.
r? @locks

Extract `RenderedHtml` component

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css
app/styles/crate/version.module.css
app/templates/crate/version.hbs

The goal of this PR is to put all the additional metadata of a crate/version into the sidebar, and have the main section focus on the primary content. This content section currently includes the rather large "Copy Cargo.toml snippet" button, which this PR moves to the sidebar instead:
(the screenshot shows the button in the hovered state)
r? @locks

Move "Copy Cargo.toml snippet" button to the sidebar

---

app/components/download-graph.js
app/controllers/crate/version.js
app/templates/crate/version.hbs
tests/components/download-graph-test.js

This code is only needed inside the `DownloadGraph` component, so that's where the code should live. This also gives us the opportunity to simplify the code a little bit, since the Chart.js library needs to data in a different layout than the previous implementation that was based on Google Charts. Visually the results should still be identical to the previous state though :)
r? @locks

Move download data processing code into `DownloadGraph` component

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css
app/templates/crate/version.hbs

In the quicklinks section at the top the link is a bit hard to find. This PR moves it to the sidebar under the list of "Dependencies".
The long-term goal is to move the remaining links to the sidebar too.
r? @locks

controllers/crate.version: Move reverse dependencies link into the sidebar

---

app/components/header.module.css
app/components/progress-bar.module.css
app/styles/application.module.css

This PR refactors our CSS color variables to use numeric darkness values in their names (e.g. `grey900` and `yellow500`), instead of "dark, darker, darkest, ...". It also switches those color values over to use HSL instead of RGB to make it easier to find good light/dark variants of the colors in the future. The actual colors did not change though, they were only converted to the other representation :)
r? @locks

styles: Use numeric darkness naming and HSL for color values

---

src/boot/categories.toml

Sub categories include: transpilers, interpreters, and compilers.
I decided to follow the precedence set by `"parser-implementations"` and `"parsing"` for these categories since they felt appropriately related.
Resolves #1412

Add "compilers" category.

---

.github/workflows/ci.yml

We are running into a similar issue to what is described at https://github.com/embroider-build/embroider/issues/677. We currently allow the CI step to fail, but since it waits until it times out it keeps the PRs in "running" state for an unnecessarily long time.
This PR is changing the CI to only build, but not run the tests, with embroider to avoid the above issue. Once https://github.com/embroider-build/embroider/issues/677 is addressed we can revert this change again.
r? @locks

CI: Disable `yarn test` command for `embroider` job

---

app/models/version.js
app/serializers/version.js
mirage/models/version.js
mirage/serializers/version.js
tests/mirage/crates-test.js
tests/mirage/me-test.js
tests/models/version-test.js

For the more recent releases the crates.io backend now records who published the release and returns that information on the API. It would be useful to eventually show this data either in the versions list or on the version details page.
This PR adds a corresponding `published_by` relationship to the `version` model to make this data generally available in the frontend.

models/version: Add `published_by` relationship

---

app/models/version.js
tests/models/version-test.js

Each published `version` can have different optional `features` and it would be nice to see when a feature has been introduced. This PR prepares for showing this information in the versions list by adding `features` and `featureList` properties to the `version` model.

models/version: Add `features/featureList` properties

---

migrations/2021-02-09-133314_add_version_owner_actions_index/down.sql
migrations/2021-02-09-133314_add_version_owner_actions_index/up.sql

The `api/v1/crates/:name` endpoint includes the `audit_actions` field in the response for each of the crate's versions, and it fetches that data from the `version_owner_actions table`. The query providing that data was unreasonably slow though. Here is its `EXPLAIN ANALYZE`:
QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------
Sort  (cost=1655.59..1655.59 rows=3 width=244) (actual time=15.114..15.115 rows=3 loops=1)
Sort Key: version_owner_actions.id
Sort Method: quicksort  Memory: 25kB
->  Nested Loop  (cost=0.06..1655.58 rows=3 width=244) (actual time=13.514..15.107 rows=3 loops=1)
->  Seq Scan on version_owner_actions  (cost=0.00..1643.40 rows=3 width=28) (actual time=13.500..15.084 rows=3 loops=1) …

Add an index on version_owner_actions.version_id

---

app/routes/crate/version.js

see http://ember-concurrency.com/docs/task-cancelation-help

crate.version: Prevent `TaskCancelation` errors from being sent to Sentry

---

app/models/version.js
tests/models/version-test.js

if there is 0.4.0, 0.4.1 and 0.4.2, and 0.4.2 is yanked then the highest of the release track should be 0.4.1.

models/version: Ignore yanked versions in `isHighestOfReleaseTrack` property

---

app/components/download-graph.js

Fixes https://github.com/rust-lang/crates.io/issues/3256

DownloadGraph: Only call `destroy` if the `Chart` instance has been created

---

app/components/download-graph.js

Fixes https://github.com/rust-lang/crates.io/issues/3254

DownloadGraph: Ignore missing `version` relationships

---

app/routes/application.js

This will hopefully make it easier to identify which routes have the most issues 😅

routes/application: Add `routeName` tag to all issues

---

app/components/sort-dropdown/option.hbs
app/controllers/crate/versions.js
app/styles/crate/versions.module.css
app/templates/crate/versions.hbs
tests/acceptance/versions-test.js

and if "Date" is chose, the following situation, where a bunch of patch releases for older versions got published, will be more visible:

crate.versions: Add "Sort By" dropdown with "Date" and "SemVer" options

---

.github/workflows/ci.yml

This PR adds https://github.com/actions-rs/tarpaulin to our CI pipeline to display a test coverage report.
Resolves https://github.com/rust-lang/crates.io/issues/1162

CI: Run tests via `cargo-tarpaulin`

---

package.json
yarn.lock

This should no longer be necessary since we're using `@ember/test-waiters` everywhere now.

yarn: Remove obsolete `ember-test-waiters` resolution

---

.github/workflows/ci.yml

This should hopefully allow cargo-tarpaulin to be cached correctly

CI: Bump cargo binaries cache version

---

app/templates/crate/version.hbs

according to https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines this appears to be a better fit for what we're doing here

crate.version: Use `<article>` instead of `<section>` for the rendered README

---

Cargo.lock

This updates only the crates that reduce/replace their dependencies. Each commit has the `cargo update` log.
- bytes v0.5.6
- generator v0.6.23
- loom v0.3.6
- scoped-tls v1.0.0
- maybe-uninit v2.0.0
- smallvec v0.6.13 -> tinyvec v1.1.1
r? @jtgeibel

Update some crates to reduce deps

---

migrations/2021-02-10-141019_reserve_com0_lpt0/down.sql
migrations/2021-02-10-141019_reserve_com0_lpt0/up.sql

In #695 we added all the documented reserved Windows file names to the list of reserved crate names, to prevent people from registering crates named that way and breaking all Windows users in the process.
Unfortunately it turns out that COM0 and LPT0 are *also* reserved on Windows systems, but they're not documented in Microsoft's docs. This PR adds both names to the reserved crate names list.
Note that the migration here is a no-op on the production crates.io instance, as both names were manually added to the database before opening this PR.
r? @jtgeibel

Add COM0 and LPT0 to the list of reserved crate names

---

src/bin/server.rs
src/models/action.rs
src/models/user.rs

Address clippy lints currently in beta

---

app/components/download-graph.js

DownloadGraph: Ignore SemVer parsing issues when sorting

---

app/components/crate-sidebar.hbs
app/components/license-expression.hbs
app/components/version-list/row.hbs
app/helpers/parse-license.js
app/utils/license.js
tests/acceptance/crate-test.js
tests/utils/license-test.js

This PR is implementing a basic SPDX license expression parser and a corresponding `LicenseExpression` component, which deemphasizes keywords and adds links to https://choosealicense.com for known license IDs.

Parse license expressions and show links to choosealicense.com

---

src/controllers/util.rs

This PR simplifies the code of the `verify_origin()` function by removing the additional `Vec` allocation. It also converts the function comment to a doc comment.
r? @jtgeibel

controllers::util: Clean up `verify_origin()` function

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.js

[DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) 😉

CrateSidebar: Extract `tomlSnippet` property

---

app/components/download-graph.js
app/components/version-list/row.hbs
app/components/version-list/row.js
app/components/version-list/row.module.css
app/models/version.js
mirage/serializers/crate.js
tests/components/version-list-row-test.js
tests/models/version-test.js

* Add a tooltip message and a new release track indicator (`?`) to components/version-list/row
* Handle null returned from `semverParse` in models/version
* Add `loose` option to `semverParse` (https://github.com/npm/node-semver#functions)
I placed the checks so that "invalid version" has higher priority than "first version" but lower than "yanked".
I also modified css of the version list so that long versions do not overflow from tooltips. 
Before
After
Fixes #3294

Improve invalid semver string handling

---

src/render.rs

Resolves https://github.com/rust-lang/crates.io/issues/2151
As far as I'm aware there is no way that this could be used in any malicious way and `align` is already allowed on e.g. `img` elements by default in the `ammonia` crate.

README: Allow `align` attributes

---

app/components/crate-header.hbs
app/components/crate-header.js
app/components/crate-header.module.css
app/components/crate-sidebar.hbs
app/components/crate-sidebar.js
app/components/nav-tabs.hbs
app/components/nav-tabs.module.css
app/components/nav-tabs/tab.hbs
app/components/nav-tabs/tab.module.css
app/styles/crate/versions.module.css
app/templates/crate/owners.hbs
app/templates/crate/reverse-dependencies.hbs
app/templates/crate/versions.hbs
tests/acceptance/crate-test.js

Not visible on the screenshots: if you're a crate owner then a fourth "Settings" tab will also be visible
This should also resolve #3321

Add navigation tabs to the crate details pages

---

app/components/front-page-list/item/placeholder.module.css

I totally forgot that during https://github.com/rust-lang/crates.io/pull/3282 ... 😱

FrontPageList::Item::Placeholder: Adjust styling to match `FrontPageList::Item` component

---

app/components/crate-header.hbs
app/components/crate-header.module.css
app/components/loading-spinner.module.css
app/styles/crate/version.module.css
app/templates/crate/version.hbs

This makes it easier to figure out on first glance what a crate does, without having to wait for and read through the README text.

Display crate description in the `CrateHeader` component

---

Cargo.lock
Cargo.toml
src/router.rs
src/tests/util.rs

This bumps a few conduit crates to pull in the latest version of these dependencies.
r? @Turbo87

Bump to latest route-recognizer and cookie crates

---

app/components/crate-sidebar.hbs
app/models/crate.js

These may have existed at some point, but these fields are no longer sent by the backend, so there is no point in us still handling them

Remove obsolete attributes from `crate` model

---

app/helpers/format-email.js
app/services/progress.js

This should resolve a few of the deprecation warnings that got introduced with Ember 3.25

Import `htmlSafe` from `@ember/template`

---

app/components/version-list/row.module.css

VersionList::Row: Fix tooltip alignment in narrow viewport

---

app/components/crate-list.hbs
app/components/crate-list.module.css
app/components/crate-row.module.css
app/controllers/search.js
app/styles/category/index.module.css
app/styles/crates.module.css
app/styles/keyword/index.module.css
app/styles/me/crates.module.css
app/styles/me/following.module.css
app/styles/search.module.css
app/styles/team.module.css
app/styles/user.module.css
app/templates/category/index.hbs
app/templates/crates.hbs
app/templates/keyword/index.hbs
app/templates/me/crates.hbs
app/templates/me/following.hbs
app/templates/search.hbs
app/templates/team.hbs
app/templates/user.hbs

Extract `CrateList` component and improve the styling

---

app/components/crate-header.hbs
app/components/crate-header.js
app/components/crate-sidebar.hbs
app/components/dependency-list/row.hbs
app/components/dependency-list/row.js
app/components/dependency-list/row.module.css
app/components/link-to-dep.hbs
app/components/link-to-dep.module.css
app/components/nav-tabs/tab.hbs
app/router.js
app/routes/crate/dependencies.js
app/routes/crate/version-dependencies.js
app/routes/crate/version.js
app/styles/crate/version-dependencies.module.css
app/templates/crate/version-dependencies.hbs
app/templates/crate/version.hbs
tests/acceptance/crate-dependencies-test.js
tests/acceptance/crate-navtabs-test.js
tests/acceptance/crate-test.js

Implement "Dependencies" tab

---

app/components/crate-header.hbs
app/components/crate-header.module.css
app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css

This moves the list of crate keywords right below the crate description in the header to make them easier to discover and navigate :)

Move keyword list from `CrateSidebar` to `CrateHeader`

---

app/models/version.js
tests/models/version-test.js

Example: https://crates.io/crates/rustc-ap-rustc_arena/versions
Having `706.x` as the release track barely fits in the release track indicator, so let's shorten this value for major versions above 100.

models/version: Shorten `releaseTrack` for high major versions

---

app/components/dependency-list/row.hbs
app/router.js
app/routes/crate/range.js
tests/routes/crate/range-test.js

... that redirects the user to the highest version that satisfies the specified semver range. I guess the added test cases should explain the purpose quite well :)

Implement and use `/crates/:crate_id/range/:range` route

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.js
app/components/crate-sidebar/link.js
tests/components/crate-sidebar/link-test.js
tests/routes/crate/version/crate-links-test.js

This PR strips trailing slashes from the displayed links, strips trailing `.git` for any github.com link, and uses the simplified URL to figure out if the homepage link matches the repository link.
https://crates.io/crates/aprs-parser for example currently shows `https://github.com/Turbo87/aprs-parser-rs/` as the homepage and `https://github.com/Turbo87/aprs-parser-rs.git` as the repository, but with this PR these links will be treated as equivalent and only the repository link will be shown.

Improve "external crate link" simplification logic

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.js
app/components/crate-sidebar.module.css
app/routes/application.js
app/services/playground.js
app/utils/ajax.js
config/nginx.conf.erb
tests/components/crate-sidebar/playground-button-test.js
tests/services/playground-test.js
tests/utils/ajax-test.js

Show "Try on Rust Playground" button for crates that are available there

---

src/controllers/util.rs
src/tests/authentication.rs

The function was a bit hard to read and difficult to extend (see #3307). This PR simplifies it a little bit by returning early if a suitable authentication method was found.
r? @jtgeibel

Simplify `authenticate_user()` function

---

.github/workflows/ci.yml

It looks like `cargo clippy` and `cargo test` are currently fighting over the compile cache, which increases our CI times quite a bit. This PR moves the linting checks (`cargo fmt` and `cargo clippy`) out of the regular `backend` job to having linting and tests run in parallel.

CI: Run `cargo fmt` and `cargo clippy` as a dedicated job

---

docker-compose.yml
docker/docker-entrypoint-initdb.d/create-databases.sql

This PR allows us to use the docker-compose setup to run `cargo test` with the Dockerized Postgres server. It also adjusts the docker-compose setup a little bit to not expose the `postgres` container on *all* host interfaces, but instead only makes it available on 127.0.0.1.
To run just the database container you can use:
```
docker-compose up -d postgres
```
(`-d` runs it in daemon mode)
/cc @plaets

Docker: Improve `postgres` setup

---

Cargo.lock
Cargo.toml

The changes between alpha.3 and alpha.6: https://github.com/ramosbugs/oauth2-rs/compare/4.0.0-alpha.3...4.0.0-alpha.6
All the breaking changes mentioned on https://github.com/ramosbugs/oauth2-rs/releases and the changes themselves don't seem to affect our codebase.
Also pin its version to prevent updating by accident when running `cargo update`.
r? @jtgeibel

Upgrade `oauth2` to 4.0.0-alpha.6

---

Cargo.lock
Cargo.toml

The changes between alpha.5 and beta.1: https://github.com/lettre/lettre/compare/v0.10.0-alpha.5...v0.10.0-beta.1
This release contains a lot of refactorings and a few new features. The default features have also changed but it won't affect here as we have `default-features = false`. Other changes also don't, at a glance.
(Separating PRs from oauth2's in case we find an issue.)

Upgrade `lettre` to 0.10.0-beta.1

---

app/components/crate-header.module.css
app/components/crate-sidebar.module.css
app/styles/application.module.css

This PR primarily unifies the font-family that is used for monospace display.

Extract font-family CSS variables

---

app/components/follow-button.module.css

Instead of having the button change its size depending on the content we now set a fixed size. This avoids annoying layout shifts when changing from text label to loading spinner and back, for example.

FollowButton: Avoid size changes

---

src/render.rs
src/tests/all.rs
src/tests/authentication.rs
src/tests/krate/dependencies.rs
src/tests/krate/publish.rs
src/tests/server.rs
src/tests/token.rs
src/tests/user.rs
src/tests/util.rs
src/tests/util/response.rs
src/tests/util/test_app.rs

It is best to review per-commit, as some logic is split into sub-modules under `util` which obscures the smaller diffs within. The individual commits should all be straightforward.
In particular, many `T: serde::Deserialize` bounds are removed from various test helper methods, which allowed some remaining on-off tests to switch over to the test helpers.
r? @Turbo87

Refactor some test code

---

app/models/version.js
tests/routes/crate/version/docs-link-test.js

Is running `this.server.get` in one test twice ok?
Fixes #3348

Handle invalid docs.rs responses better (fixes #3348)

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css

CrateSidebar: Move last update, license and crate size into new "Metadata" section

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.js
tests/components/crate-sidebar/playground-button-test.js

This move a bit of noise from the sidebar into a tooltip that is shown when hovering over the button.

CrateSidebar: Move Playground explanation to a tooltip

---

app/components/crate-sidebar.module.css
app/components/crate-sidebar/link.hbs
app/components/crate-sidebar/link.module.css
app/styles/crate/version.module.css

This is an alternative for https://github.com/rust-lang/crates.io/pull/3395, which uses `text-overflow: ellipsis` instead. This shortens the URLs and uses an `…` suffix instead, if they get too long. The downside is that the full URL is not displayed if the URL is too long, but it looks like GitHub and npm use the same pattern in their UIs, so it might not be so bad 😅 
I also had to convert the README/Sidebar container element to use CSS grid instead of flexbox to make the ellipsis work properly. Maybe I missed something but I couldn't get it to work when using all of the nested flexbox elements.

CrateSidebar::Link: Use ellipsis suffix for long URLs

---

src/controllers.rs
src/controllers/version/downloads.rs
src/middleware/log_request.rs

We're getting increasingly frequent pages about quick bursts of really slow download requests. Unfortunately the amount of logging and monitoring we currently have available is not enough to properly pin down what's causing this.
This PR adds instrumentation to the download endpoint to log how much each potentially slow step (getting a db connection, getting the version info and updating the download count) takes, and the infrastructure to support such instrumentation.
To avoid outputting too much stuff into the log lines, the detailed timings are only shown on slow requests.
r? @jtgeibel

Log how much each step takes on slow downloads

---

app/components/front-page-list/item/placeholder.hbs
app/components/front-page-list/item/placeholder.module.css
app/components/placeholder.hbs
app/components/placeholder.module.css
app/styles/application.module.css
app/styles/crate/version.module.css
app/templates/crate/version.hbs

This PR also extracts a `Placeholder` component, to make this kind of thing more reuseable :)
https://user-images.githubusercontent.com/141300/110982133-6fc5bf00-8368-11eb-9d31-acc653870fb2.mov

Show placeholders instead of loading spinner for the README

---

config/nginx.conf.erb
src/middleware/log_request.rs

This works because the nginx proxy and application are running on the
same machine. For local development, which is not typically run behind
nginx, the previous calculation based on the in-app web server is used
as a fallback.

Capture request start time in nginx for calculating response times

---

app/components/user-avatar.js
app/templates/crate/owners.hbs

Let's take https://crates.io/crates/libc/owners as an example. It currently looks like:
The problem is that the name field doesn't display anything if the account name is empty (e.g. https://github.com/rust-lang-owner).
This PR fixes that behavior to show their username (`user.login`) instead.
This also fixes the alt attribute for the avatar image by just removing `null` (it still doesn't ideal but should be better).

Display username instead if they don't have the "name" field

---

src/tasks/dump_db.rs
src/tasks/dump_db/configuration.rs
src/tasks/dump_db/gen_scripts.rs

Context: I will be sending a PR to topologically sort the tables inserted into the db-dump.tar.gz by [`DumpTarball::create`](https://github.com/rust-lang/crates.io/blob/c32fef25c58e53b007dd5795e39fae48800d9bfe/src/tasks/dump_db.rs#L144). That requires access to the same `dependencies` DAG described by dump-db.toml, but outside of the context of gen_scripts.
Rationale: stream processing of db-dump.tar.gz; pipelining the extraction and import.

Extract VisibilityConfig from gen_scripts module

---

app/styles/crate/reverse-dependencies.module.css
app/templates/crate/reverse-dependencies.hbs

reverse-dependencies: Show "no results" message instead of empty list

---

Cargo.lock
Cargo.toml
src/app.rs
src/bin/server.rs
src/config.rs
src/controllers/version/downloads.rs
src/downloads_counter.rs
src/lib.rs
src/models/download.rs
src/tests/krate/downloads.rs
src/tests/util/test_app.rs

crates.io receives a lot of download requests, and we're reaching a point where executing a write query to PostgreSQL for each request is causing operational issues. Over the past few weeks we've been getting regular pages due to download requests being slow to execute or outright fail for a couple of seconds, due to the database being overwhelmed.
This PR avoids that problem by collecting download counts in memory and periodically persisting them into the database, hopefully reducing the write load coming to our primary database thanks to the new `downloads_counter` module.
The implementation is designed to reduce the amount of locking needed as much as possible to prevent requests from being unnecessarily delayed. Instead of storing the counters in a `RwLock<HashMap<i32, AtomicUsize>>`, …

Reduce database writes for the download endpoint

---

src/downloads_counter.rs

While analyzing the behavior of `DownloadsCounter` (introduced in https://github.com/rust-lang/crates.io/pull/3413) in production, we noticed that there were a few cases of transaction deadlocks tonight in the background thread persisting the download counts.
I did some investigation on the cause of this and came up with this fix. As [recommended by the PostgreSQL docs](https://www.postgresql.org/docs/11/explicit-locking.html#LOCKING-DEADLOCKS), to avoid deadlocks when multiple transactions affect multiple rows in a table, the affected keys needs to be modified in a consistent order across the transactions. We implement that by sorting by `version_id` the items we're going to insert.
<details><summary>Local reproduction instructions</summary>
The exact error we saw in production can be …

Prevent transaction deadlocks in DownloadsCounter

---

Procfile
script/start-web.sh
src/bin/server.rs
src/downloads_counter.rs

In production we aren't gracefully shutting down as expected. nginx
does a quick shutdown when receiving a `SIGTERM` and once it exits, it
appears that our process is aborted.
Instead of spawning the backend from the shell script, the backend
process is now responsible for spawning the shell script. This allows
the backend to finish its shutdown work even if the script has already
exited.
`cat` is passed to the nginx buildpack script as our "server", which
will block on `STDIN` so that `nginx` will run until receiving
`SIGTERM`.

Boot nginx from the backend app to fix graceful shutdown in production

---

app/components/rev-dep-row.hbs
app/components/rev-dep-row.js
app/components/rev-dep-row.module.css
app/styles/crate/reverse-dependencies.module.css
app/templates/crate/reverse-dependencies.hbs

Improve reverse dependency list styling

---

src/controllers/krate/publish.rs
src/tests/krate/publish.rs

See https://github.com/rust-lang/rust/issues/83227

start accepting crates without authorship information

---

src/controllers/krate/search.rs
src/tests/krate/search.rs

... to reduce unnecessary N+1 requests
This can be used in combination with e.g. #3405 to speed up the loading of crate descriptions.

krate.search: Add support for `?ids[]=foo&ids[]=bar` queries

---

Cargo.lock
Cargo.toml

New major releases of `comrak`, `dialoguer`, and `claim`. `lettre` and `oauth2` have moved from alpha to beta.
r? @Turbo87

Bump some of our direct dependencies

---

src/middleware.rs
src/middleware/debug.rs

The first commit drops the ability to enable this middleware on production. With current traffic levels this isn't very practical (as concurrent requests can interleave their output), and we don't want to log headers that may contain authorization cookies or tokens.
The second commit silences the debug information by default during local development. It can be re-enabled by setting the `RUST_LOG` environment variable appropriately.
r? @Turbo87

Update debug middleware

---

app/components/crate-sidebar.js
app/routes/application.js
app/routes/crate/version.js
app/services/progress.js
app/services/sentry.js
app/services/session.js
tests/helpers/index.js
tests/helpers/sentry.js

This makes it easier to mock the Sentry code during tests to ensure that whether we send certain types of errors to Sentry or not.

Extract `sentry` service

---

app/styles/crate/reverse-dependencies.module.css

The back link on this page does not exist anymore 😉

reverse-dependencies: Remove unused CSS class

---

app/routes/crate.js
app/routes/crate/version.js
tests/acceptance/crate-test.js

Rethrowing the error means that it ends up creating noise on Sentry even for regular network errors.
Resolves https://github.com/rust-lang/crates.io/issues/240

Show generic flash message if crate data fails to load 

---

src/bin/enqueue-job.rs
src/tasks.rs
src/tasks/daily_db_maintenance.rs

Run `VACUUM version_downloads;` daily. We could alternatively tweak the
auto-vacuum parameters on this table, but long term we should archive
daily download stats outside of the database and it will be easier to
pick the parameters then, once we have only 90 days of history rather
than growing daily without bound.
r? @Turbo87

Run daily database maintenance tasks

---

src/bin/server.rs
src/db.rs
src/downloads_counter.rs
src/tasks/update_downloads.rs
src/tests/krate/downloads.rs

This fixes https://github.com/rust-lang/crates.io/issues/3416 by adding tests for `DownloadsCounter`. There are a few notable things in this PR I'd like to highlight.
First off, the tests are not implemented in `src/tests`, but are implemented in a `#[cfg(test)] mod tests {}` in the same source file. While this resulted in some code duplication I had to do this because testing `persist_next_shard` requires access to the internals of `DownloadsCounter` and I'd prefer not to expose them.
This PR also fixes a bug I discovered while writing the test for incrementing a missing version. Inserting a missing version ID in the `version_downloads` table doesn't work thanks to the foreign key, and aborts the whole `INSERT` statement (losing all the downloads in that shard). This could happen in …

Adds tests for DownloadsCounter

---

package.json

Not having this flag set was deprecated in Ember 3.26

package.json: Set `edition: octane` flag

---

app/routes/crate/range.js
tests/routes/crate/range-test.js

Fixes #3448
It took this long because I started overthinking and went back and forth on some decisions. In the end, I decided to just replace all ',' with spaces... It should be enough for ranges that are valid for cargo (as of 0.53.0). I'm assuming that I don't need to handle the implicit caret (like renovate does) because it's inserted automatically somewhere in the backend.   
I also wanted to note that `/range/` will happily accept  ranges that are not supported by cargo (`||`, `-`, ...). Code in this commit does not handle these cases in any way. But then, cargo is currently using semver v0.10.0, meanwhile v0.11.0 implements `||`... 
For future reference:
* [Npm semver docs, section 'Advanced Range Syntax'](https://www.npmjs.com/package/semver)
* [Semver ranges in cargo …

Fixes #3448 Handle cargo-style semver in `/range`

---

src/util/errors.rs

This deprecation warning in the new Rust v1.52 beta is currently breaking our CI.
@jtgeibel I guess that's the reason why I usually prefer pinned versions in the CI configs 😉

util/errors: Fix "trait objects without an explicit `dyn`" deprecation warning/error

---

src/downloads_counter.rs

This PR is related to #3462 and uses `#[ignore]` to ignore the broken test for now. This should unblock our CI runs and allows us to keep merging unrelated PRs until the test is fixed.

DownloadsCounter: Ignore flaky `test_increment_missing_version()` test for now

---

src/downloads_counter.rs

This fixes #3462, and while we're at it duplicates `test_increment_missing_version` in two separate tests, one checking when the two versions are in the same shard and one where they're in different shards.
r? @Turbo87

Improve tests for DownloadsCounter

---

src/app.rs
src/controllers/user/me.rs
src/controllers/user/session.rs
src/downloads_counter.rs
src/email.rs
src/lib.rs
src/models/krate.rs
src/models/user.rs
src/publish_rate_limit.rs
src/tasks/update_downloads.rs
src/tests/krate/search.rs
src/tests/owners.rs
src/tests/user.rs
src/tests/util/test_app.rs

Before this PR there wasn't really a practical way to test what the content of an email is, which makes it harder for example to test that the token included in the ownership confirmation email works with the relevant APIs.
The main thing this PR does is refactoring the email handling code, moving from standalone functions to an `Emails` struct (an instance of it is stored in the `App`). This allows to configure which email backend is used at startup instead of automatically detecting it every time we happen to send an email address. It will also allow to persist other email-related information when we'll need to.
Thanks to the new email backends support this PR also adds a "memory" backend, used during tests. Instead of sending the email via SMTP or storing it into a file, the "memory" …

Add support for testing emails

---

app/serializers/crate-owner-invite.js
tests/acceptance/invites-test.js

Ember Data expects all resources to have an `id`. In this serializer we are renaming that expectation to `crate_id` for questionable reasons. This worked fine as long as only `CrateOwnerInvite` resources were contained in the response, but now we also have `User` resources, and those don't have a `crate_id` attribute, which is causing issues.
This commit removes the `users` array from the response for now to fix this problem. In the future we should look into either responding with a proper ID or generating it based on `crate_id` and `invitee_id`.

CrateOwnerInvite: Avoid "missing `id`" issue

---

src/bin/background-worker.rs

Due to the large size of the database dumps, the upload does not complete within the default 30 second timeout.
Because the database dump job was repeatedly failing, I deleted the job for today. The current database dump on S3 is probably truncated. Hopefully we can land and deploy this before the job is queued again in about 22 hours.

Increase HTTP request timeout for background jobs

---

app/adapters/crate.js
mirage/route-handlers/crates.js
tests/adapters/crate-test.js
tests/mirage/crates-test.js

This PR is based on #3445 and #3426 and allows `findRecord('crate', ...)` calls to be grouped into a single network request if they are started within the same runloop tick. This helps to prevent unintended N+1 request situations and enables us to implement #3405 in a more efficient way.

Add `crate` adapter that coalesces `findRecord()` requests

---

app/adapters/crate.js
app/components/dependency-list/row.hbs
app/components/dependency-list/row.js
app/components/dependency-list/row.module.css
app/components/rev-dep-row.hbs
app/components/rev-dep-row.js
app/components/rev-dep-row.module.css
mirage/fixtures/crates.js
mirage/route-handlers/crates.js
tests/acceptance/crate-dependencies-test.js
tests/acceptance/reverse-dependencies-test.js
tests/adapters/crate-test.js
tests/mirage/crates-test.js

This PR adds the crate descriptions to the dependency and reverse dependency lists:
The descriptions (and other `crate` details) are loaded async, so I've added a description placeholder that is replaced once the request has returned. If the request fails the row is simply displayed without a description.
The PR is based on https://github.com/rust-lang/crates.io/pull/3447 to avoid unnecessary N+1 requests.
Closes #2790

Load and show crate descriptions for dependency lists

---

app/components/header.hbs
tests/acceptance/search-test.js

Now it's more flexible and works even if you (possibly accidentally) have Caps Lock enabled. This already works for the Rust docs too so I thought it's more consistent this way.

Make it possible to open the search using S

---

src/s3/lib.rs

This is an alternative to https://github.com/rust-lang/crates.io/pull/3494, which increases the timeout only for the relevant S3 PUT request.

s3: Increase `put()` timeout to 60sec

---

app/components/pending-owner-invite-row.js
app/routes/accept-invite.js
app/templates/accept-invite.hbs
src/config.rs
src/controllers/crate_owner_invitation.rs
src/models.rs
src/models/crate_owner_invitation.rs
src/models/krate.rs
src/tests/owners.rs
src/tests/util/test_app.rs
src/util/errors.rs
src/util/errors/json.rs
src/views.rs
tests/acceptance/invites-test.js
tests/acceptance/token-invites-test.js

This PR fixes #2869 by implementing a 30 days expiration for all ownership invitations.
Once an invite gets past its expiration date it will disappear from the [pending invites page](https://crates.io/me/pending-invites), and trying to accept it with the email link will display a message saying the invite expired and that the user needs to request a new one from the crate owner. Technically it's possible to decline an invite after it's expired through the API, but declining just deletes the row from the database so it's fine.
The new expiration rules will apply to existing invites too, and invites created more than 30 days before the deploy will instantly be treated as expired. The expiration check is entirely done on the application side, and the database schema is not changed: rolling …

Add an expiration to owner invitations

---

src/controllers/version/downloads.rs

We could instead include the corrected name, but that doesn't seem very
useful and this is already something I search the logs for occasionally.
This change will allow us to collect some data to see if it would be
practical to blindly redirect the request if there is an issue obtaining
a database connection from the pool.

Log a flag for downloads with non-canonical crate names

---

src/controllers/crate_owner_invitation.rs
src/controllers/krate/follow.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/util.rs
src/tests/krate/following.rs
src/tests/owners.rs
src/tests/token.rs
src/tests/user.rs

This PR adds explicit denial of API token authentication on most GET APIs. 
Currently, CloudFront was never passing along the `Authorization` header for `GET` requests. 
(See rust-lang/simpleinfra#43 for more details.)
In addressing that issue it was pointed out that there may be GET APIs that the team might not want to commit to allowing API tokens access to.
This PR attempts to limit the exposed APIs to:
- `/api/v1/crates?following=1` (the crates "search" API, which is the only way to get the list of crates a user is following.)
- `/api/v1/me` 
> Note: There were already [tests verifying token access to this API][me-tests], but with the CloudFront issue this API was not actually accessible.
[me-tests]: https://github.com/rust-lang/crates.io/blob/03f7b273eb7a024de8282ac2297daaa47df33fa6/s …

Add API Token Auth restrictions on GET APIs

---

src/controllers/krate/search.rs
src/controllers/user/me.rs
src/tests/token.rs

This prohibits access to the `/api/v1/me` endpoint via an API token. I'd like to merge and deploy this before moving forward on rust-lang/simpleinfra#43, which would expose this endpoint. (Previous lockdown work was done in #3470.)
The second commit ensure that the user is only authenticated on the search endpoint when querying for followed crates.

Forbid token auth on `/me` endpoint

---

app/components/footer.hbs

this PR updates the website footer to link to the (updated) privacy policy, which now lives on the Rust Foundation website: https://foundation.rust-lang.org/policies/privacy-policy/.

feat(footer): update link to privacy policy

---

src/controllers/version/metadata.rs

Part of https://github.com/rust-lang/rust/issues/83227#issuecomment-823267544
Stop returning authorship information from the API, changing the endpoint to always return an empty list.

Return the empty list for authors API

---

Cargo.lock
Cargo.toml
src/app.rs
src/config.rs
src/controllers.rs
src/controllers/metrics.rs
src/db.rs
src/lib.rs
src/metrics/instance.rs
src/metrics/macros.rs
src/metrics/mod.rs
src/metrics/service.rs
src/middleware.rs
src/middleware/update_metrics.rs
src/router.rs
src/tests/all.rs
src/tests/metrics.rs
src/tests/util/test_app.rs
src/util/errors.rs
src/util/errors/json.rs

This PR adds support for collecting Prometheus metrics in crates.io, and adds some basic metrics to make sure everything works correctly. We'll want to add way more metrics after the PR is merged.
Prometheus is the monitoring service used for most of the Rust infrastructure, and the infra team maintains an instance of it. Prometheus periodically scrapes an endpoint of the application and ingests all the metrics contained in it. It then provides a query interface to visualize metrics over time, and supports generating alerts based on the current metrics.
An example query to detect when there are more than 100 crates published in an hour would be:
```
increase(cratesio_service_versions_total[1h])
```
Service-level metrics are available at `/api/private/metrics/service` and include all the …

Add support for Prometheus metrics

---

src/publish_rate_limit.rs

Larger burst limits can be applied on a per-user basis if they contact
us ahead of time.

More aggressively rate limit reserving new package names

---

Cargo.lock
Cargo.toml

There's no functional change from the beta: https://github.com/ramosbugs/oauth2-rs/compare/4.0.0-beta.1...4.0.0

Upgrade `oauth2` to 4.0.0

---

src/app.rs
src/bin/background-worker.rs
src/config.rs
src/lib.rs
src/tests/util/test_app.rs

If set to `leader` then the follower credentials are used in read-only
mode for all connections. The background-worker will log a message every
minute as a reminder to scale down its instance until the leader is
restored. To operate the server in this mode, a value must be provided
for `READ_ONLY_REPLICA_URL`.
If set to `follower` then no follower connection pool is initialized, as
if `READ_ONLY_REPLICA_URL` was not set.

Add `DB_OFFLINE` as a failsafe during outages

---

.buildpacks
Cargo.toml
Procfile
src/admin/migrate.rs
src/admin/mod.rs
src/bin/crates-admin.rs
src/bin/server.rs
src/lib.rs

The new command will be used in production to run migrations instead of installing the Diesel CLI and running migrations through it. In addition to that, synchronizing categories has been moved to the `crates-admin migrate` command instead of being executed every time the application starts.
The main advantage of this is, booting the server will not *require* a fully working database connection anymore. A connection is still needed, but this removes all the blockers for removing that limit.
r? @jtgeibel 
Part of #3541

Create `crates-admin migrate` to sync categories and migrate the db

---

src/downloads_counter.rs

This will reduce the logging output on staging and during local development.

Only log downloads_counter if a value is non-zero

---

src/admin/render_readmes.rs
src/bin/server.rs
src/config.rs
src/middleware.rs

This struct contains a lot of owned data and cloning the entire struct
is unnecessary.
r? @Turbo87

Avoid cloning `Config` struct

---

Cargo.lock
Cargo.toml
src/app.rs
src/background_jobs.rs
src/config.rs
src/controllers/version/downloads.rs
src/db.rs
src/metrics/instance.rs
src/tests/all.rs
src/tests/dump_db.rs
src/tests/unhealthy_database.rs
src/tests/util.rs
src/tests/util/chaosproxy.rs
src/tests/util/fresh_schema.rs
src/tests/util/test_app.rs

We had a few database-related outages in the recent weeks, which impacted people downloading crates with Cargo. Download requests are the majority of the traffic we serve, and they're also the most critical ones. Even if the rest of crates.io stops working downloads *must* continue to be operational to reduce the impact on our users.
As a preface, the downloads endpoint used the database for two reasons: counting the downloads (which can be skipped during outages) and ensuring the crate name is canonicalized. For example, if someone tries to  `Foo-bar 1.0.0` by calling `/api/v1/crates/foo_Bar/1.0.0/download` the crates.io application canonicalizes the name and redirects the user to `https://static.crates.io/crates/Foo-bar/Foo-bar-1.0.0.crate`. If we were not to perform canonicalization …

Do unconditional redirects for downloads when the db is broken

---

.buildpacks

We currently use heroku-buildpack-multi which is no longer actively
maintained. Heroku supports multiple buildpacks natively and it makes
sense to follow their recommendation even if our config is a bit
different. (Heroku is currently detecting the framework as
`nginx-buildpack`.)
https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app#adding-a-buildpack
> The buildpack for the primary language of your app should always be
> the last buildpack in the list. This ensures that defaults for that
> primary language are applied instead of those for another language,
> and allows Heroku to correctly detect the primary language of your app.

Run the Rust buildpack last

---

src/admin/migrate.rs
src/bin/crates-admin.rs

If the primary is in read-only mode then the leader database in
`DATABASE_URL` may be unavailable. To avoid blocking configuration
changes, the command exits immediately claiming success.

Ensure the release succeeds when the primary database is read-only

---

migrations/2021-05-03-174624_add_index_version_downloads_not_processed/down.sql
migrations/2021-05-03-174624_add_index_version_downloads_not_processed/up.sql

:warning: **Please let me manually deploy this PR to production instead of batching it with other deploys.** :warning: 
To avoid impairing workloads running in production we'll want to run `CREATE INDEX CONCURRENTLY ...` manually when the background job is not running, instead of relying on the migration in the PR. The migration will still succeed thanks to `IF NOT EXISTS`.
---
While investigating issues with the load on our primary database I noticed that all the load spikes happened when the background job updating the download counts was running. After analyzing the queries executed by that job I noticed two queries that were doing a sequential scan of the whole version_downloads table.
The version_downloads table serves two purposes: storing historical download stats (with one row per …

Add index `version_downloads_not_processed`

---

Cargo.lock
Cargo.toml

An XSS vulnerability has been reported in comrak < 0.10.1 (including 0.10.1-rc.1); see https://github.com/kivikakk/comrak/issues/187.
crates.io is **unaffected** due to our use of `ammonia` (which is best practice :+1:), but it's probably not ideal to be using a version with a known bug either way.

Update comrak to 0.10.1

---

package.json
yarn.lock

Reverts rust-lang/crates.io#3580
This has been causing the following error in production builds:
> Could not find module `ember-testing` imported from `@ember/test/index`
Detailed investigation is still pending, but in the meantime we should revert this update for now.

Revert "Update dependency ember-source to v3.27.0"

---

migrations/2021-05-05-081208_recreate_version_downloads_date_index_with_brin_pages_per_range_1/down.sql
migrations/2021-05-05-081208_recreate_version_downloads_date_index_with_brin_pages_per_range_1/up.sql

The `recent_crate_downloads` materialized view currently takes a lot of time to regenerate (in the order of multiple minutes), and that's impacting the performance of our database server. I looked at the query backing the materialized view and noticed it was using a BRIN index over the date column to discard historical data stored in the table. Our write patterns are similar to the ones where BRIN indexes works best.
I tried tweaking the parameters of the index, and these are the results:
| kind   | pages_per_range | data read | index size |
|--------|-----------------|-----------|------------|
| BRIN   |             128 |   3.29 GB |    0.16 MB |
| BRIN   |              16 |   2.13 GB |    1.12 MB |
| BRIN   |               1 |   1.34 GB |   17.00 MB |
| |
| B-TREE |                 | …

Recreate the BRIN index on `version_downloads` with `pages_per_range=1`

---

.github/workflows/ci.yml

see https://github.com/xd009642/tarpaulin/issues/756
r? @ghost

CI: Cycle cargo binary cache and add `--avoid-cfg-tarpaulin` to tarpaulin

---

src/tasks/dump_db/dump-db.toml
src/tasks/dump_db/dump-import.sql.hbs

This column is postgres specific and is normally populated via a
trigger. The trigger is now enabled during the import so that the column
can be dropped from the export.
This addresses part of what was raised in bullet point 2 of #2078. The large readme column remains because there could be people using that data, but the text search column is redundant.
r? @smarnach 
cc @kornelski

Drop crates.textsearchable_index_col from the export

---

src/tasks/dump_db/dump-db.toml

In #3479 we plan to drop old entries and archive them in some other way, so old entries will eventually disappear from dumps anyway. This should make use of the database dumps much more practical for daily use. I think it would be reasonable to even limit this to the past week of data.
r? @pietroalbini 
cc @kornelski, #2078

Include only the last 90 days of downloads in our database dumps

---

src/app.rs
src/bin/server.rs
src/db.rs
src/tests/all.rs
src/tests/server_binary.rs
src/tests/util.rs
src/tests/util/chaosproxy.rs
src/tests/util/test_app.rs

This PR implements the last bit of #3541, making sure the server binary can start without a database connection.
To avoid serving the initial requests without a connection, the server will now wait for 5 seconds at startup to initialize the database connections, and if it can't do that in that timeframe it will treat the database as unhealthy and continue starting up the server.
This is critical to our continued availability, so to make sure this doesn't regress I also implemented a test that fails if a database connection becomes a requirement to start the server again. The test is implemented by starting the server binary with the right environment variables and doing proper HTTP requests to it.
Fixes #3541 
r? @jtgeibel

Allow the application to start without a database connection

---

app/components/crate-header.module.css
app/components/crate-row.module.css
app/components/crate-sidebar.module.css
app/styles/crate/version.module.css

Notified that *crates.io* seems not optimized for small screen devices while I was finding crates on my phone, some long crate names made the website in a mess due to missing line breaks, in my opinion a simple workaround would apply to it by adding line breaks.
Test on my laptop with Safari 14.1:
- Add overflow wrap to the names of crates
- Add word-break to the header name and no-readme texts in detailed crate pages
- Add word-break to texts inside the sidebar copy button 
- Change the flex layout wrap to column when window width is less than `890px` to avoid warp overflow in row
This would not be the best workaround, it only provides a better experience while surfing the *crates.io* on the phone, on small screen devices or on a split window view.

Fix missing line breaks for crate name and refine sidebar layout

---

package.json
yarn.lock

`yarn-deduplicate` has some unintended behavior that would otherwise revert the PostCSS update. With this commit we can ensure that `ember-css-modules` uses PostCSS v8 instead of v7.

Add `postcss` resolution

---

package.json
yarn.lock

This is enabled by default in Babel these days

Remove obsolete `babel-plugin-syntax-object-rest-spread` dependency

---

src/git.rs

The first commit refactors some background job logic for the index repository.
The second commit logs a message if the background worker sees a different upstream `HEAD` than the currently expected commit. Background workers obtain a lock on the registry index so a reset should only occur if the last job modified the index but failed to push its commit, or the index was mutated externally (ex: to delete crates).
r? @Turbo87

Log a message if the background worker resets HEAD

---

src/config.rs
src/controllers/helpers/pagination.rs
src/lib.rs
src/tests/util/test_app.rs

`WEB_PAGE_OFFSET_UA_BLOCKLIST` is a comma seperated list of user-agents
that will be blocked if `WEB_MAX_ALLOWED_PAGE_OFFSET` is exceeded.
`WEB_MAX_ALLOWED_PAGE_OFFSET` defaults to 200.
`WEB_PAGE_OFFSET_UA_BLOCKLIST` defaults to the empty list. Because
empty user-agents are already blocked for non-download endpoints, the
check is disabled if this variable is empty or undefined.

Reject requests with large page offset

---

ember-cli-build.js

With Chart.js v3 this is no longer needed, and the file doesn't even exist anymore 😅

Remove obsolete Chart.js CSS import

---

src/config.rs

This fixes a bug where if `WEB_PAGE_OFFSET_UA_BLOCKLIST` was not set,
then all user-agents were blocked for large page offsets. This was
because all string contain the empty string.
Now, no blocking occurs if the variable is unset. If set to the empty
string, or the list contains an empty string, then all user-agents will
be blocked.

Disable page offset blocking if UA blocklist is unset

---

src/controllers/krate/downloads.rs
src/controllers/krate/metadata.rs
src/git.rs
src/models/version.rs
src/views.rs

This PR prepares for `semver` v1.x no longer having a `diesel` feature, which would make it much more complicated for us to directly deserialize the SQL column into a `semver::Version` field. We can deserialize it to a `String` instead, and only parse it into a `semver::Version` on demand.

models::Version: Change `num` field to a plain `String`

---

src/controllers/category.rs
src/controllers/helpers/pagination.rs
src/controllers/keyword.rs
src/controllers/krate/metadata.rs
src/controllers/krate/search.rs
src/controllers/user/me.rs
src/tests/krate/search.rs

This PR implements seek-based pagination for parts of the `/api/v1/crates` endpoint, and adds the infrastructure to parse `seek=` parameters in paginated APIs. The reason for this PR is that we have multiple crawlers scraping the whole `/api/v1/crates` endpoint every day, and offset-based pagination is not feasible after a high number of pages.
To keep the implementation simple seek-based pagination is only supported for requests matching these constraints:
* **No filters:** when the request is filtered the total results count is not the same as the total number of crates, so the current implementation to gather the number of results (`SELECT COUNT(*) FROM crates;`) does not work. This can be lifted in the future by refactoring how we gather the total number of results.
* **No sorting …

Implement seek-based pagination for filterless sortless crates endpoint

---

ember-cli-build.js

see https://github.com/simplabs/ember-test-selectors/pull/721

ember-test-selectors: Disable obsolete/deprecated `Component.reopen()` call

---

src/models/team.rs
src/tests/http-data/team_add_renamed_team
src/tests/team.rs

This should fix #2957 and fix #2687, as I understood these bugs.
I made the changes as I thought I understood the project design, but I'm happy to implement any changes that will get this to match standards and design. 
IMHO the change from checking `login` to checking `github_id` only is fine. We always get current data from github for the name that the user requested to add. And there we always get the id from github and can treat it as PK. 
The change to `crates_by_team_id_not_including_deleted_owners` is needed because the `github:crates-test-org:core`  now is not allowed to be created with a new, different ID, which it would get from `new_team`

fix server error when adding renamed github team as owner

---

Cargo.lock
Cargo.toml
src/bin/server.rs
src/config.rs
src/lib.rs
src/metrics/instance.rs
src/metrics/log_encoder.rs
src/metrics/mod.rs
src/tests/util/test_app.rs

This commit implements support for [`crates-io-heroku-metrics`][1] by logging all the instance-level metrics on stdout periodically, allowing the tool to scrape them from the logs. This will finally enable us to collect instance-level metrics on Heroku! :tada: :tada: :tada: 
Support for this on the `crates-io-heroku-metrics` side is implemented in https://github.com/rust-lang/crates-io-heroku-metrics/pull/1 (no need for the crates.io team to review it, I will merge it once this PR is deployed). Note that support for logging histograms is not implemented in this PR, but we aren't using histograms right now anyway. I'll implement histograms support once this PR is merged.
We'll also want to configure Papertrail to filter out log lines starting with `crates-io-heroku-metrics:ingest`.
[1]: …

Add support for logging instance-level metrics to stdout

---

.template-lintrc.js
app/components/footer.module.css
app/components/header.hbs
app/components/header.module.css

This PR removes the `width-limit` from the header and footer on all pages. This will allow us to use wider layouts in the future for certain pages that would benefit from having more space (e.g. crate details page).
The PR also refactors the `Header` component at the same time to use a CSS grid to get rid of the duplicate search form.

Use full page width for `Header` and `Footer` components

---

src/downloads_counter.rs
src/metrics/instance.rs
src/metrics/log_encoder.rs
src/metrics/macros.rs
src/metrics/mod.rs
src/middleware/update_metrics.rs

Now that we have support for collecting metrics this PR adds the following ones:
* `response_times`: how long preparing responses take, grouped by endpoint. Note that this does not create a metric series for each visited URL: for example all the downloads will be counted as `/crates/:crate_id/:version/download`.
* `responses_by_status_code_total` how many responses we sent, grouped by HTTP status code.
* `downloads_not_counted_total` how many download counts aren't persisted yet.
This also had to implement histograms support, needed by `response_times`.

Add more instance-level metrics

---

Cargo.lock
Cargo.toml
src/controllers/krate/publish.rs
src/models/version.rs

This PR updates the `semver` crate to the new v1.0.0 release, which is basically a complete rewrite. The `diesel` feature no longer exists, but due to #3650 we don't need it anymore.
Closes https://github.com/rust-lang/crates.io/pull/3338

Update `semver` to v1.x

---

Cargo.lock

The compilation error is a known regression related to a soundness fix.
The latest git2 avoids the error. See also
https://github.com/rust-lang/rust/issues/85574#issuecomment-847227106
r? @Turbo87

Upgrade git2 to fix compliation on nightly

---

.buildpacks

This bumps from nginx 1.18.0 to 1.20.1. This fixes a CVE that should
not affect our configuration, as we do not use the "resolver"
directive. From the nginx release log:
> Security: 1-byte memory overwrite might occur during DNS server
> response processing if the "resolver" directive was used, allowing an
> attacker who is able to forge UDP packets from the DNS server to
> cause worker process crash or, potentially, arbitrary code execution
> (CVE-2021-23017).
r? @Turbo87

Bump to the latest stable nginx

---

src/metrics/log_encoder.rs

Heroku has a limit for log lines of 10,000 bytes, and when a line reaches that size the platform will automatically split it into multiple lines, breaking the tooling reading it.
To avoid that problem when outputting metrics, this commit implements the splitting on the application side when a line is longer than 5,000 bytes. The threshold is just 5,000 because the newline is inserted *after* the item that made the line too long, so it's possible that the actual lines will be longer than 5,000 bytes.
Fixes #3689.

Split logged instance metrics into multiple lines when necessary

---

src/metrics/log_encoder.rs

Turns out that the data model used by Lua transforms is different than the data model used for the rest of Vector.
r? @jtgeibel

Fix vector.dev's histograms representation

---

mirage/factories/crate.js
mirage/route-handlers/crates.js
mirage/serializers/crate.js
mirage/serializers/dependency.js
mirage/serializers/version.js
tests/acceptance/crate-dependencies-test.js
tests/acceptance/crate-navtabs-test.js
tests/acceptance/crate-test.js
tests/acceptance/search-test.js
tests/adapters/crate-test.js
tests/mirage/crates-test.js
tests/mirage/me-test.js
tests/models/crate-test.js
tests/models/version-test.js
tests/routes/crate/version/crate-links-test.js
tests/routes/crate/version/docs-link-test.js

The `id` is rarely used and exposed on the API, but there are a few cases where it is indeed used. The `id` is meant to be a `i32` though, so having it equal to the `name` of the crate was wrong. This PR fixes the issue by having the `id` as a regular numeric ID and using `name` everywhere else.
This PR is a prerequisite for implementing `crate-owner-invitation` support into our mirage setup.

mirage: Untangle `crate.id` and `crate.name`

---

docs/CONTRIBUTING.md

Fix wrong label name and link

---

mirage/factories/crate-owner-invitation.js
mirage/models/crate-owner-invitation.js
mirage/models/crate-owner-invite.js
mirage/route-handlers/me.js
mirage/serializers/crate-owner-invitation.js
tests/acceptance/invites-test.js
tests/acceptance/token-invites-test.js
tests/mirage/invitations-test.js

This should simplify implementing https://github.com/rust-lang/crates.io/issues/2868 in the future :)

mirage: Implement `crate_owner_invitations` endpoints

---

.github/workflows/ci.yml
src/admin/migrate.rs
src/app.rs
src/bin/crates-admin.rs
src/controllers/crate_owner_invitation.rs
src/controllers/krate/search.rs
src/controllers/user/session.rs
src/controllers/util.rs
src/controllers/version.rs
src/downloads_counter.rs
src/email.rs
src/git.rs
src/metrics/log_encoder.rs
src/models/krate.rs
src/models/version.rs
src/render.rs
src/s3/lib.rs
src/tasks/update_downloads.rs
src/tests/category.rs
src/tests/krate/publish.rs
src/tests/krate/yanking.rs
src/tests/owners.rs
src/tests/server_binary.rs
src/tests/token.rs
src/tests/user.rs
src/tests/util.rs
src/tests/util/fresh_schema.rs
src/tests/util/test_app.rs
src/util/token.rs

This addresses warnings identified by clippy. Some of these warnings are currently generated on stable, but a missing environment variable caused those warnings to be logged but not to fail the build. The next to last commit fixes this.
This final commit pins to 1.52.1 for linting, until a compiler ICE in 1.53.0 is addressed. I've just [reported] this ICE against the pre-release, but it may be too late to address in 1.53.0.
r? @Turbo87 
[reported]: https://internals.rust-lang.org/t/1-53-0-prerelease-testing/14884/2?u=jtgeibel

Address clippy findings

---

src/app.rs
src/background_jobs.rs
src/bin/enqueue-job.rs
src/bin/server.rs
src/db.rs
src/git.rs
src/lib.rs
src/middleware/app.rs
src/middleware/block_traffic.rs
src/middleware/head.rs
src/middleware/require_user_agent.rs
src/middleware/static_or_continue.rs
src/render.rs
src/util/request_proxy.rs

The lib crate is only used by other in-tree crates. Therefore if Debug
or Copy impls are ever needed, they can be easily added.
82 unused Debug impls are then dropped. This probably has a slight but
negligible improvement to compile/link times.
r? @Turbo87

Cleanup unneeded lints and drop unused Debug impls

---

app/components/crate-header.hbs

`crate.owners` redirects to `crate.settings` these days, so the "Settings" tab would never receive the "active" state with the current implementation.

CrateHeader: Link to `crate.settings` so that tab gets "active" state

---

app/models/team.js

`@attr` is auto-tracked these days, so the getters recompute fine when things change

models/team: Convert computed properties to plain getters

---

mirage/factories/team.js
mirage/serializers/team.js
tests/acceptance/settings-test.js

The fixtures are inconsistent, slow and hard to maintain. We can create only what we need instead, similar to how we already do it in plenty of other test cases.

tests/settings: Replace `loadFixtures()` calls

---

src/admin/migrate.rs
src/admin/render_readmes.rs
src/app.rs
src/bin/background-worker.rs
src/bin/server.rs
src/config.rs
src/config/base.rs
src/config/database_pools.rs
src/controllers/krate/metadata.rs
src/controllers/krate/publish.rs
src/controllers/version/downloads.rs
src/lib.rs
src/middleware.rs
src/models/crate_owner_invitation.rs
src/router.rs
src/tests/authentication.rs
src/tests/util.rs
src/tests/util/test_app.rs

This commit series begins refactoring the loading of configuration settings from environment variables. Unlike the main server binary, most binaries just need access to the database, and sometimes S3.
There are still some modules that access the environment directly (such as `app`, `emails`, `git`, some middleware, etc.). This should lay the groundwork for future consolidation of this logic under the `config` module.
r? @Turbo87

Begin refactoring configuration module

---

package.json
yarn.lock

https://github.com/rust-lang/crates.io/pull/2403 removed the usage of the `is-pending` template helper, so this dependency is no longer used in our app! 🎉

Remove unused `ember-promise-helpers` dependency

---

package.json
yarn.lock

All of our target browsers these days support generator functions natively
see https://caniuse.com/es6-generators
As a side effect, this gets rid of our last ember-cli-babel v6 dependency 🚀

Remove obsolete `ember-maybe-import-regenerator` dependency

---

app/routes/crate/settings.js

This still does not check whether the authenticated user is sufficiently privileged to perform any actions on the page, but at least it prevents unauthenticated users from accessing the page.

crate/settings: Ensure that only authenticated users can visit the route

---

tests/acceptance/settings/add-owner-test.js
tests/acceptance/settings/remove-owner-test.js
tests/acceptance/settings/settings-test.js

The test module was getting a bit long and hard to follow, and with some of the upcoming changes to the route it would become even longer. This PR splits the module into three dedicated files.

tests: Split `settings` test suite into multiple files

---

src/bin/enqueue-job.rs
src/git.rs

This adds a background job that squashes the index into a single commit.
The current plan is to manually enqueue this job on a 6 week schedule,
roughly aligning with new `rustc` releases. Before deploying this, will
need to make sure that the SSH key is allowed to do a force push to the
protected master branch.
This job is derived from a [script] that was periodically run by the
cargo team. Relative to the original script, the push of the snapshot
branch is no longer forced. The job will fail if run more than once on
the same day. (If the first attempt fails before pushing a new root
commit upstream, then retries should succeed as long as the snapshot
can be fast-forwarded.)
[script]: https://github.com/rust-lang/crates-io-cargo-teams/issues/47#issuecomment-506236036

Add a background job for squashing the index

---

src/git.rs

I've tested this locally with by running `GIT_REPO_URL=https://github.com/rust-lang/crates.io-index cargo run --bin background-worker` and then verifying that the repo in `/tmp/git*/` contained only the master branch and its history.
Fixes: #3630

Fetch only the master branch when cloning the index

---

src/metrics/macros.rs
src/metrics/mod.rs

This should hopefully improve the accuracy of our download metrics and should stop reporting most of the downloads as taking more than 2ms (most download requests finish processing in around 1ms).

Improve metrics accuracy

---

src/app.rs
src/controllers.rs
src/controllers/version/downloads.rs
src/db.rs
src/metrics/instance.rs
src/middleware/log_request.rs

This PR adds more histograms to the metrics we collect, exposing information that could be useful when we get paged. Two metrics were added:
* `cratesio_instance_database_time_to_obtain_connection`: how long it takes to obtain a database connection
* `cratesio_instance_downloads_select_query_execution_time`: how long the `SELECT` in the download endpoint takes
A side effect of this is that `TimingRecorder` is not needed anymore: we used it to measure those two things, appending them in the logs for slow requests, but now that we have metrics there is no need to have it. If we need to measure more timings in the future we can just add more histograms. This PR thus removes `TimingRecorder` from the codebase.
r? @jtgeibel or @Turbo87
This can be reviewed commit-by-commit.

Add more histograms

---

src/controllers/token.rs
src/router.rs
src/tests/token.rs

Add `DELETE /tokens/current` endpoint

---

src/middleware/log_request.rs

The request ID is provided to the user in a few error cases to help us
locate the log line. However, the ID is not provided to the user for
successful requests in general, and in particular for download requests
that make up the vast majority of our traffic.
Removing this from the logs will save 48 bytes in log traffic per
download, and should reduce our log output by about 15%.

Avoid logging request_id for successful download redirects

---

.env.sample

Fix typo in env sample: github -> GitHub

---

src/git.rs

https://github.com/rust-lang/rust/pull/87671 added a warning when backslash continuations eat multiple lines. This uncovered that the message for squashing the index was missing some blank lines. This adds some newlines to silence the warning and fix the message formatting.

Fix squash message warning.

---

src/tests/account_lock.rs
src/tests/authentication.rs
src/tests/krate/dependencies.rs
src/tests/krate/publish.rs
src/tests/krate/search.rs
src/tests/krate/yanking.rs
src/tests/owners.rs
src/tests/team.rs
src/tests/token.rs
src/tests/user.rs
src/tests/util/response.rs

Signed-off-by: hi-rustin <rustin.liu@gmail.com>
r? @jtgeibel

Rename the json method of Response to into_json

---

src/controllers/crate_owner_invitation.rs
src/controllers/helpers/pagination.rs
src/router.rs
src/tests/owners.rs
src/views.rs

The endpoint provides a listing of all the invitations sent to the current user or all the invitations to a crate the user owns. Unauthenticated users or unrelated users won't be able to see others' invitations to prevent abuses.
The two ways to query the endpoint are:
GET /api/private/crate-owner-invitations?crate_name={name}
GET /api/private/crate-owner-invitations?invitee_id={uid}
The endpoint is paginated using only seek-based pagination, and the next page field is provided when more results are available.
Once the frontend switches to use the new endpoint we can remove safely remove the old "v1" endpoint, as that's only used for the frontend. Because of this, the "v1" endpoint internally uses the same logic as the new one and converts the data to the old schema.
Part of #2868 
r? …

Add the `/api/private/crate-owner-invitations` endpoint 

---

src/app.rs
src/db.rs
src/metrics/histogram.rs
src/metrics/instance.rs
src/metrics/macros.rs
src/metrics/mod.rs

While looking at the metrics, me and @jtgeibel noticed that the way we tracked used database connections before (sampling the current state every time metrics are scraped) is not really accurate, as the connections could be all used up until the scrape happens. This PR adds another metric recording the used database connections with an histogram.
This PR also refactors how histograms are defined in the source code, to account for different histograms needing different buckets.

Track used database conns with an histogram

---

ember-cli-build.js

see https://github.com/simplabs/ember-test-selectors/pull/764

test-selectors: Remove obsolete `patchClassicComponent` option

---

app/components/footer.hbs
app/components/footer.module.css

close https://github.com/rust-lang/crates.io/issues/3129

Add a link to report an Issue

---

config/targets.js

Resolves https://github.com/rust-lang/crates.io/issues/3838 by explicitly adding "Chrome 77" to our browser targets list for now.
/cc @zkat

Fix "Edge for Android" compatibility

---

.github/workflows/ci.yml

Running `rustc -V` before we install a different version clearly doesn't make a lot of sense 😅

CI: Install Rust before performing `rustc -V` call

---

src/controllers/crate_owner_invitation.rs

The compiler already knows that we want a `Vec<EncodablePublicUser>` so we can use `.into()` instead :)

controllers::crate_owner_invitation: Simplify `users` assignment

---

script/create-diff-link.sh

Replacement for https://github.com/rust-lang/crates.io/pull/3835 and symbiotic with https://github.com/rust-lang/crates-io-ops-guide/pull/4 :)

Add `create-diff-link.sh` script 

---

docs/ARCHITECTURE.md

Remove TODO and add EditorConfig plugins.

Add EditorConfig plugins

---

src/controllers/crate_owner_invitation.rs
src/router.rs
src/tests/owners.rs

... because the rest of the API also uses underscores
Addresses https://github.com/rust-lang/crates.io/pull/3763#discussion_r692235370 :)

Rename `GET /api/private/crate-owner-invitations` to `GET /api/private/crate_owner_invitations`

---

Cargo.lock
Cargo.toml
src/bin/server.rs

This reverts commit 43ac758c4575f49ae853712f6d75a03bdea898c1.
Using `tracing_subscriber::fmt::layer()` disabled the `RUST_LOG` based env filter. But if we add the filter to the registry it basically disables the breadcrumb tracing for Sentry. https://docs.rs/tracing-subscriber/0.2.20/tracing_subscriber/layer/trait.Layer.html#filtering-with-layers has more information on this. Until we find a way to filter what the `fmt` subscriber prints without disabling the breadcrumbs for Sentry we should probably not use their `tracing` integration.

Revert "sentry: Enable `tracing` feature"

---

src/render.rs

I was not sure that the `align` properly was supported for images, so I extended the `render.rs` tests to convince me that it indeed worked as intended.
Below is the commit message:
```
render: add HTML image tests with align support
The current align test was only used for text, but we want to be sure
that images can be aligned too. This is why a new test is added to
verify that the align attribute is also kept for images.
Since the align attribute requires RAW HTML for the <img> tag, the
relative_links test has also been updated to check for this usage.
```

render: add HTML image tests with align support

---

src/controllers/user/me.rs

This fix came up when running clippy with nightly. (I was using default nightly toolchain on my machine).
I noticed CI runs with stable clippy - and I added a commit to switch back to continually using stable clippy, as the comment seemed to imply that's what you wanted. I'd understand if you'd want to keep it pinned - let me know and I'll revert the change to ci/

Clippy fixes

---

mirage/serializers/crate-owner-invitation.js
tests/mirage/me/crate-owner-invitations/list-test.js

https://github.com/rust-lang/crates.io/pull/3763 changed a few minor things about the crate owner invitations responses. This PR adjusts our mirage code to match these changes (excluding pagination).

mirage/crate-owner-invitation: Adjust fake API to match the real API

---

Cargo.lock

Our production servers are currently showing what looks like a memory leak, that started after merging a20c3ea. This PR updates the locked dependencies again, in the hope that it fixes the leak through an upstream fix. If this does not work we might have to consider reverting this PR and a20c3ea. Unfortunately we have not yet been able to pinpoint the problematic dependency.

Update locked cargo dependencies

---

src/config.rs
src/controllers/version/downloads.rs
src/tests/krate/downloads.rs
src/tests/util/test_app.rs

This PR adds a new environment variable, `FORCE_UNCONDITIONAL_REDIRECTS`, which forces unconditional redirects even with a fully healthy database. The environment variable is meant to be used by an on-call operator to reduce the database load when the primary database is overloaded, and should only be set during incidents.

Add `FORCE_UNCONDITIONAL_REDIRECTS`

---

src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/helpers.rs
src/controllers/keyword.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/search.rs
src/controllers/site_metadata.rs
src/controllers/team.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/session.rs
src/controllers/version/deprecated.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/util/errors/json.rs

see https://docs.serde.rs/serde_json/macro.json.html
I guess `+132 −349` speaks for itself 😅

Use `json!` macro to simplify JSON serialization code

---

src/util/errors.rs

Instead of implementing `Error` and `Display` ourselves we can rely on https://github.com/dtolnay/thiserror to derive them for us.

errors: Derive `Error` (and `Display`) for `AppErrToStdErr`

---

src/controllers/krate/downloads.rs

Fix some typo and inaccurate documentation where version specific download counts should be in `version::downloads` instead of `krate::downloads` (which is the current file)

Update documentation on krate::downloads controller

---

src/render.rs

The image test is actually not representative and will not center the image. This fix helps users discover how to center images and proves that they will be centered on crates.io.
Note: I am the original author of this testcase from PR #3862

render: fix center image test

---

Cargo.toml
src/s3/Cargo.toml

see https://doc.rust-lang.org/cargo/reference/features.html#feature-resolver-version-2
It doesn't make a difference for us right now, but I guess we should move to the new resolver instead of staying behind on the old one for no reason :)

Cargo: Use v2 resolver

---

app/styles/application.module.css

Since Fira Sans is used across crates.io, it makes sense to use Fira Mono for monospaced text to increase consistency. After Fira Mono there is now `ui-monospace` in the font stack, which renders as SF Mono on Safari without having to manually install SF Mono. `ui-monospace` [is part of](https://www.w3.org/TR/css-fonts-4/#ui-monospace-def) the CSS Fonts Module Level 4 draft.

Match monospace font with main font

---

src/middleware/known_error_to_json.rs
src/tests/all.rs
src/tests/not_found_error.rs

We don't care about the exact implementation details (middleware), but we do care that we get a 404 error with JSON payload back. This will make it easier to refactor the implementation in the future.

KnownErrorToJson: Replace unit test with acceptance test

---

src/middleware/log_request.rs

We are currently only using `at=error` for cases where the route handler did not explicitly return a 5xx status code, but we should probably use it for all cases where 5xx is returned. This PR changes the code to achieve that.

LogRequest: Use `at=error` for all 5xx status code responses

---

src/tests/unhealthy_database.rs
src/util/errors.rs
src/util/errors/json.rs

Resolves https://github.com/rust-lang/crates.io/issues/1386
I'm not sure how to write a proper test for this unfortunately, but I've manually verified that this works as intended.

Cast `PoolError::UnhealthyPool` into `503 Service Unavailable` error

---

src/render.rs

Added unit tests to confirm things work.
Manually tested end to end and confirmed that the rendered
page has a properly working relative link as long as the Cargo.toml
is in the root of the repo.
We'll need to update cargo as mentioned in #3484 in order to
support Cargo.toml that aren't in the root of the repo

Leverage readme_path to support relative paths from readme's not at root

---

renovate.json

`reviewers` is enough, we don't need `assignees` too

renovatebot: Remove `assignees` from pull requests

---

Cargo.lock
Cargo.toml
src/tasks/dump_db/dump-export.sql.hbs
src/tasks/dump_db/dump-import.sql.hbs

see https://github.com/sunng87/handlebars-rust/blob/master/CHANGELOG.md
~It looks like none of the breaking changes in the v4 release are relevant to us.~
Update: I was wrong, https://github.com/sunng87/handlebars-rust/pull/404 does affect us. I've added another commit which removes the now problematic handlebars whitespace control characters.

Update `handlebars` crate to v4.1.3

---

app.json
src/app.rs
src/config/database_pools.rs
src/middleware.rs
src/tests/server_binary.rs

This PR splits the existing environment variables `DB_POOL_SIZE` & `DB_MIN_IDLE` into separate variables to provide different connection settings to the primary & replica databases. The main reason for this change is to be able to configure different values for both database pools.
The new env variables are:
* `DB_PRIMARY_POOL_SIZE` & `DB_REPLICA_POOL_SIZE` to configure the number of connections in the primary & replica pool
* `DB_PRIMARY_MIN_IDLE` & `DB_REPLICA_MIN_IDLE` to set the number of idle connections each pool at least maintains
* update descriptions of env vars.
**Note** the descriptions of the `*_POOL_SIZE` variables in `app.json` are most likely off & need correct wording.

Split DB_POOL_SIZE & DB_MIN_IDLE environment variables

---

src/tasks/dump_db.rs
src/tasks/dump_db/gen_scripts.rs

This was helpful when working on #3912 :)

tasks::dump_db: Add debug logging

---

src/admin/render_readmes.rs
src/markdown/lib.rs
src/render.rs

This module can be used for any kind of markdown file, not just `README.md` files :)

markdown: Remove `README` references

---

src/markdown/lib.rs

This PR adjusts the doc comment of the `readme_to_html()` function by adding an assertion for the `rendered` result.

markdown: Add output assertion to the doc test

---

src/bin/server.rs
src/lib.rs
src/sentry.rs

This will allow us to more easily enable Sentry error reporting for the other binaries too.

Extract Sentry initialization code into dedicated function

---

src/controllers.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/session.rs
src/controllers/util.rs
src/router.rs
src/uploaders.rs
src/util/errors.rs

The `chain_error()` function can be replaced by `ok_or_else()` (for `Option`) or `map_err()` (for `Result`), which makes the intent a little clearer, and removes one of the layers of indirection from our error handling, without being significantly more verbose.
Please note that this only removes the `ChainError` **trait**, but the `ChainedError` **struct** still exists.

Remove `ChainError` trait

---

src/bin/monitor.rs
src/controllers/krate/downloads.rs
src/controllers/krate/search.rs
src/controllers/user/other.rs
src/lib.rs
src/models/category.rs
src/models/keyword.rs
src/models/krate.rs
src/models/owner.rs
src/publish_rate_limit.rs
src/sql.rs

This seems a bit more organized compared to having them scattered all over the place.

Extract `sql` module with all custom `sql_function!()` calls

---

package.json
yarn.lock

https://github.com/ember-cli/broccoli-asset-rev/issues/29 can in some cases cause SRI failures. specifically, when file A depends on file B depends on file C, and file C changes, then the fingerprinting in file A and file B might not change, even though the injected filename of file C has changed, which leads to a fingerprint collision, which results in a user-visible SRI failure.
Disabling SRI is certainly not perfect, but it's better than having a broken site every now and then without any way to resolve it.

Remove `ember-cli-sri` addon temporarily

---

Cargo.lock
src/markdown/Cargo.toml

see https://github.com/kivikakk/comrak/releases
This does not appear to contain any significant changes for us, but it prevents `cargo outdated` from complaining 😆

Update `comrak` to v0.12.1

---

src/config.rs
src/router.rs
src/tests/all.rs
src/tests/blocked_routes.rs
src/tests/util/test_app.rs
src/util/errors.rs
src/util/errors/json.rs

This PR adds the `BLOCKED_ROUTES` environment variable, which allows to block individual routes through the environment. This is going to be useful during incident response if we need to block an individual route (for example if the route is degrading the performance of the database), as it would remove the need to deploy an hotfix to disable that route.
r? @jtgeibel

Add `BLOCKED_ROUTES` environment variable

---

script/import-database-dump.sh

This PR adds a small bash script which downloads the current database dump and imports it into a local `cargo_registry` database. This can be useful for e.g. trying out database queries with production data.

Implement basic `import-database-dump.sh` script

---

Cargo.lock
Cargo.toml

Changes between 0.12.0 and 0.13.0: https://github.com/tikv/rust-prometheus/compare/v0.12.0...v0.13.0
This shouldn't affect our codebase.

Update `prometheus` to 0.13.0

---

Cargo.lock
Cargo.toml
cargo-registry-markdown/Cargo.toml
cargo-registry-markdown/lib.rs
src/admin/render_readmes.rs
src/render.rs

This is consistent with `cargo-registry` and `cargo-registry-s3`.
We could also consider renaming `cargo-registry-s3` to `cio-s3` to make the name shorter, but as long as the main package is called `cargo-registry` I guess we should us that as the prefix for the other packages too.

Rename `cio-markdown` package to `cargo-registry-markdown`

---

src/admin/render_readmes.rs

Depends on #3967
(Because of https://github.com/github/feedback/discussions/4477#discussioncomment-1293255 - github ends up rendering both diffs together. Go to the commits tab and just look at the most recent commit to review).
Refactors slightly so we can add tests to the untested risky portion of this code.
I already found a couple of bugs which I will fix in follow up PRs with tests.

Add tests for admin/render_readmes

---

Cargo.lock
Cargo.toml
src/bin/server.rs

https://github.com/tokio-rs/tracing/releases/tag/tracing-subscriber-0.2.21 enables us to use per-layer event filters, which previously blocked us from using the `tracing` feature of `sentry`. This PR enables the feature using the default configuration, which reports all `error!()` usages as errors and `warn!()` and `info!()` as breadcrumbs for associated errors.

sentry: Enable `tracing` feature

---

src/admin/render_readmes.rs

Depends on #3969
(Because of github/feedback#4477 (comment) - github ends up rendering both diffs together. Go to the commits tab and just look at the most recent commit to review).
https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field

Support admin render_readme with Cargo.toml without optional readme field

---

src/tests/git.rs

Different versions of git2 in different systems use a different name for
the HEAD branch they create, switching between "master" and "main". This
causes test failures when they pick "main", as the rest of crates.io
assumes the branch is named "master".
This commit changes the HEAD name during tests to always be "master",
allowing the test suite to work everywhere without breakages.
Refactoring the application not to care about the branch name will be
done in a future commit, this just focuses on unbreaking the test suite.

Ensure the HEAD for test indexes is "master"

---

src/admin/on_call.rs

The fields in the `InvalidEvent` struct are used by the `Debug` implementation, which is used by the `anyhow!()` macro call in the `Event::send()` implementation.
The Rust v1.57.0-beta.1 compiler does not appear to agree on that though and marks these fields as unused. This PR adds `#[allow(dead_code)]` to work around the issue for now and fix our CI builds to unblock other updates.

admin::on_call: Work around potential Rust v1.57.0-beta.1 bug

---

app/controllers/dashboard.js
app/controllers/index.js
app/controllers/search.js
app/models/user.js
app/routes/categories.js
app/routes/category-slugs.js
app/routes/category.js
app/routes/category/index.js
app/routes/crate.js
app/routes/crate/reverse-dependencies.js
app/routes/crates.js
app/routes/dashboard.js
app/routes/keyword.js
app/routes/keyword/index.js
app/routes/keywords.js
app/routes/me/crates.js
app/routes/me/following.js
app/routes/me/index.js
app/routes/me/pending-invites.js
app/routes/team.js
app/routes/user.js

The implicit injection in routes and controllers has been deprecated

Explicitly inject the `store` service

---

.github/renovate.json

Using `groupName` for this was incorrect and did not update the PR title in the dependency dashboard. This PR uses the `commitMessageSuffix` option instead, and also `additionalBranchPrefix` to avoid conflicting branch names.

renovate: Adjust lockfile maintenance configuration

---

.github/renovate.json

With this PR we will have renovatebot open a PR whenever a new Rust version is released. It will update the version in `RustConfig` (used by the Heroku buildpack) and the `RUST_VERSION` environment variable in the CI config, once #4101 is merged.
Example:
- https://github.com/Turbo87/crates.io/pull/29
Related:
- https://fasterthanli.me/articles/my-ideal-rust-workflow ("Automating dependency updates" section)

renovate: Update `RustConfig` and `RUST_VERSION` in CI config automatically

---

.github/workflows/ci.yml

This adds `continue-on-error: true` for the `beta` channel, and pins the `stable` channel to the version that we use in production.

CI: Adjust Rust channels

---

src/middleware/log_request.rs

The `request.id` tag and the "custom metadata" are currently only assigned to the Sentry scope in the `after()` method of the `LogRequest` middleware. This means that for any manual `sentry::capture_exception()` call these fields will not be set correctly.
This PR moves the `configure_scope()` calls into the `before()` method and `add_custom_metadata()` function instead. This allows us to send the fields to Sentry for error reports as soon as they are available.

Sentry: Improve metadata collection

---

src/admin/render_readmes.rs
src/bin/crates-admin.rs

... instead of dropping the errors via `Option` and using `panic!()` everywhere.
/cc @nipunn1313

admin::render_readmes: Use `Result` return types

---

src/middleware.rs
src/middleware/log_request.rs
src/middleware/response_timing.rs

This is generic and not strictly related to the `LogRequest` middleware. The `UpdateMetrics` middleware should probably also use this in the future.

middleware::log_request: Split request timing code into dedicated middleware

---

Cargo.lock
Cargo.toml
src/lib.rs

`jemallocator` appears to be unmaintained and [`tikv-jemallocator`](https://github.com/tikv/jemallocator) is a friendly fork that has taken over maintenance.

Replace `jemallocator` with `tikv-jemallocator`

---

src/middleware/log_request.rs
src/middleware/normalize_path.rs

The `NormalizePath` middleware is the one that mutates the `path`, so it should also be responsible for saving the original one, if necessary.
This PR slightly changes the logic in that `OriginalPath` is only added to the request extensions if the path has been changed. The `NormalizePath` middleware now defaults to `request.path()`, if `OriginalPath` is not found in the request extensions.

middleware::log_request: Move `OriginalPath` code into `NormalizePath` middleware

---

.github/renovate.json

This should avoid multiple incompatible PRs from being opened.

renovate: Group `conduit` package updates into one PR

---

.github/renovate.json

This appears to not work as intended and is not really necessary anyway.

renovate: Remove `matchDatasource` from `conduit` grouping rules

---

src/app.rs
src/controllers/version/downloads.rs
src/tests/krate/downloads.rs

This adds a caching layer in the app backend to reduce the number of
database queries. While this query is extremely fast, a massive number
of concurrent download requests can still result in a request backlog.
In this implementation cached values are never dropped. This means
that memory usage will grow over time, however the memory usage is
expected to be well within our instance size and the application is
automatically rebooted at least once every 24 hours. Additionally, on
the rare occasion that a crate version is deleted, the cache will
continue to serve redirects and attempt to record download counts for
that version.
If a version is deleted and continues to see download requests, it is
expected that the entire shard of downloads containing that version_id
will fail to persist. …

Cache the version_id for download requests

---

Cargo.lock
Cargo.toml
src/app.rs
src/config.rs
src/controllers/version/downloads.rs
src/metrics/instance.rs
src/tests/krate/downloads.rs
src/tests/util/test_app.rs

This PR builds on top of https://github.com/rust-lang/crates.io/pull/3848, but uses https://github.com/moka-rs/moka instead of https://github.com/xacrimon/dashmap for caching the `version_id` in the `download` API endpoint. I've implemented it using environment variables and default values that will allow us to fine tune the values in production, if necessary.

Implement `version_id` cache for `download` endpoint using `moka` crate

---

src/metrics/service.rs

This can be used to monitor how long the queue of background jobs currently is.

metrics/service: Add `background_jobs` metric

---

app/components/crate-sidebar.js
app/routes/application.js
app/services/playground.js

This avoids duplicate requests to the playground API, caused by the `preloadPlaygroundCratesTask` in the `application` route requesting the data after it has already been loaded by the `CrateSidebar` component too.

services/playground: Extract loadCrates() method

---

mirage/config.js
mirage/route-handlers/invites.js
tests/mirage/private/crate-owner-invitations/get-test.js

This will be needed to address https://github.com/rust-lang/crates.io/issues/4083

mirage: Implement `GET /api/private/crate_owner_invitations` route handler

---

.github/renovate.json
.github/workflows/ci.yml
frontend.Dockerfile
package.json

We currently use one Node.js version in production, another on CI and yet another one for our Docker setup. This PR pins them all to the same release (latest v14.x) and configures renovatebot to automatically keep the versions updated.

Pin Node.js version

---

.github/renovate.json5

This allows us to use trailing commas and, more importantly, comments in the increasingly complex config file.
see https://json5.org

renovate: Convert to JSON5 file

---

.github/renovate.json5

#4148 introduced a new way for renovatebot to update our Node.js version, but it wasn't perfectly compatible with the others yet. This PR fixes the issue, and unifies how renovatebot updates the Node.js versions in all of the relevant files.

renovate: Adjust `node` package grouping

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css
app/components/owners-list.hbs
app/components/owners-list.js
app/components/owners-list.module.css
app/models/crate.js
tests/acceptance/crate-test.js

This PR extracts a `OwnersList` component and then adjusts it to show a more detailed list if the number of owners is five or less.

CrateSidebar: Show detailed list for small number of owners

---

src/bin/server.rs
src/tests/server_binary.rs

This makes it easier to click on the URL instead of having to copy-paste the port.
I'm aware that the code comment says "Do not change this line!", but I've adjusted the corresponding test code too... 😉

bin/server: Print HTTP server URL on startup

---

app/components/owners-list.hbs
app/components/owners-list.module.css
app/components/version-list/row.module.css

This PR improves the styling of the avatars in the crate owners list and the versions list. It adds a small border and drop shadow to give them a little more depth, and it also changes user avatars to circles (vs teams, which stay rectangular), similar to how GitHub does it these days.

Improve Avatar styling

---

src/controllers/version/yank.rs
src/worker/git.rs

When publishing, we also save the new version (and crate) directly in the database, so we should be able to do the same when yanking/unyanking, and avoid potentially returning incorrect data right after the request and before the background job has finished.

worker::git: Move database update out of `yank()` job

---

app/sentry.js

This is based on https://dzone.com/articles/6-tips-for-reducing-javascript-error-noise and filters out errors from e.g. broken browser extensions. It ensures that we only report errors that originate in the scripts served by our own servers.

sentry: Use `allowUrls` option to filter out errors in injected scripts

---

src/bin/server.rs

This PR replaces two conditional assignments with `match` assignments to make the code a little less verbose. Semantically these instructions should be identical.

bin/server: Simplify assignments via `match`

---

src/git.rs
src/tests/krate/publish.rs
src/tests/krate/yanking.rs
src/tests/util/test_app.rs
src/worker/git.rs

We can calculate the `path` automatically from the `crate_name`. There is no need for us to manually specify it in the tests.

TestApp: Simplify `crates_from_index_head()` method

---

src/controllers/version/yank.rs
src/worker/git.rs
src/worker/mod.rs

This PR implements one part of https://github.com/rust-lang/crates.io/issues/4172. By no longer passing `yanked` into the `yank` (now `sync_yanked`) background worker task, and instead reading `yanked` from the database, we can avoid issues from tasks running out of order.

worker::git: Read `yanked` status from database 

---

app/controllers/catch-all.js
app/routes/catch-all.js
app/routes/crate.js
app/routes/crate/version.js
app/templates/catch-all.hbs
tests/acceptance/404-test.js
tests/acceptance/crate-test.js
tests/routes/crate/version/model-test.js

Instead of redirecting back to a known URL and showing a notification message, we now stay on the requested URL and show an error page instead.
(though with "Crate/Version not found" instead)
The implementation is a little questionable, but due to the way the `error` substates in Ember.js work I've found no other way to implement this.
This PR is based on #4154.

Show 404 pages for unknown crates/versions

---

app/routes/category.js
app/routes/confirm.js
app/routes/crate/dependencies.js
app/routes/crate/docs.js
app/routes/crate/owners.js
app/routes/crate/range.js
app/routes/crate/repo.js
app/routes/crate/reverse-dependencies.js
app/routes/crate/version-dependencies.js
app/routes/keyword.js
app/routes/team.js
app/routes/user.js

These two methods on the `Route` base class are deprecated in favor of using the `router` service instead.

Fix `transitionTo()` and `replaceWith()` deprecations on routes

---

Cargo.toml
src/controllers/krate/owners.rs

They were disabled in 2014 for some unknown reason, but these days there is really no reason to have them disabled.

Cargo: Enable doctests again

---

package.json
yarn.lock

This is unfortunately required for Ember.js 4 compatibility. The `ember-data` version that we're relying on still uses `@ember/string@1`, which is not compatible with Ember.js 4. But we can't update `ember-data` (yet) due to a bug related to the `hasMany` implementation... :-/

Pin `@ember/string` dependency to v3.0.0

---

app/utils/license.js
tests/utils/license-test.js

related to https://github.com/rust-lang/crates.io/issues/2595

utils/license: Add support for parentheses

---

package.json
yarn.lock

see https://github.com/emberjs/ember-string/pull/309

Unpin and update transitive `@ember/string` dependency

---

app/controllers/index.js

Without this the `let promise = controller.fetchData();` will be invalid because the method does not return anything.

controllers/index: Fix `fetchData()` return value

---

app/models/version.js

This is needed for fastboot to work correctly, but also to correctly use the `fetch()` polyfill, if necessary.

models/version: Add missing `fetch` import

---

app/controllers/crate/version.js

The reference to the `HasManyArray` never changes, so the download graph is not rerendered with Ember Data v4. We pass the `content` value of the Promise into the component instead to fix this.

crate.version: Fix `downloads` alias

---

src/models/version.rs

related to:
- https://github.com/rust-lang/crates.io/issues/2595

Add tests for license expression validation

---

src/models/version.rs

There is no need for this trait bound since we only use the iterator once.

models/version: Remove unnecessary `Clone` trait bound

---

tests/helpers/index.js
vendor/qunit.css

This ensures that the checker board pattern is used in rendering tests, but application tests use the correct background from the `body` element.

Adjust application test background color

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

... and run that workflow only for pushes on the primary branch, instead of slowing down every single PR. Unless we make that coverage data more visible (e.g. using something like Codecov), it is probably not worth it to send 60% of the CI time of each PR just on the backend test coverage tracking, which somehow seems to escape the regular CI caches.

CI: Extract test coverage tracking into dedicated workflow

---

app/routes/me/index.js

As discussed on Discord, the `cargo login` command is showing links to https://crates.io/me to access the API tokens. Since that is probably more important than any other bookmarks and has backwards compatibility concerns this PR is changing the `/me` redirection to `/settings/tokens` (instead of `/settings` aka. `/settings/profile`).

Adjust `/me` redirection to `/settings/tokens`

---

Cargo.lock
Cargo.toml
src/models/version.rs

Resolves https://github.com/rust-lang/crates.io/issues/2595
tl;dr you can now use parenthesis (e.g. `X AND (Y OR Z)`) in license expressions. the custom `/` operator is still supported for now, though not directly compatible with the use of parenthesis.

Replace `license-exprs` crate with `spdx`

---

app/controllers/catch-all.js
app/styles/application.module.css
app/styles/catch-all.module.css
app/templates/catch-all.hbs

> Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'sha256-n1+BB7Ckjcal1Pr7QNBh/dKRTtBQsIytFodRiIosXdE='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
This PR fixes the above error, that is triggered from hitting the "Go back" link on e.g. https://crates.io/crates/jdfgkjsdfjksnd

catch-all: Fix broken "Go back" and "Reload" links

---

.github/renovate.json5

There is no real downside of having these PRs open automatically and whether or not we merge them is still our decision in the end.

renovate: Disable `dependencyDashboardApproval` option

---

app/controllers/catch-all.js
app/routes/-authenticated-route.js
app/styles/catch-all.module.css
app/templates/catch-all.hbs
tests/acceptance/dashboard-test.js
tests/acceptance/invites-test.js

Resolves https://github.com/rust-lang/crates.io/issues/3687
~Note that this is based on #4314 and includes those commits to avoid merge conflicts.~

Show "This page requires authentication" page for protected routes if unauthenticated

---

app/components/settings-page.module.css
app/components/settings/api-tokens.module.css
app/styles/breakpoints.css
ember-cli-build.js
package.json
yarn.lock

This PR adds the https://github.com/postcss/postcss-custom-media PostCSS plugin to the style pipeline and imports the default breakpoints from https://tailwindcss.com/docs/responsive-design to eventually consolidate all of our existing breakpoints.

Use `postcss-custom-media` plugin for breakpoints

---

app/components/header.hbs

The relevant links are now in the footer and everything else is already linked in "The Cargo Book", so there is no need for this dropdown in the header anymore.

Header: Remove obsolete "Docs" dropdown

---

src/git.rs

Repository: Add doc comments

---

src/git.rs
src/worker/git.rs

This PR extracts, simplifies and documents the code that temporarily writes the in-memory SSH key to the disk for consumption in `git push` when the index is squashed.

Repository: Extract `write_temporary_ssh_key()` function

---

src/git.rs
src/worker/git.rs

This new function makes it easier to run arbitrary `git` commands in the working folder of the local index clone. It was extracted from the `squash_index()` background worker tasks, which uses it to run `git push --force-with-lease`, which is not yet supported by the `git2` crate.
The main goal of this PR is to reduce the visibility of the `checkout_path` and `credentials` fields on the `Repository`, which outside code should ideally not have any access to.
Note that this includes the commits from and is based on #4363.

Repository: Extract `run_command()` function

---

app/helpers/set-theme.js
app/styles/application.module.css
app/templates/application.hbs
package.json
tests/helpers/index.js
vendor/qunit.css
yarn.lock

We can achieve the same thing with data attributes, with a bit less code :)

Replace `ember-set-body-class` addon

---

app/components/download-graph.js
tests/components/download-graph-test.js

The attempted fix (e2398df) for the breakage caused by the Ember Data v4 update (072394d) caused this property path to no longer be valid. This commit should fix the issue.
Resolves https://github.com/rust-lang/crates.io/issues/4373

DownloadGraph: Fix `extra` property access

---

mirage/route-handlers/-utils.js
mirage/route-handlers/categories.js
mirage/route-handlers/crates.js
mirage/route-handlers/keywords.js
mirage/route-handlers/me.js

This seems a bit more straight forward compared to the `withMeta()` function hiding what's being returned.

mirage: Replace `withMeta()` utility function with object spread operator

---

tests/acceptance/search-test.js

This should ensure to not break the functionality that was added in https://github.com/rust-lang/crates.io/pull/1543 when working on implementing https://github.com/rust-lang/crates.io/issues/491.

tests/search: Add test case for query parameter forwarding

---

src/git.rs
src/worker/git.rs

This makes it easier to provide additional context on some of these errors and ensure that the source error is correctly propagated.

Repository: Use `anyhow` errors as return types 

---

src/controllers/krate/publish.rs
src/git.rs
src/models/krate.rs
src/tests/builders/publish.rs
src/tests/http-data/krate_publish_features_version_2
src/tests/krate/publish.rs

This adds support for the new feature syntax described in [RFC 3143](https://rust-lang.github.io/rfcs/3143-cargo-weak-namespaced-features.html).  There are two new feature values that are allowed in the `[features]` table: weak dependencies (`foo?/feat-name`) and namespaced dependencies (`dep:bar`).  When these style of features are detected, they are placed in the index in a separate field called `features2` to prevent older versions of cargo from breaking on them. Additionally, it sets a new version field called `v` to indicate that this new field is present, which prevents versions starting at 1.51 from selecting those versions.

Add support for new feature syntax (RFC 3143)

---

app/components/crate-list.hbs
app/components/crate-list.module.css
app/controllers/search.js
app/models/crate.js
app/templates/search.hbs

Users know what they searched for and the exact result, if there is one, will always be the first result anyways, so this special highlighting does not have a particularly big benefit.
This also resolves https://github.com/rust-lang/crates.io/issues/3910 at the same time.

search: Show "Exact Match" as regular search result

---

app/controllers/crates.js
app/routes/crates.js
app/templates/crates.hbs

With over 70k crates it has become quite useless to filter the crates by their starting letter, so we might as well remove this feature to declutter the user interface a little bit.

Remove "Filter by letter" feature

---

src/tests/git.rs
src/tests/krate/publish.rs
src/tests/util/test_app.rs

This should encapsulate our mocked upstream index git operations a little bit better in the testing code.

tests: Extract `UpstreamIndex` struct

---

app/components/footer.module.css
app/components/radio-button.hbs
app/components/settings-page.hbs
app/components/settings-page.js
app/components/theme-preview.hbs
app/components/theme-preview.module.css
app/controllers/settings/appearance.js
app/router.js
app/services/design.js
app/styles/application.module.css
app/styles/settings/appearance.module.css
app/templates/application.hbs
app/templates/settings/appearance.hbs

Just like the "Toggle Design" button before, this route is only visible in development mode, or to be more precise: the link to this route is only visible in development mode, so that we can test this out in production too.
This should be seen as a first step towards implementing a "dark color scheme" mode (see https://github.com/rust-lang/crates.io/pull/3585), roughly inspired by how GitHub has implemented it in their user settings.

Replace "Toggle Design" button with new `/settings/appearance` route

---

src/boot/categories.toml

Resolves #4105
I've also added the category `Software-defined radio`.
Here are 2 crates that are in this category:
- https://github.com/rsadsb/adsb_deku
- https://github.com/FutureSDR/FutureSDR
I can remove the `SDR` from this PR if it's necessary to discuss it first at a meeting @Turbo87.
CC @wcampbell0x2a @bastibl @MoralCode

Adding categories related to Aerospace

---

cargo-registry-markdown/lib.rs
src/admin/render_readmes.rs
src/controllers/krate/publish.rs
src/util.rs
src/worker/readmes.rs

Extract `.cargo_vcs_info.json` from the tarball and use it to determine the path in vcs.
Support for this was added to cargo with
https://github.com/rust-lang/cargo/pull/9866
Fixes #3484 
(note that support for this in admin::render_readmes not yet exists - would come with #4095)
Depends on #4097 (Because of github/feedback#4477 - github ends up rendering the diffs together. Go to the commits tab and just look at the most recent commits to review).

Support relative URLs from repo-subdirectory packages

---

.github/workflows/ci.yml

As of v1.58, cargo fmt now supports the --check flag directly. Trying to get this utilized in relevant places across the r-l repos both because it's more succinct and so more people will see/become aware they no longer have to invoke the check the old way

use new cargo fmt check option

---

ember-cli-build.js

https://github.com/embroider-build/embroider/issues/823 has been resolved by now.

embroider: Remove obsolete `ember-get-config` workaround

---

.github/workflows/ci.yml
ember-cli-build.js

embroider is at v1.0.0 now and has been building a correctly working app for a while now, so it should be viable for us to upgrade now.
see https://github.com/embroider-build/embroider/

Use embroider build system by default

---

app/controllers/search.js
app/styles/application.module.css
app/styles/search.module.css
app/templates/search.hbs
app/utils/search.js
tests/acceptance/search-test.js
tests/utils/search-test.js

Resolves https://github.com/rust-lang/crates.io/issues/491
These filters can be used standalone, or combined with regular search terms. The syntax is inspired by https://api-docs.npms.io
<table>
<tr>
<td><img width="767" alt="Bildschirmfoto 2021-12-29 um 00 16 37" src="https://user-images.githubusercontent.com/141300/147614047-ca323230-20f3-4fe5-9504-8e8c026e3f9d.png">
<td><img width="766" alt="Bildschirmfoto 2021-12-29 um 00 18 00" src="https://user-images.githubusercontent.com/141300/147614106-6b856e26-80a7-4d5d-8e48-17122d5c21dc.png">

Add support for `keyword:cli` and `category:no-std` search filters

---

config/environment.js

These options have been removed in v7.x

Remove obsolete `ember-keyboard` options

---

ember-cli-build.js

This popped up during the migration to embroider.

Disable `crypto` import warning in `axe-core`

---

app/routes/crate/range.js
tests/routes/crate/range-test.js

Similar to the crate and version pages. This ensures that the URL stays the same so it can be fixed if there was a typo.

crate.range: Show error page if data fails to load

---

app/routes/crate.js
app/routes/crate/version.js
tests/acceptance/crate-test.js
tests/routes/crate/range-test.js
tests/routes/crate/version/model-test.js

This makes them a bit more consistent and useful :)

Adjust error page titles

---

app/components/crate-header.hbs
app/templates/keywords.hbs
tests/bugs/4506-test.js

This apparently broke in 8f62c4c 😱
Fixes https://github.com/rust-lang/crates.io/issues/4506

Fix `keyword` route links

---

config/environment.js

`auto` is deprecated in Ember.js 4

Ember: Use `history` location API

---

script/init-local-index.sh

Otherwise the script breaks if `init.defaultBranch` is not set to `master` (with `main` becoming a common alternative these days).
Split out from #4548.

Explicitly specify the branch name in init-local-index.sh

---

cargo-registry-markdown/lib.rs
src/tests/record.rs

Fix clippy warnings

---

src/controllers/krate/search.rs
src/tests/krate/search.rs

Fixes https://github.com/rust-lang/crates.io/issues/4538.
This does add a small string replace operation to the endpoint, but compared to the database queries the overhead should be negligible.

controllers::krate: Protect against null bytes in query string

---

src/admin/delete_crate.rs
src/admin/delete_version.rs
src/admin/migrate.rs
src/admin/populate.rs
src/admin/render_readmes.rs
src/admin/transfer_crates.rs
src/admin/verify_token.rs
src/app.rs
src/bin/background-worker.rs
src/bin/enqueue-job.rs
src/bin/monitor.rs
src/boot/categories.rs
src/config.rs
src/config/database_pools.rs
src/db.rs

In the December 22, 2021 crates.io outage, we experienced full packet loss between the database server and the application server(s). While the crates.io application supports running without a database during outages, those mitigations kicked in only after a bit more than 15 minutes of the packet loss starting.
The default parameters of the Linux network stack result in a TCP connection being marked as broken after roughly 15 minutes of no acknowledgements being received, which is what I believe happened during that outage.  Broken database mitigations kicking in after 15 minutes is too long for crates.io, as we ideally want those mitigations to kick in as soon as possible (ensuring crates.io users can continue downloading crates).
This PR tells libpq (the underlying PostgreSQL client …

Set `TCP_USER_TIMEOUT` to 15 seconds for database connections

---

src/config.rs
src/controllers/krate/metadata.rs
src/tests/krate/summary.rs
src/tests/util/test_app.rs

I haven't figured out a great way to add a test for this because I need to create a crate and get a crate ID and then change the app's config, and the test app doesn't easily have this... so I thought I'd throw up this change for discussion and see if anyone had better ideas.

Add an environment variable to let us exclude crate IDs from the recent downloads list

---

app/index.html

In-browser translation tool are mutating the DOM in ways that are unfortunately incompatible with the way most SPAs are handling DOM updates. This leads to cryptic Sentry issues like "Failed to run removeChild() bla bla". This commit attempts to disable the in-browser translation to fix these issues.
Related:
- https://stackoverflow.com/a/54200382/1478093
- https://github.com/facebook/react/issues/11538#issuecomment-350110297
- https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome

Disable in-browser translation

---

app/routes/application.js
tests/helpers/sentry.js

This allows Sentry to properly group issues by the route that they're happening on.

Sentry: Set transaction name instead of custom `routeName` tag

---

.github/renovate.json5

see https://docs.renovatebot.com/presets-default/#automergelinters and https://docs.renovatebot.com/presets-default/#automergetesters
Since we don't deploy to production from `master` automatically the security impact should be acceptable.

renovate: Automatically merge linting and testing dependency updates

---

src/boot/categories.toml

This PR proposes the addition of a virtualization category on crates.io.
Currently, there does not seem to be a category dedicated to code concerning virtualization
technology such as containerization, VMs, resource management, etc.
Some crates that would usually fall within this category have opted for others like emulation,
which while somewhat related, can be distinct from virtualization.
Any thoughts on this?

Add `Virtualization` category to crates.io

---

src/uploaders.rs
src/worker/dump_db.rs

Use `seek()` on the `content` passed to `upload` rather than separately passing in a `content_length`.
r? @Turbo87

Refactor `upload` to avoid passing content_length

---

app/controllers/catch-all.js

This fixes https://sentry.io/organizations/rust-lang/issues/2966611026. Technically `transition.retry()` should also work, but for some reason it sometimes fails, likely due to a routing bug in Ember.js. Using `replaceWith()` with the current route results in the same behavior, but avoiding this issue. Unfortunately I did not find a way to reproduce this as part of the test suite :-/
Resolves https://github.com/rust-lang/crates.io/issues/4786

catch-all: Fix `reload()` action

---

app/controllers/search.js
app/templates/search.hbs
tests/acceptance/search-test.js

Resolves https://github.com/rust-lang/crates.io/issues/4785

search: Fix app crash without given `q` query parameter

---

Cargo.lock
Cargo.toml
src/config.rs
src/controllers/helpers/pagination.rs
src/tests/krate/search.rs
src/tests/util.rs
src/tests/util/test_app.rs

This PR adds support for the new `WEB_PAGE_OFFSET_CIDR_BLOCKLIST` environment variable that holds a list of IPv4 based CIDR blocks. The use case of this env var is to block IPs coming from the same network or IP range. It should help to mitigate scenarios where a high number of distributed requests from multiple clients put a high load onto the application (e.g. bot network) which happen to come from the same IP range. The new block list is meant to complement the existing User Agent & IP block lists.
**Note** the functionality is similar to the `WEB_PAGE_OFFSET_UA_BLOCKLIST` env var which blocks requests by matching user agents. It also only applies to the same (expensive) API endpoints that fetch data using pagination. The common experience using the web site should not be affected. The …

Use env var to support blocking IP ranges

---

src/config.rs

This PR simplifies the CIDR parsing code a little bit by passing the CIDR strings one-by-one to the `parse_cidr_block()` function, instead of passing in the whole `Vec`. It also refactors `parse_cidr_block()` to return a `Result` instead of panicking directly.
/cc @justahero

Simplify CIDR parsing code

---

docs/CONTRIBUTING.md
frontend.Dockerfile

The current `frontend.Dockerfile` has 16.14.2, but 16.15.0 is required (see PR #4751). You'll run into an error when trying to run a `docker-compose build`. This PR bumps the version. 😄 
```
------
> [cratesio_frontend 4/5] RUN yarn install:
#20 1.106 yarn install v1.22.18
#20 1.663 [1/5] Validating package.json...
#20 1.684 error cargo@0.0.0: The engine "node" is incompatible with this module. Expected version "16.15.0". Got "16.14.2"
#20 1.717 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#20 1.717 error Found incompatible module.
------
failed to solve: executor failed running [/bin/sh -c yarn install]: exit code: 1
```

bump node docker image to 16.15.0

---

Cargo.lock
Cargo.toml
src/admin/upload_index.rs

This PR uses https://github.com/console-rs/indicatif to display a progress bar while backfilling the HTTP-based index, with the main advantage of having a somewhat reasonable ETA display :)
/cc @arlosi

admin/upload_index: Use `indicatif` for progress reporting

---

Cargo.lock
Cargo.toml

This should resolve a version conflict with our `dashmap` dependency and the transitive `autocfg` dependency.
see https://github.com/svartalf/rust-claim/pull/10 and https://github.com/rust-lang/crates.io/pull/4763

claim: Use git dependency

---

app/sentry.js
package.json
yarn.lock

The class is no longer available in Sentry v7, so we will import it here to keep using it for now. Eventually we might switch to `@sentry/ember` if that works well enough at some point.
This should hopefully unblock https://github.com/rust-lang/crates.io/pull/4853

sentry: Replace `Ember` import from `@sentry/integrations`

---

Cargo.toml

We're not publishing this package, so there is no need for us to have docs.rs metadata specified

Remove unused `docs.rs` metadata

---

src/router.rs
src/tests/blocked_routes.rs

Instead of having a subrouter, we can just add the routes directly to the primary router and simplify the code a little bit.

router: Remove `/api/v1/` subrouter

---

src/github.rs
src/models/team.rs
src/tests/team.rs
src/tests/util/github.rs

Right now, to be able to add a GitHub team to the list of owners of a crate, you have to both be an existing owner of the crate and to be a member of the team you want to add. The second protection is important to prevent people from inviting random teams to their crates, as we don't have an invite system for teams.
Still, that restriction gets annoying when the user adding a team to a crate is an owner of the GitHub organization the team is defined in. The user still *can* add the team, but they first need to add themselves to the team in question (and they can do so, since they're owners of the organization), which is an unnecessary annoyance.
This PR was prompted by having to add a team in the `rust-lang` organization to a crate, when the existing owner is @rust-lang-owner. In the …

Allow organization owners to add teams from their org to crates

---

src/admin/delete_crate.rs
src/admin/delete_version.rs
src/uploaders.rs

If `-y` is specified, don't ask for interactive confirmation.
There are a bunch of crates that were published in violation of our policies, and I want to run the admin delete-crate utility as part of a script and not have to manually hit `y` all the time :)

Add a -y option for scripting of delete crate/delete version admin utils

---

src/middleware.rs
src/sentry/middleware.rs
src/sentry/mod.rs

see https://docs.sentry.io/product/performance/ and https://github.com/Turbo87/sentry-conduit/pull/76

sentry: Enable performance tracing via `SENTRY_TRACES_SAMPLE_RATE` env var

---

src/controllers/version/downloads.rs

I assume that this might have been necessary when we still had `&mut Request` in the parameters of the function, but since that is no longer the case we don't need the complicated logic here.

version::downloads: Simplify `add_custom_metadata()` usage

---

src/uploaders.rs
src/worker/git.rs

This PR ensures that the `update_crate_index()` background task will be able to handle the case where a crate has been deleted from the git index. If a `NotFound` error kind is detected we will issue a `DELETE` command to the S3 index instead of uploading the file contents.

worker::git: Adjust `update_crate_index()` to handle deleted files

---

app/utils/license.js
tests/utils/license-test.js

For example the <kbd>LLVM-exception</kbd> in the license of https://crates.io/crates/cranelift/0.85.1.

Link SPDX license exceptions

---

src/models/keyword.rs

The use of `is_alphanumeric` for keyword validation is from 2014 (ee1c49be24d47c3d6a6a4d11acc7069976872892, aebaec8f3fe8514b350d48bef6461ed41380ffb2) which is way before `is_ascii_alphanumeric` became available (2018, Rust 1.24).

Replace is_alphanumeric + is_ascii with is_ascii_alphanumeric

---

src/tests/record.rs

If the data file would consist of an empty array, then don't write it as this is the default if a file does not exist.
Extracted from https://github.com/rust-lang/crates.io/pull/5022

Don't auto-generate empty http-data files

---

src/tests/http-data/krate_publish_new_krate_git_upload_appends
src/tests/http-data/krate_publish_publish_after_removing_documentation
src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates
src/tests/http-data/krate_publish_uploading_new_version_touches_crate
src/tests/http-data/krate_yanking_publish_after_yank_max_version
src/tests/http-data/krate_yanking_unyank_records_an_audit_action
src/tests/http-data/krate_yanking_yank_max_version
src/tests/http-data/krate_yanking_yank_records_an_audit_action
src/tests/http-data/owners_new_crate_owner
src/tests/http-data/version_version_size
src/tests/krate/publish.rs
src/tests/krate/yanking.rs
src/tests/owners.rs
src/tests/team.rs
src/tests/util.rs
src/tests/util/test_app.rs
src/tests/version.rs

The original intent was that tests would be able to enqueue mutliple
actions and process them more asynchronously to act as more of a stress
test of the background worker logic. However, we have no tests explicity
testing such behavior and we can always add back such methods if we
decide to implement such tests.
This change reorders some requests in the http-data files. For the most
part requests are unchanged, however now if 2 versions of a crate are
published in rapid succession the HTTP index is guarenteed to see both
versions of that file.
Previously, if versions A and B were published they would both go in
the background queue. When the queue was processed, the versions would
be published to the git index and each of those jobs would enqueue an
HTTP sync. However, those syncs would …

Always run background jobs after a test publish

---

src/tests/http-data/krate_yanking_publish_after_yank_max_version
src/tests/http-data/krate_yanking_unyank_records_an_audit_action
src/tests/http-data/krate_yanking_yank_max_version
src/tests/http-data/krate_yanking_yank_records_an_audit_action
src/tests/http-data/krate_yanking_yank_works_as_intended
src/worker/git.rs

The intent of this PR is to apply the fix in the final commit to enqueue a sync of the HTTP index whenever a yank/unyank is performed. This mirrors the way that a sync is enqueued by the publish background job after a new version is published. Once this is deployed, we will need to run a full index sync to correct any existing divergence between the official git index and the experimental HTTP index.
The other commits only affect the test harness and http-data files. A new `RECORD=force cargo test` mode allows for regenerating these data files. In this mode all responses are simulated as a status=200 success with an empty body and no response headers. Apparently we have no existing tests to cover failed S3 requests. The old recording mode where the request is actually proxied to the …

Ensure the HTTP index is updated after a yank/unyank

---

app/components/download-graph.hbs
app/components/download-graph.js
app/components/download-graph.module.css
app/controllers/crate/version.js
app/styles/crate/version.module.css
app/templates/crate/version.hbs

Related Issues:
- https://github.com/rust-lang/crates.io/issues/3876
This PR add a button to the graph of download counts which toggle between stacked / unstacked graph.
Screenshots:
- Stacked graph: <img width="1552" alt="image" src="https://user-images.githubusercontent.com/30400950/181035074-bc26aa75-bf25-418e-a9d5-ae6109afaf38.png">
- Unstacked graph: <img width="1552" alt="image" src="https://user-images.githubusercontent.com/30400950/181035124-b59023a9-848d-4656-b733-df324782dc41.png">

Toggle stacked download graph

---

src/admin/upload_index.rs

https://github.com/rust-lang/crates.io/issues/4836 migrated the admin tool to use `indicatif` for progress reporting, but back then there was no way to output additional messages without disturbing the progress bar. With the latest release of `indicatif` a `suspend()` method was introduced which allows us to restore the original behavior.

admin/upload-index: Restore "skipping file" output

---

src/boot/categories.rs
src/controllers/krate/publish.rs
src/controllers/version/downloads.rs
src/models/crate_owner_invitation.rs
src/models/keyword.rs
src/models/user.rs
src/tests/krate/publish.rs
src/tests/krate/search.rs
src/tests/krate/summary.rs
src/tests/user.rs
src/worker/readmes.rs

This should unblock #5069 and make our code a little easier on the eyes :)

Remove unnecessary derefs

---

src/controllers/krate/publish.rs
src/tests/krate/publish.rs

This PR follows #5071 and removes the code line that saves badges during publish to the database. The existing database records are still preserved for now, but no longer updated when a new version is published, and they are no longer available on the API (see #5071).

Stop saving badges in the database

---

cargo-registry-index/lib.rs
src/controllers/krate/publish.rs
src/downloads_counter.rs
src/models/version.rs
src/tests/builders/publish.rs
src/tests/builders/version.rs
src/tests/krate/publish.rs
src/views/krate_publish.rs
src/worker/update_downloads.rs

This PR was extracted from https://github.com/rust-lang/crates.io/pull/5066 to make it independently reviewable and mergeable.
The main purpose of these changes is to match the order that the entries in the index are currently serialized in. This will eventually allow us to recreate the index from a single source of truth (the database) with a minimal diff.

index: Use/Allow alphabetic ordering of features and dependencies

---

src/models/keyword.rs
src/tests/http-data/krate_publish_good_keywords
src/tests/krate/publish.rs

Prior art: '+' in feature names &mdash; https://github.com/rust-lang/crates.io/pull/2510. See that PR for the rationales in favor of that.
Specifically I would be interested in using "c++" as a tag on some of my FFI crates. Alphanumericizing it to "cpp" or "cxx" is not so good because those are each the name of a specific crate for a specific approach to C++ interop, and a crate that's generally suitable for C++ interop wouldn't want its keywords to imply it only works in concert with one of those two other crates.
Cargo has supported '+' in keywords since Rust 1.1.

Allow '+' in keywords

---

package.json

This appears to work just fine the way we're currently using it, but pnpm is complaining in certain cases which currently prevents renovatebot updates from working correctly.

pnpm: Ignore `postcss` peer dependency warnings

---

src/admin/git_import.rs
src/admin/mod.rs
src/bin/crates-admin.rs

Adds a new admin tool to import data from the git index into the database:
* `versions` table: `checksum`, `links`
* `dependencies` table: `explicit_name`
Split out from #5066
r? @Turbo87

Add tool to import from git index into the database

---

README.md

#crates-io-team is now in "web presence" instead of "ops" this updates the README to reflect the change

Update discord pointer in README

---

package.json
pnpm-lock.yaml

This is referenced by the ESLint config and can sometimes cause issues if not explicitly specified. This is probably a side effect of us switching to pnpm, which is a bit more strict in terms of peer dependencies.

ESLint: Add missing `@babel/plugin-proposal-decorators` dependency

---

src/controllers/crate_owner_invitation.rs
src/controllers/keyword.rs
src/controllers/krate/metadata.rs
src/controllers/krate/search.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/tests/owners.rs
src/tests/util/response.rs

The 2nd commit address a warning from the `beta` channel, and the 1st commit is from `nightly`. Both cleanups are reasonable.

Address some clippy warnings

---

src/admin/git_import.rs

The `git-import` admin tool assumed that no `explicit_name`s had been imported, which caused it to fail after a partial run.
This change updates the tool to filter out versions that already have `explicit_name`s in their dependencies, allowing it to be run multiple times.
The transaction scope is changed to run over a crate rather than a version, which seems to provide slightly better performance.
r? @Turbo87

git-import admin tool can resume partial imports

---

app/routes/category.js
app/routes/crate.js

`store.find()` is deprecated in favor of `store.findRecord()`

ember-data: Replace `store.find()` calls with `store.findRecord()`

---

config/deprecation-workflow.js
package.json
pnpm-lock.yaml

As the code comment says, this deprecation warning is causing false positives due to our usage of ember-concurrency.

ember-data: Silence `model-save-promise` deprecation

---

app/models/crate.js
app/models/user.js
app/utils/custom-action.js
package.json
pnpm-lock.yaml

https://github.com/mike-north/ember-api-actions/ is essentially unmaintained and it the cause of a few deprecation warnings in our test suite. this PR replaces the dependency with a small `customAction()` function that serves a similar purpose with a slightly simplified implementation.

Replace `ember-api-actions` dependency with `customAction()` function

---

app/routes/category.js
tests/routes/category-test.js

This will fill the search box with `category:<category> ` on all
category pages helping the user discover how to filter by category.
Also means when the user appends to the search field it will be searching 
the current category that is selected, instead of previously all the crates.

Autofill search box when browsing categories

---

Cargo.lock
Cargo.toml
src/tests/snapshots/all__version__authors.snap
src/tests/snapshots/all__version__index-2.snap
src/tests/snapshots/all__version__index.snap
src/tests/snapshots/all__version__show_by_crate_name_and_semver_no_published_by.snap
src/tests/snapshots/all__version__show_by_crate_name_and_version.snap
src/tests/snapshots/all__version__show_by_id.snap
src/tests/util.rs
src/tests/util/insta.rs
src/tests/version.rs

see https://insta.rs
This allows us to more easily assert on the exact structure of our API responses and give us a straight-forward way to keep the assertions up-to-date. 
Currently, if we add a new field to our API responses, the tests will still pass, because the tests are using the same structs as the production code. Even worse, if we remove a field the same is true, even though this should be considered a breaking change. With snapshot tests it will be easy to detect these sort of things because the test files will need to be updated.

tests: Use `insta` to assert on full version API responses

---

.github/renovate.json5

Similar to how we already do it for `conduit` updates

renovate: Group `diesel` packages in one pull request

---

app/styles/application.module.css
cargo-registry-markdown/lib.rs

Resolves https://github.com/rust-lang/crates.io/issues/5017
Unfortunately `ammonia` does not easily allow us to remove the empty links completely, but we can remove the clickable link styling from `<a>` elements without an `href` attribute. This, plus ignoring relative links starting with `::` allows us to fix the issue linked above.
For any crates.io users reading this: Note that we will need to rerender all README files for this to work on older releases. Once deployed, it should work fine for new releases though.

Fix rustdoc link rendering in READMEs

---

src/tests/builders/version.rs
src/tests/snapshots/all__version__index-2.snap
src/tests/snapshots/all__version__show_by_crate_name_and_semver_no_published_by.snap
src/tests/snapshots/all__version__show_by_crate_name_and_version.snap
src/tests/snapshots/all__version__show_by_id.snap
src/tests/version.rs
src/views.rs

This got introduced by https://github.com/rust-lang/crates.io/pull/5077 and backfilled using https://github.com/rust-lang/crates.io/pull/5112.

EncodableVersion: Expose new `checksum` field on the API

---

src/tests/record.rs

While 127.0.0.0 appears to work good enough on Unix machines, it did cause macOS to fail all tests. Since the original was 127.0.0.1 this commit is fixing it back to the way it was before :D
/cc @jtgeibel

tests/record: Fix server bind IP address

---

app/templates/accept-invite.hbs

This uses an in-app transition instead of completely reloading the app

accept-invite: Use `<LinkTo>` instead of raw `<a>`

---

app/components/page-header.module.css
app/styles/category/index.module.css

Some of them were way too large and looked a bit out-of-place.

PageHeader: Remove margins on `.heading` element

---

ember-cli-build.js

If the build is "parallelizable" it improves the build time performance :)

ember-cli-babel: Ensure parallel builds

---

app/components/crate-header.module.css
app/components/page-header.module.css

Align text in page headers properly

---

app/services/session.js
tests/acceptance/logout-test.js

Previously, when a user logged out, the data in the Ember Data store was still kept in-memory, so when another user logged in they could potentially see information that they shouldn't have access to. This PR performs a full page reload after logout to ensure that the Ember Data store and other in-memory data is cleared to avoid issues like this.

services/session: Clear in-memory data when logging out

---

app/styles/dashboard.module.css

fixed the icons in the dashboard page: the icons were a bit offset
before:
after:

fix css icons in dashboard

---

docs/CONTRIBUTING.md

Provides a section for release state docs to the CONTRIBUTING file.

Add release state to contrib docs

---

app/components/crate-header.hbs
tests/acceptance/crate-test.js
tests/routes/crate/range-test.js
tests/routes/crate/version/model-test.js

The tiniest possible change, but this matches how we display them in the search results and makes the page a little more consistent.

CrateHeader: Add `v` prefix to version number

---

package.json
pnpm-lock.yaml

v0.5.0 is somewhat outdated and does not work well with Embroider. This allows us to use http://localhost:4040/tests/ again, without any failing tests due to incorrect environment configs.

ember-get-config: Use override to update to v2.1.1

---

app/styles/application.module.css

This increases the contrast of our header and footer text a bit :)

Use slightly darker background color for header and footer

---

.github/workflows/ci.yml

see https://github.com/actions/setup-node/pull/532, which got integrated here by https://github.com/rust-lang/crates.io/pull/5261

CI: Replace `volta-cli/action` with builtin functionality from `actions/setup-node`
