.env.sample, Cargo.lock, Cargo.toml, src/background_jobs.rs, src/bin/background-worker.rs, src/tests/util/test_app.rs, src/worker/cloudfront.rs, src/worker/git.rs, src/worker/mod.rs
Send invalidation request to CloudFront when a crate is modified.
Does nothing if `CLOUDFRONT_DISTRIBUTION` isn't set.
Fixes #4913
=> Add CloudFront invalidation for index files

app/templates/policies.hbs
Provides a section in the policies page to communicate to users how they could leave a crate
open for transferring. The idea was first shared by @carols10cents.
=> Add FAQ on how to leave crate open for adoption

src/admin/test_pagerduty.rs
This resolves the biggest blocker of the clap v4 upgrade.
=> clap: Derive possible values for `EventType` argument

src/admin/delete_crate.rs, src/admin/delete_version.rs, src/admin/git_import.rs, src/admin/migrate.rs, src/admin/populate.rs, src/admin/render_readmes.rs, src/admin/test_pagerduty.rs, src/admin/transfer_crates.rs, src/admin/upload_index.rs, src/admin/verify_token.rs, src/admin/yank_version.rs, src/bin/crates-admin.rs
clap v4 renamed quite a few things (in a backward compatible way! ❤️) and this PR fixes all of the related deprecation warnings.
=> clap: Resolve deprecation warnings

Cargo.lock, Cargo.toml
According to https://github.com/clap-rs/clap/blob/v4.0.0/CHANGELOG.md this needs to be explicitly enabled these days.
=> clap: Add new `wrap_help` feature flag

app/services/session.js
This, in theory, fixes an issue where when I attempt to log in to http://crates.io via GitHub, the OAUTH popup closes before I can interact with it. In my case, an unrelated browser extension appears to emit an event on the popups window. 
As it turns out, `window.addEventListner('event', () => { })` can be unexpedetly chatty, especially when users have browser extensions installed.
On a positive note, OAUTH has a mechanism by which we can ensure the `event` is from the intended login flow session, which is the `state` value we already pass to it. This PR merely utilizes it for this purpose.
---
Please note, for some reason, I am not able to get this project running locally so testing this exact code hasn't been possible. I am reasonably sure this, or something very close to this will …
=> Prevent login flow from being disrupted by unrelated events

src/controllers/krate/search.rs, src/tests/krate/search.rs
When searching for crates with results order specified (by all-time / recent downloads), ignore the "exact match" for the result ordering.
Resolves #5247
=> Ignore "exact match" for search when sorted by downloads

docs/MIRROR.md
see https://github.com/rust-lang/crates.io/pull/5324#issuecomment-1279736479
=> docs: Reintroduce `MIRROR.md` to keep third party links to the document working

.env.sample, src/config/base.rs, src/worker/cloudfront.rs
Infra team has requested that we use a single environment variable set for authenticating for AWS services.
This PR standardizes on: `AWS_ACCESS_KEY` and `AWS_SECRET_KEY`.
=> Use AWS_ environment variables for authenticating to AWS services

docs/CONTRIBUTING.md
Compatibility is broken with diesel 2.0, so the current code must use diesel before 2.0.
Mentioned in the discussion below.
https://github.com/rust-lang/crates.io/discussions/5348
=> docs: Restrict `diesel_cli` to version 1.x

app/styles/application.module.css
This will make it easier in the future to use different font families for heading and body text.
=> styles: Extract `font-body/heading` font family design tokens

docs/CONTRIBUTING.md
Running: `cargo install diesel_cli --no-default-features --features postgres --version 1`
results on invalid SemVer version: `the `--version` provided, `1`, is not a valid semver version`.
=> fix: diesel cli install command

cargo-registry-s3/lib.rs
This should unblock the Rust 1.65 update in #5410
=> s3: Fix `base64::encode()` call

src/controllers/krate/publish.rs, src/email.rs, src/tests/builders/publish.rs, src/worker/dump_db.rs, src/worker/git.rs
Another PR to hopefully unblock https://github.com/rust-lang/crates.io/pull/5410
=> Remove unnecessary borrows

src/controllers/krate/metadata.rs, src/controllers/krate/search.rs
https://github.com/rust-lang/crates.io/pull/5071 changed our API to not return badges anymore, but the endpoint code was still performing the corresponding database queries for no reason. This PR removes the queries to speed up the endpoints.
=> badges: Remove obsolete database calls

src/tests/builders/publish.rs, src/tests/krate/publish.rs, src/views/krate_publish.rs
We are no longer saving these into the database (see https://github.com/rust-lang/crates.io/pull/5074), so there is no need to deserialize them from the JSON payload anymore.
=> EncodableCrateUpload: Remove obsolete `badges` field

src/views.rs
These are somewhat hard to discover when they are put somewhere in the middle of the file 😅
=> views: Move `mod` and `use` lines to the top of the file

Cargo.lock, Cargo.toml, src/downloads_counter.rs
Ideally `dashmap` would reexport the iterator types so that we can use them directly, but instead we will use generics to pass the iterator into the `persist_shard()` function. This allows us to get rid of the direct `hashbrown` dependency, which solves the version conflict with their latest release.
=> downloads_counter: Remove `hashbrown` reference

src/views.rs
This resolves https://github.com/rust-lang/crates.io/issues/5419. Not a perfect solution, but in an eventually consistent system this is hard to fix properly... 🤷
=> downloads: Use `recent_downloads` as `downloads` if it is higher

Cargo.lock, Cargo.toml, src/worker/cloudfront.rs
While testing out invalidations for the HTTP-based crate index we noticed that the CloudFront server often returns 503 errors. The official (but still experimental) AWS SDK uses a default request retry policy (max. 3 attempts, exponential backoff with 1 sec base delay) to apparently avoid these issues. This PR introduces the `retry` dependency and uses it with a similar retry policy for the CloudFront requests.
/cc @arlosi
=> cloudfront: Retry requests on server or network error

.github/workflows/ci.yml
Since the scenario has been marked as `continue-on-error` it wouldn't show up as a failure in the GitHub UI, and the number of times that this has caught any issues with the beta cycle of Rust itself in the past few years is very close to zero. Rust is using crater runs to determine incompatibilities with public projects, which includes crates.io. In conclusion, this scenario is mostly just wasting CI resources but brings very little value.
=> CI: Remove `beta` backend scenario

src/bin/background-worker.rs
No wonder that we didn't see any debug logging in the production logs if the logger is never initialized for the background worker... 😅 
This PR fixes the issue by initializing it similar to how we do it for the `server` binary. 
Potential further improvement: extract it to a shared function that all binaries can use.
=> background-worker: Initialize `tracing` logger

src/bin/background-worker.rs
Similar to #5487, the background worker also did not initialize the Sentry error reporting SDK and this PR fixes that. The code is essentially just copied over from the `server` binary.
=> background-worker: Initialize `sentry` error reporter

Cargo.lock, Cargo.toml, src/bin/background-worker.rs, src/bin/server.rs
This matches the log message style used by Heroku itself. Unfortunately it is not quite configurable yet, but it's a step in the right direction :)
=> tracing: Use `tracing-logfmt` to output log messages

src/sentry/mod.rs
We have a lot more traffic on the download endpoint than on all other endpoints combined, so this PR adjusts the trace sample rate for this specific endpoint.
Note that this PR currently does not work because we can't actually access any of the fields on the `TransactionContext` yet (see https://github.com/getsentry/sentry-rust/pull/510#issuecomment-1304493639).
=> sentry: Reduce trace sample rate for download endpoint

app/adapters/crate-owner-invite.js, app/routes/me/pending-invites.js
This is related to https://github.com/rust-lang/crates.io/issues/4083 and switches the frontend over to the new endpoint. All that is missing after this PR is to add pagination support to the frontend.
/cc @EstebanBorai
=> me/pending-invites: Use `GET /api/private/crate_owner_invitations` endpoint

src/views.rs
#5502 was causing false positives due to the simplified `ends_with()` usage. This PR fixes it by checking against `.{domain}` instead, but avoids unnecessary allocations by performing the original check first.
=> Fix documentation URL blocking for substring domains

src/middleware/log_request.rs
We've already extracted the status code with a fallback above, so there is no need for doing it again here :)
=> middleware::log_request: Simplify `status` check

src/bin/background-worker.rs, src/bin/server.rs, src/util.rs, src/util/tracing.rs
This allows us to share the same code between the `server` and `background-worker` binary.
=> Extract `tracing::init()` function

src/worker/cloudfront.rs
It looks like three retries isn't always enough, and since we run multiple background jobs in parallel retrying ten times should not be a big issue.
=> worker::cloudfront: Increase retry attempts

src/middleware/log_request.rs
We are once again near the cap of what our logging provider allows us to send per day, so this PR is trying to save a few more bytes.
Our most hit endpoint is the crate download endpoint, so optimizing this can have significant returns. This PR removes the `status` field from our log lines for requests that hit the download endpoint and are regular redirections. If the request fails we'll still log it the same as we used to before this PR.
=> middleware::log_request: Skip `status` logging for successful download requests

src/middleware/log_request.rs
this is roughly similar to the old logging but uses tracing log levels instead of the `at` field at the front. the fields themselves are not converted to `tracing` fields (yet), because we have some fields that we only optionally log, which is a little bit harder to do with `tracing`.
=> middleware::log_request: Use `tracing` macros instead of `println!()`

src/tests/util/test_app.rs
This PR adjusts the `tracing` logger of the test suite to also use the `compact` formatter (same as in production) and always output `info` level messages and anything above that.
=> tests: Adjust logging

Cargo.lock, cargo-registry-index/Cargo.toml, cargo-registry-index/lib.rs, src/admin/migrate.rs, src/bin/background-worker.rs, src/bin/server.rs, src/config/base.rs, src/middleware.rs, src/tests/server_binary.rs
This lets us turn the logging on and off with an env var, allows us to have multiple log levels, integrates well with Sentry and makes it easier to log variables in a structured way.
Note that two small changes to the `server_binary` test file were necessary, because it is listening for a specific log line, which slightly changed within the context of this PR.
=> Migrate more `println!()` calls to use `tracing` instead

src/tests/server_binary.rs
This allows us to keep the original error message and wrap it with a more contextual one like we do in other parts of the codebase.
=> tests/server_binary: Use `.context()` to enhance error message

src/auth.rs, src/controllers.rs, src/controllers/crate_owner_invitation.rs, src/controllers/util.rs, src/lib.rs
This makes our authentication code a little more discoverable. The CORS function stays in the `util` module for now.
=> Extract `auth` module

package.json
It looks like renovatebot only supports version updates in `resolutions`, so we'll revert to using that for now until support for updating `pnpm.overrides` is added.
=> package.json: Migrate `pnpm.overrides` back to `resolutions`

src/auth.rs
There is no need anymore for us to have a mutable reference to the `Request` struct.
=> UserAuthenticationExt: Remove obsolete `mut` keyword

src/auth.rs, src/controllers.rs, src/controllers/crate_owner_invitation.rs, src/controllers/krate/follow.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/krate/search.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/version/yank.rs, src/lib.rs
This wraps the `req.authenticate()` calls with a builder pattern API, which can later be extended to support token scopes. 
One small downside is that it's possible to forget to call the `check()` method and only construct the `AuthCheck` struct, but that should largely be mitigated by the `#[must_use]` attribute.
=> auth: Implement AuthCheck struct

src/tests/owners.rs, src/tests/record.rs, src/tests/routes/crates/list.rs, src/tests/team.rs, src/tests/user.rs
Some tests were using `/* ... */` comments, others `//`, but both would benefit from using doc comment syntax (`///`). Additionally, this ensure that comments are bound to the following function, which makes automated move refactorings less prone to losing the corresponding comment.
=> tests: Use more doc comments to describe tests and test helpers

src/middleware/log_request.rs
As the code comment says, we pay per GB of logged data, so this PR is another attempt to reduce the amount of bytes we send to the logging provider.
=> LogRequests: Reduce amount of logged information for successful download requests

src/models/token.rs, src/models/token/scopes.rs
This turns the `endpoint_scopes` column from `Option<Vec<String>>` to `Option<Vec<EndpointScope>>`, which is a bit more restrictive in the values it supports, and ensure that we're only serializing endpoint scopes to the database that actually exist in our application.
=> Implement `EndpointScope` enum

src/models.rs, src/models/token.rs, src/tests/owners.rs, src/tests/util.rs, src/tests/util/test_app.rs
This PR adds four additional tests for the owner change endpoint, related to the implementation of token scopes. Note that these tests are currently all returning `200 Ok` because token scope checks have not been enabled for this endpoint yet. This will be done in a follow-up PR and the tests will then be changed to account for this.
=> tests/owners: Add tests with token scopes

src/auth.rs, src/tests/owners.rs
This allows us to use something like:
```rust
let auth = AuthCheck::default()
.with_endpoint_scope(EndpointScope::ChangeOwners)
.for_crate(crate_name)
.check(req)?;
```
=> AuthCheck: Add `with_endpoint_scope()` and `for_crate()` options

src/models/token/scopes.rs
As discussed in the team meeting, this should instead be solved by having both variants as dedicated scopes, if necessary.
Related: 
- https://github.com/rust-lang/crates.io/pull/5569
=> CrateScope: Remove crate name normalization

src/boot/categories.toml
This PR creates a category for neuroscience under science.
It is common to have a separate software category for neuroscience. Various other package managers also have a category for neuroscience [1,2]. With this change, Rust software related to the analysis or the study of brain functions can explicitly specify their category as neuroscience.
1. https://docs.fedoraproject.org/en-US/neurofedora/overview/
2. https://neuro.debian.net/
=> Add `science::neuroscience` category

app/models/category.js, app/models/crate.js, app/models/dependency.js, app/models/keyword.js, app/models/version-download.js, app/models/version.js
see https://rfcs.emberjs.com/id/0739-ember-data-deprecate-non-strict-relationships/
=> Ember Data: Fix relationship deprecation warnings

Cargo.lock, Cargo.toml, src/middleware/ember_html.rs
This will also have the side effect of our logs showing the correct requested path instead of `/index.html` for everything.
=> middleware::ember_html: Use `lookup()` to avoid unnecessary path mutation

src/app.rs, src/middleware/ember_html.rs
This would potentially allow other parts of the code to use the same `Client` instance for other fastboot requests.
=> middleware::EmberHtml: Move `fastboot_client` into the `App` struct

src/tests/account_lock.rs, src/tests/authentication.rs, src/tests/blocked_routes.rs, src/tests/owners.rs, src/tests/read_only_mode.rs, src/tests/routes/metrics.rs, src/tests/server.rs, src/tests/team.rs, src/tests/token.rs, src/tests/util.rs, src/tests/util/response.rs
Most of them can use `http` directly, which helps us migrate away from `conduit` eventually
=> tests: Replace unnecessary `conduit` imports

src/tests/routes/categories/get.rs
The `app.db()` closure takes the only existing database connection and any API requests inside the closure can deadlock waiting on the connection. For some reason this does not appear to cause any issues in the current state, but once the API requests are going through an async layer this is starting to cause issues.
=> tests/routes/categories/get: Avoid database connection deadlock

conduit-hyper/src/lib.rs, conduit-hyper/src/service.rs, conduit-hyper/src/service/blocking_handler.rs, src/tests/util.rs, src/tests/util/response.rs
We are using our own `Response` struct from `src/tests/util/response.rs` to wrap around a `conduit::Response` to make it more ergonomic to use in our test suite. This however creates a tight coupling between `conduit` and our test suite.
This PR changes our own `Response` to wrap `reqwest::blocking::Response` instead. This should make it possible to do actual HTTP requests in the future, and still use the same test-related methods and structs.
=> tests/Response: Replace `conduit::Response` with `reqwest::blocking::Response`

src/tests/routes/crates/list.rs
`.search()` is putting this value directly into `MockRequest::with_query()`, which expects a URL-encoded string. This currently only works because we're skipping the `hyper` layer in our test suite, but would cause invalid URL errors otherwise.
=> tests/routes/crates/list: Fix `.search()` calls with invalid characters

src/tests/authentication.rs, src/tests/util.rs, src/tests/util/test_app.rs
Previously, our test suite ignored the `hyper` wrapper and just interfaced with `conduit` directly. We would eventually like to migrate our `conduit` middlewares to `tower` middlewares though, so we will need to run our tests through as much of our full stack as possible.
This PR changes the `RequestHelper::run()` method to use `conduit_hyper::Service` to ensure that we're using the `hyper` layer too.
=> Run tests through `conduit-hyper` layer

src/email.rs
We're only allowing SMTP in production, so logging the backend in our production logs seems a bit redundant.
=> email: Remove `email_backend` metadata logging

src/tests/util/test_app.rs, src/util/tracing.rs
This was previously only usable from within the `tests` module, but now it can also be used in unit tests.
=> tracing: Extract `init_for_test()` function

Cargo.lock, conduit-hyper/Cargo.toml, conduit-hyper/src/file_stream.rs, conduit-hyper/src/service.rs
We can use the re-exported types instead, which helps to avoid potential version conflicts.
=> conduit-hyper: Remove unnecessary dependency declarations

src/middleware.rs
Since we use `tracing` for the HTTP logs now and that uses the test writer we don't have to disable this anymore.
=> middleware: Enable `LogRequests` middleware in test mode

Cargo.lock, Cargo.toml, src/controllers.rs, src/controllers/github.rs, src/controllers/github/secret_scanning.rs, src/email.rs, src/github.rs, src/router.rs, src/tests/all.rs, src/tests/github_secret_scanning.rs, src/tests/util.rs, src/tests/util/github.rs
Adds a new POST endpoint at `/tokens/alert/github` to receive alerts from GitHub when crates.io API tokens are exposed.
Requires adding a dependency on [ring](https://crates.io/crates/ring) for ECDSA signature validation.
Intended to resolve [#3400](https://github.com/rust-lang/crates.io/issues/3400).
=> Add API endpoint to receive alerts of exposed API tokens from GitHub

src/controllers/github/secret_scanning.rs, src/tests/github_secret_scanning.rs, src/tests/util/github.rs
This PR builds on top of #5495 and improves the code a little bit more. See the individual commit messages for more details.
=> GitHub Secret Scanning improvements

src/controllers/github/secret_scanning.rs, src/tests/github_secret_scanning.rs, src/util.rs, src/util/token.rs
We don't save tokens in plaintext in the database, so the new secret scanning endpoint needs to look for the *hashed* token instead of the plaintext token.
/cc @dangardner :)
=> github/secret_scanning: Check for *hashed* tokens

src/controllers/github/secret_scanning.rs
Even if the tokens are already leaked on GitHub we shouldn't write them to the logs. Instead we will log the token ID.
=> github/secret_scanning: Adjust logging content

src/controllers/github/secret_scanning.rs, src/tests/github_secret_scanning.rs
We should not send emails for already revoked tokens.
=> github/secret_scanning: Avoid duplicate emails

src/controllers/github/secret_scanning.rs, src/models/user.rs, src/tests/github_secret_scanning.rs
When a token has already been revoked we will return to GitHub that it was a "true positive" now, but we skip sending out a notification email to the owner since we don't allow unrevoking tokens.
This PR also extracts a `send_notification_email()` function, which ensures that an error while sending emails will not cause other tokens to not be revoked.
=> github/secret_scanning: Consider revoked tokens as true positive

src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/version/yank.rs, src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_crate_scope.json, src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_endpoint_scope.json, src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_wildcard_crate_scope.json, src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_crate_scope.json, src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_endpoint_scope.json, src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_wildcard_crate_scope.json, src/tests/owners.rs, src/tests/routes/crates/versions/yank_unyank.rs
This PR adjusts our `AuthCheck` calls for the three relevant endpoints (publish, change owner, yank) to check the token scope restrictions if the token has any.
Note that for the publish operation we unfortunately need an extra database query to determine if the request is trying to publish a new crate or a new version for an existing crate. This query is performed outside of the existing database transaction since we have somewhat relaxed consistency requirements here.
In the worst case, two new crates with the same name are published concurrently, which would require both requests to have a `publish-new` token scope.
Related: 
=> Implement token scope restrictions for our endpoints

Cargo.lock, Cargo.toml, cargo-registry-index/Cargo.toml, cargo-registry-s3/Cargo.toml, src/controllers/helpers/pagination.rs, src/metrics/log_encoder.rs
This should temporarily resolve https://github.com/rust-lang/crates.io/issues/5646 until we figure out what exactly went wrong and why the background worker still seems to be running correctly despite the Sentry error reports.
=> Revert `base64` dependency upgrade

Cargo.lock, conduit-axum/Cargo.toml, conduit-axum/src/fallback.rs, src/util/tracing.rs
This slightly improves how internal server errors are logged and reported to Sentry.
=> conduit-axum: Improve internal server error handling

src/middleware/log_request.rs
https://github.com/rust-lang/crates.io/pull/3399 added support for including the nginx processing time in the response time calculation, but we currently don't know what exactly the overhead of the nginx processing is. This PR adds an additional field to our HTTP request/response logs, if the time differs by 1+ milliseconds to be able to answer that question.
=> middleware/log_request: Add `nginx_time` field if it is non-zero

src/middleware/log_request.rs
Reverts rust-lang/crates.io#5655
I've seen enough... 😅 
The result of this experiment is that `nginx_time` was actually negative in all cases where it was logged, which essentially means that `req.elapsed()` is as good of a guess as using the `X-Request-Start` header. In any case it looks like the overhead from running nginx in front of our app is negligible.
=> Revert "middleware/log_request: Add `nginx_time` field if it is non-zero"

triagebot.toml
We're not really using this bot (anymore?).
=> Remove obsolete `triagebot.toml` config

src/email.rs
Using `add_custom_metadata()` in the email code makes it hard to port the `log_request` middleware to axum, due to the `CUSTOM_METADATA` thread local which appears to be hard to migrate into the async world. The easiest solution for now is to use `tracing` calls directly instead and log the messages outside of the regular HTTP traffic logs.
Related:
- https://github.com/rust-lang/crates.io/pull/4627
=> email: Use `tracing` to log errors and successes

Cargo.lock, Cargo.toml, src/headers.rs, src/lib.rs, src/middleware/log_request.rs
This is meant to eventually replace the equivalent `conduit` middleware once it is feature complete. Until then we only log with `debug` level, which does not show up in production logs.
The two missing pieces are custom metadata and the `error` field. I've decided to put those into dedicated PRs since these changes are a bit more involved... 😅
=> Implement experimental `log_requests` axum middleware

src/auth.rs, src/controllers/helpers/pagination.rs, src/controllers/krate/publish.rs, src/controllers/version/downloads.rs, src/middleware/balance_capacity.rs, src/middleware/block_traffic.rs, src/middleware/log_request.rs, src/middleware/normalize_path.rs, src/middleware/require_user_agent.rs, src/router.rs
This requires us to go back to putting custom metadata in a request extension, but this time we're putting it in a `Arc<Mutex<Vec>>` to make it extra complicated... and compatible with axum middlewares 😅
=> middleware/log_request: Add custom metadata fields to `axum` logging

src/bin/server.rs, src/middleware.rs, src/middleware/log_request.rs, src/middleware/normalize_path.rs
This PR ports our `normalize_path` middleware from `conduit` to `axum`.
Since this middleware needs to run before the axum `Router` is involved, it needs to be wrapped around the router as suggested by https://docs.rs/axum/0.6.1/axum/middleware/index.html#rewriting-request-uri-in-middleware. 
This also means that the middleware is running before the request logging middleware, so some changes there were also necessary to make it log the same field contents as before.
=> middleware/normalize_path: Migrate to `axum`

src/tests/unhealthy_database.rs
These tests have been quite flaky on CI lately, so maybe increasing the timeout will fix the issue... 🤷‍♂️
=> tests/unhealthy_database: Increase timeout to 2 sec

Cargo.lock, Cargo.toml, src/app.rs, src/auth.rs, src/config.rs, src/controllers/user/session.rs, src/lib.rs, src/middleware.rs, src/middleware/session.rs, src/tests/authentication.rs, src/tests/util.rs, src/tests/util/test_app.rs
This PR re-implements the `SessionMiddleware` from `conduit-cookie` based on `axum` instead. 
Due to the different request lifetimes in both worlds I had to use an `Arc<RwLock<...>>` for this middleware, which makes it hard to keep the same `session()` and `session_mut()` APIs. The new APIs appear to work well enough for now though.
=> Implement axum-based `session` middleware

Cargo.toml, conduit-axum/Cargo.toml, conduit-axum/src/fallback.rs, src/middleware.rs, src/middleware/update_metrics.rs
Just like some of the previous PRs, this PR is migrating yet another conduit-based middleware to be an `axum` middleware instead :)
=> middleware/update_metrics: Migrate to `axum`

src/config.rs, src/middleware/require_user_agent.rs, src/tests/util/test_app.rs
see https://github.com/rust-lang/crates.io/commit/0ef1e2b84a11e4d569acfad7cf9b4ef8bd730148
This will make it easier to access the value from axum-based middlewares.
=> middleware/require_user_agent: Move `cdn_user_agent` field into server `config`

src/auth.rs, src/controllers/helpers/pagination.rs, src/controllers/krate/publish.rs, src/controllers/version/downloads.rs, src/middleware.rs, src/middleware/balance_capacity.rs, src/middleware/block_traffic.rs, src/middleware/log_request.rs, src/middleware/require_user_agent.rs, src/router.rs
This allows us to call `add_custom_metadata()` on both `conduit::RequestExt` and `http::Request`
=> middleware/log_requests: Extract `CustomMetadataRequestExt` trait

src/middleware.rs, src/middleware/block_traffic.rs, src/tests/server.rs, src/tests/snapshots/all__server__block_traffic_via_arbitrary_header_and_value.snap, src/tests/util/response.rs
This PR migrates our header-based traffic blocking middleware to axum. It is slightly different from the original `conduit` middleware in that we perform the iteration inside the middleware instead of applying the middleware N times.
=> middleware/block_traffic: Migrate to `axum`

Justfile
`just` is like `make` but has simpler syntax and avoids the complexity
of a build system. To install `just`, run `cargo install just`.
This PR adds commands for squashing the index and purging the build
cache. Both are expected to run against a Heroku app, i.e. staging or
production. For example `just env=staging squash-index` will squash the
index for the `crates-io-staging` staging environment.
=> Add a `Justfile` with some admin commands

src/boot/categories.toml
There's one for cryptocurrencies, but not for traditional money.
=> Add a category for finance

Cargo.lock, Cargo.toml, src/middleware.rs, src/middleware/static_or_continue.rs
This PR is migrating most of our static file serving from `conduit` to `axum`.
Previously the middleware was configurable with a path, but `axum` middlewares make this a bit more complicated (can't use `from_fn()`). Since we only need this twice at the moment it was easiest to duplicate the code for now.
=> middleware/static_or_continue: Migrate to `axum`

src/app.rs, src/middleware.rs, src/middleware/ember_html.rs
Another PR, another middleware migrated from `conduit` to `axum`... 🚀 
Not much to say about this one, other than that the `fastboot_client` is now an async `reqwest::Client`
=> middleware/ember_html: Migrate to `axum`

src/config.rs, src/config/balance_capacity.rs, src/middleware.rs, src/middleware/balance_capacity.rs, src/tests/util/test_app.rs
Instead of reading all environment variables when we create the middleware, we outsource this to the server config construction and then access the relevant values via `request.app().config`.
The reason for this change is that `axum` makes it a bit harder for use to use "configurable" middlewares, so if we can rely on the server config it will make their implementation significantly easier.
=> Simplify `BalanceCapacity` middleware

src/app.rs, src/middleware.rs, src/middleware/balance_capacity.rs
This is the final middleware that needed to be migrated to `axum`. The rest of the middlewares are only relevant to the `conduit` route handlers.
=> middleware/balance_capacity: Migrate to `axum`

cargo-registry-index/Cargo.toml, cargo-registry-markdown/Cargo.toml, cargo-registry-s3/Cargo.toml
This allows us to remove `resolver = 2`.
Signed-off-by: Yuki Okushi <jtitor@2k36.org>
=> Upgrade edition to 2021 on all the subcrates

Cargo.lock, Cargo.toml, src/admin/yank_version.rs, src/background_jobs.rs, src/bin/background-worker/main.rs, src/bin/enqueue-job.rs, src/controllers/krate/publish.rs, src/controllers/version/yank.rs, src/db.rs, src/lib.rs, src/swirl.rs, src/swirl/errors.rs, src/swirl/runner.rs, src/swirl/runner/event.rs, src/swirl/storage.rs, src/tests/util/test_app.rs, src/worker/daily_db_maintenance.rs, src/worker/dump_db.rs, src/worker/dump_db/gen_scripts.rs, src/worker/git.rs, src/worker/mod.rs, src/worker/readmes.rs, src/worker/update_downloads.rs
This PR vendors about 800 lines of code (of which ~150 are tests). This PR is split off from my port to diesel 2.0. In particular, the new version of diesel requires that a `&mut PgConnection` be passed around and it should be much easier to finish that port once we can modify this in-tree.
This also addresses a long standing pain point, which is that due to the use of `inventory` the background workers (and thus a lot of unnecessary dependencies) end up linked into every binary increasing build times and file sizes.
The amount of additional code for us to maintain can probably be trimmed further. For now I've simply extracted this from my `diesel2` branch and made sure it compiles and I think this is ready for initial review. Locally, 4 of the `unhealthy_database` tests are failing for …
=> Vendor a portion of the `swirl` crate

src/middleware.rs, src/middleware/block_traffic.rs, src/util/errors/json.rs
This corresponds roughly to https://github.com/rust-lang/crates.io/blob/bbcc09946f83eda077da4bda1ef1879e510fb195/src/router.rs#L190-L195
Note that with axum we can implement this as a middleware because axum middlewares run after the routing layer by default.
=> Implement `block_traffic::block_routes` middleware

src/lib.rs, src/router.rs
This PR moves the `axum::Router` creation code closer to the code that builds the `conduit` router. This will make it easier to move route handlers from one router to the other.
=> router: Extract `build_axum_router()` function

src/router.rs
This is recommended by the Sentry docs (see https://docs.sentry.io/platforms/javascript/enriching-events/transaction-name/)
=> sentry: Include request method in transaction name

Cargo.lock, Cargo.toml, src/controllers.rs, src/controllers/git.rs, src/lib.rs, src/router.rs
This migrates our dev-only git index serving code from `conduit-git-http-backend` to an `axum` route handler.
=> Migrate `conduit-git-http-backend` code to `axum`

Cargo.lock, Cargo.toml, src/middleware.rs
This dependency is no longer needed, now that we serve the static files via `axum`
Update: Removed `conduit-static` too, since it's also unused at this point 😅
=> Remove obsolete `conduit-conditional-get` dependency

src/middleware/static_or_continue.rs
No reason to have the same code twice if we can abstract it like this :)
=> middleware/static_or_continue: Extract common `serve()` function

conduit-axum/Cargo.toml
The `Hub::current() `and `Hub::run()` APIs are only available if the `client` feature of `sentry-core` is enabled, so let's enable it.
I'm not sure how this compiled before. I assume that it is related to us running the tests within the context of the workspace instead of compiling the libraries independently.
=> conduit-axum: Enable missing `client` feature for `sentry-core`

conduit-axum/src/fallback.rs, conduit-axum/src/tests.rs
`axum` has a simpler API than the `Response::builder()`, so let's use it...! :D
As an additional bonus we now send the correct `Content-Type` header too.
=> conduit-axum: Simplify `server_error_response()` function

src/swirl/errors.rs
This PR adjusts the error types of the `swirl` library to use `thiserror` to derive the `Error` trait and other useful traits. The resulting code should be largely equivalent.
=> swirl/errors: Use `thiserror`

src/router.rs, src/util/errors.rs
There is no need for this struct to be exported and then imported somewhere else if only a single module is using it.
=> Move `AppErrToStdErr` into the only file that uses it

src/metrics/instance.rs
`AppResult` is a complicated type due to its error type. For the `metrics` module there is no need to use it since we can just return the original `prometheus::Result<_>` instead.
=> metrics/instance: Narrow return types

src/controllers/helpers/pagination.rs, src/controllers/krate/search.rs
We can access the app state through the passed-in request. There is no need to save it in a field called `limit_page_numbers`.
=> helpers/pagination: Simplify `limit_page_numbers` API

src/controllers/krate/publish.rs, src/lib.rs, src/middleware.rs, src/middleware/app.rs
This brings us closer to what the `axum` implementation uses :)
=> middleware/app: Use `AppState` struct instead of raw `Arc<App>`

src/controllers/krate/publish.rs, src/controllers/user/session.rs, src/controllers/version/downloads.rs
Each `req.app()` calls needs to perform a typemap lookup, so this PR deduplicates a few of them where possible.
=> Simplify `req.app()` calls

src/middleware/app.rs
Once the request is dropped the app state clone will automatically be dropped too
=> middleware/app: Remove unnecessary `after()` block

src/auth.rs, src/controllers.rs, src/controllers/category.rs, src/controllers/crate_owner_invitation.rs, src/controllers/keyword.rs, src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/krate/search.rs, src/controllers/metrics.rs, src/controllers/team.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/user/session.rs, src/controllers/version/deprecated.rs, src/controllers/version/downloads.rs, src/controllers/version/metadata.rs, src/controllers/version/yank.rs, src/db.rs
We call these methods directly on the `App` instead to make the calls closer to what they will look like with `axum`
=> db: Remove `RequestTransaction` trait

src/util/tracing.rs
This allows us to run the tests with e.g. `RUST_LOG=all::record=debug` to enable debug logging of our request recorder.
=> tracing: Allow `RUST_LOG` usage in test mode

Cargo.toml, src/bin/enqueue-job.rs
```
Usage: enqueue-job <COMMAND>
Commands:
update_downloads      
dump_db               
daily_db_maintenance  
squash_index          
normalize_index       
help                  Print this message or the help of the given subcommand(s)
Options:
-h, --help  Print help information
```
```
Usage: enqueue-job dump_db <DATABASE_URL> [TARGET_NAME]
Arguments:
<DATABASE_URL>  [env: READ_ONLY_REPLICA_URL]
[TARGET_NAME]   [default: db-dump.tar.gz]
Options:
-h, --help  Print help information
```
=> bin/enqueue-job: Use `clap` to parse commands and generate help text

src/bin/crates-admin.rs
We don't need the extra `Opts` struct, we can instead just use the enum directly.
=> bin/crates-admin: Simplify `clap` usage

src/admin/enqueue_job.rs, src/admin/mod.rs, src/bin/crates-admin.rs, src/bin/enqueue-job.rs
This should allow us to get rid of the `enqueue-job` binary, which should hopefully improve link and compile times a little bit.
=> bin/crates-admin: Add `enqueue-job` subcommand

.github/workflows/ci.yml
This makes GitHub Actions only run one CI pipeline per branch and cancels any ongoing previous runs of the same branch when a new branch head is pushed.
=> CI: Cancel obsolete runs for the same branch

.github/workflows/ci.yml, .github/workflows/coverage.yml
In #5775 I forgot that the default `versioning` scheme of crates in renovatebot is `cargo`. This PR adjusts it to use `semver` instead, to avoid renovatebot from updating the versions from e.g. `1.4.1` to `=1.4.1`.
=> renovate: Add missing `versioning=semver` instructions

src/tests/util/response.rs, src/util.rs
`application/json` is defined as unicode (see https://www.ietf.org/rfc/rfc4627.txt) and the media type has no `charset` support defined for it (see https://www.iana.org/assignments/media-types/application/json)
also, this makes the header the same as what `axum` sends by default... 😅
=> Remove redundant `charset` from `application/json` content type response header

conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, src/controllers/helpers/pagination.rs, src/middleware.rs, src/middleware/log_request.rs, src/router.rs, src/util/errors.rs, src/util/errors/json.rs
Instead of having some `AppError` implementations return a response and others be treated as some other kind of error, this PR changes the code to treat all `AppError` implementations the same way by enforcing the http response conversion.
Note that this required a refactoring of the `error` log field, which we are now setting via a response extension when we convert the error into a response.
The reason for this change is to bring us closer to how `axum` handles errors, which also requires all `Result::E` types to implement `IntoResponse`.
=> util/errors: Implement `response()` for all `AppError`

conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, src/middleware/log_request.rs, src/router.rs
This makes it possible to set the `cause` field when only the `response`, but not the `request` is available.
=> Use `CauseField` response extension to set `cause` log field

conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, conduit-axum/src/tokio_utils.rs, src/controllers.rs, src/controllers/conduit_axum.rs, src/controllers/keyword.rs, src/router.rs
This PR migrates the `GET /keywords/:keyword_id` route to `axum` by implementing a `conduit_compat()` function, which handles the sync/async switching and converts `AppError` into a corresponding axum `Response`.
=> Migrate `GET /keywords/:keyword_id` route to `axum`

src/util.rs
`to_string()` calls `from_utf8_unchecked()` internally, which is unnecessary, if we directly convert it back to bytes again.
=> Simplify JSON serialization in `json_response()`

src/controllers/conduit_axum.rs, src/util/errors.rs
By implementing `IntoResponse` for `Box<dyn AppError>` we can simplify the `conduit_compat()` function a little bit :)
=> axum: Simplify `conduit_compat()` function

src/controllers/helpers/pagination.rs
`add_custom_metadata()` no longer requires `req` to be mutable :)
=> helpers/pagination: Remove unnecessary `mut` keyword

src/controllers.rs
These don't actually use `&self` so they might as well be implemented directly on the trait
=> RequestUtils: Move `redirect()` and `json()` implementation into the trait

src/middleware/block_traffic.rs
`HeaderValue` has a `PartialEq` implementation for strings, so there is no need to convert it to a string before comparing.
=> middleware/block_traffic: Remove unnecessary str conversion

src/controllers/helpers/pagination.rs, src/util/request_helpers.rs
This trait extends the `HeaderMap` struct and adds a `get_str_or_default()` method to it, which behaves roughly like the old function.
=> Replace `request_header()` fn with `HeaderMapExt` trait

conduit-axum/src/adaptor.rs, conduit-axum/src/fallback.rs, conduit-axum/src/tests.rs
The only part of crates.io that needed this was the `git-http-backend` code, which is using axum directly now, so there is no need for this anymore in the `conduit-axum` compatibility layer.
=> conduit-axum: Remove obsolete `SocketAddr` handling code

conduit-axum/src/fallback.rs
... instead of adding the handler to the extensions of each request.
This has the additional advantage that `ConduitAxumHandler` can also be used in e.g. `.route(..., get(handler))` calls, which will eventually let us migrate away from `conduit-router` and use `axum` for routing.
=> conduit-axum: Use `ConduitAxumHandler` struct to save `conduit::Handler`

conduit-axum/examples/server.rs, conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, conduit-axum/src/server.rs
#5798 prepared for it, and this PR demonstrates how the `ConduitAxumHandler` struct can be used as an adapter between a conduit handler function and the `axum::Router`.
=> conduit-axum/examples: Use `ConduitAxumHandler` to implement route handlers

conduit-axum/src/adaptor.rs, conduit-axum/src/fallback.rs
We're not using this anywhere anymore and `conduit` does not appear to use it internally either.
=> conduit-axum: Remove `StartInstant` extension

src/controllers.rs, src/controllers/category.rs, src/controllers/crate_owner_invitation.rs, src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/metrics.rs, src/controllers/team.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/util.rs, src/controllers/version.rs, src/controllers/version/deprecated.rs, src/controllers/version/downloads.rs
This simplifies how we access path parameters and prepares for adding support for `axum`
=> Extract `RequestParamExt::param()` extension fn

conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, src/controllers/util.rs
This PR extends the `RequestParamExt` implementation from #5801 with support for path parameters from the `axum::Router`
=> RequestParamExt: Use `axum` path parameters if available

src/middleware/app.rs, src/router.rs
This PR makes use of the `ConduitAxumHandler` struct introduced in #5798 to migrating our routing from `conduit` to `axum`. Note that the 404 response handling is still done by `conduit` at this point and will be migrated in a follow-up PR :)
=> Use `axum` router

conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, conduit-axum/src/tests.rs
Now that we have `ConduitAxumHandler` we don't need the `ConduitFallback` trait anymore :)
=> conduit-axum: Remove obsolete `ConduitFallback` trait

src/controllers/helpers/pagination.rs
Deserializing to a `serde_json::Value` and comparing against `json!()` gives us the same benefits, but with much less code :)
=> pagination: Simplify `assert_pagination_error()` fn

conduit-axum/src/adaptor.rs, conduit-test/src/lib.rs, conduit/src/lib.rs
We are not using any of these inside the `crates.io` codebase, so we might as well delete them... 🧹
=> conduit: Remove obsolete functions from the `RequestExt` trait

src/tests/util.rs
This function is doing the exact same thing as `get_with_query()` so there is really no need to have both of them 😅
=> tests/util: Remove redundant `get_query()` fn

conduit-axum/src/request.rs, conduit-axum/src/tests.rs, conduit-test/src/lib.rs, conduit/src/lib.rs, src/controllers.rs, src/controllers/krate/search.rs, src/controllers/version/deprecated.rs, src/tests/util.rs
This brings the `conduit` API closer to the `http::Request` struct
=> conduit: Replace `path()` and `query_string()` with `uri()`

conduit/src/lib.rs
There is no need for a type alias if we can just re-export `Extensions` from the `http` crate
=> conduit: Simplify `Extensions` export

conduit-test/src/lib.rs
These two methods don't appear to be used anywhere in our project, so we might as well remove them
=> conduit-test: Remove unused `with_method()` and `with_path()` fns

conduit-axum/src/request.rs, conduit-test/src/lib.rs, conduit/src/lib.rs
Nothing is using this anymore, so we might as well remove it.
Related:
-  #5813
=> conduit: Remove obsolete `http_version()` fn from `RequestExt` trait

conduit-test/src/lib.rs, src/controllers/helpers/pagination.rs, src/tests/util.rs
We can pass the query parameters directly into the `MockRequest::new()` call instead, since that is passing the path directly into the `uri()` method of the `Request::builder()`.
=> conduit-test: Remove `with_query()` fn

conduit/src/lib.rs
what more to say... if we don't use something, then we should probably remove it 😅
=> conduit: Remove unused `HttpResult` type

src/tests/util.rs
This is only relevant for the `git-http-backend` code, which is disabled in test mode.
=> tests/util: Remove unnecessary `ConnectInfo` extension usage

conduit-axum/examples/server.rs, conduit-axum/src/body.rs, conduit-axum/src/lib.rs, conduit-axum/src/response.rs, conduit-axum/src/tests.rs, conduit-test/src/lib.rs, conduit/src/lib.rs, src/controllers.rs, src/controllers/helpers/pagination.rs, src/controllers/metrics.rs, src/controllers/token.rs, src/middleware.rs, src/util.rs, src/util/errors.rs
Instead of using a custom enum, we can rely on the `bytes::Bytes` type, which brings us closer to what `hyper` and `axum` are using internally too.
=> conduit: Replace custom `Body` enum with `bytes::Bytes`

Cargo.lock, conduit-test/Cargo.toml, conduit-test/src/lib.rs, src/tests/util.rs
There is no need to buffer in between anymore. We can just convert the body directly.
=> conduit-test: Simplify `MockRequest` conversion code

conduit-axum/src/fallback.rs
`axum` allows us to simplify this function quite a bit 😅
=> conduit-axum: Simplify `bad_request()` fn

Cargo.lock, conduit-test/Cargo.toml, conduit-test/src/lib.rs, src/controllers/helpers/pagination.rs, src/router.rs
There is no reason anymore for `MockRequest` to implement `conduit::RequestExt` so this PR refactors it away and then finally removes the `conduit` dependency of the `conduit-test` package. The `MockRequest` is now mostly a request builder for our test suite and somewhat unrelated to `conduit` itself.
=> conduit-test: Remove `conduit` dependency

conduit/src/lib.rs
These can be accessed directly on the `ConduitRequest` instead :)
=> conduit::RequestExt: Remove redundant accessor methods

src/middleware.rs, src/middleware/block_traffic.rs, src/middleware/require_user_agent.rs
It's easier to import what we need directly and IDE completion makes this quite straight-forward :)
=> middleware: Remove obsolete `prelude` module

conduit/src/lib.rs, src/controllers.rs, src/controllers/crate_owner_invitation.rs, src/controllers/github/secret_scanning.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/token.rs, src/controllers/user/me.rs
The end of an era... sort of 😄 
The remaining two methods are inlined and moved to the `RequestUtils` trait respectively.
=> conduit: Remove `RequestExt` trait

src/controllers/helpers/pagination.rs
We are already checking the error serialization elsewhere. In this case it is sufficient to check for the error message.
This also allows us to be more flexible with the `response.body()`, since using `hyper::Body` would cause quite a bit of async issues for this assertion.
=> helpers/pagination: Simplify `assert_pagination_error()` fn

conduit-axum/examples/server.rs, conduit-axum/src/conduit.rs, conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, conduit-axum/src/tests.rs, src/router.rs
Instead of using `http::Response<Bytes>` we can use `axum::Response` to bring us closer to being able to return `axum` responses from the crates.io request handlers.
=> conduit::Handler: Expect `axum::Response` return values

conduit-axum/examples/server.rs, conduit-axum/src/conduit.rs, conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, conduit-axum/src/tests.rs, src/controllers.rs, src/controllers/helpers.rs, src/controllers/metrics.rs, src/controllers/token.rs, src/router.rs, src/util.rs
This means we need one less conversion step in the `Handler for C` implementation, and it also means we can now use anything else that implements `IntoResponse` to build responses. 🎉
Related:
- https://github.com/rust-lang/crates.io/pull/5843
=> Change request handler return type to `axum::Response`

conduit-axum/examples/server.rs, conduit-axum/src/conduit.rs, conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, conduit-axum/src/tests.rs, src/controllers/category.rs, src/controllers/crate_owner_invitation.rs, src/controllers/github/secret_scanning.rs, src/controllers/keyword.rs, src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/krate/search.rs, src/controllers/metrics.rs, src/controllers/team.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/user/session.rs, src/controllers/version/deprecated.rs, src/controllers/version/downloads.rs, src/controllers/version/metadata.rs, src/controllers/version/yank.rs, src/router.rs
This matches what `axum` does and makes our migration a little easier :)
=> Pass `request` ownership into the request handlers

src/controllers.rs, src/controllers/category.rs, src/controllers/conduit_axum.rs, src/controllers/crate_owner_invitation.rs, src/controllers/github/secret_scanning.rs, src/controllers/helpers.rs, src/controllers/keyword.rs, src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/krate/search.rs, src/controllers/metrics.rs, src/controllers/team.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/user/session.rs, src/controllers/version/deprecated.rs, src/controllers/version/downloads.rs, src/controllers/version/metadata.rs, src/controllers/version/yank.rs, src/github.rs, src/router.rs, src/util.rs, src/util/errors.rs, src/util/errors/json.rs
This PR creates a new `BoxedAppError` type alias, and in return it gets rid of the `AppResponse` and `EndpointResult` type aliases. This makes it a little more obvious what types our request handlers are returning, which will be relevant for the next PR 😉
=> Clean up type aliases

src/controllers.rs, src/controllers/helpers.rs, src/controllers/version/metadata.rs, src/middleware.rs, src/router.rs, src/util.rs
This PR finally makes the return types of our own request handlers compatible with the native ones from `axum`.
In other words: our own request handlers can now return `impl IntoResponse` 🎉
=> Allow request handlers to return any `impl IntoResponse`

src/controllers.rs, src/controllers/category.rs, src/controllers/crate_owner_invitation.rs, src/controllers/github/secret_scanning.rs, src/controllers/keyword.rs, src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/krate/search.rs, src/controllers/team.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/user/session.rs, src/controllers/version/deprecated.rs, src/controllers/version/downloads.rs, src/controllers/version/metadata.rs
This PR brings us a little closer to how request handlers with `axum` normally look like :)
=> RequestUtils: Replace `json()` fn with direct `axum::Json` usage

conduit-axum/src/conduit.rs, conduit-axum/src/fallback.rs, src/controllers/helpers/pagination.rs, src/router.rs
This will allow us to use `ConduitRequest` also in regular `axum` request handlers 😁
=> ConduitRequest: Convert into struct with `FromRequest` implementation

src/controllers/conduit_axum.rs, src/controllers/keyword.rs, src/util/errors.rs
Instead of dealing with axum responses we can use `AppResult`, which implements `IntoResponse` these days :)
=> conduit_compat(): Remove unnecessary `into_response()` calls

src/controllers/category.rs, src/controllers/crate_owner_invitation.rs, src/controllers/github/secret_scanning.rs, src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/krate/search.rs, src/controllers/metrics.rs, src/controllers/team.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/user/session.rs, src/controllers/version/deprecated.rs, src/controllers/version/downloads.rs, src/controllers/version/metadata.rs, src/controllers/version/yank.rs, src/router.rs
This replaces the `conduit()` usage in the router with async functions, using `conduit_compat()` inside to encapsulate the synchronously blocking code.
This will finally allow us to use other `axum` extractors in these functions too :)
=> Convert all request handlers to async functions

conduit-axum/src/conduit.rs, conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, src/router.rs
Now that we use async request handlers everywhere, a lot of the support code in `conduit-axum` has become obsolete. This PR removes a few of the unused constructs.
=> conduit-axum: Remove obsolete code

src/background_jobs.rs, src/worker/daily_db_maintenance.rs, src/worker/git.rs, src/worker/update_downloads.rs
We only need structs like this when we want to save parameters for the queued job, but for a job without parameters these appear to be unnecessary.
=> background_jobs: Remove empty structs

conduit-test/src/lib.rs, src/controllers/helpers/pagination.rs
This slightly simplifies the `MockRequest` struct :)
=> MockRequest: Remove unnecessary `Cursor` wrapper

conduit-axum/src/conduit.rs, conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, src/controllers.rs, src/controllers/category.rs, src/controllers/crate_owner_invitation.rs, src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/metrics.rs, src/controllers/team.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/util.rs, src/controllers/version.rs, src/controllers/version/deprecated.rs, src/controllers/version/downloads.rs, src/controllers/version/metadata.rs, src/controllers/version/yank.rs
This PR removes the `req.param()` API in favor of using the `Path` extractor from `axum`. This makes our `FromRequest` implementation for `ConduitRequest` a bit simpler and will eventually allow us to remove `ConduitRequest` completely.
=> Use `Path` extractor in request handlers

conduit-axum/src/conduit.rs, src/controllers.rs, src/controllers/github/secret_scanning.rs, src/controllers/krate/publish.rs, src/controllers/token.rs
see commit messages 😉 
The move to `ConduitRequest` will let us implement `RequestUtils` for any `Request<...>` instead of just `ConduitRequest`
=> Simplify and move `content_length()` function

src/auth.rs, src/controllers.rs, src/controllers/crate_owner_invitation.rs, src/controllers/helpers/pagination.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/util.rs, src/controllers/version/yank.rs
This makes a few of our traits and functions more reusable, by allowing them to work with any `Request`, not just `ConduitRequest` (aka. `Request<Cursor<Bytes>>`).
=> Use generic `Request` parameters where possible

src/controllers/token.rs, src/tests/routes/me/tokens/create.rs
We have a global request body size limit these days, so this request handler specific check is somewhat redundant now.
=> controllers/token: Remove obsolete `content_length()` check

src/controllers/github/secret_scanning.rs
The `Bytes` extractor already has a request body limit built in, so we don't the extra `content_length()` check.
=> controllers/github: Use `axum` extractors

app/components/crate-sidebar.hbs, app/components/crate-sidebar.js, app/templates/crate/version.hbs
This adds a `cargo add` instruction to the crate sidebar, with clipboard support:
This came about after @beeb [made a good point](https://hachyderm.io/@beeb/109641418504476058) that copying a snippet from crates.io prevents typosquatting, and not having a snippet for `cargo add` is reason to avoid it.
=> Add `cargo add` instruction to crate-sidebar

src/auth.rs
This helps a little bit with keeping a clear separation between authentication and authorization.
=> auth: Move authentication-related code back into `authenticate_user()` fn

src/controllers/crate_owner_invitation.rs, src/github.rs, src/uploaders.rs, src/util/errors.rs
Previously it was impossible to call this function directly with a `String`. If instead `internal(&the_string)` was used then an unnecessary clone of the original string was performed.
=> util/errors: Simplify `internal()` fn

src/auth.rs, src/controllers/crate_owner_invitation.rs
Using an enum makes it a bit clearer how a user was authenticated and prepares us for a future where we might have a third or fourth authentication option.
=> auth: Convert `AuthenticatedUser` struct to `Authentication` enum

src/auth.rs, src/controllers.rs, src/controllers/helpers/pagination.rs, src/controllers/util.rs, src/middleware/app.rs, src/middleware/log_request.rs, src/middleware/session.rs
This trait allows us to implement things independent from passing in `Parts` or a full `Request`. This makes it easier to reuse code when implementing the `FromRequestParts` trait of `axum`.
=> Implement `RequestPartsExt` trait

src/auth.rs
This makes our authentication code a little more composable. Not relevant yet, but soooon..... 😉
=> auth: Extract `authenticate_via_cookie/token()` fns

src/controllers/krate/publish.rs
We can use `serde_json::from_slice()` instead, which removes the need for the string conversion.
=> publish: Skip unnecessary `String::from_utf8()` call

src/auth.rs, src/controllers/crate_owner_invitation.rs, src/controllers/krate/follow.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/krate/search.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/version/yank.rs
The authentication check previously requested a second database connection from the pool for no good reason. This PR changes it to reuse the existing database connections of these request handlers.
@jtgeibel I believe this also simplifies the Diesel v2 upgrade?
=> auth: Reuse existing database connections

src/controllers/github/secret_scanning.rs
Related:
- https://github.com/rust-lang/crates.io/pull/5889
=> controllers/github: Reuse existing database connection in `send_notification_email()` call

src/controllers/crate_owner_invitation.rs
Related:
- https://github.com/rust-lang/crates.io/pull/5889
=> controllers/crate_owner_invitations: Avoid second database connection request

src/background_jobs.rs, src/db.rs, src/swirl/runner.rs, src/tests/all.rs
This is a backport of some work done in #4892. Once this lands it should be easy to finally land the port to diesel 2.0!
The 2nd commit includes 2 quick fixes to avoid obtaining 2 connections at the same time (which is now necessary to pass tests). We could do some refactoring to reuse an existing connection instead of dropping and reobtaining one, but these endpoints aren't performance critical so I'm not too worried about it.
=> Reuse existing connection when executing each background job

conduit-axum/src/conduit.rs, src/controllers/krate/publish.rs
We're down to using this in only one place at this point, so we might as well inline and remove the method... 🧹
=> conduit-axum: Inline `content_length()` method

src/controllers/krate/publish.rs
We're already checking the payload size right before the call, so there is no reason for us to check it again here.
=> controllers/publish: Remove redundant `LimitErrorReader` usage

cargo-registry-s3/lib.rs, src/controllers/krate/publish.rs, src/uploaders.rs
Previously, we were buffering the incoming `hyper::Body` into a `bytes::Bytes` instance, which we then wrapped in a `Cursor`, which we then used as a `Read` implementation to fill a `Vec<u8>`. This was somewhat wasteful because it meant that we were buffering the tarball payload twice: once in the `Bytes` and once more in the `Vec<u8>`.
This PR changes the implementation to take more advantage of the `Arc`-like behavior of `bytes::Bytes`. We implement a `split_body()` function, which turns one `Bytes` instance into two `Bytes`, one for the JSON metadata, and one for the tarball payload. This will just shuffle around a few pointers underneath, without performing any additional memory allocation.
In this PR we also slightly refactor the S3 uploader implementation to not require a redundant …
=> publish: Avoid redundant buffer copies

conduit-axum/src/conduit.rs, src/controllers/crate_owner_invitation.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/token.rs, src/controllers/user/me.rs
Our request handlers don't need this extra wrapper anymore and can use the `Bytes` instance directly.
Related:
- #5903
=> ConduitRequest: Remove `Cursor` wrapper

src/controllers.rs, src/controllers/category.rs, src/controllers/crate_owner_invitation.rs, src/controllers/keyword.rs, src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/krate/search.rs, src/controllers/metrics.rs, src/controllers/team.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/user/session.rs, src/controllers/version/deprecated.rs, src/controllers/version/downloads.rs, src/controllers/version/metadata.rs, src/controllers/version/yank.rs
We can skip the request body buffering code if the request handler does not care about the body. Ideally we wouldn't need the `Parts` either, but they are still needed in a few cases for database connections, request metadata logging, etc.
=> Use `Parts` where request body is irrelevant

src/controllers.rs, src/controllers/category.rs, src/controllers/crate_owner_invitation.rs, src/controllers/krate/downloads.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/team.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/version/deprecated.rs, src/controllers/version/metadata.rs
When we only use the `Parts` or `Request` to get a database connection, then we might as well use the `State` extractor directly :)
=> Use `State` extractor where request metadata is irrelevant

src/app.rs, src/config.rs, src/github.rs, src/tests/util/test_app.rs
This was previously used for testing purposes, but is always set to the same value these days, so we might as well hardcode it.
=> RealGitHubClient: Remove obsolete `base_url` field

src/app.rs, src/config.rs, src/controllers/github/secret_scanning.rs, src/tests/util/test_app.rs
This ensures that debug logging `gh_client_secret` will not unintentionally leak our authentication credentials.
=> config: Use `ClientId` and `ClientSecret` wrappers for GitHub OAuth fields

src/auth.rs, src/controllers/user/session.rs, src/middleware/session.rs
This PR extracts a `SessionExtension` struct, which wraps the `Arc<RwLock<Session>>` with a nicer API. This also allows us to derive `FromRequestParts`, which makes it even easier to use inside request handler functions.
=> Simplify session extension usage

src/auth.rs, src/controllers/helpers/pagination.rs, src/controllers/krate/publish.rs, src/controllers/version/downloads.rs, src/middleware/balance_capacity.rs, src/middleware/block_traffic.rs, src/middleware/log_request.rs, src/middleware/require_user_agent.rs
This PR performs a few small refactorings on the `CustomMetadata` struct and related code. The goal of the PR is to make it easier to save a reference to the struct and use it to add request log metadata without having access to the `Request` itself.
=> Simplify request log metadata collection

conduit-axum/examples/server.rs, conduit-axum/src/conduit.rs, conduit-axum/src/fallback.rs, conduit-axum/src/lib.rs, conduit-axum/src/response.rs, conduit-axum/src/tests.rs
These type aliases were at this point both point to `axum::response::Response`, which we could just use directly instead.
=> conduit-axum: Replace `AxumResponse` and `HandlerResult` type aliases

src/tests/authentication.rs, src/tests/github_secret_scanning.rs, src/tests/routes/metrics.rs, src/tests/token.rs, src/tests/util.rs, src/tests/util/mock_request.rs
This will allow us to use `Request::builder()` directly where needed, instead of having to wrap it in a `MockRequest` instance. 🎉
=> MockRequest: Convert to type alias with extension methods on `MockRequestExt` trait

Cargo.lock, Cargo.toml, src/app.rs, src/controllers/version/downloads.rs
This will make it easier in the future to convert the download request handler to more async behavior :)
see https://github.com/moka-rs/moka#example-asynchronous-cache
=> moka: Use future-aware cache

src/app.rs, src/controllers.rs, src/controllers/category.rs, src/controllers/crate_owner_invitation.rs, src/controllers/github/secret_scanning.rs, src/controllers/keyword.rs, src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/krate/search.rs, src/controllers/metrics.rs, src/controllers/site_metadata.rs, src/controllers/team.rs, src/controllers/token.rs, src/controllers/user/me.rs, src/controllers/user/other.rs, src/controllers/user/session.rs, src/controllers/version/deprecated.rs, src/controllers/version/downloads.rs, src/controllers/version/metadata.rs, src/controllers/version/yank.rs, src/middleware/app.rs, src/middleware/balance_capacity.rs, src/middleware/block_traffic.rs, src/middleware/ember_html.rs, src/middleware/require_user_agent.rs, src/middleware/update_metrics.rs
This 1) makes `AppState` easier to use in request handlers and 2) replaces most `req.app()` calls with `AppState` usage in the request handlers and middlewares.
This will eventually allow us to remove most of the `Request` parameters in the request handlers.
=> Use `AppState` in request handlers

src/controllers/version/downloads.rs
By shifting things around a bit we can avoid calling the `conduit_compat()` function if we already have a cached `version_id`. This should slightly speed up the 80-90% case where the ID is already in our cache :)
=> Avoid worker thread for cached download requests

src/controllers/krate/metadata.rs
We are not performing any blocking operations in the call, so we can skip the worker thread in this case
=> GET /crates/:crate_id/:version/readme: Remove unnecessary `conduit_compat()` call

src/controllers/user/session.rs
We are not performing any blocking operations in the call, so we can skip the worker thread in this case
=> GET /api/private/session/begin: Remove unnecessary `conduit_compat()` call

src/config.rs
`split_once()` does basically the same thing internally as what we previously did manually.
=> Simplify `parse_traffic_patterns()` fn

src/background_jobs.rs, src/db.rs, src/swirl/runner.rs, src/tests/all.rs
This should resolve the deadlock issues seen in the initial implementation in #5837. The first commit reverts the revert done in #5909. The second commit then adds the connection pool back to the state available within `Job::perform()`, though now the pool is an `Option<_>` and only available in production. If test coverage of these background jobs is ever desired it could potentially be implemented with the existing infrastructure used in `unhealthy_database` tests.
=> Share the existing background job connection with (only) some jobs

src/boot/categories.toml
Ever since no_std crates gained the ability to use alloc, the usefulness of the "no-std" category has drastically declined. It used to be an indicator for whether a crate can be used in a bare metal embedded context (more precisely: where there is no OS and no dynamic memory management), but is now used for a lot of crates that rely on dynamic memory management.
Its current use is factually accurate (these crates *are* no_std), but also not very helpful.
This adds a new "no-alloc" category (under no-std, because no-alloc is not particularly meaningful when using std) with which crates that provide the "good old" no-std can advertise their properties.
It would be used primarily by embedded Rust crates, but library crates that go the extra mile to be usable on such systems could also use …
=> Add category no-std::no-alloc

src/boot/categories.toml
There are quite a few crates that fit this category: https://crates.io/search?q=geo
=> Add Geography category

Cargo.lock, cargo-registry-index/Cargo.toml
Reverts rust-lang/crates.io#5968
This has been causing issues with our background worker, that have to be resolved first, before we can update:
```
INFO background_worker: Booting runner
INFO background_worker: Cloning index
thread 'main' panicked at 'Failed to clone index: Failed to clone index repository
Caused by:
invalid or unknown remote ssh hostkey; class=Ssh (23); code=Certificate (-17)', src/bin/background-worker.rs:61:46
stack backtrace:
0: rust_begin_unwind
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
2: core::result::unwrap_failed
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
3: …
```
=> Revert "Update Rust crate git2 to v0.16.1 [SECURITY]"

src/boot/categories.toml
The accessibility category has many crates not related to assistive technologies (web crawlers, internationalization, audio parsers, date and time):
https://crates.io/categories/accessibility
I suspect that the description is too broad and not understood by people who aren't already familiar with the "accessibility" term.
=> Clarify a11y category description

src/github.rs
This should unblock the [Rust v1.67](https://github.com/rust-lang/crates.io/pull/6003) upgrade
=> Simplify `format!()` call

Cargo.lock, cargo-registry-index/Cargo.toml, cargo-registry-index/lib.rs
Previously, we were relying on libgit2 to check the hostkey fingerprint, but since our Heroku dynos do not have a `known_hosts` file, this couldn't actually have worked, which results in us not checking the fingerprints at all. 
https://github.com/rust-lang/crates.io/pull/5996 updates libgit2, which enables fingerprint checks by default. Due to the missing `known_hosts` file this broke our background worker though.
This PR enables custom fingerprint checks for `github.com` by hardcoding the fingerprints from https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints. As the code comment says, this is most likely good enough, but could eventually be replaced by a `known_hosts`-like environment variable.
=> Implement GitHub SSH certificate checks

cargo-registry-index/lib.rs
#6032 implemented SSH hostkey checks, but unintentionally only for the code path that clones the index. The code path that pushes changes was unchanged, and was causing errors. This PR adjusts the `push()` fn to also use the custom hostkey check.
=> Fix SSH hostkey checks for `push()`

.github/workflows/ci.yml, .github/workflows/coverage.yml
Staging has been bumped to the heroku-22 stack. Assuming no unexpected
issues, we can bump CI to match and then upgrade production.
=> Bump CI to use Ubuntu 22.04

cargo-registry-index/lib.rs, src/bin/background-worker.rs
Previously we were using libgit2 to clone the index, which regularly took 2-3 minutes. This PR switches us over to using the `git` CLI, which appears to be significantly faster and clones the index in just over 30 seconds.
=> background-worker: Speed up index cloning by 3x

backend.Dockerfile
Partially fixes #6018 by installing the same version of diesel_cli as the CICD pipeline. 🙂
=> Set backend dockerfile to install diesel version 1.4.1

.github/renovate.json5, backend.Dockerfile, frontend.Dockerfile
This PR takes advantage of https://docs.renovatebot.com/presets-regexManagers/#regexmanagersdockerfileversions to update:
- The Rust Docker image version
- The Node.js Docker image version
- The pnpm version used in the `Dockerfile`
- The Diesel CLI version used in the `Dockerfile`
=> Use Renovatebot regex managers for Docker files

src/middleware.rs
This allows us to get rid of unnecessary the `dummy_error_handler()` fn :)
see https://github.com/tokio-rs/axum/pull/1696
=> middleware: Use new `option_layer()` from `axum-extra` crate

config/nginx.conf.erb
The nginx config injects the Access-Control-Allow-Origin header to allow cross-origin API requests to crates.io. This is done using the add_header directive in the configuration. This directive only injects the header for successful response codes, as per the documentation:
http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header
This means that cross-origin requests to crates.io are allowed when a crate exists (successful status code), but denied when it does not exist (404 response).
This commit fixes that behaviour and allows other sites to make use of the crates.io API, even when looking up crates that do not exist.
This fixes #6142.
Please test this change if possible. I think this change is safe, I think the missing header was an oversight. I do not know how to add a …
=> Updates nginx config to always send Access-Control-Allow-Origin header

Cargo.toml, src/middleware.rs
while digging into some errro around panic-handling in docs.rs ( https://github.com/rust-lang/docs.rs/pull/2072 ) I saw that the default behaviour in axum is that when there is a panic while handling the web request, the connection is just closed without any error. 
To me it seems like a normal server error is the better behaviour here. 
The panic will also be logged using `tracing::error`, so as long as `tower_http` as source is not filtered, the panic will also be shown in sentry, including the correct request context. 
( [it's also possible to adapt the error page, if needed](https://github.com/tower-rs/tower-http/blob/master/tower-http/src/catch_panic.rs))
=> add panic-handling axum middleware

config/nginx.conf.erb
Setting the `X-XSS-Protection` header value to `0` per OWASP's recommended best practice. It's counterintuitive, I know, but having the filter enabled can [cause more harm than good.](https://groups.google.com/a/chromium.org/g/blink-dev/c/TuYw-EZhO9g/m/blGViehIAwAJ)
The CSP header provides better protection against XSS.
https://owasp.org/www-project-secure-headers/#x-xss-protection
=> updated x-xss-protection header to follow owasp best practice

docs/CONTRIBUTING.md
Diesel was upgraded to version 2 in #4892, but the contributing instructions still have the reader install diesel_cli 1.x, which will result in some fun errors when it attempts to regenerate `src/schema.rs` when running `diesel migration run`, as recommended later in the contributing guide.
=> Update CONTRIBUTING.md to install diesel_cli 2.x

script/import-database-dump.sh
More detail is in the individual commits, but this addresses two issues I ran into while setting up a local crates.io environment:
* The import script hard codes the database name, instead of picking it up from the environment — this now checks the environment first before falling back to the hard coded name.
* The summary API endpoint 500s after running import because `recent_crate_downloads` isn't populated.
=> Update the import script to handle a couple of problematic scenarios

.buildpacks, package.json
This is an attempt to solve https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/deployments/near/346926329 and simultaneously pins the `pnpm` version that is used by Heroku.
=> Heroku: Update `pnpm` buildpack

package.json, pnpm-lock.yaml
With one of the latest v4.x release of Ember.js the `@ember/string` package has been declared a peer dependency. While it still worked fine without declaring it, it will soon become a hard error.
This should also unblock the build failure of https://github.com/rust-lang/crates.io/pull/5277
=> Add missing `@ember/string` dependency

src/worker/git.rs
This appears to have been a copy-paste issue... 😅
=> worker/git: Fix duplicate log message

app/components/user-avatar.js
Resolves https://github.com/rust-lang/crates.io/issues/6287
The `kind` field on our API only exists for owners, but not for the response from the `/me` API endpoint. Due to that, the `kind` field in that case is `undefined` which lead to "undefined" being displayed in the avatar title (see #6287).
This PR changes the title attribute logic to treat `undefined` as a `user`, which should resolve the problem.
=> Fix `undefined` in user avatar title

src/tests/dump_db.rs, src/worker/dump_db.rs, src/worker/dump_db/gen_scripts.rs
When setting up my new machine I used `brew install libpq` to install the necessary PostgreSQL CLI tools and updated my shell startup script accordingly. Unfortunately, my IDE (IntelliJ) was not aware of this path and the CLI tools were not automatically linked into the default `bin` folder of homebrew. This lead to the `dump_db_and_reimport_dump` test failing when run from within the IDE, as opposed to running successfully when run from the terminal.
The test just failed with "No such file or directory (os error 2)" though, which wasn't exactly helpful in figuring the above out... 😅 
This PR switches some of the code over from `swirl`-specific errors to using [anyhow](https://github.com/dtolnay/anyhow), which allows us to use the `.context()` method to add essentially an error stack …
=> Improve debugability of the `dump_db` background worker task

src/util/tracing.rs
This module does not exist anymore, so there is no need to keep this filter around... :D
=> tracing: Remove obsolete `conduit_axum::fallback` filter

ember-cli-build.js
see https://github.com/embroider-build/embroider/#options
This slightly decreases our JavaScript asset sizes because imports are resolved statically instead of using the AMD module system.
```
- dist/assets/chunk.514fea02e3c082d63de4.js: 620.24 kB (173.5 kB gzipped)
- dist/assets/chunk.faa54e529b84b23f258d.js: 379.93 kB (68.02 kB gzipped)
- dist/assets/chunk.fc24a4515fb363c6d8bb.js: 378.37 kB (67.43 kB gzipped)
- dist/assets/chunk.96efe47e97abf8656339.js: 349.69 kB (62.98 kB gzipped)
- dist/assets/chunk.a3d896c0d6d4d34ccfd1.js: 351.24 kB (63.55 kB gzipped)
- dist/assets/chunk.bf7497a40e0cb0b8aa38.js: 574.47 kB (164.1 kB gzipped)
```
=> embroider: Enable `staticAddonTrees` option

src/models/token.rs, src/models/token/scopes.rs, src/tests/routes/me/tokens/list.rs, src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__list__list_tokens.snap
These fields will be `null` if the token was created without any crate or endpoint scopes, or they will be arrays of the chosen scopes.
Note that these fields are considered **experimental** and we don't give any stability guarantees for now!
```json5
{
// ...
"crate_scopes": ["serde", "serde-*"]
"endpoint_scopes": ["publish-new", "publish-update"],
}
```
- https://github.com/rust-lang/rfcs/pull/2947
- https://github.com/rust-lang/crates.io/pull/5973
=> GET /me/tokens: Add `crate_scopes` and `endpoint_scopes` fields

.github/renovate.json5
The action is working well for us as-is. There does not appear to be a need for us to keep this updated quite as often as it is apparently released.
=> renovate: Throttle `tj-actions/changed-files` action updates

cargo-registry-index/lib.rs, src/controllers/krate/publish.rs, src/tests/http-data/krate_publish_new_krate_sorts_deps.json, src/tests/krate/publish.rs
We [sorted the crate dependencies](https://github.com/rust-lang/crates.io/pull/5089) when we did the normalization, but newly published crates do not get their dependencies sorted.
* Updates the `Ord` impl on `Dependency` so all fields are included to ensure a total order.
* Adds a test that verifies newly published crates get sorted (verified this failed before the fix).
r? @Turbo87 
- https://github.com/rust-lang/crates.io/pull/5089
=> Sort crate dependencies before adding to index

src/tests/record.rs
When tests fail due to a difference in the body of an HTTP request, it shows up as an escaped string vs a Vec of bytes.
This makes the assert compare the base64 encoded strings (which is what's actually in the JSON http data file).
r? @Turbo87
=> Make it easier to debug test failures due to incorrect http-data

src/models/token.rs, src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success.snap, src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes.snap, src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes.snap, src/views.rs
The `revoked` field is not used by the frontend, and the only API endpoint that returns the `revoked` field is the one that creates a brand new token, in which case it makes no sense for the token to be immediately revoked.
This is technically a breaking change, but since this endpoint is only meant to be used by the frontend when creating new tokens via the user interface the risk of breaking something should be fairly small.
=> PUT /me/token: Remove unused `revoked` field from response payload

mirage/factories/api-token.js, mirage/route-handlers/me.js, tests/mirage/me/tokens/create-test.js, tests/mirage/me/tokens/list-test.js
This PR adds the `crate_scopes` and `endpoint_scopes` fields to the API token endpoints of our [MirageJS](https://miragejs.com) server, which lets us use these fields in the frontend test suite.
This is the first step in adding token scopes support to our frontend! 🎉 
- https://github.com/rust-lang/rfcs/pull/2947
- https://github.com/rust-lang/crates.io/pull/5973
- https://github.com/rust-lang/crates.io/pull/6310
- https://github.com/rust-lang/crates.io/pull/6315
=> mirage: Add crate and endpoint scope fields

src/models/token.rs, src/views.rs
This seems a bit easier than repeating all the fields and potentially causing inconsistencies (see https://github.com/rust-lang/crates.io/pull/6316).
=> EncodableApiTokenWithToken: Use `serde(flatten)` to reuse `ApiToken` serialization

src/admin/git_import.rs
The git-import tool was used for importing the checksum, package, and links fields from the index into the database. During that import some of the `links` fields were after the import was interrupted and then re-started.
This changes the `git-import` admin tool to only import the `links` field. Running the tool should be relatively quick (takes < 1 minute locally). 
This is the expected output:
```
edited 1 rows for cyclonedds-sys#0.1.7
edited 1 rows for gaviota-sys#0.1.20
edited 1 rows for jl-sys#0.18.0
edited 1 rows for lean-sys#0.0.2
edited 1 rows for libgphoto2_sys#2.5.10
edited 1 rows for libgphoto2_sys#1.0.0
edited 1 rows for libgphoto2_sys#1.0.1
edited 1 rows for libvpx-native-sys#5.0.7
edited 1 rows for link-cplusplus#1.0.7
edited 1 rows for magic-sys#0.3.0
edited 1 rows for …
```
=> Modify the git-import tool to only import the `links` field

src/controllers/krate/search.rs
We only need the content of the `Seek` variant to `.decode()` it, so using a reference is absolutely sufficient for that.
=> krate/search: Avoid unnecessary `.clone()` call in pagination code

Cargo.toml, src/tests/server_binary.rs
The `startup_without_database` test takes about ten seconds to run and is significantly slowing down the test of the test suite. This commit introduces a `slow-tests` cargo feature, which is enabled by default, but `cargo test --no-default-features` can be used to run the test suite without this particular test, or any future tests with this annotation.
=> tests: Introduce `slow-tests` feature

Cargo.lock, cargo-registry-index/Cargo.toml, cargo-registry-index/lib.rs, src/admin/delete_crate.rs, src/admin/delete_version.rs, src/admin/yank_version.rs, src/background_jobs.rs, src/config.rs, src/controllers/krate/publish.rs, src/controllers/version/yank.rs, src/models/dependency.rs, src/models/krate.rs, src/tests/all.rs, src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted.json, src/tests/http-data/krate_publish_new_krate_twice.json, src/tests/http-data/krate_publish_publish_after_removing_documentation.json, src/tests/http-data/team_publish_owned.json, src/tests/models/krate.rs, src/tests/models/mod.rs, src/tests/models/snapshots/all__models__krate__index_metadata-2.snap, src/tests/models/snapshots/all__models__krate__index_metadata.snap, src/tests/util/test_app.rs, src/worker/git.rs, src/worker/mod.rs
When a crate is modified, rather than editing the existing index file in git, this change re-generates the entire file from the database. This makes the jobs idempotent and prevents the index from getting out of sync with the database.
The `delete_version` and `delete_crate` admin tasks now also modify the index.
Test file changes are caused because the tests were inserting versions into the DB without adding them to the index.
=> Generate index metadata files from the database

src/admin/enqueue_job.rs, src/admin/yank_version.rs, src/background_jobs.rs, src/controllers/krate/publish.rs, src/controllers/version/yank.rs, src/worker/daily_db_maintenance.rs, src/worker/dump_db.rs, src/worker/git.rs, src/worker/mod.rs, src/worker/readmes.rs, src/worker/update_downloads.rs
This makes it a little easier to understand that these functions are creating `Job` instances that need to be enqueued afterwards. It also means we have all the constructors in one place instead of being spread out across multiple files.
=> Move `Job` constructors into `Job` impl

app/routes/settings/tokens.js, tests/acceptance/api-token-test.js
Even though the app claimed that the user can no longer access the plaintext token once they leave the page, this was not actually the case. Instead we still showed the plaintext token when the user navigated back to the API tokens page.
This PR adjusts the code for the `/settings/tokens` page to delete the plaintext token from memory once the users leaves the page.
=> settings/tokens: Delete plaintext tokens from memory after leaving API tokens settings page

src/controllers/krate/publish.rs, src/tests/krate/publish.rs
The `/me` route has been changed into a redirect to `/settings/tokens` due to it being hardcoded in cargo for a specific purpose. The email address field has moved to `/settings/profile` though, so this commit fixes the error message to point to the correct page.
Resolves https://github.com/rust-lang/crates.io/issues/6364
=> Fix broken URL in error message

src/sentry/mod.rs
The transaction name includes the HTTP method these days, so `is_download_endpoint` was always false... 🙈
=> sentry: Fix `is_download_endpoint` logic

Cargo.lock, Cargo.toml, src/admin/enqueue_job.rs
When this admin tool was migrated to use `clap` we missed that the subfields of the variants would now also be printed to the logs. Since we don't want our database URL to end up in the logs we will use `SecretString` here to redact it from the derived `Debug` implementation.
Note that this has already been reviewed and deployed before this public PR was opened, and the group of people with access to the logs of crates.io is the same as the one with access to Heroku and the database, so nothing was actually leaked. Out of caution we have also rotated the credentials to the database and we are investigating other measures that should prevent these issues in the future.
=> admin/enqueue-job: Redact `database_url` in `Debug` output

src/background_jobs.rs, src/bin/crates-admin.rs, src/swirl/runner.rs
This PR adds `tracing` instrumentation around a couple of places related to our background job code. This means Sentry will now be able to track how long our background jobs are taking and eventually also what parts make them slow.
=> tracing: Instrument background job runner

Cargo.lock, Cargo.toml, src/background_jobs.rs
Is this better? Who knows...
Does it work? Yes, it does...
The expanded code looks like this:
```rs
pub enum Job {
AddCrate(AddCrateJob),
DailyDbMaintenance,
DumpDb(DumpDbJob),
NormalizeIndex(NormalizeIndexJob),
RenderAndUploadReadme(RenderAndUploadReadmeJob),
SquashIndex,
SyncToGitIndex(SyncToIndexJob),
SyncToSparseIndex(SyncToIndexJob),
SyncYanked(SyncYankedJob),
UpdateCrateIndex(UpdateCrateIndexJob),
UpdateDownloads,
}
impl 
Job {
fn as_type_str(&self) -> &'static str {
match self {
Self::AddCrate(_add_crate_job) => "add_crate",
Self::DailyDbMaintenance => "daily_db_maintenance",
Self::DumpDb(_dump_db_job) => "dump_db",
Self::NormalizeIndex(_normalize_index_job) => "normalize_index",
Self::RenderAndUploadReadme(_render_and_upload_readme_job) =>
"render_and_upload_readme", …
```
=> background_jobs: Use macros to generate `as_type_str()`, `to_value()` and `from_value()`

cargo-registry-index/lib.rs, src/app.rs, src/auth.rs, src/background_jobs.rs, src/controllers/krate/publish.rs, src/controllers/krate/search.rs, src/db.rs, src/models/krate.rs, src/uploaders.rs, src/worker/readmes.rs
This should give us a few more insights into what parts are fast or slow :)
=> Add more `tracing` instrumentation

src/bin/background-worker.rs, src/sentry/mod.rs, src/swirl/runner.rs
Some of the `tracing` spans were not properly associated to the parent `swirl.perform` span. This PR should fix the problem.
=> swirl: Improve Sentry scoping

src/controllers/krate/publish.rs, src/util/manifest.rs
https://github.com/rust-lang/crates.io/pull/6267 added the field to the database and index, but during review I missed that it was deserializing from the `rust_version` field in the `Cargo.toml` file, instead of using `rust-version` (see https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field).
This PR fixes the issue and adjusts the corresponding test :)
=> rust-version: Use "kebab-case" for `Cargo.toml` field name

app/models/version.js, tests/models/version-test.js
`1.2.3` matches the old regex, just like `1.2` does too, so this PR fixes the regex to only match a two-part version string.
=> models/version: Fix `msrv` regex

app/components/header.hbs, app/components/settings-page.hbs, app/components/settings/api-tokens.js, app/components/side-menu/item.hbs, app/controllers/settings/tokens/new.js, app/router.js, app/routes/settings/tokens.js, app/routes/settings/tokens/index.js, app/routes/settings/tokens/new.js, app/styles/settings/tokens/new.module.css, app/styles/shared/buttons.module.css, app/templates/settings/tokens.hbs, app/templates/settings/tokens/index.hbs, app/templates/settings/tokens/new.hbs, tests/routes/settings/tokens/new-test.js
This for-now-hidden page will be the foundation for adding token scopes support to the frontend. For now, the page only allows the user to enter the token name, just like before. In the next steps we will add support for crate scopes and endpoint scopes.
The page is accessible for testing by holding down the <kbd>Alt</kbd> key while clicking the "New token" button on the tokens list settings page.
=> Add new `settings/tokens/new` page

src/admin/delete_crate.rs, src/admin/delete_version.rs, src/admin/yank_version.rs, src/background_jobs.rs, src/config.rs, src/controllers/krate/publish.rs, src/controllers/version/yank.rs, src/tests/util/test_app.rs, src/worker/git.rs, src/worker/mod.rs
This PR removes the `FEATURE_INDEX_SYNC` feature flag.
I've opened this as a draft PR since we just enabled the feature flag this morning and we should probably wait with the removal for 1-2 weeks until we are confident that enabling the flag did not unintentionally break anything.
=> Remove index sync feature flag

src/util/token.rs
=> Fix typo in token.rs

app/components/crate-header.hbs, app/components/crate-header.module.css, app/styles/application.module.css, app/templates/crate/version.hbs, tests/routes/crate/version/model-test.js
Resolves https://github.com/rust-lang/crates.io/issues/6414
I'm opening this as a draft PR for discussion among the team. Also, tests are still missing for this change.
=> Show README and metadata for yanked crates/versions

app/components/rendered-html.module.css, cargo-registry-markdown/lib.rs
This is a small PR adding some style for the \<kbd> tag in the the markdown display.
It was created after a short discussion #6420.
=> README: Add styling for `<kbd>` tags

README.md, docs/CONTRIBUTING.md
see https://github.com/rust-lang/team/pull/893
=> docs: Replace Discord channel links with Zulip

app/templates/settings/tokens/new.hbs
`this.id` doesn't exist, and with the previous PR that implemented this page I forgot to replace it with something that actually works. This PR fixes the issue by leveraging the built-in `unique-id` helper of Ember.js.
=> settings/tokens/new: Fix broken `<input>` id

app/controllers/settings/tokens/new.js, app/models/api-token.js, app/styles/settings/tokens/new.module.css, app/templates/settings/tokens/new.hbs, tests/routes/settings/tokens/new-test.js
=> settings/tokens/new: Add "Scopes" section

app/controllers/settings/tokens/new.js, app/styles/settings/tokens/new.module.css, app/templates/settings/tokens/new.hbs, tests/routes/settings/tokens/new-test.js
- https://github.com/rust-lang/rfcs/pull/2947
- https://github.com/rust-lang/crates.io/pull/6428
=> settings/tokens/new: Add "Crates" section

app/utils/license.js, tests/utils/license-test.js
`replace()` only replaces the first occurrence of the search string/regex, which is unintentional here. `replaceAll()` replaces all occurrences, as the name suggests, which is what we want in this function.
This PR should also unblock https://github.com/rust-lang/crates.io/pull/6440, which made me aware of this bug.
=> utils/license: Fix `replace()` calls

app/routes/settings/tokens/index.js, tests/routes/settings/tokens/index-test.js
Previously, Ember Data would perform a background reload of the tokens on the server, but that is apparently not compatible with our usage of `TrackedArray` so the list would not update correctly.
Fortunately, we can use `reload: true` to force Ember Data to reload the list of tokens from the server in the `model()` hook.
=> settings/tokens: Make sure to always reload API tokens from the server

app/components/settings/api-tokens.hbs, app/components/settings/api-tokens.js, app/components/settings/api-tokens.module.css, app/controllers/settings/tokens/new.js, app/styles/shared/typography.module.css, app/templates/settings/tokens/new.hbs, app/utils/token-scopes.js, tests/routes/settings/tokens/new-test.js
This PR modifies the API token list to display the corresponding endpoint and crate scopes, if they have been set when generating the token:
We also use tooltips for both, using the same descriptions as on the `/settings/tokens/new` page:
=> settings/tokens: Display endpoint/crate scopes if they exist

src/config/base.rs
Since crate.io has already deprecated the `mirror` mode and remove related code, these two comment fragments may cause confusion.
This PR fix it
=> Remove confusing comment fragments about mirror mode

Cargo.lock, Cargo.toml, cargo-registry-index/Cargo.toml
This reverts commit dd25dabca656f0cad8998b8c6356fba48411433e.
see https://github.com/tokio-rs/tracing/issues/2578
=> Revert "Update Rust crate tracing to v0.1.38 (#6387)"

Cargo.lock, Cargo.toml, cargo-registry-s3/Cargo.toml
This primarily also disables the `oldtime` feature, which has a reported vulnerability (see https://rustsec.org/advisories/RUSTSEC-2020-0071).
Related:
- https://github.com/chronotope/chrono/issues/602#issuecomment-1242149249
- https://github.com/time-rs/time/issues/293
=> chrono: Disable default features

app/templates/index.hbs
this PR resolves #5403
It adds a `see all` button to every list.
Maybe these buttons should be made smaller or removed completely and instead make the title clickable. simply because i think there now is a bit to much green (see all)
=> Front Page: adding "see all" to every list

.github/workflows/ci.yml
This PR is a small improvement on top of #6464, which ensures that the `cargo-deny` check is run for all pushes to the main repo branch, not just when the `Cargo.lock` file is changed. This ensures that external changes (e.g. new vulnerabilities) are detected and reported earlier.
=> cargo-deny: Run for all push events to the main branch

.buildpacks
`emk/heroku-buildpack-rust` isn't really maintained anymore. I've forked it and cleaned it up a bit to hopefully improve the caching behavior.
=> Update `heroku-buildpack-rust` to custom fork

app/styles/index.module.css, app/templates/index.hbs
This PR removes all `see all` buttons and instead makes the title itself clickable.
"New Crate" title is hovered on this image
continues work from #6442
=> Front Page: remove `see all` buttons

app/styles/categories.module.css, app/styles/crates.module.css, app/styles/keywords.module.css, app/styles/search.module.css, app/styles/shared/sort-by.module.css, app/templates/categories.hbs, app/templates/crates.hbs, app/templates/keywords.hbs, app/templates/search.hbs
currently, all `Sort by` labels are slithy lower than center
this is just a very minor thing but after noticing it I couldn't unsee it.
now it is probably centered
=> Fix "Sort by" label positioning

.github/renovate.json5
This is an attempt to prevent issues like https://github.com/rust-lang/crates.io/pull/6478#issuecomment-1547169175 by waiting for 24 hours before trying to update `pnpm`. This should give the renovatebot setup time to support the new version.
If this turns out to not work we can revert the PR again.
=> renovate: Delay `pnpm` updates by 24 hours

app/components/crate-row.hbs
This PR removes some `abbr` tags and replaces them with `EmberTooltips` this is mainly for visual consistency and they should be functionally identical.
The same change was made for copy-button.
Before:
After:
=> Replace `abbr` with `EmberTooltips`

docs/CONTRIBUTING.md
It seems there are dependency software versions  in CONTRIBUTING.md is out of date 
e.g:
The version of  Frontedn `nodejs` and `npm`
https://github.com/rust-lang/crates.io/blob/8814a1f95592ef0eb2b6aab540c62bbe1610bf81/package.json#L151-L153
and the version of Rust itself
https://github.com/rust-lang/crates.io/blob/8814a1f95592ef0eb2b6aab540c62bbe1610bf81/Cargo.toml#L8
This PR update it
=> Update some version requirements in CONTRIBUTING.md

package.json, pnpm-lock.yaml
This reduces our reliance on outdated embroider versions
=> Update `ember-cli-mirage` to v3 alpha

app/components/crate-row.module.css
This PR makes it so that the status svg's always have the same size.
this was a minor problem on small displays.
Before:
After:
=> Search: make status svg's always the same size 

package.json, pnpm-lock.yaml
`ember-css-modules` already depends on `postcss ^8.0.0` so this resolution is no longer necessary.
=> Remove obsolete `postcss` version resolution

public/assets/following.svg
This PR removes the black background from `following.svg`.
Or am I missing some reason why this is the case?
Before:
After:
=> Dashboard: remove black background from following.svg

Cargo.lock, cargo-registry-index/Cargo.toml, cargo-registry-index/credentials.rs, cargo-registry-index/repo.rs, src/bin/background-worker.rs, src/config/database_pools.rs, src/db.rs, src/tests/util/test_app.rs
This should make it a little harder for us to accidentally leak the credentials via a `Debug` implementation.
Note that the GitHub credentials do not need this, as they are already using the corresponding `oauth` structures, that provide similar properties.
=> Use `secrecy` crate for database URLs and git credentials

src/models/version.rs, src/sql.rs, src/tests/http-data/krate_publish_version_with_build_metadata_1.json, src/tests/http-data/krate_publish_version_with_build_metadata_2.json, src/tests/http-data/krate_publish_version_with_build_metadata_3.json, src/tests/krate/publish.rs, src/tests/krate/snapshots/all__krate__publish__version_with_build_metadata@build_metadata_1.snap, src/tests/krate/snapshots/all__krate__publish__version_with_build_metadata@build_metadata_2.snap, src/tests/krate/snapshots/all__krate__publish__version_with_build_metadata@build_metadata_3.snap
Resolves https://github.com/rust-lang/crates.io/issues/1059
`cargo` does not handle these situations particularly well and the SemVer specification is a little ambiguous about how to handle build metadata.
We still have roughly 600 problematic versions in the database, so we can't introduce a unique index yet, but the query appears to be fast enough according to my local testing:
```sql
EXPLAIN SELECT * FROM versions WHERE num = '1.0.0' AND crate_id = 463;
```
```
Index Scan using unique_num on versions  (cost=0.42..8.45 rows=1 width=190)
Index Cond: ((crate_id = 463) AND ((num)::text = '1.0.0'::text))
```
vs.
```sql
EXPLAIN SELECT * FROM versions WHERE split_part(num, '+', 1) = '1.0.0' AND crate_id = 463;
```
```
Bitmap Heap Scan on versions  (cost=4.57..79.36 rows=1 width=190)
Recheck …
```
=> Prevent similar versions that only differ in build metadata from being published

Cargo.lock, Cargo.toml, cargo-registry-tarball/Cargo.toml, cargo-registry-tarball/src/builder.rs, cargo-registry-tarball/src/lib.rs, cargo-registry-tarball/src/limit_reader.rs, cargo-registry-tarball/src/manifest.rs, cargo-registry-tarball/src/vcs_info.rs, src/admin/render_readmes.rs, src/controllers/krate/publish.rs, src/util.rs, src/util/io_util.rs
This PR extracts all the crate tarball related code into a dedicated crate. This should make it easier in the future to write tools that read metadata from these tarballs for analysis or data backfilling purposes (e.g. `rust-version`).
=> Extract `cargo-registry-tarball` crate

cargo-registry-tarball/src/lib.rs, src/controllers/krate/publish.rs, src/tests/krate/publish.rs
Seeing "invalid tarball uploaded" isn't particularly helpful, so this PR splits up this error into two error enum variants with more descriptive error messages.
=> tarball: Split `Invalid` error into two enum variants

cargo-registry-tarball/src/lib.rs, cargo-registry-tarball/src/manifest.rs
According to https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/crate.20files.20with.20unusual.20.60Cargo.2Etoml.60.20files/near/362487043, `project` should be treated equivalent to `package`. It is deprecated on the cargo side though, and showing a warning for publishes that use this name.
=> tarball/Manifest: Add `project` alias for `package` table

src/bin/crates-admin.rs, src/util/tracing.rs
This enables us to use `info!()` and `warn!()` in the admin tools and actually see the output by default :D
=> bin/crates-admin: Use INFO log level by default

Cargo.lock, Cargo.toml, src/admin/backfill/mod.rs, src/admin/backfill/rust_version.rs, src/admin/mod.rs, src/bin/crates-admin.rs
This command will generate an SQL script that can be piped into the production database to backfill all of the missing `rust-version` values.
As the code comment explains, this command relies on a local import of the production database dump and using https://crates.io/crates/get-all-crates to download all the crate files to a local directory for faster processing.
I've pushed the result of this tool to https://raw.githubusercontent.com/Turbo87/crates.io/rust-version-backfill-result/rust-version-backfill.sql for review.
=> Add `crates-admin backfill rust-version` command

app/components/settings/api-tokens.js, tests/acceptance/api-token-test.js
This enables the new "Create API Token" page for everyone, including the new support for API token scopes.
for more context see https://blog.rust-lang.org/inside-rust/2023/05/09/api-token-scopes.html
Resolves https://github.com/rust-lang/crates.io/issues/5443
=> Stabilize token scopes

.eslintrc.js, app/utils/license.js
According to Sentry we have a few users that don't have browsers supporting `.replaceAll()` yet. While those browsers are technically not officially supported by us anymore they are easy enough to support in this specific case with these minor changes.
=> utils/license: Use `.replace()` instead of `.replaceAll()`

Cargo.lock, Cargo.toml, crates_io_index/Cargo.toml, crates_io_index/repo.rs, crates_io_s3/Cargo.toml, crates_io_s3/lib.rs, src/controllers/github/secret_scanning.rs, src/controllers/helpers/pagination.rs, src/metrics/log_encoder.rs, src/middleware/session.rs, src/tests/record.rs
Closes #6503.
Renovate's update failed. I created a new branch and updated the deprecated function calls to their new equivalents.
Let me know if you'd rather I close this and commit to Renovate's branch.
=> bump base64 to 0.21.1

.github/workflows/ci.yml
Just two very minor changes to our CI setup, which ensure that it's working correctly and not using any deprecated flags.
=> CI: Adjust backend linting CLI flags

app/components/rendered-html.module.css, app/styles/crate/version.module.css
Some users have `README`s that use tabs in their Rust code examples.
Although that doesn't respect the default settings of `rustfmt`, it seems that the most sensible way to handle any tabs in Rust code in crates `README`s would be to display it in the same way `rustfmt` would normally indent: with spacing of size 4 (instead of 8 by default in the browser).
This is a one-liner.
=> CSS: Set tab display size to 4 in docs section

src/tests/record.rs
In #6326, `text/plain` request payloads were decoded into... well, plain text, and `record::replay_http` was updated to handle them accordingly. The code that records those request payloads was not updated, however, so any updated test payload will now result in failures, since a base64 encoded string will be compared against a plain text string.
This adds the same logic to `record::record_http` to ensure newly recorded cassettes match.
=> tests: don't base64 encode text/plain request payloads when recording

crates_io_s3/Cargo.toml
This package couldn't be directly built with (eg) `cargo test -p crates_io_s3` due to `chrono` not having the `clock` feature enabled for `Utc::now`. Cargo feature unification was making this work when building from the top level, but there's no reason we can't have this be buildable by itself.
Extracted from https://github.com/rust-lang/crates.io/pull/6606
=> crates_io_s3: Add missing `chrono/clock` feature

crates_io_s3/Cargo.toml
Extracted from https://github.com/rust-lang/crates.io/pull/6606
=> crates_io_s3: Sort dependencies alphabetically

Cargo.lock, crates_io_s3/Cargo.toml, crates_io_s3/lib.rs, src/config/base.rs, src/uploaders.rs
This is required to allow non-AWS endpoints implementing the S3 API (such as minio) to be used for testing. These changes are reasonably mechanical, and (I hope) uncontroversial.
There are a few changes in the `Cargo.toml` for this package:
1. We need `url` as a top level import so we can use `ParseError`, which isn't re-exported by `reqwest`.
2. `thiserror` is used to define a small, crate-specific error type, since there are now functions that can return `url::ParseError`.
3. This package couldn't be directly built with (eg) `cargo test -p crates_io_s3` due to `chrono` not having the `clock` feature enabled for `Utc::now`. Cargo feature unification was making this work when building from the top level, but there's no reason we can't have this be buildable by itself.
4. Sorted the …
=> crates_io_s3: allow the region to be a full hostname

src/controllers/token.rs
Lets not spend the extra compile time if we don't actually need it :)
=> controllers/token: Remove unused `Serialize` implementations

src/models/token.rs, src/tests/user.rs, src/tests/util.rs, src/views.rs
The secrets are not entirely flowing through yet, but this should be another step in the right direction.
=> CreatedApiToken: Use `SecretString` to hide plaintext token

script/import-database-dump.sh, script/infer-database-dump-version.py
This adds a small Python 3 script to generate SQL to populate the Diesel schema migration table after importing a database dump. (Python instead of `sh` mostly because I don't really want to reinvent JSON parsing, but I'm happy to revisit that if we don't want to add an optional Python dependency for this script.)
Open question: should we allow this script to fail silently if Python is unavailable? It's obviously not a critical part of setting up a development environment, but it _is_ handy for people who may develop and/or test migrations.
=> script: infer the Diesel migrations table when importing a dump

src/models/token.rs, src/util/token.rs
While the `generate()` fn is generating a `SecureToken`, it is also returning the plaintext representation inside a `NewSecureToken` struct, so it makes more sense for this method to be on the corresponding impl block.
=> SecureToken: Move `generate()` to the `NewSecureToken` impl

src/tests/util.rs
I would've expected `clippy` to complain about this being unused, but apparently not... 🤷‍♂️
=> tests/util: Remove unused `Error` struct

src/models/token.rs, src/util/token.rs
Implementing `Clone` makes it harder for us to use the `secrecy` crate, and since we don't use `.clone()` on these structs there is no reason for us to derive an implementation for this trait.
=> ApiToken: Remove unused `Clone` implementations

src/models/token.rs, src/util/token.rs
It looks like we don't have any code comparing `ApiToken`, so we don't need the `Eq` implementations either. Since the only reason we had them on `SecureToken` was that it is included in `ApiToken`, I've removed them too.
=> ApiToken: Remove unused `PartialEq` and `Eq` implementations

app/components/settings/api-tokens.hbs, app/models/api-token.js, tests/acceptance/api-token-test.js
The expiry is not particularly highlighted yet if it is close to expiring, but showing the value at all seems like a good first step :D
=> Show API Token expiry in token list

app/components/settings/api-tokens.hbs, app/components/settings/api-tokens.js, tests/routes/settings/tokens/new-test.js
This PR follows #6573 and cleans up the API token creation code. This should be merged once the token scopes have run in production for a number of days without significant complaints.
In other words: merge this on 2023-06-19 😉
=> Clean up API token creation code

src/controllers/krate/publish.rs, src/tests/http-data/krate_publish_version_with_build_metadata_1.json, src/tests/http-data/krate_publish_version_with_build_metadata_3.json, src/uploaders.rs
This implements part one of the proposed solution in https://github.com/rust-lang/crates.io/issues/4891#issuecomment-1580879109: if a published version contains a `+` (aka. it contains build metadata), we temporarily upload the crate file to the unescaped (`+`) and escaped (`%2B`) S3 paths.
=> publish: Save build metadata containing versions to escaped path too

app/controllers/settings/tokens/new.js, app/styles/application.module.css, app/styles/settings/tokens/new.module.css, app/templates/settings/tokens/new.hbs, tests/routes/settings/tokens/new-test.js
Default (No expiration):
Available options:
Preset expiration:
Custom expiration date:
=> settings/tokens/new: Add "Expiration" options

src/background_jobs.rs, src/bin/background-worker.rs, src/tests/util/test_app.rs, src/worker/dump_db.rs, src/worker/fastly.rs, src/worker/mod.rs
After uploading a new version of the database dump, the cached version needs to be invalidated in CloudFront and Fastly.
Fixes #6652
=> Invalidate CDN caches after uploading database dump

src/tests/http-data/krate_publish_new_krate_with_readme_and_plus_version.json, src/tests/krate/publish.rs, src/worker/readmes.rs
This PR is similar to https://github.com/rust-lang/crates.io/pull/6649, but this time for the rendered README files, which have the same [problem](https://github.com/rust-lang/crates.io/issues/4891) as the crate tarball files.
=> worker/readmes: Save the README of build metadata containing versions to escaped path too

tests/routes/settings/tokens/new-test.js
Apparently this test was a gremlin and should not have been ~~fed~~ run after midnight.
JavaScript dates created with only a date are created in UTC, not in local time, which causes problems with the later assertions around the date as displayed in the local time zone. Quoting from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format:
> When the time zone offset is absent, date-only forms are interpreted
> as a UTC time and date-time forms are interpreted as local time. This
> is due to a historical spec error that was not consistent with ISO
> 8601 but could not be changed due to web compatibility. See Broken
> Parser – A Web Reality Issue.
We can fix this by also including the time without a time zone, at which point the local …
=> tests: fix API token test after midnight UTC

app/components/header.module.css
Warning: you won't be able to unsee what I'm about to show you.
<details><summary>Disturbing animation</summary>
<p>
</p>
</details> 
When a user is logged out of crates.io, the text `Browse All Crates` is nicely aligned with `Log In With GitHub`. Awesome.
When a user is logged _in_ to crates.io, the baseline of the user's name is three pixels higher than the `Browse All Crates` link. Ruinous.
The reason for this is that the `UserAvatar` component ends up being taller than the `Browse All Crates` element due to the extra height of the avatar image (22px vs the 16px font size). If we apply a small negative `margin-top` to the avatar and make all the `.nav` elements stretch to the same height by using `align-items: stretch`, then both elements are then rendered with the same baseline.
=> header: correctly align baselines when logged in

app/components/rendered-html.hbs, app/controllers/crate/version.js, app/modifiers/render-mermaids.js, app/routes/crate/version.js, app/services/mermaid.js, crates_io_markdown/lib.rs, package.json, pnpm-lock.yaml, tests/acceptance/readme-rendering-test.js
This PR is a Proof of Concept for the in #5724 requested [Mermaid ](https://github.com/mermaid-js/mermaid) support.
It is supposed to show what would be required to support mermaid (maybe I am also missing some major problem with it)
points to think about:
- should we customize the [color theme](https://mermaid.js.org/config/theming.html)
- do we need a stricter [securityLevel](https://mermaid.js.org/config/usage.html#securitylevel) 
- how could the `mermaid.run()` call be improved (not using `setTimeout()`) 
note: this is just a quick and dirty PoC implementation and should most definitely not be merged
=> Add support for `mermaid` diagrams in README files

app/adapters/api-token.js, app/components/settings/api-tokens.hbs, app/components/settings/api-tokens.js, app/components/settings/api-tokens.module.css, app/models/api-token.js, app/routes/settings/tokens/index.js, mirage/route-handlers/me.js, src/controllers/token.rs, src/tests/routes/me/tokens/list.rs, tests/acceptance/api-token-test.js
As [previously discussed](https://github.com/rust-lang/crates.io/pull/6611#pullrequestreview-1479942646), we may want to show recently expired tokens to users so they can answer the question of "why isn't my request authenticating any more". This PR does the minimum required to provide those tokens from the API, and then use that to display them in the UI.
Be gentle with me on the Ember code; I'm still feeling my way around it!
=> Show recently expired API tokens in the UI

src/config/base.rs
Converting one `match` to an else-if chain and another if-condition to a `match` makes the code a little more concise and easier on the eyes :)
=> config/Base: Simplify conditions

src/config/balance_capacity.rs, src/config/base.rs, src/config/database_pools.rs, src/tests/util/test_app.rs
Since these functions are only run by our test suite there is no need for them to live in the production code and we can instead move them to the `tests` module.
=> Inline test config code

src/config.rs, src/middleware.rs, src/tests/util/test_app.rs
Instead of relying on the `env != Env::Test` check we can use explicit flags. This will allow us to selectively enable this behavior for certain tests in the future.
=> config: Extract `serve_dist` and `serve_html` flags

src/app.rs
The default value in `r2d2` is also 3 and there appears to be no documented reason why we should use less during development.
=> config: Increase dev-mode default for `DB_HELPER_THREADS`

src/app.rs, src/config/database_pools.rs, src/db.rs, src/tests/util/test_app.rs
All of our code that reads environment variables to configure the server should live in the `config` module. This allows us to easily override configuration values on a per-test basis and is generally more straight-forward to understand for new contributors. First we read, parse and validate all of the config values, and then we use them to build the actual server structs.
=> Move database config code from `app` to `config::database_pools`

src/bin/server.rs
`tokio` is using 512 as the default value and our production servers are currently set to `SERVER_THREADS=100`. There does not appear to be a documented reason to keep this number lower in development, since the threads are only created on-demand.
=> Simplify `SERVER_THREADS` default value

src/bin/server.rs
Specifying our own default of 512 threads is redundant. We can rely on the default value in `tokio` if `SERVER_THREADS` is not explicitly set.
=> bin/server: Use `tokio` default for `max_blocking_threads` if not set

src/app.rs, src/bin/server.rs, src/config/server.rs, src/tests/util/test_app.rs
The only code to read environment variables should be in the `config` module (or potentially in the tests). The `server` binary should first use the `config` module to read everything and then build the server process based on the `config` content.
This PR moves all of the remaining env var calls to the `config` module.
=> bin/server: Move env var handling to `config` module

src/config.rs, src/config/sentry.rs, src/sentry/mod.rs
Just like previous PRs: the only environment variable reading should happen in the `config` module, so this PR extracts a `config::sentry` module and corresponding `SentryConfig` struct, which is then used by the Sentry initialization code.
This is still somewhat unusual in that the `SentryConfig` struct is not part of `config::Server`, because the Sentry initialization happens before we read the rest of the config. It is implemented this way to ensure that we get Sentry issues if a regular config value happens to break the server somehow.
=> Extract `SentryConfig` struct

src/controllers/user/session.rs, src/db.rs, src/downloads_counter.rs, src/models/keyword.rs, src/worker/update_downloads.rs
We've had the essentially same implementation four times in our code base for no good reason. This PR merges them into one.
=> Merge `TEST_DATABASE_URL` functions

Cargo.lock, Cargo.toml, src/admin/delete_version.rs, src/uploaders.rs
As it turns out, we were only deleting the versions from the database and index, but the crate and readme files were unintentionally still remaining on S3. 
This PR fixes the problem for the `delete-version` admin tool. 
The `delete-crate` tool is not yet fixed, since we need to investigate how to best perform recursive file deletions with a path prefix.
=> admin/delete_version: Delete crate and readme files from S3 too

.github/workflows/ci.yml
see https://github.com/rust-lang/crates.io/pull/6745
=> CI: Run `cargo doc` to check for documentation warnings/errors

src/auth.rs, src/ssh/mod.rs, src/worker/git.rs
`let-else` is now formatted on nightly and these changes look good to
me. I've confirmed that `cargo +stable fmt` doesn't revert anything.
=> `cargo +nightly fmt`

src/controllers/github/secret_scanning.rs, src/controllers/krate/metadata.rs, src/controllers/token.rs, src/controllers/version/deprecated.rs, src/models/krate.rs, src/models/token.rs, src/tests/builders/krate.rs, src/tests/github_secret_scanning.rs, src/tests/routes/me/tokens/create.rs, src/tests/routes/me/tokens/delete.rs, src/tests/routes/me/tokens/delete_current.rs, src/tests/token.rs
There are a few places where we typically only query a subset of columns. The `Selectable` trait allows us to easily call `.select()` and `.returning()` with a partial list of columns.
* For the `crates` table we avoid pulling in the `textsearchable_index_col` column for performance reasons.
* For the `tokens` table we can avoid querying the user's hashed token.
I'm not yet able to completely eliminate the `ALL_COLUMNS` constant for crates, as the interaction with search pagination is causing some issues.
=> `derive(Selectable)` on a few diesel structs

src/admin/delete_crate.rs, src/admin/delete_version.rs, src/lib.rs, src/storage.rs
This PR extracts the common `object_store` setup code from our admin tools into a shared module and enables it to use the local file system for storage if the `S3_BUCKET` environment variable is not set.
=> Extract and improve `storage::from_environment()` fn

src/tests/http-data/krate_publish_new_krate_twice.json, src/tests/krate/publish.rs
These tests have all done the same work, but then run different assertions afterwards. We can merge them instead to have the test suite run slightly faster.
=> tests/publish: Merge redundant tests

src/background_jobs.rs, src/bin/background-worker.rs, src/swirl/runner.rs
The runner was already using `Arc` internally, so we might as well use it on the outside too, to prevent the unnecessary `.clone()` calls on all of the internal fields.
=> bin/background-worker: Replace unnecessary clones with `Arc` usage

src/admin/delete_crate.rs, src/admin/delete_version.rs, src/storage.rs
This PR creates an abstraction layer on top of our `ObjectStore` usage with a more high-level API. It also adds a basic test suite for the API based on the `InMemory` implementation of the `object_store` crate.
=> Extract `Storage` abstraction and add tests

src/admin/render_readmes.rs, src/uploaders.rs
We're already using the new `Storage` system for uploading rendered readme files with the background worker. This PR changes the `render_readmes` admin tool to use it too.
Related:
- https://github.com/rust-lang/crates.io/pull/6702
- https://github.com/rust-lang/crates.io/pull/6783
=> admin/render_readmes: Use `Storage` system for uploading readme files to S3

src/admin/render_readmes.rs, src/controllers/krate/publish.rs, src/storage.rs, src/tests/http-data/krate_publish_new_krate_with_empty_readme.json, src/tests/krate/publish.rs, src/worker/readmes.rs
This PR has been prompted by https://github.com/rust-lang/crates.io/issues/6793.
While it is not a real fix for https://github.com/apache/arrow-rs/issues/4514, it does work around the issue by not even attempting to upload an empty README file.
Since an empty README file serves no purpose we might as well skip the upload independent from the bug mentioned above.
=> Skip upload for empty README files

src/uploaders.rs
We don't use the `Uploader` system for file uploads anymore, so the corresponding code is being removed with this PR. There is still some code left related to external URL generation, which we will soon move elsewhere though.
=> Uploader: Remove obsolete code

src/storage.rs, src/tests/krate/publish.rs
This PR implements step 5 of https://github.com/rust-lang/crates.io/issues/4891#issuecomment-1580879109.
This essentially reverts #6649 and #6660, but keeps the escaped code paths that were added in those PRs and removes the ones that were there before.
This PR must only be merged once #6665 has been merged!
=> Stop uploading to S3 with unescaped paths

pnpm-lock.yaml
This should address https://github.com/advisories/GHSA-c2qf-rxjj-qqgw.
We're not really affected since the relevant version was only used at build-time, but this should shut up the security warning... 😅
=> Update `semver` JS dependency

app/components/rendered-html.hbs
This change avoids the following warning:
=> RenderedHtml: Ignore syntax highlighting for mermaid blocks

src/bin/crates-admin.rs, src/util/tracing.rs
This is what we're using in production, so we might as well make it the default.
=> tracing: Use `INFO` as default level

src/controllers/krate/publish.rs, src/tests/krate/publish.rs
This PR allows crates.io to point out the specific crate that violates the wildcard dependency constraint.
=> Show which crate violating wildcard dependency

src/worker/fastly.rs
When invalidating the cache on Fastly using the "single URL" endpoint, the content is only purged for that specific URL. This can cause inconsistencies, since we have two domains associated with each Fastly service (namely `static.*` and `fastly-static.*`). The invalidation logix has been refactor to purge a path for both domains.
=> Purge all domains on Fastly

crates_io_tarball/examples/read_file.rs, crates_io_tarball/src/lib.rs, src/admin/backfill/rust_version.rs, src/controllers/krate/publish.rs
This allows us to use `File` instead of having to read the full file contents into memory first.
=> tarball: Implement `process_tarball()` for any `Read` impl

Cargo.lock, crates_io_tarball/Cargo.toml, crates_io_tarball/examples/check_all_crates.rs
This tool can be run on a `get-all-crates` output folder to verify that our code can successfully process all currently existing crate files.
=> tarball: Add `check_all_crates` example

src/tests/krate/publish.rs
Using an invalid `Cargo.toml` can have unintended side-effects that we don't want in this test.
=> tests/krate/publish: Use text file for upload size check

crates_io_tarball/src/builder.rs, src/tests/builders/publish.rs, src/tests/krate/publish.rs
Instead of using the raw `tar::Builder` with `GzEncoder` we can use our `TarballBuilder` abstraction layer, which will make it easier in the future to generate valid crate manifests.
=> Use `TarballBuilder` in more tests

crates_io_markdown/lib.rs, crates_io_tarball/src/lib.rs, crates_io_tarball/src/manifest.rs, src/admin/render_readmes.rs
This brings us one step closer to the structure that `cargo_toml` is using: https://docs.rs/cargo_toml/0.15.3/cargo_toml/enum.OptionalFile.html
It still does not support `true` and `false` values, but this will be added in a follow-up PR.
=> tarball/Package: Change `readme` field to `Option<PathBuf>`

Cargo.lock, crates_io_tarball/Cargo.toml, crates_io_tarball/src/lib.rs, crates_io_tarball/src/manifest.rs, src/admin/render_readmes.rs, src/tests/krate/publish.rs
Resolves https://github.com/rust-lang/crates.io/issues/6847
This PR fixes the parsing and processing of the `readme` field inside `Cargo.toml` files by using the `OptionalFile` enum from the `cargo_toml` crate. In the future we can consider migrating more of our code to use the `cargo_toml` structures.
=> Fix `readme` field parsing of `Cargo.toml` files

src/storage.rs, src/tests/util/test_app.rs
This PR fixes https://github.com/rust-lang/crates.io/issues/6850.
It also makes sure that we run the test suite with a real-world value for the `cdn_prefix` field. This required a couple of refactorings, but the commit list should make it relatively straight-forward to follow.
=> Fix download URL generation

app/templates/settings/tokens/new.hbs
This should disable password managers from assuming that this input is expecting a person name. Since users shouldn't be using the same token name multiple times the disabled autocomplete shouldn't be a big issue.
=> settings/tokens/new: Disable autocomplete for "Name" field

src/lib.rs, src/metrics/instance.rs, src/metrics/macros.rs, src/metrics/mod.rs, src/metrics/service.rs, src/models/action.rs, src/models/dependency.rs, src/rate_limiter.rs, src/sql.rs
The 2018 edition of Rust allows us to explicitly import macros, which makes the code a little easier to follow and without polluting the top-level namespace of a project.
=> Replace `#[macro_use]` with explicit imports 

src/metrics/service.rs
The `background_jobs` definition is `IntGaugeVec["priority", "job"]`, not `IntGaugeVec["job", "priority"]` 😅 
/cc @pietroalbini
=> metrics/service: Fix `background_jobs` label order

.github/workflows/smoke-test.yml, Cargo.lock, Cargo.toml, crates_io_smoke_test/Cargo.toml, crates_io_smoke_test/src/main.rs
This PR adds a new `crates_io_smoke_test` project to the workspace and a "Smoke Test" GitHub Actions workflow. The latter can be manually triggered and runs the former. The new tool will query the current state of the staging environment, run `cargo new`, adjust the `version` field and then run `cargo publish` to see if publishing works correctly.
Example: https://github.com/Turbo87/crates.io/actions/runs/5670151138/job/15364394197
Note that this is just a first step. In the next step we can `cargo new` another project with a dependency on the published version to check that downloads are working as intended.
=> Implement basic smoke test setup

Cargo.lock, crates_io_smoke_test/Cargo.toml, crates_io_smoke_test/src/api.rs, crates_io_smoke_test/src/cargo.rs, crates_io_smoke_test/src/exit_status_ext.rs, crates_io_smoke_test/src/main.rs
This PR refactors the smoke testing setup from #6884 a little bit and adds more checks at the end. Specifically, we are now testing if the published version is visible on the API and if crate file downloads for this version are working.
=> Extend smoke testing setup

src/tests/builders/publish.rs, src/tests/krate/publish.rs
The `files_with_io()` fn reads the "file" content into memory anyway, so we gain nothing from passing in the `Read` impl. This PR simplifies the code a bit and keeps `files()` as the only entry point for generating a custom tarball.
Further cleanup with come in follow-up PRs :)
=> tests/builders/publish: Inline `files_with_io()` and simplify `files()` fn

src/tests/builders/publish.rs, src/tests/krate/publish.rs, src/tests/krate/yanking.rs, src/tests/owners.rs, src/tests/routes/crates/new.rs, src/tests/routes/crates/read.rs, src/tests/routes/crates/versions/yank_unyank.rs, src/tests/team.rs, src/tests/worker/git.rs
This will make it much easier in the future to keep a stateful `TarballBuilder` around, and also simplifies the existing usages in quite a few cases.
=> PublishBuilder: Provide `version` upfront

app/models/version.js, app/routes/crate/version.js, mirage/route-handlers/docs-rs.js, tests/routes/crate/version/docs-link-test.js
To simplify refactoring how our builds are processed I want to remove the `/builds.json` endpoint on docs.rs. As a replacement [I added](https://github.com/rust-lang/docs.rs/pull/2147) a new endpoint simply giving the status that sites like crates.io wants: are there docs for this version available to link to. This also fixes some small issues with the old endpoint (some edgecases meant the first build was successful but there were no docs, or there were docs but the first build was marked unsuccessful; if the version in the path doesn't match an exact version it is used as a semver query, but using a `=version` path like done here on the old API would hit CORS issues).
=> Migrate from docs.rs' builds API to status API

crates_io_tarball/src/lib.rs, src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/tests/krate/publish.rs, src/tests/routes/crates/read.rs
This changes the `crates_io_tarball` package to a) require a `Cargo.toml` file to always be present in a crate file, and b) no longer silently fail if the `Cargo.toml` file can't be parsed.
This ensures that only crate files with valid manifests end up on crates.io. We previously accepted almost arbitrary tarballs, even without any manifests. Note that "valid" is still pretty vague since we currently only deserialize very few fields of the TOML file, but this will change in the near future.
Unfortunately this change also required a few changes to our test suite, which previously did not include `Cargo.toml` files in most of the tarballs sent to the server. The `Cargo.toml` that we send now is a veeeery basic manifest and is actually still lacking the required `name` and `version` fields, …
=> tarball: Fail if `Cargo.toml` manifest is missing or invalid

src/tests/builders/publish.rs
No need to repeat code we've already written elsewhere :)
=> tests/builders/publish: Simplify `files()` fn

crates_io_tarball/src/lib.rs, crates_io_tarball/src/manifest.rs, src/admin/render_readmes.rs, src/tests/builders/publish.rs, src/tests/krate/publish.rs, src/tests/routes/crates/read.rs
This matches https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata, which says:
> The only fields required by Cargo are [name](https://doc.rust-lang.org/cargo/reference/manifest.html#the-name-field) and [version](https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field).
With this PR our publish endpoint will no longer accept tarballs with `Cargo.toml` files that are missing these fields.
=> tarball/Package: Add `name` and `version` as required fields

config/nginx.conf.erb, src/app.rs, src/config/server.rs, src/controllers/krate/publish.rs, src/controllers/version/yank.rs, src/downloads_counter.rs, src/lib.rs, src/models/krate.rs, src/rate_limiter.rs, src/sql.rs, src/tests/builders/krate.rs, src/tests/krate/publish.rs, src/tests/krate/yanking.rs, src/tests/util/response.rs, src/tests/util/test_app.rs, src/util/errors/json.rs, src/worker/update_downloads.rs
This PR follows up on #6872 by adding support for multiple kinds of rate limits in `RateLimiter` and adding a limit for yanking and unyanking, which would've prevented last Friday's outage.
As I was already changing this code, I also moved the rate limit for publishing existing crates from nginx into the application. This makes the limit more precise (as it's not per-server anymore, potentially allowing up to 4x the limit), and allows overriding the limit just for a subset of users.
With this PR, the rate limits are:
| Action | Burst amount | Refill time |
| --- | --- | --- |
| Publish new crates | 5 | 1 every 10 minutes |
| Publish updates to existing crates | 30 | 1 every minute |
| Yanking or unyanking | 100 | 1 every minute |
Note that the environment variables also changed:
* From …
=> Add application-level rate limits for crate updates, yanking and unyanking

crates_io_tarball/src/lib.rs
Instead of extracting a `manifest` variable, we can use a `package` variable to reduce the amount of code duplication a little bit.
=> tarball: Simplify test assertions

crates_io_tarball/src/lib.rs, crates_io_tarball/src/manifest.rs, src/admin/render_readmes.rs, src/controllers/krate/publish.rs, src/tests/krate/publish.rs
This PR switches the `crates_io_tarball` package over to using the https://crates.io/crates/cargo_toml for `Cargo.toml` file parsing.
This should significantly lower the chances of invalid `Cargo.toml` files ending up on crates.io, since a lot more fields are now properly validated.
Note that `cargo_toml` supports workspace inheritance by default, so we have to run an additional validation step to ensure that our server only accepts manifest files without any workspace inheritance.
Similarly, the crate accepts `rust-version` as any random `String`, so I had to move our validation check out of the `serde` deserialization code path.
=> tarball: Use `cargo_toml` to parse `Cargo.toml` file

frontend.Dockerfile, package.json
Reverts rust-lang/crates.io#6951.
Obviously needs to wait for the buildpack to be updated. My bad.
=> Revert "Update dependency node to v18.17.1"

src/rate_limiter.rs
In https://github.com/rust-lang/crates.io/pull/6875, @pietroalbini said:
> With this PR, the rate limits are:
> 
> | Action | Burst amount | Refill time |
> | --- | --- | --- |
> | Publish new crates | 5 | 1 every 10 minutes |
> | Publish updates to existing crates | 30 | 1 every minute |
> | Yanking or unyanking | 100 | 1 every minute |
but the code didn't match that intention, which explains why we were getting so many emails asking for rate limit increases since that PR went out.
The problem was that the `default_rate_seconds` for `PublishNew` was set to `60 * 60`, aka 1 hour, when the intention was that it would be set to `10 * 60`, or 10 minutes.
I added a new test, and for `PublishNew` it fails with:
```
---- rate_limiter::tests::default_rate_limits stdout ----
thread …
```
=> PublishNew was allowing 1 new crate an hour rather than every 10 minutes

migrations/2023-08-13-175220_to_semver_no_prerelease_parallel_safe/down.sql, migrations/2023-08-13-175220_to_semver_no_prerelease_parallel_safe/up.sql, src/models/krate_reverse_dependencies.sql
These commits have been branched out of #6910 after I kept finding improvements I could make which weren't performance related.
The last commit actually gives the reverse dependencies query a performance boost by allowing Postgres to write a query plan parallelizing most of the query to parallel worker processes, which it didn't before because of [parallel safety](https://www.postgresql.org/docs/current/parallel-safety.html).
I put it in because while it is a performance improvement it also seemed like a flag which should be present everytime the function implementation allows for it.
It also helps speed-up refreshing of indexes or materialized views.
=> Improve correctness of the reverse dependencies query

Cargo.lock
This should fix the CI errors we're getting.
=> cargo: update rustls-webpki

crates_io_tarball/src/lib.rs, src/controllers/krate/publish.rs
This will handle both differences in case (ie a crate file that contains both `package-x.y.z/Cargo.toml` and `package-x.y.z/cargo.toml`, as may happen on a case-sensitive filesystem) and malformed tarballs that contain multiple copies of the same file.
Effort has been made to otherwise preserve the same semantics as `cargo` where, if there is only one manifest, only `Cargo.toml` and `cargo.toml` are accepted. (It's debatable if we should even accept `cargo.toml`, and recent versions of `cargo` won't allow crates to be published with that casing, but since there may be legacy setups out there that are still publishing crates with this variation and we've accepted them in the past, we may as well preserve that behaviour for now.)
In practice, this is what the user will see from `cargo …
=> crates_io_tarball: error if multiple manifests are found

Cargo.lock, Cargo.toml
Reverts rust-lang/crates.io#7003
A random shot in the dark to address https://github.com/rust-lang/crates.io/issues/7039 🤷‍♂️ 
The only usage of `dashmap` in our codebase is the download counter, so maaaayyyybeeee this update caused the issues? We'll see once we deploy this to production.
=> Revert "Update Rust crate dashmap to v5.5.1"

app/templates/data-access.hbs
The motivation for this is a couple of recent requests and discussions where it's been clear that (a) we need to document the sparse index as an option, and (b) it's unclear if the crawling limits apply to regular API usage as well.
This integrates the sparse index into the data access recommendations, and makes it clearer that the limits described in the crawling policy also apply to regular API usage.
Cosmetically, the page is now less dense, with some new verbiage particularly around index and API usage.
There should be no change in the actual expectations we have of users in this commit; this is simply trying to more accurately codify what our expectations really are.
=> Update the data access page on crates.io

Cargo.lock, crates_io_tarball/Cargo.toml, crates_io_tarball/src/lib.rs, crates_io_tarball/src/manifest.rs, src/admin/render_readmes.rs, src/controllers/krate/publish.rs
The `cargo_toml` maintainer currently appears unresponsive, while several pull requests for `cargo-manifest` have already been merged and released. Since both crates offer essentially the same functionality we should probably use the one where we can help with the development and maintenance.
=> Replace `cargo_toml` with `cargo-manifest`

src/controllers/krate/publish.rs, src/tests/record.rs
see https://github.com/rust-lang/crates.io/pull/7071#issuecomment-1713083172 :)
Closes #7071
/cc @hi-rustin
=> Remove dummy `let` assignments

Cargo.lock, Cargo.toml, src/admin/render_readmes.rs
close https://github.com/rust-lang/crates.io/pull/7072
See: https://github.com/chronotope/chrono/pull/1251
=> Update Rust crate chrono to v0.4.29

app/components/settings/api-tokens.hbs
https://crates.io/settings/tokens incorrectly says `~/.cargo/credentials`, it's missing the `.toml` in the filename.
=> Replace hardcoded credentials path with cargo docs link

src/tests/krate/publish.rs
Closes #6952
This deletes the flakey ratelimit test and adds four new ones:
- `publish_new_crate_ratelimit_hit`: Adds a row into `publish_limit_buckets` as though the user had been ratelimited, with a `last_refill` far in the future to ensure the ratelimiting code is hit
- `publish_new_crate_ratelimit_expires`: Ditto, but `last_refill` is now juuuust far enough in the past for the ratelimit to hit
- `publish_new_crate_ratelimit_expires`: Defaults the ratelimit to one crate every day, then sets the override to allow the test user to publish two crates a day, and then test that they can publish 2 tests a day and no more.
- `publish_new_crate_expired_override_ignored`: Ditto, but the override `expires_at` is set to just moments ago, and then checks that the test user has the normal (1-crate) …
=> Fix flakey ratelimit test

src/views/krate_publish.rs
yeah, I know some countries spell it "deserialising" but since the trait is using the American way of spelling it, I guess our docs should do the same. also, "serlializing" definitely seems wrong :D
=> views/krate_publish: Fix docs typos

src/tests/builders/publish.rs
This avoids a bit of unnecessary cloning and generally feels easier to read to me 😅
=> tests/builders/publish: Simplify `create_publish_body()` fn

src/controllers/krate/publish.rs, src/tests/krate/publish/auth.rs, src/tests/krate/publish/snapshots/all__krate__publish__auth__new_krate_wrong_user.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-10.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-2.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-3.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-4.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-5.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-6.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-7.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-8.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-9.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required-2.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required-3.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required.snap, src/tests/krate/publish/validation.rs
Instead of using things like `missing_metadata_error_message()` in our production **and** test code, this PR switches us over to using snapshot tests instead, which are easy to update if we were to change our error messages.
=> tests/krate/publish: Use more snapshot tests for error responses

crates_io_tarball/src/lib.rs
This should not be a huge deal in terms of performance, but ensures that we generate consistent error messages since `BTreeMap` has a defined non-random iteration order.
=> tarball: Use `BTreeMap` for `manifests`

src/tests/krate/publish/categories.rs, src/tests/krate/publish/dependencies.rs, src/tests/krate/publish/features.rs, src/tests/krate/publish/keywords.rs, src/tests/krate/publish/manifest.rs, src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_rename.snap, src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature.snap, src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature_name.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap, src/tests/krate/publish/snapshots/all__krate__publish__manifest__manifest_casing.snap, src/tests/krate/publish/snapshots/all__krate__publish__manifest__multiple_manifests.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__empty_json.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_version.snap, src/tests/krate/publish/validation.rs
While looking at https://github.com/rust-lang/crates.io/blob/f0c8f5e64acfd6e57dc2a060b2b7f09893a446c6/src/views/krate_publish.rs, I noticed that quite a few of these serde-based validations are not covered by our test suite. This PR adds a couple more tests to ensure that these cases are sufficiently tested.
=> Add more tests for the publish workflow

src/tests/github_secret_scanning.rs, src/tests/krate/following.rs, src/tests/krate/publish/dependencies.rs, src/tests/krate/publish/tarball.rs, src/tests/krate/publish/validation.rs, src/tests/owners.rs, src/tests/routes/crates/owners/add.rs, src/tests/routes/crates/versions/yank_unyank.rs, src/tests/routes/me/email_notifications.rs, src/tests/routes/me/tokens/create.rs, src/tests/routes/me/updates.rs, src/tests/routes/users/update.rs, src/tests/user.rs, src/tests/util.rs, src/tests/util/mock_request.rs, src/tests/worker/git.rs
This PR avoids a couple of unnecessary `Vec<u8>` cloning in our test suite. Instead of passing a reference of `Vec<u8>` into the functions which is then immediately turned into a `Vec<u8>` again, we can use `impl Into<Bytes>` to avoid the unnecessary cloning.
=> tests/util: Avoid unnecessary cloning

src/tests/builders/publish.rs
This field is not accessed outside of the module (anymore?), so there is really no need for this to be public.
=> tests/builders/publish: Decrease `krate_name` visibility

Cargo.lock, Cargo.toml, src/tests/builders/publish.rs, src/tests/krate/publish/basics.rs, src/tests/krate/publish/inheritance.rs, src/tests/krate/publish/manifest.rs, src/tests/krate/publish/max_size.rs, src/tests/krate/publish/tarball.rs, src/tests/routes/crates/read.rs, src/views/krate_publish.rs
Up until now our `PublishBuilder` only generated a very basic manifest with `name` and `version` fields by default, even if e.g. dependencies or features were added to the builder. This led to inconsistencies between the JSON metadata and the content of the `Cargo.toml` file in the generated tarball.
This PR fixes the issue by moving the manifest and tarball generation into the `build()` method and extending it to generate the necessary data in the `Cargo.toml` file using `cargo_manifest`.
Note that the `tarball()` and `files()` methods of the `PublishBuilder` had to be replaced for this to work properly. `tarball()` is replaced by direct usage of `PublishBuilder::create_publish_body()`. `files()` is replaced by `add_file()`. Additionally `custom_manifest()` and `no_manifest()` have been …
=> tests/PublishBuilder: Generate correct manifests

src/views/krate_publish.rs
According to the git history, the loop was implemented before we had a dedicated `EncodableKeyword` struct, but was apparently never migrated once the struct was introduced.
=> EncodableKeywordList: Move keyword length validation into `EncodableKeyword` impl

Cargo.lock, Cargo.toml, src/tests/builders/publish.rs
Hidden in that diff is also a small performance improvement by using `with_capacity()` and calculating the correct length upfront.
=> tests/builders/publish: Simplify `create_publish_body()` fn by using `BytesMut` struct

crates_io_tarball/src/builder.rs, crates_io_tarball/src/lib.rs, src/admin/render_readmes.rs, src/tests/builders/publish.rs, src/tests/krate/publish/max_size.rs, src/tests/krate/publish/tarball.rs
This was a cute idea, but not really worth it in the end...
=> tarball/builder: Remove `prefix` field and associated constructor arguments

tests/utils/ajax-test.js
This should help when debugging why this assertion is not working correctly on CI or locally...
e.g. for some reason it currently fails on https://github.com/rust-lang/crates.io/pull/7149, but appears to work fine on this PR 🤷‍♂️
=> tests/utils/ajax: Add assertion description

src/controllers/helpers/pagination.rs, src/downloads_counter.rs, src/rate_limiter.rs, src/swirl/runner.rs, src/tests/blocked_routes.rs, src/tests/github_secret_scanning.rs, src/tests/owners.rs, src/tests/read_only_mode.rs, src/tests/routes/crates/list.rs, src/tests/routes/crates/read.rs, src/tests/routes/metrics.rs, src/tests/routes/users/read.rs, src/tests/user.rs, src/tests/util/response.rs, src/worker/update_downloads.rs
The majority of assertions in this project use `actual, expected` ordering. This changes the ones with `expected, actual` ordering to use the other one.
This makes it more consistent when trying to understand what `left` and `right` mean in the test suite output.
The `claims` assertion library that we use also assumes `actual, expected` ordering.
=> Unify `assert_eq!()` argument order

src/tests/krate/publish/max_size.rs, src/tests/util/test_app.rs
A tarball with three empty files and a valid manifest shouldn't immediately hit those limits, so let's increase them a little bit...
=> tests: Increase default upload size limits

crates_io_tarball/src/lib.rs
Since the `if` branch returns an error we don't have to wrap the remaining code in an `else` block. This allows us to get rid of one level of indentation and makes the code a little easier to read.
=> tarball: Simplify `manifests.len()` condition

src/tests/krate/publish/rate_limit.rs
These do not appear to be necessary since the test suite runs just fine without them and should default to the test pool anyway.
=> Remove unnecessary `with_database()` calls

src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/views.rs, src/views/krate_publish.rs
... and the corresponding variables to `metadata`.
It feels to me like this is a more straight-forward and easier to understand name compared to `EncodableCrateUpload` and `new_crate`, especially because we also have a `NewCrate` struct that was not at all related to the `new_crate` variable 😅
=> EncodableCrateUpload: Rename struct to `PublishMetadata`

tests/utils/ajax-test.js
The Chrome browser version on GitHub Actions apparently got bumped lately, which was causing issues with our test suite. One of our tests is asserting against a specific network error message and that message was updated to include more information than before. This PR fixes the issue by making the test compatible with the new Chrome version.
=> tests/utils/ajax: Adjust error message assertion for new Chrome release

src/controllers/token.rs, src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__list__list_tokens.snap
In a real world scenario this should not make a huge difference, since `id` is a monotonically increasing counter, so the order should be the same as with `created_at`. We do have the unique `id` index though, which might be used by the database to speed up the query.
The main reason for this change is to ensure a stable sort order for our test suite. The `list_tokens()` test case has been a bit flaky lately (see https://github.com/rust-lang/crates.io/actions/runs/6305682314/job/17119535543?pr=7178) because the `created_at` column for all tokens is the same during a test, due to each test running within a Postgres transaction. The `id` however won't be the same, so we can achieve a stable sort order that way.
=> controllers/token: Order by `id` instead of `created_at`

src/controllers/krate/publish.rs
There are already two `.to_string()` calls happening within the `request_log.add()` function, so there is no need for us to allocate memory a third time if we can just pass in a `&str` :)
=> controllers/krate/publish: Remove unnecessary string allocations

tests/components/version-list-row-test.js, tests/models/version-test.js
There are unfortunately still plenty of deprecation warnings left in the production code since Ember Data decided to completely throw away their previous philosophy and make async relationships significantly harder to work with... 😩
=> Ember Data: Fix `toArray()` deprecation warnings in the test suite code

src/controllers/krate/publish.rs, src/models/krate.rs, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_urls.snap, src/tests/krate/publish/validation.rs
The reserved name and URL validations are somewhat unrelated to the `NewCrate` struct and are much more useful as independent validations, that can be run in combination with some of the other publish validations that we have (e.g. missing/empty metadata fields or the Cargo.toml content validation).
This PR extracts that functionality and moves it to the publish module instead.
=> models/krate: Move URL and name validation out of `create_or_update()`

src/controllers/krate/publish.rs, src/downloads_counter.rs, src/tests/all.rs, src/tests/util/test_app.rs
Less verbose, and with dedicated `tracing` instrumentation :)
=> Use `db_write()` instead of the `primary_database` field

src/tests/krate/publish/manifest.rs, src/tests/krate/publish/max_size.rs
Without this the server is not supposed to accept any publish requests. Once we switch from reading the values from the metadata JSON blob to using the embedded `Cargo.toml` file, these tests would start to fail.
=> tests/krate/publish: Add missing `description` and `license` fields to generated `Cargo.toml` files

src/controllers/krate/publish.rs
Looks like this is no longer necessary...
=> controllers/krate/publish: Remove obsolete `license.clone()` call

src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-2.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-3.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap, src/views/krate_publish.rs
This PR changes our handling of the `description`, `license` and `license_file` fields so that they are read from the `Cargo.toml` file embedded in the crate tarball, instead of the metadata JSON blob.
This is another step forward towards avoiding issues like https://blog.vlt.sh/blog/the-massive-hole-in-the-npm-ecosystem in the Rust ecosystem. Note that, compared to e.g. npm, this is currently not exploitable due to the way cargo works, but it is still confusing to our users if the metadata does not match what is actually in the tarball.
This change required a small reordering of things in the publish endpoint. Specifically, the publish size limit is read from the database earlier than previously, which could potentially cause a race condition, but from what I can tell this race condition …
=> publish: Use `description`, `license` and `license_file` fields from embedded `Cargo.toml` file

src/controllers/krate/publish.rs, src/lib.rs, src/licenses.rs, src/models/version.rs
This PR moves the license expression parsing code out of `models::version` into a dedicated module. In the second commit the API is slightly simplified and the conversion from regular error to app-specific error wrapper is moved into the route handler that calls the fn.
=> Extract `licenses` module

src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-2.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-3.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap, src/views/krate_publish.rs
This PR is similar to #7194, but this time for the `homepage`, `documentation` and `repository` fields.
=> publish: Use `homepage`, `documentation` and `repository` fields from embedded `Cargo.toml` file

src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap, src/views/krate_publish.rs
This PR is similar to https://github.com/rust-lang/crates.io/pull/7194, but this time for the `links` field
=> publish: Use `links` field from embedded `Cargo.toml` file

src/tests/builders/publish.rs, src/views/krate_publish.rs
There appears to be no relevant benefit from wrapping the category strings in a newtype struct here, since no custom deserialization/validation is performed.
=> views/krate_publish: Remove unnecessary `EncodableCategory` struct

src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap, src/views/krate_publish.rs
... instead of the metadata JSON blob
see also:
- https://github.com/rust-lang/crates.io/pull/7194
- https://github.com/rust-lang/crates.io/pull/7201
- https://github.com/rust-lang/crates.io/pull/7204
=> publish: Read `categories` metadata from embedded `Cargo.toml` file

src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-2.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-3.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords.snap, src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap, src/views/krate_publish.rs
... instead of the metadata JSON blob
see also:
- https://github.com/rust-lang/crates.io/pull/7194
- https://github.com/rust-lang/crates.io/pull/7201
- https://github.com/rust-lang/crates.io/pull/7204
- https://github.com/rust-lang/crates.io/pull/7209
=> publish: Read `keywords` metadata from embedded `Cargo.toml` file

src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature.snap, src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature_name.snap, src/views/krate_publish.rs
... instead of the metadata JSON blob
see also:
- https://github.com/rust-lang/crates.io/pull/7194
- https://github.com/rust-lang/crates.io/pull/7201
- https://github.com/rust-lang/crates.io/pull/7204
- https://github.com/rust-lang/crates.io/pull/7209
- https://github.com/rust-lang/crates.io/pull/7214
=> publish: Read `features` metadata from embedded `Cargo.toml` file

src/views/krate_publish.rs
This may have been used in the past but is apparently not needed anymore.
=> views/krate_publish: Remove unused `PartialEq` impl

src/controllers/krate/publish.rs
The `DependencyKind` enum implements `ToSql`, so we don't have to explicitly cast this to an integer (anymore).
=> publish: Remove unnecessary integer cast

src/controllers/krate/publish.rs
Before this change we were sending out a query for each added dependency, just to look up the corresponding `id` and check if the dependency exists on crates.io. With longer lists of dependencies this behavior is quite wasteful and commonly referred to as an N+1 query.
After this change we send out a single query with all dependency names, save the resulting `name, id` tuples to an in-memory `HashMap` and then use that map inside the loop to check if the corresponding crate exists.
=> publish: Avoid N+1 query in `add_dependencies()`

app/components/version-list/row.module.css, app/helpers/pretty-bytes.js, tests/unit/helpers/pretty-bytes-test.js
This is from
- https://github.com/rust-lang/crates.io/discussions/7177
and changes the unit of package size to use binary prefixes as shown in test cases in `tests/unit/helpers/pretty-bytes-test.js`.
=> Switch to binary prefixes

src/controllers/krate/publish.rs
These imports always cause a lot of name clashes with local variables since they often match the SQL column names. By prefixing the column names with the table name we can easily avoid this confusing issue.
=> publish: Remove `dsl::*` import

src/controllers/krate/publish.rs, src/tests/builders/dependency.rs, src/tests/builders/publish.rs, src/tests/krate/publish/dependencies.rs, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_name.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_rename.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_feature_name.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__new_krate_with_broken_dependency_requirement.snap, src/views/krate_publish.rs
This moves the dependency validations from the `serde` Deserializers to a new `validate_dependencies()` fn. This is in preparation for moving this code away from using the JSON metadata and reading the dependencies from the embedded `Cargo.toml` file instead.
=> publish: Move dependency validation to `validate_dependency()` fn

src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-2.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-3.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-4.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-5.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_version.snap, src/views/krate_publish.rs
This is roughly similar to #7234, to have everything in one place instead of scattered across the codebase.
=> publish: Move crate name and version validation to publish controller

Cargo.toml, src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/views/krate_publish.rs
... instead of the metadata JSON blob
see also:
- https://github.com/rust-lang/crates.io/pull/7194
- https://github.com/rust-lang/crates.io/pull/7201
- https://github.com/rust-lang/crates.io/pull/7204
- https://github.com/rust-lang/crates.io/pull/7209
- https://github.com/rust-lang/crates.io/pull/7214
- https://github.com/rust-lang/crates.io/pull/7215
=> publish: Read dependencies metadata from embedded `Cargo.toml` file

.github/workflows/coverage.yml, backend.Dockerfile
GitHub releases are sometimes a bit delayed and need manual work from the release team for patch releases. GitHub tags appear to be more reliable, so let's use those instead.
This should avoid https://github.com/rust-lang/crates.io/pull/7241 and https://github.com/rust-lang/crates.io/pull/7242 being two separate PRs instead of a single one.
=> renovate: Use `github-tags` datasource for Rust updates

src/controllers/krate/owners.rs, src/models/krate.rs, src/models/owner.rs, src/tests/owners.rs, src/tests/routes/crates/list.rs, src/tests/routes/me/get.rs, src/tests/routes/users/stats.rs, src/tests/team.rs
Fixes #1818.
My intended solution here is:
- Add a parameter to decide how the team gets looked up (in the database: `true`, vs. in the GH API: `false`)
- Pass `true` when deleting owners and `false` when adding them
Unfortunately the `Crate::owner_add` and `Crate::owner_remove` methods are like four steps above the actual DB lookup, and they call into the exact same stack of methods to get an `Owner`. I could have also created a new stack of methods but this way seems like it'll require modifying less code, which is a big positive for someone who doesn't really understand how this project works.
That said, I'm not 100% confident in where I've put the branch. Right now it's right next to the error message itself but it might belong higher up, e.g. maybe in `Team::create_or_update` it …
=> Allow removing deleted organizations from crate owners

src/controllers/krate/publish.rs, src/tests/krate/publish/dependencies.rs, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__new_krate_sorts_deps.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__new_krate_with_dependency.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__new_with_renamed_dependency.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__new_with_underscore_renamed_dependency.snap, src/tests/krate/publish/snapshots/all__krate__publish__features__features_version_2.snap
When cargo reads a `Cargo.toml` file and sees a `foo = "1.0"` dependency declaration it saves the version requirement as a `semver::VersionReq`. If cargo then publishes the crate and transforms the dependency declaration to the publish metadata JSON blob it essentially uses `semver::VersionReq::to_string()` which normalizes the version requirement and transforms `1.0` into `^1.0`.
On the crates.io side we've been accepting these values from the metadata as-is and only using `VersionReq::parse()` to check if it is a valid version requirement, but there was no normalization performed.
Since we now read dependency declarations directly from the embedded `Cargo.toml` file ourselves (see https://github.com/rust-lang/crates.io/pull/7238) the normalization that cargo (unintentionally?) performed …
=> publish: Normalize dependency version requirements

crates_io_tarball/src/manifest.rs, src/controllers/krate/publish.rs, src/tests/krate/publish/manifest.rs
This ensures that all validation code lives in the same place instead of being scattered across the codebase :)
=> tarball: Move `rust-version` validation into publish endpoint code

src/controllers/krate/publish.rs, src/tests/builders/publish.rs, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_license.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required-2.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required-3.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required.snap, src/tests/krate/publish/validation.rs
This expands the error message when the `license` expression is not valid. It provides some help text if the user needs a custom license, and also points to the cargo documentation. It also includes the actual error message from the validator, which can be helpful if you have a more complex expression, and it may not be clear exactly which part of the expression is invalid.
This also clarifies the wording when `license` is not specified.
The error may look something like this:
```
error: failed to publish to registry at http://localhost:8888/
Caused by:
the remote server responded with an error: unknown or invalid license expression; see http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers
Note: If you have a non-standard license that is not …
```
=> Expand error messages for invalid license information

Cargo.lock, Cargo.toml, src/controllers/github/secret_scanning.rs
The `ring` project is releasing new versions without tags on the corresponding repository or even changelog entries, so we basically have no idea of what is happening over there. `p256` is a pure-Rust alternative for the only `ring` algorithm that we're currently using and it also includes functions to parse the PEM format public keys.
=> Replace `ring` dependency with `p256`

Cargo.lock, crates_io_markdown/Cargo.toml, crates_io_markdown/lib.rs
see https://insta.rs/docs/snapshot-types/#inline-snapshots
The second commit in this PR also fixes a bug in our code block rendering tests which was discovered by the introduction of the snapshot tests. The combination of `r#"` strings and `\` led to us not actually using correct markdown syntax and the test only working by accident.
=> markdown: Use insta inline snapshots for tests

app/components/rendered-html.module.css, crates_io_markdown/lib.rs, tests/acceptance/readme-rendering-test.js
I realized that crates.io currently doesn't seem to render _Markdown Footnotes_ which are part of the GitHub Flavored Markdown spec. This is already supported on GitHub (obviously) and docs.rs renders them as well.
This conflicts a little bit with the HTML sanitiser, as it rewrites IDs but I did my best to match them properly in the URL sanitizer.
=> Render footnotes in crates' README.md

src/tests/builders/publish.rs, src/tests/krate/publish/max_size.rs, src/tests/krate/publish/tarball.rs, src/tests/krate/publish/validation.rs, src/tests/util.rs
This allows us to use `publish_crate()` in more places, which ensures that `run_pending_background_jobs()` is run when asserting on `app.stored_files()`.
=> RequestHelper: Accept all `Into<Bytes>` in `publish_crate()` fn

.buildpacks
see https://github.com/heroku/heroku-buildpack-nginx/releases/tag/v1.10
=> Heroku: Update `nginx` buildpack to v1.10

frontend.Dockerfile, package.json
Reverts rust-lang/crates.io#7281
Looks like Heroku can't find this version yet... 😩
=> Revert "Update dependency node to v20.8.1"

Cargo.toml
Path dependencies are automatically members of the workspace and don't have to be added explicitly. This PR tries to make it more explicit to reduce the confusion.
=> Make membership of the workspace more explicit

src/db/sql_types/semver.rs, src/models/version.rs
This struct was introduced to simplify the (de)serialization of the `Triple` struct from the database, because the `models::Version` struct implements the `De/Serialize` traits. As it turns out, these traits from the `models::Version` struct are not actually used anywhere though.
This PR removes the unused trait impls and then removes the now obsolete `SerializedTriple` struct.
=> db/sql_types/semver: Remove `SerializedTriple` struct

Cargo.lock, Cargo.toml, src/controllers/version/downloads.rs
**Please do not merge this pull request yet.**
Hi. We are planning to release a new version of [moka](https://github.com/moka-rs/moka/) cache sometime soon, hopefully in a couple of weeks from now. It has major breaking changes (for good reasons) and this PR updates the codes for it. v0.12.0 is currently in beta so this pull request (PR) is depending on the latest [v0.12.0-beta.2](https://crates.io/crates/moka/0.12.0-beta.2) for now.
For details of the breaking changes, please see the [MIGRATION-GUIDE.md](https://github.com/moka-rs/moka/blob/main/MIGRATION-GUIDE.md).
I will let you know when moka v0.12.0 is released, but since this is the biggest change in moka's history (e.g. [one of the PRs](https://github.com/moka-rs/moka/pull/294) had +5,624 −963 lines in the diff), I am a bit …
=> Update dependency moka to v0.12.1

src/tests/builders/publish.rs
see https://github.com/LukeMathWalker/cargo-manifest/pull/27
=> tests/builders/publish: Use new cargo-manifest `simplify()` API

src/middleware/app.rs, src/middleware/balance_capacity.rs, src/middleware/block_traffic.rs, src/middleware/ember_html.rs, src/middleware/log_request.rs, src/middleware/session.rs, src/middleware/static_or_continue.rs, src/middleware/update_metrics.rs
The goal of this is to give us more datapoints to identify what middlewares might affect the performance of the system.
=> middleware: Add `tracing` instrumentation

src/middleware.rs
Apparently this is derived by default now and doesn't need to be explicitly specified anymore 🎉
=> middleware: Remove unnecessary generic type parameter

config/nginx.conf.erb, src/config/server.rs, src/middleware.rs, src/middleware/common_headers.rs, src/tests/util/test_app.rs
We eventually would like to get rid of the `nginx` wrapper that we use on Heroku and rely completely on our axum server. This PR is one more step in that direction. It migrates most of the `add_header` calls from the nginx configuration to a custom axum middleware.
Note that the first commit simplifies the `s3_host()` fn a little bit to make the migration easier. The commit message explains the reasoning behind the simplification.
=> Migrate common headers from nginx to axum middleware

config/nginx.conf.erb
We are no longer using these libraries so there is no need for these configuration options anymore :)
=> nginx: Remove obsolete `ember-fetch` and `moment` paths from configuration

Cargo.toml, config/nginx.conf.erb, src/middleware.rs, src/router.rs
We've been using the [`client_body_timeout 30` nginx option](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout) to ensure timeouts between request body read operations that can be caused by maliciously slow clients.
https://docs.rs/tower-http/latest/tower_http/timeout/struct.RequestBodyTimeoutLayer.html serves a similar purpose, and while we're at it, I've also added corresponding request and response body timeouts (see http://nginx.org/en/docs/http/ngx_http_core_module.html#send_timeout). This should cover all of the timeouts that nginx and the Heroku router have provided us so far.
=> Migrate request and body timeouts from nginx to axum

config/nginx.conf.erb
This is mostly copied over and adapted from the official nginx documentation, to make it easier to read this configuration file for people that don't deal with nginx on a daily basis (aka. me) :D
=> nginx: Add documentation to the configuration file

src/middleware/app.rs, src/middleware/balance_capacity.rs, src/middleware/block_traffic.rs, src/middleware/common_headers.rs, src/middleware/ember_html.rs, src/middleware/log_request.rs, src/middleware/session.rs, src/middleware/static_or_continue.rs, src/middleware/update_metrics.rs
Reverts rust-lang/crates.io#7315
As somewhat expected, this was not particularly useful and caused more noise than anything else. Let's revert it and find other ways of getting to the information we're interested in...
=> Revert "middleware: Add `tracing` instrumentation"

Cargo.lock, Cargo.toml, config/nginx.conf.erb, src/middleware.rs
see https://docs.rs/tower-http/latest/tower_http/compression/index.html
This is using slightly different settings than with nginx, but most of them seem reasonable:
- nginx defaults to 20 bytes, we explicitly set it to 512 bytes for undocumented reasons, tower-http defaults to 32 bytes. using the defaults here appears to be fine on first glance. if we see problems with this we can still change this to use the old 512 bytes setting.
- nginx uses a MIME type allow list list, while tower-http uses a deny list, which includes by default all images except for SVGs. since we don't use any exotic MIME types (crate files come from S3 directly) this should be fine.
- nginx only supports gzip compression, tower-http enables brotli, deflate, gzip and zstd 🎉 
- tower-http uses the "default …
=> Migrate gzip compression from nginx to `tower-http::compression`

README.md, docs/ARCHITECTURE.md, docs/BACKEND.md, docs/CONTRIBUTING.md, docs/FRONTEND.md, package.json, src/worker/dump_db/readme_for_tarball.md
When I working on [this PR](https://github.com/rust-lang/crates.io/pull/7335), my vscode automatically changes the format of markdown files. So I think it would be better to use prettier to format all markdowns.
=> Format all markdown files with prettier

src/config/server.rs
=> CSP: Fix `Content-Security-Policy` header for `github-redirect.html` file

app/components/rendered-html.module.css
Fixes https://github.com/rust-lang/crates.io/issues/7351
Before:
After:
=> Fix markdown styling for regular `pre` tags

src/lib.rs, src/middleware/log_request.rs, src/real_ip.rs
This PR essentially implements http://nginx.org/en/docs/http/ngx_http_realip_module.html inside of our axum server, as another step towards removing the nginx wrapper.
… but there is a twist. Heroku is somewhat broken. Their broken handles the header incorrectly in case the original request contains multiple `X-Forwarded-For` headers. Instead of adding the connecting IP to the last header, or merging the headers, it adds the IP to the first header 😱 
I've reported this to Heroku in the form of a support ticket, but while that is being processed we will unfortunately have to use a workaround. Luckily CloudFront merges these headers, so if we get multiple headers we can know for certain that the request did not come from CloudFront.
On the bright side, we only use the value for logging at …
=> Implement `X-Forwarded-For` header processing

.buildpacks
Using this custom buildpack brings our slug size down from 303 MB to 169 MB. It also appears to solve a Rust build caching issue with the generic Rust buildpack that we had been using so far.
The main source of slug size savings is the removal of the `node_modules` folder after the build, and that the Node.js binary is not included in the slug, since it is only needed at build-time.
see https://github.com/Turbo87/heroku-buildpack-crates-io/blob/main/bin/compile
=> Use custom crates.io buildpack

.buildpacks
According to the infra team, the buildpack is only needed for additional per-dyno metrics, and the log collection is independent from this. This buildpack however is responsible for a 90 MB increase of the slug size on Heroku. If we don't gain that much from having it, then we should remove it and improve our dyno boot times again :)
After this PR the slug size is down to 73 MB (from 303 MB earlier to day)
=> Heroku: Remove Datadog buildpack

src/bin/server.rs, src/config/server.rs, src/tests/util/test_app.rs
There is a `Duration` type in the std lib, so we might as well use it instead of having `_ms` suffixed variables that are converted to `Duration` on demand :D
=> config/server: Change `downloads_persist_interval` type to `Duration`

src/storage.rs
We should not serialize the full payloads for logging/tracing purposes...
=> storage: Adjust skipped fields for instrumentation

src/tests/unhealthy_database.rs, src/tests/util.rs, src/tests/util/test_app.rs
This decouples the chaos-proxy usage from the usage of the test-database-pool and makes the use of a database replica connection a bit easier to configure. This also prepares for some upcoming changes related to the `FreshSchema` struct.
=> tests/test_app: Split `with_database()` into `without_test_database_pool()`, `with_chaos_proxy()` and `with_replica()`

src/background_jobs.rs, src/worker/dump_db.rs, src/worker/git.rs
There is no need to unnecessarily consume the `Job` instance in the `perform()` call...
=> background_jobs: Adjust `perform()` to work on `&self`

src/background_jobs.rs
They might have been used at some point in the past, but that appears to no longer be the case.
=> background_jobs: Remove unused structs

src/background_jobs.rs
The `ToString` trait is automatically implemented for anything implementing `Display`, so we don't need to explicitly specify it.
=> background_jobs: Simplify `enqueue_sync_to_index()` trait bounds

src/background_jobs.rs, src/bin/background-worker.rs
Looks like we don't need the `Arc` since the environment itself is already inside an `Arc` :)
=> background_jobs: Simplify `Environment` struct

src/background_jobs.rs, src/worker/dump_db.rs, src/worker/readmes.rs
Instead of using so many arguments in these functions it's easier to just pass in a reference to the corresponding job struct. This also allows us to eventually make this a method of the struct itself.
=> worker: Simplify `perform()` fn arguments

Cargo.lock, Cargo.toml, src/background_jobs.rs, src/worker/daily_db_maintenance.rs, src/worker/dump_db.rs, src/worker/git.rs, src/worker/mod.rs, src/worker/readmes.rs, src/worker/update_downloads.rs
Buckle up, this is a big one!
I recommend reviewing this commit-by-commit and with the "Hide whitespace" option turned on, to ignore whitespace-only indentation changes.
The goal of this PR is to unify how our background job structs look like. After this PR they all have an associated `JOB_NAME` constant and a `run()` fn, all with the same arguments. This allows us to generate the `perform()` fn with the existing `jobs!` macro.
And if you now think "this looks a lot like it should be trait definition" then you are totally right. Extracting a corresponding trait and making the runner generic over the registered jobs will come in a follow-up PR :)
As a side-effect the move to the `JOB_NAME` constant allows us to get rid of the `paste` dependency again and significantly simplify the `jobs!` …
=> worker: Extract job structs

migrations/2023-10-19-092709_fix_semver_no_prerelease_fn/down.sql, migrations/2023-10-19-092709_fix_semver_no_prerelease_fn/up.sql, src/db/sql_types/semver.rs, src/sql.rs
Resolves https://github.com/rust-lang/crates.io/issues/3882
This PR is basically reviving https://github.com/rust-lang/crates.io/pull/3886, since we now have a generated and stored `semver_no_prerelease` column in the `versions` table, which should fix the performance concerns that led to #3886 being initially rejected.
=> SQL: Fix metadata handling in to_semver_no_prerelease() function

src/background_jobs.rs, src/worker/daily_db_maintenance.rs, src/worker/dump_db.rs, src/worker/git.rs, src/worker/readmes.rs, src/worker/update_downloads.rs
As promised in #7406, this PR extracts a `BackgroundJob` trait. The trait itself it not really used in itself anywhere yet, but it ensures that all job structs conform to the same API and can't be incompatible with the `jobs!` macro.
=> background_jobs: Extract `BackgroundJob` trait

src/background_jobs.rs, src/worker/dump_db.rs, src/worker/git.rs, src/worker/readmes.rs
This PR extracts `new()` constructor functions for all of our background job structs, except for the unit structs, for which they seem somewhat unuseful.
While this is slightly more verbose on the implementation side, it also allows us to reduce the visibility level of the struct fields, since they only need to be read and written in the same module now.
=> worker: Extract `...Job::new()` fns

src/background_jobs.rs
These are only used from within the `enqueue_sync_to_index()` fn at this point, so we might as well inline them and throw away the unnecessary parts :D
=> background_jobs: Inline `sync_to_git/sparse_index()` fns

src/admin/enqueue_job.rs, src/background_jobs.rs, src/controllers/krate/publish.rs
Now that all job structs implement the `BackgroundJob` trait there is no need for us anymore to go through the `Job` enum when enqueueing new background jobs. This PR moves the `enqueue()` fns into the `BackgroundJob` trait and inlines some of the now obsolete constructor functions.
=> background_jobs: Move `enqueue()` fn into `BackgroundJob` trait

src/background_jobs.rs, src/controllers/krate/publish.rs, src/worker/git.rs, src/worker/readmes.rs
This means we can call `enqueue()` on a job struct and it will automatically use the correct default priority. `enqueue_with_priority()` can still be used to override the default priority value.
=> background_jobs: Add `PRIORITY` constant to `BackgroundJob` trait

src/tests/read_only_mode.rs, src/tests/util/test_app.rs, src/tests/util/test_database.rs
Previously these tests were using `SET TRANSACTION READ ONLY` to enter a read-only state, while in production the `read_only_mode` database connection pool option is used. This PR refactors the tests to use dedicated databases for these tests and a production-like database connection pool with the `read_only_mode` option set.
This requires the `TestApp::db()` method to not use the same database pool as the app itself, because that would be set to read-only mode. Thus this PR also refactors that method to use a dedicated connection pool it the test is using a `TestDatabase`.
=> tests/read_only_mode: Use real `read_only_mode` setting

src/admin/delete_crate.rs, src/admin/delete_version.rs, src/admin/yank_version.rs, src/background_jobs.rs, src/bin/background-worker.rs, src/controllers/krate/publish.rs, src/controllers/version/yank.rs, src/swirl/runner.rs, src/tests/util/test_app.rs, src/tests/worker/git.rs, src/worker/mod.rs
This new API decouples the `Runner` from the `Job` enum and makes it possible to configure the runner with different sets of job types, for example for testing purposes.
This allows us to completely get rid of the `Job` enum and similarly the custom `jobs!` macro.
The registration of the crates.io-specific job types is implemented in a `register_crates_io_job_types()` fn in the `RunnerExt` extension trait, to keep it decoupled from the background runner implementation in the `swirl` module.
=> swirl/runner: Add `register_job_type()` fn

.github/renovate.json5
Unless they correspond to an actual version update we don't want these to be updated...
=> renovate: Disable `digest` updates

src/background_jobs.rs, src/bin/background-worker.rs, src/swirl/runner.rs, src/tests/util/test_app.rs, src/worker/daily_db_maintenance.rs, src/worker/dump_db.rs, src/worker/git.rs, src/worker/mod.rs, src/worker/readmes.rs, src/worker/update_downloads.rs
Instead of assuming that the `Runner` will always work in combination with the `Environment` struct, we can make it generic now and let the job structs define what type of context they assume to get passed into them.
This, again, reduces the tight coupling between the `Runner` and our application-specific code (i.e. the `Environment` struct).
The design is roughly based on what https://github.com/rafaelcaricio/backie does :)
=> swirl/runner: Make `Runner` generic over `Context`

src/admin/delete_crate.rs, src/admin/delete_version.rs, src/admin/enqueue_job.rs, src/admin/git_import.rs, src/admin/migrate.rs, src/admin/populate.rs, src/admin/render_readmes.rs, src/admin/transfer_crates.rs, src/admin/upload_index.rs, src/admin/verify_token.rs, src/admin/yank_version.rs, src/bin/crates-admin.rs
Instead of using `unwrap()` or `expect()` everywhere in the admin command code we can use the `?` operator to bubble error up to the `main()` fn which then displays the errors appropriately.
=> Reduce panic usage in admin commands

app/templates/index.hbs, tests/acceptance/crate-test.js, tests/acceptance/front-page-test.js
I noticed that when a crate publishes a pre-release version the links in the "Just Updated" section of our front page would point to the crate page, which defaults to the latest stable version. In other words: the shown version is unrelated to the just published pre-release version.
This PR changes the links to point to the corresponding version instead, fixing this confusing behavior.
=> Change "Just Updated" links to point to the corresponding crate version

crates_io_index/repo.rs, src/admin/git_import.rs, src/admin/migrate.rs, src/admin/upload_index.rs, src/bin/background-worker.rs, src/bin/server.rs, src/config/balance_capacity.rs, src/config/base.rs, src/config/database_pools.rs, src/config/sentry.rs, src/config/server.rs, src/db.rs, src/sentry/mod.rs
Instead of panicking, we should bubble errors upwards through the call stack in case something is able to handle these errors properly. This PR changes our `main()` fns to return `Result` so that errors can be bubbled up properly. Similarly, a lot of the `from_environment()` fns that can error for various reasons are now returning `Result` instead of panicking.
=> Return `anyhow::Result` from more functions instead of panicking

src/middleware.rs, src/middleware/log_request.rs, src/middleware/real_ip.rs, src/tests/util.rs
By having the middleware add a `RealIp` request extension we can reuse the result of this operation further down the middleware and request processing stack.
=> Extract `real_ip` middleware

src/config/server.rs, src/controllers/helpers/pagination.rs, src/tests/util.rs
#7364 was a bit too eager to remove the `X-Real-Ip` header from nginx. As it turns out the header was/is still used in two places in our codebase, but the lowercase header value did not show up in my code search back then… 🙈 
Anyway, this PR fixes the IP-based request blocking use-case for large page numbers by using the `RealIp` request extension that was introduced in #7432.
=> Fix IP-based request blocking for large page numbers

src/config/server.rs, src/middleware.rs, src/middleware/block_traffic.rs, src/tests/server.rs, src/tests/snapshots/all__server__block_traffic_via_ip.snap, src/tests/util/test_app.rs
As https://github.com/rust-lang/crates.io/pull/7434 explains, IP-based request blocking is currently broken. This PR fixes the blocking based on the `BLOCKED_IPS` environment variable that we use on production.
=> Fix IP-based request blocking

Cargo.lock, Cargo.toml, crates_io_env_vars/Cargo.toml, crates_io_env_vars/src/lib.rs, crates_io_index/Cargo.toml, crates_io_index/repo.rs, crates_io_test_db/Cargo.toml, crates_io_test_db/src/lib.rs, src/admin/on_call.rs, src/bin/background-worker.rs, src/bin/monitor.rs, src/config/balance_capacity.rs, src/config/base.rs, src/config/database_pools.rs, src/config/sentry.rs, src/config/server.rs, src/lib.rs, src/storage.rs, src/test_util.rs, src/tests/categories.rs, src/tests/util/test_app.rs
The `env()` and `env_optional()` functions in the main package were a good start, but they often were doing too much or too little. This PR introduces four replacement functions: `var()`, `required_var()`, `var_parsed()`, and `required_var_parsed()`. 
The main difference between these and the former functions is that they return `Result` instead of panicking. This allows us to bubble up errors instead of instantly quitting the application.
=> Extract `crates_io_env_vars` package

src/middleware.rs, src/middleware/block_traffic.rs
Before this commit the compile time of the `crates_io` package on my machine was around 50 seconds. After this commit it dropped down to 5 seconds. I'm not entirely sure what the root cause of this is, but `git bisect` suggested that the addition of the `block_by_ip` middleware layer (d1fc384) was at least partially responsible. It looks like the more middleware layers we add, the longer the app takes to compile. It might also be caused by the `from_fn_with_state()` fn usage, which this commit reduces a bit... tl;dr don't know, but it's faster now 🤷‍♂️
=> middleware/block_traffic: Combine middleware functions

crates_io_test_db/src/lib.rs
It turns out that anything in `Lazy` won't actually be dropped, so we were creating a bunch of template databases with random names without cleaning them up after the test suite 🙈 
This drops the unused `Drop` impl and instead attempts to reuse any previously created template database.
New migrations should be applied automatically. Branch changes need to be done carefully though as migrations won't be reverted automatically.
=> test_db: Reuse existing template database instead of recreating it

Cargo.lock, Cargo.toml, src/cloudfront.rs, src/worker/jobs/dump_db.rs, src/worker/jobs/git.rs
As #7439 is causing quite some issues, I thought it would probably be easiest to use the high(ish...)-level CloudFront SDK from AWS instead. Turns out their API isn't particularly easy to use either, but I've somehow made it work.
I've just tested this on our staging server, and everything appears to work as intended.
=> cloudfront: Use official AWS SDK

src/fastly.rs
We don't need to `clone()` this anywhere since the `Environment` struct is usually wrapped in an `Arc`, so we might as well remove the `Clone` impl.
=> fastly: Remove unnecessary `Clone` impl

src/admin/enqueue_job.rs, src/worker/swirl/background_job.rs, src/worker/swirl/runner.rs
The tests of the `Runner` were using the private `get_single_job()` fn in somewhat convoluted ways. This PR refactors the `Runner` tests to use custom job structs instead and only rely on public APIs. This should allow us to refactor the internal workings of the `Runner` in the future without having to modify these tests.
=> worker/swirl/runner: Use public APIs for tests

src/worker/swirl/runner.rs
Now that the `Runner` test suite is no longer relying on this private API we can inline it and get rid of the complicated callback argument 🎉
=> worker/swirl/runner: Inline `get_single_job()` fn

src/cloudfront.rs, src/worker/environment.rs, src/worker/swirl/runner.rs
https://github.com/rust-lang/rust/issues/40628, https://github.com/rust-lang/rust/issues/65717 and https://github.com/rust-lang/rfcs/pull/3260 all show that unwind safety isn't particularly ergonomic to use and implement, and ultimately leads to people slapping `AssertUnwindSafe` everywhere until the compiler stops complaining.
This situation has led to built-in test framework using `catch_unwind(AssertUnwindSafe(...))` (see https://github.com/rust-lang/rust/blob/1.73.0/library/test/src/lib.rs#L649) and libraries like tower-http doing the same (see https://docs.rs/tower-http/0.4.4/src/tower_http/catch_panic.rs.html#198).
As people have mentioned in the threads above, trying to implement this correctly is akin to fighting windmills at the moment. Since the above cases demonstrated that …
=> worker/swirl/runner: Simplify `AssertUnwindSafe` usage

src/worker/swirl/runner.rs
It's enough to have these restrictions on the `impl` block. We don't need them on the `struct` too.
=> worker/swirl/runner: Remove unnecessary `Context` restriction

src/bin/background-worker.rs
All instances of our code hitting the `panic!()` on production so far have been because of a read-only database during database maintenance events (see Sentry).
The r2d2 connection pool can easily recover from these kinds of issues, so a restart of the dyno or re-initialization of the connection pool seems unnecessary.
This is emphasized by the fact that the startup time of the background worker in production is currently multiple minutes due to the index repository cloning. It seems bad to restart the background worker after just five unsuccessful connection attempts when it then takes multiple minutes again until the next attempt.
=> bin/background-worker: Simplify restart behavior

src/bin/background-worker.rs, src/tests/util/test_app.rs, src/worker/environment.rs
We are currently delaying the execution of **any** tasks until the index repository is cloned. This was useful while we were mostly running tasks that needed the repository anyway, but with the introduction of the sparse index, this is no longer the case.
This PR adjusts the code to lazily clone the index when requested, but then also fire off a background thread to start that operation once the background worker has started.
This should allow us to process sparse index updates while the git repository is still being cloned.
Note that due to the way the background worker is implemented this is still not entirely true. While the repository is being cloned a `Mutex` is being held. At some point all five background worker threads might be handling `sync_to_git_index` jobs with all of them …
=> worker: Clone index repository in the background

src/db.rs
There is no need for us to panic in this situation, when we can just bubble up the error instead, like with any other connection errors.
=> db: Return error from `DieselPool::get()` if test connection is still locked

src/worker/swirl/runner.rs
We can rely on structured logging a bit more to make the output more useful :)
=> worker/swirl/runner: Improve logging

src/bin/background-worker.rs, src/db.rs, src/tests/util/test_app.rs, src/worker/environment.rs, src/worker/jobs/daily_db_maintenance.rs, src/worker/jobs/update_downloads.rs, src/worker/swirl/perform_state.rs, src/worker/swirl/runner.rs
This roughly matches the situation on the API server side, where the database pool lives on the `App` struct alongside other parts of the system. The `PerformState` is now only used to share the existing database connection of the `Worker` with the jobs.
=> worker: Move database connection pool into the `Environment` struct

src/controllers/github/secret_scanning.rs
Less `unwrap()`, more better! 🦺
=> controllers/github/secret_scanning: Replace `unwrap()` usage with `is_some_and()`

crates_io_test_db/src/lib.rs
`WITH (FORCE)` causes existing connections to the database to be dropped. This should fix a small flakiness in our test suite where the database connection pool isn't fast enough in dropping its connections, while the `DROP DATABASE` command is already executed.
=> test_db: Use the force when dropping databases

src/app.rs, src/bin/background-worker.rs, src/fastly.rs, src/tests/util/test_app.rs, src/worker/environment.rs, src/worker/jobs/dump_db.rs
The only parts of our codebase that are using the `reqwest` client are the GitHub and Fastly clients. The GitHub client is already taking ownership of a `Client` clone, and this PR refactors the Fastly client to do the same. This then allows us to remove the `http_client` fields from the `App` and `Environment` structs since they are not used by anything else anymore.
=> Simplify `reqwest::Client` usage

src/bin/background-worker.rs, src/fastly.rs, src/worker/jobs/dump_db.rs
This PR refactors our basic `Fastly` client to use async fns and an async `reqwest` HTTP client.
This will should us to eventually write async test cases. This is currently prevented by the `reqwest::blocking::Client` constructor panicking if executed from within an async context.
The background jobs are not async functions yet, but the `DumpDb` job which uses the Fastly client already has an async runtime to upload the database dump to S3 and invalidate CloudFront, so it is relatively straight-forward to integrate there.
=> fastly: Use async `reqwest` client

Cargo.lock, Cargo.toml, src/tests/util.rs
This appears to be the recommended way of testing axum applications (see https://github.com/tokio-rs/axum/blob/axum-v0.6.20/examples/testing/src/main.rs#L77), and it allows us to drop the explicit `tower-service` dependency.
=> tests/util: Use `oneshot()` for testing

src/tests/github_secret_scanning.rs, src/tests/snapshots/all__github_secret_scanning__github_secret_alert_for_revoked_token.snap, src/tests/snapshots/all__github_secret_scanning__github_secret_alert_for_unknown_token.snap, src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token.snap
This ensures that `GitHubSecretAlertFeedbackLabel` serializes correctly, and that the response does not contain any unexpected other fields.
=> tests/github_secret_scanning: Use snapshot assertions

src/tests/util/chaosproxy.rs
`tokio::spawn()` will automatically find the parent runtime, so there is no need to refer to it directly
=> tests/util/chaosproxy: Simplify `spawn()` call

Cargo.toml, src/app.rs, src/bin/server.rs, src/controllers/crate_owner_invitation.rs, src/controllers/github/secret_scanning.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/user/session.rs, src/controllers/version/yank.rs, src/github.rs, src/models/team.rs, src/models/user.rs, src/tests/util/github.rs, src/tests/util/test_app.rs
This is roughly similar to #7475 and converts our `GitHubClient` implementations to use async functions and an async `reqwest` client instead.
This unfortunately requires us to sprinkle a few `Handle::current().block_on(...)` calls across the codebase due to the usage of these functions within `conduit_compat()` (aka. `spawn_blocking()`) calls. I've tested this out on our staging environment and it looked like everything still works as intended. If anyone knows a reason why we should us `block_on()` like that please do let me know! 😅
=> github: Use async `reqwest` client

src/tests/routes/me/email_notifications.rs, src/tests/routes/users/update.rs, src/tests/user.rs
Testing against `json!()` is easier and ensures that the response does not contain any other unexpected JSON fields.
=> Reduce `OkBool` usage in tests

src/tests/server_binary.rs, src/tests/unhealthy_database.rs, src/tests/util/chaosproxy.rs
=> Simplify `ChaosProxy` code

src/worker/environment.rs
see https://docs.rs/parking_lot/latest/parking_lot/type.Mutex.html#differences-from-the-standard-library-mutex
=> worker/environment: Use `parking_lot::Mutex` instead of `std::sync::Mutex`

src/util/tracing.rs
Having ANSI escape sequences sprinkled across the log lines helps the readability on Papertrail, but Datadog does not support them and displays them as their regular characters which makes the logs hard to read and parse. This commit disables the color support when run on Heroku to address that issue.
This might also cause a small decrease in our log volume due to the escape characters no longer counting against it.
=> tracing: Disable colored log output on Heroku

Cargo.lock, Cargo.toml, src/models/token/scopes.rs
This allows us:
- to write tests with non-fatal assertions (e.g. when unit testing a function multiple times in the same test with different inputs)
- see better failure output including the expression that was tested and a diff between the actual and expected value
- reduce the confusion of what side of `assert_eq!()` is the actual and expected value
- implement custom matchers to improve assertion expressiveness (e.g. for `assert_that!(response.status(), is_success())` it will show the actual status code instead of a boolean value)
see https://github.com/google/googletest-rust
=> Use `googletest` crate for assertions

src/tests/server_binary.rs, src/tests/util.rs, src/tests/util/matchers.rs, src/tests/util/response.rs
Before:
```
assertion failed: resp.status().is_redirection()
```
After:
```
Value of: resp.status()
Expected: is a redirection status code (300-399)
Actual: 200,
which isn't a redirection status code (300-399)
at src/tests/server_binary.rs:29:5
```
=> googletest: Extract `is_success()` and `is_redirection()` matchers for `StatusCode`

src/tests/server_binary.rs, src/tests/util/insta.rs, src/tests/util/response.rs, src/util/token.rs
Before:
```
assertion failed: token.expose_secret().starts_with(TOKEN_PREFIX)
```
After:
```
Value of: token.expose_secret()
Expected: starts with prefix "cio"
Actual: "foodBDxOyQu1C7K64sFW4rEVm2BYUaqdnxQ",
which does not start with "cio"
at src/util/token.rs:96:9
```
=> googletest: Use `starts/ends_with()` matchers

Cargo.lock, Cargo.toml, src/ci.rs, src/lib.rs, src/middleware/log_request.rs
Knowing if a request to our package registry came from a CI system or not can be useful in various ways. The immediate interest for us at the moment is telemetry, to be able to what percentage of downloads comes from known public CI systems.
This PR uses the public GitHub Actions CIDR list from https://github.com/Turbo87/github-meta and compares it to the value of the `RealIp` detection extension. If a match is found `ci="GitHub Actions"` is added to the logs.
This is currently focussed on GitHub Actions, but the design is flexible enough to add other CI providers as well.
=> Add CI system detection for requests

src/util/tracing.rs
Reverts rust-lang/crates.io#7505
https://github.com/tokio-rs/tracing/pull/2647 implemented support for the `NO_COLOR` environment variable right into `tracing_subscriber`, so we no longer need to implement this in out codebase :)
=> Revert "tracing: Disable colored log output on Heroku"

src/bin/crates-admin.rs
- Added debug assert test for the admin CLI.
=> Add debug assert to crates-admin cli

docs/CONTRIBUTING.md
1. Added language spec to code blocks to have better syntax support.
2. In Markdown, the angle brackets (<>) are used to automatically convert a URL into a clickable link. So my linter added it.
[rendered](https://github.com/hi-rustin/crates.io/blob/rustin-patch-code-block/docs/CONTRIBUTING.md)
=> Add language spec to code blocks

.github/workflows/ci.yml
This is a weird situation... we used to be part of the BrowserStack open-source program, but cancelled it back then because we were not using it. Then Percy got bought by BrowserStack, and when the free tier of Percy was exceeded we asked the Rust Foundation to pay for more credits. Which they did. And now BrowserStack (the "new" owner of Percy) wants to ramp up the cost by 4x. While we could apparently just go back to the BrowserStack open-source program, which is free and has unlimited Percy credits?!?
Anyway, I've applied us for the open-source program again and this PR is updating our `PERCY_TOKEN`. According to the docs the `PERCY_PROJECT` isn't needed anymore, but we'll see if that's true or not... :D
=> CI: Update `PERCY_TOKEN`

src/controllers/krate/publish.rs, src/models/krate.rs, src/tests/krate/publish/snapshots/all__krate__publish__features__empty_feature_name.snap
As promised in https://github.com/rust-lang/crates.io/pull/7500#pullrequestreview-1732333754, I have a few suggestions on how the feature validation code can be improved :)
=> models/krate: Improve feature validation

app/components/crate-header.hbs
Obviously I'm focusing on the important things today.
=> crate-header: correctly pluralise the number of crate versions

src/config/server.rs, src/controllers/version/downloads.rs, src/tests/routes/crates/downloads.rs, src/tests/routes/crates/versions/download.rs, src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__download__rejected_non_canonical_download.snap, src/tests/unhealthy_database.rs, src/tests/util/test_app.rs
see https://blog.rust-lang.org/2023/10/27/crates-io-non-canonical-downloads.html
This PR implements a feature flag that can be used to disable support for non-canonical downloads in our backend API. As the blog post mentions, next Monday we plan to disable support for them and roughly a month later we will remove the supporting code paths and the custom error message.
=> Disable non-canonical downloads if `REJECT_NON_CANONICAL_DOWNLOADS` env var is set

.github/workflows/ci.yml, frontend.Dockerfile, package.json
Reverts rust-lang/crates.io#7535
```
=====> Detected Framework: crates.io
-----> jq v1.7 already installed
-----> Parsing pnpm version from `package.json` file
-----> Installing pnpm v8.10.5
curl: (22) The requested URL returned error: 401
pnpm version '8.10.5' could not be found
!     Push rejected, failed to compile Multipack app.
!     Push failed
```
It's not clear exactly why v8.10.5 is failing on Heroku, but it looks like the version is currently not available for download 🤷
=> Revert "Update dependency pnpm to v8.10.5"

src/cloudfront.rs
Apparently the `Config` struct has a new **required** field and just panics when it is not set on the builder... 🙄
Related:
- #7553
- https://github.com/awslabs/aws-sdk-rust/blob/main/CHANGELOG.md#november-16th-2023
=> cloudfront: Fix AWS SDK panic

src/controllers/krate/publish.rs, src/models/krate.rs, src/tests/krate/publish/dependencies.rs, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__empty_dependency_name.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_name_contains_unicode_chars.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_name_starts_with_digit.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_rename.snap, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_too_long_dependency_name.snap
Split from https://github.com/rust-lang/crates.io/pull/7379/files
This PR only enhanced the error message for invalid dep names. Nothing changed for the validation rules.
| category                    | Cargo                                                                                                   | crates.io before change                                                                                      | crates.io after change                                                                                 |
| --------------------------- | ------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- | …
=> Better error message for invalid dep names

src/controllers/github/secret_scanning.rs, src/controllers/helpers/pagination.rs, src/controllers/krate/owners.rs, src/controllers/krate/publish.rs, src/controllers/token.rs, src/controllers/version/downloads.rs, src/controllers/version/metadata.rs, src/controllers/version/yank.rs, src/models/krate.rs, src/models/owner.rs, src/models/team.rs, src/models/version.rs, src/util/errors.rs
There is no need for us to accept `impl &ToString` if we can accept `impl ToString` directly. This allow us to make calling these functions a little more straight-forward :)
=> util/errors: Simplify error function arguments

src/typosquat/cache.rs, src/typosquat/checks.rs, src/typosquat/config.rs, src/typosquat/mod.rs
This extends our new typosquatting checks (see #7206) to detect an attack vector we've seen more recently where a bad actor tries to squat an existing, popular crate by adding or removing a common suffix (such as `-rs` or `-sys`).
The suffix list in the configuration has been taken _approximately_ from the most popular suffixes in the existing set of crates, with a small amount of human judgement involved on which ones are more likely to be abused based on recent incidents.
Most of this PR is actually tests by weight.
=> typosquat: add suffix checks

src/views.rs
The first two commits change our backend to also apply the `DOCUMENTATION_BLOCKLIST` to the `homepage` and `repository` fields. The third commit adds the `nebulanet.cc` domain to the list of blocked external domains.
This was triggered by a report about the `repository` field of https://crates.io/crates/ccl-fxhash leading to a spam page supposedly due to an expired domain registration.
=> Add `nebulanet.cc` to list of blocked external domains

src/controllers/krate/publish.rs, src/tests/krate/publish/snapshots/all__krate__publish__features__too_many_enabled_features.snap, src/tests/krate/publish/snapshots/all__krate__publish__features__too_many_enabled_features_with_custom_limit.snap, src/tests/krate/publish/snapshots/all__krate__publish__features__too_many_features.snap, src/tests/krate/publish/snapshots/all__krate__publish__features__too_many_features_with_custom_limit.snap
Most people contacting us about the `max_features` restriction apparently did not see or read the blog post yet that explains the introduction of the limit. Adding the URL to the blog post should give people more context before they send that email to help@crates.io.
=> Add blog post link to `max_features` error messages

src/external_urls.rs, src/lib.rs, src/views.rs
This isn't really directly related to the `views` module and can probably be reused in the publish endpoint too after some modifications.
=> Extract `external_urls` module

.buildpacks
see https://github.com/Turbo87/heroku-buildpack-crates-io/commit/57008548b11cecb39f28d2bb7cf3b104a301e751
This is a temporary workaround for https://github.com/pnpm/pnpm/issues/7336 and should fix our deployments again.
=> Heroku: Update crates.io buildpack

src/worker/swirl/background_job.rs, src/worker/swirl/runner.rs
Most types are already using the term `Context` and with this PR the struct fields and function arguments are also renamed to follow this convention.
=> worker/swirl Rename `environment` to `context`

Cargo.lock, Cargo.toml, src/bin/background-worker.rs, src/tests/util/test_app.rs, src/worker/environment.rs
Having six argument that you have to specify in the right order was becoming a bit ridiculous and makes it hard to extend this struct in the future. This PR takes advantage of the `derive_builder` crate, which automatically generates an `EnvironmentBuilder` struct for us, making `Environment` construction a lot more straight-forward.
=> worker/environment: Replace six-argument constructor with builder pattern

Cargo.lock, Cargo.toml, src/bin/background-worker.rs, src/tests/util/test_app.rs, src/worker/swirl/errors.rs, src/worker/swirl/runner.rs
Instead of calling `run_all_pending_jobs()` in a loop, which then fills up the `threadpool` to its maximum capacity, we now call `start()`, which starts up `num_workers` background worker threads and then `wait_for_shutdown()` can be used to wait for the worker threads to finish. In normal operation these thread should not finish on their own. In testing mode, when `shutdown_when_queue_empty()` has been used, the worker threads will shutdown once they can't find any pending jobs in the queue anymore.
This change also removes the `Event` enum and the related channel code, since the new implementation does not require communication between the workers and the runner anymore.
Rearchitecting the runner like this should make it a bit easier to replace our usage of threads with tokio tasks in …
=> Rearchitect `swirl::Runner` implementation

src/bin/background-worker.rs, src/cloudfront.rs, src/tests/util/test_app.rs, src/worker/jobs/dump_db.rs, src/worker/jobs/git.rs, src/worker/jobs/readmes.rs, src/worker/swirl/runner.rs
Do I know what I'm doing? Barely...
Does it work? Apparently!? 😅 
This PR essentially replaces the `std::thread::spawn()` call in the `start()` fn with `tokio::task::spawn_blocking()`. This means that all jobs are now executed within the context of a tokio runtime, which allows us to get rid of the per-job runtime creation that was happening in some of the jobs. This will hopefully also allow us to make the `run()` fn of the `BackgroundJob` trait async in the future.
=> worker/swirl/runner: Spawn worker threads on tokio runtime

src/worker/jobs/daily_db_maintenance.rs, src/worker/jobs/dump_db.rs, src/worker/jobs/git.rs, src/worker/jobs/readmes.rs, src/worker/jobs/typosquat.rs, src/worker/jobs/update_downloads.rs, src/worker/swirl/background_job.rs, src/worker/swirl/runner.rs
References are tricky when dealing with async boundaries... Since our jobs use `Context = Arc<Environment>` the cloning should be relatively cheap and make the async/await conversion a bit easier.
=> worker/swirl/background_job: Pass owned `Context` to the `run()` fn

src/app.rs, src/bin/server.rs, src/github.rs, src/tests/util/test_app.rs
Passing in a `GitHubClient` into `App::new()` instead of a raw `reqwest::Client` unlocked quite a bit of cleanup since the `Client` in test-mode wasn't actually used anywhere, thus making the whole `proxy` field unused too.
=> Simplify GitHub client assignment

src/worker/jobs/daily_db_maintenance.rs, src/worker/jobs/dump_db.rs, src/worker/jobs/git.rs, src/worker/jobs/readmes.rs, src/worker/jobs/typosquat.rs, src/worker/jobs/update_downloads.rs, src/worker/swirl/background_job.rs, src/worker/swirl/runner.rs
This PR makes all of our background worker jobs async functions. Most of them involve database operations though, so some usage of `spawn_blocking()` is still needed, but it should make it easier to convert more and more parts of our codebase to async/await in the future.
=> worker/swirl/background_job: Change `run()` fn to be async

src/app.rs, src/bin/server.rs, src/tests/util/test_app.rs
This removes the need to mutate the `App` in testing mode after it has been constructed and the corresponding duplicate initialization of the `email` field.
=> app: Change `new()` fn to accept `Emails` argument

README.md, crates_io_markdown/lib.rs, docs/ARCHITECTURE.md, docs/CONTRIBUTING.md, src/email.rs, src/util/errors/json.rs
This change makes our usage of the "crates.io" name consistent across the project by using it in lowercase form everywhere, also at the start of a sentence.
=> Adjust "crates.io" usage to lowercase

crates_io_worker/src/job_registry.rs, crates_io_worker/src/runner.rs
This makes the raw `HashMap` a little easier to work with and allows us to restrict access to the `runnable()` fn to the `job_registry` module.
=> worker: Extract 'JobRegistry` struct

app/components/version-list/row.module.css
=> VersionList::Row: Limit version number size

app/controllers/crate/versions.js
If we fail to parse a version string then the `semver` property will be `null`, leading us running `null.compare(...)` which does not exist. This change extends the sorting function to handle this edge case.
see https://crates.io/crates/cursed-trying-to-break-cargo/versions?sort=semver
=> controllers/crate/versions: Fix null error in `sortedVersions`

crates_io_worker/Cargo.toml, crates_io_worker/src/background_job.rs, crates_io_worker/src/job_registry.rs, crates_io_worker/src/util.rs, crates_io_worker/src/worker.rs
This PR converts more of our worker code to async/await by moving the `block_on()` call further to the outside. Each new layer inside is converted to async/await accordingly.
=> worker: Move `block_on()` call further outside

src/models/krate.rs, src/tests/krate/publish/features.rs
Fixes https://github.com/rust-lang/crates.io/issues/7632
=> models/krate: Fix unintentional `max_features` reset after publishing

crates_io_worker/src/background_job.rs, crates_io_worker/src/job_registry.rs, crates_io_worker/src/runner.rs, crates_io_worker/src/storage.rs, crates_io_worker/src/worker.rs, crates_io_worker/tests/runner.rs, src/bin/background-worker.rs, src/tests/util/test_app.rs, src/worker/jobs/git.rs
We are currently running a single queue with 5 workers in production. Some of our background jobs require exclusive access to the cloned git index repository, which is handled by a `Mutex`. This means that we can run into situations where one worker is working on the repository and the other four workers are waiting for the mutex, while they could instead work on other jobs that don't require repository access.
This PR adds a `QUEUE` field to the `BackgroundJob` trait, which allows us to define on which queue a job should run. These queues can be configured via `configure_queue()` and can have different numbers of workers.
This PR then makes use of the new `QUEUE` field and adds a `repository` queue for all three jobs that interact with the git index repository.
=> Add support for running multiple background worker queues

src/controllers/krate/publish.rs, src/models/krate.rs, src/models/token/scopes.rs, src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_name.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-2.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-3.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-4.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-5.snap, src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names.snap
Split from https://github.com/rust-lang/crates.io/pull/7379
The summary:
| category                    | Cargo                                                                                                   | crates.io before change                                                                                      | crates.io after change                                                                                 |
| --------------------------- | ------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| Crate name                  | 1. …
=> Add better error message for invalid crate names

src/tests/util.rs, src/tests/util/response.rs
This should make our migration to axum 0.7 and hyper 1.x a little easier since our version of `reqwest` is currently not compatible with hyper 1.x.
=> tests/util/response: Replace `reqwest::blocking::Response` with `hyper::Response`

crates_io_worker/src/job_registry.rs, crates_io_worker/src/runner.rs, crates_io_worker/src/util.rs, crates_io_worker/src/worker.rs, crates_io_worker/tests/runner.rs
This PR converts the main `Worker::run()` fn to async/await, and wraps most of the `run_next_job()` fn content in a `spawn_blocking()` call.
This should get us one step closer to using an async database connection pool.
=> worker/worker: Convert `run()` fns to async

src/fastly.rs, src/storage.rs
In the current situation `reqwest` reexports the header code from the `http` crate. However once we update `hyper` to 1.x we will have two copies of the `http` crate, with differing major versions. This leads to conflicts between the header code that `reqwest` expects and the `http` crate used by `crates_io`. By importing the header code from `reqwest` we can ensure that we use the correct `http` crate version that `reqwest` expects.
=> Fix `reqwest` imports

src/tests/server_binary.rs
There is no need for the `_SECONDS` suffix if we use `Duration` directly for the `const` :)
=> tests/server_binary: Convert `u64` constant to `Duration`

src/util/bytes_request.rs
Looks like the two layers above it aren't actually necessary 🤷‍♂️
=> util/bytes_request: Simplify `LengthLimitError` downcast

src/tests/util/response.rs
The `assert_that!()` call doesn't actually need a dedicated clone of the `Bytes` instance.
=> tests/util/response: Avoid unnecessary `.clone()` call

src/middleware/log_request.rs, src/tests/server.rs
The middleware that is responsible for rejecting requests without a `User-Agent` header runs after the middleware that logs requests. The request logging middleware however was expecting a `TypedHeader<UserAgent>`, which meant that requests without such a header were unconditionally rejected, even for download requests.
Our test suite for this functionality was setting an empty header, which unfortunately behaved differently than not having such a header at all.
Related:
- 44aeb47b56037890f49c05464a973b8447f7c0ff implemented the corresponding tests (April 2019)
- 88bd12977523bf68f62d622447c2b9cbbc2f8987 changed the logging middleware to rely on `TypedHeader<UserAgent>` (Dec 2022)
=> Fix `User-Agent` header requirement error responses

src/tests/server.rs, src/tests/util.rs
This makes the function a bit more generic and reduces our reliance on `Bytes`. Instead of using `.body(Bytes::new())` we can now use `.body("")` which shrinks the code a bit. `.body(())` is unfortunately not possible yet (see https://github.com/tokio-rs/axum/pull/2411).
=> tests/util: Accept all `Into<Body>` implementations in `run()` fn

Cargo.toml
Surprisingly, clippy does not warn about `todo!()` by default. This PR changes that to avoid us unintentionally pushing work-in-progress code to the `main` branch.
=> clippy: Warn about `todo!()` usage

src/middleware.rs, src/middleware/errors.rs, src/tests/routes/crates/versions/download.rs, src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__download__rejected_non_canonical_download.snap, src/tests/routes/session/authorize.rs, src/tests/server.rs, src/tests/snapshots/all__server__block_traffic_via_arbitrary_header_and_value.snap, src/tests/snapshots/all__server__block_traffic_via_ip.snap
to quote from the code comment:
> The built-in extractors in `axum` return plain text errors, but our API contract promises JSON errors. This middleware converts such plain text errors into corresponding JSON errors, allowing us to use the `axum` extractors without having to care about the error responses.
=> Ensure that API endpoints return JSON errors

src/middleware.rs, src/middleware/cargo_compat.rs, src/tests/krate/publish/auth.rs, src/tests/owners.rs, src/tests/pagination.rs, src/tests/read_only_mode.rs, src/tests/routes/crates/list.rs, src/tests/routes/crates/versions/yank_unyank.rs, src/tests/server.rs, src/tests/snapshots/all__read_only_mode__cannot_hit_endpoint_which_writes_db_in_read_only_mode.snap, src/tests/snapshots/all__server__user_agent_is_required-2.snap, src/tests/snapshots/all__server__user_agent_is_required.snap, src/tests/util/response.rs
cargo before 1.34.0 only showed raw JSON errors when a non-200 status code was returned. In crates.io we are using the `cargo_err()` fn in many places to ensure that the error that is returned uses the `200 OK` status code. As can be seen in the diff, we haven't been consistent in this though.
This PR introduces a middleware that overrides the HTTP status code to `200 OK` for all API endpoints that are relevant for cargo (see https://doc.rust-lang.org/cargo/reference/registry-web-api.html).
This will allow us to remove `cargo_err()` and use proper status codes internally. This is particularly useful for helper functions that are used by both cargo- and non-cargo endpoints. It also makes it easier to phase out the `200 OK` requirement since the middleware could easily be disabled by a …
=> Ensure `200 OK` status codes for cargo endpoints

src/util/errors/json.rs
This has confused me too many times, so now it will be fixed :D
Having a short list of all the structs is surely nice, but if it then becomes complicated to find their impl blocks it's just not worth it, especially if not all the structs participate in this.
=> util/errors/json: Move structs closer to their impl blocks

crates_io_worker/Cargo.toml
This fixes the following issue:
```
$ cargo test --package crates_io_worker
error[E0432]: unresolved import `tokio::time`
--> crates_io_worker/src/worker.rs:13:12
|
13 | use tokio::time::sleep;
|            ^^^^ could not find `time` in `tokio`
```
=> worker: Enable missing `tokio` feature

crates_io_worker/tests/runner.rs
The `Runner` should not unnecessarily share its connections with anything on the outside, so instead of using the `Runner::connection()` fn this PR replaces it with `TestDatabase::connect()`, which uses the connection pool inside the `TestDatabase` struct instead.
=> worker/tests: Use `TestDatabase::connect()` for DB interactions

src/auth.rs
This seems slightly easier on the eyes compared to the let-if-let-else construct before.
=> auth: Simplify `ensure_not_locked()` fn

src/github.rs
`Bearer` is the official standard scheme (see https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml), while `token` is a GitHub-specific variant. According to https://docs.github.com/de/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28#about-authentication both are equivalent though.
This commit changes the authorization scheme to `Bearer` to make it easier to interact with regular HTTP tooling that does not support `token`.
=> github: Use `Bearer` authorization scheme instead of `token`

src/github.rs, src/models/team.rs, src/tests/util/github.rs, src/util/errors.rs
This reduces the need for `e.is::<NotFound>()` checks and makes the code a little less coupled to our HTTP layer and its error responses.
=> github: Extract `GitHubError` enum

Cargo.lock, Cargo.toml, crates_io_github/Cargo.toml, crates_io_github/src/lib.rs, src/app.rs, src/bin/server.rs, src/controllers/github/secret_scanning.rs, src/controllers/user/session.rs, src/github.rs, src/lib.rs, src/models/team.rs, src/tests/util/github.rs, src/util/errors.rs, src/views.rs
This PR extracts our top-level `github` module into a dedicated workspace package. This makes it easier to enforce the decoupling between the GitHub client code and our HTTP API layer.
=> Extract `crates_io_github` package

src/controllers/user/me.rs, src/models/krate.rs, src/models/owner.rs
When `diesel` returns an error it doesn't always mean that the resource couldn't be found, it could also be any other kind of error. A couple of places in the codebase were unconditionally transforming `diesel` errors into "could not find ..." errors though. This PR fixes the issue by using `.optional()?.ok_or_else(|| ...)` instead of `.map_err(|_| ...)`.
=> Fix error handling for optional SQL results

src/controllers/github/secret_scanning.rs
This PR converts `static PUBLIC_KEY_CACHE_LIFETIME_SECONDS: i64` to `const PUBLIC_KEY_CACHE_LIFETIME: Duration` since most of the work can already be performed at compile time.
=> controllers/github/secret_scanning: Simplify `PUBLIC_KEY_CACHE_LIFETIME` usage

src/config.rs, src/config/server.rs, src/email.rs
Instead of calling `dotenvy::var("DOMAIN_NAME")` over and over we can read the value from the server config struct and save it inside the `Emails` instance 🎉
=> email: Add `domain` field

src/email.rs
This is what we use in production so we may as well use it in tests too
=> email: Change default "From" address to "noreply@crates.io"

src/email.rs
This allows us to fail early if the value can't be parsed into a `Mailbox`
=> email: Add `from` field to `Emails` struct

src/email.rs, src/tests/owners.rs, src/util/errors.rs, src/worker/jobs/typosquat.rs
Previously we were creating these `Transport` instances per email that we send, but that seems a bit unnecessary. Creating them once on server startup allows us to fail early for configuration issues.
Our in-memory implementation was also using a bit of custom code, when instead we could use the official `StubTransport` implementation, which achieves the same thing.
=> email: Use `Transport` implementations in all backend variants

src/controllers/github/secret_scanning.rs
There is no need to use `BoxedAppError` if the only error returned from a function is a `diesel` error.
=> controllers/github/secret_scanning: Replace `Result<_, BoxedAppError>` with `QueryResult<_>`

src/models/crate_owner_invitation.rs, src/models/krate.rs, src/models/token.rs
`AppResult` is something from the HTTP/API layer and the `models` modules shouldn't know anything about that. This PR reduces the coupling a little bit by replacing `AppResult` with `QueryResult` where possible.
=> models: Use `QueryResult` instead of `AppResult` where possible

src/bin/server.rs
We're only logging the error, but not transforming it into an HTTP response, so there is no need for using the custom `AppResult` type.
=> bin/server: Use `anyhow` instead of `AppResult`

src/config/server.rs, src/controllers/version/downloads.rs, src/tests/routes/crates/downloads.rs, src/tests/routes/crates/versions/download.rs, src/tests/server_binary.rs, src/tests/unhealthy_database.rs, src/tests/util/test_app.rs
We've had this enabled for about a month now so its time to remove the feature flag.
=> Remove `reject_non_canonical_downloads` feature flag

src/controllers/version/downloads.rs, src/tests/routes/crates/versions/download.rs
see https://blog.rust-lang.org/2023/10/27/crates-io-non-canonical-downloads.html
=> controllers/version/downloads: Return regular 404 error for non-canonical downloads

src/controllers/github/secret_scanning.rs, src/controllers/user/me.rs, src/email.rs, src/models/krate.rs, src/models/user.rs, src/worker/jobs/typosquat.rs
Previously we implemented new email variants by adding another method to the `Emails` struct, which then internally called `self.send(...)`.
This PR explores a different implementation where each email variant is represented by its own struct, holding the values that it needs to generate the email body. Each of the structs implements a new `Email` trait, which has a `const SUBJECT` and `fn body()` on it.
This allows us to move the email generation code closer to where the emails are sent and should scale better with an increasing number of email variants. It also makes the email sending code in the `email` module a bit more generic and less coupled to the application logic.
=> Extract `Email` trait

src/models/email.rs
This does not appear to be used for anything... 🤷‍♂️
=> models/email: Remove unused `AsChangeset` impl from `Email` struct

src/models/crate_owner_invitation.rs
These appear to be unused and prevent us from using `SecretString` inside the struct
=> models/crate_owner_invitation: Remove unused `Eq` impls from `CrateOwnerInvitation` struct

src/controllers/user/me.rs, src/models/crate_owner_invitation.rs, src/models/email.rs, src/models/krate.rs, src/models/user.rs
I wanted to add `Debug` impls for all of the structs that implement the new `Email` trait, but then I saw that some of them contain sensitive information. This PR replaces those fields with `secrecy::SecretString` types to ensure that the `Debug` representation is not unintentionally leaking sensitive information.
=> Use `SecretString` for `token` fields

src/email.rs, src/util/errors.rs
Unfortunately `lettre` uses different error types for all the transports, but that doesn't mean we need to follow that example. This PR merges the three variants into one using `anyhow::Error`, since we don't really care about the specifics of the errors anyway.
The tracing logs are temporarily removed but will be restored in a follow-up PR :)
=> email: Merge `TransportError` variants

src/controllers/version/downloads.rs, src/metrics/instance.rs
At this point non-canonical downloads are responded to with a 404 error, so we might as well rely on the query failing to accomplish that. We unfortunately still need the query for download counting for now, but that will hopefully be resolved soon too.
=> controllers/version/downloads: Remove canonical crate name from query

src/controllers/version/downloads.rs
This also means we don't need to use `Handle::current().block_on()` here anymore :)
=> controllers/version/downloads: Move `app.version_id_cacher.insert()` call outside `spawn_blocking()`

src/util/errors.rs
These two don't appear to be needed anymore since they have been replaced by explicit error handling.
=> util/errors: Remove unused `From<...> for BoxedAppError` impls

src/config/server.rs, src/middleware.rs, src/middleware/cargo_compat.rs, src/tests/krate/publish/auth.rs, src/tests/owners.rs, src/tests/pagination.rs, src/tests/read_only_mode.rs, src/tests/routes/crates/list.rs, src/tests/routes/crates/versions/yank_unyank.rs, src/tests/server.rs, src/tests/util/response.rs, src/tests/util/test_app.rs
In https://github.com/rust-lang/crates.io/pull/7715 we implemented a middleware that ensured `200 OK` response status codes for all API endpoints that are relevant for cargo (see https://doc.rust-lang.org/cargo/reference/registry-web-api.html).
The PR also mentioned:
> This will allow us to remove cargo_err() and use proper status codes internally. This is particularly useful for helper functions that are used by both cargo- and non-cargo endpoints. It also makes it easier to phase out the 200 OK requirement since the middleware could easily be disabled by a feature flag in the future.
This PR implements such a feature flag, based on the value of a `CARGO_COMPAT_STATUS_CODES` environment variable. If that env var is set to `"n"` it will disable this part of the middleware and return the …
=> Implement cargo compatibility status code enforcement feature flag

app/index.html
Ref-: https://github.com/rust-lang/crates.io/pull/7789
Making the Open Graph image a full path URL (`/assets/og-image.png` to `https://crates.io/assets/og-image.png`). This change ensures that the Open Graph image works as expected, as Open Graph only supports absolute file paths.
=> Update Open Graph Image URL to Absolute Path for Compatibility

src/controllers/metrics.rs, src/middleware/block_traffic.rs, src/models/crate_owner_invitation.rs, src/util/errors.rs, src/util/errors/json.rs
Instead of having a dedicated `struct` per HTTP status code (and then some more), we can use a single struct and save the status code inside the struct, next to the error message. This allows us to throw away a significant chunk of verbose code while the API behaves exactly the same as before. Admittedly this removes the ability for `e.is::<NotFound>()` checks, but we were not and probably shouldn't be using those anyway.
Note that a few structs were not converted to using this "generic" struct yet:
- `InsecurelyGeneratedTokenRevoked` because it is used in an `e.is::<_>()` check
- `ReadOnlyMode` because it is used in an `e.is::<_>()` check
- `TooManyRequests` because it is setting a custom header, which `CustomApiError` does not currently allow
=> util/errors: Extract `CustomApiError` struct

Cargo.lock, Cargo.toml, crates_io_env_vars/Cargo.toml, crates_io_github/Cargo.toml, crates_io_index/Cargo.toml, crates_io_smoke_test/Cargo.toml, crates_io_tarball/Cargo.toml, crates_io_worker/Cargo.toml
This reverts commit 1b9fba41e7b1070214bbfc3f64d28ca42db24549.
Related:
- https://github.com/dtolnay/thiserror/issues/270
- https://github.com/rust-lang/crates.io/pull/7819
=> Revert "Update Rust crate anyhow to v1.0.77"

Cargo.lock, crates_io_env_vars/Cargo.toml, crates_io_env_vars/src/lib.rs
Previously this code wasn't really tested properly. This PR adds a basic test suite for the four helper functions defined in the `crates_io_env_vars` package.
=> env_vars: Add basic test suite

src/typosquat/database.rs, src/typosquat/test_util.rs, src/worker/jobs/typosquat.rs
Using `PgConnection` prevents us from using a pooled connection (i.e. what `TestDatabase::connect()` returns). An alternative would be to store the mutable reference to the connection in the `Faker` struct, but then we have to deal with explicit lifetimes, and the `borrow_conn()` and `into_conn()` fns would still cause a bit of weirdness.
This PR adjusts the `Faker` API to roughly match the rest of the codebase by accepting an explicit `&mut PgConnection` argument everywhere instead.
=> typosquat/test_util: Remove `conn` field from `Faker` struct

src/controllers/user/session.rs, src/downloads_counter.rs, src/models/category.rs, src/models/keyword.rs, src/rate_limiter.rs, src/sql.rs, src/test_util.rs, src/tests/categories.rs, src/tests/util/test_app.rs, src/typosquat/database.rs, src/typosquat/test_util.rs, src/worker/jobs/dump_db/gen_scripts.rs, src/worker/jobs/typosquat.rs, src/worker/jobs/update_downloads.rs
`TEST_DATABASE_URL` is only supposed to be used as a database name prefix at this point, but not as a real, existing database. This PR adjusts the remaining usages to use the `TestDatabase` struct instead.
This PR is based on https://github.com/rust-lang/crates.io/pull/7827, since `Faker` needs to be made compatible with the pooled database connection that `TestDatabase::connect()` returns.
=> Replace remaining `TEST_DATABASE_URL` usage with `TestDatabase`

src/auth.rs, src/controllers/krate/publish.rs, src/controllers/user/session.rs, src/controllers/util.rs, src/util/errors.rs, src/util/errors/json.rs
Chained errors were used in our codebase to print a `cause` field in the log output. `internal(error_message).chain(forbidden())` for example would print `cause=<error_message>` and use `forbidden()` as the HTTP response.
Unfortunately our `AppError` struct is incompatible with `std::error::Error` and its `source()` fn though, which makes our error chaining less useful.
This PR removes/replaces our custom error chaining to make it easier in the future to build one based on `std::error::Error` instead.
=> Remove `AppError::chain()` method

src/controllers.rs
This should hopefully fix the failing CI jobs. I suppose this happened due to a merge "conflict" between some of the latest PRs 😅
=> controllers: Remove unused import

crates_io_worker/src/background_job.rs, crates_io_worker/src/job_registry.rs, crates_io_worker/tests/runner.rs, src/worker/jobs/daily_db_maintenance.rs, src/worker/jobs/dump_db.rs, src/worker/jobs/git.rs, src/worker/jobs/readmes.rs, src/worker/jobs/typosquat.rs, src/worker/jobs/update_downloads.rs
Follow up https://github.com/rust-lang/crates.io/pull/7601
Because the async trait is already stabled in the std library, I think we probably can switch to using it. Then probably we can get rid of one depends.
=> Use `async fn` and return-position `impl Trait` from std library for background jobs

Cargo.lock, Cargo.toml, src/bin/server.rs
Now that https://github.com/tokio-rs/axum/pull/2398 is released we can simplify our server binary startup code quite a bit :)
=> bin/server: Use `axum::serve(...).with_graceful_shutdown(...)`

src/models/user.rs, src/tests/all.rs, src/tests/owners.rs
No need for a `Cow` if we use `&str` everywhere 🤷‍♂️
=> models/user: Simplify `NewUser::gh_access_token` type

src/tests/routes/users/read.rs, src/views.rs
We always assign a value to this field, so there is no need for us to use `Option` here.
=> Simplify `EncodablePublicUser::url` field

src/controllers/version/downloads.rs, src/controllers/version/metadata.rs, src/controllers/version/yank.rs, src/models/krate.rs, src/tests/routes/crates/versions/dependencies.rs, src/util/errors.rs
We don't need to use `cargo_err()` (aka. "200 OK") responses in these error cases anymore since the cargo compat middleware will ensure that we reply with a compatible status code for cargo-relevant endpoints.
This PR extracts a new `version_not_found()` fn and then adjusts its implementation to respond with "404 Not Found" instead.
=> Adjust "version invalid / not found" errors to reply with "404 Not Found"

src/tests/routes/crates/downloads.rs, src/tests/routes/crates/snapshots/all__routes__crates__downloads__downloads.snap
... since this route wasn't really tested before 🙈
=> tests/crates/downloads: Add basic `/:crate/:version/downloads` test

src/tests/krate/following.rs
Some branches of our route handlers were not tested at all. This PR slightly improves the situation by implementing tests for the unauthenticated case and the "unknown crate" case. It also improves the existing tests with a couple of comments and additional assertions.
=> Improve crate following test suite

src/tests/routes/crates/downloads.rs, src/tests/routes/crates/snapshots/all__routes__crates__downloads__crate_downloads.snap, src/tests/routes/crates/snapshots/all__routes__crates__downloads__version_downloads.snap
The `/api/v1/crates/:crate_id/downloads` was previously only implicitly tested. This PR adds an explicit test function for it.
=> tests/routes/crates/downloads: Split `test_downloads()` into `test_crate/version_downloads()`

src/controllers/krate/downloads.rs
`version_downloads::date` is not unique, which apparently makes our test suite flaky. This change fixes it by adding `version_downloads::version_id` as a secondary sort key. The combination of `date` and `version_id` should be unique, so the sort order should be stable now.
=> controllers/krate/downloads: Use stable sort order

src/tests/routes/crates/reverse_dependencies.rs, src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__prerelease_versions_not_included_in_reverse_dependencies.snap, src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies-2.snap, src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies.snap, src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_includes_published_by_user_when_present.snap, src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_query_supports_u64_version_number_parts.snap, src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_when_old_version_depended_but_new_doesnt.snap, src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_when_old_version_doesnt_depend_but_new_does.snap, src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__yanked_versions_not_included_in_reverse_dependencies-2.snap, src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__yanked_versions_not_included_in_reverse_dependencies.snap
This PR …
- adds a dedicated "unknown crate" test case
- converts the existing tests to use snapshot testing to assert on as much of the API as possible
=> Improve `/api/v1/crates/:crate_id/reverse_dependencies` tests

src/controllers/krate/downloads.rs, src/controllers/krate/follow.rs, src/controllers/krate/metadata.rs, src/controllers/krate/owners.rs, src/controllers/version.rs, src/tests/krate/following.rs, src/tests/owners.rs, src/tests/routes/crates/downloads.rs, src/tests/routes/crates/read.rs, src/tests/routes/crates/reverse_dependencies.rs, src/tests/routes/crates/versions/dependencies.rs, src/tests/routes/crates/versions/list.rs, src/util/errors.rs
This PR adds a `crate_not_found()` function, similar to the existing `version_not_found()` function. This function will return a "404 Not Found" error with a proper "crate `...` does not exist" message. Previously, we were relying on `diesel::result::Error::NotFound` errors being automatically converted to generic 404 errors, but with this change we get actionable error messages.
Related:
- #7851
=> Add `crate_not_found()` fn
