rust-lang/crates.io

src/tasks.rs

see https://www.lpalmieri.com/posts/password-authentication-in-rust/#3-4-1-tracing-context-is-thread-local

Fix `tracing` instrumentation across `spawn_blocking()` calls

---

crates_io_worker/src/util.rs

This is similar to #7878, but for the fn copy in the `crates_io_worker` package. Clearly it was a great idea to have multiple copies of this function... 😅

worker: Fix `tracing` instrumentation across `spawn_blocking()` calls

---

src/controllers/krate/publish.rs
src/tests/krate/publish/max_size.rs
src/util/bytes_request.rs

This PR changes our `BytesRequest` implementation to respond with a "413 Payload too large" status code if the maximum request body size is exceeded. It also adjusts our publish endpoint to return the same status code if the per-crate size limit is exceeded.
Related:
- https://github.com/rust-lang/crates.io/issues/7881

Respond with "413 Payload too large" when max upload size is exceeded

---

src/models/krate_reverse_dependencies.sql

This pr optimizes the query by pinpointing relevant crates and efficiently retrieving dependencies.
<details>
<summary>Strategies</summary>
1. Identifying relevant crates:
```sql
SELECT
crates.downloads AS crate_downloads,
crates.name AS crate_name,
versions.id AS version_id
FROM
-- We only want the crates whose *max* version is dependent, so we join on a
-- subselect that includes the versions with their ordinal position
(
SELECT DISTINCT ON (crate_id)
crate_id, semver_no_prerelease, id
FROM versions
WHERE NOT yanked
ORDER BY
crate_id,
semver_no_prerelease DESC NULLS LAST,
id DESC
) versions
INNER JOIN crates
ON crates.id = versions.crate_id
WHERE versions.id IN (SELECT version_id FROM dependencies WHERE crate_id = $1)
```
The uniqueness of crates eliminates the need for deduplication. …

Further speed-up reverse depdencies query

---

src/controllers/krate/publish.rs
src/tests/routes/crates/new.rs

Related:
- https://github.com/rust-lang/crates.io/issues/7881

controllers/krate/publish: Respond with "429 Too Many Requests" when daily version limit is reached

---

src/email.rs

`FileTransport` implements `Clone` now, so the `Arc` isn't needed anymore.
Related:
- https://github.com/lettre/lettre/pull/924

email: Remove obsolete `Arc` around `FileTransport`

---

src/tests/util.rs

The `axum::Json` extractor requires this header to be present and rejects requests that don't have it. This change ensures we can move our code over from custom JSON parsing to the `axum` extractor eventually.

tests/util: Add `Content-Type: application/json` request headers

---

src/tests/worker/snapshots/all__worker__sync_admins__sync_admins_job.snap
src/tests/worker/sync_admins.rs
src/worker/jobs/sync_admins.rs

Previously we were sending notification emails even if the team repo user doesn't have a (staging.)crates.io account. This changes the implementation to use `.returning(users::gh_id)` for the queries and only send notification emails if something in the database actually changed.
Sorry for the rather large diff 🙈

worker/jobs/sync_admins: Send notification emails only for existing accounts

---

src/controllers/version/yank.rs

> Admin Turbo87 is yanking crate crossbeam
The current logging is a bit misleading since users can only yank versions, but not complete crates. This PR fixes the issue.
Also, don't worry, the log line came from the staging environment. I didn't yank `crossbeam` on production 😉

controllers/version/yank: Include version number in admin action logs

---

app/routes/crate.js
app/routes/team.js
app/routes/user.js

https://github.com/rust-lang/crates.io/pull/7873 and https://github.com/rust-lang/crates.io/pull/7851 changed the error messages of 404 errors, but forgot to adjust our frontend code, which relied on these specific error messages to display a more useful error to the users. This PR fixes the issue by relying on the HTTP status code now, instead of checking the error message string.

Use `instanceof NotFoundError` for 404 checks

---

src/controllers/krate/metadata.rs
src/router.rs
src/tests/routes/crates/read.rs
src/tests/routes/crates/snapshots/all__routes__crates__read__new_name.snap

Since `PUT /api/v1/crates/new` is used for publishing new crates/versions, `GET /api/v1/crates/new` was not being handled by the `GET /api/v1/crates/:crate_name` handler and returned "405 Method Not Allowed". This change special cases `GET /api/v1/crates/new` requests and forwards them to the `GET /api/v1/crates/:crate_name` request handler function.
Resolves https://github.com/rust-lang/crates.io/issues/7899

Fix `GET /api/v1/crates/new` requests

---

src/typosquat/cache.rs
src/typosquat/checks.rs
src/typosquat/config.rs

In #7571, we added checks for crate names that added or removed suffixes from popular crates. This has turned out to be a useful check! (Spoiler alert for the blog post I'm publishing next week.)
@Turbo87 pointed out that this can also apply to prefixes, especially `cargo-`. This generalises the suffix check to also check prefixes, and adjusts the typomania configuration to add `cargo` to the list of interesting affixes. For now, the same set of affixes will be used for both, but depending on what we see, a future tweak would be to separate the prefix and suffix lists. Let's see how that pans out.
In terms of implementation, I briefly toyed with making this generic over the prefix/suffix combination to remove the copy/paste code, then was reminded by rust-analyzer that …

typosquat: check for prefixes being manipulated like suffixes

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

The test suite is setting this up automatically. We don't need to do this manually anymore.
Note that I've changed `TEST_DATABASE_URL` to use the default `postgres` database, since our `crates_io_test_db` code needs to initially connect to some database to create the new test template database.

CI: Remove obsolete `diesel database setup` call

---

src/controllers/krate/owners.rs
src/tests/owners.rs

This PR first adds a couple of tests for the `PUT/DELETE /crates/:crate_id/owners` endpoints. Afterwards it performs a few refactorings on the endpoint code to simplify the JSON request payload parsing code, without changing the behavior of the system.
Best reviewed commit-by-commit 😉

controllers/krate/owners: Simplify request body parsing

---

codecov.yml

We're still gathering information on how useful the coverage tracking actually is, so let's not fail CI yet for potentially flaky numbers.

codecov: Use `informational` mode for now

---

codecov.yml

codecov claims to "use the default branch from Git for your repository as the primary source", but it doesn't appear to do so in practice...

codecov: Set default branch to `main`

---

src/controllers/helpers/pagination.rs
src/controllers/krate/search.rs
src/tests/routes/crates/list.rs

This pr improve the performance by utilizing a count subquery for total retrieval.
P.S. make a separate query to fetch total should also outperforms window functions in this context.

Improve crates endpoint performance

---

src/controllers.rs
src/controllers/helpers/pagination.rs
src/controllers/krate/owners.rs
src/tests/owners.rs

This will allow us to eventually get rid of our custom `BytesRequest` extractor and it also gives users more helpful error messages.

controllers/krate/owners: Use `Json` extractor to parse request body

---

.npmrc

This PR uses pnpm's [shell-emulator](https://pnpm.io/cli/run#shell-emulator) to execute scripts, so that syntax like `PROXY_BACKEND=https://crates.io` can run on Windows.
Resolves #7360

Make frontend build scripts work on Windows

---

src/controllers.rs
src/controllers/version/yank.rs
src/tests/routes/crates/versions/yank_unyank.rs

controllers/version/yank: Use "403 Forbidden" for errors

---

src/util/errors.rs

I guess it's debatable which status code exactly we should use here, but this should definitely not use "200 OK" 😅

util/errors: Use "403 Forbidden" for GitHub permission errors

---

src/controllers.rs
src/controllers/krate/owners.rs
src/models/owner.rs
src/models/team.rs
src/tests/owners.rs
src/tests/routes/crates/owners/add.rs
src/tests/routes/crates/owners/remove.rs
src/tests/team.rs

Adjust error status codes for ownership change endpoints

---

.env.sample

The HTTP recorder in our test suite is no longer a thing, so these environment variables are not used anymore.

env: Remove obsolete `TEST` environment variables

---

src/team_repo.rs
src/tests/worker/sync_admins.rs
src/worker/jobs/sync_admins.rs

Related:
- https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/team.20repo.20integration
- https://github.com/rust-lang/team/pull/1197
- https://github.com/rust-lang/team/pull/1290
- https://team-api.infra.rust-lang.org/v1/permissions/crates_io_admin.json

team_repo: Query permission instead of team

---

src/controllers/helpers/pagination.rs
src/controllers/krate/search.rs
src/tests/routes/crates/list.rs

This PR re-introduce #7941 and resolves #8052 by reverting the use of the `to_tsquery_with_search_config` for `TsQuery` part back to the original code.

Re-introducing improve crates endpoint performance (#7941)

---

src/worker/jobs/downloads/queue/job.rs

Previously, if enqueuing the job failed, the message would have been deleted already and the log file would never be processed. With this new implementation if enqueuing the job fails, the message will not get deleted from the queue. The downside of this is that if deletion fails for some reason, we might enqueue the job multiple times. This could already happen though if the code is running concurrently and we will need to introduce a deduplication mechanism anyway.

worker/jobs/downloads/queue: Delete messages *after* processing them

---

codecov.yml

This is similar to #7956, but for the `patch` commit status. The [documentation](https://docs.codecov.com/docs/commit-status#patch-status) is unclear whether this is actually supported, but some other projects on GitHub appear to be using it, so we might as well try 😅

codecov: Use `informational: true` for `patch` status too

---

src/worker/jobs/downloads/queue/job.rs

The `jobs_from_message()` can return an empty `Vec` if all of the records are skipped, e.g. if the paths are ignored. In that case we shouldn't call the `spawn_blocking()` fn to avoid the unnecessary thread "creation". In addition to that the `enqueue_jobs()` fn inside would also acquire a database connection to then use it to enqueue zero new background jobs, which is even more wasteful.

worker/jobs/downloads/queue: Skip `spawn_blocking()` call if there are no jobs to enqueue

---

src/sqs.rs
src/worker/jobs/downloads/queue/job.rs

Instead of passing the `message_id` reference everywhere we can refactor the code a bit to add the message ID to a `tracing` span, which automatically adds it to all log messages within the scope of the span.

worker/jobs/downloads/queue: Improve `message_id` logging

---

crates_io_cdn_logs/examples/count_downloads.rs
crates_io_cdn_logs/src/lib.rs
src/worker/jobs/downloads/process_log.rs

... instead of manually timing the execution time
Admittedly, we don't see the parse time in the logs anymore like this, but we have the performance instrumentation data for background jobs on Sentry, so we still get the same information that way.

cdn_logs: Instrument `count_downloads()` fn

---

src/worker/jobs/downloads/process_log.rs

`index.staging.crates.io` is usually filtered out... :D

worker/jobs/downloads/process_log: Use realistic path for tests

---

src/worker/jobs/downloads/process_log.rs

This removes the need for the explicit `path` logging and gives us better insights on the performance tracing on Sentry.

worker/jobs/downloads/process_log: Instrument `run()` fn

---

src/config/server.rs
src/controllers/version/downloads.rs
src/tests/routes/crates/downloads.rs
src/tests/util/test_app.rs
src/worker/jobs/downloads/process_log.rs

This PR resolves the `TODO` comment in the `ProcessCdnLog` background job by implementing the database writing part of the job.
The writing behavior is enabled by a new `CDN_LOG_COUNTING_ENABLED` feature flag. If this flag is set, regular download counting on the download endpoint is disabled and the writing behavior of background job is enabled.
Writing the downloads to the database is a three step process. First, a new temporary database table will be created. Then we insert the content of the `DownloadMap` into this temporary table. Finally, we use the temporary table to insert data into the `version_downloads` table. This multi-step process is needed because we only have the name and version of the downloaded crate, but not the corresponding `version_id` and looking them up one-by-one …

Implement writing CDN log counted downloads to the database

---

src/bin/background-worker.rs
src/worker/jobs/downloads/process_log.rs

Running multiple instances of `save_to_version_downloads()` in parallel appears to be causing issues and job retries. This change moves the corresponding background job to a dedicated worker queue with only a single worker. This should prevent these jobs from running in parallel, similar to how we don't run any jobs in parallel that touch the git index repository.

Move `process_cdn_log` background job to a dedicated worker queue

---

crates_io_worker/src/worker.rs

[`anyhow` by default only returns the top-most error](https://github.com/dtolnay/anyhow/issues/111) when formatted via `Display`. The alternate formatting (`:#`) instructs it to return the full error chain instead. Unfortunately [`tracing` does not support alternate formatting yet](https://github.com/tokio-rs/tracing/issues/1311), so we have to call `format!()` manually.

worker: Improve job failure error logging

---

app/styles/index.module.css
app/templates/index.hbs
src/config/server.rs
src/controllers/krate/metadata.rs
src/tests/util/test_app.rs

This adds support for a new `DISABLE_SUMMARY` environment variable that, if set and non-empty, will cause `/api/v1/summary` to return 503. The frontend has also been updated to handle this by displaying a less dramatic message than the normal message displayed when the summary request fails.
This should probably be straight up reverted after the current incident is complete. Keying on the 503 is pretty nasty.

Allow `/api/v1/summary` to be disabled from the environment

---

src/config/server.rs
src/tests/util/test_app.rs
src/worker/jobs/downloads/update_metadata.rs

The previous implementation to update the `versions` and `crates` table was quite slow and creating a lot of bloat in the database, since it updated the `crates` and `metadata` tables for every single version that was downloaded.
This commit adds a second implementation, guarded by the `BATCH_UPDATE_DOWNLOADS` feature flag, which updates the tables in batches with a static query that does not need to transfer data back and forth between the background worker and the database.
For more context, see https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/error.20in.20crates.2Eio.20summary.

worker/jobs/downloads/update_metadata: Implement optional batch processing

---

src/controllers/version/downloads.rs

Previously, we were just not calling `downloads_counter.increment()` if the feature flag is enabled. This commit changes the code to not perform the `version_id` database query, not get a database connection from the pool, and not get a blocking thread from tokio via `spawn_blocking()`. This should speed up the download endpoint, and make it resilient against database issues.
Best reviewed in ignore-whitespace mode 😉

downloads: Avoid `spawn_blocking()` and database query if `cdn_log_counting_enabled` is set

---

migrations/2024-02-12-120203_remove_unused_index/metadata.toml
migrations/2024-02-12-120203_remove_unused_index/up.sql

The `CONCURRENTLY` allows us to still use the associated table while the index is being dropped, and the `IF EXISTS` ensures that the migration succeeds even if the index does not exist. This allows us to manually drop the index before the migrations run, instead of dropping it as part of a migration which would block the server startup.

database: Use `CONCURRENTLY IF EXISTS` to drop the `index_follows_user_id` index

---

src/worker/jobs/downloads/update_metadata.rs

We've seen a couple of deadlock errors in the logs originating from the query in the `batch_update()` function. It looks like in some cases when a `process_cdn_log` background job is running its `UPDATE` query leads to the deadlock observed in the logs. My assumption is that this happens between the initial `SELECT` in the `batch_update()` query, and the `UPDATE` at the end which sets the `counted` column to its new value. By using `FOR UPDATE` we can hopefully prevent the `process_cdn_log` from modifying the rows while the `batch_update()` function is working, which should prevent the deadlock.

worker/jobs/downloads/update_metadata: Use `SELECT ... FOR UPDATE` in `batch_update()`

---

src/worker/jobs/downloads/update_metadata.rs

Reverts rust-lang/crates.io#8143
> Feb 17 15:31:30.791 Failed to run job error="deadlock detected"
Looks like this didn't have the desired effect, so we might as well revert it...

Revert "worker/jobs/downloads/update_metadata: Use `SELECT ... FOR UPDATE` in `batch_update()`"

---

app/styles/index.module.css
app/templates/index.hbs
src/config/server.rs
src/controllers/krate/metadata.rs
src/tests/util/test_app.rs

Reverts rust-lang/crates.io#8125.
I don't think we need this, and the implementation looks exactly as hacky as you'd expect for something thrown together in a few minutes.
@Turbo87, feel free to just go ahead and merge this, assuming you agree.

Revert "Allow `/api/v1/summary` to be disabled from the environment"

---

src/worker/jobs/downloads/process_log.rs

We're not using the results of `inserted` anywhere, so there should be no need for us to include a `RETURNING` expression in the subquery.
/cc @eth3lbert

worker/jobs/downloads/process_log: Remove unused `RETURNING` expression

---

src/worker/jobs/downloads/process_log.rs
src/worker/jobs/downloads/update_metadata.rs

Ensuring a consistent update order should reduce the risk of deadlocks between the two background jobs.

Use a consistent update order for the `version_downloads` table

---

Cargo.lock
Cargo.toml
src/controllers/helpers/pagination.rs
src/controllers/krate/search.rs
src/tests/routes/crates/list.rs

This PR add seek-based pagination support for all sorting.
This PR is best reviewed commit-by-commit.
Optimization opportunities remain, but not within this PR:
- Instead of simply limiting the query to `per_page`, we could check for additional records by querying with `per_page + 1`. If the actual count exceeds `per_page`, it indicates there's a next page; otherwise, the next page is None. This eliminates unnecessary requests when no further pages exist.

Expand the scope of seek-based pagination on search

---

app/components/crate-sidebar.js
tests/components/crate-sidebar/toml-snippet-test.js

Resolves https://github.com/rust-lang/crates.io/issues/7884

components/crate-sidebar: Use `=` prefixes if exact versions are shown

---

app/controllers/crate/version.js

see https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events
The `bubbles` and `cancelable` options don't appear to be necessary, since the scrolling works fine without them.
Resolves https://github.com/rust-lang/crates.io/issues/4787

Replace deprecated `initCustomEvent()` usage

---

app/components/copy-button.hbs
app/components/copy-button.js
app/helpers/is-clipboard-supported.js
package.json
pnpm-lock.yaml

The `Clipboard.writeText()` API is now available in all major browsers (see https://caniuse.com/mdn-api_clipboard_writetext), so we don't need this dependency anymore. Additionally, calling `copy()` of this dependency causes the current selection in the browser to be unselected, which makes it harder for us to fix #3952.

Remove obsolete `copy-text-to-clipboard` dependency

---

app/templates/policies.hbs

See https://github.com/rust-lang/crates.io/discussions/7173
And see also the [npm event-stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident).
Any feedback, especially regarding wording, is appreciated!
(CC @carols10cents since you apparently proposed adding this section in #5216)

Mention concerns for "the first person who asks" for ownership transfer

---

src/db.rs

With https://github.com/rust-lang/crates.io/pull/7422, this is no longer used anywhere.

Remove obsolete `PoolError::TestConnectionUnavailable` variant

---

src/db.rs

This will make it easier to reuse this code in other database connection pool implementations.

db: Extract `ConnectionConfig::apply()` fn

---

Cargo.lock
Cargo.toml
src/app.rs
src/bin/background-worker.rs
src/config/database_pools.rs
src/controllers/team.rs
src/db.rs
src/tests/util/test_app.rs
src/util/errors.rs
src/worker/environment.rs
src/worker/jobs/downloads/update_metadata.rs

We're currently using https://docs.rs/r2d2/ for our database connection pools, but unfortunately that is not supported by [diesel_async](https://github.com/weiznich/diesel_async) (see https://github.com/weiznich/diesel_async?tab=readme-ov-file#built-in-connection-pooling-support).
This PR introduces additional database connection pools based on `deadpool` next to the existing r2d2 pools and migrates one API endpoint and one background job to use these async connection pools instead.
All of the configuration options of the sync connection pools are still supported, with one exception: `min_size()`. `deadpool` does not shrink the pool size automatically and once `max_size` is reached these connections will be kept forever. This does not seem like a huge deal for our use case though, and if …

Add async database connection pools based on `deadpool`

---

src/controllers/krate/search.rs
src/tests/routes/crates/list.rs

Revert `to_tsquery_with_search_config` usage for `TsQuery` to the original implementation to address the issue. This is the same process as in PR #8053.

Fix the issue of relevant search not working with spaces in them when using seek pagination

---

src/controllers/helpers/pagination.rs

This PR prevents panics when `per_page` query parameter is less than 1.

Ensure `per_page` query parameter is not less than 1

---

src/config/server.rs
src/tests/util/test_app.rs
src/worker/jobs/downloads/update_metadata.rs

We've very successfully used this on production for almost two weeks now. There does not appear to be any reason for switching it back off, so this commit is removing the feature flag and permanently enables the batch processing.

Remove `BATCH_UPDATE_DOWNLOADS` feature flag

---

src/controllers/krate.rs
src/controllers/krate/metadata.rs
src/controllers/krate/versions.rs
src/router.rs
src/tests/routes/crates/versions/list.rs
src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__list__invalid_seek_parameter-2.snap
src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__list__invalid_seek_parameter.snap

This PR is an improved implementation of #5302.
Add seek-based pagination support to versions endpoint with following:
- move versions to its own file
- To keep backward compatibility, paginate versions only if `per_page` is provided.
- Support `sort` query parameter to choose either sorting by `date` or `semver` .
For date sorting, we can perform sorting and pagination directly in the database. However, Heroku Postgres doesn't support the semver PG extension, so sorting and pagination for semver needs to be done on the app server.
Resolves #5292

Add basic support for seek-based pagination to versions endpoint

---

src/bin/server.rs

We don't need to regularly save the shard contents to the database if we know upfront that those shards will be empty 😅

Disable `download_counter_thread` if CDN log download counting is enabled

---

src/controllers/util.rs

This does not appear to be used anywhere anymore :)

controllers/util: Remove unused `extensions_mut()` fn

---

migrations/2024-03-05-120032_add-crate-downloads-index/down.sql
migrations/2024-03-05-120032_add-crate-downloads-index/metadata.toml
migrations/2024-03-05-120032_add-crate-downloads-index/up.sql

We discussed this change on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/.60crate_downloads.60.20table), and it looks like this will be a significant performance improvement for search queries that use the new `crate_downloads` table.

database: Add index on `crate_downloads` table

---

app/components/header.hbs
app/components/privileged-action.hbs
tests/acceptance/sudo-test.js

Whichever stage of sudo grief we're at, we're now at acceptance.
I don't think there's anything surprising here. I used the yank button as a proxy for the general `PrivilegedAction` functionality rather than creating a new test-only component, since it's already on `main` and is unlikely to change significantly. Unit tests are covering all the actually interesting bits anyway.
The one thing that _I_ was surprised by is that the `qunit-dom` helpers were capable of clicking a button in a disabled `fieldset`, even though that's not possible from the browser UI, which means I can't write a sensible "failed to yank" style test. (I tried a few different ways just to be sure.)

Add sudo mode acceptance tests, per #8210 feedback

---

src/controllers/krate/metadata.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/summary.rs
src/views.rs

This PR builds on top of https://github.com/rust-lang/crates.io/pull/8232 and switches our `GET /api/v1/crates` endpoint over to using the `crate_downloads` table instead of the `crates.downloads` column.
Performance tests on the production replica database indicated that this should not significantly affect the performance of the endpoint (see https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/.60crate_downloads.60.20table).
This should allow us to eventually remove the `crates.downloads` column, reducing the number of writes to the `crates` table.

controllers/krate/search: Read downloads from `crate_downloads` table

---

src/typosquat/database.rs
src/typosquat/test_util.rs

This is roughly similar to #8244 and switches the typosquatting detection code over to using the `crate_downloads` database table instead of the `crates.downloads` column.

typosquat/database: Sort by downloads from `crate_downloads` table

---

src/controllers/krate/publish.rs

This is roughly similar to #8244 and switches the `PUT /api/v1/crates/new` endpoint over to using the `crate_downloads` database table instead of the `crates.downloads` column.

controllers/krate/publish: Read downloads from `crate_downloads` table

---

Cargo.lock
Cargo.toml
src/controllers/user/other.rs
src/tests/routes/users/stats.rs

This is roughly similar to #8244 and switches the `/api/v1/users/:user_id/stats` endpoint over to using the `crate_downloads` database table instead of the `crates.downloads` column.

controllers/user/other: Read downloads from `crate_downloads` table

---

src/models/dependency.rs
src/models/krate_reverse_dependencies.sql
src/views.rs

This is roughly similar to #8244 and switches the reverse dependencies endpoint over to using the `crate_downloads` database table instead of the `crates.downloads` column.

models/krate_reverse_dependencies.sql: Read downloads from `crate_downloads` table

---

src/controllers/helpers/pagination.rs
src/controllers/krate/search.rs
src/controllers/krate/versions.rs

As mention in commits https://github.com/rust-lang/crates.io/pull/8244#discussion_r1513641615 and https://github.com/rust-lang/crates.io/pull/8037#discussion_r1499030402.
This PR is best reviewed commit-by-commit.

Convert seek to named fields

---

public/opensearch.xml

Searching "on Cargo" seemed a bit confusing when the page is called crates.io. I assume this was a remainder of the time before the cargo registry was rebranded to crates.io.

opensearch: Adjust search engine name and description

---

.github/workflows/ci.yml

The sub-crates have been moved to the `crates/` folder, but we forgot to adjust the path list here.
Related:
- #8263
/cc @hi-rustin

CI: Fix `changed-files` job

---

crates/crates_io_index/repo.rs
crates/crates_io_index/testing.rs
src/tests/worker/git.rs

Context: https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/Routing.20download.20traffic.20away.20from.20crates.2Eio/near/426076481
It turns out that https://github.com/rust-lang/crates.io/commit/47e3e6e5cabff53c3479a8af5854adf97264df42 was faulty. The `git reset --hard` call did reset the repository, but it seems like the git2 `Repository` has some kind of internal state (?) that is not correctly reset by that call. The documentation of `checkout_head()` claims that it "Updates files in the index and the working tree to match the content of the commit pointed at by HEAD" and that appears to solve the problem. The new test case confirms that.
Related:
- https://github.com/rust-lang/crates.io/pull/6473

index: Fix broken `git reset --hard`

---

src/admin/enqueue_job.rs
src/worker/jobs/downloads/clean_processed_log_files.rs
src/worker/jobs/downloads/mod.rs
src/worker/jobs/mod.rs
src/worker/mod.rs

Our `processed_log_files` is already at 35k+ rows and growing steadily. We don't want it to grow infinitely though, so this commit implements a new background job that can be run regularly to remove obsolete rows from the table. The cut off date is currently hardcoded to one week, which should be sufficient to prevent duplicate SQS events and keep the table at a reasonable size.

Add `clean_processed_log_files` background job

---

src/worker/jobs/downloads/update_metadata.rs

This should remove a lot write operations from the `crates` table and hopefully improve the performance of the database a little bit.
If we see that this does not have the desired effect the following query should copy the values from the new `crate_downloads` table back into the `crates` table:
```sql
update crates
set downloads = (select downloads from crate_downloads where crate_downloads.crate_id = crates.id);
```
Related:
- #8232

worker/jobs/downloads/update_metadata: Remove `crates.downloads` column writes

---

README.md

Commit b9f92e0b6d355da065f627daf274d4475491c4f6 moved the `crates-io-worker` crate to `crates/` directory. This PR fixes the the relative URL in `README.md` to point to `crates/` directory.

fix(docs): crates-io-worker url in README.md

---

deny.toml

see https://github.com/EmbarkStudios/cargo-deny/pull/611
I'm not a huge fan of some of these new behaviors and even less about them not being configurable anymore, but unless we want to maintain a fork I guess there is not much we can do about it.

cargo-deny: Migrate to advisories & licenses v2 config

---

src/controllers/version/downloads.rs

This hasn't been used since 59377c8f5214f6800df37790328a268381c68c4e was merged

controllers/version/downloads: Remove unused `get_version_id()` fn

---

src/tests/dump_db.rs
src/tests/util/test_app.rs
src/util/tracing.rs
src/worker/jobs/downloads/process_log.rs
src/worker/jobs/downloads/queue/job.rs

This reverts commit aa0f7844be82350a43f593e547ff33cab6abc34a.
While this worked in theory, it apparently only worked on the thread where it was executed, but not on other threads like the background worker 🙈

Revert "tests: Use `tracing::subscriber::DefaultGuard` to set subscriber (#8023)"

---

src/tests/util/test_app.rs

Without this, the `Drop` implementation of the the pool would complain about not running within a tokio runtime and ultimately panic the tests. This only happened to work so far because none of our integration tests had used the async database pool yet.

tests: Explicitly close async database pools within the context of a tokio runtime

---

src/tests/util/test_app.rs

Without this the tests sometimes break because all available database connections are already taken. This is particularly relevant for the tests that use `deadpool`, since those connections are cleaned up asynchronously.

tests: Reduce pool sizes

---

crates/crates_io_worker/src/runner.rs

This functions is only used with `check_for_failed_jobs()` at this point, so we might as well inline it.

worker: Inline `connection()` fn

---

src/bin/background-worker.rs
src/tests/util/test_app.rs
src/worker/environment.rs
src/worker/jobs/daily_db_maintenance.rs
src/worker/jobs/downloads/process_log.rs
src/worker/jobs/downloads/queue/job.rs
src/worker/jobs/git.rs
src/worker/jobs/readmes.rs
src/worker/jobs/sync_admins.rs
src/worker/jobs/typosquat.rs

This PR ports all of our background worker jobs to use the async database connection pool (based on the `deadpool` crate) instead of `r2d2` (which does not support `diesel-async`).
This was initially causing failing and flaky tests, but those issues got resolved by:
- https://github.com/rust-lang/crates.io/pull/8382
- and https://github.com/rust-lang/crates.io/pull/8381

worker: Replace `r2d2` with `deadpool`

---

src/tests/util/test_app.rs

We always assign this with `Some(_)`, so we might as well remove the `Option` wrapper.
As a side-effect, this brings us a little closer to removing the r2d2 connection pool, since it removes yet another `db_write()` fn call :)

tests/util/test_app: Simplify `test_database` field

---

src/tests/util/test_app.rs

The following `background_jobs::table.count() == 0` assertion covers this case already, so there is no need for us to run two queries.

tests/util/test_app: Remove duplicate background job assertion

---

src/util/errors.rs

Previously, these were converted to "500 Internal Server Error", but this didn't match the behavior of the r2d2-based connection pool. This PR adjusts the error conversion code to return "503 Service Unavailable" responses instead.

util/errors: Convert `deadpool` errors to "503 Service Unavailable" responses

---

src/util/errors.rs

If the database server closes the connection while we're still connected then it's usually a signal that the database is no longer available. For the r2d2-based connection pool we detect these situations and convert them to `UnhealthyPool` errors, but with `deadpool` we will see raw `ClosedConnection` errors instead.
Similar to #8429, this PR adjusts our code so that the `deadpool`-using code behaves roughly similar to the `r2d2` code.

util/errors: Convert `ClosedConnection` errors to "503 Service Unavailable" responses

---

Cargo.lock
crates/crates_io_worker/Cargo.toml
crates/crates_io_worker/src/runner.rs
crates/crates_io_worker/src/util.rs
crates/crates_io_worker/src/worker.rs
crates/crates_io_worker/tests/runner.rs
src/bin/background-worker.rs
src/tests/util/test_app.rs

While #8385 ported the individual background worker jobs from `r2d2` to `deadpool`, this PR ports the background worker system itself to it.
Note that the default `async_pool_size` for the test suite had to be increased because the background worker system now requires us to have one more connection available.

crates_io_worker: Replace `r2d2` with `deadpool`

---

src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/github/secret_scanning.rs
src/controllers/keyword.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/krate/versions.rs
src/controllers/metrics.rs
src/controllers/summary.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs

This PR is roughly similar to #8385, but this time all of our API endpoints are ported from the sync `r2d2` database connection pool to the async `deadpool` equivalent.
A couple of minor refactorings were needed in some places, but the semantics should still be similar to before. I guess this is best reviewed commit-by-commit... 😅

controllers: Replace `r2d2` with `deadpool`

---

src/tests/util/test_app.rs

This allows us to get rid of the `db_write()` fn on the `App` struct soon... 🎉

tests/util/test_app: Use `test_database.connect()` for `background_jobs` query

---

src/tests/unhealthy_database.rs

All of the API endpoints in these tests are using the async database pools at this point, so waiting until the *sync* connection pools are healthy again isn't particularly helpful :D

tests/unhealthy_database: Migrate from sync to async database pools

---

src/controllers/user/session.rs

This changes the order of operations a bit. Previously, we were first doing the GitHub requests and then connecting to the database. Now, we are first connecting to the database before doing the **sync** OAuth exchange with GitHub. This allows us to move from `spawn_blocking()` to `conn.interact()` though, which in turn allows us to get rid of the sync database connection pools soon.

controllers/user/session: Replace `r2d2` with `deadpool`

---

Cargo.toml
src/app.rs
src/db.rs
src/metrics/instance.rs
src/util/errors.rs

This PR completely removes the sync `r2d2` database connection pools from our backend server code. All of our code has now been migrated to the `deadpool` async pools.
There is one small caveat: our `crates_io_test_db` package is still using `r2d2` under the hood. If/How that can be migrated remains to be seen, since it's relying on `Drop` impls, which are complicated in an async world.

Remove `r2d2` database connection pools

---

src/app.rs
src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/github/secret_scanning.rs
src/controllers/keyword.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/krate/versions.rs
src/controllers/metrics.rs
src/controllers/summary.rs
src/controllers/team.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/session.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/metrics/instance.rs
src/tests/unhealthy_database.rs
src/tests/util/test_app.rs

This commit renames a couple of struct fields and functions to remove `async` and `deadpool` pre-/suffixes. This distinction is no longer needed, since we don't use sync database connection pools anymore.

deadpool: Drop obsolete `async` suffixes

---

src/util/tracing.rs

This PR enables time output for our test suites.
The DataDog and Papertrail logs in production already include timestamps, so we don't need these there, but the test suite runner does not provide them and while debugging #8449 they proved to be quite useful.

tracing: Enable time output in tests

---

src/app.rs
src/config/database_pools.rs
src/middleware/balance_capacity.rs
src/tests/util/test_app.rs

We don't have sync database pools anymore, so there is no need to keep the config code around.

config/database_pools: Remove sync database pools

---

migrations/2024-04-17-083100_remove-obsolete-fn/down.sql
migrations/2024-04-17-083100_remove-obsolete-fn/up.sql

This was used when the crate downloads were still saved in the `crates` table, but when we moved those to a dedicated table we changed the update trigger to use the regular `set_updated_at()` fn instead, making `set_updated_at_ignore_downloads()` unused.

database: Remove obsolete `set_updated_at_ignore_downloads()` fn

---

.github/renovate.json5

The release of these crates is automated, so we might as well automate their updates too.

renovate: Automerge `aws-ip-ranges` and `github-meta` crate updates

---

crates/crates_io_worker/src/runner.rs
crates/crates_io_worker/tests/runner.rs
src/bin/background-worker.rs
src/tests/util/test_app.rs

We only need this in a single place (the `start()` fn), and instead of explicitly passing in a handle we can rely on the "current" handle by making sure that `start()` is always called within the context of a runtime.

worker/runner: Remove `tokio` runtime handle parameter

---

src/auth.rs
src/controllers/crate_owner_invitation.rs
src/controllers/metrics.rs
src/controllers/util.rs
src/tests/authentication.rs
src/tests/krate/following.rs
src/tests/krate/publish/auth.rs
src/tests/routes/crates/owners/add.rs
src/tests/routes/crates/versions/yank_unyank.rs
src/tests/routes/me/get.rs
src/tests/routes/me/tokens/delete_current.rs
src/tests/routes/users/update.rs
src/util/errors.rs

This PR adjusts our `forbidden()` error constructor fn by removing the hardcoded `details` message and replacing it with more contextual error messages.
Resolves https://github.com/rust-lang/crates.io/issues/8461

Improve "403 Forbidden" error messages

---

src/util/tracing.rs

tracing output is only shown for failed tests anyway, and since we are usually quite interested to debug failed tests it's probably better to show the debug output by default.

util/tracing: Enable debug tracing by default for tests

---

src/tests/server_binary.rs
src/tests/util/chaosproxy.rs
src/tests/util/test_app.rs

Previously, the `ChaosProxy` would starts its own dedicated multi-thread runtime. After this PR the `ChaosProxy` entry point is an async function, which reuses the runtime that is used to run the async function. This slightly simplifies the setup and makes the runtimes a bit easier to reason about.
(it is also one more step towards an async test suite... 😉)

chaosproxy: Remove internal tokio runtime

---

src/tests/categories.rs

Previously we were only testing that the category syncing works, but not that the `categories.toml` file is actually valid. This commit fixes the issue by adding a dedicated test for the file.

Add test for the `categories.toml` file

---

src/boot/categories.toml

Hi,
I have been working on quite a few bioinformatics related rust packages and thought it would be great to have a bioinformatics category and related subcategories. I've added those to the file here.

Add bioinformatics category and related subcategories

---

src/storage.rs

see https://github.com/apache/arrow-rs/pull/5650

storage: Use `Attributes` API to reduce the amount of `ObjectStore` instances

---

app/components/footer.hbs

This PR updates the team link in the footer to reflect [Implement RFC#3595 Moving crates.io under devtools](https://github.com/rust-lang/team/pull/1439).
Closes #8552.

Footer: Update the team link

---

src/boot/categories.toml

Android is its own OS on top of Linux with _lots_ of custom/specific interfaces.  Many crates are wrapping (parts) of it, such as [the NDK crate].  Since there's an `os::XXX-apis` tag for many OSes already, Android also belongs in this list.
[the NDK crate]: https://crates.io/crates/ndk

Add `os::android-apis` category for Android bindings

---

config/targets.js

This reverts commit ac9dba740bdd84def5d66f384da0061edc4381f5.
It's been three years... Edge on Android is now apparently on v123, matching the desktop release version. It seems that we don't have to worry about this anymore.
This change is saving a couple dozens bytes since we can now use `?` syntax in JS without having to polyfill it.

Revert "Fix "Edge for Android" compatibility"

---

.github/workflows/ci.yml

The main goal of this PR was to ensure that the `pg_dump` version used by our database dump code matches the version of the database server that is used to run the test suite.
Since we already install the correct version on the system with the first change we can also just use `systemctl start postgresql.service` to start a PostgreSQL server, instead of having to install and boot up a dedicated Docker container for the same purpose. The second commit in this PR thus removes the Docker container and sets up the PostgreSQL server correctly so that we can use it in our test suite.
This should unblock #8578 by now installing a new enough `pg_dump` version that can be used by our test suite.

CI: Replace Docker-based PostgreSQL server with `apt-get` install

---

.env.sample
Cargo.lock
Cargo.toml
src/admin/enqueue_job.rs
src/bin/background-worker.rs
src/worker/environment.rs
src/worker/jobs/archive_version_downloads.rs
src/worker/jobs/mod.rs
src/worker/mod.rs

This PR implements a solution for https://github.com/rust-lang/crates.io/issues/3479. The new background job can be used to export all version download data to S3 and then remove it from the database. This should allow us to shrink the database considerably, which hopefully might have a positive effect on our database performance.

Implement `ArchiveVersionDownloads` background job

---

Cargo.lock
Cargo.toml
src/cloudfront.rs
src/sqs.rs

This reverts commit 34bd67e089f1baa77680d8444c1c3efcb771bd98, reversing changes made to b6b4386e964071c6d33fb68d8ca5ed7b4f20677d.
see https://github.com/awslabs/aws-sdk-rust/issues/1148

Revert "Merge pull request #8610 from rust-lang/renovate/aws-sdk-rust-monorepo"

---

app/routes/application.js
app/services/sentry.js
tests/helpers/sentry.js

`configureScope()` has apparently been deprecated a while ago and was recently removed in https://github.com/getsentry/sentry-javascript/pull/9887. Since we are mocking Sentry in our test suite we unfortunately didn't notice the issue before it popped up on our staging environment.

Sentry: Fix broken `configureScope()` call

---

package.json
pnpm-lock.yaml

Reverts rust-lang/crates.io#8631
This has caused various regressions on the staging environment. Best to revert for now and take a closer look without impacting the `main` branch.

Revert "Update sentry-javascript monorepo to v8 (major)"

---

app/templates/data-access.hbs
src/middleware/block_traffic.rs
src/tests/snapshots/all__server__block_traffic_via_arbitrary_header_and_value.snap
src/tests/snapshots/all__server__block_traffic_via_ip.snap

We only have a data access policy at https://crates.io/data-access, which has replaced the `#crawler` part of `/policies`.

Remove/replace references to the "crawler policy"

---

src/worker/jobs/expiry_notification.rs

`expiry_notification` is a bit generic and if we introduce other expiring resources this could cause confusion. This PR adjusts the `JOB_NAME` constant to match the struct name, which includes `token` in the name and resolves the potential confusion.

worker/jobs/expiry_notification: Adjust `JOB_NAME` to match struct name

---

app/components/search-form.module.css

I've tried various things to make this work properly, but haven't found a proper solution. This commit works around the issue by slightly offsetting the submit button to the right. I'm not a fan of this "solution", but I've run out of ideas...
Resolves https://github.com/rust-lang/crates.io/issues/8677

components/search-form: Work around gap between focus shadow and submit button

---

app/components/text-content.module.css
app/modifiers/highlight-syntax.js

Instead of unconditionally importing the `github.css` theme, we use a custom theme that uses the `light-dark()` fn. This custom theme is a merging the `github.css` and `github-dark.css` files into one.
Resolves https://github.com/rust-lang/crates.io/issues/8673

Implement dark mode for syntax highlighted code blocks

---

app/services/color-scheme.js

We've ironed out most of the issues with the dark UI mode, so now it's time to change the default and have people automatically get the dark UI mode if their operating system demands it.

Switch default color scheme to "System"

---

src/admin/default_versions.rs
src/admin/mod.rs
src/bin/crates-admin.rs
src/models.rs
src/models/default_versions.rs

This changes `crates-admin update-default-versions` to `crates-admin default-versions update`, and adds an additional `crates-admin default-versions verify` command. This new command iterates over all crates, calculates the default version and compares it with the default version that is currently saved in the database. In case the results do not match it prints a warning message. This should allow us to verify that our code to update the `default_versions` table is working correctly and that we don't have any inconsistencies.

admin/default_versions: Implement `verify` mode

---

app/initializers/app-hook.js
app/utils/sentry.js
tests/helpers/sentry.js

The production build is currently broken because the `app-hook` initializer is unable to import the `MockSentryService` class from `crates-io/tests` because those test-only files are not included in the production build. Ideally we'd exclude this initializer from the production build, but I haven't found a straight-forward way for doing that yet. The current solution is not ideal because we are shipping these unnecessary bytes to our users, but until we find a better way this at least unblocks our `main` branch again.
/cc @eth3lbert

Move `MockSentryService` class into the `app` folder

---

src/metrics/service.rs

Without this the background jobs will never be reset to zero again... 🙈

metrics/service: Reset `background_jobs` metric before setting new values

---

ember-cli-build.js
package.json
pnpm-lock.yaml

`postcss-preset-env` already includes https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting, which makes `postcss-nested` redundant.

Remove obsolete `postcss-nested` plugin

---

src/admin/enqueue_job.rs
src/worker/jobs/dump_db.rs

We haven't used this in years and it makes it a bit more complicated to support other file types in the future.
Related:
- https://github.com/rust-lang/crates.io/issues/2078

workers/jobs/dump_db: Remove unnecessary `target_name` field

---

src/worker/jobs/dump_db.rs

There is no need for us to recreate the `Storage` instance for each job run, we already have it in the `Context`. This also makes it possible to properly test the background job now, since it's now using the in-memory storage instead.

workers/jobs/dump_db: Use `Storage` from background job context

---

crates/crates_io_test_db/src/lib.rs
src/tests/dump_db.rs

Instead of only running `import.sql` on a database with all migrations applied we can run the generated `schema.sql` file on an empty database. This ensures that the schema and data import scripts are compatible with each other.

tests/dump_db: Add `schema.sql` to the test

---

src/tests/dump_db.rs
src/worker/jobs/dump_db.rs

This removes the need for us to guard our test suite with a mutex because of the shared export folder. With this PR every invocation of the code creates a dedicated temporary export folder, which removes the chance of filesystem conflicts between tests.

dump_db: Use `tempfile` for temporary file/folder creation

---

src/tests/dump_db.rs
src/worker/jobs/dump_db.rs

Instead of exporting into a prefixed folder we can apply the datetime prefix when creating the tarball. This allows us to skip the prefix for other output formats in the future and it also simplifies the `DumpDirectory` struct.

workers/jobs/dump_db: Apply date prefix when creating tarball

---

src/controllers/krate/publish.rs
src/tests/krate/publish/validation.rs

Resolves https://github.com/rust-lang/crates.io/discussions/8739
This PR introduces a limit on the length of the `description` field. Descriptions like https://crates.io/crates/docker-rust-api seem unreasonably long, so I've decided for an arbitrary limit of 1000 characters for now. As mentioned on the linked discussion, our frontend currently truncates the description to 200 characters in some places, so 1000 as a hard limit seem okay to me.

Introduce length limit on the `description` field

---

.github/renovate.json5

Second try... hopefully this works

renovate: Disable `node` version pinning in frontend Dockerfile

---

Cargo.lock
Cargo.toml
deny.toml
src/storage.rs
src/tests/dump_db.rs
src/worker/jobs/dump_db.rs

Zip files use compression per file, which allows users to only extract the data that they need, instead of needlessly extracting the full tarball to read the small table that they are interested in.
Resolves https://github.com/rust-lang/crates.io/issues/2078

Create `db-dump.zip` file too

---

app/components/settings-page.hbs

We can add it again if that page actually has some content, but for now it's pointless to link to a page that hasn't had any content in years.

Settings: Remove "Email Notifications" link

---

e2e/bugs/2329.spec.ts

The "Email Notifications" link doesn't exist anymore, so we can not click it in this test...

Playwright: Skip "Email Notifications" test

---

Cargo.lock
crates/crates_io_tarball/Cargo.toml
crates/crates_io_tarball/src/lib.rs

This makes it easier to write the error assertions, and has the added benefit of testing the derived `Display` trait of the error enum.

crates_io_tarball: Use `insta` snapshots to simplify test code

---

crates/crates_io_tarball/src/lib.rs

This slightly slims the test code down by replacing repeated variables with module-scope constants :)

crates_io_tarball: Extract constants

---

crates/crates_io_tarball/src/lib.rs
src/controllers/krate/publish.rs
src/tests/krate/publish/snapshots/all__krate__publish__manifest__multiple_manifests.snap

Resolves https://github.com/rust-lang/crates.io/issues/8410
This implementation uses `.to_ascii_lowercase()` on the `Path` to compare the paths. In other words: this may or may not be sufficient depending on the filesystem and the usage of non-ASCII characters in the paths. It seems to cover the majority of the existing cases though, so it's at least a step in the right direction.
In the future we could even consider rejecting non-ASCII paths, in which case this implementation would probably be sufficient.
/cc @kornelski

crates_io_tarball: Disallow paths differing only by case

---

src/db.rs

This makes queries from the application easier to recognize in the logs.
see https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-APPLICATION-NAME

Postgres: Set `application_name` to crates.io

---

crates/crates_io_tarball/src/lib.rs
src/controllers/krate/publish.rs
src/tests/krate/publish/snapshots/all__krate__publish__manifest__multiple_manifests.snap

Reverts rust-lang/crates.io#8788

Revert "crates_io_tarball: Disallow paths differing only by case"

---

config/environment.js
package.json
pnpm-lock.yaml

AFAICT we're not using this dependency in any way and we don't need to ship these bytes to the user if nothing is using them...

Remove unused `ember-cli-app-version` dependency

---

src/storage.rs

Resolves #8823
I liked the suggestion on the issue and implemented as described. Checked with the object_store crate for the correct values of the flag to support InMemory (true), LocalFileSystem (false), and S3 (true) object stores. 
I thought using match to set the attributes based on the flag looked cleaner, but I believe the if statement is more standard style.

Add supports_attributes Flag to Storage Struct to Support ObjectStore Implementations

---

src/admin/enqueue_job.rs
src/tests/dump_db.rs
src/worker/jobs/dump_db.rs

On our staging environment we usually don't use a read-replica database, so `READ_ONLY_REPLICA_URL` might not always be set. Instead of saving the potentially secret database URL in the background job we can read it from the background worker config instead, and fall back to the primary database if a read-replica is not configured.
I'm not aware of us using the background job with a non-default `database_url` in the past couple of years, so this option will probably not be missed. :D

worker/jobs/dump_db: Remove `database_url` field

---

src/tests/builders/krate.rs
src/tests/builders/version.rs

We're using regular `Option<String>` already for `links` and `rust_version` and while the `&str` might be slightly more efficient it is also slightly less ergonomic. Switching the field type also allows us to remove the `'a` lifetime declaration from the struct which makes it a bit easier on the eyes too. If we ever feel like we need the raw speed we can always add it back.

tests/builders/version: Simplify `license` field

---

app/components/text-content.module.css
e2e/acceptance/readme-rendering.spec.ts
tests/acceptance/readme-rendering-test.js

Remove background color from preformatted code blocks within lists

---

app/styles/application.module.css

This appears to not be compatible with the `postcss-nesting` plugin:
> postcss-nesting: crates.io/assets/crates-io.css:656:5: Failed to parse selectors : "" / "._c-notification__icon_17u5gr" with message: "Cannot read properties of undefined (reading 'type')"
> postcss-nesting: crates.io/assets/crates-io.css:662:5: Failed to parse selectors : "" / "._c-notification__content_17u5gr" with message: "Cannot read properties of undefined (reading 'type')"

styles: Fix `:global { ... }` block usage

---

src/controllers/krate/publish.rs
src/models/version.rs
src/tests/builders/version.rs
src/typosquat/test_util.rs
src/worker/jobs/downloads/update_metadata.rs

This finally solves the `clippy::too_many_arguments` warning, and makes the `NewVersion` struct slightly more ergonomic to use in our test code.

models/version: Derive `NewVersion` builder struct

---

Cargo.lock
Cargo.toml
src/util/tracing.rs

As discussed in the team meeting on Friday, this PR adds support for a JSON log format. If the `RUST_LOG_FORMAT` environment variable is set to `json` our tracing code will start to use https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Json.html for log formatting.

tracing: Use JSON log format if `RUST_LOG_FORMAT=json` is set

---

src/controllers/token.rs
src/router.rs
src/tests/routes/me/tokens/get.rs
src/tests/routes/me/tokens/mod.rs
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__get__show.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__get__show_token_with_scopes.snap

ref https://github.com/rust-lang/crates.io/issues/8717
In this PR I have added the `show` API for ApiToken to prepare to get the information by ID on the create token page.
And I also added some tests.

Add `GET /api/v1/me/tokens/:id` API endpoint

---

src/tests/dump_db.rs
src/tests/krate/publish/basics.rs
src/tests/krate/publish/git.rs
src/tests/krate/publish/max_size.rs
src/tests/krate/publish/rate_limit.rs
src/tests/krate/publish/readme.rs

This makes these assertions easier to update when the list of stored files changes (see #8908 😉).

Use snapshot tests for `app.stored_files()` assertions

---

.github/renovate.json5

This does not seem to play well with the `regex` manager...

renovate: Disable `pinDigest` updates for the whole `docker` datasource

---

crates/crates_io_test_db/src/lib.rs

The default value of 30 sec. is fine for production servers, but seems a bit excessive for our test suite.

crates_io_test_db: Reduce connection timeout to 5 sec.

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.js
app/components/crate-sidebar.module.css
app/components/crate-sidebar/install-instructions.hbs
app/components/crate-sidebar/install-instructions.js
app/components/crate-sidebar/install-instructions.module.css
app/helpers/sum.js
app/models/version.js

This PR adds `has_lib` and `bin_names` fields to the `version` Ember Data model and then uses these new fields to display `cargo install` instructions if a crate has any binaries. If the API does not expose these fields yet, or they are returned as `null` because the crate/version has not been analyzed yet, the code will default to the current behavior of assuming the crate is a library.
Related:
- https://github.com/rust-lang/crates.io/issues/5882
- https://github.com/rust-lang/crates.io/pull/8859

Show `cargo install` for crates with binaries

---

src/models/category.rs
src/models/krate.rs

This commit replaces some of the manual written type aliases by [`#[diesel::dsl::auto_type]`](https://docs.diesel.rs/2.2.x/diesel/dsl/attr.auto_type.html) which just generates the correct return type based on the function content. This hopefully removes some complexity from the database code.
The main motivation for this change is to update the diesel [Composing Applications](https://diesel.rs/guides/composing-applications.html) guide which is based on this code. 
I'm not 100% happy with this as it's currently not possible to use `#[auto_type]` for all the the type defs due to the following reasons:
* `#[auto_type]` by default generates a type def alongside the function that names the return type. This cannot easily be done here as associated types for non-trait impls are not stable yet. …

Use `#[diesel::dsl::auto_type]` in some places

---

src/tests/util/test_app.rs

This was decreased in 933576ae8cf92a1afdcbdafa209eeb73abbe00b2 when we were running the sync and async pools in parallel, but at this point we only use the async pool and can increase the pool size again. This should hopefully reduce the [current flakyness of our test suite](https://github.com/rust-lang/crates.io/actions/runs/9789499489/job/27029343419?pr=8993) a bit.

tests: Increase database pool size

---

app/controllers/settings/tokens/new.js
app/routes/settings/tokens/new.js
app/templates/settings/tokens/new.hbs
e2e/routes/settings/tokens/new.spec.ts
mirage/route-handlers/me.js
tests/routes/settings/tokens/new-test.js

This PR added token info retrieval on the new token page.
I have introduced a new query parameter for the `new' page to allow us to pre-populate the original token information.  
Tested locally:
https://github.com/rust-lang/crates.io/assets/29879298/462919cb-0c5c-4804-9914-e01d0710fe22
Related:
- https://github.com/rust-lang/crates.io/issues/8717

Prefill "New API Token" page with existing values if requested

---

app/controllers/crates.js
e2e/acceptance/crates.spec.ts
mirage/route-handlers/crates.js
tests/acceptance/crates-test.js

"Browse All Crates" is the most prominent link in the menu bar, displayed on all pages. Before this change, this link would present the user with (mostly) irrelevant crates, as it was sorted alphabetically: crates like `a`, `a-`, `a0`, etc.
With this change, the list is now sorted to present the most downloaded crates first.
`/keywords/:term` already defaults to that same order.

controllers/crates: default to sort by recent downloads

---

src/worker/jobs/expiry_notification.rs

ref https://github.com/rust-lang/crates.io/issues/8717
Tested locally:
1. Start the crates.io in the docker
```console
crates.io on  rustin-patch-copy-token via 🐳 orbstack is 📦 v0.0.0 via  v20.13.0 via 🦀 v1.81.0-nightly took 2s 
❯ docker ps
CONTAINER ID   IMAGE               COMMAND                  CREATED          STATUS             PORTS                                       NAMES
7ce772c8b3b2   cratesio-worker     "cargo run --bin bac…"   4 minutes ago    Up 4 minutes                                                   cratesio-worker-1
5047a4401dfe   cratesio-frontend   "pnpm start"             10 minutes ago   Up 10 minutes      0.0.0.0:4200->4200/tcp, :::4200->4200/tcp   cratesio-frontend-1
e740cac267e7   cratesio-backend    "/app/docker_entrypo…"   10 minutes ago   Up 10 minutes …
```

Update expiry notification to use the copy token link

---

.github/workflows/ci.yml
e2e/fixtures/percy.ts

This PR addresses #9052 by:
- Separates the e2e percy snapshots from the QUnit tests by prefixing them with `e2e` in their titles.
- Enables parallel test suites for percy in CI.
---
Changing only the title to separate snapshot sets **without** enabling parallel test suites is insufficient.  This will cause  finalized builds to not recognize each other and consider others **missing**.  Therefore, enabling parallel test suites for percy is necessary.
Thanks @Turbo87 for the information and guidance!

Separate e2e snapshots and enable parallel test suites for percy

---

config/deprecation-workflow.js
package.json
pnpm-lock.yaml

We don't need this anymore, so we don't need to install it anymore either. Additionally, the new major version appears to unconditionally include the addon code in production builds too which is a price I'm not willing to pay.

Remove obsolete `ember-cli-deprecation-workflow` addon

---

README.md

Follow-up work to https://github.com/rust-lang/crates.io/pull/8791 now that the page is live.
This PR was extracted from https://github.com/rust-lang/crates.io/pull/9048 since that commit seems uncontroversial on its own :)

Change the README security link to crates.io's security page

---

app/components/crate-sidebar.hbs
app/components/version-list/row.hbs
app/models/version.js

For versions we only care about the publish date, not about e.g. the last update of the `yanked` column. The displayed value was already using `created_at`, just not the attribute on the `<time>` element yet, so this can be seen as fixing an inconsistency :)

UI: Use `created_at` instead of `updated_at`

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar/install-instructions.module.css

`has_lib: false` was still showing the "Install as library" section, and looking at the code I can only 🤦‍♂️ 😂 
This PR fixes the broken assignment so that https://crates.io/crates/ripgrep will no longer show that section. The PR also includes a tiny styling tweak to make the margins between the sidebar sections consistent in this case.

CrateSidebar: Fix `@hasLib` assignment

---

public/.well-known/security.txt
src/middleware/common_headers.rs

Follow-up work to #8791 now that the page is live!

Add `.well-known/security.txt` file

---

app/components/rendered-html.hbs
app/components/rendered-html.js
app/modifiers/update-source-media.js
crates/crates_io_markdown/lib.rs

Resolves https://github.com/rust-lang/crates.io/issues/9093
GitHub allows this via e.g.:
```html
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://test.crates.io/logo_dark.svg">
</picture>
```
but so far we haven't allowed the `picture` and `source` elements when rendering markdown files. This PR changes that.
This PR also adjusts our frontend code to make these `picture` elements work properly. Natively, these elements only react to the device's color scheme choice, but not to any overrides on the website itself. The `color-scheme` CSS attribute unfortunately does not influence the `media` resolution of the `source` elements. https://larsmagnus.co/blog/how-to-make-images-react-to-light-and-dark-mode presents a relatively straight-forward way to make this work with …

Add support for pictures that react to the user's color scheme choice

---

src/worker/jobs/rss/sync_crate_feed.rs

Reverts rust-lang/crates.io#9116
The initial sync of all crates has finished, so we no longer need this hotfix :)

Revert "jobs/rss/sync_crate_feed: Introduce temporary `SKIP_RSS_CLOUDFRONT_INVALIDATION` env var"

---

app/components/settings/api-tokens.hbs
app/components/settings/api-tokens.module.css
e2e/acceptance/api-token.spec.ts
tests/acceptance/api-token-test.js

Resolves https://github.com/rust-lang/crates.io/issues/8717
The reason I chose "regenerate" instead of "copy" is that the latter is quite confusing. Users might think it means copying the token value.

Add support for regenerating the token

---

src/admin/verify_token.rs
src/models/user.rs
src/tests/user.rs

This fn is only used in two non-production places and isn't saving a lot of characters, but creates a bi-directional coupling between the API token and user models, which we don't necessarily want to have.

models/user: Inline `find_by_api_token()` fn

---

src/admin/verify_token.rs
src/auth.rs
src/models/token.rs
src/tests/user.rs
src/util/token.rs

This reduces the coupling to the `AppResult` enum and improves the composability of the code. Incidentally it also simplifies the error handling in our authentication code.

models/user: Move `HashedToken::parse()` call outside `find_by_api_token()` fn

---

.editorconfig

two spaces seems to be a lot more common in the JS world 😉

editorconfig: Adjust indentation for JSON files

---

src/controllers/krate/versions.rs
src/typosquat/database.rs

For some reason the Rust borrow checker is not currently complaining about these, but once the code is migrated to `diesel-async` it starts to fail the build.

Avoid mutations while still borrowed

---

Cargo.toml

The `all` lint group represents all lints that are enabled by default. Since they are enabled by default there is not much point in us setting them to the `warn` level again. With Rust 1.80 this will also start to trigger https://rust-lang.github.io/rust-clippy/master/index.html#lint_groups_priority, which this change now avoids.

clippy: Remove `all = "warn"` override

---

Cargo.lock
Cargo.toml
crates/crates_io_env_vars/Cargo.toml
crates/crates_io_env_vars/src/lib.rs
crates/crates_io_test_db/Cargo.toml
crates/crates_io_test_db/src/lib.rs
src/ci.rs
src/controllers/github/secret_scanning.rs
src/controllers/krate/search.rs
src/real_ip.rs
src/tests/dump_db.rs
src/tests/routes/crates/list.rs

This functionality is now supplied by the std lib 🎉 
Related:
- https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html#lazycell-and-lazylock

Remove obsolete `once_cell` dependency

---

src/bin/background-worker.rs
src/storage.rs
src/worker/jobs/archive_version_downloads.rs

Previously we were uploading the version downloads exports to a dedicated bucket, but the infra team decided that it would be best to use the `static` bucket instead. This changes the upload location by switching from a dedicated `ObjectStore` instance to a `PrefixStore` based on our `Storage` struct and the `archive/version-downloads` prefix.

Change version downloads archive location to static S3 bucket

---

src/worker/jobs/downloads/process_log.rs

On our production servers we've been seeing warnings like:
> Failed to fill temp_downloads table: error encoding message to server: value too large to transmit
It looks like this error is returned by `tokio-postgres`, which can't handle the amount of data we throw at it when using a batch size of 10k rows. This commit decreases the batch size in the hope that this makes the background job succeed. If not, we might have to further decrease it.
A potentially better solution for this would be to use a `COPY` query, but that wasn't available yet in `diesel` when the code was originally written.
Related:
- https://github.com/sfackler/rust-postgres/issues/356

jobs/downloads/process_log: Decrease batch size

---

src/tests/krate/publish/rate_limit.rs

... to decrease test flakiness. Ideally this test wouldn't rely on timings at all, but with rate limits and without an obvious way to control the clock that is unfortunately not straight-forward with the current implementation.

tests/krate/publish/rate_limit: Increase rate limit duration

---

src/worker/environment.rs
src/worker/jobs/dump_db.rs
src/worker/jobs/rss/sync_crate_feed.rs
src/worker/jobs/rss/sync_crates_feed.rs
src/worker/jobs/rss/sync_updates_feed.rs

The index only uses CloudFront, so that still needs to go directly through `Environment::cloudfront()`, but there's no particular reason to have a bunch of background jobs with similar patterns for static.crates.io.

Unify CDN invalidation into a single method on `Environment`

---

docs/ARCHITECTURE.md

Deleted two lines from `ARCHITECTURE.md` because `build.rs` was removed via https://github.com/rust-lang/crates.io/pull/7422 and `.rustfmt.toml` was removed via https://github.com/rust-lang/crates.io/pull/2107.

docs: Remove deprecated lines from ARCHITECTURE.md#Backend

---

src/worker/jobs/dump_db.rs

The `dump_db_and_reimport_dump` test fails on my machine because my `.psqlrc` sets the session into "read-only" mode by default, causing the import step to fail.
Looking at how this is used, I don't think sourcing the `.psqlrc` file is intended - a user might have it do anything! It's not uncommon to `SET` various options on the connection, some of which might cause problems (timeouts, search paths, etc).
---
* fix: don't read .psqlrc for automated DB export (0c492d28)
The dump_db::run_psql() function spawns a psql child process to run a an
export script, but psql will automatically load and execute the content
of the user's ~/.psqlrc file if it exists and execute it before the
export script.
The statements executed from the psqlrc file might change connection
parameters (for example, the …

Don't read .psqlrc for automated DB export

---

.github/renovate.json5

#9229 removes comments, so we don't want that, but we should handle the actual schema change.

Update Renovate config per the hint in #9229.

---

src/controllers/token.rs
src/tests/routes/me/tokens/create.rs

This PR will make crates.io email the user's registered email address when a new token is added to their account.
An email notification helps mitigate a sneaky 3rd party with access to the account from creating a token and using it to do nasty things later. Without the notification you'd only know about the token if you were periodically checking the token page.
Part of https://github.com/rust-lang/crates.io/issues/2639
---
* feat: token creation notification email (83c83135)
When a new token is created for an account, send a notification email to
the account owner.

Add API token creation notifications

---

src/storage.rs

Otherwise the `index.html` is served with `Content-Type: binary/octet-stream` and the browser shows a download dialog...

storage: Adjust content types for version downloads archive files

---

src/controllers/krate/owners.rs
src/tests/routes/crates/owners/add.rs
src/tests/util.rs

This limits an "add crate co-owner" request to inviting at most 10 users per request.
This bounds the amount of CPU time a single API request can take, and therefore limits how long the associated database connection and `spawn_blocking()` thread are monopolised for to service that request.
There's still some oddities around using a single transaction across all invites: it's possible to construct an API request that does the work to invite 9 people, and then aborts and rolls back any database changes. This can enable someone malicious to retry requests rapidly (including sending emails as a result). I think perhaps a refactor of the controller / model split is needed to solve this properly though.
---
* fix: bound co-owner invites per request (2ce40b3fa)
Bound the number of co-owner …

fix: bound co-owner invites per request

---

migrations/2024-08-17-152408_add-yank-message/down.sql
migrations/2024-08-17-152408_add-yank-message/up.sql
src/models/version.rs
src/schema.rs
src/worker/jobs/dump_db/dump-db.toml

ref https://github.com/rust-lang/crates.io/issues/9193
In this PR, I added a new column to the `versions` table.
I picked the text here. For a simple text-based message, I think the length is enough.
I am not sure if we should consider using JSONB here to accommodate the possibility of needing to store more structured information in the future.
I also marked it private, I guess before we expose the new API to users, we should keep it private.

database: Add `versions.yank_message` column

---

app/styles/shared/buttons.module.css

Buttons were not meant to get a green text color when the cursor hovers over them...
There might be a better fix for it, but I'm not seeing it right now. Feel free to comment if you know how to improve this 😉

styles: Fix button text color when hovering

---

src/controllers.rs
src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/github/secret_scanning.rs
src/controllers/helpers.rs
src/controllers/helpers/pagination.rs
src/controllers/keyword.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/krate/versions.rs
src/controllers/metrics.rs
src/controllers/summary.rs
src/controllers/team.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/session.rs
src/controllers/util.rs
src/controllers/version.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/util/request_helpers.rs

These can make it hard sometimes to understand where certain things are imported from and they unconditionally import the `diesel` prelude, which makes moving to `diesel_async` slightly harder in some cases. Since most Rust editor have an automatic import feature these days it should be viable to remove these preludes in favor of the additional code clarity.

Remove controller preludes

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css
app/styles/shared/buttons.module.css

This button is a `mailto:help@crates.io` link with a prefilled subject and body, that should make it easier for users to report crates which are violating our usage policies or are otherwise worth reporting to us.
Related:
- https://github.com/rust-lang/crates.io/discussions/7081

Add a "Report crate" button

---

src/tests/krate/publish/basics.rs
src/tests/routes/me/snapshots/all__routes__me__get__me-2.snap
src/tests/routes/me/snapshots/all__routes__me__get__me-3.snap
src/tests/user.rs
src/tests/util/test_app.rs

When generating a test user, derive that user's email address from the username.
This makes asserting the correct recipient emails are used when inspecting emails in tests.
@domodwyer I extracted that from one of your branches, since it seems like a useful change on its own and is also used/needed for https://github.com/rust-lang/crates.io/pull/2705 :)

test: generate per-user email

---

src/tests/github_secret_scanning.rs
src/tests/owners.rs
src/tests/routes/crates/owners/add.rs
src/tests/routes/me/tokens/create.rs
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success-2.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_expiry_date-2.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes-2.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes-2.snap
src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token-2.snap
src/tests/util/test_app.rs
src/tests/worker/snapshots/all__worker__sync_admins__sync_admins_job.snap
src/tests/worker/sync_admins.rs

This makes it slightly easier to write assertions for the emails that we are sending out. For `emails_snapshot()` the `Message-ID` and `Date` headers are automatically removed and the emails are then concatenated with a separator to work directly with the `assert_snapshot!()` macro from `insta`.

tests: Extract `TestApp::emails()` and `TestApp::emails_snapshot()` fns

---

Cargo.toml
src/lib.rs
src/tests/util/test_app.rs

Cleans up the bad comment formatting I introduced in https://github.com/rust-lang/crates.io/pull/9322, and enables a [rustdoc lint] to try and catch repeats in the future.
[rustdoc lint]: https://doc.rust-lang.org/rustdoc/lints.html#unescaped_backticks
---
* ci: lint for broken inline code / backticks (559b51b18)
Enables the rustdoc "unescaped_backticks" lint[1] at warn level.
Unfortunately this only covers "prod" code, so it doesn't catch the
actual broken backticks in the test code!
[1]: https://doc.rust-lang.org/rustdoc/lints.html#unescaped_backticks
* style: remove spurious backtick (5c34d6602)
This breaks the rustdoc rendering.

style: fix broken rustdoc comment

---

src/controllers/github/secret_scanning.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/email.rs
src/models/krate.rs
src/tests/owners.rs
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success-2.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_expiry_date-2.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes-2.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes-2.snap
src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token-2.snap
src/worker/jobs/expiry_notification.rs
src/worker/jobs/sync_admins.rs
src/worker/jobs/typosquat.rs

Before:
> Your token is about to expire
After:
> crates.io: Your API token "foo" is about to expire

Use dynamic email subjects where useful

---

src/tests/owners.rs
src/tests/snapshots/all__owners__modify_multiple_owners-2.snap
src/tests/snapshots/all__owners__modify_multiple_owners.snap
src/tests/snapshots/all__owners__new_crate_owner.snap
src/tests/util/test_app.rs

This PR adjusts the `TestApp::emails_snapshot()` fn to redact invite tokens to make the snapshots stable across reruns, and then adds a couple more email snapshot assertions to the owner invite tests.

tests/owners: Add invite email snapshot assertions

---

src/email.rs
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success-2.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_expiry_date-2.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes-2.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes-2.snap
src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token-2.snap
src/tests/snapshots/all__owners__modify_multiple_owners-2.snap
src/tests/snapshots/all__owners__modify_multiple_owners.snap
src/tests/snapshots/all__owners__new_crate_owner.snap
src/tests/worker/snapshots/all__worker__sync_admins__sync_admins_job.snap

So far we had only used `no-reply@crates.io` without a `name` in the `Mailbox`. This changes the `Mailbox` instance to use the configured `domain` as the name, which means that users will see e.g. "crates.io" as the sender instead of "no-reply@crates.io".

email: Change `from` to `crates.io <no-reply@crates.io>`

---

app/styles/application.module.css

Fixes #9330 
In dark mode, `color: initial` was causing it to revert to the browser default of black which is too similar to the dark gray background.
Now links without href will use `color: unset` so it acts as if the text color is not changed from previous context, which seems to be the original intent of setting `color: initial`.

Fix links without href being hard to read on dark theme

---

src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate-4.snap
src/tests/snapshots/all__owners__new_crate_owner-2.snap
src/tests/snapshots/all__owners__new_crate_owner.snap
src/tests/snapshots/all__team__publish_owned.snap

These were caused by a conflict between #9342 and #9341. Should've rebased first... 🙈

Fix broken snapshots

---

src/worker/jobs/send_publish_notifications.rs

This can be used to give us a bit more insight into how many emails we are sending out and whether any of them are failing to get sent.

jobs/send_publish_notifications: Add logging calls

---

src/worker/jobs/send_publish_notifications.rs

No need for spawning a worker thread if we don't have any emails to send...

jobs/send_publish_notifications: Skip `spawn_blocking()` call if no valid recipients are found

---

src/tests/snapshots/all__dump_db__sql_scripts@export.sql.snap
src/worker/jobs/dump_db/dump-db.toml

We are regularly exporting the version downloads to S3 these days, so we don't need to actively filter the data anymore when preparing the database dump.

dump-db: Remove `version_downloads` export filter

---

src/tests/routes/users/update.rs

The comment is inaccurate at this point. Our frontend only sends the `email` field, without the rest.

tests/users/update: Remove obsolete parts of the payload

---

src/controllers/krate/owners.rs
src/models/krate.rs
src/tests/owners.rs

This PR pulls out the non-database concerns from `Crate::owner_add()`, moving them to the controller instead.
This gives the controller the responsibility of generating API responses and emails, giving it better visibility into what the model call did.
Part of https://github.com/rust-lang/crates.io/issues/2639
---
* refactor: separate Crate::owner_add model concerns (f38edb075)
This separates out the concerns of interacting with the database via the
Crate model, moving management of invites (emailing, response
generation, what is considered success) to the controller.
This will simplify future work on rust-lang/crates.io#2639 by allowing
the controller to inspect the result of the owner_add() call to see if
an invite was generated, or already existed without having to peek at
strings.
* …

refactor: separate `Crate::owner_add` model concerns

---

src/controllers/user.rs
src/controllers/user/me.rs
src/controllers/user/update.rs
src/models/user.rs
src/router.rs

This makes the code slightly easier to find, since these endpoints are unrelated to the ones in the `/me` namespace.

controllers/user: Move `PUT /user/:user_id` endpoints to a dedicated module

---

src/controllers/user/update.rs
src/tests/routes/users/update.rs

... instead of `BytesRequest` and manual `serde_json::from_slice()`.
This changes the returned error message, but since the error now has more information that before I'd say that's a good thing :D

user/update: Use `axum::Json` extractor

---

src/admin/delete_crate.rs
src/storage.rs
src/worker/jobs/rss/sync_crate_feed.rs

We don't need ownership of the `String`, we can work with string slices instead. This removes a couple of unnecessary `.clone()` calls.

FeedId: Remove unnecessary allocations

---

crates/crates_io_smoke_test/src/cargo.rs
crates/crates_io_smoke_test/src/git.rs
crates/crates_io_smoke_test/src/main.rs

This is a workaround for https://github.com/rust-lang/cargo/issues/14354, which currently prevents us from running our smoke tests.
cargo currently (Rust 1.81) crashes when `cargo publish` (or `cargo package`) is used on a git repository that has no commits yet. Since that is the setup we had been using for our smoke tests we are currently running into this issue. The solution in this PR runs `git add --all` and `git commit` as part of creating our dummy project, which resolves the problem on our end. As a nice bonus, this allows us to remove the `--allow-dirty` argument from the `cargo publish` call, since we have now committed all of our changes.

smoke_test: Run `git commit` to work around cargo bug

---

crates/crates_io_smoke_test/src/git.rs
crates/crates_io_smoke_test/src/main.rs

On GitHub Actions the smoke test currently fails with:
```
Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
```
This change adds the necessary git commands to our setup to hopefully make the `git commit` call succeed now.
Related:
- #9405

smoke_test: Set git username and email before committing

---

app/controllers/settings/tokens/new.js
app/templates/settings/tokens/new.hbs
e2e/routes/settings/tokens/new.spec.ts
tests/routes/settings/tokens/new-test.js

Now that we have token expiration warning emails and an easy way to create a new token based on the settings of an existing one, we can finally change the default value of this setting to a slightly more secure value.
Resolves https://github.com/rust-lang/crates.io/issues/6664

Change default API token expiration to 90 days

---

src/tests/krate/publish/snapshots/all__krate__publish__links__crate_with_links_field-2.snap
src/tests/krate/publish/snapshots/all__krate__publish__manifest__boolean_readme-2.snap
src/tests/krate/publish/snapshots/all__krate__publish__manifest__lib_and_bin_crate-2.snap
src/tests/routes/crates/snapshots/all__routes__crates__read__show.snap
src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__prerelease_versions_not_included_in_reverse_dependencies.snap
src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies.snap
src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_includes_published_by_user_when_present.snap
src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_query_supports_u64_version_number_parts.snap
src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_when_old_version_doesnt_depend_but_new_does.snap
src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__yanked_versions_not_included_in_reverse_dependencies.snap
src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__list__versions.snap
src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_semver_no_published_by.snap
src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_version.snap
src/views.rs

This field can currently only be set directly in the database, but introducing it in a dedicated commit/PR makes the diff of the commit/PR that introduces the update API much more manageable. This PR was extracted from the PR linked below :)
/cc @Rustin170506 
Related:
- #9193
- https://github.com/rust-lang/crates.io/pull/9423

Add `yank_message` field to API version responses

---

app/styles/settings/tokens/new.module.css
app/templates/settings/tokens/new.hbs

The text should not go under the select, this PR fixes it:
r? @Turbo87

Fix display for text in new token page

---

app/components/footer.hbs

Our Zulip channel has a lot more activity than our X/Twitter account, so let's move it up a bit to reflect the order of importance.

footer: Move Zulip link above X/Twitter

---

src/controllers/krate/search.rs
src/tests/routes/crates/list.rs
src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes-2.snap
src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes-3.snap
src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes-4.snap
src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes-5.snap
src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes.snap

[PostgreSQL has an unusual definition of `UTF8` that doesn't allow for null bytes][null-bytes], even though they are technically valid UTF-8 by any other definition (including Rust's `str` type). Sending a crate search request that includes a null byte will eventually result in a database error anyway, but let's save Sentry the trouble and just 400 out early.
I did a quick audit of other places that we use query parameters and don't see any other code paths where we use a string directly as a query parameter, but I won't pretend this was a super detailed survey. (Fun fact: I can actually see the power usage for my laptop increase on my fancy new charger when I hit "show references" on the `query` method in `RequestUtils`.)
Fixes #9444.
[null-bytes]: …

search: check for null bytes before querying

---

src/config/server.rs
src/tests/all.rs
src/tests/cors.rs
src/tests/util/mock_request.rs

This PR adds a few basic tests for our `verify_origin()` implementation, which was essentially untested up until now...

Add CORS tests

---

src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate.snap
src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate_twice.snap
src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate_weird_version.snap
src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate_with_token.snap
src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_1.snap
src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_2.snap
src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_3.snap
src/tests/krate/publish/snapshots/all__krate__publish__categories__good_categories.snap
src/tests/krate/publish/snapshots/all__krate__publish__keywords__good_keywords.snap
src/tests/krate/publish/snapshots/all__krate__publish__manifest__boolean_readme.snap
src/tests/krate/publish/snapshots/all__krate__publish__max_size__tarball_between_default_axum_limit_and_max_upload_size.snap
src/tests/krate/publish/snapshots/all__krate__publish__readme__new_krate_with_empty_readme.snap
src/tests/krate/publish/snapshots/all__krate__publish__readme__new_krate_with_readme.snap
src/tests/krate/publish/snapshots/all__krate__publish__readme__new_krate_with_readme_and_plus_version.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_expiry_date.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes.snap
src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__list__list_tokens.snap
src/tests/snapshots/all__github_secret_scanning__github_secret_alert_for_revoked_token.snap
src/tests/snapshots/all__github_secret_scanning__github_secret_alert_for_unknown_token.snap
src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token.snap
src/tests/snapshots/all__read_only_mode__cannot_hit_endpoint_which_writes_db_in_read_only_mode.snap
src/tests/snapshots/all__server__user_agent_is_required-2.snap
src/tests/snapshots/all__server__user_agent_is_required.snap

Not sure why `insta` isn't doing this automatically, but I guess we can do that ourselves...

insta: Update outdated `expression` fields in snapshots

---

src/admin/delete_crate.rs

This makes it easier to see at a glance which crate a log message belongs to. tracing fields are useful too, but in this case it makes more sense to have the name directly in the log message.

admin/delete_crate: Improve logging output

---

app/templates/policies/index.hbs

This PR implements https://github.com/rust-lang/rfcs/pull/3646. For some reason I thought this had already been implemented, but I just stumbled upon that section in the policies and was surprised that it was still in there... 😅

Change crates.io policy to not offer crate transfer mediation

---

app/components/crate-sidebar.hbs
app/components/footer.hbs
app/components/footer.js
app/components/support/crate-report-form.hbs
app/components/support/crate-report-form.js
app/components/support/crate-report-form.module.css
app/controllers/support.js
app/router.js
app/routes/support.js
app/services/pristine-query.js
app/styles/support.module.css
app/templates/support.hbs
e2e/acceptance/support.spec.ts
e2e/routes/support.spec.ts
playwright.config.ts
tests/acceptance/support-test.js
tests/routes/support-test.js

This PR adds a support page that allows user to select a support type from a list and fill in required information. It also moves "Email Support" from the footer to the support page.
The support page is inspired by npm's support page[^1]. When a user clicks the "report violation" link, a report form will be displayed. The user must input a crate name, select reasons, and provide detailed information (required when "other" is chosen) before submitting. The name field in the report form should be automatically filled when navigating from the report button in the `CrateSidebar`.
Related #9496 . 
Closes #9478 .
[^1]: https://www.npmjs.com/support

Add a support page

---

triagebot.toml

This only enables issue transfers within the rust-lang org, since that is all we currently need/want.
Related:
- https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/transferring.20issues.20not.20possible
- https://github.com/rust-lang/team/pull/1568

Add `triagebot` config file

---

src/util/tracing.rs

... because they are very verbose by default 😅

tracing: Disable `tokio_postgres` debug logs for tests

---

src/controllers/token.rs
src/tests/routes/me/tokens/create.rs

The only reason for using `BytesRequest` is to provide a custom error message, but I question whether that is actually that useful here...

controllers/token: Replace `BytesRequest` with `Json` extractor

---

src/admin/delete_crate.rs
src/worker/jobs/delete_crate.rs
src/worker/jobs/mod.rs
src/worker/mod.rs

This background job can later be reused to implement https://rust-lang.github.io/rfcs/3660-crates-io-crate-deletions.html
Related:
- https://github.com/rust-lang/crates.io/issues/9352

Extract `DeleteCrateFromStorage` background job

---

src/controllers/token.rs

There is no need to spin up a worker thread for basic data validation.

controllers/token: Move `name` check outside of `spawn_blocking()` callback

---

docs/FRONTEND.md

According to https://github.com/rust-lang/crates.io/blob/main/docs/ARCHITECTURE.md#frontend---emberjs, the frontend source directory should be `app`.

Correct frontend source dir

---

src/models.rs
src/models/feature.rs
src/models/krate.rs
src/models/snapshots/crates_io__models__feature__tests__split_features_clap.snap
src/models/version.rs

Fixes https://github.com/rust-lang/crates.io/issues/6135. Closes https://github.com/rust-lang/crates.io/pull/6168.
Compared to https://github.com/rust-lang/crates.io/pull/6168, this PR implements the fix in a way that features depending on newer syntax are recursively moved to `features2` instead of moving them all unconditionally.
Probably best reviewed commit-by-commit :)
/cc @rust-lang/cargo

Move `features` to `feature2` that depend on features that use new feature syntax

---

src/admin/enqueue_job.rs

https://github.com/rust-lang/crates.io/pull/9551 slightly changed how `features` are serialized in the index. We know about a couple of cases that we want to fix, so this PR adds an option for us to manually trigger an index sync.

admin/enqueue_job: Add `sync_to_git/sparse_index` subcommands

---

src/bin/monitor.rs
src/db.rs

This (partially) removes the need for us to use a blocking `reqwest` client, which will be refactored in a follow-up PR.

bin/monitor: Convert to async

---

src/admin/default_versions.rs
src/admin/delete_crate.rs
src/admin/delete_version.rs
src/admin/enqueue_job.rs
src/admin/migrate.rs
src/admin/populate.rs
src/admin/render_readmes.rs
src/admin/test_pagerduty.rs
src/admin/transfer_crates.rs
src/admin/upload_index.rs
src/admin/verify_token.rs
src/admin/yank_version.rs
src/bin/crates-admin.rs

This makes it easier to use async-only APIs in the admin tools and convert more functions to use `diesel_async` internally.

bin/crates-admin: Convert to async

---

src/admin/on_call.rs
src/admin/test_pagerduty.rs
src/bin/monitor.rs

One less thing using `reqwest::blocking` 🎉

admin/on_call: Convert `Event::send()` to async fn

---

src/admin/transfer_crates.rs

There is only a single write query in this code path, so the transaction is somewhat unnecessary. This also simplifies the confirmation code a little bit since it doesn't have to rely on `exit(0)` anymore.

admin/transfer_crates: Remove unnecessary database transaction

---

src/admin/delete_crate.rs
src/admin/delete_version.rs
src/admin/dialoguer.rs
src/admin/transfer_crates.rs
src/admin/upload_index.rs
src/admin/yank_version.rs

There is not much point in using `.unwrap()` when all callers can easily use the `?` operator...

admin/dialoguer: Remove `.unwrap()` call from `confirm()` fn

---

src/admin/populate.rs

... because we want to reduce our usage of `spawn_blocking()`

admin/populate: Convert to async

---

src/admin/delete_version.rs
src/admin/dialoguer.rs

This PR migrates some of the code in the `admin/delete_version` module to use async/await instead of `spawn_blocking()` to eventually make it fully async.

admin/delete_version: Reduce `spawn_blocking()` usage

---

src/controllers/version/metadata.rs

This feels a bit easier to read to me. @Rustin170506 what do you think?

controllers/version/metadata: Simplify `validate_yank_update()` fn

---

src/models/default_versions.rs

The rest of the module is using `impl Conn` instead of the concrete `PgConnection` type, so this function should probably use the same...

models/default_versions: Fix `conn` argument type

---

src/admin/transfer_crates.rs

similar to https://github.com/rust-lang/crates.io/pull/9598

admin/transfer_crates: Replace `spawn_blocking()` with `diesel_async` usage

---

Cargo.lock
crates/crates_io_worker/Cargo.toml
crates/crates_io_worker/src/background_job.rs
crates/crates_io_worker/tests/runner.rs

This flag can be set when implementing background jobs to automatically deduplicate jobs when they are enqueued. If an unstarted job already exists in the queue the `enqueue()` fn will return `Ok(None)` instead of the job ID.
This should allow us to get rid of `enqueue_sync_to_index()` as a special case and make the same functionality available to other jobs as well.

worker: Add `DEDUPLICATED` flag to the `BackgroundJob` trait

---

src/worker/jobs/archive_version_downloads.rs
src/worker/jobs/daily_db_maintenance.rs
src/worker/jobs/delete_crate.rs
src/worker/jobs/downloads/clean_processed_log_files.rs
src/worker/jobs/downloads/process_log.rs
src/worker/jobs/downloads/update_metadata.rs
src/worker/jobs/dump_db.rs
src/worker/jobs/expiry_notification.rs
src/worker/jobs/index/squash.rs
src/worker/jobs/index/sync.rs
src/worker/jobs/index_version_downloads_archive/mod.rs
src/worker/jobs/rss/sync_crate_feed.rs
src/worker/jobs/rss/sync_crates_feed.rs
src/worker/jobs/rss/sync_updates_feed.rs
src/worker/jobs/send_publish_notifications.rs
src/worker/jobs/sync_admins.rs
src/worker/jobs/typosquat.rs
src/worker/jobs/update_default_version.rs

Most of our background jobs don't need to be enqueued multiple times if there is already a similar one in the queue. This commit changes most of the jobs to use the new `DEDUPLICATED` flag on the `BackgroundJob` impl.

worker/jobs: Use `DEDUPLICATED` for jobs where it makes sense

---

crates/crates_io_worker/src/background_job.rs

This reduces the amount of code that needs to be compiled for each `BackgroundJob` impl, since these inner `enqueue()` fns are not using generics.

worker: Extract `enqueue_simple/deduplicated()` fns

---

Cargo.lock
crates/crates_io_cdn_logs/Cargo.toml

Reverts rust-lang/crates.io#9622. Fixes https://github.com/rust-lang/crates.io/issues/9638.

Revert "Update Rust crate async-compression to v0.4.14"

---

Cargo.toml

This is not actually used anywhere anymore...

Remove `slow-tests` feature

---

Cargo.lock
Cargo.toml

It looks like we are not actually using this dependency anymore :)

Remove unused `scheduled-thread-pool` dependency

---

src/worker/jobs/rss/sync_crate_feed.rs
src/worker/jobs/rss/sync_crates_feed.rs
src/worker/jobs/rss/sync_updates_feed.rs

... and use `diesel-async` queries directly instead.

worker/jobs/rss: Remove `spawn_blocking()` usage

---

crates/crates_io_worker/src/background_job.rs
src/admin/delete_crate.rs
src/admin/enqueue_job.rs

This PR implements an async variant of the `BackgroundJob::enqueue()` fn, that can be used inside other async fns, without the need to use `spawn_blocking()`.
I'm not a fan of the (temporary) code duplication, but due to the `diesel` type madness I wasn't successful in extracting the common parts into shared fns.

worker: Implement async `enqueue()` fn

---

src/tests/models/krate.rs

We don't need to spin up a full-blown app for this test, when all we need is a simple database connection.

tests/models/krate: Replace `TestApp` usage with `TestDatabase`

---

Cargo.lock
crates/crates_io_index/Cargo.toml
crates/crates_io_index/data.rs
crates/crates_io_index/features.rs
crates/crates_io_index/lib.rs
crates/crates_io_index/snapshots/crates_io_index__features__tests__split_features_clap.snap
src/models.rs
src/models/feature.rs
src/models/krate.rs
src/models/version.rs

This fn is only relevant when writing out index files, so we can move it into our dedicated `crates_io_index` crate. This makes it faster to compile and test, since that crate compiles a lot faster than `crates_io` itself 😅

Move `split_features()` fn into `crates_io_index` crate

---

src/index.rs
src/worker/jobs/index/sync.rs

This reduces the amount of `spawn_blocking()` calls in the index sync background jobs, since the queries are now handled by `diesel-async` :)

index: Convert `get_index_data()` fn to async

---

src/worker/jobs/daily_db_maintenance.rs

We can use `diesel-async` instead 🎉

worker/jobs/daily_db_maintenance: Remove `spawn_blocking()` usage

---

src/worker/jobs/sync_admins.rs

Unfortunately we can't completely avoid it yet, since our email sending code is still synchronous, but we'll get there eventually...
(best reviewed with "hide whitespace changes" 😉)

worker/jobs/sync_admins: Reduce `spawn_blocking()` usage

---

src/admin/yank_version.rs

similar to https://github.com/rust-lang/crates.io/pull/9619, but now that background jobs can be enqueued async, this should actually work 😅

admin/yank_version: Remove `spawn_blocking()` usage

---

src/lib.rs
src/tests/mod.rs
src/tests/util.rs
src/tests/util/github.rs
src/typosquat/test_util.rs

... and use it where it makes sense :)

Extract `tests::util::github::next_gh_id()` fn

---

src/tests/util/test_app.rs

For tests we don't need the "upsert" behavior of `create_or_update()` and since we're passing in `None` we don't need the email sending behavior either, so let's simplify this to only insert the user in the database and nothing else :)

tests/util/test_app: Simplify `db_new_user()` fn

---

src/typosquat/database.rs
src/typosquat/test_util.rs
src/worker/jobs/typosquat.rs

We aren't actually using the `Emails` instance in this test suite, so we may as well remove it and simplify the `Faker` struct to be a module with regular functions instead :)
/cc @LawnGnome

typosquat/test_util: Simplify `Faker`

---

src/db.rs

The `enqueue-job` admin tool has been silently failing on our staging environment since #9632 was merged. This PR fixes it by reusing our `establish_async_connection()` fn, which sets up the TLS configuration correctly.
It is a bit unforunate that this wasn't caught earlier though. We could potentially look into using TLS for the database connection on CI, but we'd also need to write tests for all of the admin tools (which we should do anyway...).
It is also a bit surprising that the Heroku Scheduler, which regularly uses this admin tool to enqueue regular tasks, didn't report any warnings about the tool crashing all the time, but I guess there is not much we can do on that front :-/

Fix "unconfigured TLS" panic in `db::oneoff_async_connection()` fn

---

crates/crates_io_worker/src/worker.rs

Adding the error details as a structured logging field isn't actually as useful. Let's revert this back to regular stringification.

worker: Adjust "Failed to run job" error logging

---

src/models/team.rs
src/typosquat/test_util.rs

For `INSERT` queries there is no need for allocations, so let's replace them with regular references.

models/team: Replace `String` with `&str` for `NewTeam` struct fields

---

src/controllers/krate/publish.rs
src/models/version.rs
src/tests/builders/version.rs

models/version: Replace `String` with `&str` for `NewVersion` struct fields

---

src/models/version.rs
src/tests/builders/version.rs

`None` values are treated as using the default column value by `diesel` by default, and `#[builder(default)]` initializes these fields as `None`. This enables us to only overwrite these columns in tests, while the production code stays the same. This then enables us to get rid of two additional queries in the `VersionBuilder` test helper :)

tests/builders/version: Simplify code by adding fields to `NewVersion` struct

---

Cargo.lock
Cargo.toml
src/util/tracing.rs

This allows us to flatten the span fields, which makes them a lot easier to use within Datadog.

tracing: Use `json-subscriber` crate for JSON logging

---

src/controllers/krate/versions.rs
src/tests/routes/crates/versions/list.rs

This PR will add `release_tracks` information to the `meta` field for paginated versions. This is necessary for pagination because it only loads a portion of versions per page, while `release_tracks` may require all sorted versions to determine their values. Therefore, we also need to calculate these on the server side.
---
Tasks:

Add `release_tracks` meta to pagination versions

---

Cargo.lock
Cargo.toml
src/bin/background-worker.rs
src/controllers/krate/publish.rs
src/models/version.rs
src/tests/builders/version.rs
src/tests/util/test_app.rs
src/typosquat/test_util.rs
src/worker/environment.rs
src/worker/jobs/downloads/update_metadata.rs

`bon` uses the type system to ensure all required fields have been set, which means that we can catch issues at compile time. The necessary attributes are also less verbose due to better defaults inside `bon`. 
The only downside I've found is that custom builder fns like `dummy_checksum()` don't appear easy to implement at the moment, which is why I've inlined the two custom builder fns that we had. (/cc @Veetaha)

Replace `derive_builder` with `bon`

---

src/models/category.rs
src/tests/krate/publish/categories.rs
src/tests/routes/categories/get.rs
src/tests/routes/categories/list.rs
src/tests/routes/category_slugs/list.rs
src/tests/routes/crates/list.rs
src/tests/routes/summary.rs

The function is only used in our test suite, the update behavior isn't actually needed there and the return value is also not used anywhere. This makes it possible to significantly simplify the function to the point where there is no point anymore to keep the function. Inlining it then also allows us to merge a couple of calls into single queries that insert multiple rows at once.

Inline `NewCategory::create_or_update()`

---

src/models/default_versions.rs

This allows us to simplify the `find_default_version()` version fn, which now only needs to iterate the slice once instead of up to three times, and it makes it possible to directly compare two `Version` instances too. This should be able to simplify https://github.com/rust-lang/crates.io/pull/9722 a little bit.

models/default_version: Implement `Ord` for `Version`

---

src/controllers/krate/publish.rs
src/models.rs
src/models/default_versions.rs

Since we will respond with the `default_version` to the client, this PR always upsert the `default_value` for publish.

`default_version` for publish

---

src/worker/jobs/index/sync.rs

We don't need to log this in a quoted way since we're using JSON output on production these days anyway

worker/jobs/index/sync: Fix `krate.name` logging

---

src/worker/jobs/archive_version_downloads.rs

There is no need for us to pass in the full database pool, when all we need is a single connection.

worker/jobs/archive_version_downloads: Simplify function arguments

---

src/tests/account_lock.rs
src/tests/github_secret_scanning.rs
src/tests/krate/publish/auth.rs
src/tests/krate/publish/basics.rs
src/tests/krate/publish/categories.rs
src/tests/krate/publish/emails.rs
src/tests/krate/publish/rate_limit.rs
src/tests/krate/publish/timestamps.rs
src/tests/krate/yanking.rs
src/tests/routes/categories/list.rs
src/tests/routes/category_slugs/list.rs
src/tests/routes/crates/versions/yank_unyank.rs
src/tests/routes/me/tokens/create.rs
src/tests/routes/me/tokens/delete.rs
src/tests/routes/me/tokens/delete_current.rs
src/tests/token.rs
src/tests/util/test_app.rs
src/tests/worker/git.rs
src/tests/worker/rss/sync_crate_feed.rs
src/tests/worker/rss/sync_crates_feed.rs
src/tests/worker/rss/sync_updates_feed.rs
src/tests/worker/sync_admins.rs

... at least for those where it is easily possible 😅 
Unfortunately, things like the `CrateBuilder` still make this more complicated than necessary, but we'll get to that eventually.

Migrate tests from sync to async database connection

---

src/controllers/krate/publish.rs
src/models/category.rs
src/models/keyword.rs
src/tests/builders/krate.rs
src/tests/routes/categories/get.rs
src/tests/routes/crates/list.rs
src/tests/routes/keywords/read.rs

This allows us to use these function even if we only have an id and not a full `Crate` instance.

Replace `&Crate` arguments with `crate_id: i32`

---

src/controllers/krate/metadata.rs
src/controllers/krate/search.rs
src/controllers/krate/versions.rs
src/controllers/summary.rs
src/controllers/user/me.rs
src/models/action.rs
src/models/krate.rs

This PR modifies certain functions to accept slices of references, thereby avoiding unnecessary allocations.

Avoid unnecessary allocations

---

Cargo.lock
Cargo.toml
src/admin/delete_crate.rs

admin/delete_crate: Improve crate listing

---

docker-compose.yml
package.json

We don't use the PROXY_BACKEND env variable any more.
If we don't change it, it will try to use the mock server as the backend API.

Fix the broken entrypoint for frontend service

---

src/controllers/krate/metadata.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/summary.rs
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_twice.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_twice_alt.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_weird_version.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_with_token.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__build_metadata__version_with_build_metadata@build_metadata_1.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__build_metadata__version_with_build_metadata@build_metadata_2.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__build_metadata__version_with_build_metadata@build_metadata_3.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__categories__good_categories.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__dependencies__dep_limit-2.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__keywords__good_keywords.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__links__crate_with_links_field.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__manifest__boolean_readme.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__manifest__lib_and_bin_crate.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__max_size__tarball_between_default_axum_limit_and_max_upload_size.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__readme__new_krate_with_empty_readme.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__readme__new_krate_with_readme.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__readme__new_krate_with_readme_and_plus_version.snap
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__new_name.snap
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__show_minimal.snap
src/views.rs

There are either set to `None` or `Some(vec![])` these days, but we might as well initialize them with an empty static array instead and never return `null`.

views: Remove `badges` arguments from `EncodableCrate` constructors

---

crates/crates_io_database/src/schema.rs
crates/crates_io_database_dump/src/dump-db.toml
crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
migrations/2024-10-24-133507_add-num-no-build-column/down.sql
migrations/2024-10-24-133507_add-num-no-build-column/up.sql
src/models/version.rs

This shall be filled by the following SQL script:
```sql
update versions
set num_no_build = split_part(num, '+', 1);
with duplicates as (
-- find all versions that have the same `crate_id` and `unique_num`
select crate_id, num_no_build, array_agg(num ORDER BY id) as nums
from versions
group by crate_id, num_no_build
having count(*) > 1
),
duplicates_to_update as (
-- for each group of duplicates, update all versions except the one that
-- doesn't have "build metadata", or the first one that was published if
-- all versions have "build metadata"
select crate_id, num_no_build, unnest(case when array_position(nums, num_no_build) IS NOT NULL then array_remove(nums, num_no_build) else nums[2:] end) as num
from duplicates
)
update versions
set num_no_build = duplicates_to_update.num
from …
```

database: Add `versions.num_no_build` column

---

crates/crates_io_database/src/schema.rs
migrations/2024-10-24-134209_make-unique-num-not-null/down.sql
migrations/2024-10-24-134209_make-unique-num-not-null/up.sql
src/models/default_versions.rs
src/models/version.rs
src/tests/worker/rss/sync_crate_feed.rs
src/tests/worker/rss/sync_updates_feed.rs
src/worker/jobs/archive_version_downloads.rs
src/worker/jobs/downloads/process_log.rs
src/worker/jobs/rss/sync_crate_feed.rs
src/worker/jobs/rss/sync_updates_feed.rs

This PR was extracted from https://github.com/rust-lang/crates.io/pull/9756, because it needs to be deploy separately from the other migrations in that PR.
The backfill SQL script in https://github.com/rust-lang/crates.io/pull/9766 has been run on the staging and production databases, so this should be good to go. `SELECT * FROM versions WHERE num_no_build IS NULL` returns zero rows.

database: Change `num_no_build` to be `NOT NULL`

---

crates/crates_io_database/src/schema.rs
crates/crates_io_database_dump/src/dump-db.toml
crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
migrations/2024-10-24-133507_add-num-no-build-column/down.sql
migrations/2024-10-24-133507_add-num-no-build-column/up.sql
migrations/2024-10-24-134209_make-unique-num-not-null/down.sql
migrations/2024-10-24-134209_make-unique-num-not-null/up.sql
migrations/2024-10-25-112826_make-unique-version-unique/down.sql
migrations/2024-10-25-112826_make-unique-version-unique/metadata.toml
migrations/2024-10-25-112826_make-unique-version-unique/up.sql
src/controllers/krate/publish.rs
src/models/default_versions.rs
src/models/version.rs
src/tests/worker/rss/sync_crate_feed.rs
src/tests/worker/rss/sync_updates_feed.rs
src/worker/jobs/archive_version_downloads.rs
src/worker/jobs/downloads/process_log.rs
src/worker/jobs/rss/sync_crate_feed.rs
src/worker/jobs/rss/sync_updates_feed.rs

This PR fixes a race condition in our publish endpoint. When two versions, `1.0.0+foo` and `1.0.0+bar` are published concurrently we previously could get into a situation where the "unique version number excluding build metadata" check succeeds for both, and then both versions are added to the database, when only one such version should exist.
This PR adds a new `unique` constraint on `(crate_id, num_no_build)` to prevent this from happening.
We currently have around 650 such cases still in the database though. In those cases the `num_no_build` column is adjusted to actually contain the build metadata too (see column comment).
Finally, this PR needs to be merged/deployed in multiple stages. The initial migration adds the column in a nullable way, because the SQL script to backfill the …

Fix build metadata race condition

---

src/admin/render_readmes.rs
src/controllers/krate/metadata.rs
src/controllers/krate/versions.rs
src/controllers/user/me.rs
src/index.rs
src/models.rs
src/models/category.rs
src/models/dependency.rs
src/models/keyword.rs
src/models/krate.rs
src/models/team.rs
src/models/user.rs
src/models/version.rs

With `all_columns` the field order inside the structs is very important and it is impossible to skip columns. `as_select()` solves both of these issues.

diesel: Replace `all_columns` with `as_select()`

---

.github/workflows/ci.yml

There is no need to run the backend test suite if the changes are limited to the Playwright test suite.

CI: Run only frontend jobs for changes in the `e2e` folder

---

src/controllers/category.rs
src/controllers/summary.rs
src/models/category.rs

models/category: Convert to async/await

---

src/worker/jobs/downloads/clean_processed_log_files.rs
src/worker/jobs/downloads/process_log.rs

because we have `diesel-async` now :)

worker/jobs/downloads: Remove `spawn_blocking()` usage

---

crates/crates_io_worker/src/runner.rs
crates/crates_io_worker/src/storage.rs
crates/crates_io_worker/src/worker.rs

No need for `spawn_blocking()`, we can just use `diesel-async` queries now :)

worker: Remove `spawn_blocking()` usage

---

mirage/route-handlers/crates.js
tests/mirage/crates/versions/yank/unyank-test.js
tests/mirage/crates/versions/yank/yank-test.js

This PR was partially extracted from https://github.com/rust-lang/crates.io/pull/9765 (thanks @Rustin170506!). I've added a couple of tests for the mirage implementation of these two endpoints and fixed the bugs that the tests uncovered.
Note that the mirage implementation currently does not check for crate ownership. I'm not sure yet whether the additional complexity for that case would be justified.

mirage: Fix yank/unyank route handlers

---

mirage/factories/version.js
mirage/serializers/version.js
tests/mirage/crates/get-by-id-test.js
tests/mirage/crates/reverse-dependencies-test.js
tests/mirage/crates/versions/list-test.js
tests/mirage/me/updates/list-test.js

Extracted from https://github.com/rust-lang/crates.io/pull/9765 :)
Related:
- https://github.com/rust-lang/crates.io/pull/9437
- https://github.com/rust-lang/crates.io/pull/9765

mirage: Add `yank_message` to `version` factory and serializer

---

mirage/route-handlers/crates.js
tests/adapters/crate-test.js
tests/helpers/index.js
tests/mirage/crates/add-owner-test.js
tests/models/crate-test.js
tests/models/version-test.js
tests/services/playground-test.js

The implementation of this endpoint of our dummy API had various bugs. This PR fixes most of them and adds a couple of tests for it.
Related:
- https://github.com/rust-lang/crates.io/issues/9797

mirage: Fix `PUT /api/v1/crates/:name/owners` implementation

---

app/adapters/version.js
app/models/version.js
e2e/acceptance/sudo.spec.ts
tests/acceptance/sudo-test.js

Moved to the new API before adding frontend support for the yank message.
Tested locally:
https://github.com/user-attachments/assets/bf3ce6c2-b6b5-499c-b878-5180e710fd7d

Migrate the frontend to use the new yank API

---

crates/crates_io_worker/Cargo.toml
crates/crates_io_worker/tests/runner.rs

... which allows us to get rid of the `flavor = "multi_thread"` declaration on the tests :D

worker: Migrate tests suite to async database queries

---

src/bin/crates-admin/default_versions.rs
src/bin/crates-admin/delete_crate.rs
src/bin/crates-admin/delete_version.rs
src/bin/crates-admin/enqueue_job.rs
src/bin/crates-admin/migrate.rs
src/bin/crates-admin/populate.rs
src/bin/crates-admin/render_readmes.rs
src/bin/crates-admin/transfer_crates.rs
src/bin/crates-admin/verify_token.rs
src/bin/crates-admin/yank_version.rs
src/bin/monitor.rs
src/db.rs

Those are not used anymore so we may as well make the async variant the default now :)

db: Remove unused `oneoff_connection()` fns

---

Cargo.lock
crates/crates_io_pagerduty/Cargo.toml
crates/crates_io_pagerduty/examples/test_pagerduty.rs
crates/crates_io_pagerduty/src/lib.rs
src/bin/monitor.rs

This decouples the Pagerduty implementation from the `PAGERDUTY` environment variables and allows us to fail early if they are missing.

pagerduty: Extract `PagerdutyClient` struct

---

Cargo.lock
crates/crates_io_pagerduty/Cargo.toml
crates/crates_io_pagerduty/examples/test_pagerduty.rs

This makes it possible to use CLI arguments instead, but also improves the error messages quite a bit :)

pagerduty/example: Read environment variables via `clap`

---

src/controllers/krate/metadata.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/summary.rs
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_twice.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_twice_alt.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_weird_version.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_with_token.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__build_metadata__version_with_build_metadata@build_metadata_1.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__build_metadata__version_with_build_metadata@build_metadata_2.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__build_metadata__version_with_build_metadata@build_metadata_3.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__categories__good_categories.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__dependencies__dep_limit-2.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__keywords__good_keywords.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__links__crate_with_links_field.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__manifest__boolean_readme.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__manifest__lib_and_bin_crate.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__max_size__tarball_between_default_axum_limit_and_max_upload_size.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__readme__new_krate_with_empty_readme.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__readme__new_krate_with_readme.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__readme__new_krate_with_readme_and_plus_version.snap
src/tests/routes/crates/list.rs
src/tests/routes/crates/read.rs
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__new_name.snap
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__show_all_yanked.snap
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__show_minimal.snap
src/tests/routes/summary.rs
src/views.rs

This PR expose the `yanked` field on the API. The `yanked` state is based on the `default_version`. The `default_version` can only be yanked if all other versions are also yanked and a crate should only be yanked if all of its versions are yanked.

Expose the `yanked` field on the API

---

app/components/crate-row.hbs
app/models/crate.js
app/routes/crate/dependencies.js
app/routes/crate/version.js

This PR completes the transition to `default_version` in the frontend, which was first introduced in #8484.

frontend: Migrate to use `default_version` and `yanked`

---

src/bin/crates-admin/render_readmes.rs
src/boot/categories.rs
src/controllers/crate_owner_invitation.rs
src/controllers/github/secret_scanning.rs
src/controllers/helpers/pagination.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/krate/versions.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/update.rs
src/controllers/version.rs
src/controllers/version/downloads.rs
src/models/action.rs
src/models/crate_owner_invitation.rs
src/models/default_versions.rs
src/models/keyword.rs
src/models/krate.rs
src/models/team.rs
src/models/token.rs
src/models/user.rs
src/models/version.rs
src/rate_limiter.rs
src/util/diesel.rs

This change simplifies the migration to `diesel_async`. Using
`use diesel::prelude::*` alongside `use diesel_async::RunQueryDsl` can
sometimes cause ambiguity when not all loading functions are migrated
to use `diesel_async` within a file. This can be quite annoying.
To migrate:
1. Replace `use diesel::prelude::*` with `use crate::util::diesel::prelude::*`
for files that still need to migrate.
2. Add `use diesel::RunQueryDsl` within loading functions.
3. Once all loading functions within a file have been migrated to
`diesel_async`, you can revert to using `use diesel::prelude::*`
alongside `use diesel_async::RunQueryDsl` without issues.

util/diesel: Add diesel prelude excluding `RunQueryDsl`

---

src/controllers/keyword.rs
src/models/keyword.rs

This is a follow-up PR that builds on #9850 to reduce the usage of `spawn_block()`.

controllers/keyword: Reduce `spawn_blocking()` usage

---

src/controllers/krate/metadata.rs
src/controllers/krate/search.rs
src/controllers/summary.rs
src/index.rs
src/models.rs
src/models/krate.rs

Having these "non-yanked" and "including yanked" variants is quite confusing and doesn't provide much benefit compared to using `Version::belonging_to(...)` directly...
Related:
- https://github.com/rust-lang/crates.io/pull/1459

Inline `CrateVersions` trait fns

---

src/controllers/summary.rs

If we pass in an empty array then so be it, but there seems to be no need for the boxed and mutated queries here :)

controllers/summary: Remove unnecessary `.is_empty()` conditions

---

crates/crates_io_worker/tests/runner.rs

The second `assert_none!()` in this test was occasionally failing due to a race condition. The `TestJob` that was enqueued right before this one would sometimes already be processed before we enqueue this one, leading to this one being actually enqueued instead of being deduplicated. The reason for this was that the `runner()` fn builds a `Runner` with two workers for the default queue. This commit changes the runner to only use a single worker, which avoids the race condition.

worker/tests: Fix flaky deduplication test

---

Cargo.toml
crates/crates_io_team_repo/Cargo.toml
crates/crates_io_team_repo/src/lib.rs

There is no need to derive a mock implementation for our release builds, since it won't be used. Might help ever so slightly with build times... 🤷‍♂️

team_repo: Avoid `automock` for release builds

---

app/controllers/crate/version.js
app/models/version.js
app/styles/crate/version.module.css
app/templates/crate/version.hbs
e2e/acceptance/readme-rendering.spec.ts
mirage/route-handlers/crates.js
tests/acceptance/readme-rendering-test.js
tests/mirage/crates/versions/readme-test.js

Resolves https://github.com/rust-lang/crates.io/issues/9821

Show "Retry" button for README loading errors

---

src/controllers/version.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/models/krate.rs

This PR converts`version_and_crate()` and related fns to async, and the next one will convert `AuthCheck::check()` and related fns. The conversion order is mostly based on the order in which they occur in `spawn_blocking()`.

controllers/version: Convert `version_and_crate()` to async

---

src/controllers/version/metadata.rs
src/models/version.rs

because we can use `diesel_async` queries instead :)

Remove `spawn_blocking()` call from `GET /crates/:crate_id/:version/dependencies` endpoint

---

src/bin/crates-admin/render_readmes.rs
src/models/version.rs
src/tests/version.rs
src/worker/jobs/readmes.rs

... which allows us to remove a `spawn_blocking()` call from the `RenderAndUploadReadme` background job :)

models/version: Convert `record_readme_rendering()` to async fn

---

src/controllers/version/metadata.rs
src/models/version.rs

If there is an error in this query we shouldn't silently fail and return `None`, we should propagate the error instead and let the caller decide what to do.

models/version: Fix `published_by()` error handling

---

src/auth.rs
src/controllers/crate_owner_invitation.rs
src/controllers/krate/follow.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/update.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/models/token.rs
src/models/user.rs

This PR focuses on converting the `check()` and related implementations to async, so there might be `spawn_blocking()`  fns in controllers that can be removed. However, I expect these changes to be made in a separate PR :)

auth: Convert `check()` and related blocking fns to async

---

.buildpacks

This fixes the current deployment failures by using the `amd64` instead of `i386` build of the `jq` tool. It also updated `jq` from 1.7 to 1.7.1.
see https://github.com/Turbo87/heroku-buildpack-crates-io/compare/57008548b11cecb39f28d2bb7cf3b104a301e751...5005fb13c1a782285302e7d40712f746438a99d6

Heroku: Update buildpack

---

src/controllers/krate/follow.rs
src/controllers/token.rs
src/controllers/user/me.rs

This is a follow-up PR to #9872 that reduce/remove `spawn_blocking()` usage :)

Reduce `spawn_blocking()` usage

---

src/tests/user.rs

This patterns was from a time where there was an `email` field that was supposed to be overridden, but that is no longer the case and we can simplify this a bit :D

tests/user: Simplify `new_user()` usage

---

src/bin/crates-admin/render_readmes.rs

This reverts commit dda300ebb8ef8b3026c4b42d93593c9e6a0b1c49.
The relevant code was used inside a `std::thread::spawn()` block, which currently does not have an attached tokio runtime, which means that `Handle::current()` panics in this case. Reverting the commit fixes the issue for now, but this should probably be refactored to use tokio tasks anyway...

Revert "admin/render_readmes: Remove redundant tokio runtime"

---

src/controllers/crate_owner_invitation.rs
src/models/crate_owner_invitation.rs

This PR converts most functions in the `crate_owner_invitation` model to async/await and removes unnecessary `spawn_blocking()` usage in the controller. The `create` function is left unconverted due to additional work required, which I plan to address in a future PR :)

models/crate_owner_invitation: Convert to async/await

---

Cargo.toml
src/bin/crates-admin/render_readmes.rs

This should be our last place that still used a sync `reqwest` client :)
I tested this locally by hardcoding `cdn_prefix: Some("https://static.crates.io".to_string())` and then running `cargo run --bin crates-admin render-readmes --crate mustache --page-size 5`. seemed to work fine from what I could tell.

admin/render_readmes: Use async `reqwest` client and `diesel-async` queries

---

app/routes/team.js
app/routes/user.js
e2e/routes/team.spec.ts
e2e/routes/user.spec.ts
tests/routes/team-test.js
tests/routes/user-test.js

This matches the implementation that we already use for crates, versions, keyword, and categories :)

Show error page if team or user is missing or fails to load

---

src/controllers/krate/owners.rs
src/models/krate.rs

This is a clone of the `owners()` fn, and allows us to get rid of yet another `spawn_blocking()` block

models/krate: Add `async_owners()` fn

---

src/controllers/krate/owners.rs
src/models/team.rs

This converts `Team::owning()` to an async fn, allowing us to remove the relevant `spawn_blocking()` usage in the controller.

controllers/krate/owners: Remove `spawn_blocking()` from `GET /crates/:crate_id/owner_team` endpoint

---

src/bin/crates-admin/delete_crate.rs

TIL that `sql()` can be used in combination with `#[diesel(select_expression = ...)]` 😁

admin/delete_crate: Simplify SQL query code by deriving `Queryable` and `Selectable`

---

src/bin/crates-admin/upload_index.rs

Only the initial repository cloning and file listing operations are synchronous, but the rest of the code can live outside of `spawn_blocking()` these days.
`repo.head_oid()` is arguably also synchronous, but it is a fast enough operation to not matter too much for an admin tool :)

admin/upload_index: Reduce `spawn_blocking()` scope

---

src/bin/crates-admin/delete_crate.rs
src/bin/crates-admin/delete_version.rs
src/bin/crates-admin/dialoguer.rs
src/bin/crates-admin/transfer_crates.rs
src/bin/crates-admin/upload_index.rs
src/bin/crates-admin/yank_version.rs

The sync variant isn't used anywhere anymore, so we might as well make it private and only treat it as an "inner function" :)

admin/dialoguer: Rename `async_confirm()` fn to `confirm()`

---

src/controllers/krate/metadata.rs
src/models/action.rs
src/models/krate.rs

... because it gets rid of yet another `spawn_blocking()` call 😁

controllers/krate/metadata: Migrate reverse dependencies endpoint to `diesel-async`

---

src/bin/crates-admin/migrate.rs
src/boot/categories.rs
src/tests/categories.rs

... to move more code out of `spawn_blocking()` blocks :)

boot/categories: Migrate `sync_with_connection()` to `diesel-async` queries

---

Cargo.lock
Cargo.toml
crates/crates_io_github/Cargo.toml
crates/crates_io_github/src/lib.rs
src/tests/github_secret_scanning.rs
src/tests/util/github.rs
src/tests/util/test_app.rs

This makes our mocking code for the `GitHubClient` a lot more flexible compared to only having a single source of stub data.

github: Use mockall to generate `MockGitHubClient` implementation

---

src/tests/issues/issue1205.rs
src/tests/mod.rs
src/tests/routes/crates/owners/add.rs
src/tests/routes/crates/owners/remove.rs
src/tests/util.rs

These API endpoints can also be used with cookie authentication, so it doesn't make much sense to restrict the helper function to API token authentication :)

tests/util: Move `add/remove_owner()` fns into `RequestHelper` trait

---

src/models/krate.rs
src/models/owner.rs
src/tests/issues/issue1205.rs
src/tests/issues/issue2736.rs
src/tests/issues/mod.rs
src/tests/routes/crates/owners/remove.rs
src/tests/team.rs

When users or teams on GitHub are deleted and recreated they might exist multiple times within our own database with the same `login`. When owners are deleted, only the newest matching `login` is considered for deletion though, which makes it impossible to delete older users/teams.
This commit fixes the problem by deleting **all** owners with a matching `login` instead.
Unfortunately, `diesel` does not support `UPDATE` queries with `JOINs`, so this has to be a "raw" SQL query with bindings instead…
Fixes #2736, ~~and AFAICT also fixes https://github.com/rust-lang/crates.io/issues/1205~~
Related:
- https://github.com/rust-lang/crates.io/issues/1205
- #2736
- https://github.com/rust-lang/crates.io/issues/1818
- https://github.com/rust-lang/crates.io/issues/1512
- …

Fix owner removal for duplicate logins

---

src/models/user.rs
src/worker/jobs/expiry_notification.rs

less `spawn_blocking()`, more better!

worker/jobs/expiry_notification: Migrate to `diesel-async` queries

---

src/controllers/github/secret_scanning.rs
src/models/user.rs

less `spawn_blocking()`, more better!

controllers/github/secret_scanning: Migrate to `diesel-async` queries

---

src/worker/jobs/send_publish_notifications.rs

less `spawn_blocking()`, more better!

worker/jobs/send_publish_notifications: Migrate to `Emails::async_send()`

---

src/controllers/user/session.rs
src/util/diesel.rs
src/util/errors.rs
src/util/errors/json.rs

First converting a `diesel::result::Error` to a `BoxedAppError` only to then rely on downcasting to check the content of the original error seems a bit over-complicated. This PR replaces the check with a much simpler `is_read_only_error()` fn and then gets rid of the `ReadOnlyMode` struct in favor of another `custom()` error helper call.

Remove `ReadOnlyMode` error struct

---

src/rate_limiter.rs
src/tests/owners.rs
src/tests/routes/crates/list.rs
src/tests/routes/me/email_notifications.rs
src/tests/routes/users/read.rs
src/worker/jobs/downloads/update_metadata.rs

There is no need for an "upsert" operation here since we know that the database is in a clean state in our tests. Additionally, this drops the need for the `Emails` implementation, since all we want is a user in the database, but without any email address confirmation emails being sent out.
The motivation for this change is that it makes it easier to convert the `NewUser::create_or_update()` fn to async later, without having to adjust that many callers that don't need the extra behavior of that function.

tests: Avoid `NewUser::create_or_update()` calls

---

src/controllers/user/session.rs
src/models/user.rs
src/tests/user.rs
src/worker/jobs/expiry_notification.rs

less blocking worker threads, more async :)

controllers/user/session: Remove `spawn_blocking()` usage

---

Cargo.lock
Cargo.toml
src/tests/worker/rss/snapshots/crates_io__tests__worker__rss__sync_crates_feed__sync_crates_feed-2.snap
src/tests/worker/rss/snapshots/crates_io__tests__worker__rss__sync_updates_feed__sync_updates_feed-2.snap
src/tests/worker/rss/sync_crates_feed.rs
src/tests/worker/rss/sync_updates_feed.rs
src/worker/jobs/rss/sync_crates_feed.rs
src/worker/jobs/rss/sync_updates_feed.rs

XML tags inside `CDATA` sections don't need to be escaped, so this explicit escaping step led to an unnecessary duplicate escaping being applied.
Related:
- https://github.com/rust-syndication/rss/issues/167#issuecomment-2480138799

rss: Remove explicit/duplicate XML escaping

---

src/controllers/user/snapshots/crates_io__controllers__user__resend__tests__happy_path-2.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate-4.snap
src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_success-2.snap
src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_expiry_date-2.snap
src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_null_scopes-2.snap
src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_scopes-2.snap
src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-3.snap
src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-4.snap
src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-6.snap
src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe.snap
src/tests/snapshots/crates_io__tests__github_secret_scanning__github_secret_alert_revokes_token-2.snap
src/tests/snapshots/crates_io__tests__owners__modify_multiple_owners-6.snap
src/tests/snapshots/crates_io__tests__owners__modify_multiple_owners.snap
src/tests/snapshots/crates_io__tests__owners__new_crate_owner-2.snap
src/tests/snapshots/crates_io__tests__owners__new_crate_owner.snap
src/tests/snapshots/crates_io__tests__team__publish_owned.snap
src/tests/worker/rss/snapshots/crates_io__tests__worker__rss__sync_crate_feed__sync_crate_feed-2.snap
src/tests/worker/snapshots/crates_io__tests__worker__sync_admins__sync_admins_job.snap
src/worker/jobs/archive_version_downloads.rs
src/worker/jobs/downloads/process_log.rs
src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crate_feed__tests__load_version_updates-2.snap
src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crate_feed__tests__load_version_updates-3.snap
src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crate_feed__tests__load_version_updates.snap
src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_updates_feed__tests__load_version_updates-2.snap
src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_updates_feed__tests__load_version_updates-3.snap
src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_updates_feed__tests__load_version_updates.snap

Similar to https://github.com/rust-lang/crates.io/pull/9929, but this time mostly because I forgot to update the snapshots in #9961 😅 
Related:
- #9929 
- #9961

insta: Update snapshots

---

src/tests/util/github.rs

`gh_id = 0` has a special meaning within our database. Depending on the order of the tests we could sometimes see tests failing because the initial user was created with `gh_id = 0`. This commit fixes the flakiness by starting the `gh_id` values at 1 instead.
and yes, I thought I was going insane... 🙈

tests/util/github: Fix test flakyness

---

src/auth.rs
src/bin/crates-admin/verify_token.rs
src/models/token.rs
src/tests/user.rs

Everything is using the async variant now, so lets get rid of the sync one  🎉

models/token: Remove sync `find_by_api_token()` fn

---

src/typosquat/cache.rs
src/typosquat/database.rs
src/worker/environment.rs
src/worker/jobs/typosquat.rs

... to get rid of these pesky sync database connections.
I wish it would've been possible to split this into multiple commits, but... no 😅

typosquat: Asyncify all the things

---

src/auth.rs
src/bin/crates-admin/verify_token.rs
src/controllers/github/secret_scanning.rs
src/models/user.rs
src/tests/user.rs
src/worker/jobs/expiry_notification.rs

Everything is using the async variant now, so lets get rid of the sync one 🎉

models/user: Remove unused sync `find()` fn

---

src/models/team.rs
src/tests/mod.rs
src/tests/team.rs
src/typosquat/test_util.rs

Having two `i32` arguments in the `new()` fn was a bit dangerous and could easily lead to someone unintentionally swapping the values. This commit changes the `NewTeam` construction to use the builder pattern with named fns instead to avoid the potential confusion.

models/team: Replace `NewTeam::new()` fn with `Builder` pattern

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css
app/components/version-list/row.hbs
app/components/version-list/row.module.css
app/models/version.js
app/styles/application.module.css

This PR adjusts the MSRV tooltip to also show the required Rust Edition:
Resolves https://github.com/rust-lang/crates.io/issues/1541
Related:
- https://github.com/rust-lang/crates.io/issues/1541
- https://github.com/rust-lang/crates.io/pull/9932
- https://github.com/rust-lang/crates.io/pull/9996

Show Rust Edition requirement if set

---

src/controllers/krate/publish.rs
src/controllers/version/metadata.rs
src/models.rs
src/models/action.rs

This avoids potential bugs from confusing the `version_id: i32` and `user_id: i32` arguments in the `insert_version_owner_action()` fn.

models/action: Extract `NewVersionOwnerAction` struct

---

src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/models/action.rs
src/models/version.rs

This pull requests gets rid of more `spawn_blocking()` fns by converting the code to async/await and taking advantage of `diesel-async` queries.

controllers/version: Remove more `spawn_blocking()` fns

---

src/bin/crates-admin/default_versions.rs
src/bin/crates-admin/delete_version.rs
src/bin/crates-admin/dialoguer.rs
src/bin/crates-admin/migrate.rs
src/bin/crates-admin/render_readmes.rs
src/bin/crates-admin/upload_index.rs
src/controllers/crate_owner_invitation.rs
src/controllers/keyword.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/krate/versions.rs
src/controllers/metrics.rs
src/controllers/user/me.rs
src/controllers/version/downloads.rs
src/tasks.rs
src/worker/jobs/archive_version_downloads.rs
src/worker/jobs/downloads/update_metadata.rs
src/worker/jobs/dump_db.rs
src/worker/jobs/index/normalize.rs
src/worker/jobs/index/squash.rs
src/worker/jobs/index/sync.rs
src/worker/jobs/readmes.rs
src/worker/jobs/update_default_version.rs

The idea for our wrapper to require a `Result` return type for the callback function might have been good in theory, but leads to too many small annoyances in practice. Let's get rid of it and move back closer to the original `spawn_blocking()` implementation from `tokio`.

Simplify `spawn_blocking()` wrapper fn

---

src/controllers/krate/publish.rs

Quite a bit of code that is currently within the `spawn_blocking()` scope isn't using the sync database connection, so we might as well move it outside. One notable exception is the `process_tarball()` call, which stays within a dedicated `spawn_blocking()` call for now. While `process_tarball()` is operating on in-memory bytes and should be fairly fast, we sometimes process multiple megabytes of data here, so we can't rely on this being fast enough for an async thread.
Best reviewed in "ignore whitespace changes" mode :wink:

controllers/krate/publish: Reduce `spawn_blocking()` scope

---

src/controllers/krate/metadata.rs
src/models/krate.rs

Best reviewed in "ignore whitespace changes" mode 😉

controllers/krate/metadata: Remove `spawn_blocking()` usage

---

Cargo.lock
crates/crates_io_test_db/Cargo.toml
crates/crates_io_test_db/src/lib.rs
src/controllers/user/session.rs
src/index.rs
src/models/category.rs
src/rate_limiter.rs
src/tests/categories.rs
src/tests/util/test_app.rs
src/typosquat/database.rs
src/worker/jobs/archive_version_downloads.rs
src/worker/jobs/downloads/clean_processed_log_files.rs
src/worker/jobs/expiry_notification.rs
src/worker/jobs/rss/sync_crate_feed.rs
src/worker/jobs/rss/sync_crates_feed.rs
src/worker/jobs/rss/sync_updates_feed.rs
src/worker/jobs/typosquat.rs

One less trait that needs to be imported and we can eventually change this to use an async connection pool :)

test_db: Extract `async_connect()` fn

---

src/tests/mod.rs
src/typosquat/database.rs
src/typosquat/test_util.rs

This already exists with a slightly similar name, so we might as well use it :D

typosquat/test_util: Remove duplicate `add_crate_to_team()` fn

---

Cargo.lock
crates/crates_io_database/Cargo.toml
crates/crates_io_database/tests/schema_details.rs

One less codepath using the sync database connection pool :)

database/tests/schema_details: Use async queries

---

src/bin/crates-admin/delete_crate.rs

As discussed in https://github.com/rust-lang/crates.io/pull/9912 npm uses a 24 hour delay until a package name becomes available again after deletion. This PR introduces the same default for our `delete-crate` admin tool, but also lets us override the value with the `--availability-delay XXX` CLI option.
Related:
- https://github.com/rust-lang/crates.io/pull/9912

admin/delete-crate: Use configurable 24 hour availability delay

---

src/tests/mod.rs
src/tests/owners.rs
src/tests/team.rs
src/typosquat/database.rs

One less function using the sync `PgConnection` 🎉

Migrate `add_team_to_crate()` to async queries

---

src/controllers/krate/versions.rs

Another one down, only 30 more to go... :D

controllers/krate/versions: Remove `spawn_blocking()` call

---

src/controllers/helpers/pagination.rs
src/controllers/keyword.rs
src/controllers/krate/search.rs
src/controllers/user/me.rs

aka. fighting with the borrow checker and [internal compiler errors](https://github.com/rust-lang/rust/issues/133252)... 🙈 
but hey, it compiles now and seems to work, so I guess that's good? 😆

Implement async pagination

---

src/bin/crates-admin/default_versions.rs
src/models.rs
src/models/default_versions.rs

I **hate** the duplication... but it'll be gone soon!

models/default_versions: Add async fn variants

---

Cargo.lock
Cargo.toml
src/worker/jobs/rss/sync_crates_feed.rs
src/worker/jobs/rss/sync_updates_feed.rs

This update fixes the escaping of `]]>` in `CDATA`, which means we can remove our current workaround :)

Update `rss` dependency

---

src/bin/crates-admin/default_versions.rs
src/bin/crates-admin/delete_version.rs
src/models.rs
src/models/default_versions.rs
src/tests/builders/krate.rs
src/worker/jobs/update_default_version.rs

This PR first migrates the remaining code paths to use the async variants of the fns in the `models/default_versions` module, and then removes the now-unused sync functions, while also renaming the async variants and dropping the `async_` prefix.
- ... as promised in https://github.com/rust-lang/crates.io/pull/10036

models/default_versions: Remove sync fns

---

src/controllers/krate/owners.rs
src/models/crate_owner_invitation.rs
src/models/krate.rs
src/models/owner.rs
src/models/team.rs
src/models/user.rs
src/tests/owners.rs
src/tests/routes/crates/list.rs
src/tests/routes/me/get.rs
src/tests/routes/users/stats.rs
src/tests/team.rs

These were the last two API endpoints that were still using synchronous database operations. With this PR the two endpoints are now using `diesel-async` queries as well, allowing us to start the cleanup process of removing all of the duplicate sync functions.
Here is what GitHub Copilot has to say about the PR: 😅 
----
This pull request includes several changes to the `src/controllers/krate/owners.rs`, `src/models/crate_owner_invitation.rs`, `src/models/krate.rs`, `src/models/owner.rs`, `src/models/team.rs`, and `src/models/user.rs` files to transition from synchronous to asynchronous database operations using `diesel_async`.
Key changes include:
* [`src/controllers/krate/owners.rs`](diffhunk://#diff-b941ec2990765da236d673c85bff680d222ced1060e2ae5f5c1e360b159b9a82L65-L83): Replaced …

controllers/krate/owners: Convert remaining endpoints to async/await

---

src/bin/crates-admin/delete_crate.rs
src/controllers/crate_owner_invitation.rs
src/controllers/github/secret_scanning.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/token.rs
src/controllers/user/resend.rs
src/controllers/user/update.rs
src/controllers/version/metadata.rs
src/email.rs
src/models/krate.rs
src/models/owner.rs
src/models/team.rs
src/models/user.rs
src/tests/issues/issue1205.rs
src/tests/issues/issue2736.rs
src/tests/owners.rs
src/tests/team.rs
src/typosquat/database.rs
src/typosquat/test_util.rs
src/worker/jobs/expiry_notification.rs
src/worker/jobs/send_publish_notifications.rs
src/worker/jobs/sync_admins.rs
src/worker/jobs/typosquat.rs

This PR is basically similar to #10048 and removes the remaining sync functions that have an async counterpart.

Remove unused sync fns

---

src/typosquat/database.rs
src/typosquat/test_util.rs
src/worker/jobs/typosquat.rs

This was one of the last `TestDatabase::connect()` users. We should soon be able to remove it.

typosquat/test_util: Migrate `user()` fn to `diesel-async`

---

src/bin/crates-admin/yank_version.rs
src/controllers/krate/downloads.rs
src/controllers/krate/search.rs
src/controllers/summary.rs
src/index.rs
src/models/krate.rs
src/models/version.rs
src/worker/jobs/downloads/update_metadata.rs

This allows us to remove the unused `num_no_build` field of the struct, which means that we have to transfer less bytes from the database to the API server for the queries that result in one or many `Version` structs.

Use `Version::as_select()` to allow skipping columns

---

Cargo.lock
Cargo.toml
src/controllers/krate/publish.rs
src/tests/krate/publish/tarball.rs

Previously, the `BytesRequest` allocated memory for the full tarball (and the JSON metadata blob) before even validating that the `name` and `vers` fields of the JSON metadata correspond to a crate and version that the user has publish access too. This commit changes the code to first read the JSON metadata from the request body stream, validate it, and then read the tarball bytes afterwards.
Unfortunately, this means that we still buffer the full tarball in memory, but since we only want to upload the tarball to S3 once we validated the content of the tarball, this is somewhat hard to fix. Ideas are welcome! 😉

controllers/krate/publish: Validate JSON metadata before reading tarball

---

src/controllers/summary.rs
src/models/category.rs

Similar to https://github.com/rust-lang/crates.io/pull/9663, this PR changes our `GET /api/v1/summary` endpoint to perform various SQL queries in parallel.
In local testing this brought the average response time from around 100ms down to 80ms 🎉 
Unfortunately, the `encode_crates()` calls currently still need to be a separate step, since we can't keep hold of the `&mut conn` across `await` points when we're sharing the connection... or at least I haven't found a way yet 🤷‍♂️ 
Related:
- https://github.com/rust-lang/crates.io/pull/9663
- https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/postgres.20pipelining

controllers/summary: Use `tokio::try_join!()` to perform database queries in parallel

---

Cargo.lock
Cargo.toml
src/bin/crates-admin/render_readmes.rs

This PR migrate `render_pkg_readme()` and `find_file_by_path()` fns to async/await.

admin/render_readmes: Migrate `render_pkg_readme()` and `find_file_by_path()` fns to async/await

---

src/controllers/krate/publish.rs

Just to get a bit more insight... the old `split_body()` fn was also instrumented but I forgot to add the attributes in #10069 when implementing the new fns.

controllers/krate/publish: Add more tracing instrumentation

---

src/controllers/krate/publish.rs
src/worker/jobs/send_publish_notifications.rs

These comments are from a time when our codebase was still mostly synchronous, but this is no longer the case.

Remove outdated code comments

---

src/config/server.rs
src/controllers/krate/publish.rs
src/models/krate.rs
src/tests/krate/publish/max_size.rs
src/util.rs

Encoding this calculation in a `struct` does not seems to have much value since the calculation is only performed in the publish endpoint. Inlining the struct reduces unnecessary complexity and save a couple of lines :)

Inline `Maximums` struct

---

src/controllers/krate/publish.rs
src/tests/krate/publish/tarball.rs

This reverts PR #10069 and resolves https://github.com/rust-lang/crates.io/issues/10098.
The 503 error returned by Heroku is apparently caused by our usage of the "legacy router" on Heroku. When using "Heroku Router 2.0" the 503 error is gone, but now AWS Cloudfront starts acting up and returns 500 errors instead.
From the looks of it this appears to be a bug in Cloudfront, which does not seem to be able to handle HTTP responses while the request hasn't fully been received yet?
Unfortunately, that means we have to revert the semi-streaming publish endpoint for now and buffer everything upfront again until we either figure out how to make this work in Cloudfront, or switch to a different CDN for the crates.io API.

Revert "Merge pull request #10069 from Turbo87/publish-stream"

---

crates/crates_io_smoke_test/src/cargo.rs
crates/crates_io_smoke_test/src/main.rs

This should check a) if publishing without valid authentication fails and b) if HTTP error codes and messages are successfully received and shown by cargo.
Related:
- https://github.com/rust-lang/crates.io/issues/10098

smoke_test: Add "publish with invalid authentication" check

---

Cargo.lock
crates/crates_io_smoke_test/Cargo.toml
crates/crates_io_smoke_test/src/main.rs

The "invalid authentication" check (see #10104) was actually resulting in a false-positive, since the request payload was small enough to not trigger the Cloudfront bug. This commit adjusts the smoke test to generate a 15 MB dummy file which we then try to publish instead.
Related:
- https://github.com/rust-lang/crates.io/issues/10098
- #10104

smoke_test: Check failed publish with large payload

---

crates/crates_io_database/src/schema.rs
crates/crates_io_database_dump/src/dump-db.toml
crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
migrations/2024-11-26-155931_add-cats-and-keys-to-version/down.sql
migrations/2024-11-26-155931_add-cats-and-keys-to-version/up.sql
src/controllers/krate/publish.rs
src/models/version.rs

Similar to https://github.com/rust-lang/crates.io/pull/9998, this PR adds two new columns to the `versions` database table: `categories` and `keywords`
These columns are filled with the corresponding values from the `Cargo.toml` file when new crates/versions are published.
Compared to the per-crate categories and keywords, these are not saved in dedicated `crates_categories` and `crates_keywords` tables, but just as a regular Postgres array column. The reason for this is that we don't need to find versions by category or keyword. We only need the data to set the new crate categories/keywords when the "default version" of a crate changes (will be implemented in a follow-up PR, once the data is backfilled in the database).
Related:
- https://github.com/rust-lang/crates.io/issues/953
- …

database: Add `categories` and `keywords` columns to the `versions` table

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css
app/components/edition.hbs
app/components/edition.module.css
app/components/msrv.hbs
app/components/msrv.module.css
app/components/version-list/row.hbs
app/components/version-list/row.module.css
app/models/version.js
tests/models/version-test.js

I assume we'll want to bikeshed the tooltip wording here. I don't know if showing the minimum edition version is actually useful, honestly, but I included it for now for discussion purposes.
Visually, this feels like it works out OK:
|Edition|MSRV|
|-------|-----|
|![image](https://github.com/user-attachments/assets/3c899291-e9c0-4d0d-ad9e-78e99fb67ba1)|![image](https://github.com/user-attachments/assets/c1ea7efa-d8ee-44ba-82b3-9d465ca21e73)|
|![edition](https://github.com/user-attachments/assets/3b8e325c-d62d-4570-8055-76e529791738)|![msrv](https://github.com/user-attachments/assets/32567c24-25e8-4bed-998d-7761783b0121)|
I toyed with using small caps for the "edition" label on the versions list, but it looked weird with the uppercase "features", so I dropped it.
---
In #9996, we started …

components: don't infer MSRV based on edition

---

tests/acceptance/support-test.js

This PR add missing parameter `hooks` to fix warnings
```json
{"type":"warn","text":"The `beforeEach` hook was called inside the wrong module (`Acceptance | support > reporting a crate from support page`). Instead, use hooks provided by the callback to the containing module (`Acceptance | support`). This will become an error in QUnit 3.0."}
{"type":"warn","text":"The `afterEach` hook was called inside the wrong module (`Acceptance | support > reporting a crate from support page`). Instead, use hooks provided by the callback to the containing module (`Acceptance | support`). This will become an error in QUnit 3.0."}
{"type":"warn","text":"The `beforeEach` hook was called inside the wrong module (`Acceptance | support > reporting a crate from crate page`). Instead, use hooks provided by the …
```

tests/acceptance/support-test: Fix QUnit warning

---

src/controllers/krate.rs
src/controllers/krate/delete.rs
src/router.rs

This PR implements the first step of https://github.com/rust-lang/crates.io/issues/9352: a new `DELETE /api/v1/crates/:crate_id` endpoint that can be used by crate owners to delete their crate under certain conditions (see linked RFC)
Unresolved Questions:
- [Should names of deleted crates be blocked so that they can't be re-used?](https://github.com/rust-lang/rfcs/blob/master/text/3660-crates-io-crate-deletions.md#should-names-of-deleted-crates-be-blocked-so-that-they-cant-be-re-used) – This PR does not implement any blocking for now, similar to how it already works for our `crates-admin` tool.
Related:
- https://github.com/rust-lang/crates.io/issues/9352
- https://github.com/rust-lang/rfcs/pull/3660
- https://github.com/rust-lang/crates.io/pull/9549 
- …

Implement `DELETE /api/v1/crates/:crate_id` endpoint

---

app/components/support/crate-report-form.hbs
app/components/support/crate-report-form.module.css
app/styles/support.module.css
app/templates/support.hbs
e2e/acceptance/support.spec.ts
tests/acceptance/support-test.js

Resolves https://github.com/rust-lang/crates.io/issues/9949

Include email address in support buttons

---

docker-compose.yml
docs/CONTRIBUTING.md

You can find these warnings when you run docker-compose:
```sh
❯ docker-compose up -d
WARN[0000] /Volumes/t7/code/crates.io/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] /Volumes/t7/code/crates.io/docker-compose.override.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```
See more at: https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete

Docker: Remove deprecated `version` attribute

---

app/models/crate.js
app/models/version.js
package.json
pnpm-lock.yaml

Since `@cached` is built into Ember, we should prefer it over external dependency.

Deprecate `tracked-toolbox` dependency

---

src/controllers/krate/delete.rs

`DELETE` endpoints are supposed to return "204 No Content" upon successful deletion, unless the response contains an entity, which is not the case here.
see https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE#successfully_deleting_a_resource

controllers/krate/delete: Adjust HTTP status code

---

app/controllers/categories.js
app/controllers/category/index.js
app/controllers/crate/reverse-dependencies.js
app/controllers/crates.js
app/controllers/keyword.js
app/controllers/keywords.js
app/controllers/me/crates.js
app/controllers/me/following.js
app/controllers/search.js
app/controllers/team.js
app/controllers/user.js

Since the underlying implementation of `@reads` uses `.get()`, which introduces deprecation warnings `deprecation id: ember-data:deprecate-array-like`, this commit fixes the warning by rewriting the `@reads('some.deep.path')` to equivalent `@cached get function ()`.
This should hopefully resolve some deprecation warnings similar to the following:
```log
{"type":"warn","text":"DEPRECATION: The EmberObject get method on the class RecordArray is deprecated. Use dot-notation javascript get/set access instead. [deprecation id: ember-data:deprecate-array-like] This will be removed in ember-data 5.0.\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:712:308)\n        at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:667:339)\n        at raiseOnDeprecation …
```

ember-data: Fix `ember-data:deprecate-array-like` warning

---

.github/workflows/ci.yml
.github/workflows/smoke-test.yml

see https://woodruffw.github.io/zizmor/
/cc @woodruffw

CI: Fix zizmor issues

---

app/styles/shared/buttons.module.css

9bbea928ba2c66247fa64e6474f371ac3d57d48c introduced an `important!` marker, but missed that this was somewhat incompatible with the disabled state. This commit fixes it by also using `important!` for the disabled state. Clearly not a good long-term strategy, but good enough for now... If someone want to contribute a better fix, I'm open to it 😉

styles/buttons: Fix font color in disabled state

---

app/components/crate-header.hbs
app/components/crate-header.js

This PR addresses deprecation warnings by explicitly loading async values (`crate.keywords`, `crate.owner_user`) using tasks.
This should hopefully resolve some deprecation warnings similar to the following:
```
{"type":"warn","text":"DEPRECATION: Do not use A() on an EmberData PromiseManyArray [deprecation id: ember-data:no-a-with-array-like] This will be removed in ember-data 5.0.\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:712:308)\n        at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:667:339)\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:715:210)\n        at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:667:339)\n        at eval (webpack://crates-io/../../.pnpm/@ember+test-helpers@4.0.4_@babel+cor …
```

crate-header: Fix deprecation warnings

---

app/styles/shared/buttons.module.css

This makes it a bit more visible when buttons are disabled.

styles/buttons: Use `not-allowed` cursor for disabled buttons

---

app/adapters/application.js
app/controllers/crate/delete.js
app/router.js
app/routes/crate/delete.js
app/styles/application.module.css
app/styles/crate/delete.module.css
app/templates/crate/delete.hbs
e2e/routes/crate/delete.spec.ts
public/assets/triangle-exclamation.svg
tests/routes/crate/delete-test.js

This partially implements step 2 of https://github.com/rust-lang/crates.io/issues/9352. The missing piece after this PR is a "Delete" button in the crate settings tab, since the new route is currently only reachable by typing it directly in the URL bar. I opted for this hidden route for now to be able to test it out first before making it more public.
Related: 
- https://github.com/rust-lang/crates.io/issues/9352

UI: Implement `/crates/:name/delete` route

---

src/tests/routes/crates/list.rs
src/util/request_helpers.rs

Our search endpoint supports having multiple `ids[]` query parameters defined, but the way we generate our pagination fields only considered the last such query parameter until now. This PR fixes the code to include all query parameters instead.

Fix pagination field generation for duplicate keys

---

src/controllers/helpers/pagination.rs

Ideally we'd only pass in a `Uri`, but since we're using the `RequestLog` we still need to pass in the full `Parts` struct.
Previously we were compiling two variants of this function, one for `Parts` and one for `Request`, although only our test code was still using the `Request` variant. This PR changes the tests to use `Parts` too and then removes the obsolete generic parameter from the `gather()` fn.

controllers/helpers/pagination: Remove generic parameter from `gather()` fn

---

Cargo.lock
Cargo.toml
crates/crates_io_cdn_logs/Cargo.toml
crates/crates_io_cdn_logs/src/download_map.rs
src/lib.rs
src/middleware/log_request.rs
src/middleware/real_ip.rs

The former hasn't had a commit in 4 years, while the latter is properly maintained and might potentially unlock other useful derives.

Replace `derive_deref` with `derive_more`

---

Cargo.lock
Cargo.toml
src/controllers/krate/search.rs
src/lib.rs
src/openapi.rs
src/router.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

This PR implements the basic infrastructure to have an **experimental**, best-effort, automatically generated OpenAPI description for the crates.io API. The OpenAPI description will be available at https://crates.io/api/openaip.json, with a viewer available at https://crates.io/api/openaip.
Due to the viewer being on the same domain as the Ember.js frontend, it will automatically share the cookie authentication, which may or may not be a problem. We could alternatively consider serving the viewer from a different subdomain if this turns out to be problematic.
Note that this PR only migrates a single route for now to prove the viability of this approach. The remaining routes can be migrated incrementally.
Related:

Use `utoipa` crates to generate and serve basic OpenAPI description

---

src/controllers/helpers/pagination.rs

This PR is roughly similar to #10190 and removes another generic parameter

controllers/helpers/pagination: Remove generic parameter from `is_useragent_or_ip_blocked()` fn

---

Cargo.toml
src/app.rs
src/middleware/session.rs
src/tests/util/response.rs
src/util/bytes_request.rs

There is no need for us to implement this trait manually if we can just derive it :)

Derive `Deref` for more structs

---

src/router.rs

Now that we are not using the `BytesRequest` in the publish endpoint, this limit isn't actually used anymore. The `StreamReader` does not care about the limit and the JSON metadata blob and the tarball have their dedicated limits already.

router: Remove obsolete `DefaultBodyLimit` override

---

src/controllers/helpers/pagination.rs
src/tests/routes/crates/list.rs
src/tests/routes/me/updates.rs

This avoids allocating a bunch of `String` instances for all the keys and values in the query string when all we need is three optional fields, of which two are just integers. This PR also uses `NonZeroU32` for the `page` and `per_page` parameters, since we were throwing errors for values below 1 anyway.
Admittedly the error messages aren't perfect, since they don't include the field name of the value that couldn't be parsed, but that is something that can be improved centrally in the `Query` extractor or the underlying serde deserializer.

controllers/helpers/pagination: Read query parameters via `axum::Query` extractor

---

src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/keyword.rs
src/controllers/krate.rs
src/controllers/krate/delete.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/versions.rs
src/controllers/site_metadata.rs
src/controllers/summary.rs
src/controllers/team.rs
src/controllers/token.rs
src/controllers/user.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/resend.rs
src/controllers/user/session.rs
src/controllers/user/update.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/router.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/tests/blocked_routes.rs

This PR continues what #10186 started. It migrates (almost) all of our API endpoints to `utoipa` with a set of very basic annotations. The next step will be to add path and query parameters and request/response body schemas. Also missing is authentication schemes, but this PR should be a good starting point to add them :)

utoipa: Add annotations to (almost) all endpoints

---

app/components/crate-header.js
app/components/crate-sidebar.hbs
app/components/version-list/row.js
app/controllers/crate/settings.js
app/controllers/crate/version.js
app/models/crate.js
app/routes/crate.js
app/routes/crate/version.js
app/routes/crate/versions.js
tests/components/crate-sidebar/playground-button-test.js
tests/components/crate-sidebar/toml-snippet-test.js
tests/components/owners-list-test.js
tests/components/version-list-row-test.js
tests/models/version-test.js

This PR should hopefully fix the remaining deprecations :)

Fix frontend deprecations

---

src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/keyword.rs
src/controllers/krate/delete.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/krate/versions.rs
src/controllers/site_metadata.rs
src/controllers/summary.rs
src/controllers/team.rs
src/controllers/token.rs
src/controllers/user.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/resend.rs
src/controllers/user/session.rs
src/controllers/user/update.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/router.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

... and unify some of the differing naming patterns.
The goal of this was to save a couple of code lines, but it turns out that with longer and unique names rustfmt negates those line savings again. Still worth it for DRY reasons 😅

utoipa: Rename route handler fns to remove `operation_id` attributes

---

src/controllers/krate.rs
src/controllers/krate/delete.rs
src/controllers/krate/downloads.rs
src/controllers/krate/follow.rs
src/controllers/krate/metadata.rs
src/controllers/krate/owners.rs
src/controllers/krate/versions.rs
src/controllers/version.rs
src/controllers/version/downloads.rs
src/controllers/version/metadata.rs
src/controllers/version/yank.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/tests/routes/crates/downloads.rs

These structs can be used as `axum` extractors for the corresponding `Path` patterns. At the same time, they implement `utoipa::IntoParams`, which allows them to be used in `#[utoipa::path(params(CratePath), ...)` form, which adds them to the generated OpenAPI description.
Related:
- https://github.com/rust-lang/crates.io/pull/10186
- https://github.com/rust-lang/crates.io/pull/10201
- https://github.com/rust-lang/crates.io/pull/10207

Extract `CratePath` and `CrateVersionPath` structs

---

src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/keyword.rs
src/controllers/team.rs
src/controllers/token.rs
src/controllers/user/me.rs
src/controllers/user/other.rs
src/controllers/user/resend.rs
src/controllers/user/update.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

The overhead of adding dedicated `Path` structs for these did not seem worth it compared to https://github.com/rust-lang/crates.io/pull/10208, so I added these `Path` params only to the `utoipa` annotations.
Related:
- https://github.com/rust-lang/crates.io/pull/10186
- https://github.com/rust-lang/crates.io/pull/10201
- https://github.com/rust-lang/crates.io/pull/10207
- https://github.com/rust-lang/crates.io/pull/10208

utoipa: Add remaining `Path` params

---

Cargo.lock
Cargo.toml
src/controllers/krate/search.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/tests/krate/following.rs
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes-2.snap
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes-3.snap
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes-4.snap
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes-5.snap
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes.snap
src/util.rs
src/util/string_excl_null.rs

This allows us to automatically derive OpenAPI descriptions and avoids unnecessary memory allocations from query parameters we do not care about in this endpoint.
Small caveat: the `serde_html_form` crate currently deserializes `foo=` as `None` instead of `Some("")` (see https://github.com/jplatte/serde_html_form/issues/13), which is technically a behavior change for our API. According to our logs, our frontend UI appears to be the only user of the `following` query parameter though, and that one uses `following=1`. So while this is theoretically a breaking change, I don't think in practice it's a hard blocker.

controllers/krate/search: Read query parameters via axum extractor

---

crates/crates_io_tarball/examples/check_all_crates.rs
src/bin/background-worker.rs
src/bin/server.rs
src/rate_limiter.rs

These are all in `Result` returning fns, so there is no need to use `unwrap()` if we can use `?` instead :)

Replace `unwrap()` with `?`

---

src/controllers/krate/search.rs

No need to manually implement it, now that we use `derive_more` 🎉

controllers/krate/search: Derive `Deref` for `FilterParams`

---

src/controllers/krate/search.rs

This simplifies the `make_query()` fn, since it no longer needs to return a `Result`

controllers/krate/search: Move `letter` validation out of `make_query()` fn

---

src/controllers.rs
src/controllers/krate.rs
src/controllers/krate/metadata.rs
src/controllers/krate/rev_deps.rs
src/controllers/session.rs
src/controllers/user.rs
src/controllers/user/email_notifications.rs
src/controllers/user/email_verification.rs
src/controllers/user/me.rs
src/controllers/user/snapshots/crates_io__controllers__user__email_verification__tests__happy_path-2.snap
src/controllers/version.rs
src/controllers/version/authors.rs
src/controllers/version/dependencies.rs
src/controllers/version/metadata.rs
src/controllers/version/readme.rs
src/controllers/version/update.rs
src/controllers/version/yank.rs
src/router.rs

This PR moves a couple of endpoints to new modules to make the individual files easier to digest. Additionally, some endpoints were previously in modules that didn't really fit that well.

Extract more controller modules

---

src/controllers/helpers/pagination.rs
src/controllers/krate/search.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

I guess the title speaks for itself...? 😅 
Related:
- https://github.com/rust-lang/crates.io/pull/10186
- https://github.com/rust-lang/crates.io/pull/10201
- https://github.com/rust-lang/crates.io/pull/10207
- https://github.com/rust-lang/crates.io/pull/10208

utoipa: Add pagination query params to `list_crates()` documentation

---

Cargo.toml
src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/helpers/pagination.rs
src/controllers/krate/metadata.rs
src/controllers/krate/versions.rs
src/controllers/version/downloads.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/util/request_helpers.rs

This PR extracts a bunch of `FooQueryParams` structs to simplify our query parameter handling and better document our supported query parameters. These structs implement `axum::FromRequestParts` and `utoipa::IntoParams` so they should be easy to use and essentially self-documenting wrt our OpenAPI description.
Related:
- https://github.com/rust-lang/crates.io/pull/10186
- https://github.com/rust-lang/crates.io/pull/10201
- https://github.com/rust-lang/crates.io/pull/10207
- https://github.com/rust-lang/crates.io/pull/10208
- https://github.com/rust-lang/crates.io/pull/10233

Extract `QueryParams` structs

---

src/real_ip.rs

We have upgraded our servers to use the "Heroku Router 2.0" which fixed the `X-Forwarded-For` bug and no longer appends the IP to the first header it sees. This means we can finally remove our workaround and parse the header appropriately.

real_ip: Remove Heroku router workaround

---

crates/crates_io_session/src/lib.rs
src/controllers/crate_owner_invitation.rs
src/controllers/krate/delete.rs
src/controllers/krate/follow.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/search.rs
src/controllers/session.rs
src/controllers/token.rs
src/controllers/user/email_notifications.rs
src/controllers/user/email_verification.rs
src/controllers/user/me.rs
src/controllers/user/update.rs
src/controllers/version/update.rs
src/controllers/version/yank.rs
src/openapi.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

This PR improves our OpenAPI description by declaring what "security schemes" (aka. authentication schemes) are available, and what endpoints require which kind of authentication.

OpenAPI: Describe authentication requirements

---

e2e/acceptance/versions.spec.ts

This is another PR that extracted from #10248.

e2e/acceptance/versions: Fix potential flaky test case

---

app/templates/crate/delete.hbs
src/controllers/krate/delete.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

As discussed in the last crates.io team meeting the current limit of just 100 downloads per month was too conservative. This commit raises the limit to 500 downloads per month to make self-service deletions a bit more viable in practice.

Raise crate deletion download limit

---

app/styles/crate/delete.module.css
app/templates/crate/delete.hbs

As discussed at today's team meeting, here is a slight tweak to how the requirements are laid out when deleting a crate.
Before:
After:

crate/delete: tinker with the requirements styling

---

src/controllers/krate/delete.rs
src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_new_crate-2.snap
src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_old_crate-2.snap
src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_really_old_crate-2.snap

This PR addresses part two of https://github.com/rust-lang/crates.io/issues/9352#issuecomment-2549402681 by sending a notification email to the owner when a crate is getting deleted.

controllers/krate/delete: Send deletion notification email after successful deletion

---

mirage/route-handlers/crates.js
mirage/serializers/crate.js
tests/mirage/crates/get-by-id-test.js

mirage: Respect `include` query params in `GET /api/v1/crates/:id`

---

src/controllers/krate/versions.rs

This PR extracts the `ListQueryParams::include()` function. Instead of passing `include` as a parameter, we pass `&ListQueryParams`. This allows us to more easily introduce other query params (e.g. `ids[]`) in the future :)

controllers/krate/versions: Extract `ListQueryParams::include()` fn

---

crates/crates_io_cdn_logs/src/lib.rs

We don't use docs.rs, but this might help people that use `cargo doc` locally, or that have IDE support for these things.

cdn_logs: Use `README.md` as module documentation

---

crates/crates_io_diesel_helpers/README.md

Looks like that CI job needs to be split and/or also run for other `.md` files...

Fix prettier issues

---

mirage/route-handlers/-utils.js
mirage/route-handlers/crates.js
tests/mirage/crates/versions/list-test.js

This makes the response from Mirage consistent with our backend response :)
Related:
- #9624 
- #10214

mirage: Add `meta` field in `GET /api/v1/crates/:id/versions`

---

crates/crates_io_database/README.md
crates/crates_io_database/src/lib.rs
crates/crates_io_database_dump/README.md
crates/crates_io_database_dump/src/lib.rs
crates/crates_io_env_vars/README.md
crates/crates_io_env_vars/src/lib.rs
crates/crates_io_github/README.md
crates/crates_io_github/src/lib.rs
crates/crates_io_index/README.md
crates/crates_io_index/lib.rs
crates/crates_io_markdown/README.md
crates/crates_io_markdown/lib.rs
crates/crates_io_pagerduty/README.md
crates/crates_io_pagerduty/src/lib.rs
crates/crates_io_session/README.md
crates/crates_io_session/src/lib.rs
crates/crates_io_smoke_test/README.md
crates/crates_io_smoke_test/src/main.rs
crates/crates_io_tarball/README.md
crates/crates_io_tarball/src/lib.rs
crates/crates_io_team_repo/README.md
crates/crates_io_team_repo/src/lib.rs
crates/crates_io_test_db/README.md
crates/crates_io_test_db/src/lib.rs
crates/crates_io_worker/README.md
crates/crates_io_worker/src/lib.rs

Our subpackages in the `crates` folder lacked proper documentation, so this PR adds a couple of basic `README.md` files and instructs `rustdoc` to use them as the module docstrings too.

Add `README.md` files to subpackages

---

src/controllers/krate/metadata.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/tests/routes/crates/read.rs
src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__include_default_version.snap

This allows us to respond with a version data of `default_version` included, which potentially benefits apps by eliminating the need to wait for the crate response to obtain the `default_version` and then make a subsequent request to get the actual version data. This is particularly useful when we move towards not requesting with `versions` included.

controllers/krate/metadata: Add support for `default_version` include mode

---

mirage/route-handlers/crates.js
mirage/serializers/crate.js
tests/mirage/crates/get-by-id-test.js

mirage: Add `include=default_version` support for `GET /api/v1/crates/:id`

---

src/tests/util.rs
src/tests/util/mock_request.rs
src/tests/util/response.rs

The result of `cargo llvm-lines --lib --profile test` indicated that our `RequestHelper` trait was causing a lot of code generation due to the generic `<T>` parameter.
This PR considerably reduces the amount of copied code, and thus should improve the compile times of our test suite a bit (see https://matklad.github.io/2021/09/04/fast-rust-builds.html#Keeping-an-Eye-on-Instantiations).

tests/util: Reduce monomorphization overhead for the `RequestHelper` code

---

app/adapters/crate.js
app/models/crate.js
app/routes/crate/dependencies.js
app/routes/crate/range.js
app/routes/crate/version-dependencies.js
app/routes/crate/version.js
e2e/acceptance/crate-dependencies.spec.ts
e2e/routes/crate/range.spec.ts
tests/acceptance/crate-dependencies-test.js
tests/adapters/crate-test.js
tests/models/version-test.js
tests/routes/crate/range-test.js

Extracted from #10248.
This will ensure that the `versions` are fetched via a separate requests, rather than being included in the `crate`'s response. This not only enables us to render the page layout first for a faster first paint but also allows us to migrate to a paginated version list in the future.
Before:
https://github.com/user-attachments/assets/ba8f2e05-bad3-43ff-b033-b906976581b4
After:
https://github.com/user-attachments/assets/3626c949-e892-4a29-80a1-ce8838cd0131

app: Make separate requests for crate and versions

---

mirage/route-handlers/crates.js
tests/mirage/crates/versions/authors-test.js
tests/mirage/crates/versions/dependencies-test.js
tests/mirage/crates/versions/downloads-test.js
tests/mirage/crates/versions/get-by-num-test.js
tests/mirage/crates/versions/list-test.js
tests/mirage/crates/versions/patch-test.js
tests/mirage/crates/versions/readme-test.js
tests/mirage/crates/versions/yank/unyank-test.js
tests/mirage/crates/versions/yank/yank-test.js

This PR maintains crate version-related handling by:
- Fixing the not found error status code to 404.
- Adding the missing `GET /api/v1/crates/:name/:version` endpoint.
- Rewording some request parameters or variables for consistency.
Related:
- #7881

mirage: Maintains crate version-related handling

---

e2e/acceptance/readme-rendering.spec.ts

According to
https://github.com/mermaid-js/mermaid/blob/bc2cc61240987ac956c69e262c93971cd254f00a/packages/mermaid/src/mermaid.ts#L160-L164, when mermaid finishes processing a node, it will set the `data-processed` to true.

e2e/acceptance/readme-rendering: Fix test flakyness

---

mirage/route-handlers/crates.js
src/controllers/krate/versions.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/tests/routes/crates/versions/list.rs
tests/mirage/crates/versions/list-test.js

This allows us to return specified versions by filtering with the `ids[]` parameter.

Add multiple `nums[]` parameters support for `GET /api/v1/crates/:name/versions`

---

src/controllers/krate/delete.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

This PR adds support for `DELETE /api/v1/crates/foo?message=hello%20world` requests, to set the corresponding `message` column in the `deleted_crates` database table.
In a follow-up PR I'm planning to add a (required?) input field to the crate deletion UI, which sets the query parameter accordingly.

Add support for `message` query parameter when deleting crates

---

app/styles/crate/settings.module.css
app/templates/crate/settings.hbs
e2e/acceptance/crate-deletion.spec.ts
tests/acceptance/crate-deletion-test.js

This makes our ["Delete the foo crate?" page](https://github.com/rust-lang/crates.io/pull/10177) public, and implements one of the last missing pieces from https://github.com/rust-lang/crates.io/issues/9352.

Add "Delete this crate" button to the crate settings page

---

app/models/dependency.js
app/services/store.js
app/transforms/date.js

This fixes some deprecations introduced after upgrading Ember Data. Fixes are primarily based on log feedback.

Fix deprecations

---

Cargo.lock
Cargo.toml
crates/crates_io_tarball/Cargo.toml

This should be reverted and replaced with an actual package upgrade once `cargo-manifest` has a release that includes a fix for https://github.com/LukeMathWalker/cargo-manifest/issues/63.
Fixes #10361.

deps: patch `cargo-manifest` to support resolver 3

---

Cargo.lock
Cargo.toml
crates/crates_io_tarball/Cargo.toml

This includes the fix for https://github.com/LukeMathWalker/cargo-manifest/issues/63 that necessitated the earlier change to pin to a specific commit in my fork of `cargo-manifest`.

deps: update to `cargo-manifest` 0.18.0 for real

---

mirage/serializers/crate.js

The `@ember/debug` import makes it harder to use the mirage code outside of an Ember.js context. This commit replaces the import with an `if + throw` combination. The main advantage of `assert()` is that it is compiled out of production code, but since the mirage code is not shipped to production anyway, this advantage doesn't actually apply here.
/cc @eth3lbert 
Related:
- https://github.com/rust-lang/crates.io/pull/10357

mirage: Replace `assert()` from `@ember/debug` with conditional `throw`

---

src/controllers/krate/search.rs

This fixes an incorrect operator in the comment and also embeds the order by information in it. Hopefully, this will make it easier for contributors to know which operator to use.

Fix incorrect comparison operator in comment

---

app/adapters/crate.js
app/routes/crate.js
e2e/acceptance/crate.spec.ts
mirage/route-handlers/crates.js
tests/acceptance/crate-test.js
tests/mirage/crates/get-by-id-test.js

Before the Ember Data 5 update it was possible to visit `/crates/foo-bar` when the crate was actually called `foo_bar` and vice-versa. The Ember Data 5 update broke this behavior, and this PR is restoring it, by using `queryRecord()` instead of `findRecord()`, which can no longer deal with requesting a certain `id` and getting a different one returned from the server.
Fixes https://github.com/rust-lang/crates.io/issues/10368

Fix non-canonical crate name pages

---

app/adapters/crate.js
app/controllers/crate/delete.js
app/routes/crate/delete.js
app/styles/crate/delete.module.css
app/templates/crate/delete.hbs
e2e/acceptance/crate-deletion.spec.ts
e2e/routes/crate/delete.spec.ts
tests/acceptance/crate-deletion-test.js
tests/routes/crate/delete-test.js

As discussed in our last team meeting, this pull requests adds a required "Reason" input field to the crate deletion page:

crate/delete: Add required reason input field

---

app/adapters/crate.js
app/controllers/crate/delete.js

see https://github.com/rust-lang/crates.io/pull/10380#discussion_r1915015818 🙈

adapters/crate: Fix query parameter name

---

app/templates/policies/index.hbs

This PR resolves the last open task of https://github.com/rust-lang/crates.io/issues/9352:
> Update https://crates.io/policies to no longer mention that "Crate deletion by their owners is not possible"
Closes https://github.com/rust-lang/crates.io/issues/9352

Update "Usage Policy" regarding crate deletions

---

src/tests/routes/crates/list.rs

This PR rewrites our test cases for `alpha` and `relevance` sorting to be more dumb, explicit and easier to follow for better readability. Aside from that, previously, we seem not to cover the cases with the same rank for `relevance` sorting, which are also covered in this PR.

Improving the readability of search test cases

---

src/controllers/krate/search.rs

Previously, I used the wrong function, and the correct function was not available at that time.
The correct function `plainto_tsquery_with_search_config()` respects to `plainto_tsquery(config regconfig, query text ) → tsquery` is now available [^1], and our test cases cover this part. I think it's time we switched to using it :D
Related:
- #8052 
[^1]: https://github.com/diesel-rs/diesel_full_text_search/pull/41

controllers/krate/search: Use provided `plainto_tsquery_with_search_config()` fn

---

ember-cli-build.js
package.json
pnpm-lock.yaml

This gets rid of a lot of outdated dependencies and according to https://github.com/embroider-build/ember-auto-import/blob/v2.10.0-ember-auto-import/docs/upgrade-guide-2.0.md shouldn't have relevant breaking changes in our context.

Add `ember-auto-import` resolution override

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
crates/crates_io_worker/Cargo.toml

This removes two unused dependency declarations and adds `cargo-machete` to our CI pipeline.

Use `cargo-machete` to remove unused dependency declarations

---

app/adapters/crate.js
app/adapters/version.js
app/models/crate.js
app/routes/crate/dependencies.js
app/routes/crate/version-dependencies.js
app/routes/crate/version.js
e2e/acceptance/crate-dependencies.spec.ts
tests/acceptance/crate-dependencies-test.js
tests/adapters/crate-test.js

This PR would ensure that `default_version` is included in the `crate` response by default. This eliminates the need to wait for the `versions` request to complete when `default_version` is the only version required. This also decouples requested version handling from versions. 
Related:
- #10288 
- #10296

Include `default_version` by default

---

app/components/crate-header.hbs
app/components/crate-row.hbs
app/components/crate-sidebar.hbs
app/components/crate-sidebar.module.css
app/components/dependency-list/row.hbs
app/components/dependency-list/row.module.css
app/components/edition.hbs
app/components/ember-tooltip.js
app/components/msrv.hbs
app/components/privileged-action.hbs
app/components/settings/api-tokens.hbs
app/components/tooltip.hbs
app/components/tooltip.js
app/components/tooltip.module.css
app/components/version-list/row.hbs
app/components/version-list/row.module.css
app/modifiers/attach-tooltip.js
app/styles/application.module.css
package.json
pnpm-lock.yaml

https://floating-ui.com is a low-level library to implement e.g. tooltips. This PR replaces the unmaintained `ember-tooltips` addon with a custom `Tooltip` component based on `floating-ui` that works roughly similar. This should hopefully then unblock the `@ember/string` update in #10354.
yes, we lost the arrow, but does that really matter? 😅 
floating-ui does have an "arrow middleware", but I couldn't make it work properly in combination with `flip()`. since it would require more complexity for IMHO little gain I think it's fine to ship this without arrows.

Replace `ember-tooltips` with `floating-ui`

---

.env.sample
Cargo.lock
Cargo.toml
app/index.html
src/config/server.rs
src/middleware.rs
src/middleware/ember_html.rs
src/middleware/static_or_continue.rs
src/tests/util/test_app.rs

Related discussion: https://github.com/rust-lang/crates.io/discussions/9928
I replaced `tower_http::services::ServeFile` with a manually built response, and attempted to mimic its behavior. Furthermore, I replaced the hard coded open graph image url from `app/index.html` with a Jinja2 variable called `og_image_url`. I imagine this file is served from a bucket or the like in production, so upon deployment that variable should be replaced with the original fallback URL.
The base URL of the OG images is configurable, and should work with either a local or public instance of [`og-loc`](https://github.com/mainmatter/og-loc), or, as suggested in the related discussion, a file in a bucket.
Is this going in the right direction?
To do:

Implement dynamic OpenGraph image url support for crate pages

---

crates/crates_io_database/src/schema.rs
crates/crates_io_database_dump/src/dump-db.toml
crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
migrations/2025-02-05-083109_add-num-versions-column/down.sql
migrations/2025-02-05-083109_add-num-versions-column/up.sql
src/controllers/krate/publish.rs
src/tests/krate/publish/basics.rs

The total number of versions is one of the blockers for avoiding loading full versions within the application. To address this, we can either send a separate request to retrieve the number, or, as suggested by @Turbo87, store the value in db and include it in the crate response. The latter approach seems more promising, as it eliminates the need for an extra request solely to obtain the total.
To ensure the value is up-to-date and maintain deployment convenience, the implementation will be separated into multiple PRs:

Add `default_versions.num_versions` column

---

src/models.rs
src/models/crate_owner_invitation.rs
src/models/krate.rs

This avoids the "three `i32` arguments in a function call" issue and is more consistent with the rest of the codebase that uses similar patterns.

Extract `NewCrateOwnerInvitation` struct

---

migrations/2025-02-11-163554_fix-num-versions-trigger/down.sql
migrations/2025-02-11-163554_fix-num-versions-trigger/up.sql
src/tests/krate/publish/basics.rs

Per https://github.com/rust-lang/crates.io/pull/10519/files#r1951118907. 🤦‍♂️ 🙈 
This fixes the misused `EXCLUDED` which would cause the `num_versions` to remain at 2 during conflicts.

db: Fix incorrect Upsert for `num_versions`

---

src/controllers/token.rs
src/models.rs
src/models/token.rs
src/tests/routes/me/tokens/create.rs
src/tests/routes/me/tokens/get.rs
src/tests/routes/me/tokens/list.rs
src/tests/util.rs
src/views.rs

This simplifies the code for creating new API tokens a little bit by using the builder pattern for the new struct, instead of a list of function parameters that does not really scale.

models/token: Extract `NewApiToken` struct

---

src/controllers/krate/rev_deps.rs
src/models/krate.rs

This dependency on the `PaginationOptions` struct makes it hard to eventually extract our database model code into a dedicated crate. Since we only need the offset and limit for this query we can just pass it in directly and move the dependency into the controller that is already using `PaginationOptions` anyway.

models/krate: Remove `PaginationOptions` dependency

---

.github/workflows/ci.yml

This has been silently broken for a while and it's unclear at this point what exactly broke it. Since we rarely look at it and the `grcov` call takes the majority of our CI time, we will remove this for now in the hope that a better alternative will emerge eventually.

CI: Remove broken CodeCov integration

---

src/controllers/krate/owners.rs
src/models/owner.rs

The `models` module should not know anything the API server it is being used in...
This PR moves the `Owner::find_or_create_by_login()` fn from the model code to the corresponding controller that calls it. In the second commit the controller code is being refactored to make it easier to reason about.

models/owners: Remove `App` dependency

---

src/models/team.rs
src/models/user.rs
src/tests/user.rs

The struct has a `Debug` implementation, so we should be using `SecretString` to redact it from the output and avoid other accidental leakages.

models/user: Change `gh_access_token` field to `SecretString`

---

src/controllers/krate/owners.rs
src/models/crate_owner_invitation.rs
src/models/krate.rs
src/models/owner.rs
src/tests/issues/issue2736.rs
src/tests/mod.rs
src/tests/routes/crates/owners/remove.rs

This simplifies the usage of the `CrateOwner` struct. It also makes it slightly safer to use, since the `user_id()` and `team_id()` fns on the builder avoid potential mismatches.

Derive `bon::Builder` for `CrateOwner` struct and add `insert()` fn

---

src/controllers/krate/downloads.rs
src/models.rs
src/models/download.rs

This avoids loading the additional data that is unnecessary for the downloads endpoint.

models/download: Add a slim `Version` model to reduce data loading

---

src/controllers/krate/downloads.rs

This changes downloads endpoint to perform various SQL queries in parallel.

controllers/krate/downloads: Perform queries in parallel

---

src/models/team.rs
src/models/user.rs

We don't need an `AppResult` in most cases where a `Result<_, GitHubError>` is sufficient.

models/team: Simplify fn return types

---

crates/crates_io_github/src/lib.rs
src/models/team.rs
src/tests/issues/issue1205.rs
src/tests/routes/crates/owners/remove.rs
src/tests/util/github.rs

We can handle the `NotFound` case inside the lib, to make it easier for users of the fns.

github: Adjust `org/team_membership()` to return `Result<Option<_>, _>`

---

src/models/team.rs
src/models/user.rs

We don't need a new instance for each request...

models/team: Avoid repeated `AccessToken` instantiation

---

app/templates/crate/delete.hbs
src/controllers/krate/delete.rs

Temporary hack while we discuss #10538 further.
Here's what this now looks like on the deletion page:
Feel free to bikeshed exactly what we include in there. (Do we need the GitHub issue?)
This should be a straightforward revert depending on what we decide.

controllers/krate/delete: prevent any crates with rdeps from deletion

---

app/adapters/crate.js
app/routes/crate/version.js
e2e/acceptance/crate.spec.ts
packages/crates-io-msw/handlers/crates/downloads.js
packages/crates-io-msw/handlers/crates/downloads.test.js
src/controllers/krate/downloads.rs
src/models/action.rs
src/models/version.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
tests/acceptance/crate-test.js

While #10344 is merged, we currently include the `default_version`. Ideally, we should not load all versions for the index/version page. However, there are still some blockers. One blocker is `VersionDownload` due to its` belongsTo` relationship with `version`. This requires us to wait for `versions` to be loaded before loading `downloads`.
This PR aims to add an include mode to the `GET /api/v1/crates/{name}/downloads` endpoint. This allows it to include the related `versions` and avoids the need to wait for `versions` to be fully loaded in app.

Add `?include=versions` support for `GET /api/v1/crates/{name}/downloads` endpoint

---

app/templates/crate/version.hbs

Missed a replacement spot in #10581 🙈

app: Migrate the overlooked `versions.length` to `num_versions`

---

app/services/session.js

The `<PrivilegedAction>` tests are currently flaky and it is unclear exactly why. These debug statement might help us in figuring out the root cause of the flakiness.

services/session: Add `debug` logs

---

deny.toml

As the code comment says, we are aware, but there is not much we can do about it from our side at the moment.

cargo-deny: Ignore `ring` maintenance advisory

---

app/styles/dashboard.module.css

This fixes the low color contrast of the "Load More" button on dashboard, especially in light mode.
Light (before)
Light (after)
Dark (before)
Dark (after)

Fix low contrast of "Load More" on dashboard

---

crates/crates_io_tarball/src/lib.rs
crates/crates_io_worker/src/worker.rs
src/controllers/krate/delete.rs
src/controllers/krate/publish.rs
src/middleware/cargo_compat.rs
src/router.rs
src/worker/jobs/archive_version_downloads.rs

see https://blog.rust-lang.org/2025/02/20/Rust-1.85.0.html#async-closures

Use async closures where applicable

---

app/routes/crates.js
app/templates/catch-all.hbs
e2e/acceptance/crates.spec.ts
tests/acceptance/crates-test.js

Previously, this route was showing an unhelpful error message. With this change it is using the regular error screen with a "Try again" button and a slightly friendlier error message.
Resolves https://github.com/rust-lang/crates.io/issues/10614

Improve `/crates` route error handling

---

src/controllers/keyword.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

Looks like I somehow missed these before 😅

controllers/keyword: Add query params documentation

---

src/controllers/keyword.rs
src/openapi.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/views.rs

This PR adjusts our codebase to derive `ToSchema` for a couple of structs related to our keywords API and then attaches them to the generated OpenAPI documentation:

Add OpenAPI documentation for keyword API responses

---

src/openapi.rs

Looks like this is being picked up automatically :)

openapi: Remove unnecessary `schema` declaration

---

src/controllers/category.rs
src/tests/mod.rs
src/views.rs

`#[serde(skip_serializing_if = "Option::is_none")]` allows us to use the same struct for both cases which removes the unnecessary duplication between the two structs.

Merge `EncodableCategoryWithSubcategories` into `EncodableCategory`

---

src/controllers/category.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/views.rs

Add OpenAPI documentation for category API responses

---

src/views.rs

This fn does not appear to be used anywhere, so we might as well remove it :)

Remove unused `EncodableCrateOwnerInvitationV1::from()` fn

---

src/controllers/user/other.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/views.rs

Related:
- #10692
- https://github.com/rust-lang/crates.io/pull/10693
- #10685

Add OpenAPI documentation for `GET /api/v1/users/{user}` endpoint

---

src/controllers/krate/metadata.rs

This extracts queries into multiple dedicated load functions and further enables pipelining. Additionally, the `default_versions` logic has been rewritten to share enrichment logic with the regular versions. Changes were made in small commits for easier review per commit.

controllers/krate/metadata: Pipeline SQL queries

---

app/adapters/version.js
app/components/version-list/row.hbs
app/components/version-list/row.js
app/controllers/crate/versions.js
app/models/crate.js
app/models/version.js
app/routes/crate/versions.js
app/styles/crate/versions.module.css
app/templates/crate/versions.hbs
e2e/acceptance/crate.spec.ts
tests/acceptance/crate-test.js
tests/components/version-list-row-test.js
tests/models/version-test.js

This PR migrates the `versions` page to a paginated style, which loads more versions with a "Load More" button. Two sorted lists serve as different contexts, so they can display in different. Most of the computation for versions (`sorting` and `release_tracks`) on this page will no longer be needed on the app, they all done on the backend.
Some major changes are highlighted as follows:
- Drop support for first version hint (breaking change).
- Migrate the `versions` page to a paginated list.
- Simplify `releaseTrackSet` with `release_tracks` meta.
Regarding the first version hint, since we've moved to a paginated list and the API doesn't support reverse ordering, determining the first version would likely require fetching all versions. If we choose to support this rather than drop it, it …

Migrate versions page to paginated list

---

src/controllers/user/other.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

Related:
- #10692
- https://github.com/rust-lang/crates.io/pull/10693
- https://github.com/rust-lang/crates.io/pull/10698
- #10685

Add OpenAPI documentation for `GET /api/v1/users/{id}/stats` response payload

---

src/controllers/crate_owner_invitation.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/views.rs

Related:
- #10692
- https://github.com/rust-lang/crates.io/pull/10693
- https://github.com/rust-lang/crates.io/pull/10698
- https://github.com/rust-lang/crates.io/pull/10702
- #10685

Add OpenAPI documentation for `crate_owner_invitation` response payloads

---

src/controllers/helpers.rs
src/controllers/krate/follow.rs
src/controllers/user/email_notifications.rs
src/controllers/user/email_verification.rs
src/controllers/user/update.rs
src/controllers/version/yank.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

... and use the struct in our OpenAPI description.

Replace `ok_true()` fn with `OkResponse` struct

---

src/controllers/user/me.rs

controllers/user/me: Pipeline SQL queries

---

src/controllers/version/metadata.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/views.rs

Related:
- #10692
- https://github.com/rust-lang/crates.io/pull/10693
- https://github.com/rust-lang/crates.io/pull/10698
- https://github.com/rust-lang/crates.io/pull/10702
- https://github.com/rust-lang/crates.io/pull/10703
- https://github.com/rust-lang/crates.io/pull/10707
- #10685

Add OpenAPI documentation for `GET /api/v1/crates/{name}/{version}` response payload

---

app/serializers/crate.js
e2e/acceptance/crate.spec.ts
tests/acceptance/crate-test.js

Previously, if `categories` and `keywords` of `crate` had existing values, they would be cleared from query results if those value returned null. This caused issues when `crate` was peeked from the store. This commit detects null values and ignores the fields instead of updating them.
Fixes #10711 .

serializers/crate: Prevent `categories` and `keywords` from being cleared

---

src/controllers/crate_owner_invitation.rs
src/controllers/krate/owners.rs
src/controllers/krate/publish.rs
src/controllers/krate/rev_deps.rs
src/controllers/krate/search.rs
src/controllers/krate/versions.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/views.rs

... for various API endpoints 😅

Improve OpenAPI documentation

---

app/components/settings/api-tokens.module.css

The top-most button should not have a dedicated top margin...

settings/api-tokens: Fix `margin-top` for buttons

---

tests/acceptance/support-test.js

Attempting to fix the following flaky tests:
https://github.com/rust-lang/crates.io/actions/runs/13632195641/job/38102274110?pr=10740#step:6:239
```
not ok 156 Chrome 133.0 - [147 ms] - Exam Partition 1 - Acceptance | support > reporting a crate from crate page: valid form without detail
---
stack: >
Error: Element not found when calling `click('[data-test-id="link-crate-report"]')`.
at eval (webpack://crates-io/../../.pnpm/@ember+test-helpers@5.1.0_@babel+core@7.26.9_ember-source@6.0.1_@glimmer+component@2.0.0_rsvp@4.8.5_webpack@5.98.0_/node_modules/@ember/test-helpers/dist/dom/click.js?:107:13)
at async prepare (webpack://crates-io/./tests/acceptance/support-test.js?:3035:7)
at async Object.eval (webpack://crates-io/./tests/acceptance/support-test.js?:3091:7)
message: >
Promise rejected …
```

Fix flaky tests

---

app/styles/crate/versions.module.css
app/templates/crate/versions.hbs

An excerpt from https://rust-lang.zulipchat.com/#narrow/channel/318791-t-crates-io/topic/swc/near/503007257
>I noticed that while loading the versions list there is no loading indicator and it looks like the crate simply has no versions. might be worth implementing some kind of loading screen for that state.
This shows a loading indicator for the initial load, and a loading button when loading more :D
https://github.com/user-attachments/assets/7386c5ae-99dd-4939-8d4f-220fb16e753a

versions: Improve the loading indicator

---

crates/crates_io_database/Cargo.toml

Looks like the `ApiToken` struct needs the `chrono` feature too... 🙈

crates_io_database: Fix `utoipa` dependency declaration

---

Cargo.lock

see https://rustsec.org/advisories/RUSTSEC-2025-0009

Update `ring` to v0.17.12

---

app/components/crate-row.hbs
app/components/crate-row.module.css

This enables the hover selector only when a pointer is available to fix #10772. This also adjusts the styles for alignment and spacing, particularly when wrapping is involved.
Fixes #10772 .
Before (Always showing the copy button, without style adjustments):
After:

Adjust styles for crate row

---

app/templates/crate/delete.hbs
src/controllers/krate/delete.rs

controllers/krate/delete: remove the temporary language from #10591

---

src/bin/crates-admin/delete_crate.rs

I just tried to use the admin tool to delete a crate and it LIED TO MY FACE and included the username of a DELETED OWNER in the output. Uuuuunaaaaaaccceptable

Exclude deleted crate owners from admin tool output

---

deny.toml

and resolve a couple of other warnings.
let's hope https://github.com/EmbarkStudios/cargo-deny/issues/752 gains some traction 🤞

cargo-deny: Ignore "paste is unmaintained" "advisory"

---

tests/acceptance/support-test.js

There still seem to be issues, as per https://github.com/rust-lang/crates.io/pull/10743#issuecomment-2710106013. This adds debugging information to help us find more clues about it.

tests/acceptance/support-test: Add debugging information for flaky tests

---

crates/crates_io_diesel_helpers/src/fns.rs
src/controllers/helpers/pagination.rs
src/controllers/krate/versions.rs
src/tests/routes/crates/versions/list.rs

This PR changes how we return sorted versions from the `GET /api/v1/crates/{name}/versions` API endpoint. 
Previously, we needed to download all version numbers from the database to the API server and perform the sorting and filtering there, since the database did not support sorting by semantic version. With https://github.com/rust-lang/crates.io/pull/10763 that changed, so now we can perform the sorting and filtering directly in the database, which simplifies the code that the API server needs to run and the data that needs to be transferred between the API server and the database.
Note that I have not added any database indexes for the `semver_ord` column yet, so there is potentially some more room for performance improvements.
The implementation as-is has a small caveat, in that it is …

Use `semver_ord` column for sorting versions

---

src/controllers/krate/versions.rs

This the follow-up PR to #10819 for the `release_tracks` part. :D

controllers/krate/versions: Use `semver_ord` for `release_tracks` where applicable

---

app/components/follow-button.hbs
app/components/loading-spinner.hbs
app/components/loading-spinner.module.css
app/templates/index.hbs
app/templates/settings/tokens/new.hbs

This adjusts the spinner color to follow the color mode, and ensures certain buttons' loading spinners remain dark, especially those with backgrounds that do not follow the color mode.
Before:
After:
Before:
After:

Adjust loading spinner color

---

Cargo.lock
Cargo.toml
crates/crates_io_tarball/Cargo.toml

Astral recently published `astral-tokio-tar`, which is a fork of `krata-tokio-tar` that preserves permissions and is actively maintained. I don't see any reason not to switch to it.

Replace `krata-tokio-tar` with `astral-tokio-tar`

---

crates/crates_io_database/src/models/category.rs
src/controllers/category.rs

This enables pipelines for category SQL queries.

controllers/category: Pipeline SQL queries

---

app/components/settings/api-tokens.hbs
e2e/acceptance/api-token.spec.ts
tests/acceptance/api-token-test.js

This PR contains https://github.com/rust-lang/crates.io/pull/10868 plus another commit that adds a couple of regression assertions for the button visibilities. It looks like GitHub currently rejects my attempts to push to the other PR branch for some reason so I had to open another PR for it 🤷‍♂️ 
/cc @seqre

tests/api-token: Add action button visibility assertions

---

app/components/settings/api-tokens.hbs

The issue was reported by @fasterthanlime on https://hachyderm.io/@fasterthanlime/114199813804811002 and it was introduced by accident in https://github.com/rust-lang/crates.io/pull/9122. I moved the button outside the if statement and it seems to work!
Clicking on `Regenerate` redirects to the token creation as expected.

Make regenerate button visible for expired tokens

---

package.json
pnpm-lock.yaml

ember-data 5.3.12 with _all cookies disabled_ will produce the following errors:
```
Request to access cookie or storage on “http://localhost:4200/” was blocked because we are blocking all storage access requests.
Error while processing route: index The operation is insecure. @webpack://crates-io/../../.pnpm/@warp-drive+core-types@0.0.2/node_modules/@warp-drive/core-types/dist/runtime.js?:11:18
../../.pnpm/@warp-drive+core-types@0.0.2/node_modules/@warp-drive/core-types/dist/runtime.js@http://localhost:4200/assets/chunk.62e397042e3860b4cc0e.js:2427:1
__webpack_require__@http://localhost:4200/assets/chunk.6c34f435df0c2bcec442.js:31:42
@webpack://crates-io/../../.pnpm/@ember-data+store@5.3.12_@ember-data+request-utils@5.3.12_@ember+string@4.0.1_@warp-dri_d48323cbad6325bc586f3b5a2dc4a8ea/node …
```

Pin `ember-data` to `5.3.11`

---

src/boot/categories.toml

I'm proposing to add a new `security` category for binary and library crates related to cybersecurity, penetration testing, code review, vulnerability research, and reverse engineering.
Some examples of crates that would fit in this category:
* [binarly-io/idalib](https://github.com/binarly-io/idalib) [[idalib](https://crates.io/crates/idalib)] - Rust bindings for the IDA SDK, enabling the development of standalone analysis tools using IDA v9.0’s idalib
* [0xdea/augur](https://github.com/0xdea/augur) [[augur](https://crates.io/crates/augur)] - Reverse engineering assistant that extracts strings and related pseudo-code from a binary file
* [0xdea/haruspex](https://github.com/0xdea/haruspex) [[haruspex](https://crates.io/crates/haruspex)] - Vulnerability research assistant that extracts …

Add `security` category

---

crates/crates_io_markdown/lib.rs

The test are currently failing, which indicates a bug. From my understanding, the test should pass.
As per this URLO thread: https://users.rust-lang.org/t/missing-list-item-names-in-the-readme-on-crates-io/127558
You can see the bug live in action at
https://crates.io/crates/Yoda/0.11.5

markdown: Add tasklist test cases

---

ember-cli-build.js

We don't need the `Store` to extend `EmberObject` (anymore?), so we can disable the corresponding behavior.

ember-data: Address `DEPRECATE_STORE_EXTENDS_EMBER_OBJECT` deprecation

---

src/controllers/krate/publish.rs
src/tests/krate/publish/manifest.rs

We currently get the package name and version in three places in a publish request: the JSON metadata blob, the path prefix inside the crate tarball, and the `Cargo.toml` manifest inside the crate tarball. Up until now we were primarily relying on the JSON metadata and verifying the path prefixes. Apparently we were not checking the content of the `Cargo.toml` manifest though.
This PR fixes the issue by explicitly checking the manifest fields too and returning errors in case of a mismatch.

Return errors if metadata name or version do not match manifest

---

.github/workflows/ci.yml

Unfortunately this action needs to perform `git fetch` operations in some cases, which apparently requires `persist-credentials` to be `true`.

CI: Fix `changed-files` action usage

---

package.json
pnpm-lock.yaml

This appears to not be needed anymore? Apparently Ember.js ships with native typescript support now... or at least I haven't found anything yet that breaks without this dependency 😅

Remove unnecessary `@types/ember` dependency

---

app/services/testing.js
e2e/fixtures/ember.ts

`require()` is no longer available starting with Ember.js v6.1.0. This should help to unblock https://github.com/rust-lang/crates.io/pull/10269.

Replace `require('@ember/debug')` with service function call

---

app/services/testing.js
e2e/routes/support.spec.ts

`require()` is no longer available starting with Ember.js v6.1.0. This should unblock https://github.com/rust-lang/crates.io/pull/10269.

Replace `require('@ember/service')` with service property

---

config/optional-features.json

Looks like we're not relying on the implicit `model()` hooks anymore, so we might as well disable them.
Extracted from https://github.com/rust-lang/crates.io/pull/10976

Ember: Enable `no-implicit-route-model` feature

---

ember-cli-build.js

We don't use `ember-fetch` anymore, so we can remove the corresponding config object.

ember-fetch: Remove obsolete config object

---

app/styles/dashboard.module.css
app/styles/shared/buttons.module.css
app/templates/crate/versions.hbs
app/templates/dashboard.hbs
ember-cli-build.js

It's fine to share the styles for the button itself, but the surrounding elements don't need to be shared between the two instances. This allows us to remove the dashboard styles from the `headerModules` list, since the shared styles now live in the `shared/buttons.module.css` file.

Simplify `.load-more` CSS classes

---

app/styles/crate/versions.module.css
app/templates/crate/versions.hbs

Restyling the button to not be visible as a button makes the CSS more complicated than it needs to be. This commit splits the load more button into a loading placeholder for the initial load, and the actual load more button with a loading indicator for subsequent loads.

Split "loading" placeholder from "load more" button

---

Cargo.toml
src/config/sentry.rs
src/sentry/mod.rs

These get redacted in the Sentry ingest, but why send them at all?

sentry: remove `Authorization` header values before send

---

Cargo.lock
crates/crates_io_github/Cargo.toml
crates/crates_io_github/examples/test_github_client.rs

This makes it a bit easier to test and debug our GitHub client implementation locally, without having to rely on our mock implementation.

GitHub: Add basic example client for local testing purposes

---

crates/crates_io_github/src/lib.rs

This adds debug logging for the remaining rate limit and slightly improves the existing per-request log message.

GitHub: Improve `tracing` usage

---

crates/crates_io_github/src/lib.rs

Turns out we were not applying base64 encoding to our basic auth requests before. Using `.basic_auth()` fixes the issue, which means that we now properly authenticate, while previously we were accidentally running these requests completely unauthenticated, making us subject to the 60 requests per hour rate limit... 😅

GitHub: Use `basic/bearer_auth()` fns from `reqwest`

---

crates/crates_io_github/examples/test_github_client.rs
crates/crates_io_github/src/lib.rs

see https://docs.github.com/en/rest/repos/repos#get-a-repository
This can be used in the future to lookup the GitHub ID of repositories to avoid account resurrection attacks.

GitHub: Add support for "Get a repository" requests

---

app/controllers/crate/versions.js
app/models/version.js
app/services/release-tracks.js
e2e/acceptance/versions.spec.ts
tests/acceptance/versions-test.js

This PR adds a service to handle refreshing and updating the payload of release tracks for a crate. The value will be re-fetched via a refresh task after yanking/unyanking to maintain the correctness of the release tracks label in the UI.
Fixes #10984.

Refresh release tracks

---

src/tests/user.rs
src/tests/util.rs

We only use this struct for testing, where we don't want to hide the plaintext token for debugging purposes. This will also make it easier in the future to construct `MockTokenUser` instances from an existing plaintext token, without going through the `PlainToken` struct.

tests/util: Change `MockTokenUser::plaintext` to `String`

---

crates/crates_io_database/README.md
crates/crates_io_database/src/schema.patch

`patch -o` does not appear to work quite as intended on my machine, so let's adjust the instructions to make them actually work correctly.
This also introduces `--label` arguments to the `diff` call, to avoid the unnecessary datetime headers.

Fix `diesel` schema patch file update instructions

---

src/app.rs
src/bin/server.rs
src/tests/util/test_app.rs

With every mockable subsystem the `App::new()` fn becomes more complicated. This PR proposes the introduction of a derived `AppBuilder` struct, replacing `App::new()` and making the construction of `App` instances more flexible.

Derive `Builder` for `App` struct

---

src/tests/builders/krate.rs
src/tests/builders/version.rs
src/tests/unhealthy_database.rs

There is no need anymore for these functions to return an `AppResult`, we can use generic `anyhow::Result` instead 🎉

tests/builders: Replace `AppResult` with `anyhow`

---

crates/crates_io_github/examples/test_github_client.rs
crates/crates_io_github/src/lib.rs

Reverts rust-lang/crates.io#11017
Turns out we actually need something different... I'll implement that in a follow-up PR 😅

Revert "GitHub: Add support for "Get a repository" requests"

---

crates/crates_io_database/src/models/team.rs
crates/crates_io_github/src/lib.rs
docs/CONTRIBUTING.md
src/controllers/krate/owners.rs
src/controllers/session.rs
src/tests/user.rs
src/tests/util/github.rs

It's called "GitHub", not "Github"… 😅

Fix "Github" spelling

---

Cargo.lock
Cargo.toml
crates/crates_io_database/src/models/mod.rs
crates/crates_io_database/src/models/trustpub/github_config.rs
crates/crates_io_database/src/models/trustpub/mod.rs
crates/crates_io_github/examples/test_github_client.rs
crates/crates_io_github/src/lib.rs
crates/crates_io_trustpub/Cargo.toml
crates/crates_io_trustpub/README.md
crates/crates_io_trustpub/src/github/mod.rs
crates/crates_io_trustpub/src/github/validation.rs
crates/crates_io_trustpub/src/lib.rs
src/controllers.rs
src/controllers/trustpub/github_configs/create/mod.rs
src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__happy_path-2.snap
src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__happy_path.snap
src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__happy_path_with_environment.snap
src/controllers/trustpub/github_configs/create/tests.rs
src/controllers/trustpub/github_configs/emails.rs
src/controllers/trustpub/github_configs/json.rs
src/controllers/trustpub/github_configs/mod.rs
src/controllers/trustpub/mod.rs
src/router.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/util/errors.rs

This PR implements the first API endpoint for "Trusted Publishing" support in crates.io.
`PUT /api/v1/trusted_publishing/github_configs` can be used to create Trusted Publishing configurations specific to GitHub Actions. As discussed in https://github.com/rust-lang/crates.io/pull/11062#discussion_r2059728214, it seems best to make the configurations provider-specific, and only have the token exchange endpoint be generic.
The endpoint is currently limited to cookie authentication, so that we don't have to commit to this API yet, since our frontend will be the only user. Once we have validated that we are happy with the API we can open it up to API token authentication, but that will likely mean introducing another token scope, which seems out of scope for this PR.
This PR is probably best …

Implement `PUT /api/v1/trusted_publishing/github_configs` API endpoint

---

src/email.rs

lettre v0.11.16 fixed the `Clone` implementation, so now the `Arc` is not needed anymore.
https://github.com/lettre/lettre/pull/1075

Remove `Arc` around `AsyncFileTransport`

---

src/app.rs
src/bin/background-worker.rs
src/config/database_pools.rs
src/db.rs
src/lib.rs
src/tests/util/test_app.rs

This PR extracts a `create_database_pool()` fn from the API server initialization code and then subsequently uses it in the `bin/background-worker` binary.
This ensures that things like the `connection_timeout` and `statement_timeout` are consistently applied to both the API server and the background worker.

Use same database pool creation code for API server and background worker

---

src/config/database_pools.rs
src/db.rs
src/tests/util/test_app.rs

We may as well use a proper type, instead of a raw `u64` 😅

config/database_pools: Change `tcp_timeout` field to `Duration`

---

src/config/database_pools.rs

makes it a little easier to find and understand them :)

config/database_pools: Extract magic numbers into named constants

---

src/config/database_pools.rs

ehm... oops... 🤦‍♂️😅
looks like I f***ed that up in https://github.com/rust-lang/crates.io/pull/11185 🙈

config/database_pools: Fix broken `connection_timeout`

---

src/bin/background-worker.rs

Turns out unifying the database connection pool initialization had some unintended side effects for jobs in the background worker that use long-running database queries (e.g. `SELECT refresh_recent_crate_downloads()`).
This commit fixes the issue by explicitly overriding the timeout to be one hour instead of the default 30 sec.

bin/background-worker: Increase database statement timeout to one hour

---

.github/workflows/ci.yml
.github/workflows/smoke-test.yml

CI: Add `zizmor` job

---

Cargo.lock
Cargo.toml
crates/crates_io_docs_rs/Cargo.toml
crates/crates_io_docs_rs/README.md
crates/crates_io_docs_rs/examples/test_docs_rs_client.rs
crates/crates_io_docs_rs/src/lib.rs
src/bin/background-worker.rs
src/controllers/version.rs
src/controllers/version/docs.rs
src/router.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/tests/util.rs
src/tests/util/test_app.rs
src/worker/environment.rs
src/worker/jobs/docs_rs_queue_rebuild.rs
src/worker/jobs/mod.rs
src/worker/mod.rs

This is a first draft because I need more pointers. 
- is this how the API could look like? What's missing apart from tests? 
- where would I find the frontend parts be? [Quoting from zulip](https://rust-lang.zulipchat.com/#narrow/channel/318791-t-crates-io/topic/trigger.20docs.2Ers.20rebuilds.20from.20crates.2Eio/near/448513787): _FWIW I think I'd put the button below the [docs.rs](http://docs.rs/) link in the sidebar of the crates_
Generally I imagine that most limits should be applied from docs.rs, like how often a crate maintainer can trigger a rebuild.

Add `POST /api/v1/crates/{name}/{version}/rebuild_docs` API endpoint

---

src/controllers/site_metadata.rs

No need for `String::from(...)` if we can just work with `&str` instead :)

controllers/site_metadata: Avoid unnecessary allocation

---

src/controllers/trustpub/github_configs/delete/mod.rs
src/controllers/trustpub/github_configs/delete/snapshots/crates_io__controllers__trustpub__github_configs__delete__tests__happy_path.snap
src/controllers/trustpub/github_configs/delete/tests.rs
src/controllers/trustpub/github_configs/emails.rs
src/controllers/trustpub/github_configs/mod.rs
src/router.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

This PR implements another item on the todo list in https://github.com/rust-lang/crates.io/issues/10247: an API endpoint to delete Trusted Publishing configurations for GitHub Actions.
The implementation should be relatively straight-forward. It checks that the authenticated users is an owner of the crate, and if the configuration exists, it deletes it and sends a notification email to all the owners.
Related:
- https://github.com/rust-lang/rfcs/pull/3691
- https://github.com/rust-lang/crates.io/pull/11062
- https://github.com/rust-lang/crates.io/pull/11113

Add `DELETE /api/v1/trusted_publishing/github_configs/{id}` API endpoint

---

src/controllers/trustpub/github_configs/json.rs
src/controllers/trustpub/github_configs/list/mod.rs
src/controllers/trustpub/github_configs/list/snapshots/crates_io__controllers__trustpub__github_configs__list__tests__crate_with_no_configs.snap
src/controllers/trustpub/github_configs/list/snapshots/crates_io__controllers__trustpub__github_configs__list__tests__happy_path-2.snap
src/controllers/trustpub/github_configs/list/snapshots/crates_io__controllers__trustpub__github_configs__list__tests__happy_path.snap
src/controllers/trustpub/github_configs/list/tests.rs
src/controllers/trustpub/github_configs/mod.rs
src/router.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap

This PR implements the API endpoint to list all existing Trusted Publishing configurations for a crate.
As with the other related endpoints, this endpoint is only available to full crate owners (no team accounts) and (for now) only with cookie authentication.
Related:
- https://github.com/rust-lang/rfcs/pull/3691
- https://github.com/rust-lang/crates.io/pull/11062
- https://github.com/rust-lang/crates.io/pull/11113
- https://github.com/rust-lang/crates.io/pull/11209

Add `GET /api/v1/trusted_publishing/github_configs` API endpoint

---

crates/crates_io_database/src/models/mod.rs
crates/crates_io_database/src/models/version.rs
crates/crates_io_database/src/models/versions_published_by.rs
src/controllers/krate/publish.rs
src/tests/builders/version.rs
src/worker/jobs/downloads/update_metadata.rs

There is no need for this function to use a transaction since the only place that this is used in production is already using an outer transaction.
It is also questionable whether the `INSERT INTO versions_published_by` needs to happen in the same function, since there are plenty of other inserts that need to happen when a new version is published, but neither of them are part of this function either.
In the effort of making `crates_io_database` an easy to reason about data access layer, this PR adjusts the `NewVersion::save()` fn to only save the new version to the `versions` table, and moves the `versions_published_by` insert code outside of the function.

Simplify `NewVersion::save()` fn

---

app/templates/crate/settings.hbs

This isn't actually used for anything and was probably a copy-paste mistake.

crate/settings: Remove unnecessary `.me-email` container

---

app/controllers/crate/settings.js
app/styles/crate/settings.module.css
app/templates/crate/settings.hbs
e2e/acceptance/settings/add-owner.spec.ts
tests/acceptance/settings/add-owner-test.js
tests/routes/crate/settings-test.js

This form does not need a dedicated header and does not need to be visible all the time. This commit hides it until the user explicitly clicks the "Add Owner" button. This frees up space on the page to add the list of "Trusted Publishing" configurations.

crate/settings: Hide "Add Owner" form behind "Add Owner" button

---

app/templates/crate/settings.hbs

"Save" makes no sense in this context and appears to be a copy-paste mistake back from when the user email change form was copied...
Related:
- https://github.com/rust-lang/crates.io/pull/11301#discussion_r2129506871

crate/settings: Fix "Save" button caption to read "Add" instead

---

crates/crates_io_database/src/models/version.rs
src/controllers/krate/publish.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
src/tests/krate/publish/mod.rs
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__full_flow-3.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__full_flow-4.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__full_flow-5.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__happy_path.snap
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__happy_path_with_fancy_auth_header.snap
src/tests/krate/publish/trustpub.rs

This is the last major missing puzzle piece for the Trusted Publishing backend work: the ability to use temporary access tokens to publish new versions of crates.
Related:
- https://github.com/rust-lang/rfcs/pull/3691
- https://github.com/rust-lang/crates.io/pull/11062
- https://github.com/rust-lang/crates.io/pull/11113
- https://github.com/rust-lang/crates.io/pull/11131

controllers/krate/publish: Add support for Trusted Publishing access tokens

---

app/index.html
config/manifest.js

Set `theme-color` to `header-bg-color` so that it respects the current theme color and user preference which seems to fix the upper part of the page being inconsistent on Safari (tested on iPhone 15):
<details>
<summary>System theme in light mode</summary>
</details>
<details>
<summary>Light theme in dark mode</summary>
</details>
<details>
<summary>System theme in dark mode</summary>
</details>
<details>
<summary>Dark mode in light theme</summary>
</details>
Closes #11026

Set `theme-color` to `header-bg-color`

---

src/tests/owners.rs
src/tests/routes/categories/get.rs
src/tests/routes/crates/following.rs
src/tests/routes/keywords/read.rs
src/tests/routes/me/tokens/create.rs
src/tests/routes/me/tokens/get.rs
src/tests/routes/me/tokens/list.rs
src/tests/routes/me/updates.rs
src/tests/token.rs
src/tests/util/response.rs

These functions are somewhat inflexible, and while they use a more fluent chaining API, the rest of our assertions don't, which makes these a bit harder to use in some cases where other assertions are running on the same response instances.

tests: Inline `assert_not_found()` and `assert_forbidden()` fns

---

crates/crates_io_worker/src/worker.rs

For some reason only background jobs with the `#[instrumented]` annotation were receiving the `job.id` and `job.typ` fields from the parent span. This commit adjusts the `span` usage to not require the annotation and attach these fields for all background jobs.

worker: Fix tracing instrumentation

---

crates/crates_io_trustpub/src/access_token.rs
src/auth.rs
src/controllers/krate/publish.rs
src/controllers/trustpub/tokens/exchange/tests.rs
src/controllers/trustpub/tokens/revoke/mod.rs
src/controllers/trustpub/tokens/revoke/tests.rs
src/tests/krate/publish/auth.rs
src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__auth__new_krate_with_bearer_token-2.snap
src/tests/krate/publish/trustpub.rs

`cargo publish` was built without using an auth scheme in the `Authorization` header. Regular HTTP client libraries often only support either basic or bearer authentication, but not empty auth schemes.
The regular API tokens currently only support an empty auth scheme, while Trusted Publishing was (mistakenly) built in a way to only support the `Bearer` auth scheme.
This PR adjusts both code paths to use a shared `Authorization` header extractor which allows usage of an empty auth scheme, or the `Bearer` auth scheme, regardless of the type of token that is used or the API endpoint it is used on.
Related:
- Resolves https://github.com/rust-lang/crates.io/issues/11347

Allow empty and `Bearer` auth schemes in `Authorization` headers

---

app/components/privileged-action.hbs
app/components/version-list/row.hbs
app/components/version-list/row.module.css
app/components/yank-button.hbs
e2e/acceptance/sudo.spec.ts
e2e/acceptance/versions.spec.ts
public/assets/ellipsis-circle.svg
tests/acceptance/sudo-test.js
tests/acceptance/versions-test.js

We plan to add more actions in the future, and to prevent too many buttons from showing on each row and on small-screen devices, @Turbo87 suggests we should use a drop down menu instead.
Resolves #11139.

Replace yank button with a drop down menu

---

crates/crates_io_database_dump/src/readme_for_tarball.md

Noticed this was missing while I was grumping about other things.

db-dump: document the location of historical version download CSVs

---

src/controllers/trustpub/github_configs/create/mod.rs
src/controllers/trustpub/github_configs/create/tests.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot-2.snap
src/tests/krate/publish/trustpub.rs

`PUT` should be used for updates, not for resource creation. The conventional HTTP method for resource creation in REST APIs is `POST`.
The endpoint is currently limited to cookie authentication and not used yet by the frontend, so this change can still be made without it breaking anyone :)
Related:
- https://github.com/rust-lang/crates.io/pull/11113

trustpub: Change `PUT /api/v1/trusted_publishing/github_configs` endpoint to `POST`

---

src/controllers/trustpub/tokens/exchange/mod.rs
src/controllers/trustpub/tokens/exchange/tests.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot-2.snap
src/tests/krate/publish/trustpub.rs

`PUT` should be used for updates, not for resource creation. The conventional HTTP method for resource creation in REST APIs is `POST`. This also matches what PyPI is using.
The endpoint is already used by the experimental GitHub Action, but since we control that and are aware of the change we can easily fix it on that side :)
Related:
- https://github.com/rust-lang/crates.io/pull/11131
- https://github.com/rust-lang/crates.io/pull/11390

trustpub: Change `PUT /api/v1/trusted_publishing/tokens` endpoint to `POST`

---

packages/crates-io-msw/handlers/trustpub.js
packages/crates-io-msw/handlers/trustpub/github-configs.js
packages/crates-io-msw/handlers/trustpub/github-configs/create.js
packages/crates-io-msw/handlers/trustpub/github-configs/create.test.js
packages/crates-io-msw/handlers/trustpub/github-configs/delete.js
packages/crates-io-msw/handlers/trustpub/github-configs/delete.test.js
packages/crates-io-msw/handlers/trustpub/github-configs/list.js
packages/crates-io-msw/handlers/trustpub/github-configs/list.test.js
packages/crates-io-msw/index.js
packages/crates-io-msw/models/trustpub/github-config.js
packages/crates-io-msw/serializers/trustpub/github-config.js

This commit implements the three `/api/v1/trusted_publishing/github_configs` endpoints (list, create, delete). It adds a dedicated `trustpubGithubConfig` model and corresponding serializer and then uses them to implement the endpoints. As usual with msw, this is a relatively simple implementation, but good enough for our frontend test suite.

msw: Implement relevant Trusted Publishing endpoints

---

src/controllers/krate/publish.rs
src/tests/krate/publish/trustpub.rs

Let's explain the user how to fix the issue.

Improve trusted publishing error message

---

e2e/routes/crate/settings.spec.ts

The corresponding QUnit-based tests were added in https://github.com/rust-lang/crates.io/pull/10792, but we forgot to add them to the Playwright test suite too. This PR ports the existing set of QUnit tests over to Playwright.

e2e: Add missing `Route | crate.settings` tests

---

packages/crates-io-msw/handlers/versions.js
packages/crates-io-msw/handlers/versions/rebuild-docs.js
packages/crates-io-msw/handlers/versions/rebuild-docs.test.js

This commit implements the `/api/v1/crates/{name}/{version}/rebuild_docs` endpoint, which is relatively simple but good enough for frontend testing.

msw: Implement simplified docs rebuild endpoint

---

src/controllers/github/secret_scanning.rs
src/tests/github_secret_scanning.rs
src/tests/snapshots/crates_io__tests__github_secret_scanning__github_secret_alert_for_unknown_trustpub_token-2.snap
src/tests/snapshots/crates_io__tests__github_secret_scanning__github_secret_alert_revokes_trustpub_token-2.snap

This implements the final todo item of the Trusted Publishing backend work (see https://github.com/rust-lang/crates.io/issues/10247).
If a passed in token is successfully parsed as a Trusted Publishing token, the token is automatically revoked and a warning is logged.
Since these tokens belong to a crate (or multiple) instead of a user I have not implemented email notifications for them (yet). Should we email all owners of the crate in case a Trusted Publishing token is leaked? I guess we could also implement that in a follow-up PR, if we decide that we want that.

controllers/github/secret_scanning: Add support for Trusted Publishing tokens

---

app/router.js
app/styles/crate/settings/index.module.css
app/templates/crate/settings/index.hbs
app/templates/docs/trusted-publishing.hbs

This PR adds a "Learn more" button to the Trusted Publishing section of the crate settings:
Clicking this button leads to crates.io/docs/trusted-publishing, which will show this:
The GitHub Action itself does not exist yet (at least not under that official name). Should we keep this PR open in draft mode for now or merge it and update later if any changes are necessary?
Related:

Add Trusted Publishing documentation

---

crates/crates_io_database/Cargo.toml

This change makes `cargo check --package crates_io_database` pass without any issues.

database: Enable `postgres` feature of `diesel-async`

---

crates/crates_io_test_db/README.md
crates/crates_io_worker/README.md

Not sure why CI didn't catch this earlier... :-/

prettier: Fix markdown issues

---

app/components/crate-sidebar.hbs
app/components/crate-sidebar.js
app/components/crate-sidebar.module.css
app/models/version.js
app/utils/purl.js
tests/models/version-test.js
tests/utils/purl-test.js

This PR adds [Package URL (PURL)](https://github.com/package-url/purl-spec) support to crate pages, enabling better integration with software supply chain and security tools. PURLs follow the format `pkg:cargo/{name}@{version}` and are displayed in the sidebar metadata section with click-to-copy functionality.
This is a frontend-only implementation that generates PURLs client-side using existing crate data. The display uses ellipsis overflow with a tooltip showing the full PURL.
On `staging.crates.io` (and everywhere that is no `crates.io` itself) it will append a `repository_url` qualifier (see https://github.com/package-url/purl-spec/issues/215).

Add Package URL (PURL) display to crate sidebar

---

.github/workflows/ci.yml

This puts less pressure on our CI caches since we don't need to cache the cargo install results anymore. This should also improve #11436, by allowing us to install Typst and oxipng via binstall.

CI: Use `cargo-binstall` for pre-compiled binary installation

---

src/tests/krate/publish/rate_limit.rs

This pull request fixes a flaky rate limit test by replacing unreliable thread sleep with direct database timestamp manipulation. The test was previously using `thread::sleep()` to wait for the rate limit to expire, which could cause intermittent failures in CI environments with timing variations. The solution directly resets the rate limit timestamp in the database, making the test deterministic and more reliable.

tests: Fix rate limit test flakiness by using database reset instead of sleep

---

e2e/routes/crate/settings.spec.ts

In some cases the snapshot was showing an empty page because while the URL had already changed, the content hadn't yet been rendered. By moving the snapshot after the assertions we can ensure that the page content has rendered by the time we take the snapshot.

e2e/crate/settings: Move Percy snapshot to fix snapshot flakiness

---

src/worker/jobs/trustpub/delete_jtis.rs

It's a job without any parameters that always cleanups tokens expired to the moment of running. Therefore, there's no reason to enqueue another one if the existing hasn't been executed yet.

Dedupe expired JTI deletion job

---

app/styles/crate/settings/new-trusted-publisher.module.css
app/templates/crate/settings/new-trusted-publisher.hbs

This PR slightly adjusts the Trusted Publishing config creation form. It adds examples to the filename input help text and slightly tweaks the layout to be a bit easier on the eyes on large screens.
Related:
- https://github.com/bytecodealliance/wasm-component-ld/pull/69#issuecomment-3032604217

trustpub: Improve config creation form

---

script/import-database-dump.sh
script/reset-sequences.sql

This automatically resets all `id` column sequences to the maximum `id` column value of the corresponding table after the data was imported.
Closes https://github.com/rust-lang/crates.io/pull/10204

db-dump: Reset sequences after data import

---

crates/crates_io_og_image/examples/test_generator.rs
crates/crates_io_og_image/src/lib.rs

Turns out some GitHub users have JPEG avatars instead of PNG and that confuses Typst. This PR fixes the issue by detecting the image type and saving them with the correct filename extensions.

og_image: Add support for JPEG avatars

---

crates/crates_io_og_image/src/lib.rs
crates/crates_io_og_image/template/og-image.typ

Some of our users appear to have avatar URLs like `https://private-avatars.githubusercontent.com/u/123095?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MzQ1MjkwMjAsIm5iZiI6MTczNDUyNzgyMCwicGF0aCI6Ii91LzEyMzA5NSJ9.qPHLwlZHda1ApuLzL5FfADxTiOsNjpp85IGvljRx9bM&v=4&s=64` which result in 404 errors when attempting to download them. This commit adjusts the code to log a warning in such cases and then show the author name without an avatar instead.

og-image: Handle 404 errors from avatar downloads gracefully

---

src/worker/jobs/generate_og_image.rs

The TTL on OG images is low enough that we can ignore invalidation errors. This is particularly relevant for backfilling, where we need to generate a large number of images in short succession.

og_image: Ignore CDN invalidation errors

---

src/bin/crates-admin/backfill_og_images.rs
src/worker/jobs/generate_og_image.rs

The backfill operation on production caused a lot of CDN validations, leading to rate limiting from CloudFront, which then prevented sparse index updates. This PR ensures that the backfill operation runs without CDN invalidations, to not block the more important background jobs from finishing.

og_image: Skip CDN invalidations for backfill operation

---

crates/crates_io_og_image/src/lib.rs
src/worker/jobs/generate_og_image.rs

We should probably change the rest to `crate.name` instead, but let's do that in a dedicated step to not confuse downstream tools.

tracing: Consistently use `krate.name` field naming convention

---

package.json
pnpm-lock.yaml

see https://github.com/advisories/GHSA-968p-4wvh-cqc8

Force `@babel/runtime` to 7.27.6 to resolve security vulnerability

---

src/worker/jobs/delete_crate.rs

worker/delete_crate: Delete OG images when deleting crates

---

app/components/version-list/row.hbs
app/components/version-list/row.js
app/controllers/crate/rebuild-docs.js
app/router.js
app/routes/crate/rebuild-docs.js
app/styles/crate/rebuild-docs.module.css
app/templates/crate/rebuild-docs.hbs
e2e/acceptance/rebuild-docs.spec.ts
e2e/acceptance/versions.spec.ts
tests/acceptance/rebuild-docs-test.js
tests/acceptance/versions-test.js

Resolves https://github.com/rust-lang/crates.io/discussions/11499

Replace rebuild docs button with dedicated confirmation page

---

app/styles/crate/settings/index.module.css

crate/settings: Improve "Trusted Publishing" section styling on mobile devices

---

app/controllers/crate/settings/new-trusted-publisher.js
app/templates/crate/settings/index.hbs
app/templates/crate/settings/new-trusted-publisher.hbs

see commit messages 😉 
This should help a bit when filling out the form because it's easier to quickly find the right file name in the repository.

crate/settings: Add links back to the repository

---

src/controllers/trustpub/tokens/exchange/mod.rs
src/controllers/trustpub/tokens/exchange/tests.rs

Resolves https://github.com/rust-lang/crates.io/issues/11564

trustpub: Improve token exchange error messages

---

crates/crates_io_database/src/models/krate.rs

This does not appear to be needed (anymore?).

database/models/krate: Remove unused `QueryableByName` trait

---

.github/renovate.json5
triagebot.toml

We can let triagebot handle the labeling instead of duplicating the logic for just the renovatebot PRs.

renovatebot: Remove label assignments

---

app/components/rendered-html.hbs
app/modifiers/highlight-syntax.js
app/modifiers/render-mermaids.js
app/modifiers/update-source-media.js
tests/components/rendered-html-test.js

This pull request updates the `RenderedHtml` component and its related modifiers to ensure that they properly react to changes in the HTML content, such as rerunning syntax highlighting and diagram rendering when the input changes. It also adds tests to verify these behaviors.
Resolves https://github.com/rust-lang/crates.io/issues/11790

components/rendered-html: Fix modifier triggering on `@html` changes

---

app/serializers/crate.js
e2e/bugs/11772.spec.ts
tests/bugs/11772-test.js

The `GET /summary` call correctly initialized the `newest_version` fields of the crates, but when navigating to the crate page, the `GET /crate/foo` call by default uses an `include` query parameter that excludes the `newest_version` field from being loaded on the backend, which causes it to be returned with a value of `0.0.0` (for legacy reasons). This then reset the field on the model, causing it to be displayed incorrectly when navigating back to the front page.
This commit fixes the issue by adjusting the crate serializer to ignore `0.0.0` values for `max_version` and `newest_version`, so that they won't override previously loaded values.
Resolves https://github.com/rust-lang/crates.io/issues/11772

Fix unintentional `crate.newest_version` reset

---

src/bin/crates-admin/main.rs
src/bin/crates-admin/render_og_images.rs

The initial backfill is finished, but this tool can still be useful to manually trigger rerenders, so we will rename to reflect that new purpose.
This PR also adds a new `--skip-invalidation` option, that now defaults to not skipping the invalidation (previously we skipped it for the initial backfill).

admin: Rename `backfill-og-images` to `render-og-images`

---

src/bin/crates-admin/render_og_images.rs

There is no need for the duplicate prefix filter. We can just reuse the `build_query()` fn by moving the `.offset()` call out of it.

admin/render_og_images: Simplify query construction

---

src/bin/crates-admin/render_og_images.rs

Using `.order()` in `.count()` queries appears to make Diesel unhappy...

admin/render_og_images: Fix query construction

---

ember-cli-build.js

While this works and can be beneficial, it conflicts with our Content Security Policy (https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP) setting in production, so let's avoid the inlining for now until we can figure out a way to improve compatibility between the two.
This is how the token expiry dropdown is supposed to look like:
and this is how it currently looks like in production:
This PR fixes the issue :)

webpack: Avoid SVG file inlining

---

app/controllers/settings/tokens/new.js
app/utils/token-scopes.js
crates/crates_io_database/src/models/token/scopes.rs
e2e/routes/settings/tokens/new.spec.ts
src/controllers/trustpub/github_configs/create/mod.rs
src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__legacy_token_auth-2.snap
src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__token_auth_with_trusted_publishing_scope-2.snap
src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__token_auth_with_wildcard_crate_scope-2.snap
src/controllers/trustpub/github_configs/create/tests.rs
src/controllers/trustpub/github_configs/delete/mod.rs
src/controllers/trustpub/github_configs/delete/snapshots/crates_io__controllers__trustpub__github_configs__delete__tests__legacy_token_auth-2.snap
src/controllers/trustpub/github_configs/delete/snapshots/crates_io__controllers__trustpub__github_configs__delete__tests__token_auth_with_trusted_publishing_scope-2.snap
src/controllers/trustpub/github_configs/delete/snapshots/crates_io__controllers__trustpub__github_configs__delete__tests__token_auth_with_wildcard_crate_scope-2.snap
src/controllers/trustpub/github_configs/delete/tests.rs
src/controllers/trustpub/github_configs/list/mod.rs
src/controllers/trustpub/github_configs/list/snapshots/crates_io__controllers__trustpub__github_configs__list__tests__legacy_token_auth-2.snap
src/controllers/trustpub/github_configs/list/snapshots/crates_io__controllers__trustpub__github_configs__list__tests__token_auth_with_trusted_publishing_scope-2.snap
src/controllers/trustpub/github_configs/list/snapshots/crates_io__controllers__trustpub__github_configs__list__tests__token_auth_with_wildcard_crate_scope-2.snap
src/controllers/trustpub/github_configs/list/tests.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot-2.snap
src/tests/routes/me/tokens/create.rs
src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_trusted_publishing_scope-2.snap
src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_trusted_publishing_scope-3.snap
tests/routes/settings/tokens/new-test.js

This PR adds a new `trusted-publishing` endpoint scope to our API tokens. If this scope is used, then the API token can be used to create, list and delete Trusted Publishing configurations for the configured crates. As with the other scopes, a legacy token without any scopes can also be used for the same purpose now.
This change will allow our users with larger workspaces to automate the setup of creating Trusted Publishing configurations, which should help with adoption of Trusted Publishing by power users.

Add API token support to endpoints for managing Trusted Publishing configurations

---

crates/crates_io_database/src/models/krate.rs
src/controllers/trustpub/emails.rs
src/controllers/trustpub/github_configs/create/mod.rs
src/controllers/trustpub/github_configs/delete/mod.rs
src/controllers/trustpub/mod.rs
src/controllers/trustpub/snapshots/crates_io__controllers__trustpub__emails__tests__config_created_email-2.snap
src/controllers/trustpub/snapshots/crates_io__controllers__trustpub__emails__tests__config_created_email_different_recipient-2.snap
src/controllers/trustpub/snapshots/crates_io__controllers__trustpub__emails__tests__config_created_email_with_environment-2.snap
src/controllers/trustpub/snapshots/crates_io__controllers__trustpub__emails__tests__config_deleted_email-2.snap
src/controllers/trustpub/snapshots/crates_io__controllers__trustpub__emails__tests__config_deleted_email_different_recipient-2.snap
src/controllers/trustpub/snapshots/crates_io__controllers__trustpub__emails__tests__config_deleted_email_with_environment-2.snap

This improves type safety for these templates since the passed in template context is now less dynamic. This PR also adds a couple of rendering tests for these emails to ensure that they match our expectations.

trustpub: Extract `ConfigCreatedEmail` and `ConfigDeletedEmail` structs

---

crates/crates_io_trustpub/src/keystore/impl.rs

This makes the `get_oidc_key()` fn a little easier to comprehend :)

trustpub/keystore: Extract `Cache::update()` and `Cache::recently_updated()` fns

---

Cargo.lock
crates/crates_io_trustpub/Cargo.toml
crates/crates_io_trustpub/examples/load_jwks.rs
crates/crates_io_trustpub/src/keystore/mod.rs

This makes it easier to manually test the JWKS loading code against the real world servers of GitHub (and other providers in the future)

trustpub: Implement `load_jwks` example binary

---

src/controllers/trustpub/tokens/exchange/github_tests.rs

trustpub/tokens/exchange: Improve tests

---

Cargo.lock
Cargo.toml
crates/crates_io_session/Cargo.toml

v0.11.0 was yanked due to an unintentional breaking change that didn't affect us

Downgrade axum-extra to v0.10.3

---

app/components/rendered-html.gjs

This PR fix `<picture>` element not follow colorPreference, see my crate [simpleicons-rs](https://crates.io/crates/simpleicons-rs), it has a <picture> element in front of README, and I prepare two color pictures for it:
```
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/cscnk52/simpleicons-rs/raw/refs/heads/main/assets/img/simpleicons-rs-banner-dark.png" />
<source media="(prefers-color-scheme: light)" srcset="https://github.com/cscnk52/simpleicons-rs/raw/refs/heads/main/assets/img/simpleicons-rs-banner-light.png" />
</picture>
```
It should follow crates.io theme to change, but not.
After attach debug to it, I found just wrong order of `colorPreference` and `input`, just swap them to fix.
After fix, it looks good.
Related to …

Fix <picture> sources not follow color scheme preference

---

app/templates/crate/delete.gjs
app/templates/policies/index.gjs
src/controllers/krate/delete.rs
src/snapshots/crates_io__openapi__tests__openapi_snapshot-2.snap

as discussed in our team meeting
- https://github.com/rust-lang/crates.io/discussions/11901

Raise crate deletion downloads limit to 1000/month

---

app/components/support/crate-report-form.css
app/components/support/crate-report-form.gjs
e2e/acceptance/support.spec.ts
tests/acceptance/support-test.js

This better reflects our [security policy](https://crates.io/policies/security), which treats these cases slightly different. With this PR, malicious code reports are also sent to security@rust-lang.org to improve response times. Clicking the vulnerability checkbox now shows an additional help text suggesting to the user to first contact the crate author, file a RustSec report and read our security policy.
/cc @rust-lang/security @rust-lang/wg-secure-code

support/crate-report-form: Split `security` checkbox into `malicious-code` and `vulnerability`

---

crates/crates_io_database/src/models/action.rs
crates/crates_io_database/src/models/category.rs
crates/crates_io_database/src/models/cloudfront_invalidation_queue.rs
crates/crates_io_database/src/models/keyword.rs
crates/crates_io_database/src/models/team.rs
crates/crates_io_database/src/models/trustpub/gitlab_config.rs
src/controllers/category.rs
src/controllers/crate_owner_invitation.rs
src/controllers/keyword.rs
src/controllers/summary.rs
src/controllers/team.rs
src/controllers/trustpub/tokens/exchange/gitlab_tests.rs
src/rate_limiter.rs

We were relying on the implicit column order in many places, which can lead to subtle bugs. The `Selectable` trait ensures that fields are filled according to their corresponding column name.
This should unblock us from being able to use `column_sorting = name` with `diesel` (see https://github.com/rust-lang/crates.io/pull/12044#issuecomment-3375453049)

Add missing `.select()` and `.returning()` calls

---

.github/renovate.json5

`diesel_full_text_search` and `diesel_migrations` use underscores, but for some reason `diesel-async` uses hyphens. This adds the pattern to the renovate group, so that renovate updates these packages together :)
In other words: it should automatically merge https://github.com/rust-lang/crates.io/pull/12033 into https://github.com/rust-lang/crates.io/pull/11890

renovate: Include `diesel-` prefixed package in "diesel packages" group
